this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "pies/pulg",
        sqm: "m²",
        acre: "ac",
        hectare: "ha",
        sqft: "pies²",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gal",
        lpm: "lpm",
        lph: "lph",
        m3h: "m³/h",
        USgpm: "gal/min",
        USgph: "gal/hora",
        deg: "°",
        pcs: "uds",
        pcsDot: "uds.",
        pcsShort: "uds.",
        percent: "%",
        in_Alt: "pulg.",
        mps: "m/s",
        kph: "km/h",
        degreesCentigrade: "°C",
        mmph: "mm/h",
        mmp24h: "mm/día",
        inph: "pulg/h",
// no convertible
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Cajón automático",
        chooseSprinkler: "Elegir boquilla:",
        auto: "Ajuste automático",
        waterSource2row: ["Agua", "Entrada"],
        setLineLength: "Establecer longitud de línea (mm):",
        setPressure: "Establecer presión dinámica esperada en boquillas (bar):",
        setMaxFlow: "Establecer flujo máximo de agua (l/min):",
        controllerShort: "C",
        sensorShort: "S",
        action_activateEraser: "Activar borrador",
        action_deactivateEraser: "Desactivar borrador",
        action_boolUnite: "Unir",
        action_boolIntersect: "Intersectar",
        action_boolSubtract: "Restar",
        action_boolExclude: "Excluir",
        action_changeSprayBody: "Establecer rociador",
        action_changeVariant: "Establecer variante",
        action_changeImgVariant: "Establecer variante",
        action_changeType: "Establecer tipo",
        action_addConsumers: "Agregar consumidores",
        action_drawBranches: "Agregar ramas",
        action_editLine: "Editar segmentos",
        action_drawCircles: "Dibujar círculos",
        action_detachAll: "Desvincular todo",
        action_drawBrush: "Dibujar pincel",
        action_editBrush: "Editar pincel",
        action_changeBrushSize: "Tamaño del pincel",
        action_booleans: "Operaciones booleanas",
        action_intoPoly: "Convertir en polígono",
        action_intoBrush: "Convertir en pincel",
        action_activateRotation: "Rotar",
        action_deactivateRotation: "Inmóvil",
        action_markZones: "Representación de zonas",
        action_unmarkZones: "Eliminar marcado",
        action_sprNames: "Nombres de rociadores",
        action_noSprNames: "Eliminar nombres",
        action_lockItem: "Bloquear",
        action_unlockItem: "Desbloquear",
        Circle: "Círculo",
        Triangle: "Triángulo",
        BushForm: "Arbustos",
        BushForm1: "Arbustos 1",
        BushForm2: "Arbustos 2",
        BushForm3: "Arbustos 3",
        Square: "Cuadrado",
        noShadow: "Ninguno",
        standardShadow: "Estándar",
        noArrows: "Ninguno",
        startArrow: "Al principio",
        endArrow: "Al final",
        bothArrows: "Ambos lados",
        normalSizeSide: "Normal",
        invertedSizeSide: "Invertido",
        strMiter: "Miter",
        strRound: "Redondo",
        strBevel: "Bisel",
        strSquare: "Cuadrado",
        strButt: "Butt",
        FWnormal: "Normal",
        FWbold: "Negrita",
        FWitalic: "Cursiva",
        FWbolditalic: "Negrita cursiva",
        FJleft: "Izquierda",
        FJright: "Derecha",
        FJcenter: "Centro",
        rzwHeight: "Altura"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Selector múltiple",
        //----Drawing
        selectPoly: "No se han seleccionado elementos",
        //----Sprinkling
        selectSprink: "No se han seleccionado elementos",
        lpNozzler: "Adjuntando consumidores de agua",
        dl16CircDrawer: "Dibujo de círculos de goteo de 16mm",
        dl16sDrawer: "Dibujo de cubierta de goteo de 16mm",
        dl17CircDrawer: "Dibujo de círculos de goteo de 17mm",
        dl17sDrawer: "Dibujo de cubierta de goteo de 17mm",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Distancia total",
        type: "Tipo",
        variant: "Variante",
        area: "Área",
        perimeter: "Perímetro",
        curveLength: "Longitud",
        treeDiameter: "Diámetro de árbol",
        bushDiameter: "Diámetro de arbusto",
        nozTypes: "Tipos disponibles",
        nozType: "Tipo",
        sprBod: "Cuerpo de rociador",
        rad: 'Radio',
        angle: 'Ángulo',
        reducedBy: 'Reducido por',
        consump: 'Consumo',
        pressure: 'Presión',
        coverSize: 'Cobertura',
        maxFlow: 'Flujo máximo de agua',
        pipesNum: "Tubos conectados",
        pipeType: "Tipo",
        pipeLength: "Longitud",
        wireLength: "Longitud",
        valvesManifNum: "Manifold de válvulas",
        valvesNum: "Válvulas",
        propDiam: "Diámetro adecuado",
        curDiam: "Diámetro del dibujo",
        outsNum: "Consumidores de agua",
        flow: "Flujo de agua",
        precipRate: "Tasa de precipitación",
        totalPrecipArea: "Cobertura total",
        precipRateShort: "Precip.",
        coveredArea: "Área",
        microClimateInd: "M/Clima",
        soilTypeInd: "Tipo de suelo",
        zoneSlopeInd: "Inclinación",
        maxInfiltrationRate: "Tasa de infiltración",
        waterDemand: "Demanda de agua",
        numOfRuns: "Ejecuciones diarias",
        timePerRun: "Tiempo por ejecución",
        dailyConsumption: "Consumo diario",
        dripsNum: "Líneas de goteo conectadas",
        dripType: "Tipo de goteo",
        dripRowsStep: "Separación entre filas",
        dripRowsAngle: "Ángulo de filas",
        cntrType: "Tipo de controlador",
        sensType: "Tipo de sensor",
        zonesNum: "Zonas controladas",
        trenchWidth: "Ancho",
        trenchDepth: "Profundidad",
        trenchVolume: "Volumen",
        insetDiam: "Diámetro",
        insetLength: "Longitud",
        insetVar: "Material",
        itemsCount: "Cantidad",
        insetDepth: "Profundidad",
        zoneName: "Nombre de la zona",
        valveName: "Caja de válvula",
        itemAlias: "Alias",
//MULTISELECTOR
        itemsSelected: "Seleccionados",
        totalArea: "Área total",
        totalPerimeter: "Perímetro total",
        totalLength: "Longitud total",
        totalVolume: "Volumen total",
        totalConsumption: "Consumo total",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Polígono no válido",
        isSelfCrossing_false: "Polígono válido",
        isConnected_true: "Conectado",
        isConnected_false: "No conectado",
        isWired_true: "Cableado",
        isWired_false: "Sin cableado",
        isDripZone_true: "Zona de goteo",
        isDripZone_false: "",
        isSprinklerZone_true: "Zona de rociadores",
        isSprinklerZone_false: "",
        isOverloaded_true: "¡SOBRECARGA!",
        isOverloaded_false: "",
        isUnderpressured_true: "Presión baja",
        isUnderpressured_false: "",
        isOverpressured_true: "Presión alta",
        isOverpressured_false: "",
        isLocked_true: "Bloqueado",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Acero inoxidable",
        "High speed": "Alta velocidad",
        "Opposing nozzle": "Opposing nozzle",
        "Plastic": "Plástico",
        "MPR Nozzles": "Boquillas MPR",
        "Rotary Nozzles": "Boquillas rotativas",
        Nozzles: "Boquillas",
        "Bubbler nozzles": "Boquillas burbujeantes",
        "Multi-stream": "Multichorro",
        "Dual-stream": "Doble chorro",
        "Stream Nozzles": "Boquillas de chorro",
        "Short Radius Nozzles": "Boquillas de corto alcance",
        "Pressure compensating": "Compensador de presión",
        "Adjustable flood": "Inundación ajustable",
        Adjustable: "Ajustable",
        Fixed: "Fijo",
        "Fixed Arc": "Arco fijo",
        "Strip Pattern": "Patrón de franjas",
        "Drip line": "Línea de goteo",
        "Drip cover": "Cobertura de goteo",
        "16mm": "16mm",
        "17mm": "17mm",
        "emitter": "Con emisores",
        "noemitter": "Sin emisores",
        "Root zone watering": "Riego de zona de raíces",
        Lateral: "Lateral",
        Main: "Principal",
        Trench: "Zanja",
        hdpe: "HDPE",
        pvc: "PVC",
        Controller: "Controlador",
        Sensor: "Sensor",
        Wiring: "Cableado",
        IrrigateMarks: "Zonas de riego",
        Surface: "Superficie",
        Lawn: "Césped",
        Bed: "Cama",
        Shrubs: "Arbustos",
        Path: "Camino",
        Concrete: "Concreto",
        Sand: "Arena",
        Water: "Agua",
        Bedding: "Relleno",
        Flower: "Flor",
        Herbal: "Hierba",
        geographic: "Geográfico",
        sizeMark: "Dimensiones",
        scalingBar: "Barra de escala",
        loCurves: "Líneas",
        texts: "Textos",
        staticText: "Texto estático",
        dynamicText: "Texto dinámico",
        stampText: "Texto de sello",
        stampTextDefault: "Texto",
        stampTextgr1: "Definición de documento",
        stampTextgr2: "Celda de dirección",
        stampTextgr3: "Nombre del sitio",
        stampTextgr4: "Nombre del dibujo",
        stampTextgr9: "Información de la organización",
        stampTextgr6t: "Etapa",
        stampTextgr7t: "Página",
        stampTextgr8t: "Páginas",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Cap.",
        stampTextgr15t: "Prtcp.",
        stampTextgr16t: "Página",
        stampTextgr17t: "# Doc.",
        stampTextgr18t: "Firma",
        stampTextgr19t: "Fecha",
        stampTextgr20t: "Inv. orig. #",
        stampTextgr21t: "Firma y fecha",
        stampTextgr22t: "Inv. reempl. #",
        inserts: "Sleeves de tubería",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Mostrar gestor de capas",
        hideLM: "Ocultar gestor de capas",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Sin nombre",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Exportando diseño",
        successExporting: "Exportado correctamente",
        failExporting: "Error al exportar",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Límite diario alcanzado</a>",
        exportingLimit: "Límite: ",
        exportingLeft: "Restante hoy: ",
        pdfExportingPopUpBlocked: "Tu navegador bloqueó la ventana emergente. Por favor, permite las ventanas emergentes para este sitio para obtener el archivo .PDF",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Rosca emergente",
        tt_group_MT: "Macho",
        tt_group_FT: "Hembra",
        tt_riserHeight: "Altura de la rosca",
        tt_pressureReg: "Regulador de presión",
        tt_checkValve: "(Con válvula de retención)",
        tt_home: "Inicio",
        tt_prev: "Anterior",
        tt_next: "Siguiente",
        tt_end: "Fin",
        tt_add: "Agregar",
        tt_clone: "Clonar",
        tt_remove: "Eliminar",
        tt_rename: "Renombrar",
        tt_addToFav: "Agregar a Favoritos",
        tt_remFromFav: "Eliminar de Favoritos",
        tt_presets: "Preajustes"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "N",
        S: "S",
        E: "E",
        W: "W",
        //conventions
        sprinklers: "Aspersores",
        dripStarts: "Inicio de goteo",
        rzwLayer: "Riego zona raíz",
        dripLines: "Línea de goteo",
        valvesLayer: "Manifold de válvulas",
        waterSources: "Fuente de agua",
        quickCoupLayer: "Acoplamiento rápido",
        controllers: "Controlador",
        sensorsLayer: "Sensor",
        mainPipes: "Tubería principal",
        lateralPipes: "Tubería lateral",
        lateralPipes_sprinklerZone: "Zona (Aspersores)",
        lateralPipes_dripZone: "Zona (Línea de goteo)",
        lateralPipes_rzwZone: "Zona (Riego zona raíz)",
        lateralPipes_emptyZone: "Zona (Sin consumidores)",
        trenchesLayer: "Zanjas",
        insetsLayer: "Insetos",
        wiresLayer: "Cableado",
        senswiresLayer: "Cableado de sensores",
        surfaces: "Superficies",
        ldItemsLayer: "Plantas",
        covers: "Cobertura",
        nameplates: "Información de los consumidores",
        oreolas: "Marcas de los consumidores",
        pipeInfo: "Información de las tuberías",
        lines: "Líneas",
        overlays: "Capas superpuestas",
        stampLayer: "Marco",
        stampTexts: "Textos de sello",
//zonesTable
        zoneType: "Tipo de zona",
        color: "Color",
        consumers: "Consumidores",
        waterFlow: "Flujo",
        sprinklerZone: "Aspersión",
        dripZone: "Goteo",
        rzwZone: "Riego zona raíz",
        emptyZone: "Sin consumidores",
        specifyDiagonal: "Por favor, especifique el tamaño diagonal de su monitor en pulgadas",
//sprinklersTable
        consType: "Tipo",
        consName: "Nombre",
        zoneNum: "Zona",
        sector: "Sector",
        radius: "Radio",
        reducedBy: "Reducido por",
        nozzle: "Boquilla",
        rotor: "Rotor",
        bubbler: "Bubbler",
        bubblerNozzle: "Boquilla Bubbler",
//dripsTable
        catId: "Cat.ID",
        brand: "Marca",
        emitterStep: "Paso",
        emitterFlow: "Flujo",
//layersManangerSpecific
        consumersGrp: "Consumidores",
        nodesGrp: "Nodos",
        wiresGrp: "Cables",
        pipesGrp: "Tuberías",
        landscapeGrp: "Paisaje",
        allTogether: "Todo junto"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Tipo",
        brand: "Marca",
        catid: "ID Cat.",
        title: "Título",
        units: "Unidades",
        amount: "Cantidad",
//predetermined
        dripLine: "Línea de goteo",
        dl16: "Línea de goteo 16mm",
        dl17: "Línea de goteo 17mm",
        dripStart: "Arranque de goteo",
        ds16: "Arranque de goteo 16mm",
        ds17: "Arranque de goteo 17mm",
        manifold_no_lps_issue: "Sin zonas conectadas",
        manifold_no_mp_issue: "No conectado a la línea principal",
        manifold_no_wr_issue: "Sin cable de control adjunto",
        //nodes-----------------------------------
        sprinkler_unattached: "¡ADVERTENCIA! Tiene ASPERSORES sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        drip_unattached: "¡ADVERTENCIA! Tiene elementos de riego por GOTEO sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        mains_unattached: "¡ADVERTENCIA! Tiene LÍNEAS PRINCIPALES sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        mains_empty: "¡ADVERTENCIA! Tiene LÍNEAS PRINCIPALES sin consumidores (no se mostrarán en la hoja de especificaciones finales)",
        laterals_unattached: "¡ADVERTENCIA! Tiene TUBERÍAS LATERALES sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        laterals_empty: "¡ADVERTENCIA! Tiene TUBERÍAS LATERALES sin consumidores (no se mostrarán en la hoja de especificaciones finales)",
        rzw_unattached: "¡ADVERTENCIA! Tiene elementos de RIEGO EN LA ZONA DE LA RAÍZ sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        sensors_unattached: "¡ADVERTENCIA! Tiene SENSORES sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        manifolds_unfinished: "¡ADVERTENCIA! Tiene MANIFOLDS incompletos (no se puede completar la configuración de válvulas)",
        control_wires_unattached: "¡ADVERTENCIA! Tiene CABLEADO DE CONTROL sin conectar",
        control_wires_empty: "¡ADVERTENCIA! Tiene CABLEADO DE CONTROL sin válvulas conectadas",
        cntr_wr_unattached: "Cableado de control",
        youCanSeeThemInTheDrawing: "Puedes ver cada elemento en el dibujo, presionando el 'ojo' a la izquierda de la fila del elemento",
        sprinkler_nozzleMT: "Nodo de rociador (Boquilla hembra)",
        sprinkler_nozzleFT: "Nodo de rociador (Boquilla macho)",
        "sprinkler_rotor1/2F": "Nodo de rociador (Rotor) 1/2\" hembra",
        "sprinkler_rotor3/4F": "Nodo de rociador (Rotor) 3/4\"",
        "sprinkler_rotor1F": "Nodo de rociador (Rotor) 1\"",
        "sprinkler_rotor1/2M": "Nodo de rociador (Rotor) 1/2\" macho",
        "sprinkler_bubbler1/2F": "Nodo de rociador (Bubbler)",
        sprinkler_bubblerNozzleMT: "Nodo de rociador (Boquilla de burbuja hembra)",
        sprinkler_bubblerNozzleFT: "Nodo de rociador (Boquilla de burbuja macho)",
        dripIrrigation16: "Riego por goteo (16mm)",
        dripIrrigation17: "Riego por goteo (17mm)",
        rootZoneWatering: "Sistema de riego de zona radicular",
        manifold: "Nodo de colector de válvulas",
        automation: "Nodo de automatización",
        mainPipes_hdpePE80SDR11: "Tubos principales HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Tubos principales HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Tubos principales HDPE SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Tubos laterales HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Tubos laterales HDPE SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Tubos laterales HDPE SDR 17.6",
        mainPipes_hdpeSDR9: "Tubos principales HDPE SDR 9",
        mainPipes_hdpeSDR11: "Tubos principales HDPE SDR 11",
        mainPipes_hdpeSDR136: "Tubos principales HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Tubos principales HDPE SDR 17",
        mainPipes_hdpeSDR176: "Tubos principales HDPE SDR 17.6",
        lateralPipes_hdpeSDR9: "Tubos laterales HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Tubos laterales HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Tubos laterales HDPE SDR 13.6",
        lateralPipes_hdpeSDR17: "Tubos laterales HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Tubos laterales HDPE SDR 17.6",
        mainPipes_pvcSCH40: "Tubos principales PVC SCH40",
        mainPipes_pvcSCH80: "Tubos principales PVC SCH80",
        lateralPipes_pvcSCH40: "Tubos laterales PVC SCH40",
        lateralPipes_pvcSCH80: "Tubos laterales PVC SCH80",
        wiring: "Cableado",
        qcv: "Válvulas de acoplamiento rápido",
        fixedCntr: "fijo",
        stand_aloneCntr: "autónomo",
        modularCntr: "modular",
        decoderCntr: "decodificador",
        inset: "Sleeve de tubería",
        insets: "Sleeves",
//-----------------------------------------
        novar: "sin variantes",
        choosevar: "elegir variante",
//element.types----------------------------
        nozzle: "Boquilla",
        rotor: "Rociador",
        rotorNozzle: "Boquilla para rociador",
        bubbler: "Difusor",
        bubblerNozzle: "Boquilla para difusor",
        rzw: "Sistema de riego de zona radicular",
        sprayBody: "Cuerpo de spray",
        outBarb: "Barb a boquilla",
        flexPipe: "Tubería flexible",
        sj: "Juntas giratorias",
        inBarb: "Barb a tubería",
        midSprinkPipeFitting: "Accesorio de tubería",
        endSprinkPipeFitting: "Accesorio final de tubería",
        midRZWPipeFitting: "Accesorio de tubería",
        endRZWPipeFitting: "Accesorio final de tubería",
        dripPipe: "Tubería de goteo",
        blindPipe: "Tubería ciega",
        dripTeeFitting: "Tee de goteo",
        dripCapFitting: "Tapa de goteo",
        dripCouplingFitting: "Acoplador de goteo",
        dripElbowFitting: "Codo de goteo",
        dripSpike: "Estaca de goteo",
        sprinklerZoneValve: "Válvula de zona de rociadores",
        emptyZoneValve: "Válvula sin consumidores",
        valveOutFitting: "Válvula a zona",
        dripZoneValve: "Válvula de zona de goteo",
        rzwZoneValve: "Válvula de riego en la zona de raíces",
        pressureReg: "Regulador de presión",
        filter_pressureReg: "Filtro con regulador de presión",
        controller: "Controlador",
        flowMeter: "Medidor de flujo",
        rainSensor: "Sensor de lluvia",
        soilSensor: "Sensor de suelo",
        freezeSensor: "Sensor de heladas",
        wrFreezeSensor: "Sensor de lluvia/heladas inalámbrico",
        windSensor: "Sensor de viento",
        solarSensor: "Sensor solar",
        flowSensor: "Sensor de flujo",
        weatherStation: "Estación meteorológica",
        solarPanel: "Panel solar",
        mainPipe: "Tubería principal",
        teeFitting: "T de unión",
        elbowFitting: "Codo",
        reducerFitting: "Reductor",
        lateralPipe: "Tubería lateral",
        capFitting: "Tapa",
        basicCable: "Cable básico",
        basicWire: "Cable básico",
        sensorCable: "Cable para sensor meteorológico",
        qcPlastic: "Válvula de acoplamiento rápido de plástico",
        qcMetal: "Válvula de acoplamiento rápido de metal",
        gateway: "Gateway",
        antExt: "Antenna extension",
        loramod: "LoRa modules",
        //typesOfAcessories
        hdpeCOR: "Tubería corrugada",
        expModule: "Módulo de expansión",
        rzwSleeve: "Manga de tela para riego en la zona de raíces",
        rwCap: "Tapa para agua reciclada",
        gutterMount: "Soporte para canal",
        delayRelay: "Relé de retardo",
        fctFlow: "T receptáculo FCT",
        fctBspAdap: "Adaptador para accesorio FCT",
        drainCheckValve: "Válvula de retención para drenaje",
        rwId: "Identificación para agua reciclada",
        vpc: "Tapa a prueba de vandalismo",
        inletFilter: "Filtro de entrada",
        wifiModule: "Módulo Wi-Fi",
        wallMount: "Soporte de pared",
        rwsSock: "Manga de tela para riego en la zona de raíces",
        rwsGrate: "Rejilla para RWS",
        npCover: "Cubierta para agua no potable",
        sprExt: "Extensión para aspersor",
        popUpToThread: "Adaptador para aspersor emergente",
        valveBox: "Caja de válvula",
        valveBoxExt: "Extensión para caja de válvula",
        qcPlasticKey: "Llave para válvula de cierre rápido (plástico)",
        qcPlasticElbFit: "Acople en codo para válvula de cierre rápido (plástico)",
        qcMetalKey: "Llave para válvula de cierre rápido (metal)",
        qcMetalElbFit: "Acople en codo para válvula de cierre rápido (metal)",
        qcMetalCapKey: "Llave de la tapa",
        insTape: "Cinta de aislamiento",
        wrConn: "Conector",
        shrinkTube: "Tubo termocontraíble",
        hcFrontPanel: "Panel frontal",
        ball_valve: "Válvula de bola",
        check_valve: "Válvula de retención",
        thread_manifold: "Colector",
        plastic_filter: "Filtro (plástico)",
        waterMeter: "Medidor de agua",
        rfModule: "Módulo de radio",
        largeAntenna: "Antena grande",
        wifiHub: "Hub WiFi",
        handRemoteKit: "Kit de control remoto",
        handRemote: "Control remoto",
        wifiBundleKit: "Kit de conexión WiFi",
//typesOfFittings
//drip
        barb_cap_8: "Cierre de extremo de riego por goteo",
        barb_elbow_PP: "Codo con barba",
        barb_elbow_PT: "Codo con barba y rosca",
        barb_tee_PPP: "T de barba",
        barb_coupling_PP: "Unión con barba",
        barb_cross_PPPP: "Cruz con barba",
        barb_cap_P: "Cierre de barba",
        barb_coupling_PT: "Unión con barba y rosca",
        barb_tee_PTP: "T de barba y rosca",
        barb_valve_PT: "Válvula con barba y rosca",
        barb_valve_PP: "Válvula con barba",
        twlc_elbow_PP: "Codo con cierre de rosca",
        twlc_tee_PPP: "T con cierre de rosca",
        twlc_coupling_PP: "Unión con cierre de rosca",
        twlc_cross_PPPP: "Cruz con cierre de rosca",
        twlc_cap_P: "Cierre con cierre de rosca",
        twlc_coupling_PT: "Unión con cierre de rosca y rosca",
        twlc_tee_PTP: "T con cierre de rosca y rosca",
        twlc_valve_PT: "Válvula con cierre de rosca y rosca",
        twlc_valve_PP: "Válvula con cierre de rosca",
        dl_valves: "Válvulas especiales",
        //pipe
        hdpeSDR9: "Tubo HDPE SDR 9",
        hdpeSDR11: "Tubo HDPE SDR 11",
        hdpeSDR136: "Tubo HDPE SDR 13.6",
        hdpeSDR17: "Tubo HDPE SDR 17",
        hdpeSDR176: "Tubo HDPE SDR 17.6",
        ldpeSDR9: "Tubo LDPE SDR 9",
        ldpeSDR11: "Tubo LDPE SDR 11",
        ldpeSDR136: "Tubo LDPE SDR 13.6",
        ldpeSDR17: "Tubo LDPE SDR 17",
        pvcSCH40: "Tubo PVC SCH40",
        pvcSCH80: "Tubo PVC SCH80",
        compress_elbow_PT: "Codo de compresión/rosca",
        compress_coupling_PT: "Acoplamiento de compresión/rosca",
        compress_tee_PTP: "T de compresión/rosca",
        compress_cap_P: "Tapón final de compresión",
        compress_elbow_PP: "Codo de compresión",
        compress_coupling_PP: "Acoplamiento de compresión",
        compress_tee_PPP: "T de compresión",
        compress_cross_PPPP: "Cruz de compresión",
        compress_single_clamp_saddle: "Abrazadera de compresión",
        compress_ballvalve_PP: "Válvula de bola de compresión",
        compress_ballvalve_PT: "Válvula de bola de compresión/rosca",
        customfit_elbow_PT: "Codo roscado personalizado",
        customfit_coupling_PT: "Unión roscada personalizada",
        customfit_tee_PTP: "T de rosca personalizada",
        customfit_cap_P: "Tapón final personalizado",
        customfit_elbow_PP: "Codo personalizado",
        customfit_coupling_PP: "Unión personalizada",
        customfit_tee_PPP: "T personalizada",
        customfit_cross_PPPP: "Cruz personalizada",
        customfit_single_clamp_saddle: "Silla de sujeción simple",
        customfit_ballvalve_PP: "Válvula de bola personalizada",
        customfit_ballvalve_PT: "Válvula de bola roscada personalizada",
        thread_nipple: "Niple",
        thread_coupling: "Acoplamiento",
        thread_mf_reducer: "Reductor macho/hembra",
        thread_mf_adapter: "Adaptador macho/hembra",
        thread_mf_bush: "Casquillo macho/hembra",
        thread_tee: "T hembra",
        thread_elbow: "Codo hembra",
        thread_mf_elbow: "Codo macho/hembra",
        thread_cap: "Tapa hembra",
        thread_plug: "Tapón macho",
        thread_union_nut: "Tuerca de unión",
        thread_cross: "Cruz",
        cable: "Cable",
        wire: "Cable eléctrico",
        // slip
        slip_single_clamp_saddle: "Silla de abrazadera simple (en tubería de PVC)",
        slip_elbow_PT: "Codo de deslizamiento/rosca",
        slip_coupling_PT: "Acople de deslizamiento/rosca",
        slip_tee_PTP: "T de deslizamiento/rosca",
        slip_cap_P: "Tapón final de deslizamiento",
        slip_elbow_PP: "Codo de deslizamiento",
        slip_coupling_PP: "Acople de deslizamiento",
        slip_tee_PPP: "T de deslizamiento",
        slip_cross_PPPP: "Cruz de deslizamiento",
        slip_ballvalve_PP: "Válvula de bola de deslizamiento",
        slip_ballvalve_PT: "Válvula de bola de deslizamiento/rosca",
//extendables
        arbitraryFittings: "Conexiones arbitrarias",
        dripStartAssembly: "Conjunto de inicio para goteo",
        intakeAssembly: "Conjunto de admisión",
        offtakeAssembly: "Conjunto de derivación para conexiones arbitrarias",
        numofvalves: "Número de válvulas: ",
        numofvalvesshort: "Válvulas: ",
        numofmanifs: "Número de colectores: ",
        intakePipeSize: "Tamaño de tubería de admisión: ",
        valveBoxes: "Cajas de válvulas",
        valveAccessories: "Accesorios de válvulas",
        oneValveAccessories: "Accesorios de válvulas",
        controllerAccessories: "Accesorios de controlador",
        sensorAccessories: "Accesorios de sensor",
        sprBodyAccessories: "Accesorios de cuerpo de rociado",
        rzwAccessories: "Accesorios de riego en la zona de la raíz",
        pipeStartFittings: "Conexiones arbitrarias de la tubería principal",
        qcAccessories: "Accesorios de válvulas Q/C",
        wiringAccessories: "Accesorios de cableado",
        pipeSize: "Tamaño de la tubería: ",
        endOfPipe: "(Posición final)",
        midOfPipe: "(Corte en la tubería)",
        emptyRender: [
            "Lo siento... no se ha encontrado ningún contenido",
            "No has completado completamente ninguno de los nodos de riego para ser renderizado"
        ],
        serviceFail: [
            "Lo siento... el servicio de renderización de especificaciones no está disponible en este momento",
            "Por favor, inténtalo de nuevo más tarde, cuando se establezca la conexión",
            "Ten en cuenta que la configuración que hayas hecho anteriormente se guardará"
        ],
        serviceTrialExpired: [
            "Lo siento... el servicio de renderización de especificaciones no está disponible para tu cuenta",
            "Eso significa que tu período de prueba ha terminado, y si quieres usar este servicio",
            "<a href='/account/subscription'>Puedes actualizar a una cuenta PRO</a>"
        ],
        serviceLimitReached: [
            "Has alcanzado el límite diario de renderización de hojas de especificaciones",
            "Para eliminar el límite en el número de renders de especificaciones por día",
            "<a href='/account/subscription'>Puedes actualizar a una cuenta PRO</a>"
        ],
        findInDrawing: "Mostrar en lienzo",
// IDS DE GRUPOS Y ELEMENTOS PARA LABORES
        labours_group_pipes: "Tuberías",
        labours_group_fittings: "Accesorios",
        labours_group_valveBoxes: "Cajas de válvulas",
        labours_group_wires: "Cableado",
        labours_group_sprinklers: "Aspersores",
        labours_group_rws: "Sistemas de riego por zona radicular",
        labours_group_sprinklerConnections: "Conexiones de aspersores",
        labours_group_drip: "Líneas y accesorios de riego por goteo",
        labours_group_manifolds: "Manifolds",
        labours_group_quickCoupling: "Acoplamientos rápidos",
        labours_group_controllers: "Controladores",
        labours_group_sensors: "Sensores",
        labours_group_trenches: "Zanjas",
        labours_group_insets: "Manguitos de tubería",
        labours_group_lawns: "Césped",
        labours_group_irrigatedArea: "Área regada",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
        MMM: ["\x01", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
        dddd: ["\x02", "Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
        ddd: ["\x03", "Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
        //buttonsCaps
        ok: "Aceptar",
        save: "Guardar",
        apply: "Aplicar",
        defaults: "Predeterminados",
        retry: "Reintentar",
        finish: "Finalizar",
        safeRestart: "Reinicio seguro",
        saveAndExit: "Guardar y salir",
        exit: "Salir",
        cancel: "Cancelar",
        rename: "Renombrar",
        idk: "No lo sé",
        getFile: "Obtener archivo",
        reset: "Restablecer",
        random: "Aleatorio",
//misc
        zoneNum: "Zona n.º",
        valveNum: "Caja de válvulas n.º",
        zonesColoring: "Representación de zonas",
        coversColoured: "Pintar cubiertas de aspersores",
        dripsColoring: "Coloración de líneas de goteo",
        dripsSameAsZonesColored: "Línea de goteo en el mismo color de su zona",
        //saveOflline
        saveOffline: [
            "Lo sentimos... se ha perdido la conexión",
            "Pero no se preocupe, puede continuar con su proyecto en modo fuera de línea.",
            "Mientras esté desconectado, todos sus guardados se almacenarán como un archivo de texto en la carpeta de descargas de su navegador.",
            "Luego podrá cargar la última versión de su dibujo en el servidor."
        ],
        restartOffline: [
            "Lo sentimos... se ha perdido la conexión",
            "Pero no se preocupe, su proyecto se guardó localmente en su computadora.",
            "Puede encontrarlo en la carpeta de descargas de su navegador.",
            "Si desea trabajar sin conexión, puede descargar una instancia sin conexión de la aplicación desde su panel en http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Lo sentimos... algo salió mal al cargar su proyecto",
            "Parece que su guardado anterior se corrompió de alguna manera.",
            "Pero no se preocupe, podemos repararlo.",
            "Su proyecto ahora se marcará como 'Roto' en su taller.",
            "Y nuestro personal técnico manejará esta situación lo antes posible."
        ],
        corruptedSavingFile: [
            "Lo sentimos... el archivo que está intentando cargar no es legible",
            "Pero no se preocupe, podemos repararlo.",
            "Todo lo que necesita hacer es enviar este archivo roto en el formulario de carga de archivos de su taller.",
            "Y luego intentaremos hacer que funcione de nuevo."
        ],
        ajaxReqFail: [
            "Lo sentimos... perdimos la conexión con el servidor",
            "Es imposible enviar/recibir datos en este momento",
            "Por favor, inténtelo de nuevo más tarde"
        ],
        critical: [
            "Lo sentimos... algo salió mal",
            "Pero no se preocupe, su dibujo está seguro, simplemente haga clic en el botón de reinicio seguro para continuar ..."
        ],
        fatal: [
            "Lo sentimos... algo salió mal",
            "Ayúdenos a mejorar nuestro servicio. Describa después de qué acciones de usuario se produjo este error",
            "Proporcione información aquí"
        ],
        areYouSure: [
            "Está a punto de cerrar este proyecto",
            "Tenga en cuenta que todos los cambios no guardados se perderán."
        ],
        pickAnotherCSVFile: "Elija otro archivo",
        csvFileTooBig: [
            "Tamaño máximo de archivo csv excedido",
            "Por razones de optimización, el tamaño máximo de archivo csv que se puede manejar está limitado a 4Mb"
        ],
        notAnCSV: [
            "Lo sentimos, este tipo de archivo no es compatible",
            "Formatos compatibles: .csv"
        ],
        pickAnotherImage: "Elija otra imagen",
        imageTooBig: [
            "Tamaño máximo de imagen excedido",
            "Por razones de optimización, el tamaño máximo de imagen que se puede manejar está limitado a 10Mb"
        ],
        notAnImage: [
            "Lo sentimos, este tipo de archivo no es compatible",
            "Formatos de imagen compatibles: .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "ACCIÓN RESTRINGIDA",
            "Esta acción no está permitida para la suscripción GRATUITA"
        ],
        goPro: 'IR A PRO',
        renameLayout: "Ingrese un nuevo nombre",
        areYouSureDeleteLayout: [
            "¡Atención! Esta acción no se puede deshacer",
            "¿Está seguro de que desea eliminar: ",
            "Eliminar"
        ],
        setUnderlaySize: [
            "Establecer la longitud de la línea que acaba de dibujar",
            "Ha ingresado un valor incorrecto. Por favor intente nuevamente"
        ],
        setMonitorDiagonal: [
            "Proporcione información sobre el tamaño diagonal de su monitor",
            "Ha ingresado un valor incorrecto. Por favor intente nuevamente"
        ],
        getSpecsTable: [
            "Establecer las preferencias de salida de especificaciones",
            "Agrupar el equipo por ",
            "Nodo", "Marca",
            "Establecer el tipo de archivo como ",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Ingrese el título",
            "Disposición #",
            "Guardar",
            "Guardando especificaciones",
            "Completado. Haga clic aquí para abrir",
            "Falló el guardado",
            "Actualizar disposiciones existentes",
            "Actualizar",
            "Actualizando disposiciones"
        ],
        exportLayoutsAsPdf: [
            "Elija las disposiciones a exportar",
            "archivos separados (en desarrollo)",
            "un álbum",
            "Exportar",
            "Exportar disposiciones en"
        ],
        differentSprGroups: [
            "Error al conectar diferentes tipos de consumidores de agua en esta tubería",
            "Según las normas de diseño de riego, no está permitido mezclar diferentes tipos de consumidores de agua o aspersores con diferentes tasas de precipitación en la misma zona"
        ],
        tooFarAwaySpr: [
            "Error al conectar consumidores",
            "Algunos de los consumidores están demasiado lejos de la tubería lateral para conectarse. La distancia máxima de conexión se puede configurar en el menú de preferencias."
        ],
        outlayerConfig: [
            "Configuración de la hoja de especificaciones"
        ],
        presetsMenu: {
            title: "Preajustes",
            titleTextboxLabel: "Título del Preajuste",
            descriptionTextboxLabel: "Descripción",
            applyButton: "<i class='far fa-check-circle'></i> Aplicar",
            defaultButton: "<i class='far fa-undo'></i> Predeterminado",
            removeButton: "<i class='far fa-trash'></i> Eliminar",
            updateButton: "<i class='far fa-sync'></i> Actualizar",
            createButton: "<i class='far fa-plus'></i> Crear nuevo",
            closeButton: "<i class='far fa-times'></i> Cerrar",
            favorites_drawing: "Herramientas Favoritas (Paisajismo)",
            favorites_sprinkling: "Herramientas Favoritas (Riego)",
            favorites_layouting: "Herramientas Favoritas (Diseño)",
            configs_drawing: "Configuración del Proyecto",
            configs_outlayer: "Configuración de la Hoja de Especificaciones",
        },
        newPresetItem: "Nuevo Preajuste",
        cL_alreadyConnected: [
            "No se pudo concatenar las líneas",
            "Estas líneas ya están conectadas a"
        ],
        cL_segOnElem: [
            "No se pudo concatenar las líneas",
            "No se puede conectar al segmento que está en"
        ],
        cL_strangeError: [
            "No se pudo concatenar las líneas",
            "Lo siento...La conexión falló"
        ],
        cL_misgrouping: [
            "No se pudo concatenar las líneas",
            "Estas líneas tienen consumidores que no se recomienda colocar en la misma zona. Si deseas conectarlas de todas formas, activa el 'Modo Inseguro' para la Agrupación de Rociadores en la configuración del proyecto"
        ],
        cL_valve: "Colector de válvulas",
        cL_waterSource: "Fuente de agua",
        cL_dripStart: "Inicio de goteo",
        cL_controller: "Controlador",
        cL_sensors: "Sensores",
        cL_valves: "Colector de válvulas",
        cL_notSameVariant: [
            "Fallo al concatenar las líneas",
            "Estas líneas tienen diferentes tipos",
            "Tipo de línea que se está dibujando actualmente",
            "Tipo de línea con la que deseas conectar"
        ],
        hasRestorableProject: [
            "Tienes datos no guardados para este proyecto",
            "Puedes restaurar el estado no guardado desde la instantánea tomada en"
        ],
        restoreProject: "Restaurar",
        imageLost: [
            "Lo sentimos, no podemos encontrar algunas de las imágenes de fondo en el servidor",
            "Esta imagen no se encontró:"
        ],
        cannotSaveBecauseOffline: [
            "Fallo al enviar la solicitud al servidor",
            "Sin conexión al servidor",
            "Verifique si tiene una conexión a internet",
            "Para no perder los datos, no cierre esta ventana e intente guardar los datos más tarde, cuando se establezca la conexión con el servidor",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "No se pudo guardar la solicitud",
            "Demasiados intentos de código inválidos",
            "Verifique si ingresó correctamente la dirección de correo electrónico e inténtelo de nuevo después de 30 segundos.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "No se pudo guardar la solicitud",
            "Dirección de correo electrónico ingresada incorrectamente",
            "Verifique si ingresó correctamente la dirección de correo electrónico e inténtelo de nuevo",
            "",
            "",
        ],
        designRequestCompleted: [
            "Su solicitud se creó / actualizó correctamente",
            "Enlace de edición", "copiar",
            "Enlace para ver", "copiar",
        ],
        designRequestContacts: [
            "Contact information",
            "Organization",
            "Name",
            "Email",
            "Phone",
            "Address",
            "Website",
        ],
        approveActionByCode: [
            "Confirmar acción",
            "Se envió un correo electrónico con un código de confirmación a la dirección de correo electrónico que proporcionó.",
            "Ingrese este código en el campo a continuación",
            "Ha ingresado un número inválido, inténtelo de nuevo"
        ],
        filterSelection_exclude: "Excluir de la selección",
        filterSelection_include: "Incluir en la selección",
        filterSelectionNames: {
            sprinklers: "Consumidores",
            sprinklers_nozzle: "Consumidores - Boquillas",
            sprinklers_rotaryNozzle: "Consumidores - Boquillas rotativas",
            sprinklers_rotor: "Consumidores - Rotores",
            sprinklers_bubbler: "Consumidores - Difusores",
            sprinklers_bubblerNozzle: "Consumidores - Boquillas difusoras",
            dripStarts: "Inicios de goteo",
            rzwLayer: "Riego en zona radicular",
            dripLines: "Tubos de goteo",
            valvesLayer: "Válvulas principales",
            waterSources: "Fuentes de agua",
            controllers: "Controladores",
            sensorsLayer: "Sensores",
            mainPipes: "Tuberías principales",
            lateralPipes: "Tuberías secundarias",
            trenchesLayer: "Zanjas",
            insetsLayer: "Insertos de tubería",
            wiresLayer: "Cables",
            senswiresLayer: "Cables de sensores",
            quickCoupLayer: "Acoples rápidos",
            surfaces: "Polígonos y líneas",
            ldItemsLayer: "Elementos del paisaje"
        },
//CONFIGURACIONES DE NODO DE RIEGO
        sprinklerNode: "Nodo de riego",
        fcType: "Tipo de conexión flexible",
        sj: "Junta de pivote",
        flexPipeBarbs: "Tubo flexible + conectores",
        minFlexPipeLength: "Longitud mínima de tubería flexible por conexión",
        midSprinkPipeFitting: "Conector de tubería",
        endSprinkPipeFitting: "Conector de final de tubería",
        single_clamp_saddle: "Silla de fijación",
        tee_PTP: "T de conexión con rosca hembra BSP",
        elbow_PT: "Codo con rosca hembra BSP",
        coupling_PT: "Adaptador con rosca hembra BSP",
        //MANIFOLD NODE CONFIGS
        manifoldNode: "Nodo del colector",
        valvesOutlay: "Conexión de válvulas",
        fold: "Plegado",
        unfold: "Desplegado",
        threadsNode: "Conexiones roscadas",
        threadTypes: "Tipos de roscas",
//CONFIGURACIONES DE NODOS DE AUTOMATIZACIÓN
        automationNode: "Nodo de automatización",
        controllerModules: "Los módulos de expansión de los controladores modulares son seleccionados:",
        controllerVoltage: "Voltaje de entrada del controlador:",
        230: "230 VAC",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automáticamente (mejor ajuste)",
        userModules: "Manualmente (como accesorios)",
//NODO DE RZW
        rzwNode: "Nodo de riego de la zona radicular",
        midRZWPipeFitting: "Conexión de empalme",
        endRZWPipeFitting: "Conexión final de tubería",
//NODO DE RIEGO POR GOTEO
        dripNode: "Riego por goteo",
        dripConnectionType: "Tipo de conexión de riego por goteo",
        dripLengthPrecision: "Dígitos después del punto decimal en la longitud de la tubería",
        dripTubingAddon: "Aditivo para tubería de riego por goteo",
        barb: "Conexiones de tubería de barra",
        twistLock: "Conexiones de bloqueo de giro",
        dripSpikesStep: "Paso del soporte de la línea de goteo",
        dripCrossFittingAble: "Capaz de conexión en cruz",
        pipesNode: "Sección de tuberías",
        hdpeConnectionType: "Tipo de conexión de tubería HDPE",
        pvcConnectionType: "Tipo de conexiones PVC",
        pipeAddon: "Aditivo de tubería para cada diámetro",
        pipeLengthPrecision: "Dígitos después del punto decimal en longitud de tubería",
        crossFittingAble: "Capaz de conexión cruzada",
        compress: "Conexiones de compresión",
        customfit: "Conexiones personalizadas",
        wiringNode: "Sección de cableado",
        exportNode: "Opciones de exportación",
        exportNumbersPrecision: "Dígitos después del punto decimal en números",
        basicWiringMethod: "Método de cableado de control",
        cableCoresArray: "Rango de número de núcleos de cable",
        noAutoWiring: "Agregar cableado manualmente",
        separateCableToManifold: "Cable múltiple separado para colectores",
        separateWireToValve: "Cable separado para válvula + cable común para colector",
        maxCableCores: "Máximo de núcleos de cable",
        verticalWiringAddon: "Aditivo vertical para cable de controlador",
        verticalSensWiringAddon: "Aditivo vertical para cable de sensor",
        wireAddon: "Aditivo de cable para cada tipo",
        wireLengthPrecision: "Dígitos después del punto decimal en longitud de cableado",
//DRAWER CONFIG
        drawerConfig: [
            "Configuración del proyecto"
        ],
//SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Consumidores",
        pressureDefinedBy: "La presión esperada en los consumidores es",
        allowReduceRotors: "Se permite reducir el radio de los rotores",
        radio_option_yes: "Sí",
        radio_option_no: "No",
        recommendedPressure: "Recomendada por el proveedor",
        userPressure: "Establecida por el usuario",
        expPressure: "Presión esperada en el consumidor",
        sprinklerGroupMode: "Agrupación de consumidores",
        safeSprGroupMode: "Modo estricto (agrupar solo los compatibles)",
        unsafeSprGroupMode: "Modo inseguro (¡ADVERTENCIA! Sin restricciones de agrupación)",
//CONFIGURACIÓN DE UNIDADES
        unitsConfig: "Unidades de medida",
        precisionStd: "Cifras decimales",
        unitsSystemGridAndRuler: "Sistema de unidades de medida para la cuadrícula y la regla",
        distanceUnits: "Distancia",
        distancePrecision: "Cifras decimales",
        sprinklerDistUnits: "Radio del aspersor",
        sprinklerDistPrecision: "Cifras decimales",
        areaUnits: "Área",
        areaPrecision: "Cifras decimales",
        volumeUnits: "Volumen",
        volumePrecision: "Cifras decimales",
        waterFlowUnits: "Caudal de agua",
        waterFlowPrecision: "Cifras decimales",
        pressureUnits: "Presión",
        pressurePrecision: "Cifras decimales",
        velocityUnits: "Velocidad",
        velocityPrecision: "Cifras decimales",
        precipRateUnits: "Tasa de precipitación",
        precipRatePrecision: "Cifras decimales",
//CONFIGURACIÓN DE PROPIEDADES DE ZONA
        climateConfig: "Cálculo del tiempo de riego",
        lawnCultureType: "Tipo de césped",
        coolLoving: "De clima fresco",
        warmLoving: "De clima cálido",
        climateTemp: "Temperatura media del verano",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Humedad media del verano",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Microclima de la zona <i class='far fa-question-circle'></i>",
        microClimateTooltip: "Suave\n" +
            "Áreas de riego que están a la sombra, protegidas del viento y alejadas de objetos secos y calentados\n" +
            "\n" +
            "Normal\n" +
            "Lugares en el paisaje donde se representan las condiciones microclimáticas: la presencia de\n" +
            "edificios, aceras y caminos, sombra, etc. no afectan significativamente los valores de\n" +
            "evapotranspiración\n" +
            "\n" +
            "Áspero\n" +
            "Refleja condiciones que impiden el crecimiento de las plantas y fácilmente se traduce en un estado de estrés si la planta no es regada adecuadamente. Puede ser un lugar abierto, bajo el sol ardiente, en cercanía a pasillos, edificios u otras estructuras del paisaje, reflejando la luz de vidrio o elementos del paisaje que absorben el calor, o puede ser un lugar ventoso.",
        gentleMicroClimate: "Suave",
        normalMicroClimate: "Normal",
        toughMicroClimate: "Áspero",
        soilType: "Composición del suelo en las zonas",
        sand: "Arenoso",
        sandyLoam: "Franco arenoso",
        lightLoam: "Franco",
        mediumLoam: "Franco limoso",
        heavyLoam: "Franco arcilloso",
        clay: "Arcilloso",
        heavyClay: "Arcilla pesada",
        zoneSlope: "Inclinación general en las zonas",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Presupuesto de agua",
        lowWB: "Bajo",
        normalWB: "Normal",
        highWB: "Alto",
        ft: "pies",
        in: "pulgada",
        ftin: "pies/pulgadas",
        metric: "métrico",
        imperialUS: "imperial (EE.UU.)",
//UNITS CONFIG
        hydraConfig: "Hidráulica",
        waterTemp: "Temperatura del agua",
        maxFlowVelocity: "Velocidad máxima del flujo en tubería"
    }
};
