this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "pies/pulg",
        sqm: "m²",
        acre: "ac",
        hectare: "ha",
        sqft: "pies²",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gal",
        cubft: "ft³",
        lpm: "lpm",
        lph: "lph",
        m3h: "m³/h",
        USgpm: "gal/min",
        USgph: "gal/hora",
        deg: "°",
        pcs: "uds",
        pcsDot: "uds.",
        pcsShort: "uds.",
        percent: "%",
        in_Alt: "pulg.",
        mps: "m/s",
        kph: "km/h",
        ftps: "ft/s",
        degreesCentigrade: "°C",
        mmph: "mm/h",
        mmp24h: "mm/día",
        inph: "pulg/h",
// no convertible
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Cajón automático",
        chooseSprinkler: "Elegir boquilla:",
        auto: "Ajuste automático",
        waterSource2row: ["Agua", "Entrada"],
        setLineLength: "Establecer longitud de línea (mm):",
        setPressure: "Establecer presión dinámica esperada en boquillas (bar):",
        setMaxFlow: "Establecer flujo máximo de agua (l/min):",
        controllerShort: "C",
        sensorShort: "S",
        action_activateEraser: "Activar borrador",
        action_deactivateEraser: "Desactivar borrador",
        action_boolUnite: "Unir",
        action_boolIntersect: "Intersectar",
        action_boolSubtract: "Restar",
        action_boolExclude: "Excluir",
        action_changeSprayBody: "Establecer rociador",
        action_changeVariant: "Establecer variante",
        action_changeImgVariant: "Establecer variante",
        action_changeType: "Establecer tipo",
        action_addConsumers: "Agregar consumidores",
        action_drawBranches: "Agregar ramas",
        action_editLine: "Editar segmentos",
        action_drawCircles: "Dibujar círculos",
        action_detachAll: "Desvincular todo",
        action_drawBrush: "Dibujar pincel",
        action_editBrush: "Editar pincel",
        action_changeBrushSize: "Tamaño del pincel",
        action_booleans: "Operaciones booleanas",
        action_intoPoly: "Convertir en polígono",
        action_intoBrush: "Convertir en pincel",
        action_activateRotation: "Rotar",
        action_deactivateRotation: "Inmóvil",
        action_markZones: "Representación de zonas",
        action_unmarkZones: "Eliminar marcado",
        action_sprNames: "Nombres de rociadores",
        action_noSprNames: "Eliminar nombres",
        action_lockItem: "Bloquear",
        action_unlockItem: "Desbloquear",
        Circle: "Círculo",
        Triangle: "Triángulo",
        BushForm: "Arbustos",
        BushForm1: "Arbustos 1",
        BushForm2: "Arbustos 2",
        BushForm3: "Arbustos 3",
        Square: "Cuadrado",
        noShadow: "Ninguno",
        standardShadow: "Estándar",
        noArrows: "Ninguno",
        startArrow: "Al principio",
        endArrow: "Al final",
        bothArrows: "Ambos lados",
        normalSizeSide: "Normal",
        invertedSizeSide: "Invertido",
        strMiter: "Miter",
        strRound: "Redondo",
        strBevel: "Bisel",
        strSquare: "Cuadrado",
        strButt: "Butt",
        FWnormal: "Normal",
        FWbold: "Negrita",
        FWitalic: "Cursiva",
        FWbolditalic: "Negrita cursiva",
        FJleft: "Izquierda",
        FJright: "Derecha",
        FJcenter: "Centro",
        rzwHeight: "Altura"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Selector múltiple",
        //----Drawing
        selectPoly: "No se han seleccionado elementos",
        //----Sprinkling
        selectSprink: "No se han seleccionado elementos",
        lpNozzler: "Adjuntando consumidores de agua",
        dl16CircDrawer: "Dibujo de círculos de goteo de 16/13mm",
        dl16sDrawer: "Dibujo de cubierta de goteo de 16/13mm",
        dl17CircDrawer: "Dibujo de círculos de goteo de 17mm",
        dl17sDrawer: "Dibujo de cubierta de goteo de 17mm",
        "ldTextDrawer": "Configuración de Texto",
        "staticTextDrawer": "Configuración de Texto",
        "dynamicTextDrawer": "Configuración de Texto",
        "ldStaticTextDrawer": "Configuración de Texto",
        "ldtextEditor": "Edición de Texto",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Distancia total",
        type: "Tipo",
        variant: "Variante",
        area: "Área",
        perimeter: "Perímetro",
        curveLength: "Longitud",
        treeDiameter: "Diámetro de árbol",
        bushDiameter: "Diámetro de arbusto",
        nozTypes: "Tipos disponibles",
        nozType: "Tipo",
        sprBod: "Cuerpo de rociador",
        rad: 'Radio',
        angle: 'Ángulo',
        reducedBy: 'Reducido por',
        consump: 'Consumo',
        pressure: 'Presión',
        coverSize: 'Cobertura',
        maxFlow: 'Flujo máximo de agua',
        pipesNum: "Tubos conectados",
        pipeType: "Tipo",
        pipeLength: "Longitud",
        wireLength: "Longitud",
        valvesManifNum: "Manifold de válvulas",
        valvesNum: "Válvulas",
        propDiam: "Diámetro adecuado",
        curDiam: "Diámetro del dibujo",
        outsNum: "Consumidores de agua",
        flow: "Flujo de agua",
        precipRate: "Tasa de precipitación",
        totalPrecipArea: "Cobertura total",
        uniformity: "CU",
        uniformity2: "DU",
        overwatered: "Overwatered",
        precipRateShort: "Precip.",
        runtimeInd: "Tiempo de ejecución",
        coveredArea: "Área",
        microClimateInd: "M/Clima",
        soilTypeInd: "Tipo de suelo",
        zoneSlopeInd: "Inclinación",
        maxInfiltrationRate: "Tasa de infiltración",
        waterDemand: "Demanda de agua",
        numOfRuns: "Ejecuciones diarias",
        timePerRun: "Tiempo por ejecución",
        dailyConsumption: "Consumo diario",
        dripsNum: "Líneas de goteo conectadas",
        dripType: "Tipo de goteo",
        dripRowsStep: "Separación entre filas",
        dripRowsAngle: "Ángulo de filas",
        cntrType: "Tipo de controlador",
        sensType: "Tipo de sensor",
        zonesNum: "Zonas controladas",
        trenchWidth: "Ancho",
        trenchDepth: "Profundidad",
        trenchVolume: "Volumen",
        insetDiam: "Diámetro",
        insetLength: "Longitud",
        insetVar: "Material",
        itemsCount: "Cantidad",
        insetDepth: "Profundidad",
        zoneName: "Nombre de la zona",
        valveName: "Caja de válvula",
        itemAlias: "Alias",
        lineWidth: "Ancho",
        lineDepth: "Profundidad",
        lineArea: "Área",
        lineVolume: "Volumen",
        surfaceDepth: "Profundidad/Altura",
        surfaceVolume: "Volumen",
//MULTISELECTOR
        itemsSelected: "Seleccionados",
        totalArea: "Área total",
        totalPerimeter: "Perímetro total",
        totalLength: "Longitud total",
        totalVolume: "Volumen total",
        totalConsumption: "Consumo total",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Polígono no válido",
        isSelfCrossing_false: "Polígono válido",
        isConnected_true: "Conectado",
        isConnected_false: "No conectado",
        isWired_true: "Cableado",
        isWired_false: "Sin cableado",
        isDripZone_true: "Zona de goteo",
        isDripZone_false: "",
        isSprinklerZone_true: "Zona de rociadores",
        isSprinklerZone_false: "",
        isOverloaded_true: "¡SOBRECARGA!",
        isOverloaded_false: "",
        isUnderpressured_true: "Presión baja",
        isUnderpressured_false: "",
        isOverpressured_true: "Presión alta",
        isOverpressured_false: "",
        isLocked_true: "Bloqueado",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Acero inoxidable",
        "High speed": "Alta velocidad",
        "Opposing nozzle": "Opposing nozzle",
        "Plastic": "Plástico",
        "MPR Nozzles": "Boquillas MPR",
        "Rotary Nozzles": "Boquillas rotativas",
        Nozzles: "Boquillas",
        "Bubbler nozzles": "Boquillas burbujeantes",
        "Multi-stream": "Multichorro",
        "Dual-stream": "Doble chorro",
        "Stream Nozzles": "Boquillas de chorro",
        "Short Radius Nozzles": "Boquillas de corto alcance",
        "Pressure compensating": "Compensador de presión",
        "Adjustable flood": "Inundación ajustable",
        Adjustable: "Ajustable",
        Fixed: "Fijo",
        "Fixed Arc": "Arco fijo",
        "Strip Pattern": "Patrón de franjas",
        "Drip line": "Línea de goteo",
        "Drip cover": "Cobertura de goteo",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "Con emisores",
        "noemitter": "Sin emisores",
        "Root zone watering": "Riego de zona de raíces",
        Lateral: "Lateral",
        Main: "Principal",
        Trench: "Zanja",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC(Metric)",
        ldpe: "LDPE",
        Controller: "Controlador",
        Sensor: "Sensor",
        Wiring: "Conexión",
        IrrigateMarks: "Zonas de riego",
        Surface: "Superficie",
        Lawn: "Césped",
        Bed: "Cama",
        Shrubs: "Arbustos",
        Path: "Camino",
        Concrete: "Concreto",
        Sand: "Arena",
        Water: "Agua",
        Bedding: "Relleno",
        Flower: "Flor",
        Herbal: "Hierba",
        geographic: "Geográfico",
        loSurface: "Superficie",
        loStdSurf: "Estándar (Polígono)",
        loStdSurf_BRUSH: "Estándar (Pincel)",
        sizeMark: "Dimensiones",
        scalingBar: "Barra de escala",
        loCurves: "Líneas",
        texts: "Textos",
        staticText: "Texto estático",
        dynamicText: "Texto dinámico",
        stampText: "Texto de sello",
        stampTextDefault: "Texto",
        stampTextgr1: "Definición de documento",
        stampTextgr2: "Celda de dirección",
        stampTextgr3: "Nombre del sitio",
        stampTextgr4: "Nombre del dibujo",
        stampTextgr9: "Información de la organización",
        stampTextgr6t: "Etapa",
        stampTextgr7t: "Página",
        stampTextgr8t: "Páginas",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Cap.",
        stampTextgr15t: "Prtcp.",
        stampTextgr16t: "Página",
        stampTextgr17t: "# Doc.",
        stampTextgr18t: "Firma",
        stampTextgr19t: "Fecha",
        stampTextgr20t: "Inv. orig. #",
        stampTextgr21t: "Firma y fecha",
        stampTextgr22t: "Inv. reempl. #",
        inserts: "Sleeves de tubería",
        poly: "Polígono",
        brush: "Pincel",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Mostrar gestor de capas",
        hideLM: "Ocultar gestor de capas",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Sin nombre",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Exportando diseño",
        successExporting: "Exportado correctamente",
        failExporting: "Error al exportar",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Límite diario alcanzado</a>",
        exportingLimit: "Límite: ",
        exportingLeft: "Restante hoy: ",
        pdfExportingPopUpBlocked: "Tu navegador bloqueó la ventana emergente. Por favor, permite las ventanas emergentes para este sitio para obtener el archivo .PDF",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Rosca emergente",
        tt_group_MT: "Macho",
        tt_group_FT: "Hembra",
        tt_riserHeight: "Altura de la rosca",
        tt_pressureReg: "Regulador de presión",
        tt_checkValve: "(Con válvula de retención)",
        tt_home: "Inicio",
        tt_prev: "Anterior",
        tt_next: "Siguiente",
        tt_end: "Fin",
        tt_add: "Agregar",
        tt_clone: "Clonar",
        tt_remove: "Eliminar",
        tt_rename: "Renombrar",
        tt_addToFav: "Agregar a Favoritos",
        tt_remFromFav: "Eliminar de Favoritos",
        tt_presets: "Preajustes",
        tt_MagicAutoPlacer: "`Colocación automática a lo largo de la línea`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "N",
        S: "S",
        E: "E",
        W: "W",
        //conventions
        sprinklers: "Aspersores",
        dripStarts: "Inicio de goteo",
        rzwLayer: "Riego zona raíz",
        dripLines: "Línea de goteo",
        valvesLayer: "Manifold de válvulas",
        waterSources: "Fuente de agua",
        quickCoupLayer: "Acoplamiento rápido",
        controllers: "Controlador",
        sensorsLayer: "Sensor",
        mainPipes: "Tubería principal",
        lateralPipes: "Tubería lateral",
        lateralPipes_sprinklerZone: "Zona (Aspersores)",
        lateralPipes_dripZone: "Zona (Línea de goteo)",
        lateralPipes_rzwZone: "Zona (Riego zona raíz)",
        lateralPipes_emptyZone: "Zona (Sin consumidores)",
        trenchesLayer: "Zanjas",
        insetsLayer: "Manguitos",
        wiresLayer: "Cableado",
        wirelessLayer: "Conexión inalámbrica",
        senswirelessLayer: "Conexión inalámbrica de sensores",
        senswiresLayer: "Cableado de sensores",
        surfaces: "Superficies",
        ldItemsLayer: "Plantas",
        covers: "Cobertura",
        nameplates: "Información de los consumidores",
        oreolas: "Marcas de los consumidores",
        pipeInfo: "Información de las tuberías",
        lines: "Líneas",
        overlays: "Capas superpuestas",
        stampLayer: "Marco",
        stampTexts: "Textos de sello",
//zonesTable
        zoneType: "Tipo de zona",
        color: "Color",
        consumers: "Consumidores",
        waterFlow: "Flujo",
        sprinklerZone: "Aspersión",
        dripZone: "Goteo",
        rzwZone: "Riego zona raíz",
        emptyZone: "Sin consumidores",
        specifyDiagonal: "Por favor, especifique el tamaño diagonal de su monitor en pulgadas",
//sprinklersTable
        consType: "Tipo",
        consName: "Nombre",
        zoneNum: "Zona",
        sector: "Sector",
        radius: "Radio",
        reducedBy: "Reducido por",
        nozzle: "Boquilla",
        rotor: "Rotor",
        bubbler: "Bubbler",
        bubblerNozzle: "Boquilla Bubbler",
//dripsTable
        catId: "Cat.ID",
        brand: "Marca",
        emitterStep: "Paso",
        emitterFlow: "Flujo",
//layersManangerSpecific
        consumersGrp: "Consumidores",
        nodesGrp: "Nodos",
        wiresGrp: "Cables",
        pipesGrp: "Tuberías",
        landscapeGrp: "Paisaje",
        allTogether: "Todo junto"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Tipo",
        brand: "Marca",
        catid: "ID Cat.",
        title: "Título",
        units: "Unidades",
        amount: "Cantidad",
//predetermined
        dripLine: "Línea de goteo",
        dl16: "Línea de goteo 16/13mm",
        dl17: "Línea de goteo 17mm",
        dripStart: "Arranque de goteo",
        ds16: "Arranque de goteo 16/13mm",
        ds17: "Arranque de goteo 17mm",
        manifold_no_lps_issue: "Sin zonas conectadas",
        manifold_no_mp_issue: "No conectado a la línea principal",
        manifold_no_wr_issue: "Sin cable de control adjunto",
        //nodes-----------------------------------
        sprinkler_unattached: "¡ADVERTENCIA! Tiene ASPERSORES sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        drip_unattached: "¡ADVERTENCIA! Tiene elementos de riego por GOTEO sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        mains_unattached: "¡ADVERTENCIA! Tiene LÍNEAS PRINCIPALES sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        mains_empty: "¡ADVERTENCIA! Tiene LÍNEAS PRINCIPALES sin consumidores (no se mostrarán en la hoja de especificaciones finales)",
        laterals_unattached: "¡ADVERTENCIA! Tiene TUBERÍAS LATERALES sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        laterals_empty: "¡ADVERTENCIA! Tiene TUBERÍAS LATERALES sin consumidores (no se mostrarán en la hoja de especificaciones finales)",
        rzw_unattached: "¡ADVERTENCIA! Tiene elementos de RIEGO EN LA ZONA DE LA RAÍZ sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        sensors_unattached: "¡ADVERTENCIA! Tiene SENSORES sin conectar (no se mostrarán en la hoja de especificaciones finales)",
        manifolds_unfinished: "¡ADVERTENCIA! Tiene MANIFOLDS incompletos (no se puede completar la configuración de válvulas)",
        control_wires_unattached: "¡ADVERTENCIA! Tiene CABLEADO DE CONTROL sin conectar",
        control_wires_empty: "¡ADVERTENCIA! Tiene CABLEADO DE CONTROL sin válvulas conectadas",
        cntr_wr_unattached: "Cableado de control",
        youCanSeeThemInTheDrawing: "Puedes ver cada elemento en el dibujo, presionando el 'ojo' a la izquierda de la fila del elemento",
        sprinkler_nozzleMT: "Nodo de rociador (Boquilla hembra)",
        sprinkler_nozzleFT: "Nodo de rociador (Boquilla macho)",
        "sprinkler_rotor1/2F": "Nodo de rociador (Rotor) 1/2\" hembra",
        "sprinkler_rotor3/4F": "Nodo de rociador (Rotor) 3/4\"",
        "sprinkler_rotor1F": "Nodo de rociador (Rotor) 1\"",
        "sprinkler_rotor11/4F": "Nodo de aspersor (Rotor) 1 1/4\"",
        "sprinkler_rotor11/2F": "Nodo de aspersor (Rotor) 1 1/2\"",
        "sprinkler_rotor2F": "Nodo de aspersor (Rotor) 2\"",
        "sprinkler_rotor1/2M": "Nodo de rociador (Rotor) 1/2\" macho",
        "sprinkler_rotor3/4M": "Sprinkler node (Rotor) 3/4\" male",
        "sprinkler_bubbler1/2F": "Nodo de rociador (Bubbler)",
        sprinkler_bubblerNozzleMT: "Nodo de rociador (Boquilla de burbuja hembra)",
        sprinkler_bubblerNozzleFT: "Nodo de rociador (Boquilla de burbuja macho)",
        dripIrrigation16: "Riego por goteo (16/13mm)",
        dripIrrigation17: "Riego por goteo (17mm)",
        rootZoneWatering: "Sistema de riego de zona radicular",
        manifold: "Nodo de colector de válvulas",
        automation: "Nodo de automatización",
        mainPipes_hdpePE80SDR11: "Tubos principales HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Tubos principales HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Tubos principales HDPE SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Tubos laterales HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Tubos laterales HDPE SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Tubos laterales HDPE SDR 17.6",
        mainPipes_hdpeSDR9: "Tubos principales HDPE SDR 9",
        mainPipes_hdpeSDR11: "Tubos principales HDPE SDR 11",
        mainPipes_hdpeSDR136: "Tubos principales HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Tubos principales HDPE SDR 17",
        mainPipes_hdpeSDR176: "Tubos principales HDPE SDR 17.6",
        lateralPipes_hdpeSDR9: "Tubos laterales HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Tubos laterales HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Tubos laterales HDPE SDR 13.6",
        lateralPipes_hdpeSDR17: "Tubos laterales HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Tubos laterales HDPE SDR 17.6",
        mainPipes_pvcSCH40: "Tubos principales PVC SCH40",
        mainPipes_pvcSCH80: "Tubos principales PVC SCH80",
        mainPipes_pvcCL315: "Tubos principales PVC CLASS 315",
        mainPipes_pvcCL200: "Tubos principales PVC CLASS 200",
        mainPipes_pvcCL160: "Tubos principales PVC CLASS 160",
        mainPipes_pvcCL125: "Tubos principales PVC CLASS 125",
        mainPipes_pvcUSCJPN18: "Main pipes PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Main pipes PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Main pipes PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Main pipes PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Main pipes PVC-U SCJ (PN4.5)",
        mainPipes_ldpeCLASS3: "Tubos principales LDPE CLASS 3",
        lateralPipes_pvcSCH40: "Tubos laterales PVC SCH40",
        lateralPipes_pvcSCH80: "Tubos laterales PVC SCH80",
        lateralPipes_pvcCL315: "Tubos laterales PVC CLASS 315",
        lateralPipes_pvcCL200: "Tubos laterales PVC CLASS 200",
        lateralPipes_pvcCL160: "Tubos laterales PVC CLASS 160",
        lateralPipes_pvcCL125: "Tubos laterales PVC CLASS 125",
        lateralPipes_pvcUSCJPN18: "Lateral pipes PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Lateral pipes PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Lateral pipes PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Lateral pipes PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Lateral pipes PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Tubos laterales LDPE CLASS 3",
        wiring: "Cableado",
        qcv: "Válvulas de acoplamiento rápido",
        fixedCntr: "fijo",
        stand_aloneCntr: "autónomo",
        modularCntr: "modular",
        decoderCntr: "decodificador",
        inset: "Sleeve de tubería",
        insets: "Sleeves",
//-----------------------------------------
        novar: "sin variantes",
        choosevar: "elegir variante",
//element.types----------------------------
        nozzle: "Boquilla",
        rotor: "Rociador",
        rotorNozzle: "Boquilla para rociador",
        bubbler: "Difusor",
        bubblerNozzle: "Boquilla para difusor",
        rzw: "Sistema de riego de zona radicular",
        sprayBody: "Cuerpo de spray",
        sprinklerStandAssembly: "Sprinkler stand (Riser)",
        outBarb: "Barb a boquilla",
        flexPipe: "Tubería flexible",
        sj: "Juntas giratorias",
        inBarb: "Barb a tubería",
        midSprinkPipeFitting: "Accesorio de tubería",
        endSprinkPipeFitting: "Accesorio final de tubería",
        midRZWPipeFitting: "Accesorio de tubería",
        endRZWPipeFitting: "Accesorio final de tubería",
        dripPipe: "Tubería de goteo",
        blindPipe: "Tubería ciega",
        dripTeeFitting: "Tee de goteo",
        dripCapFitting: "Tapa de goteo",
        dripCouplingFitting: "Acoplador de goteo",
        dripElbowFitting: "Codo de goteo",
        dripSpike: "Estaca de goteo",
        sprinklerZoneValve: "Válvula de zona de rociadores",
        emptyZoneValve: "Válvula sin consumidores",
        valveOutFitting: "Válvula a zona",
        dripZoneValve: "Válvula de zona de goteo",
        rzwZoneValve: "Válvula de riego en la zona de raíces",
        pressureReg: "Regulador de presión",
        filter_pressureReg: "Filtro con regulador de presión",
        controller: "Controlador",
        flowMeter: "Medidor de flujo",
        rainSensor: "Sensor de lluvia",
        soilSensor: "Sensor de humedad",
        freezeSensor: "Sensor de heladas",
        wrFreezeSensor: "Sensor de lluvia/heladas inalámbrico",
        windSensor: "Sensor de viento",
        solarSensor: "Sensor solar",
        flowSensor: "Sensor de flujo",
        weatherStation: "Estación meteorológica",
        solarPanel: "Panel solar",
        mainPipe: "Tubería principal",
        teeFitting: "T de unión",
        elbowFitting: "Codo",
        reducerFitting: "Reductor",
        lateralPipe: "Tubería lateral",
        capFitting: "Tapa",
        basicCable: "Cable básico",
        basicWire: "Cable básico",
        sensorCable: "Cable para sensor meteorológico",
        qcPlastic: "Válvula de acoplamiento rápido de plástico",
        qcMetal: "Válvula de acoplamiento rápido de metal",
        gateway: "Gateway",
        antExt: "Antenna extension",
        loramod: "LoRa modules",
        //typesOfAcessories
        hdpeCOR: "Tubería corrugada",
        expModule: "Módulo de expansión",
        rzwSleeve: "Manga de tela para riego en la zona de raíces",
        rwCap: "Tapa para agua reciclada",
        gutterMount: "Soporte para canal",
        delayRelay: "Relé de retardo",
        fctFlow: "T receptáculo FCT",
        fctBspAdap: "Adaptador para accesorio FCT",
        drainCheckValve: "Válvula de retención para drenaje",
        rwId: "Identificación para agua reciclada",
        vpc: "Tapa a prueba de vandalismo",
        inletFilter: "Filtro de entrada",
        wifiModule: "Módulo Wi-Fi",
        wallMount: "Soporte de pared",
        rwsSock: "Manga de tela para riego en la zona de raíces",
        rwsGrate: "Cuadricula para RWS",
        npCover: "Cubierta para agua no potable",
        sprExt: "Extensión para aspersor",
        popUpToThread: "Adaptador para aspersor emergente",
        valveBox: "Caja de válvula",
        valveBoxExt: "Extensión para caja de válvula",
        qcPlasticKey: "Llave para válvula de cierre rápido (plástico)",
        qcPlasticElbFit: "Acople en codo para válvula de cierre rápido (plástico)",
        qcMetalKey: "Llave para válvula de cierre rápido (metal)",
        qcMetalElbFit: "Acople en codo para válvula de cierre rápido (metal)",
        qcMetalCapKey: "Llave de la tapa",
        insTape: "Cinta de aislamiento",
        wrConn: "Conector",
        shrinkTube: "Tubo termocontraíble",
        hcFrontPanel: "Panel frontal",
        ball_valve: "Válvula de bola",
        check_valve: "Válvula de retención",
        thread_manifold: "Colector",
        plastic_filter: "Filtro (plástico)",
        waterMeter: "Medidor de agua",
        rfModule: "Módulo de radio",
        largeAntenna: "Antena grande",
        wifiHub: "Hub WiFi",
        handRemoteKit: "Kit de control remoto",
        handRemote: "Control remoto",
        wifiBundleKit: "Kit de conexión WiFi",
//typesOfFittings
//drip
        barb_cap_8: "Cierre de extremo de riego por goteo",
        barb_elbow_PP: "Codo con barba",
        barb_elbow_PT: "Codo con barba y rosca",
        barb_tee_PPP: "T de barba",
        barb_coupling_PP: "Unión con barba",
        barb_cross_PPPP: "Cruz con barba",
        barb_cap_P: "Cierre de barba",
        barb_coupling_PT: "Unión con barba y rosca",
        barb_tee_PTP: "T de barba y rosca",
        barb_valve_PT: "Válvula con barba y rosca",
        barb_valve_PP: "Válvula con barba",
        twlc_elbow_PP: "Codo con cierre de rosca",
        twlc_tee_PPP: "T con cierre de rosca",
        twlc_coupling_PP: "Unión con cierre de rosca",
        twlc_cross_PPPP: "Cruz con cierre de rosca",
        twlc_cap_P: "Cierre con cierre de rosca",
        twlc_coupling_PT: "Unión con cierre de rosca y rosca",
        twlc_tee_PTP: "T con cierre de rosca y rosca",
        twlc_valve_PT: "Válvula con cierre de rosca y rosca",
        twlc_valve_PP: "Válvula con cierre de rosca",
        dl_valves: "Válvulas especiales",
        //pipe
        hdpeSDR9: "Tubo HDPE SDR 9",
        hdpeSDR11: "Tubo HDPE SDR 11",
        hdpeSDR136: "Tubo HDPE SDR 13.6",
        hdpeSDR17: "Tubo HDPE SDR 17",
        hdpeSDR176: "Tubo HDPE SDR 17.6",
        ldpeSDR9: "Tubo LDPE SDR 9",
        ldpeSDR11: "Tubo LDPE SDR 11",
        ldpeSDR136: "Tubo LDPE SDR 13.6",
        ldpeSDR17: "Tubo LDPE SDR 17",
        pvcSCH40: "Tubo PVC SCH40",
        pvcSCH80: "Tubo PVC SCH80",
        pvcCL315: "Tubo PVC CLASS 315",
        pvcCL200: "Tubo PVC CLASS 200",
        pvcCL160: "Tubo PVC CLASS 160",
        pvcCL125: "Tubo PVC CLASS 125",
        pvcUSCJPN18: "Pipe PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Pipe PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Pipe PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Pipe PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Pipe PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "Tubo LDPE CLASS 3",
        compress_elbow_PT: "Codo de compresión/rosca",
        compress_coupling_PT: "Acoplamiento de compresión/rosca",
        compress_tee_PTP: "T de compresión/rosca",
        compress_cap_P: "Tapón final de compresión",
        compress_elbow_PP: "Codo de compresión",
        compress_coupling_PP: "Acoplamiento de compresión",
        compress_tee_PPP: "T de compresión",
        compress_cross_PPPP: "Cruz de compresión",
        compress_single_clamp_saddle: "Abrazadera de compresión",
        compress_ballvalve_PP: "Válvula de bola de compresión",
        compress_ballvalve_PT: "Válvula de bola de compresión/rosca",
        customfit_elbow_PT: "Codo roscado personalizado",
        customfit_coupling_PT: "Unión roscada personalizada",
        customfit_tee_PTP: "T de rosca personalizada",
        customfit_cap_P: "Tapón final personalizado",
        customfit_elbow_PP: "Codo personalizado",
        customfit_coupling_PP: "Unión personalizada",
        customfit_tee_PPP: "T personalizada",
        customfit_cross_PPPP: "Cruz personalizada",
        customfit_single_clamp_saddle: "Silla de sujeción simple",
        customfit_ballvalve_PP: "Válvula de bola personalizada",
        customfit_ballvalve_PT: "Válvula de bola roscada personalizada",
        thread_nipple: "Niple",
        thread_coupling: "Acoplamiento",
        thread_mf_reducer: "Reductor macho/hembra",
        thread_mf_adapter: "Adaptador macho/hembra",
        thread_mf_bush: "Casquillo macho/hembra",
        thread_tee: "T hembra",
        thread_elbow: "Codo hembra",
        thread_mf_elbow: "Codo macho/hembra",
        thread_cap: "Tapa hembra",
        thread_plug: "Tapón macho",
        thread_union_nut: "Tuerca de unión",
        thread_cross: "Cruz",
        cable: "Cable",
        wire: "Cable eléctrico",
        // slip
        slip_single_clamp_saddle: "Silla de abrazadera simple (en tubería de PVC)",
        slip_elbow_PT: "Codo de deslizamiento/rosca",
        slip_coupling_PT: "Acople de deslizamiento/rosca",
        slip_tee_PTP: "T de deslizamiento/rosca",
        slip_cap_P: "Tapón final de deslizamiento",
        slip_elbow_PP: "Codo de deslizamiento",
        slip_coupling_PP: "Acople de deslizamiento",
        slip_tee_PPP: "T de deslizamiento",
        slip_cross_PPPP: "Cruz de deslizamiento",
        slip_ballvalve_PP: "Válvula de bola de deslizamiento",
        slip_ballvalve_PT: "Válvula de bola de deslizamiento/rosca",
//extendables
        arbitraryFittings: "Conexiones arbitrarias",
        dripStartAssembly: "Conjunto de inicio para goteo",
        intakeAssembly: "Conjunto de admisión",
        offtakeAssembly: "Conjunto de derivación para conexiones arbitrarias",
        numofvalves: "Número de válvulas: ",
        numofvalvesshort: "Válvulas: ",
        numofmanifs: "Número de colectores: ",
        intakePipeSize: "Tamaño de tubería de admisión: ",
        valveBoxes: "Cajas de válvulas",
        valveAccessories: "Accesorios de válvulas",
        oneValveAccessories: "Accesorios de válvulas",
        controllerAccessories: "Accesorios de controlador",
        sensorAccessories: "Accesorios de sensor",
        sprBodyAccessories: "Accesorios de cuerpo de rociado",
        rzwAccessories: "Accesorios de riego en la zona de la raíz",
        pipeStartFittings: "Conexiones arbitrarias de la tubería principal",
        qcAccessories: "Accesorios de válvulas Q/C",
        wiringAccessories: "Accesorios de cableado",
        pipeSize: "Tamaño de la tubería: ",
        endOfPipe: "(Posición final)",
        midOfPipe: "(Corte en la tubería)",
        emptyRender: [
            "Lo siento... no se ha encontrado ningún contenido",
            "No has completado completamente ninguno de los nodos de riego para ser renderizado"
        ],
        serviceFail: [
            "Lo siento... el servicio de renderización de especificaciones no está disponible en este momento",
            "Por favor, inténtalo de nuevo más tarde, cuando se establezca la conexión",
            "Ten en cuenta que la configuración que hayas hecho anteriormente se guardará"
        ],
        serviceTrialExpired: [
            "Lo siento... el servicio de renderización de especificaciones no está disponible para tu cuenta",
            "Eso significa que tu período de prueba ha terminado, y si quieres usar este servicio",
            "<a href='/account/subscription'>Puedes actualizar a una cuenta PRO</a>"
        ],
        serviceLimitReached: [
            "Has alcanzado el límite diario de renderización de hojas de especificaciones",
            "Para eliminar el límite en el número de renders de especificaciones por día",
            "<a href='/account/subscription'>Puedes actualizar a una cuenta PRO</a>"
        ],
        findInDrawing: "Mostrar en lienzo",
// IDS DE GRUPOS Y ELEMENTOS PARA LABORES
        labours_group_pipes: "Tuberías",
        labours_group_fittings: "Accesorios",
        labours_group_valveBoxes: "Cajas de válvulas",
        labours_group_wires: "Cableado",
        labours_group_sprinklers: "Aspersores",
        labours_group_rws: "Sistemas de riego por zona radicular",
        labours_group_sprinklerConnections: "Conexiones de aspersores",
        labours_group_drip: "Líneas y accesorios de riego por goteo",
        labours_group_manifolds: "Manifolds",
        labours_group_quickCoupling: "Acoplamientos rápidos",
        labours_group_controllers: "Controladores",
        labours_group_sensors: "Sensores",
        labours_group_trenches: "Zanjas",
        labours_group_insets: "Manguitos de tubería",
        labours_group_lawns: "Césped",
        labours_group_irrigatedArea: "Área regada",
        labours_group_arbitrary_sp: "💦 Elementos de riego personalizados",
        labours_group_arbitrary_ld: "🌳 Elementos de paisaje personalizados",
        ldArbitrary_equip: "Equipamiento",
        ldArbitrary_labour: "Mano de obra",
        spArbitrary_equip: "Equipamiento",
        spArbitrary_labour: "Mano de obra",
        arbitrary_sp: '💦 Elementos de riego personalizados',
        arbitrary_ld: '🌳 Custom Landscape elements',
        ldLine_labour: "Línea",
        ldLine_equip: "Línea",
        spLine_labour: "Línea",
        spLine_equip: "Línea",
        ldLineWithArea_labour: "Línea (m2)",
        ldLineWithArea_equip: "Línea (m2)",
        spLineWithArea_labour: "Línea (m2)",
        spLineWithArea_equip: "Línea (m2)",
        ldVolumetricLine_labour: "Línea (m3)",
        ldVolumetricLine_equip: "Línea (m3)",
        spVolumetricLine_labour: "Línea (m3)",
        spVolumetricLine_equip: "Línea (m3)",
        polyLdSurface_labour: "Superficie",
        brushLdSurface_labour: "Superficie",
        polyLdSurface_equip: "Superficie",
        brushLdSurface_equip: "Superficie",
        polySpSurface_labour: "Superficie",
        brushSpSurface_labour: "Superficie",
        polySpSurface_equip: "Superficie",
        brushSpSurface_equip: "Superficie",
        polyLdVolumetricSurface_labour: "Superficie (m3)",
        brushLdVolumetricSurface_labour: "Superficie (m3)",
        polyLdVolumetricSurface_equip: "Superficie (m3)",
        brushLdVolumetricSurface_equip: "Superficie (m3)",
        polySpVolumetricSurface_labour: "Superficie (m3)",
        brushSpVolumetricSurface_labour: "Superficie (m3)",
        polySpVolumetricSurface_equip: "Superficie (m3)",
        brushSpVolumetricSurface_equip: "Superficie (m3)",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
        MMM: ["\x01", "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"],
        dddd: ["\x02", "Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
        ddd: ["\x03", "Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
        //buttonsCaps
        ok: "Aceptar",
        save: "Guardar",
        on: "Activado",
        off: "Desactivado",
        apply: "Aplicar",
        defaults: "Predeterminados",
        retry: "Reintentar",
        finish: "Finalizar",
        safeRestart: "Reinicio seguro",
        saveAndExit: "Guardar y salir",
        exit: "Salir",
        cancel: "Cancelar",
        rename: "Renombrar",
        idk: "No lo sé",
        getFile: "Obtener archivo",
        reset: "Restablecer",
        random: "Aleatorio",
//misc
        zoneNum: "Zona n.º",
        valveNum: "Caja de válvulas n.º",
        zonesColoring: "Representación de zonas",
        coversColoured: "Pintar cubiertas de aspersores",
        dripsColoring: "Coloración de líneas de goteo",
        dripsSameAsZonesColored: "Línea de goteo en el mismo color de su zona",
        //saveOflline
        saveOffline: [
            "Lo sentimos... se ha perdido la conexión",
            "Pero no se preocupe, puede continuar con su proyecto en modo fuera de línea.",
            "Mientras esté desconectado, todos sus guardados se almacenarán como un archivo de texto en la carpeta de descargas de su navegador.",
            "Luego podrá cargar la última versión de su dibujo en el servidor."
        ],
        restartOffline: [
            "Lo sentimos... se ha perdido la conexión",
            "Pero no se preocupe, su proyecto se guardó localmente en su computadora.",
            "Puede encontrarlo en la carpeta de descargas de su navegador.",
            "Si desea trabajar sin conexión, puede descargar una instancia sin conexión de la aplicación desde su panel en http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Lo sentimos... algo salió mal al cargar su proyecto",
            "Parece que su guardado anterior se corrompió de alguna manera.",
            "Pero no se preocupe, podemos repararlo.",
            "Su proyecto ahora se marcará como 'Roto' en su taller.",
            "Y nuestro personal técnico manejará esta situación lo antes posible."
        ],
        corruptedSavingFile: [
            "Lo sentimos... el archivo que está intentando cargar no es legible",
            "Pero no se preocupe, podemos repararlo.",
            "Todo lo que necesita hacer es enviar este archivo roto en el formulario de abrir de archivos de su taller.",
            "Y luego intentaremos hacer que funcione de nuevo."
        ],
        ajaxReqFail: [
            "Lo sentimos... perdimos la conexión con el servidor",
            "Es imposible enviar/recibir datos en este momento",
            "Por favor, inténtelo de nuevo más tarde"
        ],
        critical: [
            "Lo sentimos... algo salió mal",
            "Pero no se preocupe, su dibujo está seguro, simplemente haga clic en el botón de reinicio seguro para continuar ..."
        ],
        fatal: [
            "Lo sentimos... algo salió mal",
            "Ayúdenos a mejorar nuestro servicio. Describa después de qué acciones de usuario se produjo este error",
            "Proporcione información aquí"
        ],
        areYouSure: [
            "Está a punto de cerrar este proyecto",
            "Tenga en cuenta que todos los cambios no guardados se perderán."
        ],
        pickAnotherCSVFile: "Elija otro archivo",
        csvFileTooBig: [
            "Tamaño máximo de archivo csv excedido",
            "Por razones de optimización, el tamaño máximo de archivo csv que se puede manejar está limitado a 4Mb"
        ],
        notAnCSV: [
            "Lo sentimos, este tipo de archivo no es compatible",
            "Formatos compatibles: .csv"
        ],
        invalidCSV: [
            "Contenido de archivo CSV no válido",
            "Error al analizar el archivo de exportación de la aplicación Moasure, verifique si el archivo se exportó correctamente"
        ],
        pickAnotherImage: "Elija otra imagen",
        imageTooBig: [
            "Tamaño máximo de imagen excedido",
            "Por razones de optimización, el tamaño máximo de imagen que se puede manejar está limitado a 10Mb"
        ],
        notAnImage: [
            "Lo sentimos, este tipo de archivo no es compatible",
            "Formatos de imagen compatibles: .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "ACCIÓN RESTRINGIDA",
            "Esta acción no está permitida para la suscripción GRATUITA"
        ],
        goPro: 'IR A PRO',
        renameLayout: "Ingrese un nuevo nombre",
        areYouSureDeleteLayout: [
            "¡Atención! Esta acción no se puede deshacer",
            "¿Está seguro de que desea eliminar: ",
            "Eliminar"
        ],
        setUnderlaySize: [
            "Establecer la longitud de la línea que acaba de dibujar",
            "Ha ingresado un valor incorrecto. Por favor intente nuevamente"
        ],
        setMonitorDiagonal: [
            "Proporcione información sobre el tamaño diagonal de su monitor",
            "Ha ingresado un valor incorrecto. Por favor intente nuevamente"
        ],
        getSpecsTable: [
            "Establecer las preferencias de salida de especificaciones",
            "Agrupar el equipo por ",
            "Nodo", "Marca",
            "Establecer el tipo de archivo como ",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Ingrese el título",
            "Disposición #",
            "Guardar",
            "Guardando especificaciones",
            "Completado. Haga clic aquí para abrir",
            "Falló el guardado",
            "Actualizar disposiciones existentes",
            "Actualizar",
            "Actualizando disposiciones"
        ],
        exportLayoutsAsPdf: [
            "Elija las disposiciones a exportar",
            "archivos separados (en desarrollo)",
            "un álbum",
            "Exportar",
            "Exportar disposiciones en"
        ],
        differentSprGroups: [
            "Error al conectar diferentes tipos de consumidores de agua en esta tubería",
            "Según las normas de diseño de riego, no está permitido mezclar diferentes tipos de consumidores de agua o aspersores con diferentes tasas de precipitación en la misma zona"
        ],
        tooFarAwaySpr: [
            "Error al conectar consumidores",
            "Algunos de los consumidores están demasiado lejos de la tubería lateral para conectarse. La distancia máxima de conexión se puede configurar en el menú de preferencias."
        ],
        outlayerConfig: [
            "Configuración de la hoja de especificaciones"
        ],
        presetsMenu: {
            title: "Preajustes",
            titleTextboxLabel: "Título del Preajuste",
            descriptionTextboxLabel: "Descripción",
            applyButton: "<i class='far fa-check-circle'></i> Aplicar",
            defaultButton: "<i class='far fa-undo'></i> Predeterminado",
            removeButton: "<i class='far fa-trash'></i> Eliminar",
            updateButton: "<i class='far fa-sync'></i> Actualizar",
            createButton: "<i class='far fa-plus'></i> Crear nuevo",
            closeButton: "<i class='far fa-times'></i> Cerrar",
            favorites_drawing: "Herramientas Favoritas (Paisajismo)",
            favorites_sprinkling: "Herramientas Favoritas (Riego)",
            favorites_layouting: "Herramientas Favoritas (Diseño)",
            configs_drawing: "Configuración del Proyecto",
            configs_outlayer: "Configuración de la Hoja de Especificaciones",
        },
        newPresetItem: "Nuevo Preajuste",
        cL_alreadyConnected: [
            "No se pudo concatenar las líneas",
            "Estas líneas ya están conectadas a"
        ],
        cL_segOnElem: [
            "No se pudo concatenar las líneas",
            "No se puede conectar al segmento que está en"
        ],
        cL_strangeError: [
            "No se pudo concatenar las líneas",
            "Lo siento...La conexión falló"
        ],
        cL_misgrouping: [
            "No se pudo concatenar las líneas",
            "Estas líneas tienen consumidores que no se recomienda colocar en la misma zona. Si deseas conectarlas de todas formas, activa el 'Modo Inseguro' para la Agrupación de Rociadores en la configuración del proyecto"
        ],
        cL_valve: "Colector de válvulas",
        cL_waterSource: "Fuente de agua",
        cL_dripStart: "Inicio de goteo",
        cL_controller: "Controlador",
        cL_sensors: "Sensores",
        cL_valves: "Colector de válvulas",
        cL_notSameVariant: [
            "Fallo al concatenar las líneas",
            "Estas líneas tienen diferentes tipos",
            "Tipo de línea que se está dibujando actualmente",
            "Tipo de línea con la que deseas conectar"
        ],
        hasRestorableProject: [
            "Tienes datos no guardados para este proyecto",
            "Puedes restaurar el estado no guardado desde la instantánea tomada en"
        ],
        restoreProject: "Restaurar",
        imageLost: [
            "Lo sentimos, no podemos encontrar algunas de las imágenes de fondo en el servidor",
            "Esta imagen no se encontró:"
        ],
        precipCalcError_mixedError: [
            'Error en los mapas de precipitación',
            'Error al construir mapas de precipitación para la combinación de aspersores:',
        ],
        precipCalcError_mprNonMprRot: 'No se pueden mezclar rotores normales y rotores con boquillas MPR',
        precipCalcError_mprNozNonMprRot: 'No se pueden mezclar boquillas MPR y rotores normales',
        precipCalcError_staticNozRot: 'No se pueden mezclar boquillas estáticas con rotores',
        precipCalcError_staticMprNoz: 'No se pueden mezclar boquillas estáticas con boquillas MPR',
        precipCalcError_missingError: [
            'Error en los mapas de precipitación',
            'Faltan perfiles de precipitación para los aspersores:',
        ],
        precipCalcError_zoningError: [
            'Error de zonificación en los mapas de precipitación',
            'Error al construir mapas de precipitación para la combinación de aspersores:',
        ],
        precipCalcError_noZoneAndZone: 'No se puede calcular la precipitación para rotores conectados y no conectados simultáneamente. El tiempo de ejecución es desconocido, por lo tanto, la cantidad de revoluciones de los rotores es incierta',
        algoNozzler_noSolutions: [
            'No se encontraron soluciones posibles para la colocación de aspersores',
            'Intente lo siguiente:',
            '1. Cambie las restricciones de superposición y otras opciones en el menú de configuración de la herramienta de colocación automática',
            '2. Seleccione otro tipo de aspersores, ya que pueden proporcionar la flexibilidad necesaria en la colocación',
            '3. Use el botón de abajo para reiniciar la solución con restricciones más "flexibles" para la superposición y la cobertura'
        ],
        retryWithLooseOptions: "Reintentar con opciones 'flexibles'",
        cannotSaveBecauseOffline: [
            "Fallo al enviar la solicitud al servidor",
            "Sin conexión al servidor",
            "Verifique si tiene una conexión a internet",
            "Para no perder los datos, no cierre esta ventana e intente guardar los datos más tarde, cuando se establezca la conexión con el servidor",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "No se pudo guardar la solicitud",
            "Demasiados intentos de código inválidos",
            "Verifique si ingresó correctamente la dirección de correo electrónico e inténtelo de nuevo después de 30 segundos.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "No se pudo guardar la solicitud",
            "Dirección de correo electrónico ingresada incorrectamente",
            "Verifique si ingresó correctamente la dirección de correo electrónico e inténtelo de nuevo",
            "",
            "",
        ],
        designRequestCompleted: [
            "Su solicitud se creó / actualizó correctamente",
            "Enlace de edición", "copiar",
            "Enlace para ver", "copiar",
        ],
        designRequestContacts: [
            "Contact information",
            "Organization",
            "Name",
            "Email",
            "Phone",
            "Address",
            "Website",
        ],
        "designRequestInfo": [
            "¡Bienvenido al Estudio de Diseño!",
            "Aquí puede crear una solicitud para planificar su sistema de riego de manera fácil y rápida.",
            "Puede encontrar un <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>video de instrucciones aquí</a>",
            "Para más información o si tiene alguna pregunta, no dude en ponerse en contacto con nosotros."
        ],
        approveActionByCode: [
            "Confirmar acción",
            "Se envió un correo electrónico con un código de confirmación a la dirección de correo electrónico que proporcionó.",
            "Ingrese este código en el campo a continuación",
            "Ha ingresado un número inválido, inténtelo de nuevo"
        ],
        "revisionCheckFailedSoft": [
            "¡Conflicto de revisión!",
            "Este proyecto está actualmente abierto en otro navegador o dispositivo.",
            "Puedes sobrescribir los datos en el servidor (ya que solo almacenamos una versión de tu proyecto) haciendo clic en `sobrescribir`, pero ten cuidado: ¡se perderá todo el progreso realizado en otras sesiones!",
            "Una mejor estrategia es entender dónde y quién abrió este proyecto y decidir qué versión está actualizada.",
            "Si quieres tomar el control sobre la última versión de este proyecto abierto simultáneamente, puedes abrir este proyecto de nuevo duplicando esta pestaña en tu navegador.",
        ],
        "revisionBlocked": [
            "¡El guardado está bloqueado por el administrador!",
            "Actualmente, nuestro personal técnico está revisando tu proyecto debido a errores que están ocurriendo en él.",
            "Por favor, espera hasta que la revisión esté completa, luego recibirás un correo electrónico con más instrucciones.",
        ],
        missingVariants: [
            'Error de elementos faltantes',
            'A continuación se muestra la lista de elementos personalizados que faltan en su biblioteca de proyectos y, por lo tanto, no se pueden renderizar:',
            'Por favor, active los conjuntos que contienen estos elementos en el menú de configuración del proyecto (en Taller)'
        ],
        "openInOtherTab": "Abrir último",
        "overwrite": "Sobrescribir",
        "saveToFile": "Guardar en archivo",
        filterSelection_exclude: "Excluir de la selección",
        filterSelection_include: "Incluir en la selección",
        filterSelectionNames: {
            sprinklers: "Consumidores",
            sprinklers_nozzle: "Consumidores - Boquillas",
            sprinklers_rotaryNozzle: "Consumidores - Boquillas rotativas",
            sprinklers_rotor: "Consumidores - Rotores",
            sprinklers_bubbler: "Consumidores - Difusores",
            sprinklers_bubblerNozzle: "Consumidores - Boquillas difusoras",
            sprinklers_pinpoint: "Consumidores - Aspersores de precisión",
            dripStarts: "Inicios de goteo",
            rzwLayer: "Riego en zona radicular",
            dripLines: "Tubos de goteo",
            valvesLayer: "Válvulas principales",
            waterSources: "Fuentes de agua",
            controllers: "Controladores",
            sensorsLayer: "Sensores",
            mainPipes: "Tuberías principales",
            lateralPipes: "Tuberías secundarias",
            trenchesLayer: "Zanjas",
            insetsLayer: "Manguitos",
            wiresLayer: "Cables",
            wirelessLayer: "Conexión inalámbrica",
            senswirelessLayer: "Conexión inalámbrica de sensores",
            senswiresLayer: "Cables de sensores",
            quickCoupLayer: "Acoples rápidos",
            surfaces: "Polígonos y líneas",
            ldItemsLayer: "Elementos del paisaje",
            ldArbitraryLayer: "Elementos de paisaje personalizados",
            spArbitraryLayer: "Elementos de riego personalizados",
            overlays: "Elementos de diseño",
            stampTexts: "Textos de sello"
        },
//CONFIGURACIONES DE NODO DE RIEGO
        sprinklerNode: "Nodo de riego",
        fcType: "Tipo de conexión",
        sj: "Junta de pivote",
        sprinklerStand: "Sprinkler stand (Riser)",
        flexPipeBarbs: "Tubo flexible + conectores",
        minFlexPipeLength: "Longitud mínima de tubería flexible por conexión",
        midSprinkPipeFitting: "Conector de tubería",
        endSprinkPipeFitting: "Conector de final de tubería",
        single_clamp_saddle: "Silla de fijación",
        tee_PTP: "T de conexión con rosca hembra BSP",
        elbow_PT: "Codo con rosca hembra BSP",
        coupling_PT: "Adaptador con rosca hembra BSP",
        //MANIFOLD NODE CONFIGS
        manifoldNode: "Nodo del colector",
        valvesOutlay: "Conexión de válvulas",
        fold: "Plegado",
        unfold: "Desplegado",
        threadsNode: "Conexiones roscadas",
        threadTypes: "Tipos de roscas",
//CONFIGURACIONES DE NODOS DE AUTOMATIZACIÓN
        automationNode: "Nodo de automatización",
        controllerModules: "Los módulos de expansión de los controladores modulares son seleccionados:",
        controllerVoltage: "Voltaje de entrada del controlador:",
        controllerVoltageV2: "Voltaje de entrada del controlador:",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automáticamente (mejor ajuste)",
        userModules: "Manualmente (como accesorios)",
//NODO DE RZW
        rzwNode: "Nodo de riego de la zona radicular",
        midRZWPipeFitting: "Conexión de empalme",
        endRZWPipeFitting: "Conexión final de tubería",
//NODO DE RIEGO POR GOTEO
        dripNode: "Riego por goteo",
        dripConnectionType: "Tipo de conexión de riego por goteo",
        dripLengthPrecision: "Dígitos después del punto decimal en la longitud de la tubería",
        dripTubingAddon: "Aditivo para tubería de riego por goteo",
        barb: "Conexiones de tubería de barra",
        twistLock: "Conexiones de bloqueo de giro",
        dripSpikesStep: "Paso del soporte de la línea de goteo",
        dripCrossFittingAble: "Capaz de conexión en cruz",
        pipesNode: "Sección de tuberías",
        hdpeConnectionType: "Tipo de conexión de tubería HDPE",
        ldpeConnectionType: "Tipo de conexión de tubería LDPE",
        pvcConnectionType: "Tipo de conexiones PVC",
        pipeAddon: "Aditivo de tubería para cada diámetro",
        pipeLengthPrecision: "Dígitos después del punto decimal en longitud de tubería",
        crossFittingAble: "Capaz de conexión cruzada",
        compress: "Conexiones de compresión",
        customfit: "Conexiones personalizadas",
        slip: "Slip fittings",
        wiringNode: "Sección de cableado",
        exportNode: "Opciones de exportación",
        exportNumbersPrecision: "Dígitos después del punto decimal en números",
        basicWiringMethod: "Método de cableado de control",
        cableCoresArray: "Rango de número de núcleos de cable",
        noAutoWiring: "Agregar cableado manualmente",
        separateCableToManifold: "Cable múltiple separado para colectores",
        separateWireToValve: "Cable separado para válvula + cable común para colector",
        maxCableCores: "Máximo de núcleos de cable",
        verticalWiringAddon: "Aditivo vertical para cable de controlador",
        verticalSensWiringAddon: "Aditivo vertical para cable de sensor",
        wireAddon: "Aditivo de cable para cada tipo",
        wireLengthPrecision: "Dígitos después del punto decimal en longitud de cableado",
//DRAWER CONFIG
        drawerConfig: [
            "Configuración del proyecto"
        ],
//SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Consumidores",
        pressureDefinedBy: "La presión esperada en los consumidores es",
        allowReduceRotors: "Se permite reducir el radio de los rotores",
        autoconnector: "Conexión interactiva de aspersores a la tubería lateral",
        radio_option_yes: "Sí",
        radio_option_no: "No",
        extreme_rotor_reduction: "Extremo (Hasta el 50%) (Puede causar precipitación desigual)",
        radio_option_yes2: "Sí",
        takeReductionInAccountWhenAutoPlacing: "Ofrecer distancias de lanzamiento reducidas al colocar aspersores automáticamente",
        takeReductionInAccountWhenAutoPlacingForRotors: "Ofrecer distancias de lanzamiento reducidas al colocar aspersores automáticamente (Rotors)",
        recommendedPressure: "Recomendada por el proveedor",
        userPressure: "Establecida por el usuario",
        expPressure: "Presión esperada en el consumidor",
        sprinklerGroupMode: "Agrupación de consumidores",
        safeSprGroupMode: "Modo estricto (agrupar solo los compatibles)",
        unsafeSprGroupMode: "Modo inseguro (¡ADVERTENCIA! Sin restricciones de agrupación)",
        "sprinklerAttachBulkMode": "Modo de Conexión Masiva de Consumidores",
        "safeSprAttachMode": "No volver a conectar los consumidores ya conectados",
        "unsafeSprAttachMode": "Modo inseguro (¡ADVERTENCIA! Posible reconexión de consumidores ya conectados. Úselo bajo su propio riesgo)",
//CONFIGURACIÓN DE UNIDADES
        unitsConfig: "Unidades de medida",
        precisionStd: "Cifras decimales",
        unitsSystemGridAndRuler: "Sistema de unidades de medida para la cuadrícula y la regla",
        distanceUnits: "Distancia",
        distancePrecision: "Cifras decimales",
        trenchSizeUnits: "Unidades de dimensiones",
        trenchSizePrecision: "Dígitos después del punto decimal",
        sprinklerDistUnits: "Radio del aspersor",
        sprinklerDistPrecision: "Cifras decimales",
        areaUnits: "Área",
        areaPrecision: "Cifras decimales",
        volumeUnits: "Volumen",
        volumePrecision: "Cifras decimales",
        waterFlowUnits: "Caudal de agua",
        waterFlowPrecision: "Cifras decimales",
        pressureUnits: "Presión",
        pressurePrecision: "Cifras decimales",
        velocityUnits: "Velocidad",
        velocityPrecision: "Cifras decimales",
        precipRateUnits: "Tasa de precipitación",
        precipRatePrecision: "Cifras decimales",
//CONFIGURACIÓN DE PROPIEDADES DE ZONA
        climateConfig: "Cálculo del tiempo de riego",
        lawnCultureType: "Tipo de césped",
        coolLoving: "De clima fresco",
        warmLoving: "De clima cálido",
        climateTemp: "Temperatura media del verano",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Humedad media del verano",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Microclima de la zona <i class='far fa-question-circle'></i>",
        microClimateTooltip: "Suave\n" +
            "Áreas de riego que están a la sombra, protegidas del viento y alejadas de objetos secos y calentados\n" +
            "\n" +
            "Normal\n" +
            "Lugares en el paisaje donde se representan las condiciones microclimáticas: la presencia de\n" +
            "edificios, aceras y caminos, sombra, etc. no afectan significativamente los valores de\n" +
            "evapotranspiración\n" +
            "\n" +
            "Áspero\n" +
            "Refleja condiciones que impiden el crecimiento de las plantas y fácilmente se traduce en un estado de estrés si la planta no es regada adecuadamente. Puede ser un lugar abierto, bajo el sol ardiente, en cercanía a pasillos, edificios u otras estructuras del paisaje, reflejando la luz de vidrio o elementos del paisaje que absorben el calor, o puede ser un lugar ventoso.",
        gentleMicroClimate: "Suave",
        normalMicroClimate: "Normal",
        toughMicroClimate: "Áspero",
        soilType: "Composición del suelo en las zonas",
        sand: "Arenoso",
        sandyLoam: "Franco arenoso",
        lightLoam: "Franco",
        mediumLoam: "Franco limoso",
        heavyLoam: "Franco arcilloso",
        clay: "Arcilloso",
        heavyClay: "Arcilla pesada",
        zoneSlope: "Inclinación general en las zonas",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Presupuesto de agua",
        lowWB: "Bajo",
        normalWB: "Normal",
        highWB: "Alto",
        ft: "pies",
        in: "pulgada",
        ftin: "pies/pulgadas",
        metric: "métrico",
        imperialUS: "imperial (EE.UU.)",
//UNITS CONFIG
        hydraConfig: "Hidráulica",
        waterTemp: "Temperatura del agua",
        maxFlowVelocity: "Velocidad máxima del flujo en tubería",
        "commonConfig": "Configuraciones comunes",
        "lateralNozzlerSwitch": "Cómo cambiar al modo de acople de boquillas",
        "NStabonly": "Tab",
        "NStabshift": "Tab+Shift",
        "showActionSubtitles": "Mostrar subtítulos de acción",
        "Yeah": "Sí",
        "Nope": "No",
        start: "Iniciar",
        recalibrate: "Re-calibrar",
        calibrationSuccess: [
            "Calibrado exitosamente",
            "Ahora puedes usar la pantalla táctil en dos modos: 'mover cursor' (movimiento ligero al tocar) y 'modo arrastrar' (movimiento fuerte al tocar)"
        ],
        calibrationFailEqual: [
            "Calibración fallida",
            "No detectamos ninguna diferencia significativa en la forma en que tocas la pantalla en ambos modos",
            "Puedes intentarlo de nuevo. Y asegúrate de estar usando tu dedo, no un lápiz"
        ],
        calibrationFailImproper: [
            "Calibración fallida",
            "Detectamos más presión en la pluma que en el yunque",
            "Puedes intentarlo de nuevo. Y asegúrate de mover la pluma con menos presión que el yunque"
        ],
        calibrationImpossible: [
            "Calibración imposible",
            "Parece que tu dispositivo no soporta la medición del área táctil. Por lo tanto, no podemos definir dos modos para la interacción táctil",
            "En este caso, puedes usar un ratón virtual para poder arrastrar cualquier cosa. Aparecerá en el lado izquierdo de la pantalla."
        ],
        calibrationNeeded: [
            "¡Calibración necesaria!",
            "Tenemos que calibrar tu pantalla táctil para poder definir dos modos de interacción táctil:",
            "Modo mover cursor - cuando solo quieres mover el cursor o el segmento de polígono al dibujar",
            "Y modo arrastrar - cuando quieres mover elementos o cambiar su tamaño. También debes mover-arrastar cuando quieras seleccionar varios elementos",
            "Por favor, haz clic en el botón Iniciar y sigue las instrucciones en pantalla"
        ],
        insertImage: 'Insertar',
        mapImagePicker: [
            "Cargador de imágenes satelitales",
            "Latitud/Longitud",
            "Ingresar latitud",
            "Ingresar longitud",
            "Ubicación actual",
            "Ir",
            "Dirección",
            "Escriba parte de la dirección y haga clic en 'Buscar'",
            "Buscar",
            "Zoom",
            "Panorámica"
        ],
        "imageCrop": [
            "Crop tool"
        ],
        cropImage: "Crop",
        invalid_dataset_1: 'Invalid dataset. Project contains prohibited types of surfaces. Only irrigated (LAWN), non-irrigated and obstacles are allowed.',
        invalid_dataset_2: 'Invalid dataset. Not more or less than ONE irrigated surface is allowed.',
        invalid_dataset_3: 'Invalid dataset. Irrigated surface is self-intersected.',
        invalid_dataset_4: 'Invalid dataset. Obstacle marker should not be compound (Made of more than one polygon)',
        invalid_dataset_5: 'Invalid dataset. Obstacle surface should be fully contained within irrigated surface.',
        invalid_dataset_6: 'Invalid dataset. Project contains prohibited types of sprinklers. Allowed:',
        invalid_dataset_7: 'Invalid dataset. Precipitation rate of sprinklers is out of range',
        invalid_dataset_8: 'Invalid dataset. Sprinklers must not have individual pressure settings',
        invalid_dataset_9: 'Invalid dataset. The project should not set a custom expected pressure at the sprinklers',
        invalid_dataset_10: 'Invalid dataset. Uniformity is too low.',
        invalid_dataset_11: 'Invalid dataset. Overwatered area is too big.',
        layoutPresetsMenu: [
            "Preajustes de diseño",
            "Preajuste de diseño actual",
            "Preajuste de conjunto de diseños",
            "Preajuste predeterminado para nuevo diseño:",
            "- Elegir preajuste -",
            "- No hay preajustes disponibles -"
        ],
        edit: "Editar",
        nozzleCharacteristicsConfig: "Configuraciones de características de boquilla",
        nozzleCharacteristicsConfig_lang: {
           // Main editor
           title: "Configuración de características de boquilla",
           save: "Guardar",
           cancel: "Cancelar",
           reset: "Restablecer",
           typeArc: "Arco",
           typeStrip: "Franja",
           typeVariableArc: "Arco variable",
           unknown: "Desconocido",
           object: "Objeto",
           selectVariant: "Seleccionar variante",
           editVariant: "Editar variante",

           // Variant editor fields
           editData: "Editar datos de rendimiento",
           editPrecipMap: "Editar mapa de precipitación",
           pressuresLabel: "Presiones",
           anglesLabel: "Ángulos",
           valuePairsLabel: "Pares de valores",
           valuesLabel: "Valores",
           pointsLabel: "puntos",
           valuesSuffix: "valores",
           pairsSuffix: "pares",
           none: "ninguno",

           // Field name labels
           pressMap: "Presión",
           angleMap: "Ángulo",
           valuesMap: "Valores",
           precipMap: "Precipitación",
           reducableBy: "Multiplicador de reducción (0.0 - 1.0)",

           // Error messages
           invalidInputFormat: "Formato de entrada no válido.",
           fieldInvalidFormat: "Formato no válido.",
           reducableByOutOfRange: "El valor debe estar entre 0.01 y 0.99.",

           // NozzleDataEditor translations (passed to that editor)
           dataEditor: {
               modeSingle: "Ángulos individuales",
               modeRange: "Rangos de ángulos",
               pressureAngleLabel: "Presión/Ángulo",
               pressure: "Presión",
               angle: "Ángulo",
               distance: "Distancia",
               flow: "Caudal",
               addRow: "Añadir fila",
               addCol: "Añadir columna",
               delete: "Eliminar",
               save: "Guardar",
               cancel: "Cancelar",
               reset: "Restablecer",
               distanceUnit: "Unidad de distancia",
               pressureUnit: "Unidad de presión",
               flowUnit: "Unidad de caudal",
               angleMode: "Modo de ángulo:",
               cannotDeleteLastRow: "¡No se puede eliminar la última fila!",
               cannotDeleteLastColumn: "¡No se puede eliminar la última columna!",
               angleRangesCannotIntersect: "¡Los rangos de ángulos no pueden intersecarse!",
               pleaseFillAllCells: "¡Por favor complete todas las celdas! Celdas vacías:",
               row: "Fila",
               col: "Columna"
           },

           // PrecipMapEditor translations (passed to that editor)
           precipEditor: {
               precipitation: "Precipitación",
               distance: "Distancia",
               addCol: "Añadir columna",
               delete: "Eliminar",
               save: "Guardar",
               cancel: "Cancelar",
               reset: "Restablecer",
               precipitationUnit: "Unidad de precipitación",
               cannotDeleteLastColumn: "¡No se puede eliminar la última columna!"
           }
        },
        experimentalConfig: "Funciones experimentales",
        autoNozzlePlacer: "Asistencia de colocación de boquillas en el césped (ALT desactiva)",
        stylesConfig: "Estilos",
        nozzlesStyles: "Estilos de aspersores",
        nozzlesStyles_lang : {
            title: "Configuración de estilos de boquillas",
            save: "Guardar",
            cancel: "Cancelar",
            reset: "Restablecer valores predeterminados",
            // Group headers
            nozzleCoverGroup: "Colores de la cubierta de boquilla",
            // Color labels
            coverFillColor: "Color de relleno de cubierta",
            underpressFillColor: "Color de relleno de cubierta a baja presión",
            overpressFillColor: "Color de relleno de cubierta a alta presión"
        },
        linesStyles: "Estilos de tuberías y cableado",
        linesStyles_lang: {
            title: "Configuración de estilos de líneas",
            save: "Guardar",
            cancel: "Cancelar",
            reset: "Restablecer valores predeterminados",
            // Group headers
            mainPipeGroup: "Colores de tubería principal",
            lateralPipeGroup: "Colores de tubería lateral",
            dripLinesGroup: "Colores de líneas de goteo",
            wiresGroup: "Colores de cables",
            // Color labels
            mpColor: "Tubería principal",
            mpOverColor: "Tubería principal (Hover)",
            mpPVCColor: "Tubería principal PVC",
            mpPVCOverColor: "Tubería principal PVC (Hover)",
            mpPVCMSColor: "Tubería principal PVC Multi-hilo",
            mpPVCMSOverColor: "Tubería principal PVC Multi-hilo (Hover)",
            lpColor: "Tubería lateral",
            lpOverColor: "Tubería lateral (Hover)",
            lpPVCColor: "Tubería lateral PVC",
            lpPVCOverColor: "Tubería lateral PVC (Hover)",
            lpPVCMSColor: "Tubería lateral PVC Multi-hilo",
            lpPVCMSOverColor: "Tubería lateral PVC Multi-hilo (Hover)",
            lpLDPESColor: "Tubería lateral LDPE-S",
            lpLDPESOverColor: "Tubería lateral LDPE-S (Hover)",
            dl16Color: "Línea de goteo 16mm",
            dl16OverColor: "Línea de goteo 16mm (Hover)",
            dl17Color: "Línea de goteo 17mm",
            dl17OverColor: "Línea de goteo 17mm (Hover)",
            wrColor: "Cable",
            wrOverColor: "Cable (Hover)",
            wrlsColor: "Inalámbrico",
            wrlsOverColor: "Inalámbrico (Hover)",
            swrColor: "Cable de sensor",
            swrOverColor: "Cable de sensor (Hover)",
            swrlsColor: "Sensor inalámbrico",
            swrlsOverColor: "Sensor inalámbrico (Hover)",
            dwrColor: "Cable de datos",
            dwrOverColor: "Cable de datos (Hover)"
        },
        continuousPlacementMode: "Modo de colocación continua",
    }
};
