this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "pieds/pouces",
        sqm: "m²",
        acre: "ac",
        hectare: "ha",
        sqft: "pi²",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gal",
        lpm: "lpm",
        lph: "lph",
        m3h: "m³/h",
        USgpm: "gpm",
        USgph: "gph",
        deg: "°",
        pcs: "pcs",
        pcsDot: "pcs.",
        pcsShort: "pcs.",
        percent: "%",
        in_Alt: "in.",
        mps: "m/s",
        kph: "km/h",
        ftps: "ft/s",
        degreesCentigrade: "°C",
        mmph: "mm/h",
        mmp24h: "mm/jour",
        inph: "po/h",
// non convertissable
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Tiroir automatique",
        chooseSprinkler: "Choisir une buse:",
        auto: "Réglage automatique",
        waterSource2row: ["Eau", "Prise"],
        setLineLength: "Définir la taille de la conduite (mm) :",
        setPressure: "Définir la pression dynamique attendue aux buses (bar) :",
        setMaxFlow: "Définir le débit d'eau maximum (l/min) :",
        controllerShort: "C",
        sensorShort: "S",
        action_activateEraser: "Activer la gomme",
        action_deactivateEraser: "Désactiver la gomme",
        action_boolUnite: "Unir",
        action_boolIntersect: "Intersection",
        action_boolSubtract: "Soustraire",
        action_boolExclude: "Exclure",
        action_changeSprayBody: "Définir le corps de la buse",
        action_changeVariant: "Définir la variante",
        action_changeImgVariant: "Définir la variante d'image",
        action_changeType: "Définir le type",
        action_addConsumers: "Ajouter des consommateurs",
        action_drawBranches: "Ajouter des branches",
        action_editLine: "Modifier les segments",
        action_drawCircles: "Dessiner des cercles",
        action_detachAll: "Détacher tout",
        action_drawBrush: "Dessiner une brosse",
        action_editBrush: "Modifier la brosse",
        action_changeBrushSize: "Taille de la brosse",
        action_booleans: "Opérations booléennes",
        action_intoPoly: "Transformer en polygone",
        action_intoBrush: "Transformer en brosse",
        action_activateRotation: "Faire pivoter",
        action_deactivateRotation: "Ne pas faire pivoter",
        action_markZones: "Représentation des zones",
        action_unmarkZones: "Supprimer le marquage",
        action_sprNames: "Noms des arroseurs",
        action_noSprNames: "Supprimer les noms",
        action_lockItem: "Verrouiller",
        action_unlockItem: "Déverrouiller",
        Circle: "Cercle",
        Triangle: "Triangle",
        BushForm: "Arbuste",
        BushForm1: "Arbuste 1",
        BushForm2: "Arbuste 2",
        BushForm3: "Arbuste 3",
        Square: "Carré",
        noShadow: "Aucune",
        standardShadow: "Standard",
        noArrows: "Aucune",
        startArrow: "Au début",
        endArrow: "À la fin",
        bothArrows: "Des deux côtés",
        normalSizeSide: "Normal",
        invertedSizeSide: "Inversé",
        strMiter: "En pointe",
        strRound: "Arrondi",
        strBevel: "Biseauté",
        strSquare: "Carré",
        strButt: "Coupé",
        FWnormal: "Normal",
        FWbold: "Gras",
        FWitalic: "Italique",
        FWbolditalic: "Gras Italique",
        FJleft: "Gauche",
        FJright: "Droite",
        FJcenter: "Centré",
        rzwHeight: "Hauteur"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Sélecteur",
//----Dessin
        selectPoly: "Aucun élément sélectionné",
//----Arrosage
        selectSprink: "Aucun élément sélectionné",
        lpNozzler: "Ajout de consommateurs d'eau",
        dl16CircDrawer: "Dessin de cercles de goutte à goutte 16/13mm",
        dl16sDrawer: "Dessin de couvercles de goutte à goutte 16/13mm",
        dl17CircDrawer: "Dessin de cercles de goutte à goutte 17mm",
        dl17sDrawer: "Dessin de couvercles de goutte à goutte 17mm",
        "ldTextDrawer": "Configuration du Texte",
        "staticTextDrawer": "Configuration du Texte",
        "dynamicTextDrawer": "Configuration du Texte",
        "ldStaticTextDrawer": "Configuration du Texte",
        "ldtextEditor": "Édition du Texte",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Distance totale",
        type: "Type",
        variant: "Variante",
        area: "Zone",
        perimeter: "Périmètre",
        curveLength: "Longueur",
        treeDiameter: "Diamètre de l'arbre",
        bushDiameter: "Diamètre de l'arbuste",
        nozTypes: "Types disponibles",
        nozType: "Type",
        sprBod: "Corps de la buse",
        rad: 'Rayon',
        angle: 'Angle',
        reducedBy: 'Réduit de',
        consump: 'Consommation',
        pressure: 'Pression',
        coverSize: 'Surface de couverture',
        maxFlow: 'Débit maximum',
        pipesNum: "Tuyaux raccordés",
        pipeType: "Type",
        pipeLength: "Longueur",
        wireLength: "Longueur",
        valvesManifNum: "Collecteurs de vannes",
        valvesNum: "Vannes",
        propDiam: "Diamètre correct",
        curDiam: "Diamètre de dessin",
        outsNum: "Consommateurs d'eau",
        flow: "Débit d'eau",
        precipRate: "Taux de précipitation",
        totalPrecipArea: "Surface totale",
        uniformity: "Uniformity (CU)",
        overwatered: "Overwatered",
        precipRateShort: "Précip.",
        runtimeInd: "Temps d'exécution",
        coveredArea: "Surface",
        microClimateInd: "M/Climate",
        soilTypeInd: "Sol",
        zoneSlopeInd: "Pente",
        maxInfiltrationRate: "Taux d'infiltration",
        waterDemand: "Besoin en eau",
        numOfRuns: "Nombre de cycles par jour",
        timePerRun: "Durée de chaque cycle",
        dailyConsumption: "Consommation quotidienne",
        dripsNum: "Lignes de goutte à goutte connectées",
        dripType: "Type de goutte à goutte",
        dripRowsStep: "Écartement entre les rangées",
        dripRowsAngle: "Angle entre les rangées",
        cntrType: "Type de contrôleur",
        sensType: "Type de capteur",
        zonesNum: "Zones contrôlées",
        trenchWidth: "Largeur",
        trenchDepth: "Profondeur",
        trenchVolume: "Volume",
        insetDiam: "Diamètre",
        insetLength: "Longueur",
        insetVar: "Matériau",
        itemsCount: "Quantité",
        insetDepth: "Profondeur",
        zoneName: "Nom de la zone",
        valveName: "Boîtier de vanne",
        itemAlias: "Alias",
        lineWidth: "Largeur",
        lineDepth: "Profondeur",
        lineArea: "Surface",
        lineVolume: "Volume",
        surfaceDepth: "Profondeur/Hauteur",
        surfaceVolume: "Volume",
//MULTISELECTOR
        itemsSelected: "Sélectionné(s)",
        totalArea: "Surface totale",
        totalPerimeter: "Périmètre total",
        totalLength: "Longueur totale",
        totalVolume: "Volume total",
        totalConsumption: "Consommation totale",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Polygone invalide",
        isSelfCrossing_false: "Polygone valide",
        isConnected_true: "Connecté",
        isConnected_false: "Non connecté",
        isWired_true: "Câblé",
        isWired_false: "Non câblé",
        isDripZone_true: "Zone de goutte à goutte",
        isDripZone_false: "",
        isSprinklerZone_true: "Zone d'arrosage",
        isSprinklerZone_false: "",
        isOverloaded_true: "SURCHARGE !!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Pression faible",
        isUnderpressured_false: "",
        isOverpressured_true: "Haute pression",
        isOverpressured_false: "",
        isLocked_true: "Verrouillé",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Acier inoxydable",
        "High speed": "Haute vitesse",
        "Opposing nozzle": "Opposing nozzle",
        "Plastic": "Plastique",
        "MPR Nozzles": "Buses MPR",
        "Rotary Nozzles": "Buses rotatives",
        Nozzles: "Buses",
        "Bubbler nozzles": "Buses de bullage",
        "Multi-stream": "Multijets",
        "Dual-stream": "Double jet",
        "Stream Nozzles": "Buses de jet",
        "Short Radius Nozzles": "Buses à faible rayon",
        "Pressure compensating": "Compensation de pression",
        "Adjustable flood": "Inondation ajustable",
        Adjustable: "Ajustable",
        Fixed: "Fixe",
        "Fixed Arc": "Arc fixe",
        "Strip Pattern": "Motif de bande",
        "Drip line": "Ligne de goutte à goutte",
        "Drip cover": "Couverture de goutte à goutte",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "Avec émetteurs",
        "noemitter": "Sans émetteurs",
        "Root zone watering": "Arrosage de la zone racinaire",
        Lateral: "Latéral",
        Main: "Principal",
        Trench: "Tranchée",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC(Metric)",
        ldpe: "LDPE",
        Controller: "Contrôleur",
        Sensor: "Capteur",
        Wiring: "Connexion",
        IrrigateMarks: "Zones",
        Surface: "Surface",
        Lawn: "Pelouse",
        Bed: "Parterre",
        Shrubs: "Arbustes",
        Path: "Chemin",
        Concrete: "Béton",
        Sand: "Sable",
        Water: "Eau",
        Bedding: "Couverture",
        Flower: "Fleur",
        Herbal: "Herbes",
        geographic: "Géographique",
        sizeMark: "Dimensions",
        scalingBar: "Barre d'échelle",
        loCurves: "Lignes",
        texts: "Textes",
        staticText: "Texte statique",
        dynamicText: "Texte dynamique",
        stampText: "Texte d'empreinte",
        stampTextDefault: "Texte",
        stampTextgr1: "Définition du document",
        stampTextgr2: "Cellule d'adresse",
        stampTextgr3: "Nom du site",
        stampTextgr4: "Nom du dessin",
        stampTextgr9: "Informations d'organisation",
        stampTextgr6t: "Étape",
        stampTextgr7t: "Page",
        stampTextgr8t: "Pages",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Ch.",
        stampTextgr15t: "Prtcp.",
        stampTextgr16t: "Page",
        stampTextgr17t: "# Doc.",
        stampTextgr18t: "Sign.",
        stampTextgr19t: "Date",
        stampTextgr20t: "Inv. d'orig.",
        stampTextgr21t: "Sign. et date",
        stampTextgr22t: "Inv. de remplacement",
        inserts: "Manchons de tuyaux",
        poly: "Polygone",
        brush: "Pinceau",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Afficher le gestionnaire de calques",
        hideLM: "Masquer le gestionnaire de calques",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Sans nom",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Exportation de la mise en page en cours",
        successExporting: "Exportation réussie",
        failExporting: "Échec de l'exportation",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Limite quotidienne atteinte</a>",
        exportingLimit: "Limite : ",
        exportingLeft: "Reste aujourd'hui : ",
        pdfExportingPopUpBlocked: "Votre navigateur a bloqué la fenêtre pop-up. Veuillez autoriser les pop-ups pour ce site afin d'obtenir le fichier .PDF",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Filetage popup",
        tt_group_MT: "Mâle",
        tt_group_FT: "Femelle",
        tt_riserHeight: "Hauteur de riser",
        tt_pressureReg: "Régulateur de pression",
        tt_checkValve: "(Avec clapet anti-retour)",
        tt_home: "Accueil",
        tt_prev: "Précédent",
        tt_next: "Suivant",
        tt_end: "Fin",
        tt_add: "Ajouter",
        tt_clone: "Dupliquer",
        tt_remove: "Supprimer",
        tt_rename: "Renommer",
        tt_addToFav: "Ajouter aux favoris",
        tt_remFromFav: "Retirer des favoris",
        tt_presets: "Préréglages",
        tt_MagicAutoPlacer: "`Placement automatique le long de la ligne`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "N",
        S: "S",
        E: "E",
        W: "W",
        //conventions
        sprinklers: "Arroseurs",
        dripStarts: "Départs goutte à goutte",
        rzwLayer: "Arrosage racinaire",
        dripLines: "Lignes de goutte à goutte",
        valvesLayer: "Collecteur de vannes",
        waterSources: "Source d'eau",
        quickCoupLayer: "Raccord rapide",
        controllers: "Contrôleur",
        sensorsLayer: "Capteur",
        mainPipes: "Tuyau principal",
        lateralPipes: "Tuyaux latéraux",
        lateralPipes_sprinklerZone: "Zone (Arroseurs)",
        lateralPipes_dripZone: "Zone (Lignes de goutte à goutte)",
        lateralPipes_rzwZone: "Zone (Arrosage racinaire)",
        lateralPipes_emptyZone: "Zone (Sans consommateurs)",
        trenchesLayer: "Tranchées",
        insetsLayer: "Manches",
        wiresLayer: "Câblage",
        wirelessLayer: "Connexion sans fil",
        senswiresLayer: "Connexion sans fil des capteurs",
        senswiresLayer: "Câblage du capteur",
        surfaces: "Surfaces",
        ldItemsLayer: "Plantes",
        covers: "Zone de couverture",
        nameplates: "Infos consommateurs",
        oreolas: "Marques de consommateurs",
        pipeInfo: "Infos tuyaux",
        lines: "Lignes",
        overlays: "Superpositions",
        stampLayer: "Cadre",
        stampTexts: "Textes de tampon",
//zonesTable
        zoneType: "Type de zone",
        color: "Couleur",
        consumers: "Consommateurs",
        waterFlow: "Débit",
        sprinklerZone: "Arroseur",
        dripZone: "Goutte à goutte",
        rzwZone: "Arrosage racinaire",
        emptyZone: "Pas de consommateurs",
        specifyDiagonal: "Veuillez spécifier la taille de votre écran en diagonale en pouces",
//sprinklersTable
        consType: "Type de consommateur",
        consName: "Nom",
        zoneNum: "Zone",
        sector: "Secteur",
        radius: "Rayon",
        reducedBy: "Réduit de",
        nozzle: "Buse",
        rotor: "Rotor",
        bubbler: "Bubbler",
        bubblerNozzle: "Buse-Bubbler",
//dripsTable
        catId: "ID Catégorie",
        brand: "Marque",
        emitterStep: "Pas",
        emitterFlow: "Débit",
//layersManangerSpecific
        consumersGrp: "Consommateurs",
        nodesGrp: "Nœuds",
        wiresGrp: "Câbles",
        pipesGrp: "Tuyaux",
        landscapeGrp: "Paysage",
        allTogether: "Tous"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Type",
        brand: "Marque",
        catid: "Cat.ID",
        title: "Titre",
        units: "Unités",
        amount: "Quantité",
//predetermined
        dripLine: "Ligne de goutte-à-goutte",
        dl16: "Ligne de goutte-à-goutte 16/13mm",
        dl17: "Ligne de goutte-à-goutte 17mm",
        dripStart: "Départ goutte-à-goutte",
        ds16: "Départ goutte-à-goutte 16/13mm",
        ds17: "Départ goutte-à-goutte 17mm",
        manifold_no_lps_issue: "Aucune zone connectée",
        manifold_no_mp_issue: "Non connecté à la ligne principale",
        manifold_no_wr_issue: "Aucun fil de commande attaché",
        //nodes-----------------------------------
        sprinkler_unattached: "ATTENTION !!! Vous avez des arroseurs non attachés (ils ne seront pas présentés dans la fiche technique finale)",
        drip_unattached: "ATTENTION !!! Vous avez des éléments d'irrigation au goutte-à-goutte non attachés (ils ne seront pas présentés dans la fiche technique finale)",
        mains_unattached: "ATTENTION !!! Vous avez des canalisations principales non attachées (elles ne seront pas présentées dans la fiche technique finale)",
        mains_empty: "ATTENTION !!! Vous avez des canalisations principales sans consommateurs (elles ne seront pas présentées dans la fiche technique finale)",
        laterals_unattached: "ATTENTION !!! Vous avez des tuyaux latéraux non attachés (ils ne seront pas présentés dans la fiche technique finale)",
        laterals_empty: "ATTENTION !!! Vous avez des tuyaux latéraux sans consommateurs (ils ne seront pas présentés dans la fiche technique finale)",
        rzw_unattached: "ATTENTION !!! Vous avez des éléments d'arrosage de la zone racinaire non attachés (ils ne seront pas présentés dans la fiche technique finale)",
        sensors_unattached: "ATTENTION !!! Vous avez des capteurs non attachés (ils ne seront pas présentés dans la fiche technique finale)",
        manifolds_unfinished: "ATTENTION !!! Vous avez des collecteurs inachevés (vous ne pouvez pas compléter la configuration des vannes)",
        control_wires_unattached: "ATTENTION !!! Vous avez des fils de contrôle non connectés",
        control_wires_empty: "ATTENTION !!! Vous avez des fils de contrôle sans vannes connectées",
        cntr_wr_unattached: "Fil de commande",
        youCanSeeThemInTheDrawing: "Vous pouvez voir chaque élément sur le dessin en appuyant sur l'œil à gauche de la ligne de l'élément",
        sprinkler_nozzleMT: "Buse d'arrosage (buse à filetage femelle)",
        sprinkler_nozzleFT: "Buse d'arrosage (buse à filetage mâle)",
        "sprinkler_rotor1/2F": "Buse d'arrosage (rotor) 1/2\" femelle",
        "sprinkler_rotor3/4F": "Buse d'arrosage (rotor) 3/4\" femelle",
        "sprinkler_rotor1F": "Buse d'arrosage (rotor) 1\" femelle",
        "sprinkler_rotor11/4F": "Nœud de l'arroseur (Rotor) 1 1/4\"",
        "sprinkler_rotor11/2F": "Nœud de l'arroseur (Rotor) 1 1/2\"",
        "sprinkler_rotor2F": "Nœud de l'arroseur (Rotor) 2\"",
        "sprinkler_rotor1/2M": "Buse d'arrosage (rotor) 1/2\" mâle",
        "sprinkler_rotor3/4M": "Sprinkler node (Rotor) 3/4\" male",
        "sprinkler_bubbler1/2F": "Buse d'arrosage (arroseur)",
        sprinkler_bubblerNozzleMT: "Buse d'arrosage (embout arroseur à filetage femelle)",
        sprinkler_bubblerNozzleFT: "Buse d'arrosage (embout arroseur à filetage mâle)",
        dripIrrigation16: "Irrigation goutte à goutte (16/13mm)",
        dripIrrigation17: "Irrigation goutte à goutte (17mm)",
        rootZoneWatering: "Système d'arrosage de la zone racinaire",
        manifold: "Nœud de collecteur de vannes",
        automation: "Nœud d'automatisation",
        mainPipes_hdpePE80SDR11: "Tubes principaux HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Tubes principaux HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Tubes principaux HDPE SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Tuyaux latéraux HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Tuyaux latéraux HDPE SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Tuyaux latéraux HDPE SDR 17.6",
        mainPipes_hdpeSDR9: "Tubes principaux HDPE SDR 9",
        mainPipes_hdpeSDR11: "Tubes principaux HDPE SDR 11",
        mainPipes_hdpeSDR136: "Tubes principaux HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Tubes principaux HDPE SDR 17",
        mainPipes_hdpeSDR176: "Tubes principaux HDPE SDR 17.6",
        lateralPipes_hdpeSDR9: "Tuyaux latéraux HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Tuyaux latéraux HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Tuyaux latéraux HDPE SDR 13.6",
        lateralPipes_hdpeSDR17: "Tuyaux latéraux HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Tuyaux latéraux HDPE SDR 17,6",
        mainPipes_pvcSCH40: "Tuyaux principaux en PVC SCH40",
        mainPipes_pvcSCH80: "Tuyaux principaux en PVC SCH80",
        mainPipes_pvcCL315: "Tuyaux principaux en PVC CLASS 315",
        mainPipes_pvcCL200: "Tuyaux principaux en PVC CLASS 200",
        mainPipes_pvcCL160: "Tuyaux principaux en PVC CLASS 160",
        mainPipes_pvcCL125: "Tuyaux principaux en PVC CLASS 125",
        mainPipes_pvcUSCJPN18: "Main pipes PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Main pipes PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Main pipes PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Main pipes PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Main pipes PVC-U SCJ (PN4.5)",
        mainPipes_ldpeCLASS3: "Tuyaux principaux en LDPE CLASS 3",
        lateralPipes_pvcSCH40: "Tuyaux latéraux en PVC SCH40",
        lateralPipes_pvcSCH80: "Tuyaux latéraux en PVC SCH80",
        lateralPipes_pvcCL315: "Tuyaux latéraux en PVC CLASS 315",
        lateralPipes_pvcCL200: "Tuyaux latéraux en PVC CLASS 200",
        lateralPipes_pvcCL160: "Tuyaux latéraux en PVC CLASS 160",
        lateralPipes_pvcCL125: "Tuyaux latéraux en PVC CLASS 125",
        lateralPipes_pvcUSCJPN18: "Lateral pipes PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Lateral pipes PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Lateral pipes PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Lateral pipes PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Lateral pipes PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Tuyaux latéraux en LDPE CLASS 3",
        wiring: "Câblage",
        qcv: "Vannes de raccord rapide",
        fixedCntr: "fixe",
        stand_aloneCntr: "autonome",
        modularCntr: "modulaire",
        decoderCntr: "décodage",
        inset: "Manchon de tuyau",
        insets: "Manchons",
        //-----------------------------------------
        novar: "pas de variantes",
        choosevar: "choisir une variante",
        //element.types----------------------------
        nozzle: "Buse",
        rotor: "Rotor",
        rotorNozzle: "Buse de rotor",
        bubbler: "Arroseur bubleur",
        bubblerNozzle: "Buse arroseur-bubleur",
        rzw: "Système d'arrosage de la zone racinaire",
        sprayBody: "Corps d'arroseur",
        sprinklerStandAssembly: "Sprinkler stand (Riser)",
        outBarb: "Barb to nozzle",
        flexPipe: "Tuyau souple",
        sj: "Joint pivotant",
        inBarb: "Barb-to-pipe",
        midSprinkPipeFitting: "Raccord en T",
        endSprinkPipeFitting: "Raccord de fin de tuyau",
        midRZWPipeFitting: "Raccord en T",
        endRZWPipeFitting: "Raccord de fin de tuyau",
        dripPipe: "Tuyau d'égouttement",
        blindPipe: "Tuyau borgne",
        dripTeeFitting: "Té d'égouttement",
        dripCapFitting: "Bouchon d'égouttement",
        dripCouplingFitting: "Raccord d'égouttement",
        dripElbowFitting: "Coude d'égouttement",
        dripSpike: "Pointe d'égouttement",
        sprinklerZoneValve: "Vanage de zone d'arrosage",
        emptyZoneValve: "Vanage sans consommateurs",
        valveOutFitting: "Valve-to-zone",
        dripZoneValve: "Vanage de zone d'égouttement",
        rzwZoneValve: "Vanage d'arrosage de la zone racinaire",
        pressureReg: "Régulateur de pression",
        filter_pressureReg: "Filtre avec régulateur de pression",
        controller: "Contrôleur",
        flowMeter: "Débitmètre",
        rainSensor: "Capteur de pluie",
        soilSensor: "Capteur d'humidité du sol",
        freezeSensor: "Capteur de gel",
        wrFreezeSensor: "Capteur de pluie/gel sans fil",
        windSensor: "Capteur de vent",
        solarSensor: "Capteur solaire",
        flowSensor: "Capteur de débit",
        weatherStation: "Station météo",
        solarPanel: "Panneau solaire",
        mainPipe: "Conduite principale",
        teeFitting: "Té",
        elbowFitting: "Coude",
        reducerFitting: "Réducteur",
        lateralPipe: "Tuyau latéral",
        capFitting: "Bouchon",
        basicCable: "Câble de base",
        basicWire: "Fil de base",
        sensorCable: "Câble de capteur météo",
        qcPlastic: "Valve Q/C en plastique",
        qcMetal: "Valve Q/C en métal",
        gateway: "Gateway",
        antExt: "Antenna extension",
        loramod: "LoRa modules",
        //typesOfAcessories
        hdpeCOR: "Tuyau ondulé en HDPE",
        expModule: "Module d'extension",
        rzwSleeve: "Manchon en tissu",
        rwCap: "Capuchon d'eau récupérée",
        gutterMount: "Monture de gouttière",
        delayRelay: "Relais de retard",
        fctFlow: "Té pour prise FCT",
        fctBspAdap: "Adaptateur pour raccord FCT",
        drainCheckValve: "Clapet anti-retour",
        rwId: "ID d'eau récupérée",
        vpc: "Capuchon antivandalisme",
        inletFilter: "Filtre d'entrée",
        wifiModule: "Module Wi-Fi",
        wallMount: "Montage mural",
        rwsSock: "Manchon en tissu",
        rwsGrate: "Grille pour RWS",
        npCover: "Couverture d'eau non potable",
        sprExt: "Extension d'arroseur",
        popUpToThread: "Adaptateur d'arroseur",
        valveBox: "Boîte de vanne",
        valveBoxExt: "Extension de boîte de vanne",
        qcPlasticKey: "Clé pour vanne Q/C en plastique",
        qcPlasticElbFit: "Raccord coudé",
        qcMetalKey: "Clé pour vanne Q/C en métal",
        qcMetalElbFit: "Raccord coudé",
        qcMetalCapKey: "Clé de couverture",
        insTape: "Ruban isolant",
        wrConn: "Connecteur",
        shrinkTube: "Tube thermorétractable",
        hcFrontPanel: "Panneau frontal",
        ball_valve: "Vannde à bille",
        check_valve: "Clapet anti-retour",
        thread_manifold: "Collecteur fileté",
        plastic_filter: "Filtre (en plastique)",
        waterMeter: "Compteur d'eau",
        rfModule: "Module radio",
        largeAntenna: "Antenne",
        wifiHub: "Concentrateur Wi-Fi",
        handRemoteKit: "Kit de télécommande",
        handRemote: "Télécommande",
        wifiBundleKit: "Kit de groupage Wi-Fi",
        //typesOfFittings
        //drip
        barb_cap_8: "Fermeture d'extrémité pour goutteurs",
        barb_elbow_PP: "Coude avec raccord barbelé",
        barb_elbow_PT: "Coude avec raccord barbelé et fileté",
        barb_tee_PPP: "Té avec raccord barbelé",
        barb_coupling_PP: "Raccord avec raccord barbelé",
        barb_cross_PPPP: "Croix avec raccord barbelé",
        barb_cap_P: "Bouchon d'extrémité avec raccord barbelé",
        barb_coupling_PT: "Raccord avec raccord barbelé et fileté",
        barb_tee_PTP: "Té avec raccord barbelé et fileté",
        barb_valve_PT: "Vanne avec raccord barbelé et fileté",
        barb_valve_PP: "Vanne avec raccord barbelé",
        twlc_elbow_PP: "Coude avec raccord à verrouillage en torsion",
        twlc_tee_PPP: "Té avec raccord à verrouillage en torsion",
        twlc_coupling_PP: "Raccord avec raccord à verrouillage en torsion",
        twlc_cross_PPPP: "Croix avec raccord à verrouillage en torsion",
        twlc_cap_P: "Bouchon d'extrémité avec raccord à verrouillage en torsion",
        twlc_coupling_PT: "Raccord avec raccord à verrouillage en torsion et fileté",
        twlc_tee_PTP: "Té avec raccord à verrouillage en torsion et fileté",
        twlc_valve_PT: "Vanne avec raccord à verrouillage en torsion et fileté",
        twlc_valve_PP: "Vanne avec raccord à verrouillage en torsion",
        dl_valves: "Vannes spéciales",
        //pipe
        hdpeSDR9: "Tube HDPE SDR 9",
        hdpeSDR11: "Tube HDPE SDR 11",
        hdpeSDR136: "Tube HDPE SDR 13.6",
        hdpeSDR17: "Tube HDPE SDR 17",
        hdpeSDR176: "Tube HDPE SDR 17.6",
        ldpeSDR9: "Tube LDPE SDR 9",
        ldpeSDR11: "Tube LDPE SDR 11",
        ldpeSDR136: "Tube LDPE SDR 13.6",
        ldpeSDR17: "Tube LDPE SDR 17",
        pvcSCH40: "Tube PVC SCH40",
        pvcSCH80: "Tube PVC SCH80",
        pvcCL315: "Tube PVC CLASS 315",
        pvcCL200: "Tube PVC CLASS 200",
        pvcCL160: "Tube PVC CLASS 160",
        pvcCL125: "Tube PVC CLASS 125",
        pvcUSCJPN18: "Pipe PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Pipe PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Pipe PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Pipe PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Pipe PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "Tube LDPE CLASS 3",
        compress_elbow_PT: "Coude à compression/fileté",
        compress_coupling_PT: "Raccord à compression/fileté",
        compress_tee_PTP: "Té à compression/fileté",
        compress_cap_P: "Bouchon d'extrémité à compression",
        compress_elbow_PP: "Coude à compression",
        compress_coupling_PP: "Raccord à compression",
        compress_tee_PPP: "Té à compression",
        compress_cross_PPPP: "Croix à compression",
        compress_single_clamp_saddle: "Selle à serrage simple",
        compress_ballvalve_PP: "Vanntulette à compression",
        compress_ballvalve_PT: "Vanntulette à compression/fileté",
        customfit_elbow_PT: "Coude personnalisé/filetage",
        customfit_coupling_PT: "Raccord personnalisé/filetage",
        customfit_tee_PTP: "T personnalisé/filetage",
        customfit_cap_P: "Bouchon d'extrémité personnalisé",
        customfit_elbow_PP: "Coude personnalisé",
        customfit_coupling_PP: "Raccord personnalisé",
        customfit_tee_PPP: "T personnalisé",
        customfit_cross_PPPP: "Croix personnalisée",
        customfit_single_clamp_saddle: "Selle simple à bride",
        customfit_ballvalve_PP: "Vanne à boisseau sphérique personnalisée",
        customfit_ballvalve_PT: "Vanne à boisseau sphérique personnalisée/filetée",
        thread_nipple: "Téton fileté",
        thread_coupling: "Raccord fileté",
        thread_mf_reducer: "Réducteur mâle/femelle",
        thread_mf_adapter: "Adaptateur mâle/femelle",
        thread_mf_bush: "Réducteur femelle/mâle",
        thread_tee: "Té femelle",
        thread_elbow: "Coude femelle",
        thread_mf_elbow: "Coude mâle/femelle",
        thread_cap: "Capuchon femelle",
        thread_plug: "Bouchon mâle",
        thread_union_nut: "Écrou d'union",
        thread_cross: "Croix filetée",
        cable: "Câble",
        wire: "Fil",
        // slip
        slip_single_clamp_saddle: "Attache simple pour tuyau PVC",
        slip_elbow_PT: "Coude à joint/glissement",
        slip_coupling_PT: "Raccord à joint/glissement",
        slip_tee_PTP: "Té à joint/glissement",
        slip_cap_P: "Bouchon de fin",
        slip_elbow_PP: "Coude à glissement",
        slip_coupling_PP: "Raccord à glissement",
        slip_tee_PPP: "Té à glissement",
        slip_cross_PPPP: "Croix à glissement",
        slip_ballvalve_PP: "Vanne à glissement",
        slip_ballvalve_PT: "Vanne à joint/glissement",
//extendables
        arbitraryFittings: "Raccords arbitraires",
        dripStartAssembly: "Assemblage de départ pour goutte à goutte",
        intakeAssembly: "Assemblage d'admission",
        offtakeAssembly: "Raccords arbitraires pour dérivation",
        numofvalves: "Nombre de vannes :",
        numofvalvesshort: "Vannes :",
        numofmanifs: "Nombre de collecteurs :",
        intakePipeSize: "Taille du tuyau d'admission :",
        valveBoxes: "Boîtes de vannes",
        valveAccessories: "Accessoires de vannes",
        oneValveAccessories: "Accessoires de vanne",
        controllerAccessories: "Accessoires de contrôleur",
        sensorAccessories: "Accessoires de capteur",
        sprBodyAccessories: "Accessoires de corps de pulvérisation",
        rzwAccessories: "Accessoires d'arrosage en profondeur",
        pipeStartFittings: "Raccords arbitraires pour tuyau principal",
        qcAccessories: "Accessoires de vannes à déconnexion rapide",
        wiringAccessories: "Accessoires de câblage",
        pipeSize: "Taille du tuyau :",
        endOfPipe: "(Position finale)",
        midOfPipe: "(Découpage)",
        emptyRender: [
            "Désolé... aucun contenu n'a été analysé",
            "Vous n'avez pas terminé complètement l'un des nœuds d'irrigation à afficher"
        ],
        serviceFail: [
            "Désolé... le service de rendu de spécification est actuellement inaccessible",
            "Veuillez réessayer plus tard, lorsque la connexion sera établie",
            "Notez que la configuration que vous avez précédemment effectuée sera toutefois enregistrée"
        ],
        serviceTrialExpired: [
            "Désolé... le service de rendu de spécifications n'est pas disponible pour votre compte",
            "Cela signifie que votre période d'essai est terminée et si vous souhaitez utiliser ce service",
            "<a href='/account/subscription'>vous pouvez passer à un compte PRO</a>"
        ],
        serviceLimitReached: [
            "Vous avez atteint la limite quotidienne de rendus de fiches de spécifications",
            "Pour supprimer la limite sur le nombre de rendus de spécifications par jour",
            "<a href='/account/subscription'>vous pouvez passer à un compte PRO</a>"
        ],
        findInDrawing: "Afficher sur le canevas",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Tuyauterie",
        labours_group_fittings: "Raccords",
        labours_group_valveBoxes: "Boîtes de vannes",
        labours_group_wires: "Câblages",
        labours_group_sprinklers: "Arroseurs",
        labours_group_rws: "Arrosage en zone racinaire",
        labours_group_sprinklerConnections: "Connexions des arroseurs",
        labours_group_drip: "Tuyaux et raccords goutte à goutte",
        labours_group_manifolds: "Collecteurs",
        labours_group_quickCoupling: "Raccords rapides",
        labours_group_controllers: "Contrôleurs",
        labours_group_sensors: "Capteurs",
        labours_group_trenches: "Tranchées",
        labours_group_insets: "Manchons de tuyaux",
        labours_group_lawns: "Pelouse",
        labours_group_irrigatedArea: "Zone irriguée",
        labours_group_arbitrary_sp: "💦 Éléments d'irrigation personnalisés",
        labours_group_arbitrary_ld: "🌳 Éléments de paysage personnalisés",
        ldArbitrary_equip: "Équipement",
        ldArbitrary_labour: "Main-d'œuvre",
        spArbitrary_equip: "Équipement",
        spArbitrary_labour: "Main-d'œuvre",
        arbitrary_sp: '💦 Éléments d\'irrigation personnalisés',
        arbitrary_ld: '🌳 Custom Landscape elements',
        ldLine_labour: "Ligne",
        ldLine_equip: "Ligne",
        spLine_labour: "Ligne",
        spLine_equip: "Ligne",
        ldLineWithArea_labour: "Ligne (m2)",
        ldLineWithArea_equip: "Ligne (m2)",
        spLineWithArea_labour: "Ligne (m2)",
        spLineWithArea_equip: "Ligne (m2)",
        ldVolumetricLine_labour: "Ligne (m3)",
        ldVolumetricLine_equip: "Ligne (m3)",
        spVolumetricLine_labour: "Ligne (m3)",
        spVolumetricLine_equip: "Ligne (m3)",
        polyLdSurface_labour: "Surface",
        brushLdSurface_labour: "Surface",
        polyLdSurface_equip: "Surface",
        brushLdSurface_equip: "Surface",
        polySpSurface_labour: "Surface",
        brushSpSurface_labour: "Surface",
        polySpSurface_equip: "Surface",
        brushSpSurface_equip: "Surface",
        polyLdVolumetricSurface_labour: "Surface (m3)",
        brushLdVolumetricSurface_labour: "Surface (m3)",
        polyLdVolumetricSurface_equip: "Surface (m3)",
        brushLdVolumetricSurface_equip: "Surface (m3)",
        polySpVolumetricSurface_labour: "Surface (m3)",
        brushSpVolumetricSurface_labour: "Surface (m3)",
        polySpVolumetricSurface_equip: "Surface (m3)",
        brushSpVolumetricSurface_equip: "Surface (m3)",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
        MMM: ["\x01", "janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."],
        dddd: ["\x02", "dimanche", "lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
        ddd: ["\x03", "dim.", "lun.", "mar.", "mer.", "jeu.", "ven.", "sam."],
        //buttonsCaps
        ok: "OK",
        save: "Enregistrer",
        apply: "Appliquer",
        defaults: "Défauts",
        retry: "Réessayer",
        finish: "Terminer",
        safeRestart: "Redémarrage sécurisé",
        saveAndExit: "Enregistrer et quitter",
        exit: "Quitter",
        cancel: "Annuler",
        rename: "Renommer",
        idk: "Je ne sais pas",
        getFile: "Obtenir le fichier",
        reset: "Réinitialiser",
        random: "Aléatoire",
//misc
        zoneNum: "Zone #",
        valveNum: "Boîtier de vanne #",
        zonesColoring: "Représentation des zones",
        coversColoured: "Peindre les couvercles des arroseurs",
        dripsColoring: "Coloration des conduites d'égouttement",
        dripsSameAsZonesColored: "La conduite d'égouttement est colorée dans la couleur de sa zone",
        //saveOflline
        saveOffline: [
            "Désolé... la connexion est perdue",
            "Mais ne vous inquiétez pas, vous pouvez continuer votre projet en mode hors ligne.",
            "Tant que vous êtes hors ligne - toutes vos sauvegardes seront stockées sous forme de fichier texte dans le dossier de téléchargements de votre navigateur.",
            "Et plus tard, vous pouvez télécharger la dernière version de votre dessin sur le serveur."
        ],
        restartOffline: [
            "Désolé... la connexion est perdue",
            "Mais ne vous inquiétez pas, votre projet a été enregistré localement sur votre ordinateur.",
            "Vous pouvez le trouver dans le dossier de téléchargements de votre navigateur.",
            "Si vous voulez travailler hors ligne, vous pouvez télécharger une instance hors ligne de l'application depuis votre compte sur http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Désolé... quelque chose s'est mal passé lors du chargement de votre projet",
            "Il semble que votre sauvegarde précédente ait été corrompue d'une manière ou d'une autre.",
            "Mais ne vous inquiétez pas, nous pouvons la réparer.",
            "Votre projet sera marqué comme 'corrompu' dans votre atelier maintenant.",
            "Et notre personnel technique gérera cette situation dès que possible."
        ],
        corruptedSavingFile: [
            "Désolé... le fichier que vous essayez de charger n'est pas lisible",
            "Mais ne vous inquiétez pas, nous pouvons le réparer.",
            "Tout ce que vous avez besoin de faire est de soumettre ce fichier corrompu dans le formulaire de chargement de fichier de votre atelier.",
            "Et ensuite, nous essaierons de le remettre en marche."
        ],
        ajaxReqFail: [
            "Désolé... Nous avons perdu la connexion au serveur",
            "Il est impossible d'envoyer / recevoir des données pour le moment",
            "Veuillez réessayer plus tard"
        ],
        critical: [
            "Désolé... quelque chose s'est mal passé",
            "Mais ne vous inquiétez pas, votre dessin est en sécurité, il suffit de cliquer sur le bouton de redémarrage sécurisé pour continuer..."
        ],
        fatal: [
            "Désolé... quelque chose s'est mal passé",
            "Veuillez nous aider à améliorer notre service. Décrivez les actions de l'utilisateur après lesquelles cette erreur s'est produite",
            "Fournissez des informations ici"
        ],
        areYouSure: [
            "Vous êtes sur le point de fermer ce projet",
            "Notez que toutes les modifications non enregistrées seront perdues."
        ],
        pickAnotherCSVFile: "Choisissez un autre fichier",
        csvFileTooBig: [
            "Taille maximale du fichier CSV dépassée",
            "Pour des raisons d'optimisation, la taille maximale du fichier CSV géré est limitée à 4 Mo"
        ],
        notAnCSV: [
            "Désolé, ce type de fichier n'est pas pris en charge",
            "Formats de fichier pris en charge : .csv"
        ],
        invalidCSV: [
            "Contenu du fichier CSV invalide",
            "Erreur d'analyse du fichier d'exportation de l'application Moasure, veuillez vérifier si le fichier a été correctement exporté"
        ],
        pickAnotherImage: "Choisissez une autre image",
        imageTooBig: [
            "Taille maximale de l'image dépassée",
            "Pour des raisons d'optimisation, la taille maximale de l'image gérée est limitée à 10 Mo"
        ],
        notAnImage: [
            "Désolé, ce type de fichier n'est pas pris en charge",
            "Formats d'image pris en charge : .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "Action RESTREINTE",
            "Cette action n'est pas autorisée pour un abonnement GRATUIT"
        ],
        goPro: 'PASSER À LA VERSION PRO',
        renameLayout: "Entrez un nouveau nom",
        areYouSureDeleteLayout: [
            "Attention! Cette action ne peut pas être annulée",
            "Êtes-vous sûr de vouloir supprimer : ",
            "Supprimer"
        ],
        setUnderlaySize: [
            "Définir la longueur de la ligne que vous venez de dessiner",
            "Vous avez entré une valeur incorrecte. Veuillez réessayer"
        ],
        setMonitorDiagonal: [
            "Veuillez nous donner des informations sur la taille diagonale de votre écran",
            "Vous avez entré une valeur incorrecte. Veuillez réessayer"
        ],
        getSpecsTable: [
            "Définir les préférences de sortie des spécifications",
            "Regrouper l'équipement par ",
            "Noeud", "Marque",
            "Définir le type de fichier comme ",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Entrez un titre",
            "Agencement #",
            "Enregistrer",
            "Enregistrement des spécifications",
            "Terminé. Cliquez ici pour ouvrir",
            "Échec de l'enregistrement",
            "Mettre à jour les agencements existants",
            "Mettre à jour",
            "Mise à jour des agencements"
        ],
        exportLayoutsAsPdf: [
            "Choisissez les mises en page à exporter",
            "fichiers séparés (en développement)",
            "un album",
            "Exporter",
            "Exporter les mises en page en"
        ],
        differentSprGroups: [
            "Impossible d'attacher différents types de consommateurs d'eau à ce tuyau",
            "Selon les normes de conception d'irrigation, il est inacceptable de mélanger différents types de consommateurs d'eau ou de pulvérisateurs avec des taux de précipitation différents dans la même zone"
        ],
        tooFarAwaySpr: [
            "Impossible de connecter les consommateurs",
            "Certains des consommateurs sont trop éloignés du tuyau latéral pour être connectés. La distance maximale de connexion que vous pouvez configurer dans le menu des préférences"
        ],
        outlayerConfig: [
            "Configuration de la fiche de spécification"
        ],
        presetsMenu: {
            title: "Préréglages",
            titleTextboxLabel: "Titre du préréglage",
            descriptionTextboxLabel: "Description",
            applyButton: "<i class='far fa-check-circle'></i> Appliquer",
            defaultButton: "<i class='far fa-undo'></i> Défaut",
            removeButton: "<i class='far fa-trash'></i> Supprimer",
            updateButton: "<i class='far fa-sync'></i> Mettre à jour",
            createButton: "<i class='far fa-plus'></i> Créer un nouveau",
            closeButton: "<i class='far fa-times'></i> Fermer",
            favorites_drawing: "Outils favoris (Paysage)",
            favorites_sprinkling: "Outils favoris (Irrigation)",
            favorites_layouting: "Outils favoris (Plans)",
            configs_drawing: "Configuration du projet",
            configs_outlayer: "Configuration de la fiche technique",
        },
        newPresetItem: "Nouveau préréglage",
        cL_alreadyConnected: [
            "Échec de la concaténation des lignes",
            "Ces lignes sont toutes deux connectées à"
        ],
        cL_segOnElem: [
            "Échec de la concaténation des lignes",
            "Vous ne pouvez pas vous connecter à un segment qui est sur"
        ],
        cL_strangeError: [
            "Échec de la concaténation des lignes",
            "Désolé...la connexion a échoué"
        ],
        cL_misgrouping: [
            "Échec de la concaténation des lignes",
            "Ces lignes ont des consommateurs qui ne sont pas recommandés pour être placés sur la même zone. Si vous voulez les connecter quand même, activez le 'Mode non sécurisé' pour le groupement des arroseurs dans la configuration du projet."
        ],
        cL_valve: "Collecteur de vannes",
        cL_waterSource: "Source d'eau",
        cL_dripStart: "Début de la ligne goutte-à-goutte",
        cL_controller: "Programmateur",
        cL_sensors: "Capteurs",
        cL_valves: "Collecteur de vannes",
        cL_notSameVariant: [
            "Impossible de connecter les lignes",
            "Ces lignes sont de types différents",
            "Type de la ligne que vous dessinez actuellement",
            "Type de la ligne à laquelle vous voulez la connecter"
        ],
        hasRestorableProject: [
            "Vous avez des données non sauvegardées pour ce projet",
            "Vous pouvez restaurer l'état non sauvegardé à partir d'une sauvegarde effectuée à"
        ],
        restoreProject: "Restaurer",
        imageLost: [
            "Désolé, nous ne pouvons pas trouver certaines des images de fond sur le serveur",
            "Cette image n'a pas été trouvée:"
        ],
        precipCalcError_mixedError: [
            'Erreur des cartes de précipitation',
            'Échec de la création des cartes de précipitation pour la combinaison d’arroseurs :',
        ],
        precipCalcError_mprNonMprRot: 'Impossible de mélanger les rotors normaux et les rotors avec des buses MPR',
        precipCalcError_mprNozNonMprRot: 'Impossible de mélanger les buses MPR et les rotors normaux',
        precipCalcError_staticNozRot: 'Impossible de mélanger les buses statiques avec les rotors',
        precipCalcError_staticMprNoz: 'Impossible de mélanger les buses statiques avec les buses MPR',
        precipCalcError_missingError: [
            'Erreur des cartes de précipitation',
            'Profils de précipitation manquants pour les arroseurs :',
        ],
        precipCalcError_zoningError: [
            'Erreur de zonage des cartes de précipitation',
            'Échec de la création des cartes de précipitation pour la combinaison d’arroseurs :',
        ],
        precipCalcError_noZoneAndZone: 'Impossible de calculer les précipitations pour les rotors connectés et non connectés simultanément. Le temps d’exécution est inconnu, donc le nombre de révolutions des rotors est incertain',
        algoNozzler_noSolutions: [
            'Aucune solution possible de placement des arroseurs trouvée',
            'Essayez de faire ce qui suit :',
            '1. Modifiez les restrictions de chevauchement et d\'autres options dans le menu de configuration de l\'outil de placement automatique',
            '2. Sélectionnez un autre type d\'arroseurs, car ils peuvent offrir la flexibilité nécessaire pour le placement',
            '3. Utilisez le bouton ci-dessous pour relancer la résolution avec des restrictions plus "souples" pour le chevauchement et la couverture'
        ],
        retryWithLooseOptions: "Réessayer avec des options 'souples'",
        cannotSaveBecauseOffline: [
            "Impossible d'envoyer une demande au serveur",
            "Pas de connexion au serveur",
            "Vérifiez si vous avez une connexion Internet",
            "Pour ne pas perdre de données, ne fermez pas cette fenêtre et essayez de sauvegarder les données plus tard, lorsque la connexion au serveur sera établie",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Échec de la sauvegarde de la demande",
            "Trop de tentatives de code invalide",
            "Vérifiez si vous avez correctement saisi l'adresse e-mail et réessayez après 30 secondes.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Échec de la sauvegarde de la demande",
            "Adresse e-mail incorrectement saisie",
            "Vérifiez si vous avez correctement saisi l'adresse e-mail et réessayez",
            "",
            "",
        ],
        designRequestCompleted: [
            "Votre demande a été créée/mise à jour avec succès",
            "Lien d'édition", "Copier",
            "Lien de visualisation", "Copier",
        ],
        designRequestContacts: [
            "Contact information",
            "Organization",
            "Name",
            "Email",
            "Phone",
            "Address",
            "Website",
        ],
        "designRequestInfo": [
            "Bienvenue dans le Studio de Design !",
            "Ici, vous pouvez créer une demande pour planifier votre système d'irrigation facilement et rapidement.",
            "Vous pouvez trouver une <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>vidéo d'instruction ici</a>",
            "Pour plus d'informations ou si vous avez des questions, n'hésitez pas à nous contacter."
        ],
        approveActionByCode: [
            "Confirmer l'action",
            "Un e-mail avec un code de confirmation a été envoyé à l'adresse e-mail que vous avez fournie.",
            "Veuillez saisir ce code dans le champ ci-dessous",
            "Vous avez entré un numéro invalide, réessayez"
        ],
        "revisionCheckFailedSoft": [
            "Conflit de révision !",
            "Ce projet est actuellement ouvert dans un autre navigateur ou appareil.",
            "Vous pouvez écraser les données sur le serveur (car nous ne stockons qu'une seule version de votre projet) en cliquant sur `écraser`, mais soyez prudent - tous les progrès réalisés dans d'autres sessions seront perdus !",
            "Une meilleure stratégie est de comprendre où et qui a ouvert ce projet et de décider quelle version est à jour.",
            "Si vous voulez prendre le contrôle sur la dernière version de ce projet ouvert simultanément, vous pouvez ouvrir ce projet à nouveau en dupliquant cet onglet dans votre navigateur.",
        ],
        "revisionBlocked": [
            "L'enregistrement est bloqué par l'Admin !",
            "Actuellement, votre projet est en cours de révision par notre équipe technique en raison des erreurs qui s'y produisent.",
            "Veuillez attendre que la révision soit terminée, vous serez ensuite informé par e-mail des instructions à suivre.",
        ],
        missingVariants: [
            'Erreur d’éléments manquants',
            'Voici la liste des éléments personnalisés absents de votre bibliothèque de projet et donc impossibles à afficher :',
            'Veuillez activer les ensembles contenant ces éléments dans le menu de configuration du projet (dans Atelier)'
        ],
        "openInOtherTab": "Ouvrir le dernier",
        "overwrite": "Écraser",
        "saveToFile": "Enregistrer dans le fichier",
        filterSelection_exclude: "Exclure de la sélection",
        filterSelection_include: "Inclure dans la sélection",
        filterSelectionNames: {
            sprinklers: "Consommateurs",
            sprinklers_nozzle: "Consommateurs - Buses",
            sprinklers_rotaryNozzle: "Consommateurs - Buses rotatives",
            sprinklers_rotor: "Consommateurs - Rotors",
            sprinklers_bubbler: "Consommateurs - Bubblers",
            sprinklers_bubblerNozzle: "Consommateurs - Buses-bubblers",
            dripStarts: "Départs goutte à goutte",
            rzwLayer: "Arrosage racinaire",
            dripLines: "Tuyaux d'égouttement",
            valvesLayer: "Collecteurs de vannes",
            waterSources: "Sources d'eau",
            controllers: "Contrôleurs",
            sensorsLayer: "Capteurs",
            mainPipes: "Tuyaux principaux",
            lateralPipes: "Tuyaux latéraux",
            trenchesLayer: "Tranchées",
            insetsLayer: "Manches",
            wiresLayer: "Câblage",
            wirelessLayer: "Connexion sans fil",
            senswiresLayer: "Connexion sans fil des capteurs",
            senswiresLayer: "Câblage de capteurs",
            quickCoupLayer: "Raccords rapides",
            surfaces: "Polygones et lignes",
            ldItemsLayer: "Éléments paysagers"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Noeud de sprinkler",
        fcType: "Type de connexion",
        sj: "Joint à rotule",
        sprinklerStand: "Sprinkler stand (Riser)",
        flexPipeBarbs: "Tuyau flexible + barbes",
        minFlexPipeLength: "Longueur minimale de tuyau flexible par connexion",
        midSprinkPipeFitting: "Raccord pour tuyau central",
        endSprinkPipeFitting: "Raccord pour extrémité de tuyau",
        single_clamp_saddle: "Selle à collier simple",
        tee_PTP: "Té avec filetage femelle BSP",
        elbow_PT: "Coude avec filetage femelle BSP",
        coupling_PT: "Adaptateur avec filetage femelle BSP",
//MANIFOLD NODE CONFIGS
        manifoldNode: "Noeuds de collecteur",
        valvesOutlay: "Disposition des vannes",
        fold: "Replié",
        unfold: "Déplié",
        threadsNode: "Connexions filetées",
        threadTypes: "Types de filetage",
//AUTOMATION NODE CONFIGS
        automationNode: "Noeud d'automatisation",
        controllerModules: "Les modules d'extension de contrôleurs modulaires sont choisis :",
        controllerVoltage: "Tension d'entrée du contrôleur :",
        controllerVoltageV2: "Tension d'entrée du contrôleur :",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automatiquement (meilleur choix)",
        userModules: "Manuellement (comme accessoires)",
        //RZW NODE
        rzwNode: "Nœud d'arrosage de la zone racinaire",
        midRZWPipeFitting: "Raccord d'ajout en T",
        endRZWPipeFitting: "Raccord final",
// DRIP node
        dripNode: "Irrigation au goutte à goutte",
        dripConnectionType: "Type de raccord pour l'irrigation au goutte-à-goutte",
        dripLengthPrecision: "Chiffres après la virgule pour la longueur du tuyau",
        dripTubingAddon: "Additif pour tuyau d'irrigation au goutte-à-goutte",
        barb: "Raccords à barbes",
        twistLock: "Raccords twist-lock",
        dripSpikesStep: "Pas pour supports de ligne de goutteurs",
        dripCrossFittingAble: "Compatibilité avec raccord en croix",
        pipesNode: "Section de tuyauterie",
        hdpeConnectionType: "Type de raccord pour le PEHD",
        ldpeConnectionType: "Type de raccord pour le PELD",
        pvcConnectionType: "Type de raccord pour le PVC",
        pipeAddon: "Additif pour chaque diamètre de tuyau",
        pipeLengthPrecision: "Chiffres après la virgule pour la longueur de tuyau",
        crossFittingAble: "Compatibilité avec raccord en croix",
        compress: "Raccords de compression",
        customfit: "Raccords personnalisés",
        slip: "Slip fittings",
        wiringNode: "Section de câblage",
        exportNode: "Options d'exportation",
        exportNumbersPrecision: "Chiffres après la virgule pour les nombres",
        basicWiringMethod: "Méthode de câblage de contrôle",
        cableCoresArray: "Plage de nombre de fils pour le câble",
        noAutoWiring: "Ajouter le câblage manuellement",
        separateCableToManifold: "Séparer le câble multiconducteur en direction du collecteur",
        separateWireToValve: "Fil séparé pour la valve + fil commun pour le collecteur",
        maxCableCores: "Nombre maximal de fils pour le câble",
        verticalWiringAddon: "Additif vertical pour le fil de contrôle du programmateur",
        verticalSensWiringAddon: "Additif vertical pour le fil de capteur",
        wireAddon: "Additif pour chaque type de fil",
        wireLengthPrecision: "Chiffres après la virgule pour la longueur de fil",
        //DRAWER CONFIG
        drawerConfig: [
            "Configuration du projet"
        ],
        //SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Consommateurs",
        pressureDefinedBy: "Pression attendue aux consommateurs",
        allowReduceRotors: "Autoriser la réduction du rayon des rotors",
        autoconnector: "Connexion interactive des arroseurs au réseau de tuyauterie latérale",
        radio_option_yes: "Oui",
        radio_option_no: "Non",
        extreme_rotor_reduction: "Extrême (Jusqu'à 50%) (Peut causer une précipitation inégale)",
        radio_option_yes2: "Oui",
        takeReductionInAccountWhenAutoPlacing: "Proposer des distances de jet réduites lors du placement automatique des arroseurs",
        takeReductionInAccountWhenAutoPlacingForRotors: "Proposer des distances de jet réduites lors du placement automatique des arroseurs (Rotors)",
        recommendedPressure: "Recommandé par le fabricant",
        userPressure: "Réglée par l'utilisateur",
        expPressure: "Pression attendue au consommateur",
        sprinklerGroupMode: "Regroupement des consommateurs",
        safeSprGroupMode: "Mode strict (groupement uniquement compatible)",
        unsafeSprGroupMode: "Mode non sécurisé (ATTENTION! Aucune restriction de groupement)",
        "sprinklerAttachBulkMode": "Mode de Connexion en Masse des Consommateurs",
        "safeSprAttachMode": "Ne pas reconnecter les consommateurs déjà connectés",
        "unsafeSprAttachMode": "Mode dangereux (ATTENTION! Reconnexion possible des consommateurs déjà connectés. Utilisez à vos risques et périls)",
// CONFIGURATION DES UNITÉS DE MESURE
        unitsConfig: "Unités de mesure",
        precisionStd: "Chiffres après la virgule",
        unitsSystemGridAndRuler: "Système d'unités de mesure pour la grille et la règle",
        distanceUnits: "Distance",
        distancePrecision: "Chiffres après la virgule",
        trenchSizeUnits: "Unités de dimensions",
        trenchSizePrecision: "Chiffres après la virgule",
        sprinklerDistUnits: "Rayon de la buse",
        sprinklerDistPrecision: "Chiffres après la virgule",
        areaUnits: "Surface",
        areaPrecision: "Chiffres après la virgule",
        volumeUnits: "Volume",
        volumePrecision: "Chiffres après la virgule",
        waterFlowUnits: "Débit d'eau",
        waterFlowPrecision: "Chiffres après la virgule",
        pressureUnits: "Pression",
        pressurePrecision: "Chiffres après la virgule",
        velocityUnits: "Vitesse",
        velocityPrecision: "Chiffres après la virgule",
        precipRateUnits: "Taux de précipitation",
        precipRatePrecision: "Chiffres après la virgule",
// CONFIGURATION DES PROPRIÉTÉS DE ZONE
        climateConfig: "Calcul du temps d'arrosage",
        lawnCultureType: "Type de pelouse",
        coolLoving: "Aimant le froid",
        warmLoving: "Aimant le chaud",
        climateTemp: "Température moyenne de l'été",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Humidité moyenne de l'été",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Microclimat de la zone <i class='far fa-question-circle'></i>",
        microClimateTooltip: "Doux\n" +
            "Zones d'irrigation à l'ombre, abritées du vent et éloignées des objets secs et chauffés\n" +
            "\n" +
            "Normal\n" +
            "Lieux dans le paysage où les conditions de microclimat sont représentées: la présence de\n" +
            "bâtiments, de trottoirs et de chemins, d'ombrage, etc. n'affecte pas de manière significative les valeurs de\n" +
            "évapotranspiration\n" +
            "\n" +
            "Difficile\n" +
            "Reflet des conditions qui entravent la croissance des plantes et se traduisent facilement par un état de stress si la plante n'est pas correctement arrosée. Il peut s'agir d'un endroit ouvert, sous un soleil éclatant, à proximité de chemins, de bâtiments ou d'autres structures paysagères, reflétant la lumière du verre ou des éléments paysagers qui absorbent la chaleur, ou d'un endroit venteux.",
        gentleMicroClimate: "Doux",
        normalMicroClimate: "Normal",
        toughMicroClimate: "Difficile",
        soilType: "Composition du sol dans les zones",
        sand: "Sableux",
        sandyLoam: "Sabloneux",
        lightLoam: "Léger",
        mediumLoam: "Moyen",
        heavyLoam: "Lourd",
        clay: "Argileux",
        heavyClay: "Argileux lourd",
        zoneSlope: "Pente générale des zones",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Budget d'eau",
        lowWB: "Bas",
        normalWB: "Normal",
        highWB: "Haut",
        ft: "pieds",
        in: "pouce",
        ftin: "pieds/pouces",
        metric: "métrique",
        imperialUS: "impérial (US)",
//UNITS CONFIG
        hydraConfig: "Hydraulique",
        waterTemp: "Température de l'eau",
        maxFlowVelocity: "Vitesse d'écoulement maximale dans la conduite",
        "commonConfig": "Paramètres communs",
        "lateralNozzlerSwitch": "Comment passer en mode de fixation de buses",
        "NStabonly": "Tab",
        "NStabshift": "Tab+Maj",
        "showActionSubtitles": "Afficher les sous-titres d'action",
        "Yeah": "Oui",
        "Nope": "Non",
        start: "Démarrer",
        recalibrate: "Recalibrer",
        calibrationSuccess: [
            "Calibré avec succès",
            "Vous pouvez maintenant utiliser l'écran tactile en deux modes - 'déplacer le curseur' (mouvement léger au toucher) et 'mode glisser' (mouvement appuyé au toucher)"
        ],
        calibrationFailEqual: [
            "Échec de la calibration",
            "Nous n'avons détecté aucune grande différence dans la manière dont vous touchez l'écran dans les deux modes",
            "Vous pouvez réessayer. Et assurez-vous d'utiliser votre doigt, pas un stylet"
        ],
        calibrationFailImproper: [
            "Échec de la calibration",
            "Nous avons détecté une plus grande pression sur la plume que sur l'enclume",
            "Vous pouvez réessayer. Et assurez-vous de déplacer la plume avec moins de pression que l'enclume"
        ],
        calibrationImpossible: [
            "Calibration impossible",
            "Il semble que votre appareil ne prend pas en charge la mesure de la zone tactile. Nous ne pouvons donc pas définir deux modes d'interaction tactile",
            "Dans ce cas, vous pouvez utiliser une souris virtuelle pour pouvoir faire glisser n'importe quoi. Elle apparaîtra sur le côté gauche de l'écran."
        ],
        calibrationNeeded: [
            "Calibration nécessaire !",
            "Nous devons calibrer votre écran tactile pour pouvoir définir deux modes d'interaction tactile :",
            "Mode déplacement du curseur - lorsque vous souhaitez simplement déplacer le curseur ou déplacer le segment de polygone en dessinant",
            "Et mode glisser - lorsque vous souhaitez déplacer des éléments ou en modifier la taille. Vous devriez également glisser-déplacer lorsque vous souhaitez sélectionner plusieurs éléments",
            "Veuillez cliquer sur le bouton Démarrer et suivre les instructions à l'écran"
        ],
        insertImage: 'Insérer',
        mapImagePicker: [
            "Chargeur d'images satellite",
            "Latitude/Longitude",
            "Entrer la latitude",
            "Entrer la longitude",
            "Localisation actuelle",
            "Aller",
            "Adresse",
            "Tapez une partie de l'adresse et cliquez sur 'Rechercher'",
            "Rechercher",
            "Zoom",
            "Déplacement"
        ],
        "imageCrop": [
            "Crop tool"
        ],
        cropImage: "Crop",
        invalid_dataset_1: 'Invalid dataset. Project contains prohibited types of surfaces. Only irrigated (LAWN), non-irrigated and obstacles are allowed.',
        invalid_dataset_2: 'Invalid dataset. Not more or less than ONE irrigated surface is allowed.',
        invalid_dataset_3: 'Invalid dataset. Irrigated surface is self-intersected.',
        invalid_dataset_4: 'Invalid dataset. Obstacle marker should not be compound (Made of more than one polygon)',
        invalid_dataset_5: 'Invalid dataset. Obstacle surface should be fully contained within irrigated surface.',
        invalid_dataset_6: 'Invalid dataset. Project contains prohibited types of sprinklers. Allowed:',
        invalid_dataset_7: 'Invalid dataset. Precipitation rate of sprinklers is out of range',
        invalid_dataset_8: 'Invalid dataset. Sprinklers must not have individual pressure settings',
        invalid_dataset_9: 'Invalid dataset. The project should not set a custom expected pressure at the sprinklers',
        invalid_dataset_10: 'Invalid dataset. Uniformity is too low.',
        invalid_dataset_11: 'Invalid dataset. Overwatered area is too big.',
        layoutPresetsMenu: [
            "Préréglages de mise en page",
            "Préréglage de mise en page actuel",
            "Préréglage d'ensemble de mises en page",
            "Préréglage par défaut pour nouvelle mise en page:",
            "- Choisir un préréglage -",
            "- Aucun préréglage disponible -"
        ]
    }
};
