this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: "\"",
        ftin: "ft/in",
        sqm: "m²",
        acre: "ac",
        hectare: "ha",
        sqft: "sqr.ft",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gal",
        cubft: "ft³",
        lpm: "l/m",
        lph: "l/h",
        m3h: "m³/h",
        USgpm: "gpm",
        USgph: "gph",
        deg: "°",
        pcs: "komada",
        pcsDot: "kom.",
        pcsShort: "kom.",
        percent: "%",
        in_Alt: "in.",
        mps: "m/s",
        kph: "km/h",
        ftps: "ft/s",
        degreesCentigrade: "°C",
        mmph: "mm/h",
        mmp24h: "mm/dan",
        inph: "in/h",
        // unconvertable
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Automatski odabir",
        chooseSprinkler: "Odaberi diznu:",
        auto: "Auto-set",
        waterSource2row: ["Water", "Intake"],
        setLineLength: "Podesi veličinu linije (mm):",
        setPressure: "Podesite očekivani dinamički tlak na diznama (bar):",
        setMaxFlow: "Odredite maksimalni protok vode (l/min):",
        controllerShort: "P",
        sensorShort: "S",
        action_activateEraser: "Aktiviraj gumicu",
        action_deactivateEraser: "Deaktiviraj gumicu",
        action_boolUnite: "Ujedini",
        action_boolIntersect: "Presijeci",
        action_boolSubtract: "Oduzmi",
        action_boolExclude: "Izuzmi",
        action_changeSprayBody: "Odaberi prskalice",
        action_changeVariant: "Odaberi varijantu",
        action_changeImgVariant: "Odaberi varijantu",
        action_changeType: "Odaberi tip",
        action_addConsumers: "Dodaj potrošače",
        action_drawBranches: "Dodaj grane",
        action_editLine: "Uredi segmente",
        action_drawCircles: "Nacrtaj krugove",
        action_detachAll: "Odvoji sve",
        action_drawBrush: "Crtaći kist",
        action_editBrush: "Uredi kist",
        action_changeBrushSize: "Veličina kista",
        action_booleans: "Boolean ops.",
        action_intoPoly: "Pretvori u poligon",
        action_intoBrush: "Pretvori u kist",
        action_activateRotation: "Rotiraj",
        action_deactivateRotation: "Mirno",
        action_markZones: "Označavanje zona",
        action_unmarkZones: "Ukloni oznake",
        action_sprNames: "Nazivi rasprskivača",
        action_noSprNames: "Ukloni nazive",
        action_lockItem: "Zaključaj",
        action_unlockItem: "Otključaj",
        Circle: "Krug",
        Triangle: "Trokut",
        BushForm: "Grmlje",
        BushForm1: "Grm 1",
        BushForm2: "Grm 2",
        BushForm3: "Grm 3",
        Square: "Kvadrat",
        noShadow: "Nema",
        standardShadow: "Standard",
        noArrows: "Nema",
        startArrow: "Na početku",
        endArrow: "Na kraju",
        bothArrows: "Obje strane",
        normalSizeSide: "Normalno",
        invertedSizeSide: "Obrnuto",
        strMiter: "Oštro",
        strRound: "Zaobljeno",
        strBevel: "Zakošeno",
        strSquare: "Kvadrat",
        strButt: "Bez",
        FWnormal: "Normalno",
        FWbold: "Podebljano",
        FWitalic: "Kurziv",
        FWbolditalic: "Podebljani kurziv",
        FJleft: "Lijevo",
        FJright: "Desno",
        FJcenter: "Centar",
        rzwHeight: "Visina"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Odabirač",
        //----Drawing
        selectPoly: "Nema odabranih stavki",
        //----Sprinkling
        selectSprink: "Nema odabranih stavki",
        lpNozzler: "Priključivanje potrošača vode",
        dl16CircDrawer: "Polaganje kap po kap krugova 16/13mm",
        dl16sDrawer: "Crtanje rastera kap po kap 16/13mm",
        dl17CircDrawer: "Polaganje kap po kap krugova 17mm",
        dl17sDrawer: "Crtanje rastera kap po kap 16/13mm",
        "ldTextDrawer": "Postavljanje Teksta",
        "staticTextDrawer": "Postavljanje Teksta",
        "dynamicTextDrawer": "Postavljanje Teksta",
        "ldStaticTextDrawer": "Postavljanje Teksta",
        "ldtextEditor": "Uređivanje Teksta",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Ukupna udaljenost",
        type: "Vrsta",
        variant: "Varijanta",
        area: "Površina",
        perimeter: "Opseg",
        curveLength: "Dužina",
        treeDiameter: "Promjer",
        bushDiameter: "Promjer",
        nozTypes: "Dostupne vrste",
        nozType: "Vrsta",
        sprBod: "Tijelo rasprskivača",
        rad: 'Radijus',
        angle: 'Kut',
        reducedBy: 'Smanjeno za',
        consump: 'Potrošnja',
        pressure: 'Tlak',
        coverSize: 'Pokrivenost',
        maxFlow: 'Maksimalni protok vode',
        pipesNum: "Spojene cijevi",
        pipeType: "Vrsta",
        pipeLength: "Dužina",
        wireLength: "Dužina",
        valvesManifNum: "Razvodi ventila",
        valvesNum: "Ventili",
        propDiam: "Ispravni promjer",
        curDiam: "Nacrtani promjer",
        outsNum: "Potrošači vode",
        flow: "Protok vode",
        precipRate: "Intenzitet kišenja",
        totalPrecipArea: "Ukupna pokrivena površina",
        uniformity: "CU",
        uniformity2: "DU",
        overwatered: "Overwatered",
        precipRateShort: "Int.Kiš.",
        runtimeInd: "Vrijeme rada",
        coveredArea: "Površina",
        microClimateInd: "M/Klima",
        soilTypeInd: "Tlo",
        zoneSlopeInd: "Kosina",
        maxInfiltrationRate: "Stopa infiltracije",
        waterDemand: "Zahtjev za vodom",
        numOfRuns: "Ciklusa na dan",
        timePerRun: "Vrijeme rada po ciklusu",
        dailyConsumption: "Dnevna potrošnja",
        dripsNum: "Spojenih cijevi kap po kap",
        dripType: "Vrsta cijevi kap po kap",
        dripRowsStep: "Razmak redova u rasteru",
        dripRowsAngle: "Kut polaganja redova u rasteru",
        cntrType: "Vrsta programatora",
        sensType: "Vrsta senzora",
        zonesNum: "Kontroliranih zona",
        trenchWidth: "Širina",
        trenchDepth: "Dubina",
        trenchVolume: "Volumen",
        insetDiam: "Promjer",
        insetLength: "Duljina",
        insetVar: "Materijal",
        itemsCount: "Broj",
        insetDepth: "Dubina",
        zoneName: "Naziv zone",
        valveName: "Ventilska kutija",
        itemAlias: "Naziv",
        lineWidth: "Širina",
        lineDepth: "Dubina",
        lineArea: "Površina",
        lineVolume: "Volumen",
        surfaceDepth: "Dubina/Visina",
        surfaceVolume: "Volumen",
        //MULTISELECTOR
        itemsSelected: "Odabrano",
        totalArea: "Ukupna površina",
        totalPerimeter: "Ukupni opseg",
        totalLength: "Ukupna duljina",
        totalVolume: "Ukupni volumen",
        totalConsumption: "Ukupna potrošnja",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Neispravni poligon",
        isSelfCrossing_false: "Ispravan poligon",
        isConnected_true: "Povezano",
        isConnected_false: "Nije povezano",
        isWired_true: "Ožičeno",
        isWired_false: "Nije ožičeno",
        isDripZone_true: "Zona kapanja",
        isDripZone_false: "",
        isSprinklerZone_true: "Zona prskanja",
        isSprinklerZone_false: "",
        isOverloaded_true: "PREOPTEREĆENJE!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Niski tlak",
        isUnderpressured_false: "",
        isOverpressured_true: "Visok tlak",
        isOverpressured_false: "",
        isLocked_true: "Zaključano",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Nehrđajući čelik",
        "High speed": "Visoka brzina",
        "Opposing nozzle": "Opposing nozzle",
        "Plastic": "Plastika",
        "MPR Nozzles": "MPR Dizne",
        "Rotary Nozzles": "Rotacijske dizne",
        Nozzles: "Dizne",
        "Bubbler nozzles": "Bubbler dizne",
        "Multi-stream": "Više mlazni",
        "Dual-stream": "Dvostruki mlaz",
        "Stream Nozzles": "Stream Nozzles",
        "Short Radius Nozzles": "Dizne kratkog dometa",
        "Pressure compensating": "S kompenzacijom tlaka",
        "Adjustable flood": "Podesiv poplavni",
        Adjustable: "Podesive",
        Fixed: "Fiksne",
        "Fixed Arc": "Fiksni kut",
        "Strip Pattern": "Trakasti uzorak",
        "Drip line": "Kap po kap linijski",
        "Drip cover": "Kap po kap raster",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "S kapaljkama",
        "noemitter": "Bez kapaljki",
        "Root zone watering": "Navodnjavanje zone korijena",
        Lateral: "Lateralna",
        Main: "Opskrbna",
        Trench: "Rov",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC(Metric)",
        ldpe: "LDPE",
        Controller: "Programator",
        Sensor: "Senzor",
        Wiring: "Povezivanje",
        IrrigateMarks: "Zones",
        Surface: "Površina",
        Lawn: "Travnjak",
        Bed: "Gredica",
        Shrubs: "Grmlje",
        Path: "Staza",
        Concrete: "Beton",
        Sand: "Pijesak",
        Water: "Voda",
        Bedding: "Pokrov",
        Flower: "Cvijeće",
        Herbal: "Začini",
        geographic: "Geografski",
        loSurface: "Površina",
        loStdSurf: "Standardno (Poligon)",
        loStdSurf_BRUSH: "Standardno (Kist)",
        sizeMark: "Kote",
        scalingBar: "Mjerna traka",
        loCurves: "Linije",
        texts: "Tekstovi",
        staticText: "Statični tekst",
        dynamicText: "Dinamički tekst",
        stampText: "Tekst sastavnice",
        stampTextDefault: "Tekst",
        stampTextgr1: "Definicija dokumenta",
        stampTextgr2: "Adresa",
        stampTextgr3: "Naziv objekta",
        stampTextgr4: "Naziv nacrta",
        stampTextgr9: "Organization info",
        stampTextgr6t: "Faza",
        stampTextgr7t: "Strana",
        stampTextgr8t: "Strane",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Ch.",
        stampTextgr15t: "Prtcp.",
        stampTextgr16t: "Strana",
        stampTextgr17t: "# Dok.",
        stampTextgr18t: "Potpis",
        stampTextgr19t: "Datum",
        stampTextgr20t: "Orig. Inv.#",
        stampTextgr21t: "Sign'n'Date",
        stampTextgr22t: "Repl. Inv.#",
        inserts: "Proturne cijevi",
        poly: "Poligon",
        brush: "Kist",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Prikaži upravljanje slojevima",
        hideLM: "Sakrij upravljanje slojevima",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Neimenovano",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Izvoz Nacrta u tijeku",
        successExporting: "Uspješno izvezeno",
        failExporting: "Neuspješno izvezeno",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Dosegnut dnevni limit</a>",
        exportingLimit: "Limit: ",
        exportingLeft: "Preostalo danas: ",
        pdfExportingPopUpBlocked: "Vaš preglednik je blokirao iskočni prozor. Molimo dozvolite iskočne prozore za ovu stranicu kako biste dobili .PDF datoteku.",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Navoj za diznu",
        tt_group_MT: "Muški",
        tt_group_FT: "Ženski",
        tt_riserHeight: "Visina dizanja",
        tt_pressureReg: "Regulator tlaka",
        tt_checkValve: "(S bespovratnim ventilom)",
        tt_home: "Početna",
        tt_prev: "Prethodna",
        tt_next: "Slijedeća",
        tt_end: "Kraj",
        tt_add: "Dodaj",
        tt_clone: "Kloniraj",
        tt_remove: "Ukloni",
        tt_rename: "Preimenuj",
        tt_addToFav: "Dodaj u Favorite",
        tt_remFromFav: "Ukloni iz Favorita",
        tt_presets: "Predlošci",
        tt_MagicAutoPlacer: "`Automatsko postavljanje uzduž linije`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "S",
        S: "J",
        E: "I",
        W: "Z",
        //conventions
        sprinklers: "Rasprskivači",
        dripStarts: "Kap po kap priključci",
        rzwLayer: "Navodnjavanje zone korijena",
        dripLines: "Kap po kap",
        valvesLayer: "Razvod ventila",
        waterSources: "Priključak na vodu",
        quickCoupLayer: "Q/C priključci",
        controllers: "Programator",
        sensorsLayer: "Senzor",
        mainPipes: "Opskrbna cijev",
        lateralPipes: "Lateralne cijevi",
        lateralPipes_sprinklerZone: "Lateralna cijev (Rasprskivači)",
        lateralPipes_dripZone: "Lateralna cijev (Kap po kap)",
        lateralPipes_rzwZone: "Lateralna cijev (RWS)",
        lateralPipes_emptyZone: "Lateralna cijev (bez potrošača)",
        trenchesLayer: "Rovovi",
        insetsLayer: "Proturi",
        wiresLayer: "Ožičenje",
        wirelessLayer: "Bežična veza",
        senswiresLayer: "Bežična veza senzora",
        senswiresLayer: "Ožičenje senzora",
        surfaces: "Površine",
        ldItemsLayer: "Biljke",
        covers: "Dometi",
        nameplates: "Opis potrošača",
        oreolas: "Oznake potrošača",
        pipeInfo: "Opis cijevi",
        lines: "linije",
        overlays: "Preklapanja",
        stampLayer: "Okvir",
        stampTexts: "Tekstovi sastavnice",
        //zonesTable
        zoneType: "Tip Zone",
        color: "Boja",
        consumers: "Potrošači",
        waterFlow: "Protok",
        sprinklerZone: "Rasprskivači",
        dripZone: "Kap po kap",
        rzwZone: "RWS",
        emptyZone: "Bez potrošača",
        specifyDiagonal: "Molimo, unesite veličinu dijagonale vašeg monitora u inčima",
        //sprinklersTable
        consType: "Tip",
        consName: "Naziv",
        zoneNum: "Zona",
        sector: "Sektor",
        radius: "Radijus",
        reducedBy: "Reducirano",
        nozzle: "Dizna",
        rotor: "Rotor",
        bubbler: "Bubbler",
        bubblerNozzle: "Bubbler-Dizna",
        //dripsTable
        catId: "Kat. Br.",
        brand: "Proizvođač",
        emitterStep: "Razmak",
        emitterFlow: "Protok",
        //layersManangerSpecific
        consumersGrp: "Potrošači",
        nodesGrp: "Elementi sustava",
        wiresGrp: "Ožičenje",
        pipesGrp: "Cijevi",
        landscapeGrp: "Krajobraz",
        allTogether: "Sve"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Tip",
        brand: "Proizvođač",
        catid: "Kat. Br.",
        title: "Naslov",
        units: "Jedinice",
        amount: "Količina",
        //predetermined
        dripLine: "Kap po kap",
        dl16: "Kap po kap 16/13mm",
        dl17: "Kap po kap 17mm",
        dripStart: "Kap po kap priključak",
        ds16: "Kap po kap priključak 16/13mm",
        ds17: "Kap po kap priključak 17mm",
        manifold_no_lps_issue: "Nema spojenih zona",
        manifold_no_mp_issue: "Nije spojeno na opskrbnu cijev",
        manifold_no_wr_issue: "Nema spojenog ožičenja",
        //nodes-----------------------------------
        sprinkler_unattached: "UPOZORENJE!!! Imate nespojene rasprskivače (neće biti prikazani u konačnom listu specifikacija)",
        drip_unattached: "UPOZORENJE!!! Imate nespojene elemente kap po kap navodnjavanja (neće biti prikazani u konačnom listu specifikacija)",
        mains_unattached: "UPOZORENJE!!! Imate nespojene OPSKRBNE CIJEVI (neće biti prikazane u konačnom listu specifikacija)",
        mains_empty: "UPOZORENJE!!! Imate OPSKRBNE CIJEVI bez potrošača (neće biti prikazane u konačnom listu specifikacija)",
        laterals_unattached: "UPOZORENJE!!! Imate nespojene LATERALNE CIJEVI (neće biti prikazane u konačnom listu specifikacija)",
        laterals_empty: "UPOZORENJE!!! Imate LATERALNE CIJEVI bez potrošača (neće biti prikazane u konačnom listu specifikacija)",
        rzw_unattached: "UPOZORENJE!!! Imate nespojene elemente navodnjavanja zone korijena (neće biti prikazani u konačnom listu specifikacija)",
        sensors_unattached: "UPOZORENJE!!! Imate nespojene SENZORE (neće biti prikazani u konačnom listu specifikacija)",
        manifolds_unfinished: "UPOZORENJE!!! Imate nezavršene razvode ventila (Ne možete dovršiti konfiguraciju ventila)",
        control_wires_unattached: "UPOZORENJE!!! Imate nespojeno ožičenje",
        control_wires_empty: "UPOZORENJE!!! Imate ožičenje bez spojenih ventila",
        cntr_wr_unattached: "Kontrolna žica",
        youCanSeeThemInTheDrawing: "Možete pogledati svaki element na crtežu, klikom na ikonu oka, lijevo od retka tog elementa",
        sprinkler_nozzleMT: "Priključak rasprskivača (Dizna sa Ženskim navojem)",
        sprinkler_nozzleFT: "Priključak rasprskivača (Dizna sa Muškim navojem)",
        "sprinkler_rotor1/2F": "Priključak rasprskivača (Rotor) 1/2\" ženski",
        "sprinkler_rotor3/4F": "Priključak rasprskivača (Rotor) 3/4\" ženski",
        "sprinkler_rotor1F": "Priključak rasprskivača (Rotor) 1\" ženski",
        "sprinkler_rotor11/4F": "Čvor prskalice (Rotor) 1 1/4\"",
        "sprinkler_rotor11/2F": "Čvor prskalice (Rotor) 1 1/2\"",
        "sprinkler_rotor2F": "Čvor prskalice (Rotor) 2\"",
        "sprinkler_rotor1/2M": "Priključak rasprskivača (Rotor) 1/2\" muški",
        "sprinkler_rotor3/4M": "Sprinkler node (Rotor) 3/4\" male",
        "sprinkler_bubbler1/2F": "Priključak rasprskivača (Bubbler) 1/2\" ženski",
        sprinkler_bubblerNozzleMT: "Priključak rasprskivača (Bubbler Dizna sa Ženskim navojem)",
        sprinkler_bubblerNozzleFT: "Priključak rasprskivača (Bubbler Dizna sa Muškim navojem)",
        dripIrrigation16: "Navodnjavanje kap po kap (16/13mm)",
        dripIrrigation17: "Navodnjavanje kap po kap (17mm)",
        rootZoneWatering: "Sustav navodnjavanja zone korijena",
        manifold: "Priključak razvoda ventila",
        automation: "Priključak automatike",
        mainPipes_hdpePE80SDR11: "Opskrbne cijevi HDPE PE80 SDR 11",
        mainPipes_hdpePE80SDR136: "Opskrbne cijevi HDPE PE80 SDR 13.6",
        mainPipes_hdpePE80SDR176: "Opskrbne cijevi HDPE PE80 SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Lateralne cijevi HDPE PE80 SDR 11",
        lateralPipes_hdpePE80SDR136: "Lateralne cijevi HDPE PE80 SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Lateralne cijevi HDPE PE80 SDR 17.6",
        mainPipes_hdpeSDR9: "Opskrbne cijevi HDPE SDR 9",
        mainPipes_hdpeSDR11: "Opskrbne cijevi HDPE SDR 11",
        mainPipes_hdpeSDR136: "Opskrbne cijevi HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Opskrbne cijevi HDPE SDR 17",
        mainPipes_hdpeSDR176: "Opskrbne cijevi HDPE SDR 17.6",
        lateralPipes_hdpeSDR9: "Lateralne cijevi HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Lateralne cijevi HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Lateralne cijevi HDPE SDR 13.6",
        lateralPipes_hdpeSDR17: "Lateralne cijevi HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Lateralne cijevi HDPE SDR 17.6",
        mainPipes_pvcSCH40: "Opskrbne cijevi PVC SCH40",
        mainPipes_pvcSCH80: "Opskrbne cijevi PVC SCH80",
        mainPipes_pvcCL315: "Opskrbne cijevi PVC CLASS 315",
        mainPipes_pvcCL200: "Opskrbne cijevi PVC CLASS 200",
        mainPipes_pvcCL160: "Opskrbne cijevi PVC CLASS 160",
        mainPipes_pvcCL125: "Opskrbne cijevi PVC CLASS 125",
        mainPipes_pvcUSCJPN18: "Main pipes PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Main pipes PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Main pipes PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Main pipes PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Main pipes PVC-U SCJ (PN4.5)",
        mainPipes_ldpeCLASS3: "Opskrbne cijevi LDPE CLASS 3",
        lateralPipes_pvcSCH40: "Lateralne cijevi PVC SCH40",
        lateralPipes_pvcSCH80: "Lateralne cijevi PVC SCH80",
        lateralPipes_pvcCL315: "Lateralne cijevi PVC CLASS 315",
        lateralPipes_pvcCL200: "Lateralne cijevi PVC CLASS 200",
        lateralPipes_pvcCL160: "Lateralne cijevi PVC CLASS 160",
        lateralPipes_pvcCL125: "Lateralne cijevi PVC CLASS 125",
        lateralPipes_pvcUSCJPN18: "Lateral pipes PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Lateral pipes PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Lateral pipes PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Lateral pipes PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Lateral pipes PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Lateralne cijevi LDPE CLASS 3",
        wiring: "Ožičenje",
        qcv: "Q/C Ventili",
        fixedCntr: "s fiksnim brojem zona",
        stand_aloneCntr: "baterijski",
        modularCntr: "modularni",
        decoderCntr: "dekoderski",
        inset: "Proturna cijev",
        insets: "Proturi",
        //-----------------------------------------
        novar: "nema varijanti",
        choosevar: "odaberi varijantu",
        //element.types----------------------------
        nozzle: "Dizna",
        rotor: "Rotor",
        rotorNozzle: "Rotor dizna",
        bubbler: "Bubbler",
        bubblerNozzle: "Bubbler-dizna",
        rzw: "Sustav navodnjavanja korijena",
        sprayBody: "Tijelo rasprskivača",
        sprinklerStandAssembly: "Sprinkler stand (Riser)",
        outBarb: "Ubodna spojnica prema rasprskivaču",
        flexPipe: "Fleksibilna cijev",
        sj: "Zglobni priključak",
        inBarb: "Ubodna spojnica prema cijevi",
        midSprinkPipeFitting: "Priključak rasprskivača na cijev",
        endSprinkPipeFitting: "Priključak rasprskivača na kraj cijevi",
        midRZWPipeFitting: "Priključak RWS-a na cijev",
        endRZWPipeFitting: "Priključak RWS-a na kraj cijevi",
        dripPipe: "Kap po kap cijev",
        blindPipe: "Cijev bez kapaljki",
        dripTeeFitting: "Kap po kap T-komad",
        dripCapFitting: "Kap po kap završni komad",
        dripCouplingFitting: "Kap po kap spojnica",
        dripElbowFitting: "Kap po kap koljeno",
        dripSpike: "Kap po kap kolčić",
        sprinklerZoneValve: "Ventil zone s rasprskivačima",
        emptyZoneValve: "Ventil bez potrošača",
        valveOutFitting: "Izlazni adapter ventila",
        dripZoneValve: "Ventil zone s kap po kap",
        rzwZoneValve: "Ventil zone navodnjavanja korijena",
        pressureReg: "Regulator tlaka",
        filter_pressureReg: "Filter s regulacijum tlaka",
        controller: "Programator",
        flowMeter: "Mjerač protoka",
        rainSensor: "Kišni senzor",
        soilSensor: "Senzor tla",
        freezeSensor: "Senzor mraza",
        wrFreezeSensor: "Wireless Rain/Freeze sensor",
        windSensor: "Senzor vjetra",
        solarSensor: "Senor solarni",
        flowSensor: "Senzor protoka",
        weatherStation: "Vremenska stanica",
        solarPanel: "Solarni panel",
        mainPipe: "Opskrbna cijev",
        teeFitting: "T-komad",
        elbowFitting: "Koljeno",
        reducerFitting: "Redukcija",
        lateralPipe: "Lateralna cijev",
        capFitting: "Završni komad",
        basicCable: "Osnovni kabel",
        basicWire: "Osnovna žica",
        sensorCable: "Žica vremenskog senzora",
        qcPlastic: "Q/C ventil plastični",
        qcMetal: "Q/C ventil metalni",
        gateway: "Gateway",
        antExt: "Antenna extension",
        loramod: "LoRa modules",
        //typesOfAcessories
        hdpeCOR: "Korugirana cijev",
        expModule: "Modul za proširenje",
        rzwSleeve: "Zaštitni omot",
        rwCap: "Kapa za recikliranu vodu",
        gutterMount: "Montaža na oluk",
        delayRelay: "Relej za odgodu",
        fctFlow: "FCT Prihvatni T-komad",
        fctBspAdap: "BSP Adapter za FCT spojeve",
        drainCheckValve: "Ispusni nepovratni ventil",
        rwId: "Oznaka reciklirane vode",
        vpc: "Kapa sa zaključavanjem",
        inletFilter: "Ulazni filter",
        wifiModule: "Wi-Fi modul",
        wallMount: "Zidna montaža",
        rwsSock: "Zaštitni omot za RWS",
        rwsGrate: "Rešetka za RWS",
        npCover: "Poklopac za recikliranu vodu",
        sprExt: "Produžetak za rasprskivač",
        popUpToThread: "Adapter za rasprskivač",
        valveBox: "Ventilska kutija",
        valveBoxExt: "Ekstenzija ventilske kutije",
        qcPlasticKey: "Plastični Ključ za Q/C ventil",
        qcPlasticElbFit: "Plastično okretno koljeno",
        qcMetalKey: "Metalni Ključ za Q/C ventil",
        qcMetalElbFit: "Metalno okretno koljeno",
        qcMetalCapKey: "Ključ za Q/C poklopac",
        insTape: "Izolir traka",
        wrConn: "Vodotijesna spojnica",
        shrinkTube: "Termoskupljajuća cijev",
        hcFrontPanel: "Prednja ploča",
        ball_valve: "Kuglasti ventil",
        check_valve: "Nepovratni ventil",
        thread_manifold: "Navojni razvod",
        plastic_filter: "Filter (plastični)",
        waterMeter: "Vodomjer",
        rfModule: "Radio modul",
        largeAntenna: "Antena",
        wifiHub: "WiFi Hub",
        handRemoteKit: "Kit za ručni daljinski",
        handRemote: "Ručni daljinski",
        wifiBundleKit: "WiFi Komplet",
        //typesOfFittings
        //drip
        barb_cap_8: "Dvostruki prsten za kraj kap po kap cijevi",
        barb_elbow_PP: "Ubodno koljeno",
        barb_elbow_PT: "Ubodno navojno koljeno",
        barb_tee_PPP: "Ubodni T-komad",
        barb_coupling_PP: "Ubodna spojnica",
        barb_cross_PPPP: "Ubodni križni komad",
        barb_cap_P: "Ubodni završni komad",
        barb_coupling_PT: "Ubodni navojni adapter",
        barb_tee_PTP: "Ubodni T-komad s navojem",
        barb_valve_PT: "Ubodni Ventil na navoj",
        barb_valve_PP: "Ubodni Ventil",
        twlc_elbow_PP: "Brzospajajuće koljeno",
        twlc_tee_PPP: "Brzospajajući T-komad",
        twlc_coupling_PP: "Brzospajajuća spojnica",
        twlc_cross_PPPP: "Brzospajajući križni komad",
        twlc_cap_P: "Brzospajajući završni komad",
        twlc_coupling_PT: "Brzospajajući navojni adapter",
        twlc_tee_PTP: "Brzospajajući navojni T-komad",
        twlc_valve_PT: "Brzospajajući ventil na navoj",
        twlc_valve_PP: "Brzospajajući ventil",
        dl_valves: "Specijalni ventili",
        //pipe
        hdpeSDR9: "Cijev HDPE SDR 9",
        hdpeSDR11: "Cijev HDPE SDR 11",
        hdpeSDR136: "Cijev HDPE SDR 13.6",
        hdpeSDR17: "Cijev HDPE SDR 17",
        hdpeSDR176: "Cijev HDPE SDR 17.6",
        ldpeSDR9: "Cijev LDPE SDR 9",
        ldpeSDR11: "Cijev LDPE SDR 11",
        ldpeSDR136: "Cijev LDPE SDR 13.6",
        ldpeSDR17: "Cijev LDPE SDR 17",
        pvcSCH40: "Cijev PVC SCH40",
        pvcSCH80: "Cijev PVC SCH80",
        pvcCL315: "Cijev PVC CLASS 315",
        pvcCL200: "Cijev PVC CLASS 200",
        pvcCL160: "Cijev PVC CLASS 160",
        pvcCL125: "Cijev PVC CLASS 125",
        pvcUSCJPN18: "Pipe PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Pipe PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Pipe PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Pipe PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Pipe PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "Cijev LDPE CLASS 3",
        compress_elbow_PT: "Kompresijsko navojno koljeno",
        compress_coupling_PT: "Kompresijska navojna spojnica",
        compress_tee_PTP: "Kompresijski T-komad s navojem",
        compress_cap_P: "Kompresijski završni čep",
        compress_elbow_PP: "Kompresijsko koljeno",
        compress_coupling_PP: "Kompresijska spojnica",
        compress_tee_PPP: "Kompresijski T-komad",
        compress_cross_PPPP: "Kompresijski križni komad",
        compress_single_clamp_saddle: "Obujmica",
        compress_ballvalve_PP: "Kompresijski Kuglasti ventil",
        compress_ballvalve_PT: "Kompresijski/Navojni Kuglasti ventil",
        customfit_elbow_PT: "Prilagodljivi / navojni lakat",
        customfit_coupling_PT: "Prilagodljivi / navojni spojnik",
        customfit_tee_PTP: "Prilagođeni / navojni T komad",
        customfit_cap_P: "Prilagođeni krajni čep",
        customfit_elbow_PP: "Prilagođeni lakat",
        customfit_coupling_PP: "Prilagođeni spojnik",
        customfit_tee_PPP: "Prilagođeni T komad",
        customfit_cross_PPPP: "Prilagođeni križ",
        customfit_single_clamp_saddle: "Jednostavna spojnica s upornicom",
        customfit_ballvalve_PP: "Prilagođeni kuglasti ventil",
        customfit_ballvalve_PT: "Prilagodljivi / navojni kuglasti ventil",
        thread_nipple: "Nipla",
        thread_coupling: "Navojna Spojnica",
        thread_mf_reducer: "Muško/Ženska redukcija",
        thread_mf_adapter: "Muško/Ženski adapter",
        thread_mf_bush: "Muško/Ženska kratka redukcija",
        thread_tee: "Navojni T-komad",
        thread_elbow: "Navojno koljeno",
        thread_mf_elbow: "Navojno Muško/Žensko koljeno",
        thread_cap: "Navojna kapa",
        thread_plug: "Navojni čep",
        thread_union_nut: "Spojna matica",
        thread_cross: "Navojni križni komad",
        cable: "Cabel",
        wire: "Žica",
        // slip
        slip_single_clamp_saddle: "Obujmica (na PVC cijev)",
        slip_elbow_PT: "Slip/navojno koljeno",
        slip_coupling_PT: "Slip/navojna spojnica",
        slip_tee_PTP: "Slip T-komad s navojem",
        slip_cap_P: "Slip završni komad",
        slip_elbow_PP: "Slip koljeno",
        slip_coupling_PP: "Slip spojnica",
        slip_tee_PPP: "Slip T-komad",
        slip_cross_PPPP: "Slip križni komad",
        slip_ballvalve_PP: "Slip Kuglasti ventil",
        slip_ballvalve_PT: "Slip/navojni Kuglasti ventil",
        //extendables
        arbitraryFittings: "Proizvoljni spojevi",
        dripStartAssembly: "Priključni komplet za kap po kap",
        intakeAssembly: "Dolazni sklop",
        offtakeAssembly: "Izlazni sklop",
        numofvalves: "Broj ventila: ",
        numofvalvesshort: "Ventili: ",
        numofmanifs: "Broj razvoda: ",
        intakePipeSize: "Veličina dovodne cijevi: ",
        valveBoxes: "Ventilske kutije",
        valveAccessories: "Pribori za ventile",
        oneValveAccessories: "Pribor za ventil",
        controllerAccessories: "Pribor za programator",
        sensorAccessories: "Pribor za senzor",
        sprBodyAccessories: "Pribor za rasprskivače",
        rzwAccessories: "Pribor za navodnjavanje zone korijena",
        pipeStartFittings: "Proizvoljni spojevi opskrbne cijevi",
        qcAccessories: "Pribor za Q/C ventile",
        wiringAccessories: "Pribor za ožičenje",
        pipeSize: "Veličina cijevi: ",
        endOfPipe: "(Krajnja pozicija)",
        midOfPipe: "(Rezanje)",
        emptyRender: [
            "Nažalost... sadržaj nije raščlanjen",
            "Niste potpuno završili nijedan od čvorova navodnjavanja za prikaz"
        ],
        serviceFail: [
            "Nažalost... usluga prikaza specifikacija trenutno nije dostupna",
            "Molimo, pokušajte ponovno kasnije, kada veza bude uspostavljena",
            "Napominjemo da će konfiguracija koju ste ranije napravili i dalje biti pohranjena"
        ],
        serviceTrialExpired: [
            "Nažalost... usluga prikaza specifikacija nije dostupna za vaš račun",
            "To znači da je vaš probni period završen, a ako želite koristiti ovu uslugu",
            "<a href='/account/subscription'>možete nadograditi na PRO račun</a>"
        ],
        serviceLimitReached: [
            "Dosegli ste dnevni limit za prikaz specifikacija",
            "Kako biste uklonili limit na broj prikaza specifikacija po danu",
            "<a href='/account/subscription'>Možete nadograditi na PRO račun</a>"
        ],
        findInDrawing: "Prikaži na papiru",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Cijevi",
        labours_group_fittings: "Spojni materijal",
        labours_group_valveBoxes: "Ventilske kutije",
        labours_group_wires: "Ožičenje",
        labours_group_sprinklers: "Rasprskivači",
        labours_group_rws: "Navodnjavanje zone korjenja",
        labours_group_sprinklerConnections: "Spojevi rasprskivača",
        labours_group_drip: "Cijevi kap po kap i spojnice",
        labours_group_manifolds: "Razvodi",
        labours_group_quickCoupling: "Hidranti s brzim spojem",
        labours_group_controllers: "Programatori",
        labours_group_sensors: "Senzori",
        labours_group_trenches: "Rovovi",
        labours_group_insets: "Proturi",
        labours_group_lawns: "Travnjaci",
        labours_group_irrigatedArea: "Navodnjavana površina",
        labours_group_arbitrary_sp: "💦 Prilagođeni elementi navodnjavanja",
        labours_group_arbitrary_ld: "🌳 Prilagođeni elementi krajobraza",
        ldArbitrary_equip: "Oprema",
        ldArbitrary_labour: "Rad",
        spArbitrary_equip: "Oprema",
        spArbitrary_labour: "Rad",
        arbitrary_sp: '💦 Prilagođeni elementi navodnjavanja',
        arbitrary_ld: '🌳 Custom Landscape elements',
        ldLine_labour: "Linija",
        ldLine_equip: "Linija",
        spLine_labour: "Linija",
        spLine_equip: "Linija",
        ldLineWithArea_labour: "Linija (m2)",
        ldLineWithArea_equip: "Linija (m2)",
        spLineWithArea_labour: "Linija (m2)",
        spLineWithArea_equip: "Linija (m2)",
        ldVolumetricLine_labour: "Linija (m3)",
        ldVolumetricLine_equip: "Linija (m3)",
        spVolumetricLine_labour: "Linija (m3)",
        spVolumetricLine_equip: "Linija (m3)",
        polyLdSurface_labour: "Površina",
        brushLdSurface_labour: "Površina",
        polyLdSurface_equip: "Površina",
        brushLdSurface_equip: "Površina",
        polySpSurface_labour: "Površina",
        brushSpSurface_labour: "Površina",
        polySpSurface_equip: "Površina",
        brushSpSurface_equip: "Površina",
        polyLdVolumetricSurface_labour: "Površina (m3)",
        brushLdVolumetricSurface_labour: "Površina (m3)",
        polyLdVolumetricSurface_equip: "Površina (m3)",
        brushLdVolumetricSurface_equip: "Površina (m3)",
        polySpVolumetricSurface_labour: "Površina (m3)",
        brushSpVolumetricSurface_labour: "Površina (m3)",
        polySpVolumetricSurface_equip: "Površina (m3)",
        brushSpVolumetricSurface_equip: "Površina (m3)",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "Siječanj", "Veljača", "Ožujak", "Travanj", "Svibanj", "Lipanj", "Srpanj", "Kolovoz", "Rujan", "Listopad", "Studeni", "Prosinac"],
        MMM: ["\x01", "Sij", "Vel", "Ožu", "Tra", "Svi", "Lip", "Srp", "Kol", "Ruj", "Lis", "Stu", "Pro"],
        dddd: ["\x02", "Nedjelja", "Ponedjeljak", "Utorak", "Srijeda", "Četvrtak", "Petak", "Subota"],
        ddd: ["\x03", "Ned", "Pon", "Uto", "Sri", "Čet", "Pet", "Sub"],
        //buttonsCaps
        ok: "Ok",
        save: "Spremi",
        on: "Uklj",
        off: "Isklj",
        apply: "Primijeni",
        defaults: "Zadano",
        retry: "Pokušaj ponovno",
        finish: "Završi",
        safeRestart: "Sigurno ponovno pokretanje",
        saveAndExit: "Spremi i Izađi",
        exit: "Izađi",
        cancel: "Odustani",
        rename: "Preimenuj",
        idk: "Ne znam",
        getFile: "Dohvati datoteku",
        reset: "Poništi",
        random: "Slučajno",
        //misc
        zoneNum: "Zona #",
        valveNum: "Ventilska kutija #",
        zonesColoring: "Bojanje Zona",
        coversColoured: "Bojaj markice rasprskivača",
        dripsColoring: "Boje cijevi kap po kap",
        dripsSameAsZonesColored: "Kap po kap cijevi obojane bojom zone",
        //saveOflline
        saveOffline: [
            "Žao nam je... veza je izgubljena",
            "Ali ne brinite, možete nastaviti s projektom u izvanmrežnom načinu rada.",
            "Dok ste izvan mreže - sve vaše spremljene promjene biti će spremljene kao tekstualna datoteka u mapi preuzimanja vašeg preglednika.",
            "Kasnije možete učitati zadnju verziju vašeg nacrta na poslužitelj."
        ],
        restartOffline: [
            "Žao nam je... veza je izgubljena",
            "Ali ne brinite, vaš projekt je spremljen lokalno na vašem računalu.",
            "Možete ga pronaći u mapi preuzimanja preglednika.",
            "Ako želite raditi izvanmrežno, možete preuzeti izvanmrežnu verziju aplikacije iz vašeg ormarića na http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Žao nam je... nešto je pošlo po zlu prilikom učitavanja vašeg projekta",
            "Čini se da je vaše prethodno spremanje nekako oštećeno.",
            "Ali ne brinite, mi to možemo popraviti.",
            "Vaš projekt će sada u Radionici bit označen kao 'Oštećen'.",
            "Naš tehnički tim pobrinuti će se za ovu situaciju čim prije moguće."
        ],
        corruptedSavingFile: [
            "Žao nam je... datoteka koju pokušavate učitati nije čitljiva",
            "Ali ne brinite, mi to možemo popraviti.",
            "Sve što trebate učiniti je predati ovu oštećenu datoteku u obliku datoteke učitavanja u vašoj radionici.",
            "A zatim ćemo je pokušati popraviti da opet radi."
        ],
        ajaxReqFail: [
            "Žao nam je... Izgubili smo vezu s poslužiteljem",
            "Trenutno nije moguće slati/primati podatke",
            "Molimo pokušajte kasnije"
        ],
        critical: [
            "Žao nam je... nešto je pošlo po krivu",
            "Ali ne brinite, vaš nacrt je na sigurnom mjestu, samo kliknite na gumb za sigurno ponovno pokretanje kako bi nastavili..."
        ],
        fatal: [
            "Žao nam je... nešto je pošlo po krivu",
            "Molimo vas pomozite nam unaprijediti našu uslugu. Opišite nakon kojih korisničkih radnji se pojavila ova pogreška",
            "Ovdje unesite informacije"
        ],
        areYouSure: [
            "Upravo se spremate zatvoriti ovaj projekt",
            "Imajte na umu da će sve nespremljene promjene biti izgubljene.."
        ],
        pickAnotherCSVFile: "Odaberite drugu datoteku",
        csvFileTooBig: [
            "Prekoračena je maksimalna veličina csv datoteke",
            "Zbog optimizacije, maksimalna veličina obrađene csv datoteke ograničena je na 4 MB"
        ],
        notAnCSV: [
            "Žao nam je, ovaj tip datoteke nije podržan",
            "Podržani formati: .csv"
        ],
        invalidCSV: [
            "Nevažeći sadržaj CSV datoteke",
            "Pogreška pri analizi izvozne datoteke aplikacije Moasure, provjerite je li datoteka pravilno izvezena"
        ],
        pickAnotherImage: "Odaberite drugu sliku",
        imageTooBig: [
            "Prekoračena maksimalna veličina slike",
            "Zbog optimizacije, maksimalna podržana veličina slike je ograničena na 10 MB"
        ],
        notAnImage: [
            "Nažalost, ovaj tip datoteke nije podržan",
            "Podržani formati slika: .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "Akcija OGRANIČENA",
            "Ova akcija nije dozvoljena za BESPLATNU pretplatu"
        ],
        goPro: 'GO PRO',
        renameLayout: "Unesite novo ime",
        areYouSureDeleteLayout: [
            "Pažnja! Ova akcija se ne može poništiti",
            "Jeste li sigurni da želite izbrisati: ",
            "Izbriši"
        ],
        setUnderlaySize: [
            "Postavite dužinu crte koju ste upravo nacrtali",
            "Unijeli ste pogrešnu vrijednost. Molimo pokušajte ponovno"
        ],
        setMonitorDiagonal: [
            "Molimo dajte nam informaciju o veličini dijagonale vašeg monitora",
            "Unijeli ste pogrešnu vrijednost. Molimo pokušajte ponovno"
        ],
        getSpecsTable: [
            "Podesite postavke izvoza specifikacije",
            "Grupirajte opremu po ",
            "Čvoru", "Proizvođaču",
            "Postavite tip datoteke kao ",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Unesite naslov",
            "Izgled #",
            "Spremi",
            "Spremanje specifikacija",
            "Završeno. Kliknite ovdje za otvaranje",
            "Spremanje nije uspjelo",
            "Ažurirajte postojeće izglede",
            "Ažuriraj",
            "Ažuriranje izgleda"
        ],
        exportLayoutsAsPdf: [
            "Odaberite nacrte za izvoz",
            "odvojene datoteke (u razvoju)",
            "jedan album",
            "Izvoz",
            "Izvezi nacrte u"
        ],
        differentSprGroups: [
            "Neuspjelo spajanje različitih tipova potrošača vode na ovoj cijevi",
            "Prema standardima u projektiranju navodnjavanja, nije prihvatljivo miješati različite tipove potrošača ili rasprskivače sa različitim intenzitetima kišenja u istoj zoni"
        ],
        tooFarAwaySpr: [
            "Neuspjelo spajanje potrošača",
            "Neki od potrošača su predaleko od lateralne cijevi da bi bili povezani. Maksimalnu udaljenost povezivanja možete konfigurirati u postavkama."
        ],
        outlayerConfig: [
            "Konfiguracija specifikacija"
        ],
        presetsMenu: {
            title: "Predlošci",
            titleTextboxLabel: "Naziv predloška",
            descriptionTextboxLabel: "Opis",
            applyButton: "<i class='far fa-check-circle'></i>&nbsp;Primijeni",
            defaultButton: "<i class='far fa-undo'></i>&nbsp;Postavi kao zadano",
            removeButton: "<i class='far fa-trash'></i>&nbsp;Ukloni",
            updateButton: "<i class='far fa-sync'></i>&nbsp;Ažuriraj",
            createButton: "<i class='far fa-plus'></i>&nbsp;Izradi novi",
            closeButton: "<i class='far fa-times'></i>&nbsp;Zatvori",
            favorites_drawing: "Omiljeni alati (Crtanje)",
            favorites_sprinkling: "Omiljeni alati (Navodnjavanje)",
            favorites_layouting: "Omiljeni alati (Nacrti)",
            configs_drawing: "Konfiguracija Projekta",
            configs_outlayer: "Konfiguracija Specifikacija",
        },
        newPresetItem: "Novi predložak",
        cL_alreadyConnected: [
            "Neuspjelo spajanje linija",
            "Te su linije već spojene na"
        ],
        cL_segOnElem: [
            "Neuspjelo spajanje linija",
            "Ne možete se spojiti na segment koji se nalazi na"
        ],
        cL_strangeError: [
            "Neuspjelo spajanje linija",
            "Ispričavamo se... Spajanje nije uspjelo"
        ],
        cL_misgrouping: [
            "Neuspjelo spajanje linija",
            "Te linije imaju potrošače koje nije preporučljivo staviti na istu zonu. Ako ih želite spojiti unatoč tome, uključite 'Nesiguran način' za grupiranje rasprskivača u konfiguraciji projekta"
        ],
        cL_valve: "Razvod ventila",
        cL_waterSource: "Izvor vode",
        cL_dripStart: "Priključak za kap po kap",
        cL_controller: "Programator",
        cL_sensors: "Senzor",
        cL_valves: "Razvod ventila",
        cL_notSameVariant: [
            "Neuspjelo spajanje linija",
            "Te linije su različite vrste",
            "Vrsta trenutno crtane linije",
            "Vrsta linije s kojom želite spojiti"
        ],
        hasRestorableProject: [
            "Imate nespremljene podatke za ovaj projekt",
            "Možete vratiti nespremljeno stanje iz snimka napravljenog u"
        ],
        restoreProject: "Vrati",
        imageLost: [
            "Nažalost, ne možemo pronaći neke slika podloge na poslužitelju",
            "Ova slika nije pronađena:"
        ],
        precipCalcError_mixedError: [
            'Pogreška u kartama oborina',
            'Neuspjelo stvaranje karata oborina za kombinaciju prskalica:',
        ],
        precipCalcError_mprNonMprRot: 'Ne mogu se miješati obični rotori i rotori s MPR mlaznicama',
        precipCalcError_mprNozNonMprRot: 'Ne mogu se miješati MPR mlaznice i obični rotori',
        precipCalcError_staticNozRot: 'Ne mogu se miješati statičke mlaznice s rotorima',
        precipCalcError_staticMprNoz: 'Ne mogu se miješati statičke mlaznice s MPR mlaznicama',
        precipCalcError_missingError: [
            'Pogreška u kartama oborina',
            'Nedostaju profili oborina za prskalice:',
        ],
        precipCalcError_zoningError: [
            'Pogreška zoniranja u kartama oborina',
            'Neuspjelo stvaranje karata oborina za kombinaciju prskalica:',
        ],
        precipCalcError_noZoneAndZone: 'Nije moguće izračunati oborine za povezane i nepovezane rotore istovremeno. Vrijeme rada je nepoznato, stoga je broj okretaja rotora neizvjestan',
        algoNozzler_noSolutions: [
            'Nisu pronađena moguća rješenja za postavljanje prskalica',
            'Pokušajte sljedeće:',
            '1. Promijenite ograničenja preklapanja i druge opcije u izborniku konfiguracije alata za automatsko postavljanje',
            '2. Odaberite drugu vrstu prskalica jer mogu pružiti potrebnu fleksibilnost u postavljanju',
            '3. Koristite gumb ispod za ponovno pokretanje rješavanja s "labavijim" ograničenjima za preklapanje i pokrivanje'
        ],
        retryWithLooseOptions: "Pokušajte ponovno s 'labavijim' opcijama",
        cannotSaveBecauseOffline: [
            "Nije uspjelo slanje zahtjeva poslužitelju",
            "Nema veze s poslužiteljem",
            "Provjerite imate li internetsku vezu",
            "Kako ne biste izgubili podatke, ne zatvarajte ovaj prozor i pokušajte ponovno spremiti podatke kasnije, kada se uspostavi veza s poslužiteljem",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Nije uspjelo spremanje zahtjeva",
            "Previše pokušaja s neispravnim s kodom",
            "Provjerite jeste li točno unijeli adresu e-pošte i pokušajte ponovno nakon 30 sekundi.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Spremanje zahtjeva nije uspjelo",
            "Unijeli ste neispravnu e-mail adresu",
            "Provjerite jeste li ispravno unijeli e-mail adresu i pokušajte ponovo",
            "",
            "",
        ],
        designRequestCompleted: [
            "Vaš zahtjev je uspješno stvoren/ažuriran",
            "Link za uređivanje", "kopiraj me",
            "Link za pregled", "kopiraj me",
        ],
        designRequestContacts: [
            "Contact information",
            "Organization",
            "Name",
            "Email",
            "Phone",
            "Address",
            "Website",
        ],
        "designRequestInfo": [
            "Dobrodošli u Design Studio!",
            "Ovdje možete brzo i lako kreirati zahtjev za planiranje vašeg sustava za navodnjavanje.",
            "Ovdje možete pronaći <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>video s uputama</a>",
            "Za dodatne informacije ili ako imate bilo kakvih pitanja, slobodno nas kontaktirajte."
        ],
        approveActionByCode: [
            "Potvrdi radnju",
            "Na vašu e-mail adresu je poslan email s potvrdnim kôdom.",
            "Molimo unesite ovaj kôd u polje ispod",
            "Unijeli ste neispravan broj, pokušajte ponovno"
        ],
        "revisionCheckFailedSoft": [
            "Sukob revizija!",
            "Ovaj projekt trenutno je otvoren u drugom pregledniku ili uređaju.",
            "Možete prebrisati podatke na serveru (budući da pohranjujemo samo jednu verziju vašeg projekta) klikom na `prepiši`, ali budite oprezni - sav napredak ostvaren u drugim sesijama bit će izgubljen!",
            "Bolja strategija je razumjeti gdje i tko je otvorio ovaj projekt i odlučiti čija je verzija ažurirana.",
            "Ako želite preuzeti kontrolu nad najnovijom verzijom ovog istovremeno otvorenog projekta, možete ponovno otvoriti ovaj projekt dupliciranjem ove kartice u pregledniku.",
        ],
        "revisionBlocked": [
            "Spremanje je blokirano od strane Admina!",
            "Trenutno naš tehnički tim pregledava vaš projekt zbog pogrešaka koje se događaju u njemu.",
            "Molimo pričekajte dok pregled ne bude završen, nakon toga ćete biti obaviješteni e-poštom s daljnjim uputama.",
        ],
        missingVariants: [
            'Pogreška nedostajućih elemenata',
            'U nastavku je popis prilagođenih elemenata koji nedostaju u vašoj projektnoj biblioteci i stoga se ne mogu prikazati:',
            'Molimo uključite Setove koji sadrže te elemente u izborniku za konfiguraciju projekta (u Radionici)'
        ],
        "openInOtherTab": "Otvori najnovije",
        "overwrite": "Prepiši",
        "saveToFile": "Spremi u datoteku",
        filterSelection_exclude: "Isključi iz odabira",
        filterSelection_include: "Uključi u odabir",
        filterSelectionNames: {
            sprinklers: "Potrošači",
            sprinklers_nozzle: "Potrošači - Dizne",
            sprinklers_rotaryNozzle: "Potrošači - Rotacijske dizne",
            sprinklers_rotor: "Potrošači - Rotori",
            sprinklers_bubbler: "Potrošači - Bubbleri",
            sprinklers_bubblerNozzle: "Potrošači - Bubbleri-dizne",
            sprinklers_pinpoint: "Potrošači - Precizni rasprskivači",
            dripStarts: "Priključci za kap po kap",
            rzwLayer: "Navodnjavanje zone korijenja",
            dripLines: "Cijevi kap po kap",
            valvesLayer: "Razvodi ventila",
            waterSources: "Izvori vode",
            controllers: "Programatori",
            sensorsLayer: "Senzori",
            mainPipes: "Opskrbne cijevi",
            lateralPipes: "Lateralne cijevi",
            trenchesLayer: "Rovovi",
            insetsLayer: "Proturi",
            wiresLayer: "Ožičenje",
            wirelessLayer: "Bežična veza",
            senswirelessLayer: "Bežična veza senzora",
            senswiresLayer: "Ožičenje senzora",
            quickCoupLayer: "Hidrantski spojevi",
            surfaces: "Poligoni i linije",
            ldItemsLayer: "Elementi pejzaža",
            ldArbitraryLayer: "Prilagođeni elementi pejzaža",
            spArbitraryLayer: "Prilagođeni elementi navodnjavanja",
            overlays: "Elementi rasporeda",
            stampTexts: "Tekstovi pečata"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Priključak rasprskivača",
        fcType: "Tip veze",
        sj: "Zglobni priključak",
        sprinklerStand: "Sprinkler stand (Riser)",
        flexPipeBarbs: "Fleksibilne cijevi + Ubodni elementi",
        minFlexPipeLength: "Minimalna duljina fleksibilne cijevi po spoju",
        midSprinkPipeFitting: "Priključak rasprskivača na cijev",
        endSprinkPipeFitting: "Priključak rasprskivača na kraj cijevi",
        single_clamp_saddle: "Obujmica",
        tee_PTP: "T-komad sa ženskim BSP navojem",
        elbow_PT: "Koljeno sa ženskim BSP navojem",
        coupling_PT: "Adapter sa ženskim BSP navojem",
        //MANIFOLD NODE CONFIGS
        manifoldNode: "Razvod ventila",
        valvesOutlay: "Raspored ventila",
        fold: "Grupno",
        unfold: "Pojedinačno",
        threadsNode: "Navojni spojevi",
        threadTypes: "Vrste navoja",
        //AUTOMATION NODE CONFIGS
        automationNode: "Automatika",
        controllerModules: "Odabrani moduli za proširenje za modularni programator:",
        controllerVoltage: "Ulazni napon programatora:",
        controllerVoltageV2: "Ulazni napon programatora:",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automatski (najbolje odgovara)",
        userModules: "Ručno (kao dodatak)",
        //RZW NODE
        rzwNode: "Navodnjavanje zone korijenja",
        midRZWPipeFitting: "Priključak RWS-a na cijev",
        endRZWPipeFitting: "Priključak RWS-a na kraj cijevi",
        //DRIP node
        dripNode: "Navodnjavanje kap po kap",
        dripConnectionType: "Tip spojeva za kap po kap",
        dripLengthPrecision: "Znamenke nakon decimalne točke u duljini cijevi",
        dripTubingAddon: "Dodatak cijevima kap po kap",
        barb: "Ubodni spojevi",
        twistLock: "Brzospajajući spojevi",
        dripSpikesStep: "Razmak držača za cijev kap po kap",
        dripCrossFittingAble: "Križni spoj cijevi kap po kap omogućen",
        pipesNode: "Cjevovod",
        hdpeConnectionType: "Tip spojeva za HDPE",
        ldpeConnectionType: "Tip spojeva za LDPE",
        pvcConnectionType: "Tip spojeva za PVC",
        pipeAddon: "Dodatak cijevima za svaki promjer",
        pipeLengthPrecision: "Znamenke nakon decimalne točke u duljini cijevi",
        crossFittingAble: "Križni spoj cijevi omogućen",
        compress: "Kompresijski spojevi",
        customfit: "Prilagođeni priključci",
        slip: "Slip fittings",
        wiringNode: "Ožičenje",
        exportNode: "Opcije izvoza",
        exportNumbersPrecision: "Znamenke nakon decimalne točke u brojevima",
        basicWiringMethod: "Metoda ožičenja automatike",
        cableCoresArray: "Raspon broja žila u kabelu",
        noAutoWiring: "Dodaj ožičenje ručno",
        separateCableToManifold: "Odvojeni višežilni kabel do razvoda",
        separateWireToValve: "Odvojena žica za ventil + zajednička žica do razvoda ventila",
        maxCableCores: "Maksimalni broj žila u kabelu",
        verticalWiringAddon: "Okomiti dodatak žice prema programatoru",
        verticalSensWiringAddon: "Okomiti dodatak žice prema senzoru",
        wireAddon: "Dodatak žice za svaki tip",
        wireLengthPrecision: "Znamenke nakon decimalne točke u duljini ožičenja",
        //DRAWER CONFIG
        drawerConfig: [
            "Konfiguracija projekta"
        ],
        //SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Rasprskivači",
        pressureDefinedBy: "Očekivani tlak na rasprskivaču je",
        allowReduceRotors: "Dopušteno je smanjiti domet rotora",
        autoconnector: "Interaktivno povezivanje prskalica s bočnim cjevovodom",
        radio_option_yes: "Da",
        radio_option_no: "Ne",
        extreme_rotor_reduction: "Ekstremno (Do 50%) (Može uzrokovati neujednačene oborine)",
        radio_option_yes2: "Da",
        takeReductionInAccountWhenAutoPlacing: "Ponuditi smanjene dosege prskalica pri automatskom postavljanju",
        takeReductionInAccountWhenAutoPlacingForRotors: "Ponuditi smanjene dosege prskalica pri automatskom postavljanju (Rotors)",
        recommendedPressure: "Preporučeno od proizvođača",
        userPressure: "Postavljeno od strane korisnika",
        expPressure: "Očekivani tlak na rasprskivaču",
        sprinklerGroupMode: "Grupiranje rasprskivača",
        safeSprGroupMode: "Striktni način (grupira samo kompatibilne)",
        unsafeSprGroupMode: "Nesiguran način (UPOZORENJE! Bez ograničenja grupiranja)",
        "sprinklerAttachBulkMode": "Način Masovnog Povezivanja Potrošača",
        "safeSprAttachMode": "Ne ponovno povezuj već povezane potrošače",
        "unsafeSprAttachMode": "Nesiguran način (UPOZORENJE! Moguće je ponovno povezivanje već povezanih potrošača. Koristite na vlastiti rizik)",
        //UNITS CONFIG
        unitsConfig: "Jedinice mjere",
        precisionStd: "Znamenke nakon decimalne točke",
        unitsSystemGridAndRuler: "Sustav mjernih jedinica za mrežu i ravnalo",
        distanceUnits: "Udaljenost",
        distancePrecision: "Znamenke nakon decimalne točke",
        trenchSizeUnits: "Jedinice dimenzija",
        trenchSizePrecision: "Znamenke nakon decimalne točke",
        sprinklerDistUnits: "Domet rasprskivača",
        sprinklerDistPrecision: "Znamenke nakon decimalne točke",
        areaUnits: "Površina",
        areaPrecision: "Znamenke nakon decimalne točke",
        volumeUnits: "Volumen",
        volumePrecision: "Znamenke nakon decimalne točke",
        waterFlowUnits: "Protok vode",
        waterFlowPrecision: "Znamenke nakon decimalne točke",
        pressureUnits: "Tlak",
        pressurePrecision: "Znamenke nakon decimalne točke",
        velocityUnits: "Brzina",
        velocityPrecision: "Znamenke nakon decimalne točke",
        precipRateUnits: "Intenzitet kišenja",
        precipRatePrecision: "Znamenke nakon decimalne točke",
        // ZONE PROPS CONFIG
        climateConfig: "Izračun vremena navodnjavanja",
        lawnCultureType: "Tip trave",
        coolLoving: "Trava za hladnija područja",
        warmLoving: "Trava za toplija područja",
        climateTemp: "Prosječna ljetna temperatura",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Prosječna vlažnost ljeti",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Mikroklima zone&nbsp;<i class='far fa-question-circle'></i>",
        microClimateTooltip: "Blaga\n" +
            "Navodnjavane površine koje su u hladu, zaštićene od vjetra i daleko od suhih i zagrijanih objekata\n" +
            "\n" +
            "Normalna\n" +
            "Mjesta u krajoliku gdje je mikroklima predstavljena generalnim okolnim uvjetima, a gdje prisustvo\n" +
            "zgrada, trotoara, staza, hlada itd. ne utječe značajno na vrijednosti evapotranspiracije.\n" +
            "Ovi uvjeti se smatraju prosječnim ili standardnim i ne predstavljaju značajne izazove za rast biljaka.\n" +
            "\n" +
            "Teška\n" +
            "Oslikava uvjete koji otežavaju rast biljaka i lako se dolazi u stanje stresa ako biljka nije pravilno navodnjavana. To može biti otvoreno mjesto, jako izloženo suncu, u blizini staza, zgrada ili drugih krajobraznih struktura, reflektiranje sunčevih zraka od stakla ili  pored krajobraznih elemenata koji apsorbiraju toplinu, ili može biti mjesto izloženo vjetru.",
        gentleMicroClimate: "Blaga",
        normalMicroClimate: "Normalna",
        toughMicroClimate: "Teška",
        soilType: "Sastav tla u zonama navodnjavanja",
        sand: "Pijesak",
        sandyLoam: "Ilovasta pjeskulja",
        lightLoam: "Pjeskovita ilovača",
        mediumLoam: "Obična ilovača",
        heavyLoam: "Teža ilovača",
        clay: "Glinasta ilovača",
        heavyClay: "Teška glina",
        zoneSlope: "Nagib tla u zonama navodnjavanja",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Vodeni budžet",
        lowWB: "Nizak",
        normalWB: "Normalan",
        highWB: "Visok",
        ft: "feet",
        in: "inch",
        ftin: "feet/inches",
        metric: "Metrički",
        imperialUS: "Imperijalni (US)",
        //UNITS CONFIG
        hydraConfig: "Hidraulika",
        waterTemp: "Temperatura vode",
        maxFlowVelocity: "Maksimalna brzina tečenja u cijevima",
        "commonConfig": "Opće postavke",
        "lateralNozzlerSwitch": "Kako preći na način pričvršćivanja mlaznica",
        "NStabonly": "Tab",
        "NStabshift": "Tab+Shift",
        "showActionSubtitles": "Prikaži podnaslove akcija",
        "Yeah": "Da",
        "Nope": "Ne",
        start: "Pokreni",
        recalibrate: "Ponovno kalibriraj",
        calibrationSuccess: [
            "Uspješno kalibrirano",
            "Sada možete koristiti zaslon osjetljiv na dodir u dva načina - 'pomicanje kursora' (lagani dodir i pokret) i 'način povlačenja' (čvrsti dodir i pokret)"
        ],
        calibrationFailEqual: [
            "Kalibracija nije uspjela",
            "Nismo otkrili nikakvu značajnu razliku u načinu dodira zaslona u oba načina",
            "Možete pokušati ponovno. I uvjerite se da koristite prst, a ne olovku"
        ],
        calibrationFailImproper: [
            "Kalibracija nije uspjela",
            "Otkrili smo veći pritisak na perju nego na nakovnju",
            "Možete pokušati ponovno. I uvjerite se da premještate pero s manjim pritiskom nego nakovanj"
        ],
        calibrationImpossible: [
            "Kalibracija nije moguća",
            "Čini se da vaš uređaj ne podržava mjerenje područja dodira. Stoga ne možemo definirati dva načina za dodirnu interakciju",
            "U tom slučaju možete koristiti virtualni miš kako biste mogli povlačiti bilo što. Pojavit će se na lijevoj strani zaslona."
        ],
        calibrationNeeded: [
            "Potrebna kalibracija!",
            "Moramo kalibrirati vaš zaslon osjetljiv na dodir kako bismo mogli definirati dva načina dodirne interakcije:",
            "Način pomicanja kursora - kada samo želite pomicati kursor ili pomaknuti segment poligona prilikom crtanja",
            "I način povlačenja - to je kada želite premještati elemente ili ih mijenjati veličinu. Također biste trebali povlačiti-pomicati kada želite odabrati više stavki",
            "Molimo kliknite na gumb Pokreni i slijedite upute na ekranu"
        ],
        insertImage: 'Umetni',
        mapImagePicker: [
            "Učitavač satelitskih slika",
            "Geografska širina/Dužina",
            "Unesite geografsku širinu",
            "Unesite geografsku dužinu",
            "Trenutna lokacija",
            "Idi",
            "Adresa",
            "Upišite dio adrese i kliknite 'Traži'",
            "Traži",
            "Povećaj",
            "Panorama"
        ],
        "imageCrop": [
            "Crop tool"
        ],
        cropImage: "Crop",
        invalid_dataset_1: 'Invalid dataset. Project contains prohibited types of surfaces. Only irrigated (LAWN), non-irrigated and obstacles are allowed.',
        invalid_dataset_2: 'Invalid dataset. Not more or less than ONE irrigated surface is allowed.',
        invalid_dataset_3: 'Invalid dataset. Irrigated surface is self-intersected.',
        invalid_dataset_4: 'Invalid dataset. Obstacle marker should not be compound (Made of more than one polygon)',
        invalid_dataset_5: 'Invalid dataset. Obstacle surface should be fully contained within irrigated surface.',
        invalid_dataset_6: 'Invalid dataset. Project contains prohibited types of sprinklers. Allowed:',
        invalid_dataset_7: 'Invalid dataset. Precipitation rate of sprinklers is out of range',
        invalid_dataset_8: 'Invalid dataset. Sprinklers must not have individual pressure settings',
        invalid_dataset_9: 'Invalid dataset. The project should not set a custom expected pressure at the sprinklers',
        invalid_dataset_10: 'Invalid dataset. Uniformity is too low.',
        invalid_dataset_11: 'Invalid dataset. Overwatered area is too big.',
        layoutPresetsMenu: [
            "Postavke izgleda",
            "Trenutna postavka izgleda",
            "Postavka skupa izgleda",
            "Zadana postavka za novi izgled:",
            "- Odaberite postavku -",
            "- Nema dostupnih postavki -"
        ],
        edit: "Uredi",
        nozzleCharacteristicsConfig: "Konfiguracije karakteristika mlaznice",
        nozzleCharacteristicsConfig_lang: {
           // Main editor
           title: "Konfiguracija karakteristika mlaznice",
           save: "Spremi",
           cancel: "Odustani",
           reset: "Resetiraj",
           typeArc: "Luk",
           typeStrip: "Traka",
           typeVariableArc: "Promjenjivi luk",
           unknown: "Nepoznato",
           object: "Objekt",
           selectVariant: "Odaberi varijantu",
           editVariant: "Uredi varijantu",

           // Variant editor fields
           editData: "Uredi podatke o performansama",
           editPrecipMap: "Uredi kartu oborina",
           pressuresLabel: "Tlakovi",
           anglesLabel: "Kutovi",
           valuePairsLabel: "Parovi vrijednosti",
           valuesLabel: "Vrijednosti",
           pointsLabel: "točaka",
           valuesSuffix: "vrijednosti",
           pairsSuffix: "parovi",
           none: "nema",

           // Field name labels
           pressMap: "Tlak",
           angleMap: "Kut",
           valuesMap: "Vrijednosti",
           precipMap: "Oborine",
           reducableBy: "Množitelj smanjenja (0.0 - 1.0)",

           // Error messages
           invalidInputFormat: "Nevažeći format unosa.",
           fieldInvalidFormat: "Nevažeći format.",
           reducableByOutOfRange: "Vrijednost mora biti između 0.01 i 0.99.",

           // NozzleDataEditor translations (passed to that editor)
           dataEditor: {
               modeSingle: "Pojedinačni kutovi",
               modeRange: "Rasponi kutova",
               pressureAngleLabel: "Tlak/Kut",
               pressure: "Tlak",
               angle: "Kut",
               distance: "Udaljenost",
               flow: "Protok",
               addRow: "Dodaj redak",
               addCol: "Dodaj stupac",
               delete: "Obriši",
               save: "Spremi",
               cancel: "Odustani",
               reset: "Resetiraj",
               distanceUnit: "Jedinica udaljenosti",
               pressureUnit: "Jedinica tlaka",
               flowUnit: "Jedinica protoka",
               angleMode: "Način kuta:",
               cannotDeleteLastRow: "Ne može se obrisati zadnji redak!",
               cannotDeleteLastColumn: "Ne može se obrisati zadnji stupac!",
               angleRangesCannotIntersect: "Rasponi kutova ne mogu se presijecati!",
               pleaseFillAllCells: "Molimo ispunite sve ćelije! Prazne ćelije:",
               row: "Redak",
               col: "Stupac"
           },

           // PrecipMapEditor translations (passed to that editor)
           precipEditor: {
               precipitation: "Oborine",
               distance: "Udaljenost",
               addCol: "Dodaj stupac",
               delete: "Obriši",
               save: "Spremi",
               cancel: "Odustani",
               reset: "Resetiraj",
               precipitationUnit: "Jedinica oborina",
               cannotDeleteLastColumn: "Ne može se obrisati zadnji stupac!"
           }
        },
        experimentalConfig: "Eksperimentalne značajke",
        autoNozzlePlacer: "Pomoć pri postavljanju mlaznica na travnjaku (ALT onemogućuje)",
        stylesConfig: "Stilovi",
        linesStyles: "Stilovi cijevi i ožičenja",
        linesStyles_lang: {
            title: "Konfiguracija stilova linija",
            save: "Spremi",
            cancel: "Odustani",
            reset: "Vrati na zadano",
            // Group headers
            mainPipeGroup: "Boje glavne cijevi",
            lateralPipeGroup: "Boje bočne cijevi",
            dripLinesGroup: "Boje kapljičnih linija",
            wiresGroup: "Boje žica",
            // Color labels
            mpColor: "Glavna cijev",
            mpOverColor: "Glavna cijev (Prelazak)",
            mpPVCColor: "Glavna cijev PVC",
            mpPVCOverColor: "Glavna cijev PVC (Prelazak)",
            mpPVCMSColor: "Glavna cijev PVC Višežilna",
            mpPVCMSOverColor: "Glavna cijev PVC Višežilna (Prelazak)",
            lpColor: "Bočna cijev",
            lpOverColor: "Bočna cijev (Prelazak)",
            lpPVCColor: "Bočna cijev PVC",
            lpPVCOverColor: "Bočna cijev PVC (Prelazak)",
            lpPVCMSColor: "Bočna cijev PVC Višežilna",
            lpPVCMSOverColor: "Bočna cijev PVC Višežilna (Prelazak)",
            lpLDPESColor: "Bočna cijev LDPE-S",
            lpLDPESOverColor: "Bočna cijev LDPE-S (Prelazak)",
            dl16Color: "Kapljična linija 16mm",
            dl16OverColor: "Kapljična linija 16mm (Prelazak)",
            dl17Color: "Kapljična linija 17mm",
            dl17OverColor: "Kapljična linija 17mm (Prelazak)",
            wrColor: "Žica",
            wrOverColor: "Žica (Prelazak)",
            wrlsColor: "Bežično",
            wrlsOverColor: "Bežično (Prelazak)",
            swrColor: "Žica senzora",
            swrOverColor: "Žica senzora (Prelazak)",
            swrlsColor: "Bežični senzor",
            swrlsOverColor: "Bežični senzor (Prelazak)",
            dwrColor: "Podatkovni kabel",
            dwrOverColor: "Podatkovni kabel (Prelazak)"
        },
        continuousPlacementMode: "Način kontinuiranog postavljanja",
    }
};
