this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "láb/inch",
        sqm: "m²",
        acre: "acre",
        hectare: "hektár",
        sqft: "négyzetláb",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gallon",
        cubft: "ft³",
        lpm: "l/perc",
        lph: "l/óra",
        m3h: "m³/óra",
        USgpm: "gallon/perc",
        USgph: "gallon/óra",
        deg: "°",
        pcs: "db",
        pcsDot: "db.",
        pcsShort: "db.",
        percent: "%",
        in_Alt: "inch.",
        mps: "m/s",
        kph: "km/h",
        ftps: "láb/s",
        degreesCentigrade: "°C",
        mmph: "mm/ó",
        mmp24h: "mm/nap",
        inph: "inch/ó",
        // unconvertable
        min: "perc."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Automatikus rajzoló",
        chooseSprinkler: "Válassz fúvókát:",
        auto: "Automatikus beállítás",
        waterSource2row: ["Víz", "Beömlő"],
        setLineLength: "Adja meg a vezeték méretét (mm):",
        setPressure: "Adja meg a várt dinamikus nyomást a fúvókáknál (bar):",
        setMaxFlow: "Adja meg a maximális vízáramlást (l/perc):",
        controllerShort: "V",
        sensorShort: "É",
        action_activateEraser: "Radír aktiválása",
        action_deactivateEraser: "Radír deaktiválása",
        action_boolUnite: "Egyesít",
        action_boolIntersect: "Metsz",
        action_boolSubtract: "Kivon",
        action_boolExclude: "Kizár",
        action_changeSprayBody: "Permetező beállítása",
        action_changeVariant: "Változat beállítása",
        action_changeImgVariant: "Képváltozat beállítása",
        action_changeType: "Típus beállítása",
        action_addConsumers: "Fogyasztók hozzáadása",
        action_drawBranches: "Ágak hozzáadása",
        action_editLine: "Szegmensek szerkesztése",
        action_drawCircles: "Körök rajzolása",
        action_detachAll: "Minden leválasztása",
        action_drawBrush: "Ecset rajzolása",
        action_editBrush: "Ecset szerkesztése",
        action_changeBrushSize: "Ecset mérete",
        action_booleans: "Boolean műveletek",
        action_intoPoly: "Poligonná alakítás",
        action_intoBrush: "Ecsetté alakítás",
        action_activateRotation: "Forgatás",
        action_deactivateRotation: "Álló",
        action_markZones: "Zónák megjelenítése",
        action_unmarkZones: "Megjelölés eltávolítása",
        action_sprNames: "Szórófejek nevei",
        action_noSprNames: "Nevek eltávolítása",
        action_lockItem: "Zárolás",
        action_unlockItem: "Feloldás",
        Circle: "Kör",
        Triangle: "Háromszög",
        BushForm: "Bokrok",
        BushForm1: "Bokrok 1",
        BushForm2: "Bokrok 2",
        BushForm3: "Bokrok 3",
        Square: "Négyzet",
        noShadow: "Nincs",
        standardShadow: "Standard",
        noArrows: "Nincs",
        startArrow: "Az elején",
        endArrow: "A végén",
        bothArrows: "Mindkét oldalon",
        normalSizeSide: "Normál",
        invertedSizeSide: "Fordított",
        strMiter: "Éles",
        strRound: "Kerek",
        strBevel: "Lekerekített",
        strSquare: "Négyzet",
        strButt: "Vége",
        FWnormal: "Normál",
        FWbold: "Félkövér",
        FWitalic: "Dőlt",
        FWbolditalic: "Dőlt Félkövér",
        FJleft: "Balra",
        FJright: "Jobbra",
        FJcenter: "Középen",
        rzwHeight: "Magasság"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Selektor",
        //----Drawing
        selectPoly: "Nincs kijelölt elem",
        //----Sprinkling
        selectSprink: "Nincs kijelölt elem",
        lpNozzler: "Vízfogyasztók csatlakoztatása",
        dl16CircDrawer: "16/13mm csepegtető körök elhelyezése",
        dl16sDrawer: "16/13mm csepegtető hüvely rajzolása",
        dl17CircDrawer: "17mm csepegtető körök elhelyezése",
        dl17sDrawer: "17mm csepegtető hüvely rajzolása",
        "ldTextDrawer": "Szöveg konfiguráció",
        "staticTextDrawer": "Szöveg konfiguráció",
        "dynamicTextDrawer": "Szöveg konfiguráció",
        "ldStaticTextDrawer": "Szöveg konfiguráció",
        "ldtextEditor": "Szöveg szerkesztése",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Teljes távolság",
        type: "Típus",
        variant: "Változat",
        area: "Terület",
        perimeter: "Kerület",
        curveLength: "Hossz",
        treeDiameter: "Átmérő",
        bushDiameter: "Átmérő",
        nozTypes: "Elérhető típusok",
        nozType: "Típus",
        sprBod: "Szórófej teste",
        rad: 'Sugár',
        angle: 'Szög',
        reducedBy: 'Csökkentve',
        consump: 'Fogyasztás',
        pressure: 'Nyomás',
        coverSize: 'Lefedettség mérete',
        maxFlow: 'Maximális vízáramlás',
        pipesNum: "Csatlakoztatott csövek",
        pipeType: "Típus",
        pipeLength: "Hossz",
        wireLength: "Hossz",
        valvesManifNum: "Szelepösszeállítások",
        valvesNum: "Szelepek",
        propDiam: "Megfelelő átmérő",
        curDiam: "Rajzolt átmérő",
        outsNum: "Vízfogyasztók",
        flow: "Vízáramlás",
        precipRate: "Csapadékintenzitás",
        totalPrecipArea: "Teljes lefedettség",
        uniformity: "CU",
        uniformity2: "DU",
        overwatered: "Túlöntözött",
        precipRateShort: "Csapadék.",
        runtimeInd: "Futási idő",
        coveredArea: "Terület",
        microClimateInd: "M/Klíma",
        soilTypeInd: "Talajtípus",
        zoneSlopeInd: "Lejtő",
        maxInfiltrationRate: "Infiltrációs sebesség",
        waterDemand: "Vízigény",
        numOfRuns: "Napi ciklusok",
        timePerRun: "Időtartam ciklusonként",
        dailyConsumption: "Napi fogyasztás",
        dripsNum: "Csatlakoztatott csepegtető vonalak",
        dripType: "Csepegtetés típusa",
        dripRowsStep: "Sorok lépése a területen",
        dripRowsAngle: "Sorok szöge a területen",
        cntrType: "Vezérlő típusa",
        sensType: "Érzékelő típusa",
        zonesNum: "Vezérelt zónák",
        trenchWidth: "Szélesség",
        trenchDepth: "Mélység",
        trenchVolume: "Térfogat",
        insetDiam: "Átmérő",
        insetLength: "Hossz",
        insetVar: "Anyag",
        itemsCount: "Mennyiség",
        insetDepth: "Mélység",
        zoneName: "Zóna neve",
        valveName: "Szelep doboz neve",
        itemAlias: "Alias",
        lineWidth: "Szélesség",
        lineDepth: "Mélység",
        lineArea: "Terület",
        lineVolume: "Térfogat",
        surfaceDepth: "Mélység/Magasság",
        surfaceVolume: "Térfogat",
        //MULTISELECTOR
        itemsSelected: "Kiválasztott",
        totalArea: "Teljes terület",
        totalPerimeter: "Teljes kerület",
        totalLength: "Teljes hossz",
        totalVolume: "Teljes térfogat",
        totalConsumption: "Teljes fogyasztás",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Statuses
        isSelfCrossing_true: "Érvénytelen poligon",
        isSelfCrossing_false: "Érvényes poligon",
        isConnected_true: "Csatlakoztatva",
        isConnected_false: "Nincs csatlakoztatva",
        isWired_true: "Vezetékekkel összekötve",
        isWired_false: "Vezetékekkel nem összekötve",
        isDripZone_true: "Csepegtető övezet",
        isDripZone_false: "",
        isSprinklerZone_true: "Szórófejes övezet",
        isSprinklerZone_false: "",
        isOverloaded_true: "TÚLTERHELT!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Alacsony nyomás",
        isUnderpressured_false: "",
        isOverpressured_true: "Magas nyomás",
        isOverpressured_false: "",
        isLocked_true: "Zárolva",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Rozsdamentes acél",
        "High speed": "Magas sebesség",
        "Opposing nozzle": "Ellentétes fúvóka",
        "Plastic": "Műanyag",
        "MPR Nozzles": "MPR Fúvókák",
        "Rotary Nozzles": "Rotációs fúvókák",
        Nozzles: "Fúvókák",
        "Bubbler nozzles": "Buborékoló fúvókák",
        "Multi-stream": "Többáramú",
        "Dual-stream": "Kettős áram",
        "Stream Nozzles": "Áramló fúvókák",
        "Short Radius Nozzles": "Rövid sugárú fúvókák",
        "Pressure compensating": "Nyomáskompenzált",
        "Adjustable flood": "Állítható áradat",
        Adjustable: "Állítható",
        Fixed: "Rögzített",
        "Fixed Arc": "Rögzített ív",
        "Strip Pattern": "Csíkmintás",
        "Drip line": "Csepegtető vonal",
        "Drip cover": "Csepegtető takaró",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "Emitteres",
        "noemitter": "Emitter nélküli",
        "Root zone watering": "Gyökérzóna öntözése",
        Lateral: "Oldalirányú",
        Main: "Fő",
        Trench: "Árok",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC (metrikus)",
        ldpe: "LDPE",
        Controller: "Vezérlő",
        Sensor: "Érzékelő",
        Wiring: "Kábelezés",
        IrrigateMarks: "Öntözési zónák",
        Surface: "Felszín",
        Lawn: "Gyep",
        Bed: "Ágyás",
        Shrubs: "Bokrok",
        Path: "Ösvény",
        Concrete: "Beton",
        Sand: "Homok",
        Water: "Víz",
        Bedding: "Alap",
        Flower: "Virágok",
        Herbal: "Gyógynövényes",
        geographic: "Földrajzi",
        sizeMark: "Méretek",
        scalingBar: "Mérőlécek",
        loCurves: "Görbék",
        texts: "Szövegek",
        staticText: "Statikus szöveg",
        dynamicText: "Dinamikus szöveg",
        stampText: "Bélyegző szöveg",
        stampTextDefault: "Szöveg",
        stampTextgr1: "Dokumentum meghatározása",
        stampTextgr2: "Cím cella",
        stampTextgr3: "Hely neve",
        stampTextgr4: "Rajz neve",
        stampTextgr9: "Szervezet információi",
        stampTextgr6t: "Szakasz",
        stampTextgr7t: "Oldal",
        stampTextgr8t: "Oldalak",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Fejezet.",
        stampTextgr15t: "Tan.",
        stampTextgr16t: "Oldal",
        stampTextgr17t: "# Dok.",
        stampTextgr18t: "Aláírás.",
        stampTextgr19t: "Dátum",
        stampTextgr20t: "Ered. Inv. sz.",
        stampTextgr21t: "Aláírás és dátum",
        stampTextgr22t: "Hely. Inv. sz.",
        inserts: "Csővédők",
        poly: "Poligon",
        brush: "Kefe",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Rétegkezelő megjelenítése",
        hideLM: "Rétegkezelő elrejtése",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Névtelen",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Elrendezés exportálása elkezdődött",
        successExporting: "Exportálás sikeresen befejeződött",
        failExporting: "Nem sikerült exportálni",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Napi limit elérve</a>",
        exportingLimit: "Limit: ",
        exportingLeft: "Mai maradék: ",
        pdfExportingPopUpBlocked: "A böngészője blokkolta a felugró ablakot. Kérjük, engedélyezze a felugró ablakokat ezen az oldalon a .PDF fájl letöltéséhez",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Pop-up szál",
        tt_group_MT: "Férfi",
        tt_group_FT: "Női",
        tt_riserHeight: "Emelőcső magassága",
        tt_pressureReg: "Nyomásszabályozó",
        tt_checkValve: "(Visszacsapó szeleppel)",
        tt_home: "Kezdőlap",
        tt_prev: "Előző",
        tt_next: "Következő",
        tt_end: "Vége",
        tt_add: "Hozzáad",
        tt_clone: "Klónoz",
        tt_remove: "Eltávolít",
        tt_rename: "Átnevez",
        tt_addToFav: "Hozzáadás a kedvencekhez",
        tt_remFromFav: "Eltávolítás a kedvencekből",
        tt_presets: "Beállítások",
        tt_MagicAutoPlacer: "`Automatikus elhelyezés a vonal mentén`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "É",
        S: "D",
        E: "K",
        W: "Ny",
        //conventions
        sprinklers: "Öntözők",
        dripStarts: "Csepegtető indítása",
        rzwLayer: "Gyökérzóna öntözése",
        dripLines: "Csepegtető vonalak",
        valvesLayer: "Szelepvezérlők",
        waterSources: "Vízforrások",
        quickCoupLayer: "Gyorscsatlakozó réteg",
        controllers: "Vezérlők",
        sensorsLayer: "Érzékelők",
        mainPipes: "Főcsövek",
        lateralPipes: "Oldalcsövek",
        lateralPipes_sprinklerZone: "Zóna (Öntözők)",
        lateralPipes_dripZone: "Zóna (Csepegtető vonalak)",
        lateralPipes_rzwZone: "Zóna (Gyökérzóna öntözése)",
        lateralPipes_emptyZone: "Zóna (Nincs fogyasztó)",
        trenchesLayer: "Árkok",
        insetsLayer: "Betétek",
        wiresLayer: "Kábelezés",
        wirelessLayer: "Vezeték nélküli kapcsolat",
        senswirelessLayer: "Vezeték nélküli érzékelő kapcsolat",
        senswiresLayer: "Érzékelők kábelezése",
        surfaces: "Felületek",
        ldItemsLayer: "Növények",
        covers: "Fedett területek",
        nameplates: "Fogyasztói információs táblák",
        oreolas: "Fogyasztói jelek",
        pipeInfo: "Csőinformációk",
        lines: "Vonalak",
        overlays: "Rétegek",
        stampLayer: "Bélyegző réteg",
        stampTexts: "Bélyegző szövegek",
        //zonesTable
        zoneType: "Zóna típusa",
        color: "Szín",
        consumers: "Fogyasztók",
        waterFlow: "Vízáramlás",
        sprinklerZone: "Öntöző zóna",
        dripZone: "Csepegtető zóna",
        rzwZone: "Gyökérzóna öntözése",
        emptyZone: "Üres zóna",
        specifyDiagonal: "Kérem, adja meg a monitor átlóját inch-ben",
        //sprinklersTable
        consType: "Típus",
        consName: "Név",
        zoneNum: "Zóna",
        sector: "Szektor",
        radius: "Sugár",
        reducedBy: "Csökkentve",
        nozzle: "Fúvóka",
        rotor: "Rotor",
        bubbler: "Buborékos",
        bubblerNozzle: "Buborékos fúvóka",
        //dripsTable
        catId: "Kat. ID",
        brand: "Márka",
        emitterStep: "Lépés",
        emitterFlow: "Áramlás",
        //layersManangerSpecific
        consumersGrp: "Fogyasztói csoport",
        nodesGrp: "Csomópontok",
        wiresGrp: "Vezetékek",
        pipesGrp: "Csövek",
        landscapeGrp: "Táj",
        allTogether: "Mind együtt"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Típus",
        brand: "Márka",
        catid: "Kat. ID",
        title: "Cím",
        units: "Egységek",
        amount: "Mennyiség",
        //predetermined
        dripLine: "Csepegtető vonal",
        dl16: "16/13mm csepegtető vonal",
        dl17: "17mm csepegtető vonal",
        dripStart: "Csepegtetés kezdete",
        ds16: "16/13mm csepegtetés kezdete",
        ds17: "17mm csepegtetés kezdete",
        manifold_no_lps_issue: "Nincsenek csatlakoztatott zónák",
        manifold_no_mp_issue: "Nem csatlakozik a fővezetékhez",
        manifold_no_wr_issue: "Nincs csatlakoztatott vezérlőkábel",
        //nodes-----------------------------------
        sprinkler_unattached: "FIGYELEM!!! Vannak csatlakoztatatlan SZÓRÓFEJEK (nem lesznek bemutatva a végső specifikációban)",
        drip_unattached: "FIGYELEM!!! Vannak csatlakoztatatlan CSÖPÖGTETŐ ÖNTÖZŐ ELEMEK (nem lesznek bemutatva a végső specifikációban)",
        mains_unattached: "FIGYELEM!!! Vannak csatlakoztatatlan FŐVEZETÉKEK (nem lesznek bemutatva a végső specifikációban)",
        mains_empty: "FIGYELEM!!! Vannak FŐVEZETÉKEK fogyasztók nélkül (nem lesznek bemutatva a végső specifikációban)",
        laterals_unattached: "FIGYELEM!!! Vannak csatlakoztatatlan OLDALCSÖVEK (nem lesznek bemutatva a végső specifikációban)",
        laterals_empty: "FIGYELEM!!! Vannak OLDALCSÖVEK fogyasztók nélkül (nem lesznek bemutatva a végső specifikációban)",
        rzw_unattached: "FIGYELEM!!! Vannak csatlakoztatatlan GYÖKÉRZÓNÁT ÖNTÖZŐ ELEMEK (nem lesznek bemutatva a végső specifikációban)",
        sensors_unattached: "FIGYELEM!!! Vannak csatlakoztatatlan ÉRZÉKELŐK (nem lesznek bemutatva a végső specifikációban)",
        manifolds_unfinished: "FIGYELEM!!! Vannak befejezetlen ELOSZTÓK (nem lehet befejezni a szelepek konfigurációját)",
        control_wires_unattached: "FIGYELEM!!! Vannak csatlakoztatatlan VEZÉRLŐKÁBELEK",
        control_wires_empty: "FIGYELEM!!! VEZÉRLŐKÁBELEK vannak szelepek nélkül",
        cntr_wr_unattached: "Vezérlőkábel",
        youCanSeeThemInTheDrawing: "Minden elemet megtekinthet a rajzon, a sor bal oldalán lévő 'szem' ikonra kattintva",
        sprinkler_nozzleMT: "Szórófej csatlakozó (Női menetes fúvóka)",
        sprinkler_nozzleFT: "Szórófej csatlakozó (Férfi menetes fúvóka)",
        "sprinkler_rotor1/2F": "Szórófej csatlakozó (Rotor) 1/2\" női",
        "sprinkler_rotor3/4F": "Szórófej csatlakozó (Rotor) 3/4\"",
        "sprinkler_rotor1F": "Szórófej csatlakozó (Rotor) 1\"",
        "sprinkler_rotor11/4F": "Öntöző csomópont (Rotor) 1 1/4\"",
        "sprinkler_rotor11/2F": "Öntöző csomópont (Rotor) 1 1/2\"",
        "sprinkler_rotor2F": "Öntöző csomópont (Rotor) 2\"",
        "sprinkler_rotor1/2M": "Szórófej csatlakozó (Rotor) 1/2\" férfi",
        "sprinkler_rotor3/4M": "Sprinkler node (Rotor) 3/4\" male",
        "sprinkler_bubbler1/2F": "Zraszacz csomópont (Buborékos)",
        "sprinkler_bubblerNozzleMT": "Zraszacz csomópont (Buborékos fúvóka női menettel)",
        "sprinkler_bubblerNozzleFT": "Zraszacz csomópont (Buborékos fúvóka férfi menettel)",
        "dripIrrigation16": "Csepegtető öntözés (16/13mm)",
        "dripIrrigation17": "Csepegtető öntözés (17mm)",
        "rootZoneWatering": "Gyökérzóna öntözőrendszer",
        "manifold": "Szelep elosztócsomópont",
        "automation": "Automatizálás csomópont",
        "mainPipes_hdpePE80SDR11": "Fő HDPE csövek SDR 11",
        "mainPipes_hdpePE80SDR136": "Fő HDPE csövek SDR 13.6",
        "mainPipes_hdpePE80SDR176": "Fő HDPE csövek SDR 17.6",
        "lateralPipes_hdpePE80SDR11": "Mellék HDPE csövek SDR 11",
        "lateralPipes_hdpePE80SDR136": "Mellék HDPE csövek SDR 13.6",
        "lateralPipes_hdpePE80SDR176": "Mellék HDPE csövek SDR 17.6",
        "mainPipes_hdpeSDR9": "Fő HDPE csövek SDR 9",
        "mainPipes_hdpeSDR11": "Fő HDPE csövek SDR 11",
        "mainPipes_hdpeSDR136": "Fő HDPE csövek SDR 13.6",
        "mainPipes_hdpeSDR17": "Fő HDPE csövek SDR 17",
        "mainPipes_hdpeSDR176": "Fő HDPE csövek SDR 17.6",
        "lateralPipes_hdpeSDR9": "Mellék HDPE csövek SDR 9",
        "lateralPipes_hdpeSDR11": "Mellék HDPE csövek SDR 11",
        "lateralPipes_hdpeSDR136": "Mellék HDPE csövek SDR 13.6",
        "lateralPipes_hdpeSDR17": "Mellék HDPE csövek SDR 17",
        "lateralPipes_hdpeSDR176": "Mellék HDPE csövek SDR 17.6",
        "mainPipes_pvcSCH40": "Fő PVC csövek SCH40",
        "mainPipes_pvcSCH80": "Fő PVC csövek SCH80",
        "mainPipes_pvcCL315": "Fő PVC csövek OSZTÁLY 315",
        "mainPipes_pvcCL200": "Fő PVC csövek OSZTÁLY 200",
        "mainPipes_pvcCL160": "Fő PVC csövek OSZTÁLY 160",
        "mainPipes_pvcCL125": "Fő PVC csövek OSZTÁLY 125",
        "mainPipes_pvcUSCJPN18": "Fő PVC-U SCJ csövek (PN18)",
        "mainPipes_pvcUSCJPN12": "Fő PVC-U SCJ csövek (PN12)",
        "mainPipes_pvcUSCJPN9": "Fő PVC-U SCJ csövek (PN9)",
        "mainPipes_pvcUSCJPN6": "Fő PVC-U SCJ csövek (PN6)",
        "mainPipes_pvcUSCJPN45": "Fő PVC-U SCJ csövek (PN4.5)",
        "mainPipes_ldpeCLASS3": "Fő LDPE csövek OSZTÁLY 3",
        "lateralPipes_pvcSCH40": "Mellék PVC csövek SCH40",
        lateralPipes_pvcSCH80: "Oldalcsövek PVC SCH80",
        lateralPipes_pvcCL315: "Oldalcsövek PVC OSZTÁLY 315",
        lateralPipes_pvcCL200: "Oldalcsövek PVC OSZTÁLY 200",
        lateralPipes_pvcCL160: "Oldalcsövek PVC OSZTÁLY 160",
        lateralPipes_pvcCL125: "Oldalcsövek PVC OSZTÁLY 125",
        lateralPipes_pvcUSCJPN18: "Oldalcsövek PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Oldalcsövek PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Oldalcsövek PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Oldalcsövek PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Oldalcsövek PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Oldalcsövek LDPE OSZTÁLY 3",
        wiring: "Kábelezés",
        qcv: "Gyorscsatlakozó szelepek",
        fixedCntr: "rögzített",
        stand_aloneCntr: "önálló",
        modularCntr: "moduláris",
        decoderCntr: "dekóder",
        inset: "Csővédő",
        insets: "Csővédők",
        //-----------------------------------------
        novar: "nincs változat",
        choosevar: "válassz változatot",
        //element.types----------------------------
        nozzle: "Fúvóka",
        rotor: "Rotor",
        rotorNozzle: "Rotorfúvóka",
        bubbler: "Buborékoló",
        bubblerNozzle: "Buborékoló fúvóka",
        rzw: "Gyökérzóna öntözőrendszer",
        sprayBody: "Permetezőtest",
        sprinklerStandAssembly: "Szórófej állvány (emelő)",
        outBarb: "Fúvókához való vég",
        flexPipe: "Rugalmas cső",
        sj: "Csuklós kapcsolat",
        inBarb: "Csőhöz való vég",
        midSprinkPipeFitting: "Középső csőfitting",
        endSprinkPipeFitting: "Cső vége fitting",
        midRZWPipeFitting: "Középső csőfitting",
        endRZWPipeFitting: "Cső vége fitting",
        dripPipe: "Csepegtető cső",
        blindPipe: "Vakcső",
        dripTeeFitting: "Csepegtető T-idom",
        dripCapFitting: "Csepegtető záróelem",
        dripCouplingFitting: "Csepegtető összekötő",
        dripElbowFitting: "Csepegtető könyök",
        dripSpike: "Csepegtető tüske",
        sprinklerZoneValve: "Szórófejzóna szelep",
        emptyZoneValve: "Szelep áramkör nélkül",
        valveOutFitting: "Szelep kimeneti fitting",
        dripZoneValve: "Csepegtető zóna szelep",
        rzwZoneValve: "Gyökérzóna öntözés szelep",
        pressureReg: "Nyomásszabályozó",
        filter_pressureReg: "Szűrő nyomásszabályozóval",
        controller: "Vezérlő",
        flowMeter: "Áramlásmérő",
        rainSensor: "Esőérzékelő",
        soilSensor: "Talajnedvesség érzékelő",
        freezeSensor: "Fagyérzékelő",
        wrFreezeSensor: "Vezeték nélküli eső-/fagyérzékelő",
        windSensor: "Szélérzékelő",
        solarSensor: "Napfényérzékelő",
        flowSensor: "Átfolyásérzékelő",
        weatherStation: "Időjárás állomás",
        solarPanel: "Napelem",
        mainPipe: "Főcső",
        teeFitting: "T-idom",
        elbowFitting: "Könyök",
        reducerFitting: "Redukció",
        lateralPipe: "Oldalcső",
        capFitting: "Lezáró",
        basicCable: "Alap kábel",
        basicWire: "Alap vezeték",
        sensorCable: "Időjárás érzékelő kábel",
        qcPlastic: "Q/C műanyag szelep",
        qcMetal: "Q/C fémszelep",
        gateway: "Átjáró",
        antExt: "Antenna meghosszabbító",
        loramod: "LoRa modulok",
        //typesOfAcessories
        hdpeCOR: "Hullámos HDPE cső",
        expModule: "Bővítő modul",
        rzwSleeve: "Szövet hüvely",
        rwCap: "Újrahasznosított víz zárókupak",
        gutterMount: "Ereszcsatorna szerelvény",
        delayRelay: "Késleltető relé",
        fctFlow: "FCT bekötő T-idom",
        fctBspAdap: "FCT BSP adapter",
        drainCheckValve: "Visszacsapó szelep",
        rwId: "Újrahasznosított víz azonosító",
        vpc: "Vandálbiztos zárókupak",
        inletFilter: "Bemeneti szűrő",
        wifiModule: "Wi-Fi modul",
        wallMount: "Fali szerelvény",
        rwsSock: "Szövet hüvely",
        rwsGrate: "RWS rács",
        npCover: "Ivóvíz elleni védőfedél",
        sprExt: "Szórófej meghosszabbító",
        popUpToThread: "Szórófej adapter",
        valveBox: "Zawor doboz",
        valveBoxExt: "Szelepdoboz meghosszabbítás",
        qcPlasticKey: "Q/C műanyag kulcs",
        qcPlasticElbFit: "Kolanko",
        qcMetalKey: "Q/C fémszelep kulcs",
        qcMetalElbFit: "Kolanko",
        qcMetalCapKey: "Fém fedél kulcs",
        insTape: "Szigetelőszalag",
        wrConn: "Csatlakozó",
        shrinkTube: "Hőre zsugorodó cső",
        hcFrontPanel: "Első panel",
        ball_valve: "Golyós szelep",
        check_valve: "Ellenőrző szelep",
        thread_manifold: "Menetes elosztó",
        plastic_filter: "Szűrő (műanyag)",
        waterMeter: "Vízmérő",
        rfModule: "Rádiós modul",
        largeAntenna: "Nagy antenna",
        wifiHub: "Wi-Fi hub",
        handRemoteKit: "Kézi távirányító készlet",
        handRemote: "Kézi távirányító",
        wifiBundleKit: "Wi-Fi csomag",
        //typesOfFittings
        //drip
        barb_cap_8: "Csepegtető vonal vége",
        barb_elbow_PP: "Zaciskos könyök",
        barb_elbow_PT: "Menetes zaciskos könyök",
        barb_tee_PPP: "Zaciskos T-idom",
        barb_coupling_PP: "Zaciskos csatlakozó",
        barb_cross_PPPP: "Zaciskos kereszt",
        barb_cap_P: "Zaciskos végzáró",
        barb_coupling_PT: "Menetes zaciskos csatlakozó",
        barb_tee_PTP: "Menetes zaciskos T-idom",
        barb_valve_PT: "Menetes zaciskos szelep",
        barb_valve_PP: "Zaciskos szelep",
        twlc_elbow_PP: "Twist-lock könyök",
        twlc_tee_PPP: "Twist-lock T-idom",
        twlc_coupling_PP: "Twist-lock csatlakozó",
        twlc_cross_PPPP: "Twist-lock kereszt",
        twlc_cap_P: "Twist-lock végzáró",
        twlc_coupling_PT: "Menetes twist-lock csatlakozó",
        twlc_tee_PTP: "Menetes twist-lock T-idom",
        twlc_valve_PT: "Menetes twist-lock szelep",
        twlc_valve_PP: "Twist-lock szelep",
        dl_valves: "Speciális szelepek",
//pipe
        hdpeSDR9: "HDPE SDR 9 cső",
        hdpeSDR11: "HDPE SDR 11 cső",
        hdpeSDR136: "HDPE SDR 13.6 cső",
        hdpeSDR17: "HDPE SDR 17 cső",
        hdpeSDR176: "HDPE SDR 17.6 cső",
        ldpeSDR9: "LDPE SDR 9 cső",
        ldpeSDR11: "LDPE SDR 11 cső",
        ldpeSDR136: "LDPE SDR 13.6 cső",
        ldpeSDR17: "LDPE SDR 17 cső",
        pvcSCH40: "PVC SCH40 cső",
        pvcSCH80: "PVC SCH80 cső",
        pvcCL315: "PVC CLASS 315 cső",
        pvcCL200: "PVC CLASS 200 cső",
        pvcCL160: "PVC CLASS 160 cső",
        pvcCL125: "PVC CLASS 125 cső",
        pvcUSCJPN18: "PVC-U SCJ (PN18) cső",
        pvcUSCJPN12: "PVC-U SCJ (PN12) cső",
        pvcUSCJPN9: "PVC-U SCJ (PN9) cső",
        pvcUSCJPN6: "PVC-U SCJ (PN6) cső",
        pvcUSCJPN45: "PVC-U SCJ (PN4.5) cső",
        ldpeCLASS3: "LDPE CLASS 3 cső",
        compress_elbow_PT: "Menetes kompressziós könyök",
        compress_coupling_PT: "Menetes kompressziós csatlakozó",
        compress_tee_PTP: "Menetes kompressziós T-idom",
        compress_cap_P: "Kompressziós végzáró",
        compress_elbow_PP: "Kompressziós könyök",
        compress_coupling_PP: "Kompressziós csatlakozó",
        compress_tee_PPP: "Kompressziós T-idom",
        compress_cross_PPPP: "Kompressziós kereszt",
        compress_single_clamp_saddle: "Egybilincses kompressziós nyereg",
        compress_ballvalve_PP: "Kompressziós labdacsap",
        compress_ballvalve_PT: "Menetes kompressziós labdacsap",
        customfit_elbow_PT: "Menetes egyedi könyök",
        customfit_coupling_PT: "Menetes egyedi csatlakozó",
        customfit_tee_PTP: "Menetes egyedi T-idom",
        customfit_cap_P: "Egyedi végzáró",
        customfit_elbow_PP: "Egyedi könyök",
        customfit_coupling_PP: "Egyedi csatlakozó",
        customfit_tee_PPP: "Egyedi T-idom",
        customfit_cross_PPPP: "Egyedi kereszt",
        customfit_single_clamp_saddle: "Egyedi egybilincses nyereg",
        customfit_ballvalve_PP: "Egyedi labdacsap",
        customfit_ballvalve_PT: "Menetes egyedi labdacsap",
        thread_nipple: "Menetes szopóka",
        thread_coupling: "Menetes kötőelem",
        thread_mf_reducer: "Menetes férfi-női redukció",
        thread_mf_adapter: "Menetes férfi-női adapter",
        thread_mf_bush: "Menetes férfi-női boksz",
        thread_tee: "Menetes T-idom",
        thread_elbow: "Menetes könyök",
        thread_mf_elbow: "Menetes férfi-női könyök",
        thread_cap: "Menetes végzáró",
        thread_plug: "Menetes dugó",
        thread_union_nut: "Menetes unió anya",
        thread_cross: "Menetes kereszt",
        cable: "Kábel",
        wire: "Vezeték",
// slip
        slip_single_clamp_saddle: "Egybilincses csatlakozó (PVC csőre)",
        slip_elbow_PT: "Menetes átmenetes könyök",
        slip_coupling_PT: "Menetes átmenetes kötőelem",
        slip_tee_PTP: "Menetes átmenetes T-idom",
        slip_cap_P: "Csúszó végzáró",
        slip_elbow_PP: "Csúszó könyök",
        slip_coupling_PP: "Csúszó kötőelem",
        slip_tee_PPP: "Csúszó T-idom",
        slip_cross_PPPP: "Csúszó kereszt",
        slip_ballvalve_PP: "Csúszó labdacsap",
        slip_ballvalve_PT: "Menetes csúszó labdacsap",
//extendables
        arbitraryFittings: "Tetszőleges csatlakozók",
        dripStartAssembly: "Csepegtető rendszer kezdő összeállítása",
        intakeAssembly: "Beömlő összeállítás",
        offtakeAssembly: "Elágazás összeállítása",
        numofvalves: "Szelepek száma: ",
        numofvalvesshort: "Szelepek: ",
        numofmanifs: "Elosztók száma: ",
        intakePipeSize: "Beömlő cső mérete: ",
        valveBoxes: "Szelep dobozok",
        valveAccessories: "Szelep kiegészítők",
        oneValveAccessories: "Egy szelep kiegészítői",
        controllerAccessories: "Vezérlő kiegészítők",
        sensorAccessories: "Szenzor kiegészítők",
        sprBodyAccessories: "Permetező test kiegészítők",
        rzwAccessories: "Gyökérzóna öntözés kiegészítői",
        pipeStartFittings: "Tetszőleges csatlakozók a főcsőhöz",
        qcAccessories: "Q/C szelep kiegészítők",
        wiringAccessories: "Kábel kiegészítők",
        pipeSize: "Cső méret: ",
        endOfPipe: "(A cső vége)",
        midOfPipe: "(A cső közepén)",
        emptyRender: [
            "Sajnáljuk... egyetlen tartalom sem lett feldolgozva",
            "Egyetlen öntözőrendszer elemet sem fejeztél be teljesen a megjelenítéshez"
        ],
        serviceFail: [
            "Sajnáljuk... a specifikációs renderelési szolgáltatás jelenleg nem érhető el",
            "Próbálja újra később, amikor a kapcsolat helyreáll",
            "Vegye figyelembe, hogy a korábban végrehajtott konfiguráció mentésre kerül"
        ],
        serviceTrialExpired: [
            "Sajnáljuk... a specifikációs renderelési szolgáltatás nem érhető el a fiókjához",
            "Ez azt jelenti, hogy próbaidőszaka lejárt, és ha szeretné tovább használni ezt a szolgáltatást",
            "<a href='/account/subscription'>Frissítheti fiókját PRO fiókká</a>"
        ],
        serviceLimitReached: [
            "Elérte a napi limitet a specifikációs lapok renderelésében",
            "A napi specifikáció renderelések számának korlátozásának eltávolítása érdekében",
            "<a href='/account/subscription'>Frissítheti fiókját PRO fiókká</a>"
        ],
        findInDrawing: "Megjelenítés a vásznon",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Csövezés",
        labours_group_fittings: "Fittings",
        labours_group_valveBoxes: "Szelepdobozok",
        labours_group_wires: "Kábelezés",
        labours_group_sprinklers: "Szórófejek",
        labours_group_rws: "Gyökérzóna öntözés",
        labours_group_sprinklerConnections: "Szórófej csatlakozások",
        labours_group_drip: "Csepegtető vonalak és fittings",
        labours_group_manifolds: "Elosztók",
        labours_group_quickCoupling: "Gyorscsatlakozók",
        labours_group_controllers: "Vezérlők",
        labours_group_sensors: "Érzékelők",
        labours_group_trenches: "Árkok",
        labours_group_insets: "Csővédők",
        labours_group_lawns: "Gyep",
        labours_group_irrigatedArea: "Öntözött terület",
        labours_group_arbitrary_sp: "💦 Egyedi öntözési elemek",
        labours_group_arbitrary_ld: "🌳 Egyedi tájképi elemek",
        ldArbitrary_equip: "Felszerelés",
        ldArbitrary_labour: "Munkaerő",
        spArbitrary_equip: "Felszerelés",
        spArbitrary_labour: "Munkaerő",
        arbitrary_sp: '💦 Egyedi öntözési elemek',
        arbitrary_ld: '🌳 Custom Landscape elements',
        ldLine_labour: "Vonal",
        ldLine_equip: "Vonal",
        spLine_labour: "Vonal",
        spLine_equip: "Vonal",
        ldLineWithArea_labour: "Vonal (m2)",
        ldLineWithArea_equip: "Vonal (m2)",
        spLineWithArea_labour: "Vonal (m2)",
        spLineWithArea_equip: "Vonal (m2)",
        ldVolumetricLine_labour: "Vonal (m3)",
        ldVolumetricLine_equip: "Vonal (m3)",
        spVolumetricLine_labour: "Vonal (m3)",
        spVolumetricLine_equip: "Vonal (m3)",
        polyLdSurface_labour: "Felület",
        brushLdSurface_labour: "Felület",
        polyLdSurface_equip: "Felület",
        brushLdSurface_equip: "Felület",
        polySpSurface_labour: "Felület",
        brushSpSurface_labour: "Felület",
        polySpSurface_equip: "Felület",
        brushSpSurface_equip: "Felület",
        polyLdVolumetricSurface_labour: "Felület (m3)",
        brushLdVolumetricSurface_labour: "Felület (m3)",
        polyLdVolumetricSurface_equip: "Felület (m3)",
        brushLdVolumetricSurface_equip: "Felület (m3)",
        polySpVolumetricSurface_labour: "Felület (m3)",
        brushSpVolumetricSurface_labour: "Felület (m3)",
        polySpVolumetricSurface_equip: "Felület (m3)",
        brushSpVolumetricSurface_equip: "Felület (m3)",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "Január", "Február", "Március", "Április", "Május", "Június", "Július", "Augusztus", "Szeptember", "Október", "November", "December"],
        MMM: ["\x01", "Jan", "Feb", "Már", "Ápr", "Máj", "Jún", "Júl", "Aug", "Szep", "Okt", "Nov", "Dec"],
        dddd: ["\x02", "Vasárnap", "Hétfő", "Kedd", "Szerda", "Csütörtök", "Péntek", "Szombat"],
        ddd: ["\x03", "Vas", "Hét", "Ked", "Sze", "Csü", "Pén", "Szo"],
        //buttonsCaps
        ok: "Ok",
        save: "Mentés",
        apply: "Alkalmaz",
        defaults: "Alapértelmezettek",
        retry: "Újrapróbál",
        finish: "Befejez",
        safeRestart: "Biztonságos újraindítás",
        saveAndExit: "Mentés és Kilépés",
        exit: "Kilépés",
        cancel: "Mégse",
        rename: "Átnevez",
        idk: "Nem tudom",
        getFile: "Fájl lekérése",
        reset: "Visszaállítás",
        random: "Véletlen",
        //misc
        zoneNum: "Zóna #",
        valveNum: "Szelepdoboz #",
        zonesColoring: "Zónák reprezentációja",
        coversColoured: "Szórófej fedelek színezése",
        dripsColoring: "Csepegtető vonalak színezése",
        dripsSameAsZonesColored: "Csepegtető vonalak színezése a zónájuk színe szerint",
        //saveOflline
        saveOffline: [
            "Sajnáljuk... a kapcsolat megszakadt",
            "De ne aggódj, folytathatod a projektet offline módban.",
            "Amíg offline vagy - minden mentésed szövegfájlként tárolódik a böngésző letöltései mappájában.",
            "És később feltöltheted a rajz legújabb verzióját a szerverre."
        ],
        restartOffline: [
            "Sajnáljuk... a kapcsolat megszakadt",
            "De ne aggódj, a projekted helyileg mentésre került a számítógépeden.",
            "Megtalálhatod a böngésző letöltései mappájában.",
            "Ha offline módban szeretnél dolgozni, letölthetsz egy Offline példányt az alkalmazásból a fiókodból a http://www.irrisketch.com címen"
        ],
        brokenSaving: [
            "Sajnáljuk... valami hiba történt a projekt betöltése közben",
            "Úgy tűnik, hogy az előző mentés sérült valahogy.",
            "De ne aggódjon, meg tudjuk javítani.",
            "A projektje most 'Sérült' jelöléssel lesz ellátva a műhelyében.",
            "És a technikai személyzetünk mihamarabb kezeli ezt a helyzetet."
        ],
        corruptedSavingFile: [
            "Sajnáljuk... a betölteni próbált fájl nem olvasható",
            "De ne aggódjon, meg tudjuk javítani.",
            "Csak be kell nyújtania ezt a sérült fájlt a műhelyében található fájlbetöltő űrlapon.",
            "És aztán megpróbáljuk újra működésbe hozni."
        ],
        ajaxReqFail: [
            "Sajnáljuk... elveszítettük a kapcsolatot a szerverrel",
            "Jelenleg lehetetlen adatokat küldeni/fogadni",
            "Kérjük, próbálja meg később újra"
        ],
        critical: [
            "Sajnáljuk... valami hiba történt",
            "De ne aggódjon, a rajza biztonságban van most, csak kattintson a biztonságos újraindítás gombra a folytatáshoz..."
        ],
        fatal: [
            "Sajnáljuk... valami hiba történt",
            "Segítsen nekünk, hogy szolgáltatásunkat jobbá tegyük. Írja le, hogy milyen felhasználói lépések után történt ez a hiba",
            "Itt szolgáltasson információt"
        ],
        areYouSure: [
            "Biztosan bezárja ezt a projektet",
            "Vegye figyelembe, hogy az összes mentetlen változás elveszik."
        ],
        pickAnotherCSVFile: "Válasszon másikat",
        csvFileTooBig: [
            "A maximális CSV fájlméret túllépve",
            "Optimalizálási célokból a maximális CSV fájlkezelés 4 MB-ra van korlátozva"
        ],
        notAnCSV: [
            "Sajnáljuk, ez a fájltípus nem támogatott",
            "Támogatott formátumok: .csv"
        ],
        invalidCSV: [
            "Érvénytelen CSV fájl tartalom",
            "Moasure alkalmazás exportálási fájl elemzési hiba, kérjük ellenőrizze, hogy a fájl megfelelően lett-e exportálva"
        ],
        pickAnotherImage: "Válasszon másikat",
        imageTooBig: [
            "A maximális képméret túllépve",
            "Optimalizálási célokból a maximális képfeldolgozás 10 MB-ra van korlátozva"
        ],
        notAnImage: [
            "Sajnáljuk, ez a fájltípus nem támogatott",
            "Támogatott képformátumok: .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "Művelet KORLÁTOZOTT",
            "Ez a művelet nem engedélyezett a SZABAD előfizetéshez"
        ],
        goPro: 'PROFI LETT',
        renameLayout: "Adja meg az új nevet",
        areYouSureDeleteLayout: [
            "Figyelem! Ez a művelet nem vonható vissza",
            "Biztosan törli: ",
            "Törlés"
        ],
        setUnderlaySize: [
            "Állítsa be a vonal hosszát, amelyet éppen húzott",
            "Helytelen értéket adott meg. Kérem, próbálja újra"
        ],
        setMonitorDiagonal: [
            "Kérjük, adjon nekünk információt a monitor átlós méretéről",
            "Helytelen értéket adott meg. Kérem, próbálja újra"
        ],
        getSpecsTable: [
            "Állítson be specifikációs kimeneti beállításokat",
            "Csoportosítsa az eszközöket",
            "Csomópont", "Márka",
            "Állítsa be a fájltípust",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Adja meg a címet",
            "Kép #",
            "Mentés",
            "Specifikációk mentése",
            "Befejezve. Kattintson ide az megnyitáshoz",
            "Mentés sikertelen",
            "Létező elrendezések frissítése",
            "Frissítés",
            "Elrendezések frissítése"
        ],
        exportLayoutsAsPdf: [
            "Válassza ki a kimentendő elrendezéseket",
            "külön fájlok (fejlesztés alatt)",
            "egy album",
            "Exportálás",
            "Elrendezések exportálása mint"
        ],
        differentSprGroups: [
            "Nem sikerült különböző típusú vízfogyasztókat csatlakoztatni ehhez a csőhöz",
            "Az öntözési tervezési szabványok szerint nem elfogadható különböző típusú vízfogyasztókat vagy szórófejeket különböző csapadék aránnyal ugyanazon a zónán belül keverni"
        ],
        tooFarAwaySpr: [
            "Nem sikerült csatlakoztatni a fogyasztókat",
            "Néhány fogyasztó túl messze van a laterális csőtől, hogy csatlakoztatható legyen. A kapcsolat maximális távolságát a preferenciák menüben állíthatja be"
        ],
        outlayerConfig: [
            "Specifikációs lap konfiguráció"
        ],
        presetsMenu: {
            title: "Előre beállítások",
            titleTextboxLabel: "Előre beállítás címe",
            descriptionTextboxLabel: "Leírás",
            applyButton: "<i class='far fa-check-circle'></i>&nbsp;Alkalmaz",
            defaultButton: "<i class='far fa-undo'></i>&nbsp;Alapértelmezett beállítások",
            removeButton: "<i class='far fa-trash'></i>&nbsp;Törlés",
            updateButton: "<i class='far fa-sync'></i>&nbsp;Frissítés",
            createButton: "<i class='far fa-plus'></i>&nbsp;Új létrehozása",
            closeButton: "<i class='far fa-times'></i>&nbsp;Bezárás",
            favorites_drawing: "Kedvenc eszközök (Táj)",
            favorites_sprinkling: "Kedvenc eszközök (Öntözés)",
            favorites_layouting: "Kedvenc eszközök (Elrendezések)",
            configs_drawing: "Projekt konfiguráció",
            configs_outlayer: "Specifikációs lap konfiguráció",
        },
        newPresetItem: "Új előre beállítás",
        cL_alreadyConnected: [
            "Sikertelen vonalak összekapcsolása",
            "Ezek a vonalak mindkettő kapcsolatban áll"
        ],
        cL_segOnElem: [
            "Sikertelen vonalak összekapcsolása",
            "Nem csatlakoztathat olyan szakaszt, amelyen"
        ],
        cL_strangeError: [
            "Sikertelen vonalak összekapcsolása",
            "Sajnáljuk... A kapcsolat nem sikerült"
        ],
        cL_misgrouping: [
            "Sikertelen vonalak összekapcsolása",
            "Ezek a vonalak olyan fogyasztókkal rendelkeznek, amelyeket nem ajánlott ugyanarra a zónára helyezni. Ha mégis össze szeretné őket kötni, kapcsolja be az 'Biztonságtalan mód' beállítást a Szórófejek csoportosítása menüpontban a projekt konfigurációban"
        ],
        cL_valve: "Szelepek összegzője",
        cL_waterSource: "Vízforrás",
        cL_dripStart: "Csepegtetés indítása",
        cL_controller: "Irányító",
        cL_sensors: "Érzékelő",
        cL_valves: "Szelepek összegzője",
        cL_notSameVariant: [
            "Sikertelen vonalak összekapcsolása",
            "Ezek a vonalak különböző típusúak",
            "Jelenlegi vonal típusa",
            "Vonal típusa, amelyet csatlakoztatni szeretne"
        ],
        hasRestorableProject: [
            "Van mentetlen adat a projektben",
            "Visszaállíthatja a mentett állapotot a következő pillanatképből",
        ],
        restoreProject: "Visszaállítás",
        imageLost: [
            "Sajnáljuk, nem találjuk néhány alap képet a szerveren",
            "Ez a kép nem található:"
        ],
        precipCalcError_mixedError: [
            'Csapadéktérkép hiba',
            'Nem sikerült létrehozni a csapadéktérképeket az öntözőfejek kombinációjához:',
        ],
        precipCalcError_mprNonMprRot: 'Nem lehet keverni a normál rotorokat és az MPR fúvókákkal rendelkező rotorokat',
        precipCalcError_mprNozNonMprRot: 'Nem lehet keverni az MPR fúvókákat és a normál rotorokat',
        precipCalcError_staticNozRot: 'Nem lehet keverni a statikus fúvókákat a rotorokkal',
        precipCalcError_staticMprNoz: 'Nem lehet keverni a statikus fúvókákat az MPR fúvókákkal',
        precipCalcError_missingError: [
            'Csapadéktérkép hiba',
            'Hiányzó csapadékprofilok az öntözőfejekhez:',
        ],
        precipCalcError_zoningError: [
            'Csapadéktérkép zónázási hiba',
            'Nem sikerült létrehozni a csapadéktérképeket az öntözőfejek kombinációjához:',
        ],
        precipCalcError_noZoneAndZone: 'Nem lehet egyszerre kiszámítani a csapadékot a csatlakoztatott és nem csatlakoztatott rotorokhoz. Az üzemidő ismeretlen, ezért a rotorok fordulatszáma bizonytalan',
        algoNozzler_noSolutions: [
            'Nem található lehetséges megoldás a szórófejek elhelyezésére',
            'Próbálja meg a következőket:',
            '1. Módosítsa az átfedési korlátozásokat és egyéb beállításokat az automatikus elhelyezési eszköz konfigurációs menüjében',
            '2. Válasszon más típusú szórófejeket, mivel ezek nagyobb rugalmasságot nyújthatnak az elhelyezésben',
            '3. Használja az alábbi gombot a megoldás újraindításához "lazább" átfedési és lefedési korlátozásokkal'
        ],
        retryWithLooseOptions: "Újrapróbálkozás 'lazább' opciókkal",
        cannotSaveBecauseOffline: [
            "Nem sikerült a kérés küldése a szerverhez",
            "Nincs kapcsolat a szerverrel",
            "Ellenőrizze, hogy van-e internetkapcsolat",
            "Annak érdekében, hogy ne veszítsen adatokat, ne zárja be ezt az ablakot, és próbálja meg később újra menteni az adatokat, amikor a kapcsolat a szerverrel létrejön",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Nem sikerült a mentési kérés",
            "Túl sok érvénytelen kód kísérlet",
            "Ellenőrizze, hogy helyesen adta-e meg az e-mail címet, majd próbálkozzon újra 30 másodperc múlva.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Nem sikerült a mentési kérés",
            "Rosszul megadott e-mail cím",
            "Ellenőrizze, hogy helyesen adta-e meg az e-mail címet, majd próbálkozzon újra",
            "",
            "",
        ],
        designRequestCompleted: [
            "A kérés sikeresen létrehozva/frissítve",
            "Szerkesztési link", "másolás",
            "Megtekintési link", "másolás",
        ],
        designRequestContacts: [
            "Kapcsolattartási információk",
            "Szervezet",
            "Név",
            "E-mail",
            "Telefonszám",
            "Cím",
            "Weboldal",
        ],
        designRequestInfo: [
            "Üdvözöljük a Design Stúdióban!",
            "Itt könnyen és gyorsan létrehozhat egy kérést öntözési rendszerének tervezésére.",
            "Egy <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>útmutató videót itt talál</a>",
            "További információkért vagy ha kérdése van, ne habozzon kapcsolatba lépni velünk."
        ],
        approveActionByCode: [
            "Művelet jóváhagyása",
            "E-mailben elküldtünk egy jóváhagyási kódot a megadott e-mail címre.",
            "Kérem, adja meg ezt a kódot az alábbi mezőbe",
            "Érvénytelen számot adott meg, próbálja újra"
        ],
        revisionCheckFailedSoft: [
            'Revíziós konfliktus!',
            'Ez a projekt jelenleg egy másik böngészőben vagy eszközön van megnyitva.',
            'Felülírhatja az adatokat a szerveren (mivel csak egy verziót tárolunk a projektjéből), ha rákattint a "felülírás" gombra, de legyen óvatos - minden másik munkamenetben végzett munka elveszik!',
            'Jobb stratégia megérteni, hogy hol és ki nyitotta meg ezt a projektet, és eldönteni, melyik verzió a legfrissebb.',
            'Ha a legfrissebb verzióhoz szeretne hozzáférni ennek a párhuzamosan megnyitott projektnek, nyissa meg újra ezt a projektet, duplikálva ezt a lapot a böngészőjében.',
        ],
        revisionBlocked: [
            'Mentés blokkolva az adminisztrátor által!',
            'Jelenleg a projektet technikai személyzetünk vizsgálja azon hibák miatt, amelyek előfordultak benne.',
            'Kérjük, várjon, amíg a vizsgálat befejeződik, majd e-mailben értesítjük további utasításokkal.',
        ],
        missingVariants: [
            'Hiányzó elemek hiba',
            'Az alábbiakban látható az egyedi elemek listája, amelyek hiányoznak a projektkönyvtárból, ezért nem jeleníthetők meg:',
            'Kérjük, kapcsolja be azokat a készleteket, amelyek tartalmazzák ezeket az elemeket a projektbeállítások menüben (a Műhelyben)'
        ],
        openInOtherTab: "Nyissa meg a legfrissebbet",
        overwrite: "Felülír",
        saveToFile: "Mentés fájlba",
        filterSelection_exclude: "Kizárás a kiválasztásból",
        filterSelection_include: "Beküldés a kiválasztásba",
        filterSelectionNames: {
            sprinklers: "Fogyasztók",
            sprinklers_nozzle: "Fogyasztók - Nozzlik",
            sprinklers_rotaryNozzle: "Fogyasztók - Forgó Nozzlik",
            sprinklers_rotor: "Fogyasztók - Rotorok",
            sprinklers_bubbler: "Fogyasztók - Buborékfúvók",
            sprinklers_bubblerNozzle: "Fogyasztók - Buborékfúvó Nozzlik",
            sprinklers_pinpoint: "Fogyasztók - Pontos szórófejek",
            dripStarts: "Csepegtetők indítása",
            rzwLayer: "Gyökérzóna öntözése",
            dripLines: "Csepegtető csövek",
            valvesLayer: "Szelepek rétege",
            waterSources: "Vízforrások",
            controllers: "Irányítók",
            sensorsLayer: "Érzékelők",
            mainPipes: "Főcsövek",
            lateralPipes: "Oldalsó csövek",
            trenchesLayer: "Árkok",
            insetsLayer: "Beágyazások",
            wiresLayer: "Vezetékek",
            wirelessLayer: "Vezeték nélküli kapcsolat",
            senswirelessLayer: "Vezeték nélküli érzékelő kapcsolat",
            senswiresLayer: "Érzékelő vezetékezés",
            quickCoupLayer: "Gyors csatlakozók",
            surfaces: "Poligonok és vonalak",
            ldItemsLayer: "Tájképi elemek",
            ldArbitraryLayer: "Egyedi tájképi elemek",
            spArbitraryLayer: "Egyedi öntözési elemek",
            overlays: "Elrendezési elemek",
            stampTexts: "Bélyegzőszövegek"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Szórófej csomópont",
        fcType: "Szórófej csatlakozás típusa",
        sj: "Forgó csatlakozó",
        sprinklerStand: "Szórófej állvány (emelő)",
        flexPipeBarbs: "Hajlékony cső + bárkák",
        minFlexPipeLength: "A flexibilis cső minimális hossza csatlakozásonként",
        midSprinkPipeFitting: "Csatlakozó idom",
        endSprinkPipeFitting: "Vég-csatlakozó",
        single_clamp_saddle: "Csíptető nyereg",
        tee_PTP: "Tee az BSP menettel",
        elbow_PT: "Kanyar az BSP menettel",
        coupling_PT: "Átalakító az BSP menettel",
//MANIFOLD NODE CONFIGS
        manifoldNode: "Elágazások csomópontjai",
        valvesOutlay: "Szelepek elrendezése",
        fold: "Összecsukott",
        unfold: "Kinyitott",
        threadsNode: "Menetes csatlakozások",
        threadTypes: "Menet típusok",
//AUTOMATION NODE CONFIGS
        automationNode: "Automatizálási csomópont",
        controllerModules: "Moduláris vezérlő bővítő modulok kiválasztva:",
        controllerVoltage: "Vezérlő bemeneti feszültsége:",
        controllerVoltageV2: "Vezérlő bemeneti feszültsége:",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automatikusan (legjobb illeszkedés)",
        userModules: "Kézzel (kiegészítőként)",
//RZW NODE
        rzwNode: "Gyökérzóna öntözési csomópont",
        midRZWPipeFitting: "Csatlakozó idom",
        endRZWPipeFitting: "Vég-csatlakozó",
//DRIP node
        dripNode: "Csepegtető öntözés",
        dripConnectionType: "Csepegtető csatlakozó típusa",
        dripLengthPrecision: "Számjegyek a tűzcső hosszának tizedesjegye után",
        dripTubingAddon: "Csepegtető cső adalékanyag",
        barb: "Bárka csatlakozók",
        twistLock: "Csavarással záródó csatlakozók",
        dripSpikesStep: "Csepegtető vonal tartó tüske lépés",
        dripCrossFittingAble: "Kereszt alakú csatlakozás képes",
        pipesNode: "Csővezeték szakasz",
        hdpeConnectionType: "HDPE csatlakozó típusa",
        ldpeConnectionType: "LDPE csatlakozó típusa",
        pvcConnectionType: "PVC csatlakozó típusa",
        pipeAddon: "Cső adalék minden átmérőhöz",
        pipeLengthPrecision: "Számjegyek a csövek hosszának tizedesjegye után",
        crossFittingAble: "Kereszt alakú csatlakozás képes",
        compress: "Tömörítő csatlakozók",
        customfit: "Egyedi csatlakozók",
        slip: "Csúszós csatlakozók",
        wiringNode: "Vezetékek szakasza",
        exportNode: "Exportálási lehetőségek",
        exportNumbersPrecision: "Számjegyek a számok tizedesjegye után",
        basicWiringMethod: "Vezérlő vezetékrendszere",
        cableCoresArray: "Kábel magok szám tartomány",
        noAutoWiring: "Vezetékek hozzáadása kézzel",
        separateCableToManifold: "Külön többmagú kábel az elágazásokhoz",
        separateWireToValve: "Külön vezeték a szelepekhez + közös vezeték az elágazásokhoz",
        maxCableCores: "Maximális kábelmagok",
        verticalWiringAddon: "Függőleges adalék a vezérlő vezetékhez",
        verticalSensWiringAddon: "Függőleges adalék az érzékelő vezetékhez",
        wireAddon: "Vezeték adalék minden típushoz",
        wireLengthPrecision: "Számjegyek a vezetékek hosszának tizedesjegye után",
//DRAWER CONFIG
        drawerConfig: [
            "Projekt konfiguráció"
        ],
//SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Fogyasztók",
        pressureDefinedBy: "Az elvárt nyomás a fogyasztóknál",
        allowReduceRotors: "Engedélyezze a szórófej sugara csökkentését",
        autoconnector: "Interaktív csatlakozás a szórófejek és az oldalsó csőhálózat között",
        radio_option_yes: "Igen",
        radio_option_no: "Nem",
        extreme_rotor_reduction: "Extrém (Akár 50%) (Egyenlőtlen csapadékmennyiséget okozhat)",
        radio_option_yes2: "Igen",
        takeReductionInAccountWhenAutoPlacing: "Csökkentett dobótávolságok figyelembe vétele szórófejek automatikus elhelyezésekor",
        takeReductionInAccountWhenAutoPlacingForRotors: "Csökkentett dobótávolságok figyelembe vétele szórófejek automatikus elhelyezésekor (Rotors)",
        recommendedPressure: "Ajánlott a gyártó által",
        userPressure: "Felhasználó által beállított",
        expPressure: "Az elvárt nyomás a fogyasztónál",
        sprinklerGroupMode: "Csoportosítás a fogyasztók között",
        safeSprGroupMode: "Szigorú mód (csak kompatibilis csoportok)",
        unsafeSprGroupMode: "Biztonságtalan mód (FIGYELEM! Nincsenek csoportosítási korlátozások)",
        "sprinklerAttachBulkMode": "Tömeges fogyasztó csatlakozás módja",
        "safeSprAttachMode": "Ne csatlakoztassa újra a már csatlakoztatott fogyasztókat",
        "unsafeSprAttachMode": "Biztonságtalan mód (FIGYELEM! Lehetséges újrakapcsolás már csatlakoztatott fogyasztók esetén. Használja saját felelősségére)",
// UNITS CONFIG
        unitsConfig: "Mérési egységek",
        precisionStd: "Tizedesjegyek a tizedesvessző után",
        unitsSystemGridAndRuler: "Mértékegységrendszer rácsra és vonalzóra",
        distanceUnits: "Távolság",
        distancePrecision: "Tizedesjegyek a tizedesvessző után",
        trenchSizeUnits: "Méret egységek",
        trenchSizePrecision: "Tizedesjegyek száma",
        sprinklerDistUnits: "Permetező sugár",
        sprinklerDistPrecision: "Tizedesjegyek a tizedesvessző után",
        areaUnits: "Terület",
        areaPrecision: "Tizedesjegyek a tizedesvessző után",
        volumeUnits: "Térfogat",
        volumePrecision: "Tizedesjegyek a tizedesvessző után",
        waterFlowUnits: "Víz áramlása",
        waterFlowPrecision: "Tizedesjegyek a tizedesvessző után",
        pressureUnits: "Nyomás",
        pressurePrecision: "Tizedesjegyek a tizedesvessző után",
        velocityUnits: "Sebesség",
        velocityPrecision: "Tizedesjegyek a tizedesvessző után",
        precipRateUnits: "Csapadék mennyisége",
        precipRatePrecision: "Tizedesjegyek a tizedesvessző után",
// ZONE PROPS CONFIG
        climateConfig: "Öntözési idő számítása",
        lawnCultureType: "Fű típusa",
        coolLoving: "Hidegtűrő",
        warmLoving: "Melegtűrő",
        climateTemp: "Átlagos nyári hőmérséklet",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Átlagos nyári páratartalom",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Zóna mikroklímája&nbsp;<i class='far fa-question-circle'></i>",
        microClimateTooltip: "Enyhe\n" +
            "Öntözött területek, melyek árnyékban vannak, védettek a szél ellen, és távol vannak a száraz és meleg tárgyaktól\n" +
            "\n" +
            "Normál\n" +
            "Helyek a tájban, ahol a mikroklímás viszonyok jelentkeznek: az épületek jelenléte,\n" +
            "gyalogutak és járdák, árnyék, stb. nem befolyásolják jelentősen az evapotranszpiráció értékeit\n" +
            "\n" +
            "" +
            "Szélsőséges\n" +
            "Olyan feltételeket tükröz, amelyek gátolják a növények növekedését, és könnyen stresszhelyzetbe hozzák a növényeket, ha nem megfelelően öntözik. Ez lehet egy nyílt terület, tűző napon, közel a járdákhoz, épületekhez vagy más tájképi szerkezetekhez, amelyek üvegből vagy tájképi elemekből tükrözik a fényt, vagy széljárással érintkeznek.",
        gentleMicroClimate: "Enyhe",
        normalMicroClimate: "Normál",
        toughMicroClimate: "Szélsőséges",
        soilType: "Talaj összetétele a zónákban",
        sand: "Homokos",
        sandyLoam: "Homokos agyag",
        lightLoam: "Könnyű agyag",
        mediumLoam: "Közepes agyag",
        heavyLoam: "Súlyos agyag",
        clay: "Agyag",
        heavyClay: "Súlyos agyag",
        zoneSlope: "Általános lejtés a zónákban",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Vízköltségvetés",
        lowWB: "Alacsony",
        normalWB: "Normál",
        highWB: "Magas",
        ft: "láb",
        in: "hüvelyk",
        ftin: "láb/hüvelyk",
        metric: "metrikus",
        imperialUS: "angol (US)",
// UNITS CONFIG
        hydraConfig: "Hidraulika",
        waterTemp: "Vízhőmérséklet",
        maxFlowVelocity: "Maximális áramlási sebesség a csőben",
        commonConfig: "Általános beállítások",
        lateralNozzlerSwitch: "Hogyan váltson permetezők csatlakoztatási módra",
        NStabonly: "Fül",
        NStabshift: "Fül+Shift",
        showActionSubtitles: "Mutasd a műveletfeliratokat",
        Yeah: "Igen",
        Nope: "Nem",
        start: "Indítás",
        recalibrate: "Újra kalibrálás",
        calibrationSuccess: [
            "Sikeresen kalibrálva",
            "Most már használhatja az érintőképernyőt két módban - 'kurzormozgatás' (enyhe érintéses mozgás) és 'húzás mód' (erős érintéses mozgás)"
        ],
        calibrationFailEqual: [
            "Kalibrálás sikertelen",
            "Nem észleltünk jelentős különbséget abban, ahogy érinti a képernyőt mindkét módban",
            "Próbálkozhat újra. És győződjön meg róla, hogy ujját használja, ne tollat"
        ],
        calibrationFailImproper: [
            "Kalibrálás sikertelen",
            "Nagyobb nyomást észleltünk a tollon, mint az üllőn",
            "Próbálkozhat újra. És győződjön meg róla, hogy a tollat könnyebb nyomással mozgatja, mint az üllőt"
        ],
        calibrationImpossible: [
            "Kalibrálás lehetetlen",
            "Úgy tűnik, hogy eszköze nem támogatja az érintőfelület mérését. Ezért nem tudjuk meghatározni az érintési-interakció két módját",
            "Ebben az esetben virtuális egérrel tud mozgatni bármit. Ez megjelenik a képernyő bal oldalán.",
        ],
        calibrationNeeded: [
            "Kalibrálás szükséges!",
            "Kalibrálnunk kell az érintőképernyőt, hogy meghatározhassuk az érintési-interakció két módját:",
            "Kurzormozgatási mód - amikor csak a kurzort szeretné mozgatni, vagy a sokszöget szeretné mozgatni a rajzon",
            "És húzás mód - amikor elemeket szeretne mozgatni vagy átméretezni. Emellett húzás-mozgatást kell végeznie, ha több elemet szeretne kijelölni",
            "Kérjük, kattintson az Indítás gombra, és kövesse a képernyőn megjelenő utasításokat"
        ],
        insertImage: 'Beszúrás',
        mapImagePicker: [
            "Műholdkép betöltő",
            "Szélesség/Hosszúság",
            "Adja meg a szélességet",
            "Adja meg a hosszúságot",
            "Jelenlegi hely",
            "Mehet",
            "Cím",
            "Írja be a cím egy részét, majd kattintson a 'Keresés' gombra",
            "Keresés",
            "Nagyítás",
            "Panoráma"
        ],
        "imageCrop": [
            "Képvágó eszköz"
        ],
        cropImage: "Vágás",
        invalid_dataset_1: 'Érvénytelen adathalmaz. A projekt tiltott típusú felületeket tartalmaz. Csak öntözött (GYEP), nem öntözött területek és akadályok engedélyezettek.',
        invalid_dataset_2: 'Érvénytelen adathalmaz. Csak EGY öntözött felület engedélyezett, sem több, sem kevesebb.',
        invalid_dataset_3: 'Érvénytelen adathalmaz. Az öntözött felület önmetsződik.',
        invalid_dataset_4: 'Érvénytelen adathalmaz. Az akadályjelző nem lehet összetett (Több mint egy sokszögből áll).',
        invalid_dataset_5: 'Érvénytelen adathalmaz. Az akadályfelületnek teljesen tartalmaznia kell az öntözött felületet.',
        invalid_dataset_6: 'Érvénytelen adathalmaz. A projekt tiltott típusú permetezőket tartalmaz. Engedélyezettek:',
        invalid_dataset_7: 'Érvénytelen adathalmaz. A permetezők csapadékhozata nincs megfelelő tartományban.',
        invalid_dataset_8: 'Érvénytelen adathalmaz. A permetezőknek nem lehet egyedi nyomásbeállítása.',
        invalid_dataset_9: 'Érvénytelen adathalmaz. A projektnek nem kell egyéni várható nyomást beállítania a permetezőknél.',
        invalid_dataset_10: 'Érvénytelen adathalmaz. A homogenitás túl alacsony.',
        invalid_dataset_11: 'Érvénytelen adathalmaz. A túlzottan öntözött terület túl nagy.',
        layoutPresetsMenu: [
            "Elrendezés előbeállítások",
            "Jelenlegi elrendezés előbeállítás",
            "Elrendezéskészlet előbeállítás",
            "Alapértelmezett előbeállítás új elrendezéshez:",
            "- Válasszon előbeállítást -",
            "- Nincs elérhető előbeállítás -"
        ],
        edit: "Szerkesztés",
        nozzleCharacteristicsConfig: "Fúvóka jellemzők konfigurációi",
        nozzleCharacteristicsConfig_lang: {
           // Main editor
           title: "Fúvóka jellemzők konfigurációja",
           save: "Mentés",
           cancel: "Mégse",
           reset: "Visszaállítás",
           typeArc: "Ív",
           typeStrip: "Csík",
           typeVariableArc: "Változó ív",
           unknown: "Ismeretlen",
           object: "Objektum",
           selectVariant: "Válasszon változatot",
           editVariant: "Változat szerkesztése",

           // Variant editor fields
           editData: "Teljesítményadatok szerkesztése",
           editPrecipMap: "Csapadéktérkép szerkesztése",
           pressuresLabel: "Nyomások",
           anglesLabel: "Szögek",
           valuePairsLabel: "Értékpárok",
           valuesLabel: "Értékek",
           pointsLabel: "pont",
           valuesSuffix: "érték",
           pairsSuffix: "pár",
           none: "nincs",

           // Field name labels
           pressMap: "Nyomás",
           angleMap: "Szög",
           valuesMap: "Értékek",
           precipMap: "Csapadék",
           reducableBy: "Csökkentési szorzó (0.0 - 1.0)",

           // Error messages
           invalidInputFormat: "Érvénytelen bemeneti formátum.",
           fieldInvalidFormat: "Érvénytelen formátum.",
           reducableByOutOfRange: "Az értéknek 0.01 és 0.99 között kell lennie.",

           // NozzleDataEditor translations (passed to that editor)
           dataEditor: {
               modeSingle: "Egyedi szögek",
               modeRange: "Szög tartományok",
               pressureAngleLabel: "Nyomás/Szög",
               pressure: "Nyomás",
               angle: "Szög",
               distance: "Távolság",
               flow: "Áramlás",
               addRow: "Sor hozzáadása",
               addCol: "Oszlop hozzáadása",
               delete: "Törlés",
               save: "Mentés",
               cancel: "Mégse",
               reset: "Visszaállítás",
               distanceUnit: "Távolság egység",
               pressureUnit: "Nyomás egység",
               flowUnit: "Áramlás egység",
               angleMode: "Szög mód:",
               cannotDeleteLastRow: "Az utolsó sor nem törölhető!",
               cannotDeleteLastColumn: "Az utolsó oszlop nem törölhető!",
               angleRangesCannotIntersect: "A szögtartományok nem metszhetik egymást!",
               pleaseFillAllCells: "Kérjük, töltse ki az összes cellát! Üres cellák:",
               row: "Sor",
               col: "Oszlop"
           },

           // PrecipMapEditor translations (passed to that editor)
           precipEditor: {
               precipitation: "Csapadék",
               distance: "Távolság",
               addCol: "Oszlop hozzáadása",
               delete: "Törlés",
               save: "Mentés",
               cancel: "Mégse",
               reset: "Visszaállítás",
               precipitationUnit: "Csapadék egység",
               cannotDeleteLastColumn: "Az utolsó oszlop nem törölhető!"
           }
        }
    }
};
