this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "ft/in",
        sqm: "m²",
        acre: "ac",
        hectare: "ha",
        sqft: "sqr.ft",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gal",
        cubft: "ft³",
        lpm: "lpm",
        lph: "lph",
        m3h: "m³/h",
        USgpm: "gpm",
        USgph: "gph",
        deg: "°",
        pcs: "pz",
        pcsDot: "pz.",
        pcsShort: "pz.",
        percent: "%",
        in_Alt: "in.",
        mps: "m/s",
        kph: "km/h",
        ftps: "ft/s",
        degreesCentigrade: "°C",
        mmph: "mm/h",
        mmp24h: "mm/giorno",
        inph: "in/h",
// unconvertable
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Cassetto automatico",
        chooseSprinkler: "Scegli il getto d'acqua:",
        auto: "Imposta automaticamente",
        waterSource2row: ["Presa", "d'acqua"],
        setLineLength: "Imposta la dimensione della linea (mm):",
        setPressure: "Imposta la pressione dinamica prevista alle bocchette (bar):",
        setMaxFlow: "Imposta il flusso d'acqua massimo (l/min):",
        controllerShort: "C",
        sensorShort: "S",
        action_activateEraser: "Attiva la gomma",
        action_deactivateEraser: "Disattiva la gomma",
        action_boolUnite: "Unisci",
        action_boolIntersect: "Interseca",
        action_boolSubtract: "Sottrai",
        action_boolExclude: "Escludi",
        action_changeSprayBody: "Imposta il getto",
        action_changeVariant: "Imposta la variante",
        action_changeImgVariant: "Imposta la variante dell'immagine",
        action_changeType: "Imposta il tipo",
        action_addConsumers: "Aggiungi consumatori",
        action_drawBranches: "Aggiungi rami",
        action_editLine: "Modifica i segmenti",
        action_drawCircles: "Disegna cerchi",
        action_detachAll: "Sgancia tutto",
        action_drawBrush: "Disegna pennello",
        action_editBrush: "Modifica il pennello",
        action_changeBrushSize: "Dimensione del pennello",
        action_booleans: "Operazioni booleane",
        action_intoPoly: "Converti in poligono",
        action_intoBrush: "Converti in pennello",
        action_activateRotation: "Ruota",
        action_deactivateRotation: "Fermo",
        action_markZones: "Rappresentazione delle zone",
        action_unmarkZones: "Rimuovi marcatura",
        action_sprNames: "Nomi dei getti d'acqua",
        action_noSprNames: "Rimuovi i nomi",
        action_lockItem: "Blocca",
        action_unlockItem: "Sblocca",
        Circle: "Cerchio",
        Triangle: "Triangolo",
        BushForm: "Arbusti",
        BushForm1: "Arbusti 1",
        BushForm2: "Arbusti 2",
        BushForm3: "Arbusti 3",
        Square: "Quadrato",
        noShadow: "Nessuna",
        standardShadow: "Standard",
        noArrows: "Nessuna",
        startArrow: "All'inizio",
        endArrow: "Alla fine",
        bothArrows: "Entrambi i lati",
        normalSizeSide: "Normale",
        invertedSizeSide: "Invertito",
        strMiter: "Taglio a cuneo",
        strRound: "Tondo",
        strBevel: "Smussato",
        strSquare: "Quadrato",
        strButt: "Butt",
        FWnormal: "Normale",
        FWbold: "Grassetto",
        FWitalic: "Corsivo",
        FWbolditalic: "Grassetto Corsivo",
        FJleft: "Sinistra",
        FJright: "Destra",
        FJcenter: "Centro",
        rzwHeight: "Altezza"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Selettore",
//----Disegno
        selectPoly: "Nessun elemento selezionato",
//----Irrigazione
        selectSprink: "Nessun elemento selezionato",
        lpNozzler: "Collegamento dei consumatori d'acqua",
        dl16CircDrawer: "Disegno dei cerchi di gocciolamento per il posizionamento di tubi da 16/13mm",
        dl16sDrawer: "Disegno della copertura per il gocciolamento dei tubi da 16/13mm",
        dl17CircDrawer: "Disegno dei cerchi di gocciolamento per il posizionamento di tubi da 17mm",
        dl17sDrawer: "Disegno della copertura per il gocciolamento dei tubi da 17mm",
        "ldTextDrawer": "Impostazione del Testo",
        "staticTextDrawer": "Impostazione del Testo",
        "dynamicTextDrawer": "Impostazione del Testo",
        "ldStaticTextDrawer": "Impostazione del Testo",
        "ldtextEditor": "Modifica del Testo",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Distanza totale",
        type: "Tipo",
        variant: "Variante",
        area: "Area",
        perimeter: "Perimetro",
        curveLength: "Lunghezza",
        treeDiameter: "Diametro",
        bushDiameter: "Diametro",
        nozTypes: "Tipi disponibili",
        nozType: "Tipo",
        sprBod: "Corpo del getto d'acqua",
        rad: 'Raggio',
        angle: 'Angolo',
        reducedBy: 'Ridotto di',
        consump: 'Consumo',
        pressure: 'Pressione',
        coverSize: 'Copertura',
        maxFlow: 'Flusso d\'acqua massimo',
        pipesNum: "Tubi collegati",
        pipeType: "Tipo",
        pipeLength: "Lunghezza",
        wireLength: "Lunghezza",
        valvesManifNum: "Collettori di valvole",
        valvesNum: "Valvole",
        propDiam: "Diametro corretto",
        curDiam: "Diametro disegnato",
        outsNum: "Consumatori d'acqua",
        flow: "Flusso d'acqua",
        precipRate: "Intensità di precipitazione",
        totalPrecipArea: "Superficie totale coperta",
        uniformity: "CU",
        uniformity2: "DU",
        overwatered: "Overwatered",
        precipRateShort: "Int. precip.",
        runtimeInd: "Tempo di esecuzione",
        coveredArea: "Area coperta",
        microClimateInd: "M/Climate",
        soilTypeInd: "Tipo di suolo",
        zoneSlopeInd: "Pendenza",
        maxInfiltrationRate: "Velocità di infiltrazione massima",
        waterDemand: "Richiesta d'acqua",
        numOfRuns: "Numero di avviamenti giornalieri",
        timePerRun: "Tempo per avviamento",
        dailyConsumption: "Consumo giornaliero",
        dripsNum: "Linee di gocciolamento collegate",
        dripType: "Tipo di gocciolatore",
        dripRowsStep: "Passo delle file in superficie",
        dripRowsAngle: "Angolo delle file in superficie",
        cntrType: "Tipo di controller",
        sensType: "Tipo di sensore",
        zonesNum: "Zone controllate",
        trenchWidth: "Larghezza",
        trenchDepth: "Profondità",
        trenchVolume: "Volume",
        insetDiam: "Diametro",
        insetLength: "Lunghezza",
        insetVar: "Materiale",
        itemsCount: "Quantità",
        insetDepth: "Profondità",
        zoneName: "Nome zona",
        valveName: "Cassetta delle valvole",
        itemAlias: "Alias",
        lineWidth: "Larghezza",
        lineDepth: "Profondità",
        lineArea: "Area",
        lineVolume: "Volume",
        surfaceDepth: "Profondità/Altezza",
        surfaceVolume: "Volume",
//MULTISELECTOR
        itemsSelected: "Selezionati",
        totalArea: "Area totale",
        totalPerimeter: "Perimetro totale",
        totalLength: "Lunghezza totale",
        totalVolume: "Volume totale",
        totalConsumption: "Consumo totale",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Poligono non valido",
        isSelfCrossing_false: "Poligono valido",
        isConnected_true: "Connesso",
        isConnected_false: "Non connesso",
        isWired_true: "Cablati",
        isWired_false: "Non cablati",
        isDripZone_true: "Zona di gocciolamento",
        isDripZone_false: "",
        isSprinklerZone_true: "Zona di irrigazione",
        isSprinklerZone_false: "",
        isOverloaded_true: "SOVRACCARICO!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Bassa pressione",
        isUnderpressured_false: "",
        isOverpressured_true: "Alta pressione",
        isOverpressured_false: "",
        isLocked_true: "Bloccato",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Acciaio inossidabile",
        "High speed": "Alta velocità",
        "Opposing nozzle": "Getto opposto",
        "Plastic": "Plastica",
        "MPR Nozzles": "Getti MPR",
        "Rotary Nozzles": "Getti rotanti",
        Nozzles: "Getti",
        "Bubbler nozzles": "Getti bubbler",
        "Multi-stream": "Multigetto",
        "Dual-stream": "Biflusso",
        "Stream Nozzles": "Getti a getto unico",
        "Short Radius Nozzles": "Getti a raggio corto",
        "Pressure compensating": "Compensazione di pressione",
        "Adjustable flood": "Inondazione regolabile",
        Adjustable: "Regolabile",
        Fixed: "Fisso",
        "Fixed Arc": "Angolo fisso",
        "Strip Pattern": "Modello a strisce",
        "Drip line": "Tubo a gocciolamento",
        "Drip cover": "Copertura per gocciolamento",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "Con emitter",
        "noemitter": "Senza emitter",
        "Root zone watering": "Irrigazione della zona radicale",
        Lateral: "Laterale",
        Main: "Principale",
        Trench: "Fossa",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC(Metric)",
        ldpe: "LDPE",
        Controller: "Controller",
        Sensor: "Sensore",
        Wiring: "Collegamento",
        IrrigateMarks: "Zone di irrigazione",
        Surface: "Superficie",
        Lawn: "Prato",
        Bed: "Aiuola",
        Shrubs: "Cespugli",
        Path: "Sentiero",
        Concrete: "Cemento",
        Sand: "Sabbia",
        Water: "Acqua",
        Bedding: "Piantumazione",
        Flower: "Fiore",
        Herbal: "Erbe",
        geographic: "Geografico",
        loSurface: "Superficie",
        loStdSurf: "Standard (Poligono)",
        loStdSurf_BRUSH: "Standard (Pennello)",
        sizeMark: "Dimensioni",
        scalingBar: "Barra di scala",
        loCurves: "Linee",
        texts: "Testi",
        staticText: "Testo statico",
        dynamicText: "Testo dinamico",
        stampText: "Testo timbro",
        stampTextDefault: "Testo",
        stampTextgr1: "Definizione documento",
        stampTextgr2: "Cella indirizzo",
        stampTextgr3: "Nome sito",
        stampTextgr4: "Nome disegno",
        stampTextgr9: "Informazioni organizzazione",
        stampTextgr6t: "Fase",
        stampTextgr7t: "Pagina",
        stampTextgr8t: "Pagine",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Cap.",
        stampTextgr15t: "Prtcp.",
        stampTextgr16t: "Pagina",
        stampTextgr17t: "# Doc.",
        stampTextgr18t: "Fir.",
        stampTextgr19t: "Data",
        stampTextgr20t: "Inv.# orig.",
        stampTextgr21t: "Fir. e data",
        stampTextgr22t: "Inv.# sost.",
        inserts: "Manicotti per tubi",
        poly: "Poligono",
        brush: "Pennello",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Mostra gestore dei livelli",
        hideLM: "Nascondi gestore dei livelli",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Senza nome",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Esportazione in corso",
        successExporting: "Esportazione avvenuta con successo",
        failExporting: "Impossibile esportare",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Limite giornaliero raggiunto</a>",
        exportingLimit: "Limite: ",
        exportingLeft: "Rimasti oggi: ",
        pdfExportingPopUpBlocked: "Il tuo browser ha bloccato la finestra pop-up. Per favore, consenti i pop-up per questo sito per ottenere il file .PDF",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Raccordo a scomparsa",
        tt_group_MT: "Maschio",
        tt_group_FT: "Femmina",
        tt_riserHeight: "Altezza asta di innalzamento",
        tt_pressureReg: "Regolatore di pressione",
        tt_checkValve: "(Con valvola di ritegno)",
        tt_home: "Home",
        tt_prev: "Precedente",
        tt_next: "Successivo",
        tt_end: "Fine",
        tt_add: "Aggiungi",
        tt_clone: "Duplica",
        tt_remove: "Rimuovi",
        tt_rename: "Rinomina",
        tt_addToFav: "Aggiungi ai preferiti",
        tt_remFromFav: "Rimuovi dai preferiti",
        tt_presets: "Preimpostazioni",
        tt_MagicAutoPlacer: "`Posizionamento automatico lungo la linea`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "N",
        S: "S",
        E: "E",
        W: "W",
//conventions
        sprinklers: "Irrigatori",
        dripStarts: "Inizio gocciolatore",
        rzwLayer: "Irrigazione a radice",
        dripLines: "Linee a gocciolamento",
        valvesLayer: "Collettori valvole",
        waterSources: "Fonte di acqua",
        quickCoupLayer: "Raccordi rapidi",
        controllers: "Controllori",
        sensorsLayer: "Sensori",
        mainPipes: "Tubazioni principali",
        lateralPipes: "Tubazioni laterali",
        lateralPipes_sprinklerZone: "Zona (Irrigatori)",
        lateralPipes_dripZone: "Zona (Linee a gocciolamento)",
        lateralPipes_rzwZone: "Zona (Irrigazione a radice)",
        lateralPipes_emptyZone: "Zona (Senza utenti)",
        trenchesLayer: "Scavi",
        insetsLayer: "Maniche",
        wiresLayer: "Cablaggio",
        wirelessLayer: "Connessione wireless",
        senswirelessLayer: "Connessione wireless dei sensori",
        senswiresLayer: "Cablaggio sensore",
        surfaces: "Superfici",
        ldItemsLayer: "Piante",
        covers: "Area coperta",
        nameplates: "Informazioni utente",
        oreolas: "Etichette utente",
        pipeInfo: "Informazioni tubazioni",
        lines: "Linee",
        overlays: "Sovrapposizioni",
        stampLayer: "Cornice",
        stampTexts: "Testi timbro",
//zonesTable
        zoneType: "Tipo di zona",
        color: "Colore",
        consumers: "Consumatori",
        waterFlow: "Flusso d'acqua",
        sprinklerZone: "Irrigatore a pioggia",
        dripZone: "Irrigazione a goccia",
        rzwZone: "Irrigazione radicale",
        emptyZone: "Nessun consumatore",
        specifyDiagonal: "Per favore, specifica la dimensione diagonale del tuo monitor in pollici",
        //sprinklersTable
        consType: "Tipo",
        consName: "Nome",
        zoneNum: "Zona",
        sector: "Settore",
        radius: "Raggio",
        reducedBy: "Ridotto",
        nozzle: "Getto",
        rotor: "Rotore",
        bubbler: "Spruzzatore",
        bubblerNozzle: "Spruzzatore-Getto",
//dripsTable
        catId: "ID Categoria",
        brand: "Marca",
        emitterStep: "Intervallo",
        emitterFlow: "Flusso",
//layersManangerSpecific
        consumersGrp: "Consumatori",
        nodesGrp: "Nodi",
        wiresGrp: "Cavi",
        pipesGrp: "Tubi",
        landscapeGrp: "Paesaggio",
        allTogether: "Tutti"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Tipo",
        brand: "Marca",
        catid: "ID Categoria",
        title: "Titolo",
        units: "Unità",
        amount: "Quantità",
//predetermined
        dripLine: "Tubo a goccia",
        dl16: "Tubo a goccia 16/13mm",
        dl17: "Tubo a goccia 17mm",
        dripStart: "Inizio tubo a goccia",
        ds16: "Inizio tubo a goccia 16/13mm",
        ds17: "Inizio tubo a goccia 17mm",
        manifold_no_lps_issue: "Nessuna zona collegata",
        manifold_no_mp_issue: "Non collegato alla linea principale",
        manifold_no_wr_issue: "Nessun filo di controllo collegato",
        //nodes-----------------------------------
        sprinkler_unattached: "ATTENZIONE!!! Hai irrigatori NON ATTACCATI (non saranno presenti nella lista delle specifiche finali)",
        drip_unattached: "ATTENZIONE!!! Hai elementi di IRRIGAZIONE A GOCCIA NON ATTACCATI (non saranno presenti nella lista delle specifiche finali)",
        mains_unattached: "ATTENZIONE!!! Hai LINEE PRINCIPALI NON ATTACCATE (non saranno presenti nella lista delle specifiche finali)",
        mains_empty: "ATTENZIONE!!! Hai LINEE PRINCIPALI senza consumatori (non saranno presenti nella lista delle specifiche finali)",
        laterals_unattached: "ATTENZIONE!!! Hai TUBI LATERALI NON ATTACCATI (non saranno presenti nella lista delle specifiche finali)",
        laterals_empty: "ATTENZIONE!!! Hai TUBI LATERALI senza consumatori (non saranno presenti nella lista delle specifiche finali)",
        rzw_unattached: "ATTENZIONE!!! Hai elementi di IRRIGAZIONE DELLA ZONA RADICALE NON ATTACCATI (non saranno presenti nella lista delle specifiche finali)",
        sensors_unattached: "ATTENZIONE!!! Hai SENSORI NON ATTACCATI (non saranno presenti nella lista delle specifiche finali)",
        manifolds_unfinished: "ATTENZIONE!!! Hai COLLETTORI NON FINITI (non puoi completare la configurazione delle valvole)",
        control_wires_unattached: "ATTENZIONE!!! Hai fili di CONTROLLO non collegati",
        control_wires_empty: "ATTENZIONE!!! Hai fili di CONTROLLO senza valvole collegate",
        cntr_wr_unattached: "Filo di controllo",
        youCanSeeThemInTheDrawing: "Puoi vedere ogni elemento nel disegno, premendo l' 'occhio' sulla sinistra della riga dell'elemento",
        sprinkler_nozzleMT: "Nodo irrigatore (Getto con filettatura femmina)",
        sprinkler_nozzleFT: "Nodo irrigatore (Getto con filettatura maschio)",
        "sprinkler_rotor1/2F": "Nodo irrigatore (Rotore) 1/2\" femmina",
        "sprinkler_rotor3/4F": "Nodo irrigatore (Rotore) 3/4\"",
        "sprinkler_rotor1F": "Nodo irrigatore (Rotore) 1\"",
        "sprinkler_rotor11/4F": "Nodo irrigatore (Rotore) 1 1/4\"",
        "sprinkler_rotor11/2F": "Nodo irrigatore (Rotore) 1 1/2\"",
        "sprinkler_rotor2F": "Nodo irrigatore (Rotore) 2\"",
        "sprinkler_rotor1/2M": "Nodo irrigatore (Rotore) 1/2\" maschio",
        "sprinkler_rotor3/4M": "Sprinkler node (Rotor) 3/4\" male",
        "sprinkler_bubbler1/2F": "Nodo irrigatore (Spruzzatore)",
        sprinkler_bubblerNozzleMT: "Nodo irrigatore (Spruzzatore con getto e filettatura femmina)",
        sprinkler_bubblerNozzleFT: "Nodo irrigatore (Spruzzatore con getto e filettatura maschio)",
        dripIrrigation16: "Irrigazione a goccia (16/13mm)",
        dripIrrigation17: "Irrigazione a goccia (17mm)",
        rootZoneWatering: "Sistema di irrigazione della zona radicale",
        manifold: "Collettore di valvole",
        automation: "Nodo di automazione",
        mainPipes_hdpePE80SDR11: "Tubi principali HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Tubi principali HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Tubi principali HDPE SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Tubi laterali HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Tubi laterali HDPE SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Tubi laterali HDPE SDR 17.6",
        mainPipes_hdpeSDR9: "Tubi principali HDPE SDR 9",
        mainPipes_hdpeSDR11: "Tubi principali HDPE SDR 11",
        mainPipes_hdpeSDR136: "Tubi principali HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Tubi principali HDPE SDR 17",
        mainPipes_hdpeSDR176: "Tubi principali HDPE SDR 17.6",
        lateralPipes_hdpeSDR9: "Tubi laterali HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Tubi laterali HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Tubi laterali HDPE SDR 13.6",
        lateralPipes_hdpeSDR17: "Tubi laterali HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Tubi laterali HDPE SDR 17.6",
        mainPipes_pvcSCH40: "Tubi principali in PVC SCH40",
        mainPipes_pvcSCH80: "Tubi principali in PVC SCH80",
        mainPipes_pvcCL315: "Tubi principali in PVC CLASS 315",
        mainPipes_pvcCL200: "Tubi principali in PVC CLASS 200",
        mainPipes_pvcCL160: "Tubi principali in PVC CLASS 160",
        mainPipes_pvcCL125: "Tubi principali in PVC CLASS 125",
        mainPipes_pvcUSCJPN18: "Main pipes PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Main pipes PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Main pipes PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Main pipes PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Main pipes PVC-U SCJ (PN4.5)",
        mainPipes_ldpeCLASS3: "Tubi principali in LDPE CLASS 3",
        lateralPipes_pvcSCH40: "Tubi laterali in PVC SCH40",
        lateralPipes_pvcSCH80: "Tubi laterali in PVC SCH80",
        lateralPipes_pvcCL315: "Tubi laterali in PVC CLASS 315",
        lateralPipes_pvcCL200: "Tubi laterali in PVC CLASS 200",
        lateralPipes_pvcCL160: "Tubi laterali in PVC CLASS 160",
        lateralPipes_pvcCL125: "Tubi laterali in PVC CLASS 125",
        lateralPipes_pvcUSCJPN18: "Lateral pipes PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Lateral pipes PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Lateral pipes PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Lateral pipes PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Lateral pipes PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Tubi laterali in LDPE CLASS 3",
        wiring: "Cablaggio",
        qcv: "Valvole a sgancio rapido",
        fixedCntr: "fisso",
        stand_aloneCntr: "indipendente",
        modularCntr: "modulare",
        decoderCntr: "decoder",
        inset: "Manicotto per tubo",
        insets: "Manicotti",
        //-----------------------------------------
        novar: "nessuna variante",
        choosevar: "scegli variante",
        //element.types----------------------------
        nozzle: "Getto",
        rotor: "Rotore",
        rotorNozzle: "Getto per rotore",
        bubbler: "Spruzzatore",
        bubblerNozzle: "Spruzzatore con getto",
        rzw: "Sistema di irrigazione della zona radicale",
        sprayBody: "Corpo spruzzatore",
        sprinklerStandAssembly: "Sprinkler stand (Riser)",
        outBarb: "Attacco a barbetta per getto",
        flexPipe: "Tubo flessibile",
        sj: "Articolazione a slitta",
        inBarb: "Attacco a barbetta per tubo",
        midSprinkPipeFitting: "Raccordo per tubo",
        endSprinkPipeFitting: "Raccordo terminale per tubo",
        midRZWPipeFitting: "Raccordo per tubo",
        endRZWPipeFitting: "Raccordo terminale per tubo",
        dripPipe: "Tubo per irrigazione a goccia",
        blindPipe: "Tubo cieco",
        dripTeeFitting: "Tee per irrigazione a goccia",
        dripCapFitting: "Tappo per irrigazione a goccia",
        dripCouplingFitting: "Accoppiamento per irrigazione a goccia",
        dripElbowFitting: "Gomito per irrigazione a goccia",
        dripSpike: "Punta per irrigazione a goccia",
        sprinklerZoneValve: "Valvola per zona irrigazione a pioggia",
        emptyZoneValve: "Valvola senza consumatori",
        valveOutFitting: "Valvola per zona",
        dripZoneValve: "Valvola per zona irrigazione a goccia",
        rzwZoneValve: "Valvola di irrigazione della zona radicale",
        pressureReg: "Regolatore di pressione",
        filter_pressureReg: "Filtro con regolatore di pressione",
        controller: "Controllore",
        flowMeter: "Contatore di flusso",
        rainSensor: "Sensore di pioggia",
        soilSensor: "Sensore di umidità del suolo",
        freezeSensor: "Sensore di gelo",
        wrFreezeSensor: "Sensore di pioggia/gelo senza fili",
        windSensor: "Sensore del vento",
        solarSensor: "Sensore solare",
        flowSensor: "Sensore di flusso",
        weatherStation: "Stazione meteo",
        solarPanel: "Pannello solare",
        mainPipe: "Tubo principale",
        teeFitting: "Tee",
        elbowFitting: "Gomito",
        reducerFitting: "Riduttore",
        lateralPipe: "Tubo laterale",
        capFitting: "Tappo",
        basicCable: "Cavo base",
        basicWire: "Filo base",
        sensorCable: "Cavo sensore meteo",
        qcPlastic: "Valvola a sgancio rapido in plastica",
        qcMetal: "Valvola a sgancio rapido in metallo",
        gateway: "Gateway",
        antExt: "Antenna extension",
        loramod: "LoRa modules",
        //typesOfAcessories
        hdpeCOR: "Tubo corrugato",
        expModule: "Modulo di espansione",
        rzwSleeve: "Fodero in tessuto",
        rwCap: "Tappo acqua di recupero",
        gutterMount: "Supporto per grondaia",
        delayRelay: "Relè di ritardo",
        fctFlow: "Tee di ricettacolo FCT",
        fctBspAdap: "Adattatore per raccordo FCT",
        drainCheckValve: "Valvola di ritegno",
        rwId: "ID acqua di recupero",
        vpc: "Cappuccio antigraffio",
        inletFilter: "Filtro di ingresso",
        wifiModule: "Modulo Wi-Fi",
        wallMount: "Supporto a muro",
        rwsSock: "Fodero in tessuto",
        rwsGrate: "Griglia per RWS",
        npCover: "Coperchio non potabile",
        sprExt: "Estensione spruzzatore",
        popUpToThread: "Adattatore spruzzatore",
        valveBox: "Scatola della valvola",
        valveBoxExt: "Estensione della scatola della valvola",
        qcPlasticKey: "Chiave per valvola a sgancio rapido in plastica",
        qcPlasticElbFit: "Raccordo ad angolo per valvola a sgancio rapido in plastica",
        qcMetalKey: "Chiave per valvola a sgancio rapido in metallo",
        qcMetalElbFit: "Raccordo ad angolo per valvola a sgancio rapido in metallo",
        qcMetalCapKey: "Chiave del coperchio",
        insTape: "Nastro isolante",
        wrConn: "Connettore",
        shrinkTube: "Tubo termoretraibile",
        hcFrontPanel: "Pannello frontale",
        ball_valve: "Valvola a sfera",
        check_valve: "Valvola di ritegno",
        thread_manifold: "Collettore",
        plastic_filter: "Filtro (plastica)",
        waterMeter: "Contatore dell'acqua",
        rfModule: "Modulo radio",
        largeAntenna: "Antenna",
        wifiHub: "Hub WiFi",
        handRemoteKit: "Kit telecomando",
        handRemote: "Telecomando",
        wifiBundleKit: "Kit bundle WiFi",
//typesOfFittings
//drip
        barb_cap_8: "Chiusura di fine tubo",
        barb_elbow_PP: "Curva a barbetta",
        barb_elbow_PT: "Curva a barbetta con filettatura",
        barb_tee_PPP: "T a barbetta",
        barb_coupling_PP: "Accoppiamento a barbetta",
        barb_cross_PPPP: "Croce a barbetta",
        barb_cap_P: "Tappo a barbetta",
        barb_coupling_PT: "Accoppiatore a barba con filettatura",
        barb_tee_PTP: "Tee a barba con filettatura",
        barb_valve_PT: "Valvola a barba con filettatura",
        barb_valve_PP: "Valvola a barba",
        twlc_elbow_PP: "Gomito Twist-lock",
        twlc_tee_PPP: "Tee Twist-lock",
        twlc_coupling_PP: "Accoppiatore Twist-lock",
        twlc_cross_PPPP: "Croce Twist-lock",
        twlc_cap_P: "Tappo Twist-lock",
        twlc_coupling_PT: "Accoppiatore Twist-lock con filettatura",
        twlc_tee_PTP: "Tee Twist-lock con filettatura",
        twlc_valve_PT: "Valvola Twist-lock con filettatura",
        twlc_valve_PP: "Valvola Twist-lock",
        dl_valves: "Valvole speciali",
//pipe
        hdpeSDR9: "Tubo HDPE SDR 9",
        hdpeSDR11: "Tubo HDPE SDR 11",
        hdpeSDR136: "Tubo HDPE SDR 13.6",
        hdpeSDR17: "Tubo HDPE SDR 17",
        hdpeSDR176: "Tubo HDPE SDR 17.6",
        ldpeSDR9: "Tubo LDPE SDR 9",
        ldpeSDR11: "Tubo LDPE SDR 11",
        ldpeSDR136: "Tubo LDPE SDR 13.6",
        ldpeSDR17: "Tubo LDPE SDR 17",
        pvcSCH40: "Tubo PVC SCH40",
        pvcSCH80: "Tubo PVC SCH80",
        pvcCL315: "Tubo PVC CLASS 315",
        pvcCL200: "Tubo PVC CLASS 200",
        pvcCL160: "Tubo PVC CLASS 160",
        pvcCL125: "Tubo PVC CLASS 125",
        pvcUSCJPN18: "Pipe PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Pipe PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Pipe PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Pipe PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Pipe PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "Tubo LDPE CLASS 3",
        compress_elbow_PT: "Gomito Compressione/Filettatura",
        compress_coupling_PT: "Accoppiatore Compressione/Filettatura",
        compress_tee_PTP: "Tee Compressione/Filettatura",
        compress_cap_P: "Tappo Compressione",
        compress_elbow_PP: "Gomito Compressione",
        compress_coupling_PP: "Accoppiatore Compressione",
        compress_tee_PPP: "Tee Compressione",
        compress_cross_PPPP: "Croce Compressione",
        compress_single_clamp_saddle: "Sella singola con morsetto a compressione",
        compress_ballvalve_PP: "Valvola a sfera a compressione",
        compress_ballvalve_PT: "Valvola a sfera a compressione/filettatura",
        customfit_elbow_PT: "Gomito personalizzato / filettato",
        customfit_coupling_PT: "Accoppiamento personalizzato / filettato",
        customfit_tee_PTP: "T personalizzato / filettato",
        customfit_cap_P: "Tappo finale personalizzato",
        customfit_elbow_PP: "Gomito personalizzato",
        customfit_coupling_PP: "Accoppiamento personalizzato",
        customfit_tee_PPP: "T personalizzato",
        customfit_cross_PPPP: "Croce personalizzata",
        customfit_single_clamp_saddle: "Sella a morsetto singolo",
        customfit_ballvalve_PP: "Valvola a sfera personalizzata",
        customfit_ballvalve_PT: "Valvola a sfera personalizzata",
        thread_nipple: "Raccordo a mammella",
        thread_coupling: "Accoppiatore filettato",
        thread_mf_reducer: "Riduttore maschio/femmina",
        thread_mf_adapter: "Adattatore maschio/femmina",
        thread_mf_bush: "Boccola maschio/femmina",
        thread_tee: "Tee femmina",
        thread_elbow: "Gomito femmina",
        thread_mf_elbow: "Gomito maschio/femmina",
        thread_cap: "Tappo femmina",
        thread_plug: "Spina maschio",
        thread_union_nut: "Dado di unione",
        thread_cross: "Croce filettata",
        cable: "Cavo",
        wire: "Filo",
        // slip
        slip_single_clamp_saddle: "Sella singola con morsetto (su tubo in PVC)",
        slip_elbow_PT: "Gomito slip/filettatura",
        slip_coupling_PT: "Accoppiatore slip/filettatura",
        slip_tee_PTP: "Tee slip/filettatura",
        slip_cap_P: "Tappo Slip",
        slip_elbow_PP: "Gomito slip",
        slip_coupling_PP: "Accoppiatore slip",
        slip_tee_PPP: "Tee slip",
        slip_cross_PPPP: "Croce slip",
        slip_ballvalve_PP: "Valvola a sfera slip",
        slip_ballvalve_PT: "Valvola a sfera slip/filettatura",
//extendables
        arbitraryFittings: "Raccordi arbitrari",
        dripStartAssembly: "Assemblaggio di partenza del gocciolatore",
        intakeAssembly: "Assemblaggio di aspirazione",
        offtakeAssembly: "Raccordi arbitari di presa",
        numofvalves: "Numero di valvole: ",
        numofvalvesshort: "Valvole: ",
        numofmanifs: "Numero di collettori: ",
        intakePipeSize: "Dimensione del tubo di aspirazione: ",
        valveBoxes: "Scatole di valvole",
        valveAccessories: "Accessori per valvole",
        oneValveAccessories: "Accessori per valvola",
        controllerAccessories: "Accessori per controller",
        sensorAccessories: "Accessori per sensori",
        sprBodyAccessories: "Accessori per erogatore a getto",
        rzwAccessories: "Accessori per irrigazione a zona radicale",
        pipeStartFittings: "Raccordi arbitrari per il tubo principale",
        qcAccessories: "Accessori per valvole Q/C",
        wiringAccessories: "Accessori per cablaggio",
        pipeSize: "Dimensione del tubo: ",
        endOfPipe: "(Posizione finale)",
        midOfPipe: "(Taglio)",
        emptyRender: [
            "Spiacente... nessun contenuto elaborato",
            "Non hai completato completamente nessun nodo di irrigazione da renderizzare"
        ],
        serviceFail: [
            "Spiacente... il servizio di rendering delle specifiche non è raggiungibile al momento",
            "Riprova più tardi, quando sarà stabilita la connessione",
            "Nota che la configurazione che hai fatto in precedenza verrà comunque salvata"
        ],
        serviceTrialExpired: [
            "Spiacente... il servizio di rendering delle specifiche non è disponibile per il tuo account",
            "Questo significa che il tuo periodo di prova è terminato, e se vuoi utilizzare questo servizio",
            "<a href='/account/subscription'>Puoi aggiornare al Conto PRO</a>"
        ],
        serviceLimitReached: [
            "Hai raggiunto il limite giornaliero di fogli di specifiche renderizzati",
            "Per rimuovere il limite sul numero di rendering delle specifiche al giorno",
            "<a href='/account/subscription'>Puoi aggiornare al Conto PRO</a>"
        ],
        findInDrawing: "Mostra sulla tela",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Tubi",
        labours_group_fittings: "Raccordi",
        labours_group_valveBoxes: "Scatole di valvole",
        labours_group_wires: "Cablaggio",
        labours_group_sprinklers: "Erogatori a getto",
        labours_group_rws: "Irrigazione a zona radicale",
        labours_group_sprinklerConnections: "Connessioni per erogatori a getto",
        labours_group_drip: "Tubi e raccordi per gocciolamento",
        labours_group_manifolds: "Collettori",
        labours_group_quickCoupling: "Accoppiamento rapido",
        labours_group_controllers: "Controller",
        labours_group_sensors: "Sensori",
        labours_group_trenches: "Fossati",
        labours_group_insets: "Manicotti per tubi",
        labours_group_lawns: "Prato",
        labours_group_irrigatedArea: "Zona irrigata",
        labours_group_arbitrary_sp: "💦 Elementi di irrigazione personalizzati",
        labours_group_arbitrary_ld: "🌳 Elementi di paesaggio personalizzati",
        ldArbitrary_equip: "Attrezzatura",
        ldArbitrary_labour: "Manodopera",
        spArbitrary_equip: "Attrezzatura",
        spArbitrary_labour: "Manodopera",
        arbitrary_sp: '💦 Elementi di irrigazione personalizzati',
        arbitrary_ld: '🌳 Custom Landscape elements',
        ldLine_labour: "Linea",
        ldLine_equip: "Linea",
        spLine_labour: "Linea",
        spLine_equip: "Linea",
        ldLineWithArea_labour: "Linea (m2)",
        ldLineWithArea_equip: "Linea (m2)",
        spLineWithArea_labour: "Linea (m2)",
        spLineWithArea_equip: "Linea (m2)",
        ldVolumetricLine_labour: "Linea (m3)",
        ldVolumetricLine_equip: "Linea (m3)",
        spVolumetricLine_labour: "Linea (m3)",
        spVolumetricLine_equip: "Linea (m3)",
        polyLdSurface_labour: "Superficie",
        brushLdSurface_labour: "Superficie",
        polyLdSurface_equip: "Superficie",
        brushLdSurface_equip: "Superficie",
        polySpSurface_labour: "Superficie",
        brushSpSurface_labour: "Superficie",
        polySpSurface_equip: "Superficie",
        brushSpSurface_equip: "Superficie",
        polyLdVolumetricSurface_labour: "Superficie (m3)",
        brushLdVolumetricSurface_labour: "Superficie (m3)",
        polyLdVolumetricSurface_equip: "Superficie (m3)",
        brushLdVolumetricSurface_equip: "Superficie (m3)",
        polySpVolumetricSurface_labour: "Superficie (m3)",
        brushSpVolumetricSurface_labour: "Superficie (m3)",
        polySpVolumetricSurface_equip: "Superficie (m3)",
        brushSpVolumetricSurface_equip: "Superficie (m3)",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"],
        MMM: ["\x01", "Gen", "Feb", "Mar", "Apr", "Mag", "Giu", "Lug", "Ago", "Set", "Ott", "Nov", "Dic"],
        dddd: ["\x02", "Domenica", "Lunedì", "Martedì", "Mercoledì", "Giovedì", "Venerdì", "Sabato"],
        ddd: ["\x03", "Dom", "Lun", "Mar", "Mer", "Gio", "Ven", "Sab"],
//buttonsCaps
        ok: "Ok",
        save: "Salva",
        apply: "Applica",
        defaults: "Predefiniti",
        retry: "Riprova",
        finish: "Fine",
        safeRestart: "Riavvio sicuro",
        saveAndExit: "Salva ed esci",
        exit: "Esci",
        cancel: "Annulla",
        rename: "Rinomina",
        idk: "Non lo so",
        getFile: "Ottieni il file",
        reset: "Reset",
        random: "Casuale",
//misc
        zoneNum: "Zona n.",
        valveNum: "Scatola valvole n.",
        zonesColoring: "Rappresentazione delle zone",
        coversColoured: "Coperture degli erogatori colorate",
        dripsColoring: "Colorazione delle linee di gocciolamento",
        dripsSameAsZonesColored: "Linee di gocciolamento colorate con il colore della zona",
        //saveOflline
        saveOffline: [
            "Spiacente... la connessione è persa",
            "Ma non preoccuparti, puoi continuare il tuo progetto in modalità offline.",
            "Mentre sei offline, tutti i tuoi salvataggi verranno memorizzati come file di testo nella cartella download del tuo browser.",
            "E in seguito puoi caricare l'ultima versione del tuo disegno sul server."
        ],
        restartOffline: [
            "Spiacente... la connessione è persa",
            "Ma non preoccuparti, il tuo progetto è stato salvato localmente sul tuo computer.",
            "Puoi trovarlo nella cartella download del browser.",
            "Se vuoi lavorare offline, puoi scaricare un'istanza offline dell'applicazione dal tuo account su http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Spiacente... qualcosa è andato storto durante il caricamento del tuo progetto",
            "Sembra che il tuo salvataggio precedente sia stato in qualche modo corrotto.",
            "Ma non preoccuparti, possiamo ripararlo.",
            "Il tuo progetto ora sarà contrassegnato come 'Corrotto' nella tua area di lavoro.",
            "E il nostro personale tecnico gestirà questa situazione il prima possibile."
        ],
        corruptedSavingFile: [
            "Spiacente... il file che stai cercando di caricare non è leggibile",
            "Ma non preoccuparti, possiamo ripararlo.",
            "Tutto ciò che devi fare è inviare questo file corrotto nel modulo di caricamento file della tua area di lavoro.",
            "E poi cercheremo di farlo funzionare di nuovo."
        ],
        ajaxReqFail: [
            "Spiacente... abbiamo perso la connessione al server",
            "Al momento non è possibile inviare/ricevere dati",
            "Per favore, riprova più tardi."
        ],
        critical: [
            "Spiacente... qualcosa è andato storto",
            "Ma non preoccuparti, il tuo disegno è al sicuro, clicca solo sul pulsante di riavvio sicuro per continuare..."
        ],
        fatal: [
            "Spiacente... qualcosa è andato storto",
            "Aiutaci a migliorare il nostro servizio. Descrivi dopo quali azioni dell'utente si è verificato questo errore.",
            "Fornisci informazioni qui"
        ],
        areYouSure: [
            "Stai per chiudere questo progetto",
            "Nota che tutte le modifiche non salvate andranno perse."
        ],
        pickAnotherCSVFile: "Scegli un altro file",
        csvFileTooBig: [
            "Dimensioni massime del file csv superate",
            "Per motivi di ottimizzazione, il massimo file csv gestibile è limitato a 4Mb"
        ],
        notAnCSV: [
            "Spiacente, questo tipo di file non è supportato",
            "Formati supportati: .csv"
        ],
        invalidCSV: [
            "Contenuto del file CSV non valido",
            "Errore di analisi del file di esportazione dell'app Moasure, verifica che il file sia stato esportato correttamente"
        ],
        pickAnotherImage: "Scegli un'altra immagine",
        imageTooBig: [
            "Dimensioni massime dell'immagine superate",
            "Per motivi di ottimizzazione, la dimensione massima dell'immagine gestita è limitata a 10Mb"
        ],
        notAnImage: [
            "Spiacente, questo tipo di file non è supportato",
            "Formati di immagine supportati: .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "Azione LIMITATA",
            "Questa azione non è consentita per l'abbonamento GRATUITO"
        ],
        goPro: 'PASSA A PRO',
        renameLayout: "Inserisci il nuovo nome",
        areYouSureDeleteLayout: [
            "Attenzione! Questa azione non può essere annullata",
            "Sei sicuro di voler eliminare: ",
            "Elimina"
        ],
        setUnderlaySize: [
            "Imposta la lunghezza della linea che hai appena disegnato",
            "Hai inserito un valore non corretto. Riprova."
        ],
        setMonitorDiagonal: [
            "Fornisci informazioni sulla dimensione diagonale del tuo monitor",
            "Hai inserito un valore non corretto. Riprova."
        ],
        getSpecsTable: [
            "Imposta le preferenze di output delle specifiche",
            "Raggruppa l'attrezzatura per",
            "Nodo", "Marca",
            "Imposta il tipo di file come",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Inserisci il titolo",
            "Schema #",
            "Salva",
            "Salvataggio specifiche",
            "Completato. Clicca qui per aprire",
            "Salvataggio fallito",
            "Aggiorna i layout esistenti",
            "Aggiorna",
            "Aggiornamento layout"
        ],
        exportLayoutsAsPdf: [
            "Scegli i layout da esportare",
            "file separati (in sviluppo)",
            "un album",
            "Esporta",
            "Esporta i layout in"
        ],
        differentSprGroups: [
            "Impossibile collegare tipologie differenti di utenti idrici su questa tubazione",
            "Secondo gli standard di progettazione dell'irrigazione, non è accettabile mescolare tipologie di utenti idrici o irrigatori con diversi tassi di precipitazione nella stessa zona"
        ],
        troppoLontanoSpr: [
            "Connessione fallita con i consumatori",
            "Alcuni dei consumatori sono troppo lontani dalla tubazione laterale per essere connessi. La massima distanza di connessione è configurabile nel menu delle preferenze"
        ],
        outlayerConfig: [
            "Configurazione del foglio di specifica"
        ],
        presetsMenu: {
            title: "Preimpostazioni",
            titleTextboxLabel: "Titolo preimpostazione",
            descriptionTextboxLabel: "Descrizione",
            applyButton: "<i class='far fa-check-circle'></i> Applica",
            defaultButton: "<i class='far fa-undo'></i> Imposta predefinito",
            removeButton: "<i class='far fa-trash'></i> Rimuovi",
            updateButton: "<i class='far fa-sync'></i> Aggiorna",
            createButton: "<i class='far fa-plus'></i> Crea nuovo",
            closeButton: "<i class='far fa-times'></i> Chiudi",
            favorites_drawing: "Strumenti preferiti (Paesaggistica)",
            favorites_sprinkling: "Strumenti preferiti (Irrigazione)",
            favorites_layouting: "Strumenti preferiti (Layout)",
            configs_drawing: "Configurazione del progetto",
            configs_outlayer: "Configurazione del foglio di specifica",
        },
        newPresetItem: "Nuovo Preset",
        cL_alreadyConnected: [
            "Impossibile concatenare le linee",
            "Queste linee sono già collegate a"
        ],
        cL_segOnElem: [
            "Impossibile concatenare le linee",
            "Non puoi connetterti al segmento che è su"
        ],
        cL_strangeError: [
            "Impossibile concatenare le linee",
            "Spiacenti... la connessione non è riuscita"
        ],
        cL_misgrouping: [
            "Impossibile concatenare le linee",
            "Queste linee hanno consumatori che non sono raccomandati da collocare nella stessa zona. Se vuoi connetterli comunque, attiva la modalità 'Non sicura' per la raggruppamento degli irrigatori nella configurazione del progetto"
        ],
        cL_valve: "Collettore di valvole",
        cL_waterSource: "Fonte d'acqua",
        cL_dripStart: "Inizio gocciolamento",
        cL_controller: "Controllore",
        cL_sensors: "Sensori",
        cL_valves: "Collettore di valvole",
        cL_notSameVariant: [
            "Concatenazione delle linee non riuscita",
            "Queste linee hanno tipologie differenti",
            "Tipologia della linea correntemente disegnata",
            "Tipologia della linea con cui vuoi connettere"
        ],
        hasRestorableProject: [
            "Hai dati non salvati per questo progetto",
            "Puoi ripristinare lo stato non salvato dallo snapshot creato in data"
        ],
        restoreProject: "Ripristina",
        imageLost: [
            "Spiacenti, non possiamo trovare alcune delle immagini di sottofondo sul server",
            "Questa immagine non è stata trovata:"
        ],
        precipCalcError_mixedError: [
            'Errore nelle mappe di precipitazione',
            'Impossibile creare mappe di precipitazione per la combinazione di irrigatori:',
        ],
        precipCalcError_mprNonMprRot: 'Non è possibile mescolare rotori normali e rotori con ugelli MPR',
        precipCalcError_mprNozNonMprRot: 'Non è possibile mescolare ugelli MPR e rotori normali',
        precipCalcError_staticNozRot: 'Non è possibile mescolare ugelli statici con rotori',
        precipCalcError_staticMprNoz: 'Non è possibile mescolare ugelli statici con ugelli MPR',
        precipCalcError_missingError: [
            'Errore nelle mappe di precipitazione',
            'Profili di precipitazione mancanti per gli irrigatori:',
        ],
        precipCalcError_zoningError: [
            'Errore di zonizzazione delle mappe di precipitazione',
            'Impossibile creare mappe di precipitazione per la combinazione di irrigatori:',
        ],
        precipCalcError_noZoneAndZone: 'Non è possibile calcolare la precipitazione per rotori collegati e non collegati contemporaneamente. Il tempo di esecuzione è sconosciuto, pertanto il numero di rivoluzioni dei rotori è incerto',
        algoNozzler_noSolutions: [
            'Nessuna soluzione possibile di posizionamento degli irrigatori trovata',
            'Prova a fare quanto segue:',
            '1. Modifica le restrizioni di sovrapposizione e altre opzioni nel menu di configurazione dello strumento di posizionamento automatico',
            '2. Seleziona un altro tipo di irrigatori poiché possono offrire la flessibilità necessaria nel posizionamento',
            '3. Usa il pulsante qui sotto per riavviare la risoluzione con restrizioni più "rilassate" per sovrapposizione e copertura'
        ],
        retryWithLooseOptions: "Riprova con opzioni 'rilassate'",
        cannotSaveBecauseOffline: [
            "Impossibile inviare la richiesta al server",
            "Nessuna connessione al server",
            "Controlla la connessione internet",
            "Per evitare di perdere i dati, non chiudere questa finestra e prova a salvare i dati in seguito, quando la connessione al server sarà disponibile",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Impossibile salvare la richiesta",
            "Troppi tentativi di codice non validi",
            "Controlla se hai inserito correttamente l'indirizzo email e riprova dopo 30 secondi.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Impossibile salvare la richiesta",
            "Indirizzo email inserito in modo errato",
            "Controlla se hai inserito correttamente l'indirizzo email e riprova",
            "",
            "",
        ],
        designRequestCompleted: [
            "La tua richiesta è stata creata/aggiornata con successo",
            "Link di modifica", "copia",
            "Link di visualizzazione", "copia",
        ],
        designRequestContacts: [
            "Contact information",
            "Organization",
            "Name",
            "Email",
            "Phone",
            "Address",
            "Website",
        ],
        "designRequestInfo": [
            "Benvenuti nello Studio di Design!",
            "Qui puoi creare una richiesta per pianificare il tuo sistema di irrigazione in modo facile e veloce.",
            "Puoi trovare un <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>video di istruzioni qui</a>",
            "Per ulteriori informazioni o se hai domande, non esitare a contattarci."
        ],
        approveActionByCode: [
            "Conferma azione",
            "È stata inviata un'email con un codice di conferma all'indirizzo email che hai fornito.",
            "Inserisci questo codice nel campo sottostante",
            "Hai inserito un numero non valido, riprova"
        ],
        "revisionCheckFailedSoft": [
            "Conflitto di revisione!",
            "Questo progetto è attualmente aperto su un altro browser o dispositivo.",
            "Puoi sovrascrivere i dati sul server (poiché stiamo memorizzando solo una versione del tuo progetto) cliccando su `sovrascrivi`, ma fai attenzione - tutti i progressi fatti in altre sessioni andranno persi!",
            "Una strategia migliore è capire dove e chi ha aperto questo progetto e decidere quale versione è aggiornata.",
            "Se vuoi prendere il controllo sull'ultima versione di questo progetto aperto simultaneamente, puoi riaprire questo progetto duplicando questa scheda nel tuo browser.",
        ],
        "revisionBlocked": [
            "Il salvataggio è bloccato dall'Admin!",
            "Attualmente il tuo progetto è in fase di revisione da parte del nostro staff tecnico a causa degli errori che si stanno verificando.",
            "Attendere il completamento della revisione, dopodiché riceverai una notifica via email con ulteriori istruzioni.",
        ],
        missingVariants: [
            'Errore di elementi mancanti',
            'Di seguito è riportato l’elenco degli elementi personalizzati assenti nella libreria del progetto e quindi impossibili da visualizzare:',
            'Si prega di attivare i Set che contengono questi elementi nel menu di configurazione del progetto (in Officina)'
        ],
        "openInOtherTab": "Apri l'ultimo",
        "overwrite": "Sovrascrivi",
        "saveToFile": "Salva su file",
        filterSelection_exclude: "Escludi dalla selezione",
        filterSelection_include: "Includi nella selezione",
        filterSelectionNames: {
            sprinklers: "Consumatori",
            sprinklers_nozzle: "Consumatori - Getti",
            sprinklers_rotaryNozzle: "Consumatori - Getti rotanti",
            sprinklers_rotor: "Consumatori - Rotori",
            sprinklers_bubbler: "Consumatori - Bubblers",
            sprinklers_bubblerNozzle: "Consumatori - Bubblers-getti",
            sprinklers_pinpoint: "Consumatori - Irrigatori di precisione",
            dripStarts: "Punti di inizio a goccia",
            rzwLayer: "Irrigazione a zona radicale",
            dripLines: "Tubi gocciolanti",
            valvesLayer: "Collettori valvole",
            waterSources: "Fonti d'acqua",
            controllers: "Controllori",
            sensorsLayer: "Sensori",
            mainPipes: "Tubi principali",
            lateralPipes: "Tubi laterali",
            trenchesLayer: "Trincee",
            insetsLayer: "Maniche",
            wiresLayer: "Cavi elettrici",
            wirelessLayer: "Connessione wireless",
            senswirelessLayer: "Connessione wireless dei sensori",
            senswiresLayer: "Cavi sensori",
            quickCoupLayer: "Attacchi rapidi",
            surfaces: "Poligoni e linee",
            ldItemsLayer: "Elementi del paesaggio",
            ldArbitraryLayer: "Elementi paesaggistici personalizzati",
            spArbitraryLayer: "Elementi di irrigazione personalizzati",
            overlays: "Elementi del layout",
            stampTexts: "Testi del timbro"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Nodo irrigatore",
        fcType: "Tipo di connessione",
        sj: "Giunto oscillante",
        sprinklerStand: "Sprinkler stand (Riser)",
        flexPipeBarbs: "Tubo flessibile + barbe",
        minFlexPipeLength: "Lunghezza minima del tubo flessibile per connessione",
        midSprinkPipeFitting: "Raccordo di connessione",
        endSprinkPipeFitting: "Raccordo di fine tubo",
        single_clamp_saddle: "Morsetto a sella",
        tee_PTP: "Tee con filettatura femmina BSP",
        elbow_PT: "Gomito con filettatura femmina BSP",
        coupling_PT: "Adattatore con filettatura femmina BSP",
//CONFIGURAZIONI NODI COLLETTORI
        manifoldNode: "Nodi collettore",
        valvesOutlay: "Dispersioni delle valvole",
        fold: "Piegato",
        unfold: "Sdoppiato",
        threadsNode: "Connessioni filettate",
        threadTypes: "Tipi di filettature",
//CONFIGURAZIONI NODI AUTOMAZIONE
        automationNode: "Nodo di automazione",
        controllerModules: "I moduli di espansione dei controller modulari sono scelti:",
        controllerVoltage: "Tensione di ingresso del controller:",
        controllerVoltageV2: "Tensione di ingresso del controller:",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automaticamente (miglior abbinamento)",
        userModules: "Manualmente (come accessori)",
//RZW NODE
        rzwNode: "Irrigazione zona radicale",
        midRZWPipeFitting: "Raccordo di connessione",
        endRZWPipeFitting: "Raccordo terminale",
//DRIP node
        dripNode: "Irrigazione a goccia",
        dripConnectionType: "Tipo di raccordi per irrigazione a goccia",
        dripLengthPrecision: "Cifre decimali nella lunghezza del tubo per irrigazione a goccia",
        dripTubingAddon: "Additivo per tubi per irrigazione a goccia",
        barb: "Raccordi con barbetta",
        twistLock: "Raccordi twist-lock",
        dripSpikesStep: "Intervallo tra i supporti per tubi per irrigazione a goccia",
        dripCrossFittingAble: "Adatto a raccordi a croce",
        pipesNode: "Sezione tubi",
        hdpeConnectionType: "Tipo di raccordi HDPE",
        ldpeConnectionType: "Tipo di raccordi LDPE",
        pvcConnectionType: "Tipo di raccordi PVC",
        pipeAddon: "Additivo per tubi per ciascun diametro",
        pipeLengthPrecision: "Cifre decimali nella lunghezza dei tubi",
        crossFittingAble: "Adatto a raccordi a croce",
        compress: "Raccordi a compressione",
        customfit: "Raccordi personalizzati",
        slip: "Slip fittings",
        wiringNode: "Sezione cavi",
        exportNode: "Opzioni di esportazione",
        exportNumbersPrecision: "Cifre decimali nei numeri",
        basicWiringMethod: "Metodo di collegamento dei cavi",
        cableCoresArray: "Gamma di numeri di fili del cavo",
        noAutoWiring: "Aggiungi cavi manualmente",
        separateCableToManifold: "Separare cavi multicolore a collettore",
        separateWireToValve: "Separare i fili per ogni valvola + un filo comune a collettore",
        maxCableCores: "Numero massimo di fili del cavo",
        verticalWiringAddon: "Additivo verticale per il cavo del controllore",
        verticalSensWiringAddon: "Additivo verticale per il cavo del sensore",
        wireAddon: "Additivo per il cavo per ogni tipo",
        wireLengthPrecision: "Cifre decimali per la lunghezza dei cavi",
//DRAWER CONFIG
        drawerConfig: [
            "Configurazione del progetto"
        ],
//SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Consumatori",
        pressureDefinedBy: "La pressione attesa ai consumatori è",
        allowReduceRotors: "Consenti riduzione del raggio dei rotori",
        autoconnector: "Connessione interattiva degli irrigatori alla tubazione laterale",
        radio_option_yes: "Sì",
        radio_option_no: "No",
        extreme_rotor_reduction: "Estremo (Fino al 50%) (Può causare precipitazioni disuniformi)",
        radio_option_yes2: "Sì",
        takeReductionInAccountWhenAutoPlacing: "Offrire distanze di lancio ridotte quando si posizionano irrigatori automaticamente",
        takeReductionInAccountWhenAutoPlacingForRotors: "Offrire distanze di lancio ridotte quando si posizionano irrigatori automaticamente (Rotors)",
        recommendedPressure: "Raccomandato dal produttore",
        userPressure: "Impostato dall'utente",
        expPressure: "Pressione attesa al consumatore",
        sprinklerGroupMode: "Raggruppamento dei consumatori",
        safeSprGroupMode: "Modalità sicura (raggruppa solo elementi compatibili)",
        unsafeSprGroupMode: "Modalità non sicura (ATTENZIONE! Nessuna restrizione di raggruppamento)",
        "sprinklerAttachBulkMode": "Modalità di Connessione Massiva dei Consumatori",
        "safeSprAttachMode": "Non riconnettere i consumatori già connessi",
        "unsafeSprAttachMode": "Modalità non sicura (ATTENZIONE! Possibile riconnessione dei consumatori già connessi. Usare a proprio rischio e pericolo)",
        //UNITS CONFIG
        unitsConfig: "Unità di misura",
        precisionStd: "Cifre decimali",
        unitsSystemGridAndRuler: "Sistema di unità di misura per griglia e righello",
        distanceUnits: "Distanza",
        distancePrecision: "Cifre dopo la virgola per la distanza",
        trenchSizeUnits: "Unità di dimensioni",
        trenchSizePrecision: "Cifre dopo la virgola",
        sprinklerDistUnits: "Raggio irrigatore",
        sprinklerDistPrecision: "Cifre dopo la virgola per il raggio irrigatore",
        areaUnits: "Area",
        areaPrecision: "Cifre dopo la virgola per l'area",
        volumeUnits: "Volume",
        volumePrecision: "Cifre dopo la virgola per il volume",
        waterFlowUnits: "Flusso d'acqua",
        waterFlowPrecision: "Cifre dopo la virgola per il flusso d'acqua",
        pressureUnits: "Pressione",
        pressurePrecision: "Cifre dopo la virgola per la pressione",
        velocityUnits: "Velocità",
        velocityPrecision: "Cifre dopo la virgola per la velocità",
        precipRateUnits: "Tasso di precipitazione",
        precipRatePrecision: "Cifre dopo la virgola per il tasso di precipitazione",
// ZONE PROPS CONFIG
        climateConfig: "Calcolo del tempo di irrigazione",
        lawnCultureType: "Tipo di prato",
        coolLoving: "Amante del freddo",
        warmLoving: "Amante del caldo",
        climateTemp: "Temperatura media estiva",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Umidità media estiva",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Microclima della zona <i class='far fa-question-circle'></i>",
        microClimateTooltip: "Mite\n" +
            "Zone irrigue che sono all'ombra, riparate dal vento e lontane da oggetti secchi e riscaldati\n" +
            "\n" +
            "Normale\n" +
            "Luoghi nel paesaggio in cui le condizioni del microclima sono rappresentate: la presenza di edifici, " +
            "marciapiedi e percorsi, ombra, ecc. non influiscono significativamente sui valori dell'evapotraspirazione\n" +
            "\n" +
            "Difficile\n" +
            "Riflette le condizioni che ostacolano la crescita delle piante e si traducono " +
            "facilmente in uno stato di stress se la pianta non viene irrigata correttamente. Può essere un luogo aperto, sotto il sole cocente, in prossimità di percorsi, edifici o altre strutture paesaggistiche, che riflettono la luce dai vetri o dagli elementi del paesaggio che assorbono il calore, o può essere un luogo ventoso.",
        gentleMicroClimate: "Mite",
        normalMicroClimate: "Normale",
        toughMicroClimate: "Difficile",
        soilType: "Composizione del suolo nelle zone",
        sand: "Sabbioso",
        sandyLoam: "Fangoso sabbioso",
        lightLoam: "Fangoso leggero",
        mediumLoam: "Fangoso medio",
        heavyLoam: "Fangoso pesante",
        clay: "Argilloso",
        heavyClay: "Argilla pesante",
        zoneSlope: "Pendenza generale delle zone",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Budget dell'acqua",
        lowWB: "Basso",
        normalWB: "Normale",
        highWB: "Alto",
        ft: "piedi",
        in: "pollici",
        ftin: "piedi/pollici",
        metric: "metrico",
        imperialUS: "imperiale (USA)",
//UNITS CONFIG
        hydraConfig: "Idraulica",
        waterTemp: "Temperatura dell'acqua",
        maxFlowVelocity: "Velocità massima del flusso nella tubazione",
        "commonConfig": "Impostazioni comuni",
        "lateralNozzlerSwitch": "Come passare alla modalità di attacco degli ugelli",
        "NStabonly": "Tab",
        "NStabshift": "Tab+Shift",
        "showActionSubtitles": "Mostra sottotitoli d'azione",
        "Yeah": "Sì",
        "Nope": "No",
        start: "Avvia",
        recalibrate: "Ricalibra",
        calibrationSuccess: [
            "Calibrato con successo",
            "Ora puoi usare il touchscreen in due modalità - 'muovi cursore' (movimento leggero al tocco) e 'modalità trascina' (movimento forte al tocco)"
        ],
        calibrationFailEqual: [
            "Calibrazione fallita",
            "Non abbiamo rilevato grandi differenze nel modo in cui tocchi lo schermo in entrambe le modalità",
            "Puoi riprovare. E assicurati di usare il dito, non uno stilo"
        ],
        calibrationFailImproper: [
            "Calibrazione fallita",
            "Abbiamo rilevato una maggiore pressione sulla penna rispetto all'incudine",
            "Puoi riprovare. E assicurati di muovere la penna con una pressione più leggera rispetto all'incudine"
        ],
        calibrationImpossible: [
            "Calibrazione impossibile",
            "Sembra che il tuo dispositivo non supporti la misurazione dell'area tattile. Pertanto, non possiamo definire due modalità per l'interazione tattile",
            "In questo caso puoi usare un mouse virtuale per poter trascinare qualsiasi cosa. Apparirà sul lato sinistro dello schermo."
        ],
        calibrationNeeded: [
            "Calibrazione necessaria!",
            "Dobbiamo calibrare il tuo touchscreen per poter definire due modalità di interazione tattile:",
            "Modalità muovi cursore - quando vuoi semplicemente muovere il cursore o spostare il segmento di un poligono durante il disegno",
            "E modalità trascina - quando vuoi spostare elementi intorno o ridimensionarli. Dovresti anche trascinare-muovere quando vuoi selezionare più elementi",
            "Per favore clicca sul pulsante Avvia e segui le istruzioni sullo schermo"
        ],
        insertImage: 'Inserisci',
        mapImagePicker: [
            "Caricatore di immagini satellitari",
            "Latitudine/Longitudine",
            "Inserire la Latitudine",
            "Inserire la Longitudine",
            "Posizione attuale",
            "Vai",
            "Indirizzo",
            "Digita parte dell'indirizzo e clicca 'Cerca'",
            "Cerca",
            "Zoom",
            "Pan"
        ],
        "imageCrop": [
            "Crop tool"
        ],
        cropImage: "Crop",
        invalid_dataset_1: 'Invalid dataset. Project contains prohibited types of surfaces. Only irrigated (LAWN), non-irrigated and obstacles are allowed.',
        invalid_dataset_2: 'Invalid dataset. Not more or less than ONE irrigated surface is allowed.',
        invalid_dataset_3: 'Invalid dataset. Irrigated surface is self-intersected.',
        invalid_dataset_4: 'Invalid dataset. Obstacle marker should not be compound (Made of more than one polygon)',
        invalid_dataset_5: 'Invalid dataset. Obstacle surface should be fully contained within irrigated surface.',
        invalid_dataset_6: 'Invalid dataset. Project contains prohibited types of sprinklers. Allowed:',
        invalid_dataset_7: 'Invalid dataset. Precipitation rate of sprinklers is out of range',
        invalid_dataset_8: 'Invalid dataset. Sprinklers must not have individual pressure settings',
        invalid_dataset_9: 'Invalid dataset. The project should not set a custom expected pressure at the sprinklers',
        invalid_dataset_10: 'Invalid dataset. Uniformity is too low.',
        invalid_dataset_11: 'Invalid dataset. Overwatered area is too big.',
        layoutPresetsMenu: [
            "Preset di layout",
            "Preset di layout corrente",
            "Preset set di layout",
            "Preset predefinito per nuovo layout:",
            "- Scegli preset -",
            "- Nessun preset disponibile -"
        ],
        edit: "Modificare",
        nozzleCharacteristicsConfig: "Configurazioni caratteristiche ugello",
        nozzleCharacteristicsConfig_lang: {
           // Main editor
           title: "Configurazione caratteristiche ugello",
           save: "Salva",
           cancel: "Annulla",
           reset: "Reimposta",
           typeArc: "Arco",
           typeStrip: "Striscia",
           typeVariableArc: "Arco variabile",
           unknown: "Sconosciuto",
           object: "Oggetto",
           selectVariant: "Seleziona variante",
           editVariant: "Modifica variante",

           // Variant editor fields
           editData: "Modifica dati prestazioni",
           editPrecipMap: "Modifica mappa precipitazioni",
           pressuresLabel: "Pressioni",
           anglesLabel: "Angoli",
           valuePairsLabel: "Coppie di valori",
           valuesLabel: "Valori",
           pointsLabel: "punti",
           valuesSuffix: "valori",
           pairsSuffix: "coppie",
           none: "nessuno",

           // Field name labels
           pressMap: "Pressione",
           angleMap: "Angolo",
           valuesMap: "Valori",
           precipMap: "Precipitazioni",
           reducableBy: "Moltiplicatore di riduzione (0.0 - 1.0)",

           // Error messages
           invalidInputFormat: "Formato di input non valido.",
           fieldInvalidFormat: "Formato non valido.",
           reducableByOutOfRange: "Il valore deve essere compreso tra 0.01 e 0.99.",

           // NozzleDataEditor translations (passed to that editor)
           dataEditor: {
               modeSingle: "Angoli singoli",
               modeRange: "Intervalli di angoli",
               pressureAngleLabel: "Pressione/Angolo",
               pressure: "Pressione",
               angle: "Angolo",
               distance: "Distanza",
               flow: "Portata",
               addRow: "Aggiungi riga",
               addCol: "Aggiungi colonna",
               delete: "Elimina",
               save: "Salva",
               cancel: "Annulla",
               reset: "Reimposta",
               distanceUnit: "Unità di distanza",
               pressureUnit: "Unità di pressione",
               flowUnit: "Unità di portata",
               angleMode: "Modalità angolo:",
               cannotDeleteLastRow: "Impossibile eliminare l'ultima riga!",
               cannotDeleteLastColumn: "Impossibile eliminare l'ultima colonna!",
               angleRangesCannotIntersect: "Gli intervalli di angoli non possono intersecarsi!",
               pleaseFillAllCells: "Si prega di compilare tutte le celle! Celle vuote:",
               row: "Riga",
               col: "Colonna"
           },

           // PrecipMapEditor translations (passed to that editor)
           precipEditor: {
               precipitation: "Precipitazioni",
               distance: "Distanza",
               addCol: "Aggiungi colonna",
               delete: "Elimina",
               save: "Salva",
               cancel: "Annulla",
               reset: "Reimposta",
               precipitationUnit: "Unità di precipitazioni",
               cannotDeleteLastColumn: "Impossibile eliminare l'ultima colonna!"
           }
        },
        experimentalConfig: "Funzionalità sperimentali",
        autoNozzlePlacer: "Assistenza al posizionamento degli ugelli sul prato (ALT disabilita)",
        stylesConfig: "Stili",
        linesStyles: "Stili tubi e cablaggio",
        linesStyles_lang: {
            title: "Configurazione stili linee",
            save: "Salva",
            cancel: "Annulla",
            reset: "Ripristina predefiniti",
            // Group headers
            mainPipeGroup: "Colori tubo principale",
            lateralPipeGroup: "Colori tubo laterale",
            dripLinesGroup: "Colori linee gocciolamento",
            wiresGroup: "Colori cavi",
            // Color labels
            mpColor: "Tubo principale",
            mpOverColor: "Tubo principale (Hover)",
            mpPVCColor: "Tubo principale PVC",
            mpPVCOverColor: "Tubo principale PVC (Hover)",
            mpPVCMSColor: "Tubo principale PVC Multi-filo",
            mpPVCMSOverColor: "Tubo principale PVC Multi-filo (Hover)",
            lpColor: "Tubo laterale",
            lpOverColor: "Tubo laterale (Hover)",
            lpPVCColor: "Tubo laterale PVC",
            lpPVCOverColor: "Tubo laterale PVC (Hover)",
            lpPVCMSColor: "Tubo laterale PVC Multi-filo",
            lpPVCMSOverColor: "Tubo laterale PVC Multi-filo (Hover)",
            lpLDPESColor: "Tubo laterale LDPE-S",
            lpLDPESOverColor: "Tubo laterale LDPE-S (Hover)",
            dl16Color: "Linea gocciolamento 16mm",
            dl16OverColor: "Linea gocciolamento 16mm (Hover)",
            dl17Color: "Linea gocciolamento 17mm",
            dl17OverColor: "Linea gocciolamento 17mm (Hover)",
            wrColor: "Cavo",
            wrOverColor: "Cavo (Hover)",
            wrlsColor: "Wireless",
            wrlsOverColor: "Wireless (Hover)",
            swrColor: "Cavo sensore",
            swrOverColor: "Cavo sensore (Hover)",
            swrlsColor: "Sensore wireless",
            swrlsOverColor: "Sensore wireless (Hover)",
            dwrColor: "Cavo dati",
            dwrOverColor: "Cavo dati (Hover)"
        }
    }
};
