this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "pėdos/colių",
        sqm: "m²",
        acre: "akrai",
        hectare: "ha",
        sqft: "kv.m.",
        bar: "barai",
        kpa: "kPa",
        atm: "atmosferos",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "JAV galonai",
        lpm: "l/min",
        lph: "l/val",
        m3h: "m³/val",
        USgpm: "JAV galonai/min",
        USgph: "JAV galonai/val",
        deg: "°",
        pcs: "vnt",
        pcsDot: "vnt.",
        pcsShort: "vnt.",
        percent: "%",
        in_Alt: "colių",
        mps: "m/s",
        kph: "km/val",
        ftps: "ft/s",
        degreesCentigrade: "°C",
        mmph: "mm/min",
        mmp24h: "mm/24h",
        inph: "colių/min",
// negaliu versti
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Automatinis parinkimas",
        chooseSprinkler: "Pasirinkite purkštuką:",
        auto: "Nustatyti automatiškai",
        waterSource2row: ["Vanduo", "Priėmimas"],
        setLineLength: "Nustatykite linijos ilgį (mm):",
        setPressure: "Nustatykite tikėtiną dinaminį slėgį ant purkštukų (bar):",
        setMaxFlow: "Nustatykite maksimalų vandens tekėjimą (l/min):",
        controllerShort: "V",
        sensorShort: "J",
        action_activateEraser: "Aktyvuoti trintuką",
        action_deactivateEraser: "Išjungti trintuką",
        action_boolUnite: "Vienybė",
        action_boolIntersect: "Sankirta",
        action_boolSubtract: "Atimti",
        action_boolExclude: "Išbraukti",
        action_changeSprayBody: "Pasirinkti purškiklį",
        action_changeVariant: "Pasirinkti variantą",
        action_changeImgVariant: "Pasirinkti vaizdo variantą",
        action_changeType: "Pasirinkti tipą",
        action_addConsumers: "Pridėti vartotojus",
        action_drawBranches: "Pridėti šakas",
        action_editLine: "Redaguoti segmentus",
        action_drawCircles: "Brėžti apskritimus",
        action_detachAll: "Atsegti visus",
        action_drawBrush: "Brėžti šepetėliu",
        action_editBrush: "Redaguoti šepetėlį",
        action_changeBrushSize: "Šepetėlio dydis",
        action_booleans: "Logikos operacijos",
        action_intoPoly: "Paversti į daugiakampį",
        action_intoBrush: "Paversti į šepetėlį",
        action_activateRotation: "Pasukti",
        action_deactivateRotation: "Stovėti",
        action_markZones: "Zonų atvaizdavimas",
        action_unmarkZones: "Pašalinti žymėjimą",
        action_sprNames: "Purkštukų pavadinimai",
        action_noSprNames: "Pašalinti pavadinimus",
        action_lockItem: "Užrakinti",
        action_unlockItem: "Atrakinti",
        Circle: "Apskritimas",
        Triangle: "Trikampis",
        BushForm: "Krūmai",
        BushForm1: "Krūmai 1",
        BushForm2: "Krūmai 2",
        BushForm3: "Krūmai 3",
        Square: "Kvadratas",
        noShadow: "Nėra",
        standardShadow: "Standartinis",
        noArrows: "Nėra",
        startArrow: "Pradžioje",
        endArrow: "Pabaigoje",
        bothArrows: "Abiejose pusėse",
        normalSizeSide: "Normalus",
        invertedSizeSide: "Apverstas",
        strMiter: "Aštrus",
        strRound: "Apskritas",
        strBevel: "Nelygus",
        strSquare: "Kvadratinis",
        strButt: "Plyšinė",
        FWnormal: "Normalus",
        FWbold: "Paryškintas",
        FWitalic: "Kursyvas",
        FWbolditalic: "Paryškintas kursyvas",
        FJleft: "Kairėje",
        FJright: "Dešinėje",
        FJcenter: "Centruotas",
        rzwHeight: "Aukštis"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Pasirinkiklis",
//----Brėžimas
        selectPoly: "Nepasirinkti elementai",
//----Laistymas
        selectSprink: "Nepasirinkti elementai",
        lpNozzler: "Pridedami vartotojai",
        dl16CircDrawer: "Lašintuvų apskritimų dedėjas 16/13mm",
        dl16sDrawer: "Lašintuvų dangčių brėžimas 16/13mm",
        dl17CircDrawer: "Lašintuvų apskritimų dedėjas 17mm",
        dl17sDrawer: "Lašintuvų dangčių brėžimas 17mm",
        "ldTextDrawer": "Teksto Nustatymas",
        "staticTextDrawer": "Teksto Nustatymas",
        "dynamicTextDrawer": "Teksto Nustatymas",
        "ldStaticTextDrawer": "Teksto Nustatymas",
        "ldtextEditor": "Teksto Redagavimas",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Iš viso atstumas",
        type: "Tipas",
        variant: "Variantas",
        area: "Plotas",
        perimeter: "Perimetras",
        curveLength: "Ilgis",
        treeDiameter: "Skersmuo",
        bushDiameter: "Skersmuo",
        nozTypes: "Galimi tipai",
        nozType: "Tipas",
        sprBod: "Purškimo kūnas",
        rad: 'Spindulys',
        angle: 'Kampas',
        reducedBy: 'Sumažinta',
        consump: 'Suvartojimas',
        pressure: 'Slėgis',
        coverSize: 'Padengimas',
        maxFlow: 'Maksimalus vandens tekėjimas',
        pipesNum: "Prisijungusios vamzdynų dalys",
        pipeType: "Tipas",
        pipeLength: "Ilgis",
        wireLength: "Ilgis",
        valvesManifNum: "Vamzdžių kolektoriai",
        valvesNum: "Venti-liai",
        propDiam: "Tinkamas skersmuo",
        curDiam: "Piešinio skersmuo",
        outsNum: "Vandens vartotojai",
        flow: "Vandens tekėjimas",
        precipRate: "Kritulių intensyvumas",
        totalPrecipArea: "Visas dangos plotas",
        uniformity: "Uniformity (CU)",
        overwatered: "Overwatered",
        precipRateShort: "Kritul.",
        runtimeInd: "Veikimo laikas",
        coveredArea: "Plotas",
        microClimateInd: "Mikroklimatas",
        soilTypeInd: "Dirvožemis",
        zoneSlopeInd: "Plokštuma",
        maxInfiltrationRate: "Įsiskverbimo greitis",
        waterDemand: "Vandens poreikis",
        numOfRuns: "Skaičius per dieną",
        timePerRun: "Laikas vienam skaičiavimui",
        dailyConsumption: "Dieninis suvartojimas",
        dripsNum: "Lašintuvų linijos prijungtos",
        dripType: "Lašintuvų tipas",
        dripRowsStep: "Paviršiaus eilučių žingsnis",
        dripRowsAngle: "Paviršiaus eilučių kampas",
        cntrType: "Valdiklio tipas",
        sensType: "Jutiklio tipas",
        zonesNum: "Valdomos zonos",
        trenchWidth: "Plotis",
        trenchDepth: "Gylis",
        trenchVolume: "Tūris",
        insetDiam: "Skersmuo",
        insetLength: "Ilgis",
        insetVar: "Medžiaga",
        itemsCount: "Kiekis",
        insetDepth: "Gylis",
        zoneName: "Zonos pavadinimas",
        valveName: "Venti-liacijų dėžė",
        itemAlias: "Pseudonimas",
//MULTISELECTOR
        itemsSelected: "Pasirinkta",
        totalArea: "Iš viso plotas",
        totalPerimeter: "Iš viso perimetras",
        totalLength: "Iš viso ilgis",
        totalVolume: "Iš viso tūris",
        totalConsumption: "Iš viso suvartota",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Netinkama daugiakampio forma",
        isSelfCrossing_false: "Tinkama daugiakampio forma",
        isConnected_true: "Susijusi",
        isConnected_false: "Nesusijusi",
        isWired_true: "Priključyta",
        isWired_false: "Nepriključyta",
        isDripZone_true: "Lašinimo zona",
        isDripZone_false: "",
        isSprinklerZone_true: "Purkštuvų zona",
        isSprinklerZone_false: "",
        isOverloaded_true: "PERDAUG!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Mažas slėgis",
        isUnderpressured_false: "",
        isOverpressured_true: "Didelis slėgis",
        isOverpressured_false: "",
        isLocked_true: "Užrakinta",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Plienas",
        "High speed": "Didelė sparta",
        "Opposing nozzle": "Priešingu kryptimi purkštuvai",
        "Plastic": "Plastikas",
        "MPR Nozzles": "MPR Purkštuvai",
        "Rotary Nozzles": "Sukamojo tipo purkštuvai",
        Nozzles: "Purkštuvai",
        "Bubbler nozzles": "Burbuliukų tipo purkštuvai",
        "Multi-stream": "Kelių srautų purkštuvai",
        "Dual-stream": "Dvigubo srauto purkštuvai",
        "Stream Nozzles": "Vieno srauto purkštuvai",
        "Short Radius Nozzles": "Trumpo spindulio purkštuvai",
        "Pressure compensating": "Slėgio kompensuojantys purkštuvai",
        "Adjustable flood": "Reguliuojami laukai",
        Adjustable: "Reguliuojami",
        Fixed: "Nereguliuojami",
        "Fixed Arc": "Nereguliuojami kampo purkštuvai",
        "Strip Pattern": "Juostinis purkštimas",
        "Drip line": "Lašinimo linija",
        "Drip cover": "Lašinimo dangtelis",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "Su lašintuvais",
        "noemitter": "Be lašintuvų",
        "Root zone watering": "Šaknų zonos laistymas",
        Lateral: "Šoninė linija",
        Main: "Pagrindinė linija",
        Trench: "Kasimo duobė",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC(Metric)",
        ldpe: "LDPE",
        Controller: "Valdiklis",
        Sensor: "Jutiklis",
        Wiring: "Prijungimas",
        IrrigateMarks: "Zonos",
        Surface: "Paviršius",
        Lawn: "Lawn",
        Bed: "Gulė",
        Shrubs: "Krūmai",
        Path: "Kelias",
        Concrete: "Betonas",
        Sand: "Smėlis",
        Water: "Vanduo",
        Bedding: "Įranga",
        Flower: "Gėlės",
        Herbal: "Žolynai",
        geographic: "Geografinis",
        sizeMark: "Matmenys",
        scalingBar: "Skalių linija",
        loCurves: "Linijos",
        texts: "Tekstai",
        staticText: "Statinis tekstas",
        dynamicText: "Dinaminis tekstas",
        stampText: "Spaudas tekstas",
        stampTextDefault: "Tekstas",
        stampTextgr1: "Dokumentų apibrėžimas",
        stampTextgr2: "Adreso laukas",
        stampTextgr3: "Svetainės pavadinimas",
        stampTextgr4: "Paveikslėlio pavadinimas",
        stampTextgr9: "Organizacijos informacija",
        stampTextgr6t: "Etapas",
        stampTextgr7t: "Puslapis",
        stampTextgr8t: "Puslapiai",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Ch.",
        stampTextgr15t: "Dalyvauti",
        stampTextgr16t: "Puslapis",
        stampTextgr17t: "# Dok.",
        stampTextgr18t: "Parašas",
        stampTextgr19t: "Data",
        stampTextgr20t: "Orig. Inv.#",
        stampTextgr21t: "Parašas ir data",
        stampTextgr22t: "Repl. Inv.#",
        inserts: "Vamzdžių dėklai",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Rodyti sluoksnių tvarkyklę",
        hideLM: "Slėpti sluoksnių tvarkyklę",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Nepavadintas",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Išvedama maketai",
        successExporting: "Sėkmingai išvesta",
        failExporting: "Nepavyko eksportuoti",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Pasiekta dienos riba</a>",
        exportingLimit: "Limitas: ",
        exportingLeft: "Liko šiandien: ",
        pdfExportingPopUpBlocked: "Jūsų naršyklė blokavo iššokančią dailės langą. Leiskite šiam svetainei rodyti iššokančius langus, kad gautumėte .PDF failą",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Iššokantis vamzdis",
        tt_group_MT: "Vyr.",
        tt_group_FT: "Mot.",
        tt_riserHeight: "Iškilimo aukštis",
        tt_pressureReg: "Slėgio reguliatorius",
        tt_checkValve: "(su tikrinimo ventiliu)",
        tt_home: "Pradžia",
        tt_prev: "Ankstesnis",
        tt_next: "Sekantis",
        tt_end: "Pabaiga",
        tt_add: "Pridėti",
        tt_clone: "Kopijuoti",
        tt_remove: "Pašalinti",
        tt_rename: "Pervadinti",
        tt_addToFav: "Pridėti prie mėgstamų",
        tt_remFromFav: "Pašalinti iš mėgstamų",
        tt_presets: "Nustatymai",
        tt_MagicAutoPlacer: "`Automatinis išdėstymas išilgai linijos`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "Š",
        S: "P",
        E: "R",
        W: "V",
//conventions
        sprinklers: "Purkštukai",
        dripStarts: "Lašelinės pradžios",
        rzwLayer: "Šaknų zonos laistymas",
        dripLines: "Lašelinės linijos",
        valvesLayer: "Ventinės kolektoriai",
        waterSources: "Vandens tiekimas",
        quickCoupLayer: "Greitas jungtukas",
        controllers: "Valdikliai",
        sensorsLayer: "Jutikliai",
        mainPipes: "Pagrindinis vamzdis",
        lateralPipes: "Šoniniai vamzdeliai",
        lateralPipes_sprinklerZone: "Zona (Purkštukai)",
        lateralPipes_dripZone: "Zona (Lašelinės linijos)",
        lateralPipes_rzwZone: "Zona (Šaknų zonos laistymas)",
        lateralPipes_emptyZone: "Zona (Be vartotojų)",
        trenchesLayer: "Tarpų linijos",
        insetsLayer: "Įdėkliukai",
        wiresLayer: "Elektra",
        wirelessLayer: "Belaidis ryšys",
        senswiresLayer: "Belaidis jutiklių ryšys",
        senswiresLayer: "Jutiklių laidai",
        surfaces: "Paviršiai",
        ldItemsLayer: "Augalai",
        covers: "Dengiamoji plotas",
        nameplates: "Vartotojo informacija",
        oreolas: "Vartotojo žymos",
        pipeInfo: "Vamzdžių informacija",
        lines: "Linijos",
        overlays: "Uždėtiniai sluoksniai",
        stampLayer: "Kadras",
        stampTexts: "Kadrų tekstai",
//zonesTable
        zoneType: "Zonos tipas",
        color: "Spalva",
        consumers: "Vartotojai",
        waterFlow: "Srautas",
        sprinklerZone: "Laistymas su purkštukais",
        dripZone: "Laistymas su lašintuvais",
        rzwZone: "Šaknų laistymas",
        emptyZone: "Nėra vartotojų",
        specifyDiagonal: "Prašome, nurodyti savo monitoriaus įstrižainės dydį coliais",
//sprinklersTable
        consType: "Tipas",
        consName: "Pavadinimas",
        zoneNum: "Zona",
        sector: "Sektorius",
        radius: "Spindulys",
        reducedBy: "Sumažintas",
        nozzle: "Purkštuko galva",
        rotor: "Sukantis purkštukas",
        bubbler: "Bubbler",
        bubblerNozzle: "Bublerio antgalis",
//dripsTable
        catId: "Kategorijos ID",
        brand: "Gamintojas",
        emitterStep: "Žingsnio ilgis",
        emitterFlow: "Srautas",
//layersManangerSpecific
        consumersGrp: "Vartotojai",
        nodesGrp: "Taškai",
        wiresGrp: "Kabeliai",
        pipesGrp: "Vamzdynai",
        landscapeGrp: "Kraštovaizdis",
        allTogether: "Visi"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Tipas",
        brand: "Prekės ženklas",
        catid: "Kat. ID",
        title: "Pavadinimas",
        units: "Vienetai",
        amount: "Kiekis",
//predetermined
        dripLine: "Lašinimo linija",
        dl16: "Lašinimo linija 16/13mm",
        dl17: "Lašinimo linija 17mm",
        dripStart: "Lašinimo pradžia",
        ds16: "Lašinimo pradžia 16/13mm",
        ds17: "Lašinimo pradžia 17mm",
        manifold_no_lps_issue: "Nėra prijungtų zonų",
        manifold_no_mp_issue: "Neprijungta prie pagrindinio vamzdyno",
        manifold_no_wr_issue: "Nėra prijungta valdymo laidų",
        //nodes-----------------------------------
        sprinkler_unattached: "ĮSPĖJIMAS!!! Jūs turite neprijungtų PURKŠTUVO elementų (jie nebus pateikti galutinėje specifikacijų lentelėje)",
        drip_unattached: "ĮSPĖJIMAS!!! Jūs turite neprijungtų LAŠINIMO sistemos elementų (jie nebus pateikti galutinėje specifikacijų lentelėje)",
        mains_unattached: "ĮSPĖJIMAS!!! Jūs turite neprijungtų PAGRIDO linijų (jos nebus pateikti galutinėje specifikacijų lentelėje)",
        mains_empty: "ĮSPĖJIMAS!!! Jūs turite PAGRIDO linijas be vartotojų (jos nebus pateikti galutinėje specifikacijų lentelėje)",
        laterals_unattached: "ĮSPĖJIMAS!!! Jūs turite neprijungtų LATERALIŲ VAMZDELIO linijų (jos nebus pateikti galutinėje specifikacijų lentelėje)",
        laterals_empty: "ĮSPĖJIMAS!!! Jūs turite LATERALIŲ VAMZDELIO linijas be vartotojų (jos nebus pateikti galutinėje specifikacijų lentelėje)",
        rzw_unattached: "ĮSPĖJIMAS!!! Jūs turite neprijungtų ŠAKNŲ ZONOS LAISTYMO elementų (jie nebus pateikti galutinėje specifikacijų lentelėje)",
        sensors_unattached: "ĮSPĖJIMAS!!! Jūs turite neprijungtų JUTIKLIŲ (jie nebus pateikti galutinėje specifikacijų lentelėje)",
        manifolds_unfinished: "ĮSPĖJIMAS!!! Jūs turite NEBAIGTŲ KOLEKTORIŲ (neužbaigus, negalima sukurti vamzdynų konfigūracijos)",
        control_wires_unattached: "ĮSPĖJIMAS!!! Jūs turite NEPRIJUNGTO VALDYMO laidų",
        control_wires_empty: "ĮSPĖJIMAS!!! Jūs turite VALDYMO laidų be prijungtų vamzdžių",
        cntr_wr_unattached: "Valdymo laidai",
        youCanSeeThemInTheDrawing: "Galite peržiūrėti kiekvieną elementą, spustelėję 'akis' elementų eilutėje kairėje",
        sprinkler_nozzleMT: "Purkštukas (Siurblinio vamzdelio šerdis su išorine įvija)",
        sprinkler_nozzleFT: "Laistytuvas (žarna su vyr. gijomis)",
        "sprinkler_rotor1/2F": "Laistytuvas (Rotacinis) 1/2\" vyr.",
        "sprinkler_rotor3/4F": "Laistytuvas (Rotacinis) 3/4\"",
        "sprinkler_rotor1F": "Laistytuvas (Rotacinis) 1\"",
        "sprinkler_rotor11/4F": "Purkštuvo mazgas (Rotorius) 1 1/4\"",
        "sprinkler_rotor11/2F": "Purkštuvo mazgas (Rotorius) 1 1/2\"",
        "sprinkler_rotor2F": "Purkštuvo mazgas (Rotorius) 2\"",
        "sprinkler_rotor1/2M": "Laistytuvas (Rotacinis) 1/2\" mot.",
        "sprinkler_bubbler1/2F": "Laistytuvas (Burbulinis)",
        sprinkler_bubblerNozzleMT: "Laistytuvas (Burbulinis žarna su vyr. gijomis)",
        sprinkler_bubblerNozzleFT: "Laistytuvas (Burbulinis žarna su mot. gijomis)",
        dripIrrigation16: "Laistymas lašelių sistema (16/13mm)",
        dripIrrigation17: "Laistymas lašelių sistema (17mm)",
        rootZoneWatering: "Šaknų zonos laistymas",
        manifold: "Ventiilų kolektorius",
        automation: "Automatika",
        mainPipes_hdpePE80SDR11: "Pagrindiniai vamzdeliai HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Pagrindiniai vamzdeliai HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Pagrindiniai vamzdeliai HDPE SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Šoniniai vamzdeliai HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Šoniniai vamzdeliai HDPE SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Šoniniai vamzdeliai HDPE SDR 17.6",
        mainPipes_hdpeSDR9: "Pagrindiniai vamzdeliai HDPE SDR 9",
        mainPipes_hdpeSDR11: "Pagrindiniai vamzdeliai HDPE SDR 11",
        mainPipes_hdpeSDR136: "Pagrindiniai vamzdeliai HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Pagrindiniai vamzdeliai HDPE SDR 17",
        mainPipes_hdpeSDR176: "Pagrindiniai vamzdeliai HDPE SDR 17.6",
        lateralPipes_hdpeSDR9: "Šoniniai vamzdeliai HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Šoniniai vamzdeliai HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Šoniniai vamzdeliai HDPE SDR 13.6",
        lateralPipes_hdpeSDR17: "Šoniniai vamzdeliai HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Šoniniai vamzdeliai HDPE SDR 17.6",
        mainPipes_pvcSCH40: "Pagrindiniai vamzdeliai PVC SCH40",
        mainPipes_pvcSCH80: "Pagrindiniai vamzdeliai PVC SCH80",
        mainPipes_pvcCL315: "Pagrindiniai vamzdeliai PVC CLASS 315",
        mainPipes_pvcCL200: "Pagrindiniai vamzdeliai PVC CLASS 200",
        mainPipes_pvcCL160: "Pagrindiniai vamzdeliai PVC CLASS 160",
        mainPipes_pvcCL125: "Pagrindiniai vamzdeliai PVC CLASS 125",
        mainPipes_pvcUSCJPN18: "Main pipes PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Main pipes PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Main pipes PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Main pipes PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Main pipes PVC-U SCJ (PN4.5)",
        mainPipes_ldpeCLASS3: "Pagrindiniai vamzdeliai LDPE CLASS 3",
        lateralPipes_pvcSCH40: "Šoniniai vamzdeliai PVC SCH40",
        lateralPipes_pvcSCH80: "Šoniniai vamzdeliai PVC SCH80",
        lateralPipes_pvcCL315: "Šoniniai vamzdeliai PVC CLASS 315",
        lateralPipes_pvcCL200: "Šoniniai vamzdeliai PVC CLASS 200",
        lateralPipes_pvcCL160: "Šoniniai vamzdeliai PVC CLASS 160",
        lateralPipes_pvcCL125: "Šoniniai vamzdeliai PVC CLASS 125",
        lateralPipes_pvcUSCJPN18: "Lateral pipes PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Lateral pipes PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Lateral pipes PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Lateral pipes PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Lateral pipes PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Šoniniai vamzdeliai LDPE CLASS 3",
        wiring: "Laidai",
        qcv: "Greita jungtis",
        fixedCntr: "Fiksuotas",
        stand_aloneCntr: "Atskiras",
        modularCntr: "Modulinis",
        decoderCntr: "Dekoderis",
        inset: "Vamzdyno antgalis",
        insets: "Vamzdyno antgaliai",
//-----------------------------------------
        novar: "Nėra variantų",
        choosevar: "Pasirinkite variantą",
//element.types----------------------------
        nozzle: "Dulkių židinys",
        rotor: "Rotorius",
        rotorNozzle: "Rotoriaus dulkių židinys",
        bubbler: "Blizgutė",
        bubblerNozzle: "Blizgutės dulkių židinys",
        rzw: "Šaknų zona",
        sprayBody: "Sprejus",
        sprinklerStandAssembly: "Sprinkler stand (Riser)",
        outBarb: "Barb-to-nozzle",
        flexPipe: "Lankstus vamzdis",
        sj: "Posūkio jungtis",
        inBarb: "Barb-to-pipe",
        midSprinkPipeFitting: "Jungiamasis vamzdelio elementas",
        endSprinkPipeFitting: "Galinis vamzdelio elementas",
        midRZWPipeFitting: "Jungiamasis vamzdelio elementas",
        endRZWPipeFitting: "Galinis vamzdelio elementas",
        dripPipe: "Lašelinis vamzdelis",
        blindPipe: "Uždaroji vamzdžio dalis",
        dripTeeFitting: "Lašelinio T-jungtis",
        dripCapFitting: "Lašelinis dangtelis",
        dripCouplingFitting: "Lašelinė jungtis",
        dripElbowFitting: "Lašelinė lenktylė",
        dripSpike: "Lašelinis kerpis",
        sprinklerZoneValve: "Purkštukų zonos vožtuvas",
        emptyZoneValve: "Vožtuvas be vartotojų",
        valveOutFitting: "Vožtuvo-prie-zonos elementas",
        dripZoneValve: "Lašelinės zonos vožtuvas",
        rzwZoneValve: "Šaknų zonos laistymo vožtuvas",
        pressureReg: "Slėgio reguliatorius",
        filter_pressureReg: "Filtravimo ir slėgio reguliavimo sistema",
        controller: "Valdiklis",
        flowMeter: "Srauto matuoklis",
        rainSensor: "Lietimo jutiklis",
        soilSensor: "Dirvožemio drėgmės jutiklis",
        freezeSensor: "Šalčiui jautrus daviklis",
        wrFreezeSensor: "Bevielis lietaus/šalčiui jautrus daviklis",
        windSensor: "Vėjo jutiklis",
        solarSensor: "Saulės jutiklis",
        flowSensor: "Srauto jutiklis",
        weatherStation: "Oro stotis",
        solarPanel: "Saulės baterija",
        mainPipe: "Pagrindinė vamzdyno linija",
        teeFitting: "T-kryžius",
        elbowFitting: "Lenktytė",
        reducerFitting: "Rezginys",
        lateralPipe: "Šoninė vamzdyno linija",
        capFitting: "Uždarymo elementas",
        basicCable: "Pagrindinis kabelis",
        basicWire: "Pagrindinis laidai",
        sensorCable: "Oro jutiklio laidai",
        qcPlastic: "Greito jungimo vožtuvai (plastikiniai)",
        qcMetal: "Greito jungimo vožtuvai (metaliniai)",
        gateway: "Gateway",
        antExt: "Antenna extension",
        loramod: "LoRa modules",
        //typesOfAcessories
        hdpeCOR: "Vamzdžių apsaugos vamzdis",
        expModule: "Išplėtimo modulis",
        rzwSleeve: "Audinio apsauginės apvalkalas",
        rwCap: "Perdirbto vandens uždarymo elementas",
        gutterMount: "Latakų tvirtinimo laikiklis",
        delayRelay: "Vėlavimo rele",
        fctFlow: "FCT priėmimo skydelis",
        fctBspAdap: "Adapteris FCT skydeliui",
        drainCheckValve: "Patikrinimo vožtuvas",
        rwId: "Atkurtos vandens ID",
        vpc: "Vandalizmo apsaugos dangtelis",
        inletFilter: "Įleidimo filtras",
        wifiModule: "Wi-Fi modulis",
        wallMount: "Sieninis laikiklis",
        rwsSock: "Audinio apvalkalas",
        rwsGrate: "Reclaimed water grate",
        npCover: "Nepakankamai gryno vandens dangtelis",
        sprExt: "Dėmės pratęsimas",
        popUpToThread: "Purškimo adapteris",
        valveBox: "Vidpadžių dėžutė",
        valveBoxExt: "Vidpadžių dėžutės pratęsimas",
        qcPlasticKey: "Atrakinimo raktas Q/C ventilams",
        qcPlasticElbFit: "Lenkiamasis jungiklis",
        qcMetalKey: "Atrakinimo raktas Q/C ventilams",
        qcMetalElbFit: "Lenkiamasis jungiklis",
        qcMetalCapKey: "Dangtelio atrakinimo raktas",
        insTape: "Izoliacinė juosta",
        wrConn: "Jungtis",
        shrinkTube: "Šilumos susitraukimo vamzdelis",
        hcFrontPanel: "Priekinis skydelis",
        ball_valve: "Sferinis vožtuvas",
        check_valve: "Patikrinimo vožtuvas",
        thread_manifold: "Šakotuvas",
        plastic_filter: "Filtrai (plastikiniai)",
        waterMeter: "Vandens skaitiklis",
        rfModule: "Radijo modulis",
        largeAntenna: "Antena",
        wifiHub: "WiFi centras",
        handRemoteKit: "Nuotolinio valdymo komplektas",
        handRemote: "Nuotolinis valdymas",
        wifiBundleKit: "WiFi rinkinys",
        //typesOfFittings
        //drip
        barb_cap_8: "Lašintuvo galinė dalis",
        barb_elbow_PP: "Lašintuvo lakštinis lenktyne",
        barb_elbow_PT: "Lašintuvo lakštinis lenktyne su sujungimu",
        barb_tee_PPP: "Lašintuvo T-šakotė",
        barb_coupling_PP: "Lašintuvo jungtis",
        barb_cross_PPPP: "Lašintuvo kryžius",
        barb_cap_P: "Lašintuvo galinis dangtelis",
        barb_coupling_PT: "Lašintuvo jungtis su sujungimu",
        barb_tee_PTP: "Lašintuvo T-šakotė su sujungimu",
        barb_valve_PT: "Lašintuvo vožtuvas su sujungimu",
        barb_valve_PP: "Lašintuvo vožtuvas",
        twlc_elbow_PP: "Posūkio vamzdelis",
        twlc_tee_PPP: "T-šakotė",
        twlc_coupling_PP: "Sujungimas",
        twlc_cross_PPPP: "Kryžius",
        twlc_cap_P: "Galas",
        twlc_coupling_PT: "Sujungimas su sujungimu",
        twlc_tee_PTP: "T-šakotė su sujungimu",
        twlc_valve_PT: "Vožtuvas su sujungimu",
        twlc_valve_PP: "Vožtuvas",
        dl_valves: "Specialūs vožtuvai",
        //pipe
        hdpeSDR9: "Vamzdis HDPE SDR 9",
        hdpeSDR11: "Vamzdis HDPE SDR 11",
        hdpeSDR136: "Vamzdis HDPE SDR 13.6",
        hdpeSDR17: "Vamzdis HDPE SDR 17",
        hdpeSDR176: "Vamzdis HDPE SDR 17.6",
        ldpeSDR9: "Vamzdis LDPE SDR 9",
        ldpeSDR11: "Vamzdis LDPE SDR 11",
        ldpeSDR136: "Vamzdis LDPE SDR 13.6",
        ldpeSDR17: "Vamzdis LDPE SDR 17",
        pvcSCH40: "Vamzdis PVC SCH40",
        pvcSCH80: "Vamzdis PVC SCH80",
        pvcCL315: "Vamzdis PVC CLASS 315",
        pvcCL200: "Vamzdis PVC CLASS 200",
        pvcCL160: "Vamzdis PVC CLASS 160",
        pvcCL125: "Vamzdis PVC CLASS 125",
        pvcUSCJPN18: "Pipe PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Pipe PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Pipe PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Pipe PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Pipe PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "Tubo LDPE CLASS 3",
        compress_elbow_PT: "Suspaudimo/Gijos kampinis jungtuvas",
        compress_coupling_PT: "Suspaudimo/Gijos jungtuvas",
        compress_tee_PTP: "Suspaudimo/Gijos T jungtis",
        compress_cap_P: "Suspaudimo galinis kištukas",
        compress_elbow_PP: "Suspaudimo kampinis jungtuvas",
        compress_coupling_PP: "Suspaudimo jungtuvas",
        compress_tee_PPP: "Suspaudimo T jungtis",
        compress_cross_PPPP: "Suspaudimo kryžius",
        compress_single_clamp_saddle: "Vieno sujungimo antgalis",
        compress_ballvalve_PP: "Suspaudimo kulkos vairas",
        compress_ballvalve_PT: "Suspaudimo/Gijos kulkos vairas",
        customfit_elbow_PT: "Individualus/Gijinės kelio sąnarys",
        customfit_coupling_PT: "Individualus/Gijinė jungtis",
        customfit_tee_PTP: "Individualus/Gijinė T formos vamzdis",
        customfit_cap_P: "Individuali galinė įdėklų dangtelis",
        customfit_elbow_PP: "Individualus kelio sąnarys",
        customfit_coupling_PP: "Individuali jungtis",
        customfit_tee_PPP: "Individuali T forma",
        customfit_cross_PPPP: "Individuali kryžius",
        customfit_single_clamp_saddle: "Vieno kablio sėdynė",
        customfit_ballvalve_PP: "Individuali sferinė vamzdžio žarna",
        customfit_ballvalve_PT: "Individuali/Gijinė sferinė vamzdžio žarna",
        thread_nipple: "Vamzdžio žirnelis",
        thread_coupling: "Gijos jungtuvas",
        thread_mf_reducer: "Mažinimo jungtis vyras/moteris",
        thread_mf_adapter: "Adapteris vyras/moteris",
        thread_mf_bush: "Įkišamasis adapteris vyras/moteris",
        thread_tee: "Moteriškas šakotuvas",
        thread_elbow: "Mot. kampinė jungtis",
        thread_mf_elbow: "Vyr./mot. kampinė jungtis",
        thread_cap: "Moteriška galvutė",
        thread_plug: "Vyrinis kištukas",
        thread_union_nut: "Sąjungos varžtas",
        thread_cross: "Kryžius",
        cable: "Kabelis",
        wire: "Laidas",
// slip
        slip_single_clamp_saddle: "Vieno spaustuko šakotuvas (ant PVC vamzdžio)",
        slip_elbow_PT: "Lizdinis/gijinės jungties kampas",
        slip_coupling_PT: "Lizdinis/gijinės jungties jungtis",
        slip_tee_PTP: "Lizdinio/gijinio šakotuvo jungtis",
        slip_cap_P: "Lizdinis galas",
        slip_elbow_PP: "Lizdinis kampas",
        slip_coupling_PP: "Lizdinė jungtis",
        slip_tee_PPP: "Lizdinis šakotuvas",
        slip_cross_PPPP: "Lizdinis kryžius",
        slip_ballvalve_PP: "Lizdinis sferinio ventilio kištukas",
        slip_ballvalve_PT: "Lizdinis/gijinės jungties sferinis vent. kištukas",
        //extendables
        arbitraryFittings: "Universalių jungtukų komplektas",
        dripStartAssembly: "Lašinimo sistemos pradžios komplektas",
        intakeAssembly: "Įsiurbimo komplektas",
        offtakeAssembly: "Atjungimo universalių jungtukų komplektas",
        numofvalves: "Ventilių skaičius: ",
        numofvalvesshort: "Ventilės: ",
        numofmanifs: "Vamzdžių skaičius: ",
        intakePipeSize: "Įsiurbimo vamzdžio skersmuo: ",
        valveBoxes: "Ventilių dėžės",
        valveAccessories: "Ventilių priedai",
        oneValveAccessories: "Ventilio priedai",
        controllerAccessories: "Valdiklio priedai",
        sensorAccessories: "Jutiklių priedai",
        sprBodyAccessories: "Purkštuko priedai",
        rzwAccessories: "Šakniastiebių laistymo priedai",
        pipeStartFittings: "Pagrindinių vamzdžių universalių jungtukų komplektas",
        qcAccessories: "Greito jungimo vožtuvų priedai",
        wiringAccessories: "Elektros laidų priedai",
        pipeSize: "Vamzdžio skersmuo: ",
        endOfPipe: "(Galas)",
        midOfPipe: "(Vidurys)",
        emptyRender: [
            "Atsiprašome... nepavyko rasti turinio",
            "Nepavyko sukurti jokių konfiguracijų, kurios būtų galima atvaizduoti"
        ],
        serviceFail: [
            "Atsiprašome... specifikacijos kūrimo paslauga šiuo metu nepasiekiama",
            "Bandykite dar kartą vėliau, kai ryšys bus atkurtas",
            "Turėkite omenyje, kad anksčiau atlikti konfigūravimai bus išsaugoti"
        ],
        serviceTrialExpired: [
            "Atsiprašome... specifikacijų kūrimo paslauga jūsų paskyrai neleidžiama",
            "Tai reiškia, kad jūsų bandymo laikotarpis pasibaigė ir norint naudoti šią paslaugą,",
            "<a href='/account/subscription'>galite atnaujinti savo paskyrą į PRO paskyrą</a>"
        ],
        serviceLimitReached: [
            "Jūs pasiekėte maksimalų leistiną dienos specifikacijų kūrimo limitą",
            "Norint pašalinti limitą dėl specifikacijų skaičiaus per dieną,",
            "<a href='/account/subscription'>galite atnaujinti savo paskyrą į PRO paskyrą</a>"
        ],
        findInDrawing: "Rasti paveiksle",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Vamzdžiai",
        labours_group_fittings: "Jungtys",
        labours_group_valveBoxes: "Vamzdžių dėžutės",
        labours_group_wires: "Elektrinės laidai",
        labours_group_sprinklers: "Laistytuvai",
        labours_group_rws: "Šaknų zonų laistymas",
        labours_group_sprinklerConnections: "Laistytuvų jungtys",
        labours_group_drip: "Lašinimo linijos ir jungtys",
        labours_group_manifolds: "Vamzdžių kolektoriai",
        labours_group_quickCoupling: "Greito jungimo sistemos",
        labours_group_controllers: "Valdikliai",
        labours_group_sensors: "Sensoriai",
        labours_group_trenches: "Kasės",
        labours_group_insets: "Vamzdžių apsaugos",
        labours_group_lawns: "Vejos",
        labours_group_irrigatedArea: "Laistoma plotas",
        labours_group_arbitrary_sp: "Pasirinktiniai laistymo elementai",
        labours_group_arbitrary_ld: "Pasirinktiniai kraštovaizdžio elementai",
        ldArbitrary_equip: "Įranga",
        ldArbitrary_labour: "Darbas",
        spArbitrary_equip: "Įranga",
        spArbitrary_labour: "Darbas",
        arbitrary_sp: '💦 Pasirinktiniai laistymo elementai',
        arbitrary_ld: '🌳 Pasirinktiniai kraštovaizdžio elementai',
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "Sausis", "Vasaris", "Kovas", "Balandis", "Gegužė", "Birželis", "Liepa", "Rugpjūtis", "Rugsėjis", "Spalis", "Lapkritis", "Gruodis"],
        MMM: ["\x01", "Sau", "Vas", "Kov", "Bal", "Geg", "Bir", "Lie", "Rgp", "Rgs", "Spa", "Lap", "Grd"],
        dddd: ["\x02", "Sekmadienis", "Pirmadienis", "Antradienis", "Trečiadienis", "Ketvirtadienis", "Penktadienis", "Šeštadienis"],
        ddd: ["\x03", "Sek", "Pir", "Ant", "Tre", "Ket", "Pen", "Šeš"],
//buttonsCaps
        ok: "Gerai",
        save: "Išsaugoti",
        apply: "Taikyti",
        defaults: "Numatytieji",
        retry: "Bandyti dar kartą",
        finish: "Baigti",
        safeRestart: "Saugus paleidimas iš naujo",
        saveAndExit: "Išsaugoti ir išeiti",
        exit: "Išeiti",
        cancel: "Atšaukti",
        rename: "Pervadinti",
        idk: "Aš nežinau",
        getFile: "Gauti failą",
        reset: "Atstatyti",
        random: "Atsitiktinis",
        //misc
        zoneNum: "Zonos #",
        valveNum: "Ventiliatoriaus dėžutė #",
        zonesColoring: "Zonų vaizdavimas",
        coversColoured: "Dažyti purkštukų dangteliai",
        dripsColoring: "Lašelių linijų spalvinimas",
        dripsSameAsZonesColored: "Lašelių linijos spalvintos pagal zonų spalvas",
//saveOflline
        saveOffline: [
            "Atsiprašome... prarastas ryšys",
            "Bet nesijaudinkite, galite tęsti savo projektą neprisijungę.",
            "Kol esate neprisijungę - visi jūsų išsaugojimai bus saugomi kaip teksto failas jūsų naršyklės parsisiuntimų aplanke.",
            "Vėliau galėsite įkelti naujausią savo piešinio versiją į serverį."
        ],
        restartOffline: [
            "Atsiprašome... prarastas ryšys",
            "Bet nesijaudinkite, jūsų projektas buvo išsaugotas jūsų kompiuteryje.",
            "Galite jį rasti naršyklės parsisiuntimų aplanke.",
            "Jei norite dirbti neprisijungę, galite atsisiųsti programos neprisijungę versiją iš savo kabineto http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Atsiprašome... kažkas nutiko, bandant užkrauti jūsų projektą",
            "Atrodo, kad jūsų ankstesnė išsaugojimo versija buvo pažeista kaip nors.",
            "Bet nesijaudinkite, mes galime tai sutvarkyti.",
            "Jūsų projektas dabar bus pažymėtas kaip 'Sugedęs' jūsų darboje.",
            "Ir mūsų techninis personalas kuo greičiau susitvarkys su šia situacija."
        ],
        corruptedSavingFile: [
            "Atsiprašome... failas, kurį bandote įkelti, nėra įskaitomas",
            "Bet nesijaudinkite, mes galime tai sutvarkyti.",
            "Viskas, ką jums reikia padaryti, tai pateikti šį sugedusį failą savo darbo kambaryje esančiame failo įkėlimo lange.",
            "Tada mes bandysime jį sutvarkyti."
        ],
        ajaxReqFail: [
            "Atsiprašome... praradome ryšį su serveriu",
            "Šiuo metu neįmanoma siųsti / gauti jokių duomenų",
            "Bandykite dar kartą vėliau"
        ],
        critical: [
            "Atsiprašome... kažkas nutiko",
            "Bet nesijaudinkite, jūsų piešinys dabar yra saugioje vietoje, tiesiog spustelėkite saugų paleidimą, kad tęstumėte..."
        ],
        fatal: [
            "Atsiprašome... kažkas nutiko",
            "Prašome padėti mums padaryti mūsų paslaugą geresnę. Aprašykite, po kokių vartotojo veiksmų ši klaida įvyko",
            "Pateikite informaciją čia"
        ],
        areYouSure: [
            "Ar tikrai norite uždaryti šį projektą?",
            "Atminkite, kad visi neišsaugoti pakeitimai bus prarasti."
        ],
        pickAnotherCSVFile: "Pasirinkite kitą failą",
        csvFileTooBig: [
            "Viršytas maksimalus CSV failo dydis",
            "Optimizacijos sumetimais, maksimalus leidžiamas CSV failo dydis yra 4 MB."
        ],
        notAnCSV: [
            "Atsiprašome, šis failo tipas nepalaikomas",
            "Palaikomi formatai: .csv"
        ],
        invalidCSV: [
            "Neteisingas CSV failo turinys",
            "Moasure programos eksporto failo analizės klaida, patikrinkite, ar failas buvo tinkamai eksportuotas"
        ],
        pickAnotherImage: "Pasirinkite kitą failą",
        imageTooBig: [
            "Viršytas maksimalus paveikslėlio dydis",
            "Optimizacijos sumetimais, maksimalus leidžiamas paveikslėlio dydis yra 10 MB."
        ],
        notAnImage: [
            "Atsiprašome, šis failo tipas nepalaikomas",
            "Palaikomi paveikslėlių formatai: .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "Veiksmas UŽKERTAS",
            "Šis veiksmas neleidžiamas NEMOKAMAM abonementui"
        ],
        goPro: 'EIK PRO',
        renameLayout: "Įveskite naują pavadinimą",
        areYouSureDeleteLayout: [
            "Dėmesio! Šio veiksmo atšaukti negalėsite",
            "Ar tikrai norite ištrinti: ",
            "Ištrinti"
        ],
        setUnderlaySize: [
            "Nustatykite linijos ilgį, kurį ką tik nubrėžėte",
            "Įvedėte neteisingą reikšmę. Bandykite dar kartą"
        ],
        setMonitorDiagonal: [
            "Prašome pateikti informaciją apie jūsų monitoriaus įstrižainės dydį",
            "Įvedėte neteisingą reikšmę. Bandykite dar kartą"
        ],
        getSpecsTable: [
            "Nustatykite specifikacijos išvesties nustatymus",
            "Įrangą grupuoti pagal",
            "Mazgas", "Prekės ženklą",
            "Nustatyti failo tipą kaip",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Įveskite pavadinimą",
            "Išdėstymas #",
            "Įrašyti",
            "Įrašomas specifikacijas",
            "Baigta. Spustelėkite čia, kad atidarytumėte",
            "Įrašyti nepavyko",
            "Atnaujinti esamus išdėstymus",
            "Atnaujinti",
            "Atnaujinami išdėstymai"
        ],
        exportLayoutsAsPdf: [
            "Pasirinkite išklotinius eksportavimui",
            "atsekiama failais (plėtojama)",
            "vienas albumas",
            "Eksportuoti",
            "Eksportuoti išklotinius"
        ],
        differentSprGroups: [
            "Nepavyko pritvirtinti skirtingų vartotojų tipų prie šio vamzdžio",
            "Pagal laistymo projektavimo standartus draudžiama derinti skirtingus vartotojų tipus ar purškiklius su skirtingais kritulių kiekiais vienoje zonoje"
        ],
        tooFarAwaySpr: [
            "Nepavyko prijungti vartotojų",
            "Kai kurių vartotojų atstumas nuo pagrindinio vamzdžio yra per didelis, kad jie galėtų būti prijungti. Maksimalus prijungimo atstumas gali būti nustatytas nuostatų meniuose"
        ],
        outlayerConfig: [
            "Specifikacijos lapo konfigūracija"
        ],
        presetsMenu: {
            title: "Nuostatos",
            titleTextboxLabel: "Nuostatos pavadinimas",
            descriptionTextboxLabel: "Aprašymas",
            applyButton: "<i class='far fa-check-circle'></i> Taikyti",
            defaultButton: "<i class='far fa-undo'></i> Grąžinti numatytąją",
            removeButton: "<i class='far fa-trash'></i> Pašalinti",
            updateButton: "<i class='far fa-sync'></i> Atnaujinti",
            createButton: "<i class='far fa-plus'></i> Sukurti naują",
            closeButton: "<i class='far fa-times'></i> Uždaryti",
            favorites_drawing: "Mėgstami įrankiai (Kraštovaizdis)",
            favorites_sprinkling: "Mėgstami įrankiai (Laistymas)",
            favorites_layouting: "Mėgstami įrankiai (Išdėstymas)",
            configs_drawing: "Projekto konfigūracija",
            configs_outlayer: "Specifikacijos lapo konfigūracija",
        },
        newPresetItem: "Naujas nustatymas",
        cL_alreadyConnected: [
            "Nepavyko sujungti linijų",
            "Šios linijos jau prijungtos prie"
        ],
        cL_segOnElem: [
            "Nepavyko sujungti linijų",
            "Negalite prijungti prie segmento, esančio ant"
        ],
        cL_strangeError: [
            "Nepavyko sujungti linijų",
            "Atsiprašome...Nepavyko prisijungti"
        ],
        cL_misgrouping: [
            "Nepavyko sujungti linijų",
            "Šios linijos turi vartotojų, kurie nerekomenduojami dėti į tą pačią zoną. Jei norite juos vis tiek sujungti, įjunkite 'Nesaugaus režimo' grupavimą projekto konfigūracijoje"
        ],
        cL_valve: "Ventilių kolektorius",
        cL_waterSource: "Vandens šaltinis",
        cL_dripStart: "Lašelinio startas",
        cL_controller: "Valdiklis",
        cL_sensors: "Sensorius",
        cL_valves: "Ventilių kolektorius",
        cL_notSameVariant: [
            "Nepavyko sujungti linijų",
            "Šios linijos yra skirtingos",
            "Dabartinės linijos tipas",
            "Linijos tipas, su kuriuo norite sujungti"
        ],
        hasRestorableProject: [
            "Šiam projektui turite nesaugotų duomenų",
            "Galite atkurti nesaugotą būseną iš atkūrimo taško, kuris buvo sukurtas"
        ],
        restoreProject: "Atkurti",
        imageLost: [
            "Atsiprašome, mes negalime rasti kai kurių pagrindo paveikslų serveryje",
            "Šis paveikslas nebuvo rastas:"
        ],
        precipCalcError_mixedError: [
            'Kritulių žemėlapių klaida',
            'Nepavyko sukurti kritulių žemėlapių purkštuvų deriniui:',
        ],
        precipCalcError_mprNonMprRot: 'Negalima maišyti įprastų rotorių ir rotorių su MPR purkštukais',
        precipCalcError_mprNozNonMprRot: 'Negalima maišyti MPR purkštukų ir įprastų rotorių',
        precipCalcError_staticNozRot: 'Negalima maišyti statinių purkštukų su rotoriais',
        precipCalcError_staticMprNoz: 'Negalima maišyti statinių purkštukų su MPR purkštukais',
        precipCalcError_missingError: [
            'Kritulių žemėlapių klaida',
            'Trūksta kritulių profilių purkštuvams:',
        ],
        precipCalcError_zoningError: [
            'Kritulių žemėlapių zonų klaida',
            'Nepavyko sukurti kritulių žemėlapių purkštuvų deriniui:',
        ],
        precipCalcError_noZoneAndZone: 'Negalima apskaičiuoti kritulių prijungtiems ir neprijungtiems rotoriams tuo pačiu metu. Veikimo laikas nežinomas, todėl rotorių apsisukimų skaičius yra neaiškus',
        algoNozzler_noSolutions: [
            'Nerasta jokių galimų purkštuvų išdėstymo sprendimų',
            'Pabandykite atlikti šiuos veiksmus:',
            '1. Pakeiskite persidengimo apribojimus ir kitas parinktis automatinio išdėstymo įrankio konfigūracijos meniu',
            '2. Pasirinkite kitokio tipo purkštuvus, nes jie gali suteikti reikalingą lankstumą išdėstymui',
            '3. Naudokite žemiau esantį mygtuką, kad iš naujo pradėtumėte sprendimą su „laisvesniais“ apribojimais persidengimui ir padengimui'
        ],
        retryWithLooseOptions: "Bandykite dar kartą su „laisvesnėmis“ parinktimis",
        cannotSaveBecauseOffline: [
            "Nepavyko siųsti užklausos į serverį",
            "Nėra ryšio su serveriu",
            "Patikrinkite, ar turite interneto ryšį",
            "Norint išsaugoti duomenis ir nepamesti jų, neuždarykite šio lango ir bandykite duomenis išsaugoti vėliau, kai bus nustatytas ryšys su serveriu",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Nepavyko išsaugoti užklausos",
            "Per daug klaidingų kodų bandymų",
            "Patikrinkite, ar teisingai įvedėte el. pašto adresą, ir bandykite dar kartą po 30 sekundžių.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Nepavyko išsaugoti užklausos",
            "El. pašto adresas įvestas neteisingai",
            "Patikrinkite, ar teisingai įvedėte el. pašto adresą, ir bandykite dar kartą",
            "",
            "",
        ],
        designRequestCompleted: [
            "Jūsų užklausa sėkmingai sukūrė / atnaujino",
            "Redaguoti nuorodą", "nukopijuoti mane",
            "Peržiūros nuoroda", "nukopijuoti mane",
        ],
        designRequestContacts: [
            "Contact information",
            "Organization",
            "Name",
            "Email",
            "Phone",
            "Address",
            "Website",
        ],
        "designRequestInfo": [
            "Sveiki atvykę į Dizaino Studiją!",
            "Čia galite greitai ir lengvai sukurti užklausą savo laistymo sistemos planavimui.",
            "Čia galite rasti <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>instrukcinį vaizdo įrašą</a>",
            "Jei turite kokių nors klausimų ar reikia daugiau informacijos, nedvejodami susisiekite su mumis."
        ],
        approveActionByCode: [
            "Patvirtinti veiksmą",
            "Patvirtinimo kodas buvo išsiųstas į jūsų pateiktą el. pašto adresą.",
            "Įveskite šį kodą laukelyje žemiau",
            "Įvedėte neteisingą numerį, bandykite dar kartą"
        ],
        "revisionCheckFailedSoft": [
            "Revizijos konfliktas!",
            "Šis projektas šiuo metu atidarytas kitoje naršyklėje ar įrenginyje.",
            "Galite perrašyti duomenis serveryje (kadangi saugome tik vieną jūsų projekto versiją) spustelėdami `perrašyti`, bet būkite atsargūs - visi kitose sesijose padaryti pažangos praras!",
            "Geresnė strategija yra suprasti, kur ir kas atidarė šį projektą, ir nuspręsti, kurios versijos yra naujausios.",
            "Jei norite perimti kontrolę prieš naujausią šio projekto versiją, kuris buvo atidarytas tuo pačiu metu, galite vėl atidaryti šį projektą dubliuodami šią kortelę savo naršyklėje.",
        ],
        "revisionBlocked": [
            "Išsaugojimas yra blokuojamas administratoriaus!",
            "Šiuo metu mūsų techninis personalas peržiūri jūsų projektą dėl jo klaidų.",
            "Prašome palaukti, kol peržiūra bus baigta, tada gausite tolesnes instrukcijas el. paštu.",
        ],
        missingVariants: [
            'Trūkstamų elementų klaida',
            'Žemiau pateiktas tinkintų elementų sąrašas, kurių nėra jūsų projekto bibliotekoje, todėl jie negali būti atvaizduoti:',
            'Įjunkite rinkinius, kuriuose yra šie elementai, projekto konfigūracijos meniu (Dirbtuvėse)'
        ],
        "openInOtherTab": "Atidaryti naujausią",
        "overwrite": "Perrašyti",
        "saveToFile": "Išsaugoti į failą",
        filterSelection_exclude: "Išskirti iš pasirinkimo",
        filterSelection_include: "Įtraukti į pasirinkimą",
        filterSelectionNames: {
            sprinklers: "Paskirstytuvai",
            sprinklers_nozzle: "Paskirstytuvai - antgaliai",
            sprinklers_rotaryNozzle: "Paskirstytuvai - sukamieji antgaliai",
            sprinklers_rotor: "Paskirstytuvai - rotoriniai antgaliai",
            sprinklers_bubbler: "Paskirstytuvai - burbuliukai",
            sprinklers_bubblerNozzle: "Paskirstytuvai - burbuliukų antgaliai",
            dripStarts: "Lašeliniai pradžių mazgai",
            rzwLayer: "Šaknų zonos laistymas",
            dripLines: "Lašelinės linijos",
            valvesLayer: "Ventilių kolektoriai",
            waterSources: "Vandens šaltiniai",
            controllers: "Valdikliai",
            sensorsLayer: "Jutikliai",
            mainPipes: "Pagrindiniai vamzdynai",
            lateralPipes: "Šoniniai vamzdynai",
            trenchesLayer: "Graždų linijos",
            insetsLayer: "Įdėklai",
            wiresLayer: "Elektrinės linijos",
            wirelessLayer: "Belaidis ryšys",
            senswiresLayer: "Belaidis jutiklių ryšys",
            senswiresLayer: "Jutiklių elektrinės linijos",
            quickCoupLayer: "Greiti jungtys",
            surfaces: "Daugiakampiai ir linijos",
            ldItemsLayer: "Landskape elemento sluoksnis"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Laistytuvo mazgas",
        fcType: "Lankstaus jungimo tipas",
        sj: "Svingo sąsaja",
        sprinklerStand: "Sprinkler stand (Riser)",
        flexPipeBarbs: "Lankstus vamzdis su barbais",
        minFlexPipeLength: "Minimalus lanksto vamzdžio ilgis per jungtį",
        midSprinkPipeFitting: "Prijungimo detalė",
        endSprinkPipeFitting: "Galinis vamzdžio įtaisas",
        single_clamp_saddle: "Spyna ant vamzdžio",
        tee_PTP: "T-kryžius su moterišku BSP gijimu",
        elbow_PT: "Kodinis kampas su moterišku BSP gijimu",
        coupling_PT: "Adaptyvas su moterišku BSP gijimu",
//MANIFOLD NODE CONFIGS
        manifoldNode: "Kolektorinio mazgo konfiguracija",
        valvesOutlay: "Ventilių išdėstymas",
        fold: "Susilanksto",
        unfold: "Išskleidžia",
        threadsNode: "Gijinių jungčių mazgas",
        threadTypes: "Gijinių jungčių tipai",
//AUTOMATION NODE CONFIGS
        automationNode: "Automatizavimo mazgas",
        controllerModules: "Pasirinkti modularūs valdiklių išplėtimo moduliai:",
        controllerVoltage: "Valdiklio įvesties įtampa:",
        controllerVoltageV2: "Valdiklio įvesties įtampa:",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automatiškai (geriausiai tinka)",
        userModules: "Rankiniu būdu (kaip priedai)",
//RZW NODE
        rzwNode: "Šaknų zonos laistymo mazgas",
        midRZWPipeFitting: "Prijungimo detalė",
        endRZWPipeFitting: "Galinis vamzdžio įtaisas",
        //DRIP node
        dripNode: "Lašelinė sistema",
        dripConnectionType: "Lašelinės jungtys",
        dripLengthPrecision: "Skaitmenų po kablelio tikslumas vamzdžio ilgiui",
        dripTubingAddon: "Lašelinio vamzdžio priedas",
        barb: "Įkišami vamzdžių jungtys",
        twistLock: "Sukimas išsukimas tipo lašelinės jungtys",
        dripSpikesStep: "Lašelinio vamzdžio laikiklių žingsnio ilgis",
        dripCrossFittingAble: "Kryžminės jungtys",
        pipesNode: "Vamzdžių sekcija",
        hdpeConnectionType: "HDPE vamzdžių jungtys",
        ldpeConnectionType: "LDPE vamzdžių jungtys",
        pvcConnectionType: "PVC vamzdžių jungtys",
        pipeAddon: "Priedai kiekvienam vamzdžių skersmeniui",
        pipeLengthPrecision: "Skaitmenų po kablelio tikslumas vamzdžio ilgiui",
        crossFittingAble: "Kryžminės jungtys",
        compress: "Spaudimo vamzdžių jungtys",
        customfit: "Individualios jungtys",
        slip: "Slip fittings",
        wiringNode: "Elektros laidų sekcija",
        exportNode: "Eksportavimo parinktys",
        exportNumbersPrecision: "Skaitmenų po kablelio tikslumas",
        basicWiringMethod: "Valdymo laidų metodas",
        cableCoresArray: "Laidų skaičiaus intervalas",
        noAutoWiring: "Laidų pridėjimas rankiniu būdu",
        separateCableToManifold: "Atskirkite daugiagyslę laidą į manifoldą",
        separateWireToValve: "Atskirkite laidą į vožtuvą + bendrą laidą į manifoldą",
        maxCableCores: "Daugiagyslių laidų maksimalus skaičius",
        verticalWiringAddon: "Vertikalus laido pridėjimas iki valdiklio",
        verticalSensWiringAddon: "Vertikalus laido pridėjimas iki jutiklio",
        wireAddon: "Laidų priedas kiekvienam tipui",
        wireLengthPrecision: "Skaitmenų po kablelio tikslumas laidų ilgiui",
//DRAWER CONFIG
        drawerConfig: [
            "Projekto konfigūracija"
        ],
        //SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Spreyerys",
        pressureDefinedBy: "Numatomas slėgis spreveryje",
        allowReduceRotors: "Leisti rotorius mažinti spindulį",
        autoconnector: "Interaktyvus purkštuvų prijungimas prie šoninių vamzdžių",
        radio_option_yes: "Taip",
        radio_option_no: "Ne",
        extreme_rotor_reduction: "Ekstremalus (Iki 50%) (Gali sukelti nelygų kritulių pasiskirstymą)",
        radio_option_yes2: "Taip",
        takeReductionInAccountWhenAutoPlacing: "Siūlyti sumažintus metimo atstumus, automatiškai įrengiant purkštukus",
        takeReductionInAccountWhenAutoPlacingForRotors: "Siūlyti sumažintus metimo atstumus, automatiškai įrengiant purkštukus (Rotors)",
        recommendedPressure: "Rekomenduojamas gamintojo",
        userPressure: "Nustatytas vartotojo",
        expPressure: "Numatomas slėgis spreveryje",
        sprinklerGroupMode: "Spreverysių grupavimas",
        safeSprGroupMode: "Griežtas režimas (grupuojami tik suderinami sprev. tipai)",
        unsafeSprGroupMode: "Nesaugus režimas (DĖMESIO! Grupavimo apribojimų nėra!)",
        "sprinklerAttachBulkMode": "Masinio Vartotojų Prijungimo Režimas",
        "safeSprAttachMode": "Neprisijungti iš naujo jau prisijungusiems vartotojams",
        "unsafeSprAttachMode": "Nesaugus režimas (ĮSPĖJIMAS! Galimas jau prisijungusių vartotojų perjungimas. Naudokite savo rizika)",
//UNITS CONFIG
        unitsConfig: "Matavimo vienetai",
        precisionStd: "Skaičių skaičius po kablelio",
        unitsSystemGridAndRuler: "Matavimo vienetų sistema tinkleliui ir linijalui",
        distanceUnits: "Atstumas",
        distancePrecision: "Skaičių skaičius po kablelio",
        sprinklerDistUnits: "Spreveryje skersmuo",
        sprinklerDistPrecision: "Skaičių skaičius po kablelio",
        areaUnits: "Plotas",
        areaPrecision: "Skaičių skaičius po kablelio",
        volumeUnits: "Tūris",
        volumePrecision: "Skaičių skaičius po kablelio",
        waterFlowUnits: "Vandens srautas",
        waterFlowPrecision: "Skaičių skaičius po kablelio",
        pressureUnits: "Slėgis",
        pressurePrecision: "Skaičių skaičius po kablelio",
        velocityUnits: "Greitis",
        velocityPrecision: "Skaičių skaičius po kablelio",
        precipRateUnits: "Kritulių kiekis",
        precipRatePrecision: "Skaičių skaičius po kablelio",
        // ZONE PROPS CONFIG
        climateConfig: "Laistymo laiko skaičiavimas",
        lawnCultureType: "Lauko žolės tipas",
        coolLoving: "Mėgstantis vėsias klimatas",
        warmLoving: "Mėgstantis šiltas klimatas",
        climateTemp: "Vidutinė vasaros temperatūra",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Vidutinis vasaros drėgnumas",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Zonos mikroklimatas <i class='far fa-question-circle'></i>",
        microClimateTooltip: "Švelni\n" +
            "Laistymo zonos, kurios yra šešėlyje, apsaugotos nuo vėjo ir toli nuo sausų ir karštų objektų.\n" +
            "\n" +
            "Normali\n" +
            "Vietos kraštovaizdyje, kuriose mikroklimato sąlygos yra atstovaujamos: pastatų, pėsčiųjų takų ir kelių, šešėlio ir kt. buvimas nereikšmingai veikia garuotuvės reikšmes\n" +
            "\n" +
            "Griežta\n" +
            "Atspindi sąlygas, kurios trukdo augalų augimui ir lengvai verčia augalą stresuotu būsenos, jei augalas netinkamai nėra laistomas." +
            " Tai gali būti atvira vieta, po deginančiu saule, arti takų, pastatų ar kitų kraštovaizdžio struktūrų," +
            " atspindinčių šviesą nuo stiklo ar kraštovaizdžio elementų, kurie sugeria šilumą, arba tai gali būti vėjo vieta.",
        gentleMicroClimate: "Švelni",
        normalMicroClimate: "Normali",
        toughMicroClimate: "Griežta",
        soilType: "Dirvožemio sudėtis zonose",
        sand: "Smėlingas",
        sandyLoam: "Smėlingai molingas",
        lightLoam: "Lengvas molis",
        mediumLoam: "Vidutinis molis",
        heavyLoam: "Sunkus molis",
        clay: "Molis",
        heavyClay: "Sunki molis",
        zoneSlope: "Teritorijų linkių charakteristikos",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Vandens biudžetas",
        lowWB: "Mažas",
        normalWB: "Normalus",
        highWB: "Didelis",
        ft: "pėdos",
        in: "colių",
        ftin: "pėdos/colių",
        metric: "metrinė",
        imperialUS: "imperinė (JAV)",
//UNITS CONFIG
        hydraConfig: "Hidraulika",
        waterTemp: "Vandens temperatūra",
        maxFlowVelocity: "Maksimali srovės greitis vamzdyje",
        "commonConfig": "Bendrosios nuostatos",
        "lateralNozzlerSwitch": "Kaip perjungti į purkštukų tvirtinimo režimą",
        "NStabonly": "Tab",
        "NStabshift": "Tab+Shift",
        "showActionSubtitles": "Rodyti veiksmų subtitrus",
        "Yeah": "Taip",
        "Nope": "Ne",
        start: "Pradėti",
        recalibrate: "Pakalibruoti iš naujo",
        calibrationSuccess: [
            "Sėkmingai sukalibruota",
            "Dabar galite naudoti lietimui jautrų ekraną dvejopai - 'judinti žymeklį' (lengvas prisilietimas ir judėjimas) ir 'tempimo režimas' (stiprus prisilietimas ir judėjimas)"
        ],
        calibrationFailEqual: [
            "Kalibravimas nepavyko",
            "Nepastebėjome didelio skirtumo, kaip lietėte ekraną abiem režimais",
            "Galite bandyti dar kartą. Įsitikinkite, kad naudojate pirštą, o ne rašiklį"
        ],
        calibrationFailImproper: [
            "Kalibravimas nepavyko",
            "Pastebėjome didesnį spaudimą ant plunksnos nei ant priekalo",
            "Galite bandyti dar kartą. Įsitikinkite, kad judinate plunksną lengvesniu spaudimu nei priekalą"
        ],
        calibrationImpossible: [
            "Kalibravimas neįmanomas",
            "Atrodo, kad jūsų įrenginys nepalaiko lietimo ploto matavimo. Todėl negalime apibrėžti dviejų lietimo sąveikos režimų",
            "Šiuo atveju galite naudoti virtualią pelę, kad galėtumėte tempti bet ką. Ji atsiras ekrano kairėje pusėje."
        ],
        calibrationNeeded: [
            "Reikalingas kalibravimas!",
            "Turime pakalibruoti jūsų lietimui jautrų ekraną, kad galėtume apibrėžti du lietimo sąveikos režimus:",
            "Žymeklio judinimo režimas - kai norite tiesiog judinti žymeklį aplink arba perkelti poligono segmentą piešiant",
            "Ir tempimo režimas - tai, kai norite perkelti elementus aplink arba keisti jų dydį. Taip pat turėtumėte naudoti tempimą, kai norite pasirinkti daug daiktų",
            "Prašome paspausti 'Pradėti' mygtuką ir laikytis instrukcijų ekrane"
        ],
        insertImage: 'Įterpti',
        mapImagePicker: [
            "Palydovinės nuotraukos įkėlėjas",
            "Platuma/Ilguma",
            "Įveskite platumą",
            "Įveskite ilgumą",
            "Dabartinė vieta",
            "Eiti",
            "Adresas",
            "Įrašykite dalį adreso ir spustelėkite 'Ieškoti'",
            "Ieškoti",
            "Artinimas",
            "Panoraminis vaizdas"
        ],
        "imageCrop": [
            "Crop tool"
        ],
        cropImage: "Crop",
        invalid_dataset_1: 'Invalid dataset. Project contains prohibited types of surfaces. Only irrigated (LAWN), non-irrigated and obstacles are allowed.',
        invalid_dataset_2: 'Invalid dataset. Not more or less than ONE irrigated surface is allowed.',
        invalid_dataset_3: 'Invalid dataset. Irrigated surface is self-intersected.',
        invalid_dataset_4: 'Invalid dataset. Obstacle marker should not be compound (Made of more than one polygon)',
        invalid_dataset_5: 'Invalid dataset. Obstacle surface should be fully contained within irrigated surface.',
        invalid_dataset_6: 'Invalid dataset. Project contains prohibited types of sprinklers. Allowed:',
        invalid_dataset_7: 'Invalid dataset. Precipitation rate of sprinklers is out of range',
        invalid_dataset_8: 'Invalid dataset. Sprinklers must not have individual pressure settings',
        invalid_dataset_9: 'Invalid dataset. The project should not set a custom expected pressure at the sprinklers',
        invalid_dataset_10: 'Invalid dataset. Uniformity is too low.',
        invalid_dataset_11: 'Invalid dataset. Overwatered area is too big.',
        layoutPresetsMenu: [
            "Išdėstymo išankstiniai nustatymai",
            "Dabartinis išdėstymo išankstinis nustatymas",
            "Išdėstymų rinkinio išankstinis nustatymas",
            "Numatytasis išankstinis nustatymas naujam išdėstymui:",
            "- Pasirinkite išankstinį nustatymą -",
            "- Nėra išankstinių nustatymų -"
        ]
    }
};
