this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "ft/in",
        sqm: "m²",
        acre: "ac",
        hectare: "ha",
        sqft: "vkv.ft",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gal",
        lpm: "lpm",
        lph: "lph",
        m3h: "m³/u",
        USgpm: "gal/u",
        USgph: "gal/u",
        deg: "°",
        pcs: "stuks",
        pcsDot: "stuks.",
        pcsShort: "stuks.",
        percent: "%",
        in_Alt: "in.",
        mps: "m/s",
        kph: "km/u",
        degreesCentigrade: "°C",
        mmph: "mm/u",
        mmp24h: "mm/dag",
        inph: "in/u",
// onomzetbaar
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Automatische tekenaar",
        chooseSprinkler: "Kies sproeier:",
        auto: "Automatisch instellen",
        waterSource2row: ["Water", "Inlaat"],
        setLineLength: "Stel de lijnlengte in (mm):",
        setPressure: "Stel de verwachte dynamische druk in bij de sproeiers (bar):",
        setMaxFlow: "Stel de maximale waterstroom in (l/min):",
        controllerShort: "C",
        sensorShort: "S",
        action_activateEraser: "Activeer gum",
        action_deactivateEraser: "Deactiveer gum",
        action_boolUnite: "Verenigen",
        action_boolIntersect: "Doorsnijden",
        action_boolSubtract: "Aftrekken",
        action_boolExclude: "Uitsluiten",
        action_changeSprayBody: "Stel de sproeier in",
        action_changeVariant: "Stel de variant in",
        action_changeImgVariant: "Stel de variant in",
        action_changeType: "Stel het type in",
        action_addConsumers: "Voeg verbruikers toe",
        action_drawBranches: "Takken toevoegen",
        action_editLine: "Segmenten bewerken",
        action_drawCircles: "Cirkels tekenen",
        action_detachAll: "Alles loskoppelen",
        action_drawBrush: "Penseel tekenen",
        action_editBrush: "Penseel bewerken",
        action_changeBrushSize: "Penseelgrootte",
        action_booleans: "Boolean bewerkingen",
        action_intoPoly: "Omzetten naar veelhoek",
        action_intoBrush: "Omzetten naar penseel",
        action_activateRotation: "Roteer",
        action_deactivateRotation: "Stilstaan",
        action_markZones: "Zone-representatie",
        action_unmarkZones: "Markering verwijderen",
        action_sprNames: "Sproeiernamen",
        action_noSprNames: "Verwijder namen",
        action_lockItem: "Vergrendelen",
        action_unlockItem: "Ontgrendelen",
        Circle: "Cirkel",
        Triangle: "Driehoek",
        BushForm: "Struiken",
        BushForm1: "Struiken 1",
        BushForm2: "Struiken 2",
        BushForm3: "Struiken 3",
        Square: "Vierkant",
        noShadow: "Geen",
        standardShadow: "Standaard",
        noArrows: "Geen",
        startArrow: "Aan het begin",
        endArrow: "Aan het einde",
        bothArrows: "Beide kanten",
        normalSizeSide: "Normaal",
        invertedSizeSide: "Omgekeerd",
        strMiter: "Miter",
        strRound: "Round",
        strBevel: "Bevel",
        strSquare: "Vierkant",
        strButt: "Butt",
        FWnormal: "Normaal",
        FWbold: "Vet",
        FWitalic: "Cursief",
        FWbolditalic: "Vet cursief",
        FJleft: "Links",
        FJright: "Rechts",
        FJcenter: "Midden",
        rzwHeight: "Hoogte"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Selectie",
//----Tekening
        selectPoly: "Geen geselecteerde items",
//----Besproeiing
        selectSprink: "Geen geselecteerde items",
        lpNozzler: "Waterverbruikers aansluiten",
        dl16CircDrawer: "Druppelcirkels leggen 16mm",
        dl16sDrawer: "Druppelafdekking tekenen 16mm",
        dl17CircDrawer: "Druppelcirkels leggen 17mm",
        dl17sDrawer: "Druppelafdekking tekenen 17mm",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Totale afstand",
        type: "Type",
        variant: "Variant",
        area: "Oppervlakte",
        perimeter: "Omtrek",
        curveLength: "Lengte",
        treeDiameter: "Diameter van de boom",
        bushDiameter: "Diameter van de struik",
        nozTypes: "Beschikbare typen",
        nozType: "Type",
        sprBod: "Spray body",
        rad: 'Straal',
        angle: 'Hoek',
        reducedBy: 'Verminderd met',
        consump: 'Verbruik',
        pressure: 'Druk',
        coverSize: 'Dekking',
        maxFlow: 'Maximale waterstroom',
        pipesNum: "Aangesloten leidingen",
        pipeType: "Type",
        pipeLength: "Lengte",
        wireLength: "Lengte",
        valvesManifNum: "Kleppen verdeelstukken",
        valvesNum: "Kleppen",
        propDiam: "Juiste diameter",
        curDiam: "Tekening diameter",
        outsNum: "Waterverbruikers",
        flow: "Waterstroom",
        precipRate: "Neerslag",
        totalPrecipArea: "Totale dekking",
        precipRateShort: "Neerslag",
        coveredArea: "Oppervlakte",
        microClimateInd: "M/Microklimaat",
        soilTypeInd: "B/Grondtype",
        zoneSlopeInd: "Helling",
        maxInfiltrationRate: "Infiltratiesnelheid",
        waterDemand: "Waterbehoefte",
        numOfRuns: "Aantal runs per dag",
        timePerRun: "Tijd per run",
        dailyConsumption: "Dagelijkse consumptie",
        dripsNum: "Aangesloten druppellijnen",
        dripType: "Druppeltype",
        dripRowsStep: "Afstand tussen druppelrijen",
        dripRowsAngle: "Hoek tussen druppelrijen",
        cntrType: "Type controller",
        sensType: "Type sensor",
        zonesNum: "Aantal zones",
        trenchWidth: "Breedte",
        trenchDepth: "Diepte",
        trenchVolume: "Volume",
        insetDiam: "Diameter",
        insetLength: "Lengte",
        insetVar: "Materiaal",
        itemsCount: "Aantal",
        insetDepth: "Diepte",
        zoneName: "Zonenaam",
        valveName: "Klepbox",
        itemAlias: "Alias",
//MULTISELECTOR
        itemsSelected: "Geselecteerd",
        totalArea: "Totale oppervlakte",
        totalPerimeter: "Totale omtrek",
        totalLength: "Totale lengte",
        totalVolume: "Totale volume",
        totalConsumption: "Totale consumptie",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Ongeldige polygon",
        isSelfCrossing_false: "Geldige polygon",
        isConnected_true: "Verbonden",
        isConnected_false: "Niet verbonden",
        isWired_true: "Bedraad",
        isWired_false: "Niet bedraad",
        isDripZone_true: "Druppelzone",
        isDripZone_false: "",
        isSprinklerZone_true: "Sproeizone",
        isSprinklerZone_false: "",
        isOverloaded_true: "OVERBELASTING!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Lage druk",
        isUnderpressured_false: "",
        isOverpressured_true: "Hoge druk",
        isOverpressured_false: "",
        isLocked_true: "Vergrendeld",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "RVS",
        "High speed": "Hoge snelheid",
        "Opposing nozzle": "Tegengestelde sproeier",
        "Plastic": "Kunststof",
        "MPR Nozzles": "MPR sproeiers",
        "Rotary Nozzles": "Roterende sproeiers",
        Nozzles: "Sproeiers",
        "Bubbler nozzles": "Bubbler-sproeiers",
        "Multi-stream": "Meerstraals-sproeiers",
        "Dual-stream": "Dubbelstraals-sproeiers",
        "Stream Nozzles": "Straalsproeiers",
        "Short Radius Nozzles": "Korte straal sproeiers",
        "Pressure compensating": "Drukcompenserend",
        "Adjustable flood": "Verstelbare overstroming",
        Adjustable: "Verstelbaar",
        Fixed: "Vast",
        "Fixed Arc": "Vaste hoek",
        "Strip Pattern": "Strookpatroon",
        "Drip line": "Druppelleiding",
        "Drip cover": "Druppelafdekking",
        "16mm": "16mm",
        "17mm": "17mm",
        "emitter": "Met emitters",
        "noemitter": "Zonder emitters",
        "Root zone watering": "Watergift in de wortelzone",
        Lateral: "Verdeelleiding",
        Main: "Hoofdleiding",
        Trench: "Geultje",
        hdpe: "HDPE",
        pvc: "PVC",
        Controller: "Controller",
        Sensor: "Sensor",
        Wiring: "Bedrading",
        IrrigateMarks: "Zones",
        Surface: "Oppervlak",
        Lawn: "Gazon",
        Bed: "Bed",
        Shrubs: "Struiken",
        Path: "Pad",
        Concrete: "Beton",
        Sand: "Zand",
        Water: "Water",
        Bedding: "Bodemverbeteraar",
        Flower: "Bloemen",
        Herbal: "Kruiden",
        geographic: "Geografisch",
        sizeMark: "Afmetingen",
        scalingBar: "Schaalverdeling",
        loCurves: "Lijnen",
        texts: "Teksten",
        staticText: "Statische tekst",
        dynamicText: "Dynamische tekst",
        stampText: "Stempel tekst",
        stampTextDefault: "Tekst",
        stampTextgr1: "Documentdefinitie",
        stampTextgr2: "Adrescel",
        stampTextgr3: "Locatienaam",
        stampTextgr4: "Tekeningnaam",
        stampTextgr9: "Organisatie-informatie",
        stampTextgr6t: "Fase",
        stampTextgr7t: "Pagina",
        stampTextgr8t: "Pagina's",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Kavel",
        stampTextgr15t: "Neerslag",
        stampTextgr16t: "Pagina",
        stampTextgr17t: "# Doc.",
        stampTextgr18t: "Handt.",
        stampTextgr19t: "Datum",
        stampTextgr20t: "Orig. Inv.#",
        stampTextgr21t: "Ondertekening en datum",
        stampTextgr22t: "Vervangende Inv.#",
        inserts: "Mantelbuis tabel",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Toon lagenbeheer",
        hideLM: "Verberg lagenbeheer",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Naamloos",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Indeling exporteren",
        successExporting: "Succesvol geëxporteerd",
        failExporting: "Kon niet exporteren",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Dagelijkse limiet bereikt</a>",
        exportingLimit: "Limiet: ",
        exportingLeft: "Vandaag over: ",
        pdfExportingPopUpBlocked: "Je browser heeft het pop-upvenster geblokkeerd. Sta pop-ups toe voor deze site om het .PDF-bestand te krijgen",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Pop-up draad",
        tt_group_MT: "Mannelijk",
        tt_group_FT: "Vrouwelijk",
        tt_riserHeight: "Rizer hoogte",
        tt_pressureReg: "Drukmeter",
        tt_checkValve: "(Met terugslagklep)",
        tt_home: "Home",
        tt_prev: "Vorige",
        tt_next: "Volgende",
        tt_end: "Einde",
        tt_add: "Toevoegen",
        tt_clone: "Kloon",
        tt_remove: "Verwijderen",
        tt_rename: "Hernoemen",
        tt_addToFav: "Toevoegen aan favorieten",
        tt_remFromFav: "Verwijderen uit favorieten",
        tt_presets: "Presets"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "N",
        S: "Z",
        E: "O",
        W: "W",
//conventions
        sprinklers: "Sproeiers",
        dripStarts: "Druppelaars start",
        rzwLayer: "Wortelzone irrigatie",
        dripLines: "Druppelleidingen",
        valvesLayer: "Ventielgroep",
        waterSources: "Watervoorziening",
        quickCoupLayer: "Snelkoppeling",
        controllers: "Besturing",
        sensorsLayer: "Sensoren",
        mainPipes: "Hoofdleiding",
        lateralPipes: "Zijleidingen",
        lateralPipes_sprinklerZone: "Zone (Sproeiers)",
        lateralPipes_dripZone: "Zone (Druppelleidingen)",
        lateralPipes_rzwZone: "Zone (Wortelzone irrigatie)",
        lateralPipes_emptyZone: "Zone (Zonder consumenten)",
        trenchesLayer: "Grachten",
        insetsLayer: "Inzetstukken",
        wiresLayer: "Bedrading",
        senswiresLayer: "Sensor Bedrading",
        surfaces: "Oppervlakken",
        ldItemsLayer: "Planten",
        covers: "Bedekkingsgebied",
        nameplates: "Consumenten informatie",
        oreolas: "Consumentenmarkeringen",
        pipeInfo: "Pijpinformatie",
        lines: "Lijnen",
        overlays: "Overlays",
        stampLayer: "Frame",
        stampTexts: "Stempelteksten",
//zonesTable
        zoneType: "Zonetype",
        color: "Kleur",
        consumers: "Verbruikers",
        waterFlow: "Stroom",
        sprinklerZone: "Beregeningszone",
        dripZone: "Druppelzone",
        rzwZone: "Wortelzone-irrigatie",
        emptyZone: "Geen verbruikers",
        specifyDiagonal: "Specificeer uw beeldschermdiagonaal in inches",
//sprinklersTable
        consType: "Type",
        consName: "Naam",
        zoneNum: "Zone",
        sector: "Sector",
        radius: "Straal",
        reducedBy: "Verminderd met",
        nozzle: "Sproeiermondstuk",
        rotor: "Rotor",
        bubbler: "Bubbler",
        bubblerNozzle: "Bubbler-nozzle",
//dripsTable
        catId: "Cat.ID",
        brand: "Merk",
        emitterStep: "Stap",
        emitterFlow: "Stroom",
//layersManangerSpecific
        consumersGrp: "Verbruikers",
        nodesGrp: "Knopen",
        wiresGrp: "Bedrading",
        pipesGrp: "Buizen",
        landscapeGrp: "Landschap",
        allTogether: "Alles"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Type",
        brand: "Merk",
        catid: "Cat.ID",
        title: "Titel",
        units: "Eenheden",
        amount: "Hoeveelheid",
//predetermined
        dripLine: "Druppelslang",
        dl16: "Druppelslang 16mm",
        dl17: "Druppelslang 17mm",
        dripStart: "Druppel start",
        ds16: "Druppel start 16mm",
        ds17: "Druppel start 17mm",
        manifold_no_lps_issue: "Geen zones aangesloten",
        manifold_no_mp_issue: "Niet verbonden met hoofdleiding",
        manifold_no_wr_issue: "Geen besturingsdraad aangesloten",
        //nodes-----------------------------------
        sprinkler_unattached: "WAARSCHUWING!!! U heeft niet-gekoppelde SPRINKLERS (ze worden niet weergegeven in het definitieve specificatieblad)",
        drip_unattached: "WAARSCHUWING!!! U heeft niet-gekoppelde DRUPPELirrigatie-elementen (ze worden niet weergegeven in het definitieve specificatieblad)",
        mains_unattached: "WAARSCHUWING!!! U heeft niet-gekoppelde HOOFDLEIDINGEN (ze worden niet weergegeven in het definitieve specificatieblad)",
        mains_empty: "WAARSCHUWING!!! U heeft HOOFDLEIDINGEN zonder gebruikers (ze worden niet weergegeven in het definitieve specificatieblad)",
        laterals_unattached: "WAARSCHUWING!!! U heeft niet-gekoppelde ZIJLEIDINGEN (ze worden niet weergegeven in het definitieve specificatieblad)",
        laterals_empty: "WAARSCHUWING!!! U heeft ZIJLEIDINGEN zonder gebruikers (ze worden niet weergegeven in het definitieve specificatieblad)",
        rzw_unattached: "WAARSCHUWING!!! U heeft niet-gekoppelde ROOT ZONE WATERING-elementen (ze worden niet weergegeven in het definitieve specificatieblad)",
        sensors_unattached: "WAARSCHUWING!!! U heeft niet-gekoppelde SENSOREN (ze worden niet weergegeven in het definitieve specificatieblad)",
        manifolds_unfinished: "WAARSCHUWING!!! U heeft onvoltooide COLLECTOREN (u kunt de klepconfiguratie niet voltooien)",
        control_wires_unattached: "WAARSCHUWING!!! U heeft niet-verbonden besturingsdraden",
        control_wires_empty: "WAARSCHUWING!!! U heeft BESTURINGSdraden zonder verbonden kleppen",
        cntr_wr_unattached: "Besturingsdraad",
        youCanSeeThemInTheDrawing: "Je kunt elk element op de tekening zien door op het 'oog' aan de linkerkant van de elementrij te klikken",
        sprinkler_nozzleMT: "Sproeierknoop (Sproeikop met vrouwelijke schroefdraad)",
        sprinkler_nozzleFT: "Sproeierknoop (Sproeikop met mannelijke schroefdraad)",
        "sprinkler_rotor1/2F": "Sproeierknoop (Rotor) 1/2\" vrouwelijk",
        "sprinkler_rotor3/4F": "Sproeierknoop (Rotor) 3/4\"",
        "sprinkler_rotor1/2M": "Sproeierknoop (Rotor) 1/2\" mannelijk",
        "sprinkler_bubbler1/2F": "Sproeierknoop (Bubbler)",
        sprinkler_bubblerNozzleMT: "Sproeierknoop (Bubbler sproeikop met vrouwelijke schroefdraad)",
        sprinkler_bubblerNozzleFT: "Sproeierknoop (Bubbler sproeikop met mannelijke schroefdraad)",
        dripIrrigation16: "Druk irrigatie (16mm)",
        dripIrrigation17: "Druk irrigatie (17mm)",
        rootZoneWatering: "Wortelzonebevloeiingssysteem",
        manifold: "Knooppunt van ventielcollector",
        automation: "Automatiseringsknoop",
        mainPipes_hdpePE80SDR11: "Hoofd leidingen HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Hoofd leidingen HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Hoofd leidingen HDPE SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Laterale leidingen HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Laterale leidingen HDPE SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Laterale leidingen HDPE SDR 17.6",
        mainPipes_hdpeSDR9: "Hoofdwaterleidingen HDPE SDR 9",
        mainPipes_hdpeSDR11: "Hoofdwaterleidingen HDPE SDR 11",
        mainPipes_hdpeSDR136: "Hoofdwaterleidingen HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Hoofdwaterleidingen HDPE SDR 17",
        mainPipes_hdpeSDR176: "Hoofdwaterleidingen HDPE SDR 17.6",
        lateralPipes_hdpeSDR9: "Zijdelingse waterleidingen HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Zijdelingse waterleidingen HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Zijdelingse waterleidingen HDPE SDR 13.6",
        lateralPipes_hdpeSDR17: "Zijdelingse waterleidingen HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Zijdelingse waterleidingen HDPE SDR 17.6",
        mainPipes_pvcSCH40: "Hoofdwaterleidingen PVC SCH40",
        mainPipes_pvcSCH80: "Hoofdwaterleidingen PVC SCH80",
        lateralPipes_pvcSCH40: "Zijdelingse waterleidingen PVC SCH40",
        lateralPipes_pvcSCH80: "Zijdelingse waterleidingen PVC SCH80",
        wiring: "Bedrading",
        qcv: "Snelkoppeling kleppen",
        fixedCntr: "vaste",
        stand_aloneCntr: "zelfstandige",
        modularCntr: "modulaire",
        decoderCntr: "decoder",
        inset: "Pijphuls",
        insets: "Pijphulzen",
        //-----------------------------------------
        novar: "geen varianten",
        choosevar: "Kies variant",
        //element.types----------------------------
        nozzle: "Sproeier",
        rotor: "Rotor",
        rotorNozzle: "Rotor sproeier",
        bubbler: "Luchtsproeier",
        bubblerNozzle: "Lucht-sproeier",
        rzw: "Wortelzone irrigatiesysteem",
        sprayBody: "Sproeibody",
        sprinklerStandAssembly: "Sprinkler stand",
        outBarb: "Barb-to-sproeier",
        flexPipe: "Flexibele leiding",
        sj: "Zwenkknie",
        inBarb: "Barb-to-leiding",
        midSprinkPipeFitting: "Koppelstuk",
        endSprinkPipeFitting: "Eindkoppeling",
        midRZWPipeFitting: "Koppelstuk",
        endRZWPipeFitting: "Eindkoppeling",
        dripPipe: "Druppelleiding",
        blindPipe: "Blind leiding",
        dripTeeFitting: "Druppel T-stuk",
        dripCapFitting: "Druppel afsluitdop",
        dripCouplingFitting: "Druppel koppeling",
        dripElbowFitting: "Druppel elleboog",
        dripSpike: "Druppel paal",
        sprinklerZoneValve: "Sproeizone ventiel",
        emptyZoneValve: "Ventiel zonder gebruikers",
        valveOutFitting: "Ventiel-naar-zone",
        dripZoneValve: "Druppelzone ventiel",
        rzwZoneValve: "Wortelzoneventiel",
        pressureReg: "Drukregelaar",
        filter_pressureReg: "Filter met drukregelaar",
        controller: "Besturingssysteem",
        flowMeter: "Doorstroommeter",
        rainSensor: "Regensensor",
        soilSensor: "Bodemvochtigheidssensor",
        freezeSensor: "Vriessensor",
        wrFreezeSensor: "Draadloze regen-/vriessensor",
        windSensor: "Windsensor",
        solarSensor: "Zonlichtsensor",
        flowSensor: "Doorstroomsensor",
        weatherStation: "Weerstation",
        solarPanel: "Zonnepaneel",
        mainPipe: "Hoofdwaterleiding",
        teeFitting: "T-stuk",
        elbowFitting: "Bocht",
        reducerFitting: "Reducer",
        lateralPipe: "Verdeelleiding",
        capFitting: "Afsluitdop",
        basicCable: "Basis kabel",
        basicWire: "Basisdraad",
        sensorCable: "Weersensor kabel",
        qcPlastic: "Snelaansluiting kunststof",
        qcMetal: "Snelaansluiting metaal",
        gateway: "Gateway",
        antExt: "Antenna extension",
        loramod: "LoRa modules",
        //typesOfAcessories
        hdpeCOR: "Golfpijp",
        expModule: "Uitbreidingsmodule",
        rzwSleeve: "Stoffen hoes",
        rwCap: "Herbruikbare waterdichte dop",
        gutterMount: "Dakgootmontage",
        delayRelay: "Vertragingsrelais",
        fctFlow: "FCT opvangbakje met aansluiting",
        fctBspAdap: "Adapter voor FCT fitting",
        drainCheckValve: "Terugslagklep",
        rwId: "Herbruikwater-ID",
        vpc: "Vandalismebestendige dop",
        inletFilter: "Inlaatfilter",
        wifiModule: "Wi-Fi module",
        wallMount: "Wandmontage",
        rwsSock: "Stoffen hoes voor RWS",
        rwsGrate: "RWS-rooster",
        npCover: "Deksel voor niet-drinkbaar water",
        sprExt: "Sproeierverlenging",
        popUpToThread: "Sproeieradapter",
        valveBox: "Klepbox",
        valveBoxExt: "Klepbox-verlenging",
        qcPlasticKey: "Sleutel voor Q/C-klep",
        qcPlasticElbFit: "Elleboogfitting",
        qcMetalKey: "Sleutel voor Q/C-klep",
        qcMetalElbFit: "Elleboogfitting",
        qcMetalCapKey: "Deksel-sleutel",
        insTape: "Isolatietape",
        wrConn: "Connector",
        shrinkTube: "Krimpkous",
        hcFrontPanel: "Frontpaneel",
        ball_valve: "Kogelklep",
        check_valve: "Terugslagklep",
        thread_manifold: "Verzamelaar",
        plastic_filter: "Filter (kunststof)",
        waterMeter: "Watermeter",
        rfModule: "Radio module",
        largeAntenna: "Antenne",
        wifiHub: "WiFi-hub",
        handRemoteKit: "Afstandsbedieningskit",
        handRemote: "Afstandsbediening",
        wifiBundleKit: "WiFi-bundelkit",
        //typesOfFittings
        //drip
        barb_cap_8: "Afsluitdop voor druppelslang",
        barb_elbow_PP: "Kniekoppeling voor druppelslang",
        barb_elbow_PT: "Kniekoppeling voor druppelslang en schroefdraad",
        barb_tee_PPP: "T-koppeling voor druppelslang",
        barb_coupling_PP: "Koppeling voor druppelslang",
        barb_cross_PPPP: "Kruiskoppeling voor druppelslang",
        barb_cap_P: "Afsluitdop voor druppelslang met schroefdraad",
        barb_coupling_PT: "Koppeling voor druppelslang en schroefdraad",
        barb_tee_PTP: "T-koppeling voor druppelslang en schroefdraad",
        barb_valve_PT: "Afsluiter voor druppelslang en schroefdraad",
        barb_valve_PP: "Afsluiter voor druppelslang",
        twlc_elbow_PP: "Twist-lock kniekoppeling voor druppelslang",
        twlc_tee_PPP: "Twist-lock T-koppeling voor druppelslang",
        twlc_coupling_PP: "Twist-lock koppeling voor druppelslang",
        twlc_cross_PPPP: "Twist-lock kruiskoppeling voor druppelslang",
        twlc_cap_P: "Twist-lock afsluitdop voor druppelslang met schroefdraad",
        twlc_coupling_PT: "Twist-lock koppeling voor druppelslang en schroefdraad",
        twlc_tee_PTP: "Twist-lock T-koppeling voor druppelslang en schroefdraad",
        twlc_valve_PT: "Twist-lock afsluiter voor druppelslang en schroefdraad",
        twlc_valve_PP: "Twist-lock afsluiter voor druppelslang",
        dl_valves: "Speciale afsluiters",
        //pipe
        hdpeSDR9: "Buis HDPE SDR 9",
        hdpeSDR11: "Buis HDPE SDR 11",
        hdpeSDR136: "Buis HDPE SDR 13.6",
        hdpeSDR17: "Buis HDPE SDR 17",
        hdpeSDR176: "Buis HDPE SDR 17.6",
        ldpeSDR9: "Buis LDPE SDR 9",
        ldpeSDR11: "Buis LDPE SDR 11",
        ldpeSDR136: "Buis LDPE SDR 13.6",
        ldpeSDR17: "Buis LDPE SDR 17",
        pvcSCH40: "Buis PVC SCH40",
        pvcSCH80: "Buis PVC SCH80",
        compress_elbow_PT: "Compressie/Draad elleboog",
        compress_coupling_PT: "Compressie/Draad koppeling",
        compress_tee_PTP: "Compressie/Draad T-stuk",
        compress_cap_P: "Compressie eindplug",
        compress_elbow_PP: "Compressie elleboog",
        compress_coupling_PP: "Compressie koppeling",
        compress_tee_PPP: "Compressie T-stuk",
        compress_cross_PPPP: "Compressie kruis",
        compress_single_clamp_saddle: "Eenklems zadel",
        compress_ballvalve_PP: "Compressie Kogelkraan",
        compress_ballvalve_PT: "Compressie/Draad Kogelafsluiter",
        customfit_elbow_PT: "Op maat gemaakte draaibare knie",
        customfit_coupling_PT: "Op maat gemaakte draaibare koppeling",
        customfit_tee_PTP: "Op maat gemaakte T-stuk met draad",
        customfit_cap_P: "Op maat gemaakte einddop",
        customfit_elbow_PP: "Op maat gemaakte knie",
        customfit_coupling_PP: "Op maat gemaakte koppeling",
        customfit_tee_PPP: "Op maat gemaakte T-stuk",
        customfit_cross_PPPP: "Op maat gemaakte kruisstuk",
        customfit_single_clamp_saddle: "Enkelvoudige klemzadel",
        customfit_ballvalve_PP: "Op maat gemaakte kogelkraan",
        customfit_ballvalve_PT: "Op maat gemaakte draaibare kogelkraan",
        thread_nipple: "Nippel",
        thread_coupling: "Koppeling",
        thread_mf_reducer: "Mannetje/Vrouwtje verloopstuk",
        thread_mf_adapter: "Mannetje/Vrouwtje adapter",
        thread_mf_bush: "Mannetje/Vrouwtje verloop",
        thread_tee: "Vrouwelijke T-stuk",
        thread_elbow: "Vrouwelijke elleboog",
        thread_mf_elbow: "Mannetje/Vrouwtje elleboog",
        thread_cap: "Vrouwelijke afsluitkap",
        thread_plug: "Mannelijke afsluitplug",
        thread_union_nut: "Unie moer",
        thread_cross: "Kruisstuk",
        cable: "Kabel",
        wire: "Draad",
        // slip
        slip_single_clamp_saddle: "Enkelvoudige klemschelp (op PVC buis)",
        slip_elbow_PT: "Lijm/draad elleboog",
        slip_coupling_PT: "Lijm/draad koppeling",
        slip_tee_PTP: "Lijm/draad T-stuk",
        slip_cap_P: "Lijm afsluitdop",
        slip_elbow_PP: "Lijm elleboog",
        slip_coupling_PP: "Lijm koppeling",
        slip_tee_PPP: "Lijm T-stuk",
        slip_cross_PPPP: "Lijm kruisstuk",
        slip_ballvalve_PP: "Lijm kogelkraan",
        slip_ballvalve_PT: "Lijm/draad kogelkraan",
//extendables
        arbitraryFittings: "Willekeurige hulpstukken",
        dripStartAssembly: "Druppel start montage",
        intakeAssembly: "Inlaat montage",
        offtakeAssembly: "Aftak hulpstukken",
        numofvalves: "Aantal kleppen: ",
        numofvalvesshort: "Kleppen: ",
        numofmanifs: "Aantal verdeelstukken: ",
        intakePipeSize: "Inlaatpijpdiameter: ",
        valveBoxes: "Klep dozen",
        valveAccessories: "Klep accessoires",
        oneValveAccessories: "Klep accessoires",
        controllerAccessories: "Besturingsaccessoires",
        sensorAccessories: "Sensor accessoires",
        sprBodyAccessories: "Sproeier accessoires",
        rzwAccessories: "Root zone watering accessoires",
        pipeStartFittings: "Hulpstukken voor hoofdbuizen",
        qcAccessories: "Q/C klep accessoires",
        wiringAccessories: "Bekabelingsaccessoires",
        pipeSize: "Pijpdiameter: ",
        endOfPipe: "(Einde positie)",
        midOfPipe: "(Doorkoppeling)",
        emptyRender: [
            "Sorry... geen inhoud geparsed",
            "U hebt geen van de irrigatieknopen volledig ingevuld om te worden weergegeven"
        ],
        serviceFail: [
            "Sorry... specificatieservice voor rendering is momenteel niet bereikbaar",
            "Probeer het later opnieuw, wanneer de verbinding is hersteld",
            "Houd er rekening mee dat de configuratie die u eerder hebt gemaakt, wel wordt opgeslagen"
        ],
        serviceTrialExpired: [
            "Sorry... specificatieservice voor rendering is niet beschikbaar voor uw account",
            "Dat betekent dat uw proefperiode voorbij is en als u deze service wilt gebruiken",
            "<a href='/account/subscription'>kunt u upgraden naar een PRO-account</a>"
        ],
        serviceLimitReached: [
            "U hebt het dagelijkse limiet voor het renderen van productspecificaties bereikt",
            "Om het limiet voor het aantal specificaties dat u per dag kunt renderen te verwijderen,",
            "<a href='/account/subscription'>kunt u upgraden naar een PRO-account</a>"
        ],
        findInDrawing: "Weergeven op canvas",
// GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Leidingen",
        labours_group_fittings: "Fittingen",
        labours_group_valveBoxes: "Afsluiterkasten",
        labours_group_wires: "Bedrading",
        labours_group_sprinklers: "Sproeiers",
        labours_group_rws: "Wortelzone irrigatie",
        labours_group_sprinklerConnections: "Sproeier aansluitingen",
        labours_group_drip: "Drukleidingen en fittingen",
        labours_group_manifolds: "Verzamelkasten",
        labours_group_quickCoupling: "Snelkoppeling",
        labours_group_controllers: "Besturingsunits",
        labours_group_sensors: "Sensoren",
        labours_group_trenches: "Sleuven",
        labours_group_insets: "Leidingdoorvoeren",
        labours_group_lawns: "Gras",
        labours_group_irrigatedArea: "Geïrrigeerd gebied",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "Januari", "Februari", "Maart", "April", "Mei", "Juni", "Juli", "Augustus", "September", "Oktober", "November", "December"],
        MMM: ["\x01", "Jan", "Feb", "Mrt", "Apr", "Mei", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dec"],
        dddd: ["\x02", "Zondag", "Maandag", "Dinsdag", "Woensdag", "Donderdag", "Vrijdag", "Zaterdag"],
        ddd: ["\x03", "Zo", "Ma", "Di", "Wo", "Do", "Vr", "Za"],
//buttonsCaps
        ok: "Ok",
        save: "Opslaan",
        apply: "Toepassen",
        defaults: "Standaardinstellingen",
        retry: "Opnieuw proberen",
        finish: "Voltooien",
        safeRestart: "Veilige herstart",
        saveAndExit: "Opslaan en afsluiten",
        exit: "Afsluiten",
        cancel: "Annuleren",
        rename: "Hernoemen",
        idk: "Ik weet het niet",
        getFile: "Bestand ophalen",
        reset: "Resetten",
        random: "Willekeurig",
        //misc
        zoneNum: "Zone #",
        valveNum: "Klepbox #",
        zonesColoring: "Zones weergave",
        coversColoured: "Sproeiers afdekking schilderen",
        dripsColoring: "Kleuring van druppellijnen",
        dripsSameAsZonesColored: "Druppellijn gekleurd in dezelfde kleur als de zone",
        //saveOflline
        saveOffline: [
            "Sorry... de verbinding is verbroken",
            "Maar geen zorgen, je kunt doorgaan met je project in offline modus.",
            "Terwijl je offline bent, worden al je opgeslagen bestanden opgeslagen als tekstbestand in de downloadmap van je browser.",
            "En later kun je de nieuwste versie van je tekening op de server uploaden."
        ],
        restartOffline: [
            "Sorry... de verbinding is verbroken",
            "Maar geen zorgen, je project is lokaal op je computer opgeslagen.",
            "Je kunt het vinden in de downloadmap van je browser.",
            "Als je offline wilt werken, kun je een Offline Versie van de applicatie downloaden vanuit je account op http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Sorry... er is iets misgegaan bij het opslaan van je project",
            "Het lijkt erop dat je vorige opslagbestand op de een of andere manier is beschadigd.",
            "Maar geen zorgen, we kunnen het repareren.",
            "Je project wordt nu gemarkeerd als 'Defect' in je werkplaats.",
            "En ons technische team zal deze situatie zo snel mogelijk oplossen."
        ],
        corruptedSavingFile: [
            "Sorry... het bestand dat je probeert te opslaan is niet leesbaar",
            "Maar geen zorgen, we kunnen het repareren.",
            "Het enige wat je hoeft te doen is dit defecte bestand indienen in het formulier voor het opslaan van bestanden in je werkplaats.",
            "En dan zullen we proberen om het weer aan het werk te krijgen."
        ],
        ajaxReqFail: [
            "Sorry... We hebben de verbinding met de server verloren",
            "Het is momenteel onmogelijk om gegevens te verzenden/ontvangen",
            "Probeer het later opnieuw"
        ],
        critical: [
            "Sorry... er is iets misgegaan",
            "Maar maak je geen zorgen, je tekening is nu veilig opgeslagen, klik gewoon op de veilige herstartknop om verder te gaan..."
        ],
        fatal: [
            "Sorry... er is iets misgegaan",
            "Help ons onze service beter te maken. Beschrijf na welke gebruikersacties deze fout optrad",
            "Geef hier informatie"
        ],
        areYouSure: [
            "Je staat op het punt dit project te sluiten",
            "Houd er rekening mee dat alle niet-opgeslagen wijzigingen verloren gaan."
        ],
        pickAnotherCSVFile: "Kies een ander bestand",
        csvFileTooBig: [
            "Maximum csv-bestandsgrootte overschreden",
            "Voor optimalisatiedoeleinden is de maximale csv-bestandsgrootte beperkt tot 4 MB"
        ],
        notAnCSV: [
            "Sorry, dit bestandstype wordt niet ondersteund",
            "Ondersteunde formaten: .csv"
        ],
        pickAnotherImage: "Kies een andere afbeelding",
        imageTooBig: [
            "Maximum bestandsgrootte afbeelding overschreden",
            "Voor optimalisatiedoeleinden is de maximale grootte van afbeeldingen beperkt tot 10 MB"
        ],
        notAnImage: [
            "Sorry, dit bestandstype wordt niet ondersteund",
            "Ondersteunde afbeeldingsformaten: .pdf, .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "BEWEGING BEPERKT",
            "Deze actie is niet toegestaan voor een GRATIS abonnement"
        ],
        goPro: 'WORD PRO',
        renameLayout: "Voer een nieuwe naam in",
        areYouSureDeleteLayout: [
            "Let op! Deze actie kan niet ongedaan worden gemaakt",
            "Weet u zeker dat u wilt verwijderen: ",
            "Verwijderen"
        ],
        setUnderlaySize: [
            "Stel de lengte in van de lijn die u zojuist hebt getekend",
            "U heeft een onjuiste waarde ingevoerd. Probeer het opnieuw"
        ],
        setMonitorDiagonal: [
            "Geef ons informatie over de diagonale grootte van uw monitor",
            "U heeft een onjuiste waarde ingevoerd. Probeer het opnieuw"
        ],
        getSpecsTable: [
            "Stel de voorkeuren voor specificatie-uitvoer in",
            "Apparatuur groeperen op",
            "Node", "Merk",
            "Stel bestandstype in als",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Voer titel in",
            "Indeling #",
            "Opslaan",
            "Specificaties opslaan",
            "Voltooid. Klik hier om te openen",
            "Opslaan mislukt",
            "Bestaande indelingen bijwerken",
            "Bijwerken",
            "Indelingen bijwerken"
        ],
        exportLayoutsAsPdf: [
            "Kies indelingen om te exporteren",
            "afzonderlijke bestanden (in ontwikkeling)",
            "één album",
            "Exporteren",
            "Indelingen exporteren in"
        ],
        differentSprGroups: [
            "Kan verschillende typen watergebruikers niet aan deze buis bevestigen",
            "Volgens de ontwerpnormen voor irrigatie is het niet toegestaan om verschillende typen watergebruikers of sproeiers met verschillende neerslaghoeveelheden in dezelfde zone te mixen"
        ],
        tooFarAwaySpr: [
            "Kan gebruikers niet aansluiten",
            "Sommige gebruikers zijn te ver verwijderd van laterale buis om te kunnen worden aangesloten. Maximale verbindingsafstand die u in het voorkeurenmenu kunt configureren"
        ],
        outlayerConfig: [
            "Configuratie van specificatieblad"
        ],
        presetsMenu: {
            title: "Opgeslagen instellingen",
            titleTextboxLabel: "Titel van voorinstelling",
            descriptionTextboxLabel: "Beschrijving",
            applyButton: "<i class='far fa-check-circle'></i> Toepassen",
            defaultButton: "<i class='far fa-undo'></i> Standaard instellen",
            removeButton: "<i class='far fa-trash'></i> Verwijderen",
            updateButton: "<i class='far fa-sync'></i> Updaten",
            createButton: "<i class='far fa-plus'></i> Nieuwe aanmaken",
            closeButton: "<i class='far fa-times'></i> Sluiten",
            favorites_drawing: "Favoriete gereedschappen (Landschap)",
            favorites_sprinkling: "Favoriete gereedschappen (Irrigatie)",
            favorites_layouting: "Favoriete gereedschappen (Indelingen)",
            configs_drawing: "Projectconfiguratie",
            configs_outlayer: "Configuratie van specificatieblad",
        },
        newPresetItem: "Nieuwe voorinstelling",
        cL_alreadyConnected: [
            "Het samenvoegen van lijnen is mislukt",
            "Deze lijnen zijn al verbonden met"
        ],
        cL_segOnElem: [
            "Niet gelukt om lijnen samen te voegen",
            "Je kunt geen verbinding maken met een segment dat op"
        ],
        cL_strangeError: [
            "Niet gelukt om lijnen samen te voegen",
            "Sorry...verbindingsfout"
        ],
        cL_misgrouping: [
            "Niet gelukt om lijnen samen te voegen",
            "Deze lijnen hebben consumenten die niet aanbevolen zijn om in dezelfde zone te plaatsen. Als je ze toch wilt verbinden, schakel dan de 'Onveilige modus' in voor Groepering sprinklers in de projectconfiguratie"
        ],
        cL_valve: "Ventiel verzamelaar",
        cL_waterSource: "Watervoorziening",
        cL_dripStart: "Drip start",
        cL_controller: "Controller",
        cL_sensors: "Sensor",
        cL_valves: "Ventiel verzamelaar",
        cL_notSameVariant: [
            "Niet gelukt om lijnen samen te voegen",
            "Deze lijnen hebben verschillende typen",
            "Type van de momenteel getekende lijn",
            "Type van de lijn waarmee je wilt verbinden"
        ],
        hasRestorableProject: [
            "Je hebt niet-opgeslagen gegevens voor dit project",
            "Je kunt de niet-opgeslagen staat herstellen van een snapshot genomen op"
        ],
        restoreProject: "Herstellen",
        imageLost: [
            "Sorry, we kunnen sommige onderliggende afbeeldingen niet vinden op de server",
            "Deze afbeelding is niet gevonden:"
        ],
        cannotSaveBecauseOffline: [
            "Kan verzoek niet naar server verzenden",
            "Geen verbinding met de server",
            "Controleer of u een internetverbinding heeft",
            "Om geen gegevens te verliezen, sluit dit venster niet en probeer de gegevens later opnieuw op te slaan, wanneer de verbinding met de server is hersteld",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Verzoek kan niet worden opgeslagen",
            "Te veel ongeldige code-pogingen",
            "Controleer of u het e-mailadres correct hebt ingevoerd en probeer het opnieuw na 30 seconden.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Verzoek kan niet worden opgeslagen",
            "E-mailadres verkeerd ingevoerd",
            "Controleer of u het e-mailadres correct hebt ingevoerd en probeer het opnieuw",
            "",
            "",
        ],
        designRequestCompleted: [
            "Uw verzoek is succesvol aangemaakt/bijgewerkt",
            "Bewerkingslink", "kopieer mij",
            "Link om te bekijken", "kopieer mij",
        ],
        designRequestContacts: [
            "Contact information",
            "Organization",
            "Name",
            "Email",
            "Phone",
            "Address",
            "Website",
        ],
        approveActionByCode: [
            "Bevestig actie",
            "Er is een e-mail met een bevestigingscode naar het door u opgegeven e-mailadres verzonden.",
            "Voer deze code in het veld hieronder in",
            "U heeft een ongeldig nummer ingevoerd, probeer het opnieuw"
        ],
        filterSelection_exclude: "Uitsluiten van selectie",
        filterSelection_include: "Toevoegen aan selectie",
        filterSelectionNames: {
            sprinklers: "Watergevers",
            sprinklers_nozzle: "Watergevers - Nozzles",
            sprinklers_rotaryNozzle: "Watergevers - Roterende Nozzles",
            sprinklers_rotor: "Watergevers - Rotors",
            sprinklers_bubbler: "Watergevers - Bubbler",
            sprinklers_bubblerNozzle: "Watergevers - Bubbler-nozzles",
            dripStarts: "Drip startpunten",
            rzwLayer: "Root zone watering",
            dripLines: "Druppelleidingen",
            valvesLayer: "Afsluiters",
            waterSources: "Watervoorzieningen",
            controllers: "Besturingen",
            sensorsLayer: "Sensoren",
            mainPipes: "Hoofdleidingen",
            lateralPipes: "Laterale leidingen",
            trenchesLayer: "Trenches",
            insetsLayer: "Pipe sleeves",
            wiresLayer: "Bedrading",
            senswiresLayer: "Sensor bedrading",
            quickCoupLayer: "Snelkoppelingen",
            surfaces: "Polygoon en lijnen",
            ldItemsLayer: "Objecten"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Sproeierknoop",
        fcType: "Type van verbinding",
        sj: "Zwenkverbinding",
        flexPipeBarbs: "Flexibele buis + barbs",
        minFlexPipeLength: "Minimale lengte van flexibele buis per verbinding",
        midSprinkPipeFitting: "Verbindingsfitting",
        endSprinkPipeFitting: "Eindbuisfitting",
        single_clamp_saddle: "Klemzadel",
        tee_PTP: "T-stuk met vrouwelijke BSP-draad",
        elbow_PT: "Bocht met vrouwelijke BSP-draad",
        coupling_PT: "Adapter met vrouwelijke BSP-draad",
        //MANIFOLD NODE CONFIGS
        manifoldNode: "Verzamelnodes",
        valvesOutlay: "Klepuitlaat",
        fold: "Opgevouwen",
        unfold: "Uitgevouwen",
        threadsNode: "Geschroefde verbindingen",
        threadTypes: "Draadtypen",
        //AUTOMATION NODE CONFIGS
        automationNode: "Automatiseringsknoop",
        controllerModules: "Uitbreidingsmodules voor modulaire controllers zijn gekozen:",
        controllerVoltage: "Ingangsspanning van de controller:",
        230: "230 VAC",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automatisch (beste pasvorm)",
        userModules: "Handmatig (als accessoires)",
//RZW NODE
        rzwNode: "Beregening van wortelzone knooppunt",
        midRZWPipeFitting: "Verbinding tussenstuk",
        endRZWPipeFitting: "Eindpijp verbinding",
//DRIP node
        dripNode: "Druppelirrigatie",
        dripConnectionType: "Druppelkoppeling type",
        dripLengthPrecision: "Cijfers na de decimale punt in buislengte",
        dripTubingAddon: "Druppelslang toevoeging",
        barb: "Met ribbels verbonden koppelingen",
        twistLock: "Druk draaikoppelingen",
        dripSpikesStep: "Stap van de druppellijn houder spikes",
        dripCrossFittingAble: "Kruiskoppeling in staat",
        pipesNode: "Pijpleidingsectie",
        hdpeConnectionType: "HDPE-koppelingstype",
        pvcConnectionType: "PVC-koppelingstype",
        pipeAddon: "Pijptoename voor elke diameter",
        pipeLengthPrecision: "Cijfers na de decimale punt in lengte van de pijp",
        crossFittingAble: "Kruiskoppeling in staat",
        compress: "Compressie koppelingen",
        customfit: "Op maat gemaakte koppelingen",
        wiringNode: "Bedradingsectie",
        exportNode: "Exportopties",
        exportNumbersPrecision: "Cijfers na de decimale punt in nummers",
        basicWiringMethod: "Besturingsbedrading methode",
        cableCoresArray: "Aantal kabelkernen",
        noAutoWiring: "Bedrading handmatig toevoegen",
        separateCableToManifold: "Scheid meerkernige kabel naar verzamelleiding",
        separateWireToValve: "Scheid draad van klep + gemeenschappelijke draad naar verzamelleiding",
        maxCableCores: "Maximaal aantal kabelkernen",
        verticalWiringAddon: "Verticale toevoeging aan controllerdraad",
        verticalSensWiringAddon: "Verticale toevoeging aan sensor draad",
        wireAddon: "Draadtoevoeging voor elk type",
        wireLengthPrecision: "Cijfers achter de komma in de lengte van de bedrading",
//DRAWER CONFIG
        drawerConfig: [
            "Projectconfiguratie"
        ],
//SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Verbruikers",
        pressureDefinedBy: "Verwachte druk bij de verbruikers is",
        allowReduceRotors: "Verkorting van de rotorradius toestaan",
        radio_option_yes: "Ja",
        radio_option_no: "Nee",
        recommendedPressure: "Aanbevolen door fabrikant",
        userPressure: "Ingesteld door de gebruiker",
        expPressure: "Verwachte druk bij de verbruiker",
        sprinklerGroupMode: "Groepering van verbruikers",
        safeSprGroupMode: "Strikte modus (Alleen compitabiele verbruikers groeperen)",
        unsafeSprGroupMode: "Onveilige modus (WAARSCHUWING! Geen groeperingsbeperkingen)",
//UNITS CONFIG
        unitsConfig: "Maat eenheden",
        precisionStd: "Cijfers na de komma",
        unitsSystemGridAndRuler: "Maatsysteem voor raster en liniaal",
        distanceUnits: "Afstand",
        distancePrecision: "Cijfers na de komma",
        sprinklerDistUnits: "Straal van sprinkler",
        sprinklerDistPrecision: "Cijfers na de komma",
        areaUnits: "Oppervlakte",
        areaPrecision: "Cijfers na de komma",
        volumeUnits: "Volume",
        volumePrecision: "Cijfers na de komma",
        waterFlowUnits: "Waterdebiet",
        waterFlowPrecision: "Cijfers na de komma",
        pressureUnits: "Druk",
        pressurePrecision: "Cijfers na de komma",
        velocityUnits: "Snelheid",
        velocityPrecision: "Cijfers na de komma",
        precipRateUnits: "Neerslaghoeveelheid",
        precipRatePrecision: "Cijfers na de komma",
// ZONE PROPS CONFIG
        climateConfig: "Berekening van irrigatietijd",
        lawnCultureType: "Grastype",
        coolLoving: "Vorstbestendig",
        warmLoving: "Warmteminnend",
        climateTemp: "Gemiddelde zomertemperatuur",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Gemiddelde zomerluchtvochtigheid",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Microklimaat van zone <i class='far fa-question-circle'></i>",
        microClimateTooltip: "Mild\n" +
            "Irrigatiegebieden die in de schaduw zijn, beschermd zijn tegen wind en zich op afstand bevinden van droge en verwarmde objecten\n" +
            "\n" +
            "Normaal\n" +
            "Plaatsen in het landschap waar microklimaat omstandigheden worden vertegenwoordigd: de aanwezigheid van\n" +
            "gebouwen, trottoirs en paden, schaduw, enz. hebben geen significant effect op de waarden van\n" +
            "evapotranspiratie\n" +
            "\n" +
            "Hard\n" +
            "Weerspiegelt omstandigheden die plantengroei belemmeren en gemakkelijk leiden tot een gestreste staat als de plant niet goed bewaterd wordt. Dit kan een open plek zijn, onder een brandende zon, in de nabijheid van paden, gebouwen of andere landschapsstructuren, weerspiegelt licht van glas of landschapselementen die warmte absorberen, of het kan een winderige plek zijn.",
        gentleMicroClimate: "Mild",
        normalMicroClimate: "Normaal",
        toughMicroClimate: "Hard",
        soilType: "Bodem samenstelling van de zones",
        sand: "Zand",
        sandyLoam: "Zandleem",
        lightLoam: "Lichte leem",
        mediumLoam: "Medium leem",
        heavyLoam: "Zware leem",
        clay: "Klei",
        heavyClay: "Zware klei",
        zoneSlope: "Algemene helling van de zones",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Waterbudget",
        lowWB: "Laag",
        normalWB: "Normaal",
        highWB: "Hoog",
        ft: "voet",
        in: "inch",
        ftin: "voet/inches",
        metric: "metrisch",
        imperialUS: "imperiaal (VS)",
//UNITS CONFIG
        hydraConfig: "Hydrauliek",
        waterTemp: "Watertemperatuur",
        maxFlowVelocity: "Maximale stroomsnelheid in leiding"
    }
};

