this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "stopy/cale",
        sqm: "m²",
        acre: "akr",
        hectare: "hektar",
        sqft: "ft²",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gal. US",
        lpm: "l/min",
        lph: "l/godz",
        m3h: "m³/h",
        USgpm: "gal. US/min",
        USgph: "gal. US/godz",
        deg: "°",
        pcs: "szt.",
        pcsDot: "szt.",
        pcsShort: "szt.",
        percent: "%",
        in_Alt: "cal",
        mps: "m/s",
        kph: "km/h",
        ftps: "ft/s",
        degreesCentigrade: "stopnie Celsiusza",
        mmph: "mm/h",
        mmp24h: "mm/dzień",
        inph: "cal/h",
        // unconvertable
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Automatyczny rysownik",
        chooseSprinkler: "Wybierz dyszę:",
        auto: "Automatycznie",
        waterSource2row: ["Źródło", "Wlot"],
        setLineLength: "Ustawić długość linii (mm):",
        setPressure: "Ustawić oczekiwanie ciśnienie dynamiczne na dyszach (bar):",
        setMaxFlow: "Ustawić maksymalny przepływ wody (l/min):",
        controllerShort: "S",
        sensorShort: "S",
        action_activateEraser: "Aktywuj gumkę",
        action_deactivateEraser: "Dezaktywuj gumkę",
        action_boolUnite: "Połącz",
        action_boolIntersect: "Przecinają się",
        action_boolSubtract: "Odejmij",
        action_boolExclude: "Wyłącz",
        action_changeSprayBody: "Ustawić rozprysk",
        action_changeVariant: "Ustawić wariant",
        action_changeImgVariant: "Ustawić wariant",
        action_changeType: "Ustawić typ",
        action_addConsumers: "Dodaj konsumentów",
        action_drawBranches: "Dodaj gałęzie",
        action_editLine: "Edytuj segmenty",
        action_drawCircles: "Rysuj okręgi",
        action_detachAll: "Odczep wszystko",
        action_drawBrush: "Rysuj pędzelkiem",
        action_editBrush: "Edytuj pędzel",
        action_changeBrushSize: "Rozmiar pędzla",
        action_booleans: "Operacje logiczne",
        action_intoPoly: "Przekształć w wielokąt",
        action_intoBrush: "Przekształć w pędzel",
        action_activateRotation: "Obróć",
        action_deactivateRotation: "Bez obrotu",
        action_markZones: "Reprezentacja stref",
        action_unmarkZones: "Usuń oznaczenie",
        action_sprNames: "Nazwy spryskiwaczy",
        action_noSprNames: "Usuń nazwy",
        action_lockItem: "Zablokuj",
        action_unlockItem: "Odblokuj",
        Circle: "Koło",
        Triangle: "Trójkąt",
        BushForm: "Krzewy",
        BushForm1: "Krzewy 1",
        BushForm2: "Krzewy 2",
        BushForm3: "Krzewy 3",
        Square: "Kwadrat",
        noShadow: "Brak cienia",
        standardShadow: "Standardowy cień",
        noArrows: "Brak strzałek",
        startArrow: "Na początku",
        endArrow: "Na końcu",
        bothArrows: "Obie strony",
        normalSizeSide: "Normalny",
        invertedSizeSide: "Odwrócony",
        strMiter: "Ostrokatny",
        strRound: "Okrągły",
        strBevel: "Fazowany",
        strSquare: "Kwadratowy",
        strButt: "Prosty",
        FWnormal: "Normalny",
        FWbold: "Pogrubiony",
        FWitalic: "Kursywa",
        FWbolditalic: "Pogrubiona kursywa",
        FJleft: "Do lewej",
        FJright: "Do prawej",
        FJcenter: "Do środka",
        rzwHeight: "Wysokość"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Selektor",
//----Rysowanie
        selectPoly: "Brak zaznaczonych elementów",
//----Nawadnianie
        selectSprink: "Brak zaznaczonych elementów",
        lpNozzler: "Przyłączanie konsumentów wody",
        dl16CircDrawer: "Rysowanie okręgów kropli 16/13mm",
        dl16sDrawer: "Rysowanie osłonki kropli 16/13mm",
        dl17CircDrawer: "Rysowanie okręgów kropli 17mm",
        dl17sDrawer: "Rysowanie osłonki kropli 17mm",
        "ldTextDrawer": "Konfiguracja tekstu",
        "staticTextDrawer": "Konfiguracja tekstu",
        "dynamicTextDrawer": "Konfiguracja tekstu",
        "ldStaticTextDrawer": "Konfiguracja tekstu",
        "ldtextEditor": "Edycja tekstu",
//------------------------------------------------------------
//-------------------WARTOŚCI-----------------------------------
//------------------------------------------------------------
//Wartości
        rulerLength: "Całkowita odległość",
        type: "Typ",
        variant: "Wariant",
        area: "Powierzchnia",
        perimeter: "Obwód",
        curveLength: "Długość",
        treeDiameter: "Średnica drzewa",
        bushDiameter: "Średnica krzewu",
        nozTypes: "Dostępne typy",
        nozType: "Typ",
        sprBod: "Korpus rozpylający",
        rad: 'Promień',
        angle: 'Kąt',
        reducedBy: 'Zmniejszone o',
        consump: 'Zużycie',
        pressure: 'Ciśnienie',
        coverSize: 'Pokrycie',
        maxFlow: 'Maksymalny przepływ wody',
        pipesNum: "Podłączone rury",
        pipeType: "Typ",
        pipeLength: "Długość",
        wireLength: "Długość",
        valvesManifNum: "Manifoldy zaworów",
        valvesNum: "Zawory",
        propDiam: "Średnica właściwa",
        curDiam: "Średnica rysowania",
        outsNum: "Konsumentów wody",
        flow: "Przepływ wody",
        precipRate: "Wskaźnik opadów",
        totalPrecipArea: "Całkowite pokrycie",
        uniformity: "Jednolitość (CU)",
        overwatered: "Przesadzone",
        precipRateShort: "Opad.",
        runtimeInd: "Czas pracy",
        coveredArea: "Powierzchnia",
        microClimateInd: "M/Klimat",
        soilTypeInd: "Typ gleby",
        zoneSlopeInd: "Nachylenie",
        maxInfiltrationRate: "Wskaźnik infiltracji",
        waterDemand: "Zapotrzebowanie na wodę",
        numOfRuns: "Cykle na dobę",
        timePerRun: "Czas trwania cyklu",
        dailyConsumption: "Dzienne zużycie",
        dripsNum: "Podłączone linie kroplujące",
        dripType: "Typ kroplowania",
        dripRowsStep: "Krok rzędów na powierzchni",
        dripRowsAngle: "Kąt rzędów na powierzchni",
        cntrType: "Typ sterownika",
        sensType: "Typ czujnika",
        zonesNum: "Kontrolowane strefy",
        trenchWidth: "Szerokość",
        trenchDepth: "Głębokość",
        trenchVolume: "Objętość",
        insetDiam: "Średnica",
        insetLength: "Długość",
        insetVar: "Materiał",
        itemsCount: "Liczba",
        insetDepth: "Głębokość",
        zoneName: "Nazwa strefy",
        valveName: "Skrzynka zaworowa",
        itemAlias: "Alias",
//MULTISELECTOR
        itemsSelected: "Wybrane",
        totalArea: "Całkowita powierzchnia",
        totalPerimeter: "Razem obwód",
        totalLength: "Całkowita długość",
        totalVolume: "Całkowita objętość",
        totalConsumption: "Całkowite zużycie",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Nieprawidłowy wielokąt",
        isSelfCrossing_false: "Prawidłowy wielokąt",
        isConnected_true: "Połączony",
        isConnected_false: "Niepołączony",
        isWired_true: "Podłączony",
        isWired_false: "Niepodłączony",
        isDripZone_true: "Strefa kroplująca",
        isDripZone_false: "",
        isSprinklerZone_true: "Strefa rozpylająca",
        isSprinklerZone_false: "",
        isOverloaded_true: "PRZECIĄŻENIE!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Niskie ciśnienie",
        isUnderpressured_false: "",
        isOverpressured_true: "Wysokie ciśnienie",
        isOverpressured_false: "",
        isLocked_true: "Zablokowany",
        isLocked_false: "",
//------------------------------------------------------------
//-------------------KLASY, SERIE, PODSERIE itp.---------------
//------------------------------------------------------------
        "Stainless steel": "Stal nierdzewna",
        "High speed": "Wysoka prędkość",
        "Opposing nozzle": "Dysza przeciwna",
        "Plastic": "Plastik",
        "MPR Nozzles": "Dysze MPR",
        "Rotary Nozzles": "Dysze obrotowe",
        Nozzles: "Dysze",
        "Bubbler nozzles": "Dysze bąbelkowe",
        "Multi-stream": "Wielostrumieniowe",
        "Dual-stream": "Podwójny strumień",
        "Stream Nozzles": "Dysze strumieniowe",
        "Short Radius Nozzles": "Dysze krótkiego zasięgu",
        "Pressure compensating": "Kompensacja ciśnienia",
        "Adjustable flood": "Regulowane zalewanie",
        Adjustable: "Regulowane",
        Fixed: "Stałe",
        "Fixed Arc": "Stały kąt",
        "Strip Pattern": "Pas",
        "Drip line": "Linia kroplująca",
        "Drip cover": "Pokrywa kropli",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "Z emiterami",
        "noemitter": "Bez emitterów",
        "Root zone watering": "Podlewanie strefy korzeniowej",
        Lateral: "Sekcyjna",
        Main: "Główna",
        Trench: "Rowek",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC(Metryczne)",
        ldpe: "LDPE",
        Controller: "Sterownik",
        Sensor: "Czujnik",
        Wiring: "Połączenie",
        IrrigateMarks: "Strefy nawadniania",
        Surface: "Powierzchnia",
        Lawn: "Trawnik",
        Bed: "Rabata",
        Shrubs: "Krzewy",
        Path: "Ścieżka",
        Concrete: "Beton",
        Sand: "Piasek",
        Water: "Woda",
        Bedding: "Ściółkowanie",
        Flower: "Kwiaty",
        Herbal: "Zioła",
        geographic: "Geograficzne",
        sizeMark: "Wymiary",
        scalingBar: "Skala",
        loCurves: "Krzywe",
        texts: "Teksty",
        staticText: "Tekst statyczny",
        dynamicText: "Tekst dynamiczny",
        stampText: "Tekst pieczątki",
        stampTextDefault: "Tekst",
        stampTextgr1: "Definicja dokumentu",
        stampTextgr2: "Adres",
        stampTextgr3: "Nazwa terenu",
        stampTextgr4: "Nazwa rysunku",
        stampTextgr9: "Informacje o organizacji",
        stampTextgr6t: "Etap",
        stampTextgr7t: "Strona",
        stampTextgr8t: "Strony",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Rozdział",
        stampTextgr15t: "Odcinek",
        stampTextgr16t: "Strona",
        stampTextgr17t: "Nr. Dok.",
        stampTextgr18t: "Podpis",
        stampTextgr19t: "Data",
        stampTextgr20t: "Oryg. Nr faktury",
        stampTextgr21t: "Podpis i data",
        stampTextgr22t: "Zam. Nr faktury",
        inserts: "Mufy",
//------------------------------------------------------------
//-------------------MENADŻER WARSTW---------------------------
//------------------------------------------------------------
        showLM: "Pokaż menadżera warstw",
        hideLM: "Ukryj menadżera warstw",
//------------------------------------------------------------
//-------------------INNE SZCZEGÓŁY---------------------------
//------------------------------------------------------------
        noName: "Bez nazwy",
//------------------------------------------------------------
//-------------------STATUSY ŁADOWANIA AJAX---------------------
//------------------------------------------------------------
        beganExporting: "Eksportowanie układu",
        successExporting: "Eksportowanie zakończone sukcesem",
        failExporting: "Nie udało się wyeksportować",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Dzienny limit osiągnięty</a>",
        exportingLimit: "Limit: ",
        exportingLeft: "Pozostało dzisiaj: ",
        pdfExportingPopUpBlocked: "Twoja przeglądarka zablokowała okno popup. Proszę zezwolić na wyskakujące okna dla tej strony, aby pobrać plik .PDF",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Gwint wylotowy",
        tt_group_MT: "Męski",
        tt_group_FT: "Żeński",
        tt_riserHeight: "Wysokość podstawy",
        tt_pressureReg: "Regulator ciśnienia",
        tt_checkValve: "(Z zaworem zwrotnym)",
        tt_home: "Strona główna",
        tt_prev: "Poprzednia",
        tt_next: "Następna",
        tt_end: "Zakończ",
        tt_add: "Dodaj",
        tt_clone: "Klonuj",
        tt_remove: "Usuń",
        tt_rename: "Zmień nazwę",
        tt_addToFav: "Dodaj do ulubionych",
        tt_remFromFav: "Usuń z ulubionych",
        tt_presets: "Ustawienia domyślne",
        tt_MagicAutoPlacer: "`Automatyczne rozmieszczanie wzdłuż linii`",
    },
//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
//LAYOUTER-------------------------------------------------------------
//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
    layouter: {
//compass
        N: "Północ",
        S: "Południe",
        E: "Wschód",
        W: "Zachód",
//conventions
        sprinklers: "Rozpylacz",
        dripStarts: "Początek kroplowania",
        rzwLayer: "Nawadnianie strefy korzeniowej",
        dripLines: "Linia kroplująca",
        valvesLayer: "Kolektor zaworów",
        waterSources: "Źródło wody",
        quickCoupLayer: "Szybki złącz",
        controllers: "Sterownik",
        sensorsLayer: "Czujnik",
        mainPipes: "Rura główna",
        lateralPipes: "Rury boczne",
        lateralPipes_sprinklerZone: "Strefa (Rozpylacze)",
        lateralPipes_dripZone: "Strefa (Linie kroplujące)",
        lateralPipes_rzwZone: "Strefa (Nawadnianie strefy korzeniowej)",
        lateralPipes_emptyZone: "Strefa (Brak odbiorców)",
        trenchesLayer: "Rowki",
        insetsLayer: "Mufy",
        wiresLayer: "Podłączenia",
        wirelessLayer: "Połączenie bezprzewodowe",
        senswiresLayer: "Bezprzewodowe połączenie czujników",
        senswiresLayer: "Podłączenia czujników",
        surfaces: "Powierzchnie",
        ldItemsLayer: "Rośliny",
        covers: "Pokrycie",
        nameplates: "Informacje o odbiorcach",
        oreolas: "Oznaczenia odbiorców",
        pipeInfo: "Informacje o rurach",
        lines: "Linie",
        overlays: "Nakładki",
        stampLayer: "Ramka",
        stampTexts: "Teksty na ramce",
//zonesTable
        zoneType: "Typ strefy",
        color: "Kolor",
        consumers: "Odbiorcy",
        waterFlow: "Przepływ",
        sprinklerZone: "Rozpylacz",
        dripZone: "Kroplowanie",
        rzwZone: "Nawadnianie strefy korzeniowej",
        emptyZone: "Brak odbiorców",
        specifyDiagonal: "Proszę podać rozmiar przekątnej monitora w calach",
//sprinklersTable
        consType: "Typ",
        consName: "Nazwa",
        zoneNum: "Strefa",
        sector: "Sektor",
        radius: "Promień",
        reducedBy: "Redukcja",
        nozzle: "Dysza",
        rotor: "Rotor",
        bubbler: "Bubbler",
        bubblerNozzle: "Bubbler-Dysza",
//dripsTable
        catId: "Id. kat.",
        brand: "Marka",
        emitterStep: "Krok emitera",
        emitterFlow: "Przepływ",
//layersManangerSpecific
        consumersGrp: "Odbiorcy",
        nodesGrp: "Węzły",
        wiresGrp: "Podłączenia",
        pipesGrp: "Rury",
        landscapeGrp: "Krajobraz",
        allTogether: "Wszystkie"
    },
//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
//OUTLAYER-------------------------------------------------------------
//--------------------------------------------------------------------------
//--------------------------------------------------------------------------
    outlayer: {
//tableHeaders
        numsign: "#",
        typeCol: "Typ",
        brand: "Marka",
        catid: "Id. kat.",
        title: "Tytuł",
        units: "Jednostki",
        amount: "Ilość",
//predetermined
        dripLine: "Linia kroplująca",
        dl16: "Linia kroplująca 16/13mm",
        dl17: "Linia kroplująca 17mm",
        dripStart: "Początek kroplowania",
        ds16: "Początek kroplowania 16/13mm",
        ds17: "Początek kroplowania 17mm",
        manifold_no_lps_issue: "Brak podłączonych stref",
        manifold_no_mp_issue: "Brak podłączenia do rury głównej",
        manifold_no_wr_issue: "Brak podłączenia przewodu sterującego",
//nodes-----------------------------------
        sprinkler_unattached: "UWAGA!!! Masz niepodłączone ROZPYLACZE (nie zostaną uwzględnione w końcowym arkuszu specyfikacji)",
        drip_unattached: "UWAGA!!! Masz niepodłączone elementy kroplujące (nie zostaną uwzględnione w końcowym arkuszu specyfikacji)",
        mains_unattached: "UWAGA!!! Masz niepodłączone RURY GŁÓWNE (nie zostaną uwzględnione w końcowym arkuszu specyfikacji)",
        mains_empty: "UWAGA!!! Masz RURY GŁÓWNE bez odbiorców (nie zostaną uwzględnione w końcowym arkuszu specyfikacji)",
        laterals_unattached: "UWAGA!!! Masz niepodłączone RURY BOCZNE (nie zostaną uwzględnione w końcowym arkuszu specyfikacji)",
        laterals_empty: "UWAGA!!! Masz RURY BOCZNE bez odbiorców (nie zostaną uwzględnione w końcowym arkuszu specyfikacji)",
        rzw_unattached: "UWAGA!!! Masz niepodłączone elementy nawadniania strefy korzeniowej (nie zostaną uwzględnione w końcowym arkuszu specyfikacji)",
        sensors_unattached: "UWAGA!!! Masz niepodłączone CZUJNIKI (nie zostaną uwzględnione w końcowym arkuszu specyfikacji)",
        manifolds_unfinished: "UWAGA!!! Masz niezakończone KOLEKTORY ZAWORÓW (nie można skonfigurować zaworów)",
        control_wires_unattached: "UWAGA!!! Masz niepodłączone PRZEWODY STERUJĄCE",
        control_wires_empty: "UWAGA!!! Masz PRZEWODY STERUJĄCE bez podłączonych zaworów",
        cntr_wr_unattached: "Przewód sterujący",
        youCanSeeThemInTheDrawing: "Możesz zobaczyć każdy element na rysunku, naciskając przycisk 'oko' po lewej stronie wiersza elementu",
        sprinkler_nozzleMT: "Węzeł rozpylacza (Dysza z gwintem żeńskim)",
        sprinkler_nozzleFT: "Węzeł rozpylacza (Dysza z gwintem męskim)",
        "sprinkler_rotor1/2F": "Węzeł rozpylacza (Rotor) 1/2\" żeński",
        "sprinkler_rotor3/4F": "Węzeł rozpylacza (Rotor) 3/4\"",
        "sprinkler_rotor1F": "Węzeł rozpylacza (Rotor) 1\"",
        "sprinkler_rotor1/2M": "Węzeł rozpylacza (Rotor) 1/2\" męski",
        "sprinkler_bubbler1/2F": "Węzeł rozpylacza (Bubbler)",
        sprinkler_bubblerNozzleMT: "Węzeł rozpylacza (Dysza bąbelkowa z gwintem żeńskim)",
        sprinkler_bubblerNozzleFT: "Węzeł rozpylacza (Dysza bąbelkowa z gwintem męskim)",
        dripIrrigation16: "Kroplowanie (16/13mm)",
        dripIrrigation17: "Kroplowanie (17mm)",
        rootZoneWatering: "Nawadnianie strefy korzeniowej",
        manifold: "Węzeł kolektora zaworów",
        automation: "Węzeł automatyki",
        mainPipes_hdpePE80SDR11: "Rury główne HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Rury główne HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Rury główne HDPE SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Rury boczne HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Rury boczne HDPE SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Rury boczne HDPE SDR 17.6",
        mainPipes_hdpeSDR9: "Rury główne HDPE SDR 9",
        mainPipes_hdpeSDR11: "Rury główne HDPE SDR 11",
        mainPipes_hdpeSDR136: "Rury główne HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Rury główne HDPE SDR 17",
        mainPipes_hdpeSDR176: "Rury główne HDPE SDR 17.6",
        lateralPipes_hdpeSDR9: "Rury boczne HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Rury boczne HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Rury boczne HDPE SDR 13.6",
        lateralPipes_hdpeSDR17: "Rury boczne HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Rury boczne HDPE SDR 17.6",
        mainPipes_pvcSCH40: "Rury główne PVC SCH40",
        mainPipes_pvcSCH80: "Rury główne PVC SCH80",
        mainPipes_pvcCL315: "Rury główne PVC CLASS 315",
        mainPipes_pvcCL200: "Rury główne PVC CLASS 200",
        mainPipes_pvcCL160: "Rury główne PVC CLASS 160",
        mainPipes_pvcCL125: "Rury główne PVC CLASS 125",
        mainPipes_pvcUSCJPN18: "Rury główne PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Rury główne PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Rury główne PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Główne rury PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Główne rury PVC-U SCJ (PN4.5)",
        mainPipes_ldpeCLASS3: "Główne rury LDPE CLASS 3",
        lateralPipes_pvcSCH40: "Boczne rury PVC SCH40",
        lateralPipes_pvcSCH80: "Boczne rury PVC SCH80",
        lateralPipes_pvcCL315: "Boczne rury PVC CLASS 315",
        lateralPipes_pvcCL200: "Boczne rury PVC CLASS 200",
        lateralPipes_pvcCL160: "Boczne rury PVC CLASS 160",
        lateralPipes_pvcCL125: "Boczne rury PVC CLASS 125",
        lateralPipes_pvcUSCJPN18: "Boczne rury PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Boczne rury PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Boczne rury PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Boczne rury PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Boczne rury PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Boczne rury LDPE CLASS 3",
        wiring: "Okablowanie",
        qcv: "Szybkozłącza",
        fixedCntr: "stałe",
        stand_aloneCntr: "autonomiczne",
        modularCntr: "modularne",
        decoderCntr: "dekoder",
        inset: "Mufa rur",
        insets: "Mufy rur",
//-----------------------------------------
        novar: "brak wariantów",
        choosevar: "wybierz wariant",
//element.types----------------------------
        nozzle: "Dysza",
        rotor: "Rotor",
        rotorNozzle: "Dysza rotora",
        bubbler: "Bubler",
        bubblerNozzle: "Dysza bublera",
        rzw: "System nawadniania strefy korzeniowej",
        sprayBody: "Obudowa dyszy",
        sprinklerStandAssembly: "Podstawa zraszacza (Podstawa)",
        outBarb: "Złączka do dyszy",
        flexPipe: "Elastyczna rura",
        sj: "Złączka obrotowa",
        inBarb: "Złączka do rury",
        midSprinkPipeFitting: "Złączka łącząca",
        endSprinkPipeFitting: "Złączka końcowa",
        midRZWPipeFitting: "Złączka łącząca",
        endRZWPipeFitting: "Złączka końcowa",
        dripPipe: "Rura kroplująca",
        blindPipe: "Niewidoczna rura",
        dripTeeFitting: "T-łącznik do rury kroplującej",
        dripCapFitting: "Kapelusz do rury kroplującej",
        dripCouplingFitting: "Łącznik do rury kroplującej",
        dripElbowFitting: "Kolano do rury kroplującej",
        dripSpike: "Kolce do rur kroplujących",
        sprinklerZoneValve: "Zawór strefy zraszacza",
        emptyZoneValve: "Zawór bez odbiorników",
        valveOutFitting: "Zawór do strefy",
        dripZoneValve: "Zawór strefy kroplującej",
        rzwZoneValve: "Zawór do nawadniania strefy korzeniowej",
        pressureReg: "Regulator ciśnienia",
        filter_pressureReg: "Filtr z regulatorem ciśnienia",
        controller: "Sterownik",
        flowMeter: "Miernik przepływu",
        rainSensor: "Czujnik deszczu",
        soilSensor: "Czujnik wilgotności gleby",
        freezeSensor: "Czujnik mrozu",
        wrFreezeSensor: "Bezprzewodowy czujnik deszczu/mrozu",
        windSensor: "Czujnik wiatru",
        solarSensor: "Czujnik słoneczny",
        flowSensor: "Czujnik przepływu",
        weatherStation: "Stacja meteorologiczna",
        solarPanel: "Panel słoneczny",
        mainPipe: "Główna rura",
        teeFitting: "T-łącznik",
        elbowFitting: "Kolano",
        reducerFitting: "Redukcja",
        lateralPipe: "Sekcyjna rura",
        capFitting: "Korek",
        basicCable: "Podstawowy kabel",
        basicWire: "Podstawowy przewód",
        sensorCable: "Przewód czujnika pogody",
        qcPlastic: "Zawór szybkozłączny plastikowy",
        qcMetal: "Zawór szybkozłączny metalowy",
        gateway: "Brama",
        antExt: "Wzmacniacz antenowy",
        loramod: "Moduły LoRa",
//typesOfAcessories
        hdpeCOR: "Rura falista HDPE",
        expModule: "Moduł rozszerzenia",
        rzwSleeve: "Mankiet z tkaniny",
        rwCap: "Korek na wodę odzyskaną",
        gutterMount: "Montaż rynny",
        delayRelay: "Opóźnienie przekaźnika",
        fctFlow: "T-łącznik z gniazdem FCT",
        fctBspAdap: "Adapter do złącza FCT",
        drainCheckValve: "Zawór zwrotny",
        rwId: "Identyfikator wody odzyskanej",
        vpc: "Nakrętka antywandalowa",
        inletFilter: "Filtr wlotowy",
        wifiModule: "Moduł Wi-Fi",
        wallMount: "Montaż na ścianie",
        rwsSock: "Rękaw z tkaniny",
        rwsGrate: "Kratka do RWS",
        npCover: "Pokrywa nieprzydatna do picia",
        sprExt: "Przedłużacz do zraszacza",
        popUpToThread: "Adapter do zraszacza",
        valveBox: "Skrzynka zaworów",
        valveBoxExt: "Rozszerzenie skrzynki zaworów",
        qcPlasticKey: "Klucz do zaworu szybkozłącznego",
        qcPlasticElbFit: "Łącznik łokciowy",
        qcMetalKey: "Klucz do zaworu szybkozłącznego",
        qcMetalElbFit: "Łącznik łokciowy",
        qcMetalCapKey: "Klucz do pokrywy zaworu szybkozłącznego",
        insTape: "Taśma izolacyjna",
        wrConn: "Złączka",
        shrinkTube: "Termokurczliwa rura",
        hcFrontPanel: "Panel przedni",
        ball_valve: "Zawór kulowy",
        check_valve: "Zawór zwrotny",
        thread_manifold: "Rozdzielacz gwintowy",
        plastic_filter: "Filtr (plastikowy)",
        waterMeter: "Licznik wody",
        rfModule: "Moduł radiowy",
        largeAntenna: "Antena",
        wifiHub: "Hub Wi-Fi",
        handRemoteKit: "Zestaw pilota zdalnego sterowania",
        handRemote: "Pilot zdalnego sterowania",
        wifiBundleKit: "Zestaw Wi-Fi Bundle",
        //typesOfFittings
        //drip
        barb_cap_8: "Zakonczenie kropelkowe",
        barb_elbow_PP: "Kolano zaciskowy",
        barb_elbow_PT: "Kolano zaciskowy z gwintem",
        barb_tee_PPP: "T-łącznik zaciskowy",
        barb_coupling_PP: "Łącznik zaciskowy",
        barb_cross_PPPP: "Krzyż zaciskowy",
        barb_cap_P: "Zakonczenie kropelkowe zaciskowe",
        barb_coupling_PT: "Łącznik zaciskowy z gwintem",
        barb_tee_PTP: "T-łącznik zaciskowy z gwintem",
        barb_valve_PT: "Zawór zaciskowy z gwintem",
        barb_valve_PP: "Zawór zaciskowy",
        twlc_elbow_PP: "Kolano Twist-lock",
        twlc_tee_PPP: "T-łącznik Twist-lock",
        twlc_coupling_PP: "Łącznik Twist-lock",
        twlc_cross_PPPP: "Krzyż Twist-lock",
        twlc_cap_P: "Zakonczenie kropelkowe Twist-lock",
        twlc_coupling_PT: "Łącznik Twist-lock z gwintem",
        twlc_tee_PTP: "T-łącznik Twist-lock z gwintem",
        twlc_valve_PT: "Zawór Twist-lock z gwintem",
        twlc_valve_PP: "Zawór Twist-lock",
        dl_valves: "Specjalne zawory",
//pipe
        hdpeSDR9: "Rura HDPE SDR 9",
        hdpeSDR11: "Rura HDPE SDR 11",
        hdpeSDR136: "Rura HDPE SDR 13.6",
        hdpeSDR17: "Rura HDPE SDR 17",
        hdpeSDR176: "Rura HDPE SDR 17.6",
        ldpeSDR9: "Rura LDPE SDR 9",
        ldpeSDR11: "Rura LDPE SDR 11",
        ldpeSDR136: "Rura LDPE SDR 13.6",
        ldpeSDR17: "Rura LDPE SDR 17",
        pvcSCH40: "Rura PVC SCH40",
        pvcSCH80: "Rura PVC SCH80",
        pvcCL315: "Rura PVC CLASS 315",
        pvcCL200: "Rura PVC CLASS 200",
        pvcCL160: "Rura PVC CLASS 160",
        pvcCL125: "Rura PVC CLASS 125",
        pvcUSCJPN18: "Rura PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Rura PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Rura PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Rura PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Rura PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "Rura LDPE CLASS 3",
        compress_elbow_PT: "Kolano sprężynowy/Gwint",
        compress_coupling_PT: "Łącznik sprężynowy/Gwint",
        compress_tee_PTP: "T-łącznik sprężynowy/Gwint",
        compress_cap_P: "Korek końcowy sprężynowy",
        compress_elbow_PP: "Kolano sprężynowy",
        compress_coupling_PP: "Łącznik sprężynowy",
        compress_tee_PPP: "T-łącznik sprężynowy",
        compress_cross_PPPP: "Krzyż sprężynowy",
        compress_single_clamp_saddle: "Siodło jednoklamrowe sprężynowe",
        compress_ballvalve_PP: "Kulowy zawór sprężynowy",
        compress_ballvalve_PT: "Kulowy zawór sprężynowy/Gwint",
        customfit_elbow_PT: "Kolano dopasowawczy/Gwint",
        customfit_coupling_PT: "Łącznik dopasowawczy/Gwint",
        customfit_tee_PTP: "T-łącznik dopasowawczy/Gwint",
        customfit_cap_P: "Korek końcowy dopasowawczy",
        customfit_elbow_PP: "Kolano dopasowawczy",
        customfit_coupling_PP: "Łącznik dopasowawczy",
        customfit_tee_PPP: "T-łącznik dopasowawczy",
        customfit_cross_PPPP: "Krzyż dopasowawczy",
        customfit_single_clamp_saddle: "Siodło jednoklamrowe dopasowawcze",
        customfit_ballvalve_PP: "Kulowy zawór dopasowawczy",
        customfit_ballvalve_PT: "Kulowy zawór dopasowawczy/Gwint",
        thread_nipple: "Nipel",
        thread_coupling: "Łącznik",
        thread_mf_reducer: "Redukcja męsko-żeńska",
        thread_mf_adapter: "Adapter męsko-żeński",
        thread_mf_bush: "Mufa męsko-żeńska",
        thread_tee: "T-łącznik żeński",
        thread_elbow: "Kolano żeński",
        thread_mf_elbow: "Kolano męsko-żeński",
        thread_cap: "Korek żeński",
        thread_plug: "Wtyczka męska",
        thread_union_nut: "Śruba łącznikowa",
        thread_cross: "Krzyż",
        cable: "Kabel",
        wire: "Przewód",
        // slip
        slip_single_clamp_saddle: "Siodło jednoklamrowe (na rurze PVC)",
        slip_elbow_PT: "Kolano wsuwany/gwintowany",
        slip_coupling_PT: "Łącznik wsuwany/gwintowany",
        slip_tee_PTP: "T-łącznik wsuwany/gwintowany",
        slip_cap_P: "Korek wsuwany",
        slip_elbow_PP: "Kolano wsuwany",
        slip_coupling_PP: "Łącznik wsuwany",
        slip_tee_PPP: "T-łącznik wsuwany",
        slip_cross_PPPP: "Krzyż wsuwany",
        slip_ballvalve_PP: "Kulowy zawór wsuwany",
        slip_ballvalve_PT: "Kulowy zawór wsuwany/Gwint",
//extendables
        arbitraryFittings: "Dowolne elementy złączne",
        dripStartAssembly: "Montaż rozpoczęcia kroplenia",
        intakeAssembly: "Montaż poboru",
        offtakeAssembly: "Montaż poboru dowolnych elementów złącznych",
        numofvalves: "Liczba zaworów: ",
        numofvalvesshort: "Zawory: ",
        numofmanifs: "Liczba rozdzielaczy: ",
        intakePipeSize: "Rozmiar rury poboru: ",
        valveBoxes: "Skrzynki zaworów",
        valveAccessories: "Akcesoria do zaworów",
        oneValveAccessories: "Akcesoria do zaworu",
        controllerAccessories: "Akcesoria do sterownika",
        sensorAccessories: "Akcesoria do czujników",
        sprBodyAccessories: "Akcesoria do obudowy dyszy",
        rzwAccessories: "Akcesoria do nawadniania strefy korzeniowej",
        pipeStartFittings: "Dowolne elementy złączne głównej rury",
        qcAccessories: "Akcesoria do zaworów szybkozłącznych",
        wiringAccessories: "Akcesoria do okablowania",
        pipeSize: "Rozmiar rury: ",
        endOfPipe: "(Pozycja końcowa)",
        midOfPipe: "(Wycięcie)",
        emptyRender: [
            "Przepraszamy... brak sparsowanej zawartości",
            "Nie ukończyłeś w pełni żadnego z węzłów nawadniania do wyrenderowania"
        ],
        serviceFail: [
            "Przepraszamy... usługa renderowania specyfikacji jest niedostępna w tej chwili",
            "Prosimy spróbować ponownie później, gdy połączenie zostanie nawiązane",
            "Zauważ, że konfiguracja dokonana wcześniej zostanie zachowana"
        ],
        serviceTrialExpired: [
            "Przepraszamy... usługa renderowania specyfikacji nie jest dostępna dla twojego konta",
            "To oznacza, że twój okres próbny się skończył, a jeśli chcesz korzystać z tej usługi,",
            "<a href='/account/subscription'>możesz uaktualnić swoje konto na konto PRO</a>"
        ],
        serviceLimitReached: [
            "Osiągnąłeś dzienny limit renderowania arkuszy specyfikacyjnych",
            "Aby usunąć limit liczby renderowanych specyfikacji dziennie,",
            "<a href='/account/subscription'>możesz uaktualnić swoje konto na konto PRO</a>"
        ],
        findInDrawing: "Pokaż na płótnie",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Rury",
        labours_group_fittings: "Złączki",
        labours_group_valveBoxes: "Skrzynki zaworów",
        labours_group_wires: "Okablowanie",
        labours_group_sprinklers: "Dysze nawadniające",
        labours_group_rws: "Nawadnianie strefy korzeniowej",
        labours_group_sprinklerConnections: "Połączenia dysz nawadniających",
        labours_group_drip: "Rury i złączki kroplujące",
        labours_group_manifolds: "Rozdzielacze",
        labours_group_quickCoupling: "Szybkozłączki",
        labours_group_controllers: "Sterowniki",
        labours_group_sensors: "Czujniki",
        labours_group_trenches: "Rowy",
        labours_group_insets: "Mufy przewodów",
        labours_group_lawns: "Trawnik",
        labours_group_irrigatedArea: "Powierzchnia nawadniana",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "styczeń", "luty", "marzec", "kwiecień", "maj", "czerwiec", "lipiec", "sierpień", "wrzesień", "październik", "listopad", "grudzień"],
        MMM: ["\x01", "sty", "lut", "mar", "kwi", "maj", "cze", "lip", "sie", "wrz", "paź", "lis", "gru"],
        dddd: ["\x02", "niedziela", "poniedziałek", "wtorek", "środa", "czwartek", "piątek", "sobota"],
        ddd: ["\x03", "niedz.", "pon.", "wt.", "śr.", "czw.", "pt.", "sob."],
//buttonsCaps
        ok: "OK",
        save: "Zapisz",
        apply: "Zastosuj",
        defaults: "Domyślne",
        retry: "Ponów",
        finish: "Zakończ",
        safeRestart: "Bezpieczny restart",
        saveAndExit: "Zapisz i wyjdź",
        exit: "Wyjdź",
        cancel: "Anuluj",
        rename: "Zmień nazwę",
        idk: "Nie wiem",
        getFile: "Pobierz plik",
        reset: "Resetuj",
        random: "Losowo",
//misc
        zoneNum: "Strefa nr",
        valveNum: "Skrzynka zaworów nr",
        zonesColoring: "Reprezentacja stref",
        coversColoured: "Malowanie osłon dysz",
        dripsColoring: "Kolorowanie rur kroplujących",
        dripsSameAsZonesColored: "Rura kroplująca pokolorowana w kolorze swojej strefy",
//saveOflline
        saveOffline: [
            "Przepraszamy... połączenie zostało utracone",
            "Ale nie martw się, możesz kontynuować pracę nad swoim projektem w trybie offline.",
            "Gdy jesteś offline, wszystkie twoje zapisy będą przechowywane jako plik tekstowy w folderze pobierania twojej przeglądarki.",
            "A później możesz wgrać najnowszą wersję swojego rysunku na serwer."
        ],
        restartOffline: [
            "Przepraszamy... połączenie zostało utracone",
            "Ale nie martw się, twój projekt został zapisany lokalnie na twoim komputerze.",
            "Możesz go znaleźć w folderze pobierania przeglądarki.",
            "Jeśli chcesz pracować offline, możesz pobrać wersję offline aplikacji z twojego konta na stronie http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Przepraszamy... coś poszło nie tak podczas wczytywania twojego projektu",
            "Wygląda na to, że twoje poprzednie zapisy zostały w jakiś sposób uszkodzone.",
            "Ale nie martw się, Twój projekt zostanie oznaczony jako 'Uszkodzony' w twoim warsztacie teraz.",
            "A nasz personel techniczny zajmie się tą sytuacją tak szybko, jak to możliwe.",
            ""
        ],
        corruptedSavingFile: [
            "Przepraszamy... plik, który próbujesz wczytać, nie jest czytelny",
            "Ale nie martw się, możemy go naprawić.",
            "Wszystko, co musisz zrobić, to przesłać ten uszkodzony plik w formularzu ładowania plików na swoim warsztacie.",
            "A potem postaramy się go przywrócić do działania."
        ],
        ajaxReqFail: [
            "Przepraszamy... utracono połączenie z serwerem",
            "Obecnie niemożliwe jest wysyłanie/odbieranie danych",
            "Proszę spróbować ponownie później"
        ],
        critical: [
            "Przepraszamy... coś poszło nie tak",
            "Ale nie martw się, twój rysunek jest teraz w bezpiecznym miejscu, wystarczy kliknąć przycisk bezpiecznego restartu, aby kontynuować..."
        ],
        fatal: [
            "Przepraszamy... coś poszło nie tak",
            "Prosimy o pomoc w poprawieniu naszej usługi. Opisz, po jakich działaniach użytkownika wystąpił ten błąd",
            "Podaj informacje tutaj"
        ],
        areYouSure: [
            "Jesteś o krok od zamknięcia tego projektu",
            "Zauważ, że wszystkie niezapisane zmiany zostaną utracone."
        ],
        pickAnotherCSVFile: "Wybierz inny plik",
        csvFileTooBig: [
            "Przekroczony maksymalny rozmiar pliku CSV",
            "Ze względów optymalizacyjnych maksymalny rozmiar obsługiwanego pliku CSV jest ograniczony do 4 MB"
        ],
        notAnCSV: [
            "Przepraszamy, ten rodzaj pliku nie jest obsługiwany",
            "Obsługiwane formaty: .csv"
        ],
        pickAnotherImage: "Wybierz inny obraz",
        imageTooBig: [
            "Przekroczony maksymalny rozmiar obrazu",
            "Ze względów optymalizacyjnych maksymalny rozmiar obsługiwany obrazu jest ograniczony do 10 MB"
        ],
        notAnImage: [
            "Przepraszamy, ten rodzaj pliku nie jest obsługiwany",
            "Obsługiwane formaty obrazów: .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "Działanie OGRANICZONE",
            "To działanie nie jest dozwolone dla subskrypcji BEZPŁATNEJ"
        ],
        goPro: 'ZOSTAŃ PRO',
        renameLayout: "Wprowadź nową nazwę",
        areYouSureDeleteLayout: [
            "Uwaga! Tej czynności nie można cofnąć",
            "Jesteś pewny, że chcesz usunąć: ",
            "Usuń"
        ],
        setUnderlaySize: [
            "Ustaw długość linii, którą właśnie narysowałeś",
            "Wprowadziłeś niepoprawną wartość. Spróbuj ponownie"
        ],
        setMonitorDiagonal: [
            "Prosimy o podanie informacji o przekątnej monitora",
            "Wprowadziłeś niepoprawną wartość. Spróbuj ponownie"
        ],
        getSpecsTable: [
            "Ustaw preferencje wyjściowe specyfikacji",
            "Grupuj Materiały według",
            "Węzła", "Marki",
            "Ustaw rodzaj pliku jako",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Wprowadź tytuł",
            "Rozkład #",
            "Zapisz",
            "Zapisywanie specyfikacji",
            "Ukończono. Kliknij tutaj, aby otworzyć",
            "Zapisywanie nie powiodło się",
            "Aktualizuj istniejące rozkłady",
            "Aktualizacja",
            ""
        ],
        exportLayoutsAsPdf: [
            "Wybierz rozkłady do wyeksportowania",
            "oddzielne pliki (w trakcie rozwoju)",
            "jeden album",
            "Eksportuj",
            "Eksportuj rozkłady w"
        ],
        differentSprGroups: [
            "Nie udało się połączyć różnych typów odbiorników wody na tej rurze",
            "Zgodnie ze standardami projektowania nawadniania nie jest akceptowalne mieszanie różnych typów odbiorników wody lub dysz nawadniających o różnych intensywnościach opadów w tej samej strefie"
        ],
        tooFarAwaySpr: [
            "Nie udało się połączyć odbiorników",
            "Niektóre z odbiorników są zbyt daleko od bocznej rury, aby można było je połączyć. Maksymalną odległość połączenia można skonfigurować w menu preferencji"
        ],
        outlayerConfig: [
            "Konfiguracja arkusza specyfikacji"
        ],
        presetsMenu: {
            title: "Ustawienia wstępne",
            titleTextboxLabel: "Tytuł ustawienia wstępnego",
            descriptionTextboxLabel: "Opis",
            applyButton: "<i class='far fa-check-circle'></i> Zastosuj",
            defaultButton: "<i class='far fa-undo'></i> Ustaw domyślne",
            removeButton: "<i class='far fa-trash'></i> Usuń",
            updateButton: "<i class='far fa-sync'></i> Aktualizuj",
            createButton: "<i class='far fa-plus'></i> Utwórz nowy",
            closeButton: "<i class='far fa-times'></i> Zamknij",
            favorites_drawing: "Ulubione narzędzia (Krajobraz)",
            favorites_sprinkling: "Ulubione narzędzia (Nawadnianie)",
            favorites_layouting: "Ulubione narzędzia (Układanie)",
            configs_drawing: "Konfiguracja projektu",
            configs_outlayer: "Konfiguracja arkusza specyfikacji",
    },
        newPresetItem: "Nowa konfiguracja wstępna",
        cL_alreadyConnected: [
            "Nie udało się połączyć linii",
            "Te linie są już połączone z"
        ],
        cL_segOnElem: [
            "Nie udało się połączyć linii",
            "Nie możesz połączyć się z segmentem znajdującym się na"
        ],
        cL_strangeError: [
            "Nie udało się połączyć linii",
            "Przepraszamy... Połączenie nieudane"
        ],
        cL_misgrouping: [
            "Nie udało się połączyć linii",
            "Te linie posiadają odbiorniki, które nie są zalecane do umieszczenia w tej samej strefie. Jeśli chcesz je połączyć mimo to, włącz tryb 'Brakpiecznego łączenia' dla Grupowania dysz w konfiguracji projektu."
        ],
        cL_valve: "Zarządzenie zaworami",
        cL_waterSource: "Źródło wody",
        cL_dripStart: "Początek linii kroplującej",
        cL_controller: "Sterownik",
        cL_sensors: "Czujniki",
        cL_valves: "Zarządzenie zaworami",
        cL_notSameVariant: [
            "Nie udało się połączyć linii",
            "Te linie są różnych typów",
            "Typ obecnie rysowanej linii",
            "Typ linii, z którą chcesz się połączyć"
        ],
        hasRestorableProject: [
            "Masz niezapisane dane dla tego projektu",
            "Możesz przywrócić stan danych z migawki zrobionej o"
        ],
        restoreProject: "Przywróć",
        imageLost: [
            "Przepraszamy, nie możemy odnaleźć niektórych obrazów podkładowych na serwerze",
            "Ten obraz nie został znaleziony:"
        ],
        precipCalcError_mixedError: [
            'Błąd map opadów',
            'Nie udało się stworzyć map opadów dla kombinacji zraszaczy:',
        ],
        precipCalcError_mprNonMprRot: 'Nie można mieszać zwykłych rotorów i rotorów z dyszami MPR',
        precipCalcError_mprNozNonMprRot: 'Nie można mieszać dysz MPR i zwykłych rotorów',
        precipCalcError_staticNozRot: 'Nie można mieszać statycznych dysz z rotorami',
        precipCalcError_staticMprNoz: 'Nie można mieszać statycznych dysz z dyszami MPR',
        precipCalcError_missingError: [
            'Błąd map opadów',
            'Brakujące profile opadów dla zraszaczy:',
        ],
        precipCalcError_zoningError: [
            'Błąd strefowania map opadów',
            'Nie udało się stworzyć map opadów dla kombinacji zraszaczy:',
        ],
        precipCalcError_noZoneAndZone: 'Nie można obliczyć opadów dla rotorów podłączonych i niepodłączonych jednocześnie. Czas pracy jest nieznany, dlatego liczba obrotów rotorów jest niepewna',
        algoNozzler_noSolutions: [
            'Nie znaleziono możliwych rozwiązań rozmieszczenia zraszaczy',
            'Spróbuj wykonać następujące czynności:',
            '1. Zmień ograniczenia nakładania i inne opcje w menu konfiguracji narzędzia automatycznego rozmieszczania',
            '2. Wybierz inny typ zraszaczy, ponieważ mogą one zapewnić wymaganą elastyczność w rozmieszczeniu',
            '3. Użyj poniższego przycisku, aby ponownie uruchomić rozwiązanie z bardziej "luźnymi" ograniczeniami nakładania i pokrycia'
        ],
        retryWithLooseOptions: "Spróbuj ponownie z „luźnymi” opcjami",
        cannotSaveBecauseOffline: [
            "Nie udało się wysłać żądania do serwera",
            "Brak połączenia z serwerem",
            "Sprawdź, czy masz połączenie z internetem",
            "Aby nie stracić danych, nie zamykaj tego okna i spróbuj ponownie zapisać dane, gdy połączenie z serwerem zostanie nawiązane",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Nie udało się zapisać żądania",
            "Zbyt wiele prób nieprawidłowego kodu",
            "Sprawdź, czy poprawnie wprowadziłeś adres e-mail i spróbuj ponownie po upływie 30 sekund.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Nie udało się zapisać żądania",
            "Niepoprawny adres e-mail",
            "Sprawdź, czy wprowadziłeś poprawny adres e-mail i spróbuj ponownie",
            "",
            "",
        ],
        designRequestCompleted: [
            "Twoje żądanie zostało pomyślnie utworzone/aktualizowane",
            "Link do edycji", "skopiuj mnie",
            "Link do przeglądania", "skopiuj mnie",
        ],
        designRequestContacts: [
            "Informacje kontaktowe",
            "Organizacja",
            "Imię",
            "E-mail",
            "Telefon",
            "Adres",
            "Strona internetowa",
        ],
        designRequestInfo: [
            "Witaj w Studiu Projektowym!",
            "Tutaj możesz łatwo i szybko stworzyć żądanie dotyczące planowania swojego systemu nawadniania.",
            "Możesz znaleźć <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>film instruktażowy tutaj</a>",
            "Jeśli potrzebujesz dodatkowych informacji lub masz jakieś pytania, nie wahaj się skontaktować z nami."
        ],
        approveActionByCode: [
            "Potwierdź działanie",
            "Na podany przez Ciebie adres e-mail została wysłana wiadomość z kodem potwierdzającym.",
            "Proszę wprowadzić ten kod w polu poniżej",
            "Wprowadziłeś niepoprawny numer, spróbuj ponownie"
        ],
        revisionCheckFailedSoft: [
            'Konflikt wersji!',
            'Ten projekt jest obecnie otwarty na innym przeglądarku lub urządzeniu.',
            'Możesz nadpisać dane na serwerze (ponieważ przechowujemy tylko jedną wersję Twojego projektu), klikając przycisk „Nadpisz”, ale bądź ostrożny - cały postęp uzyskany w innych sesjach zostanie utracony!',
            'Lepszą strategią jest zrozumienie, gdzie i kto otworzył ten projekt i zdecydowanie, którą wersję uważasz za aktualną.',
            'Jeśli chcesz przejąć kontrolę nad najnowszą wersją jednocześnie otwartego projektu, możesz otworzyć ten projekt ponownie, duplikując tę kartę w swojej przeglądarce.',
        ],
        revisionBlocked: [
            'Zapisywanie zablokowane przez Administratora!',
            'Aktualnie Twój projekt jest sprawdzany przez nasz personel techniczny z powodu występujących w nim błędów.',
            'Proszę poczekaj, aż przegląd zostanie zakończony, a następnie otrzymasz e-mail z dalszymi instrukcjami.',
        ],
        openInOtherTab: "Otwórz najnowszy",
        overwrite: "Nadpisz",
        saveToFile: "Zapisz do pliku",
        filterSelection_exclude: "Wyklucz z wyboru",
        filterSelection_include: "Dołącz do wyboru",
        filterSelectionNames: {
            sprinklers: "Odbiorniki",
            sprinklers_nozzle: "Odbiorniki - Dysze",
            sprinklers_rotaryNozzle: "Odbiorniki - Dysze rotacyjne",
            sprinklers_rotor: "Odbiorniki - Rotory",
            sprinklers_bubbler: "Odbiorniki - Fontanny",
            sprinklers_bubblerNozzle: "Odbiorniki - Fontanny z dyszą",
            dripStarts: "Początki linii kroplujących",
            rzwLayer: "Nawadnianie strefy korzeniowej",
            dripLines: "Linie kroplujące",
            valvesLayer: "Zawory",
            waterSources: "Źródła wody",
            controllers: "Sterowniki",
            sensorsLayer: "Czujniki",
            mainPipes: "Rury główne",
            lateralPipes: "Rury boczne",
            trenchesLayer: "Rynny",
            insetsLayer: "Obudowy rur",
            wiresLayer: "Okablowanie",
            wirelessLayer: "Połączenie bezprzewodowe",
            senswiresLayer: "Bezprzewodowe połączenie czujników",
            senswiresLayer: "Okablowanie czujników",
            quickCoupLayer: "Szybkozłącza",
            surfaces: "Powierzchnie",
            ldItemsLayer: "Elementy krajobrazu"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Przyłącze zraszacza",
        fcType: "Typ połączenia zraszacza",
        sj: "Łącznik obrotowy (Swing Joint)",
        sprinklerStand: "Podstawa zraszacza (Riser)",
        flexPipeBarbs: "Rura elastyczna + kolce",
        minFlexPipeLength: "Minimalna długość rury elastycznej na jedno połączenie",
        midSprinkPipeFitting: "Łącznik środkowy rury zraszającej",
        endSprinkPipeFitting: "Łącznik końcowy rury zraszającej",
        single_clamp_saddle: "Opaska siodłowa",
        tee_PTP: "Trójnik z gwintem BSP",
        elbow_PT: "Kolano z gwintem BSP",
        coupling_PT: "Adapter z gwintem BSP",
//MANIFOLD NODE CONFIGS
        manifoldNode: "Przyłącze kolektora",
        valvesOutlay: "Rodzaj elektrozaworów",
        fold: "Gwint wewnętrzny",
        unfold: "Gwint zewnętrzny",
        threadsNode: "Połączenia gwintowe",
        threadTypes: "Typy gwintów",
//AUTOMATION NODE CONFIGS
        automationNode: "Sterownik",
        controllerModules: "Moduły rozszerzeń sterownika:",
        controllerVoltage: "Napięcie wejściowe sterownika:",
        controllerVoltageV2: "Napięcie wejściowe sterownika:",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automatycznie (najlepiej pasujące)",
        userModules: "Ręcznie (jako akcesoria)",
//RZW NODE
        rzwNode: "Węzeł nawadniania strefy korzeniowej",
        midRZWPipeFitting: "Łącznik środkowy rury RZW",
        endRZWPipeFitting: "Łącznik końcowy rury RZW",
//DRIP node
        dripNode: "Nawadnianie kroplowe",
        dripConnectionType: "Typy połączeń kroplowych",
        dripLengthPrecision: "Cyfry po przecinku w długości rurki kroplowej",
        dripTubingAddon: "Dodatek do rurki kroplowej",
        barb: "Kolce",
        twistLock: "Zatrzaski",
        dripSpikesStep: "Krok trzymaka rurki kroplowej",
        dripCrossFittingAble: "Możliwość krzyżowego łączenia",
        pipesNode: "Odcinek rur",
        hdpeConnectionType: "Typy połączeń HDPE",
        ldpeConnectionType: "Typy połączeń LDPE",
        pvcConnectionType: "Typy połączeń PVC",
        pipeAddon: "Dodatek do rury dla każdej średnicy",
        pipeLengthPrecision: "Cyfry po przecinku w długości rur",
        crossFittingAble: "Możliwość krzyżowego łączenia",
        compress: "Złącza śrubowe",
        customfit: "Niestandardowe złącza",
        slip: "Złącza na wsuwanie",
        wiringNode: "Odcinek przewodzenia",
        exportNode: "Opcje eksportu",
        exportNumbersPrecision: "Cyfry po przecinku w liczbach",
        basicWiringMethod: "Metoda przewodzenia sterowania",
        cableCoresArray: "Zakres liczby rdzeni kabla",
        noAutoWiring: "Dodaj przewodzenie ręcznie",
        separateCableToManifold: "Oddzielny wielordzeniowy kabel do kolektora",
        separateWireToValve: "Oddzielny przewód do zaworu + wspólny przewód do kolektora",
        maxCableCores: "Maksymalna liczba rdzeni kabla",
        verticalWiringAddon: "Dodatkowa pionowa długość kabla sterującego",
        verticalSensWiringAddon: "Dodatkowa pionowa długość kabla czujnika",
        wireAddon: "Dodatek do przewodu dla każdego typu",
        wireLengthPrecision: "Cyfry po przecinku w długości przewodu",
//DRAWER CONFIG
        drawerConfig: [
            "Konfiguracja projektu"
        ],
//SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Przyłącze",
        pressureDefinedBy: "Oczekiwane ciśnienie przyłącza wynosi",
        allowReduceRotors: "Zezwalaj na zmniejszenie promienia zraszaczy",
        radio_option_yes: "Tak",
        radio_option_no: "Nie",
        extreme_rotor_reduction: "Ekstremalne (Do 50%) (Może powodować nierównomierne opady)",
        radio_option_yes2: "Tak",
        takeReductionInAccountWhenAutoPlacing: "Oferowanie zmniejszonych odległości rzutu przy automatycznym umieszczaniu zraszaczy",
        recommendedPressure: "Zalecane przez dostawcę",
        userPressure: "Ustawiane przez użytkownika",
        expPressure: "Oczekiwane ciśnienie przyłącza",
        sprinklerGroupMode: "Grupowanie przyłączy",
        safeSprGroupMode: "Tryb ścisły (grupowanie tylko kompatybilnych)",
        unsafeSprGroupMode: "Tryb niestabilny (OSTRZEŻENIE! Brak ograniczeń grupowania)",
        "sprinklerAttachBulkMode": "Tryb masowego podłączania odbiorników",
        "safeSprAttachMode": "Nie podłączaj ponownie już podłączonych odbiorników",
        "unsafeSprAttachMode": "Tryb niestabilny (OSTRZEŻENIE! Możliwe ponowne podłączenie już podłączonych odbiorników. Użyj na własne ryzyko)",
//UNITS CONFIG
        unitsConfig: "Jednostki miary",
        precisionStd: "Cyfry po przecinku",
        unitsSystemGridAndRuler: "System jednostek miary dla siatki i linijki",
        distanceUnits: "Odległość",
        distancePrecision: "Cyfry po przecinku",
        sprinklerDistUnits: "Promień zraszacza",
        sprinklerDistPrecision: "Cyfry po przecinku",
        areaUnits: "Powierzchnia",
        areaPrecision: "Cyfry po przecinku",
        volumeUnits: "Objętość",
        volumePrecision: "Cyfry po przecinku",
        waterFlowUnits: "Przepływ wody",
        waterFlowPrecision: "Cyfry po przecinku",
        pressureUnits: "Ciśnienie",
        pressurePrecision: "Cyfry po przecinku",
        velocityUnits: "Prędkość",
        velocityPrecision: "Cyfry po przecinku",
        precipRateUnits: "Stopień opadu",
        precipRatePrecision: "Cyfry po przecinku",
// ZONE PROPS CONFIG
        climateConfig: "Obliczanie czasu nawadniania",
        lawnCultureType: "Rodzaj trawnika",
        coolLoving: "Chłodnolubne",
        warmLoving: "Ciepłolubne",
        climateTemp: "Średnia temperatura latem",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Średnia wilgotność latem",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Mikroklimat strefy&nbsp;<i class='far fa-question-circle'></i>",
        microClimateTooltip: "Łagodny\n" +
            "Obszary nawadniania, które są w cieniu, chronione przed wiatrem i oddalone od suchych i nagrzanych obiektów\n" +
            "\n" +
            "Normalny\n" +
            "Miejsca w krajobrazie, gdzie warunki mikroklimatyczne są reprezentowane: obecność\n" +
            "budynków, chodników i ścieżek, cień, itp. nie wpływają znacząco na wartości\n" +
            "ewapotranspiracji\n" +
            "\n" +
            "Surowy\n" +
            "Odzwierciedla warunki utrudniające wzrost roślin i łatwo przenosi na stan stresu, jeśli roślina nie jest odpowiednio nawadniana. Może to być otwarte miejsce, na słońcu, w bliskim sąsiedztwie ścieżek, budynków lub innych konstrukcji krajobrazowych, odbijających światło od szkła lub elementów krajobrazu, które absorbują ciepło, lub może to być miejsce wietrzne.",
        gentleMicroClimate: "Łagodny",
        normalMicroClimate: "Normalny",
        toughMicroClimate: "Surowy",
        soilType: "Skład gleby w strefach",
        sand: "Piaskowy",
        sandyLoam: "Piaskowo-gliniasty",
        lightLoam: "Lekki gliniasty",
        mediumLoam: "Średni gliniasty",
        heavyLoam: "Ciężki gliniasty",
        clay: "Glina",
        heavyClay: "Ciężka glina",
        zoneSlope: "Ogólny nachylenie na strefach",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Budżet wody",
        lowWB: "Niski",
        normalWB: "Normalny",
        highWB: "Wysoki",
        ft: "stopy",
        in: "cal",
        ftin: "stopy/cale",
        metric: "metryczne",
        imperialUS: "imperialne (US)",
//UNITS CONFIG
        hydraConfig: "Hydraulika",
        waterTemp: "Temperatura wody",
        maxFlowVelocity: "Maksymalna prędkość przepływu w rurze",
        commonConfig: "Ustawienia ogólne",
        lateralNozzlerSwitch: "Sposób przełączania na dysze boczne",
        NStabonly: "Klawisz Tab",
        NStabshift: "Klawisz Tab+Shift",
        showActionSubtitles: "Pokaż napisy akcji",
        Yeah: "Tak",
        Nope: "Nie",
        start: "Start",
        recalibrate: "Kalibracja ponowna",
        calibrationSuccess: [
            "Kalibracja zakończona sukcesem",
            "Teraz możesz używać ekran dotykowy w dwóch trybach - 'przesuń wskaźnik' (delikatne ruchy palcem) i 'tryb przeciągania' (mocniejsze naciskanie)",
        ],
        calibrationFailEqual: [
            "Kalibracja nie powiodła się",
            "Nie wykryliśmy większej różnicy w sposobie dotykania ekranu w obu trybach",
            "Możesz spróbować ponownie. Upewnij się, że używasz palca, a nie rysika"
        ],
        calibrationFailImproper: [
            "Kalibracja nie powiodła się",
            "Wykryliśmy większy nacisk na piórku niż na ambossie",
            "Możesz spróbować ponownie. Upewnij się, że przesuwasz pióro z mniejszym naciskiem niż amboss"
        ],
        calibrationImpossible: [
            "Kalibracja niemożliwa",
            "Wygląda na to, że twój urządzenie nie obsługuje pomiaru obszaru dotykowego. Dlatego nie możemy określić dwóch trybów interakcji dotykowej",
            "W takim przypadku możesz użyć wirtualnej myszki, aby móc przesuwać cokolwiek. Pojawi się na lewym boku ekranu.",
        ],
        calibrationNeeded: [
            "Kalibracja jest wymagana!",
            "Musimy dokonać kalibracji ekranu dotykowego, aby móc określić dwa tryby interakcji dotykowej:",
            "Tryb przesuwania wskaźnika - gdy chcesz tylko przesuwać wskaźnik lub przesuwać odcinek wielokąta podczas rysowania",
            "I tryb przeciągania - to jest, gdy chcesz przesuwać elementy lub zmieniać ich rozmiar. Możesz także przesuwać, aby zaznaczyć wiele elementów",
            "Kliknij przycisk Start i postępuj zgodnie z instrukcjami na ekranie"
        ],
        insertImage: 'Wstaw',
        mapImagePicker: [
            "Ładowarka obrazu satelitarnego",
            "Szerokość geograficzna/Długość geograficzna",
            "Wprowadź szerokość geograficzną",
            "Wprowadź długość geograficzną",
            "Bieżąca lokalizacja",
            "Idź",
            "Adres",
            "Wpisz część adresu i kliknij 'Szukaj'",
            "Szukaj",
            "Zoom",
            "Przesuń"
        ],
        "imageCrop": [
            "Narzędzie do przycinania"
        ],
        cropImage: "Przytnij",
        invalid_dataset_1: 'Nieprawidłowy zestaw danych. Projekt zawiera niedozwolone typy powierzchni. Dozwolone są tylko nawadniane (TRAWN), nie-nawadniane i przeszkody.',
        invalid_dataset_2: 'Nieprawidłowy zestaw danych. Dozwolona jest dokładnie JEDNA nawadniana powierzchnia.',
        invalid_dataset_3: 'Nieprawidłowy zestaw danych. Nawadniana powierzchnia przecina się samą ze sobą.',
        invalid_dataset_4: 'Nieprawidłowy zestaw danych. Wskaźnik przeszkody nie może być złożony (składać się z więcej niż jednego wielokąta)',
        invalid_dataset_5: 'Nieprawidłowy zestaw danych. Powierzchnia przeszkody musi być w całości zawarta w powierzchni nawadnianej.',
        invalid_dataset_6: 'Nieprawidłowy zestaw danych. Projekt zawiera niedozwolone typy zraszaczy. Dozwolone to:',
        invalid_dataset_7: 'Nieprawidłowy zestaw danych. Stopień opadu zraszaczy jest poza zakresem',
        invalid_dataset_8: 'Nieprawidłowy zestaw danych. Zraszacze nie mogą mieć indywidualnych ustawień ciśnienia',
        invalid_dataset_9: 'Nieprawidłowy zestaw danych. Projekt nie powinien ustawiać niestandardowego oczekiwanego ciśnienia u zraszaczy',
        invalid_dataset_10: 'Nieprawidłowy zestaw danych. Jednorodność jest zbyt niska.',
        invalid_dataset_11: 'Nieprawidłowy zestaw danych. Obszar nadmiernie nawadniany jest zbyt duży.',
    }
};
