this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "ft/in",
        sqm: "m²",
        acre: "ac",
        hectare: "ha",
        sqft: "sqr.ft",
        bar: "bar",
        kpa: "kPa",
        atm: "atm",
        mH2O: "mH₂O",
        psi: "psi",
        l: "l",
        m3: "m³",
        USg: "gal",
        cubft: "ft³",
        lpm: "lpm",
        lph: "lph",
        m3h: "m³/h",
        USgpm: "gpm",
        USgph: "gph",
        deg: "°",
        pcs: "pcs",
        pcsDot: "pcs.",
        pcsShort: "pcs.",
        percent: "%",
        in_Alt: "in.",
        mps: "m/s",
        kph: "km/h",
        ftps: "ft/s",
        degreesCentigrade: "°C",
        mmph: "mm/h",
        mmp24h: "mm/day",
        inph: "in/h",
        // unconvertable
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Gaveta automática",
        chooseSprinkler: "Escolha o bocal:",
        auto: "Ajuste automático",
        waterSource2row: ["Água", "Entrada"],
        setLineLength: "Definir o tamanho da linha (mm):",
        setPressure: "Definir a pressão dinâmica esperada nos bocais (bar):",
        setMaxFlow: "Definir o fluxo máximo de água (l/min):",
        controllerShort: "C",
        sensorShort: "S",
        action_activateEraser: "Ativar borracha",
        action_deactivateEraser: "Desativar borracha",
        action_boolUnite: "Unir",
        action_boolIntersect: "Interseccionar",
        action_boolSubtract: "Subtrair",
        action_boolExclude: "Excluir",
        action_changeSprayBody: "Definir pulverizador",
        action_changeVariant: "Definir variante",
        action_changeImgVariant: "Definir variante de imagem",
        action_changeType: "Definir tipo",
        action_addConsumers: "Adicionar consumidores",
        action_drawBranches: "Adicionar ramificações",
        action_editLine: "Editar segmentos",
        action_drawCircles: "Desenhar círculos",
        action_detachAll: "Desconectar tudo",
        action_drawBrush: "Desenhar pincel",
        action_editBrush: "Editar pincel",
        action_changeBrushSize: "Tamanho do pincel",
        action_booleans: "Operações booleanas",
        action_intoPoly: "Transformar em polígono",
        action_intoBrush: "Transformar em pincel",
        action_activateRotation: "Girar",
        action_deactivateRotation: "Parado",
        action_markZones: "Representação de zonas",
        action_unmarkZones: "Remover marcação",
        action_sprNames: "Nomes dos aspersores",
        action_noSprNames: "Remover nomes",
        action_lockItem: "Bloquear",
        action_unlockItem: "Desbloquear",
        Circle: "Círculo",
        Triangle: "Triângulo",
        BushForm: "Arbustos",
        BushForm1: "Arbustos 1",
        BushForm2: "Arbustos 2",
        BushForm3: "Arbustos 3",
        Square: "Quadrado",
        noShadow: "Nenhum",
        standardShadow: "Padrão",
        noArrows: "Nenhum",
        startArrow: "No início",
        endArrow: "No final",
        bothArrows: "Ambos os lados",
        normalSizeSide: "Normal",
        invertedSizeSide: "Invertido",
        strMiter: "Mitre",
        strRound: "Redondo",
        strBevel: "Chanfro",
        strSquare: "Quadrado",
        strButt: "Corte reto",
        FWnormal: "Normal",
        FWbold: "Negrito",
        FWitalic: "Itálico",
        FWbolditalic: "Negrito Itálico",
        FJleft: "Esquerda",
        FJright: "Direita",
        FJcenter: "Centro",
        rzwHeight: "Altura"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Seletor",
//----Desenho
        selectPoly: "Nenhum item selecionado",
//----Aspersão
        selectSprink: "Nenhum item selecionado",
        lpNozzler: "Anexando consumidores de água",
        dl16CircDrawer: "Desenhando círculos de gotejamento de 16/13mm",
        dl16sDrawer: "Desenhando capa de gotejamento de 16/13mm",
        dl17CircDrawer: "Desenhando círculos de gotejamento de 17mm",
        dl17sDrawer: "Desenhando capa de gotejamento de 17mm",
        "ldTextDrawer": "Configuração de Texto",
        "staticTextDrawer": "Configuração de Texto",
        "dynamicTextDrawer": "Configuração de Texto",
        "ldStaticTextDrawer": "Configuração de Texto",
        "ldtextEditor": "Edição de Texto",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Distância total",
        type: "Tipo",
        variant: "Variante",
        area: "Área",
        perimeter: "Perímetro",
        curveLength: "Comprimento",
        treeDiameter: "Diâmetro",
        bushDiameter: "Diâmetro",
        nozTypes: "Tipos disponíveis",
        nozType: "Tipo",
        sprBod: "Corpo do aspersor",
        rad: 'Raio',
        angle: 'Ângulo',
        reducedBy: 'Reduzido por',
        consump: 'Consumo',
        pressure: 'Pressão',
        coverSize: 'Cobertura',
        maxFlow: 'Fluxo máximo de água',
        pipesNum: "Tubos anexados",
        pipeType: "Tipo",
        pipeLength: "Comprimento",
        wireLength: "Comprimento",
        valvesManifNum: "Coletor de válvulas",
        valvesNum: "Válvulas",
        propDiam: "Diâmetro correto",
        curDiam: "Diâmetro do desenho",
        outsNum: "Consumidores de água",
        flow: "Fluxo de água",
        precipRate: "Taxa de precipitação",
        totalPrecipArea: "Área de cobertura total",
        uniformity: "CU",
        uniformity2: "DU",
        overwatered: "Overwatered",
        precipRateShort: "Taxa de precip.",
        runtimeInd: "Tempo de execução",
        coveredArea: "Área",
        microClimateInd: "Microclima",
        soilTypeInd: "Tipo de solo",
        zoneSlopeInd: "Declive da zona",
        maxInfiltrationRate: "Taxa de infiltração",
        waterDemand: "Demanda de água",
        numOfRuns: "Ciclos por dia",
        timePerRun: "Tempo por ciclo",
        dailyConsumption: "Consumo diário",
        dripsNum: "Linhas de gotejamento conectadas",
        dripType: "Tipo de gotejador",
        dripRowsStep: "Espaçamento entre as linhas",
        dripRowsAngle: "Ângulo entre as linhas",
        cntrType: "Tipo de controlador",
        sensType: "Tipo de sensor",
        zonesNum: "Zonas controladas",
        trenchWidth: "Largura",
        trenchDepth: "Profundidade",
        trenchVolume: "Volume",
        insetDiam: "Diâmetro",
        insetLength: "Comprimento",
        insetVar: "Material",
        itemsCount: "Contagem",
        insetDepth: "Profundidade",
        zoneName: "Nome da zona",
        valveName: "Caixa de válvula",
        itemAlias: "Apelido",
        lineWidth: "Largura",
        lineDepth: "Profundidade",
        lineArea: "Área",
        lineVolume: "Volume",
        surfaceDepth: "Profundidade/Altura",
        surfaceVolume: "Volume",
        //MULTISELECTOR
        itemsSelected: "Selecionados",
        totalArea: "Área total",
        totalPerimeter: "Perímetro total",
        totalLength: "Comprimento total",
        totalVolume: "Volume total",
        totalConsumption: "Consumo total",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Polígono inválido",
        isSelfCrossing_false: "Polígono válido",
        isConnected_true: "Conectado",
        isConnected_false: "Não conectado",
        isWired_true: "Cabeado",
        isWired_false: "Não cabeado",
        isDripZone_true: "Zona de gotejamento",
        isDripZone_false: "",
        isSprinklerZone_true: "Zona de aspersão",
        isSprinklerZone_false: "",
        isOverloaded_true: "SOBRECARGA!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Baixa pressão",
        isUnderpressured_false: "",
        isOverpressured_true: "Alta pressão",
        isOverpressured_false: "",
        isLocked_true: "Bloqueado",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Aço inoxidável",
        "High speed": "Alta velocidade",
        "Opposing nozzle": "Bico oposto",
        "Plastic": "Plástico",
        "MPR Nozzles": "Bicos MPR",
        "Rotary Nozzles": "Bicos rotativos",
        Nozzles: "Bicos",
        "Bubbler nozzles": "Bicos borbulhadores",
        "Multi-stream": "Multi-fluxo",
        "Dual-stream": "Dual-fluxo",
        "Stream Nozzles": "Bicos de fluxo",
        "Short Radius Nozzles": "Bicos de curto alcance",
        "Pressure compensating": "Compensador de pressão",
        "Adjustable flood": "Inundação ajustável",
        Adjustable: "Ajustável",
        Fixed: "Fixo",
        "Fixed Arc": "Arco fixo",
        "Strip Pattern": "Padrão de faixa",
        "Drip line": "Linha de gotejamento",
        "Drip cover": "Capa de gotejamento",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "Com emissores",
        "noemitter": "Sem emissores",
        "Root zone watering": "Rega da zona das raízes",
        Lateral: "Lateral",
        Main: "Principal",
        Trench: "Vala",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC(Metric)",
        ldpe: "LDPE",
        Controller: "Controlador",
        Sensor: "Sensor",
        Wiring: "Conexão",
        IrrigateMarks: "Zonas",
        Surface: "Superfície",
        Lawn: "Gramado",
        Bed: "Canteiro",
        Shrubs: "Arbustos",
        Path: "Caminho",
        Concrete: "Concreto",
        Sand: "Areia",
        Water: "Água",
        Bedding: "Leito",
        Flower: "Flor",
        Herbal: "Ervas",
        geographic: "Geográfico",
        sizeMark: "Dimensões",
        scalingBar: "Barra de escala",
        loCurves: "Linhas",
        texts: "Textos",
        staticText: "Texto estático",
        dynamicText: "Texto dinâmico",
        stampText: "Texto carimbo",
        stampTextDefault: "Texto",
        stampTextgr1: "Definição do documento",
        stampTextgr2: "Célula de endereço",
        stampTextgr3: "Nome do site",
        stampTextgr4: "Nome do desenho",
        stampTextgr9: "Informações da organização",
        stampTextgr6t: "Etapa",
        stampTextgr7t: "Página",
        stampTextgr8t: "Páginas",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Cap.",
        stampTextgr15t: "Taxa",
        stampTextgr16t: "Página",
        stampTextgr17t: "# Doc.",
        stampTextgr18t: "Assin.",
        stampTextgr19t: "Data",
        stampTextgr20t: "Orig. Inv.#",
        stampTextgr21t: "Assinatura e data",
        stampTextgr22t: "Repl. Inv.#",
        inserts: "Camisas de tubulação",
        poly: "Polígono",
        brush: "Pincel",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Mostrar gerenciador de camadas",
        hideLM: "Ocultar gerenciador de camadas",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Sem nome",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Exportando layout",
        successExporting: "Exportado com sucesso",
        failExporting: "Falha na exportação",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Limite diário atingido</a>",
        exportingLimit: "Limite: ",
        exportingLeft: "Restante hoje: ",
        pdfExportingPopUpBlocked: "Seu navegador bloqueou a janela pop-up. Por favor, permita pop-ups para este site para obter o arquivo .PDF",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Rosca",
        tt_group_MT: "Macho",
        tt_group_FT: "Fêmea",
        tt_riserHeight: "Altura do suporte",
        tt_pressureReg: "Regulador de pressão",
        tt_checkValve: "(Com válvula de retenção)",
        tt_home: "Início",
        tt_prev: "Anterior",
        tt_next: "Próximo",
        tt_end: "Fim",
        tt_add: "Adicionar",
        tt_clone: "Clonar",
        tt_remove: "Remover",
        tt_rename: "Renomear",
        tt_addToFav: "Adicionar aos favoritos",
        tt_remFromFav: "Remover dos favoritos",
        tt_presets: "Predefinições",
        tt_MagicAutoPlacer: "`Colocação automática ao longo da linha`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "N",
        S: "S",
        E: "L",
        W: "O",
        //conventions
        sprinklers: "Aspersores",
        dripStarts: "Início do gotejador",
        rzwLayer: "Irrigação de raiz",
        dripLines: "Tubulação gotejadora",
        valvesLayer: "Coletor de válvulas",
        waterSources: "Fonte de água",
        quickCoupLayer: "Engate rápido",
        controllers: "Controladores",
        sensorsLayer: "Sensores",
        mainPipes: "Tubulação principal",
        lateralPipes: "Tubulação lateral",
        lateralPipes_sprinklerZone: "Zona (Aspersores)",
        lateralPipes_dripZone: "Zona (Tubulação gotejadora)",
        lateralPipes_rzwZone: "Zona (Irrigação de raiz)",
        lateralPipes_emptyZone: "Zona (Sem consumidores)",
        trenchesLayer: "Valas",
        insetsLayer: "Mangas",
        wiresLayer: "Fiação",
        wirelessLayer: "Conexão sem fio",
        senswiresLayer: "Conexão sem fio de sensores",
        senswiresLayer: "Fiação do sensor",
        surfaces: "Superfícies",
        ldItemsLayer: "Plantas",
        covers: "Área de cobertura",
        nameplates: "Informações do consumidor",
        oreolas: "Marcas dos consumidores",
        pipeInfo: "Informações da tubulação",
        lines: "Linhas",
        overlays: "Sobreposições",
        stampLayer: "Moldura",
        stampTexts: "Textos de carimbo",
        //zonesTable
        zoneType: "Tipo de zona",
        color: "Cor",
        consumers: "Consumidores",
        waterFlow: "Fluxo",
        sprinklerZone: "Irrigação por aspersão",
        dripZone: "Irrigação por gotejamento",
        rzwZone: "Rega da zona radicular",
        emptyZone: "Sem consumidores",
        specifyDiagonal: "Por favor, especifique o tamanho diagonal do seu monitor em polegadas",
        //sprinklersTable
        consType: "Tipo",
        consName: "Nome",
        zoneNum: "Zona",
        sector: "Setor",
        radius: "Raio",
        reducedBy: "Reduzido em",
        nozzle: "Bico",
        rotor: "Rotor",
        bubbler: "Bubbler",
        bubblerNozzle: "Bubbler-Bico",
        //dripsTable
        catId: "ID de catálogo",
        brand: "Marca",
        emitterStep: "Intervalo de emissão",
        emitterFlow: "Fluxo de emissão",
        //layersManangerSpecific
        consumersGrp: "Consumidores",
        nodesGrp: "Nós",
        wiresGrp: "Fios",
        pipesGrp: "Tubos",
        landscapeGrp: "Paisagem",
        allTogether: "Todos"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Tipo",
        brand: "Marca",
        catid: "ID do catálogo",
        title: "Título",
        units: "Unidades",
        amount: "Quantidade",
//predetermined
        dripLine: "Linha de gotejamento",
        dl16: "Linha de gotejamento 16/13mm",
        dl17: "Linha de gotejamento 17mm",
        dripStart: "Início de gotejamento",
        ds16: "Início de gotejamento 16/13mm",
        ds17: "Início de gotejamento 17mm",
        manifold_no_lps_issue: "Nenhuma zona conectada",
        manifold_no_mp_issue: "Não conectado à linha principal",
        manifold_no_wr_issue: "Sem fio de controle anexado",
        //nodes-----------------------------------
        sprinkler_unattached: "ATENÇÃO!!! Você tem ASPERSORES desconectados (eles não serão apresentados na planilha final de especificações)",
        drip_unattached: "ATENÇÃO!!! Você tem elementos de irrigação por GOTEJAMENTO desconectados (eles não serão apresentados na planilha final de especificações)",
        mains_unattached: "ATENÇÃO!!! Você tem TUBULAÇÕES PRINCIPAIS desconectadas (elas não serão apresentadas na planilha final de especificações)",
        mains_empty: "ATENÇÃO!!! Você tem TUBULAÇÕES PRINCIPAIS sem consumidores (elas não serão apresentadas na planilha final de especificações)",
        laterals_unattached: "ATENÇÃO!!! Você tem TUBULAÇÕES LATERAIS desconectadas (elas não serão apresentadas na planilha final de especificações)",
        laterals_empty: "ATENÇÃO!!! Você tem TUBULAÇÕES LATERAIS sem consumidores (elas não serão apresentadas na planilha final de especificações)",
        rzw_unattached: "ATENÇÃO!!! Você tem elementos de IRRIGAÇÃO DE ZONA DE RAIZ desconectados (eles não serão apresentados na planilha final de especificações)",
        sensors_unattached: "ATENÇÃO!!! Você tem SENSORES desconectados (eles não serão apresentados na planilha final de especificações)",
        manifolds_unfinished: "ATENÇÃO!!! Você tem MANIFOLDS inacabados (não será possível concluir a configuração das válvulas)",
        control_wires_unattached: "ATENÇÃO!!! Você tem FIOS DE CONTROLE desconectados",
        control_wires_empty: "ATENÇÃO!!! Você tem FIOS DE CONTROLE sem válvulas conectadas",
        cntr_wr_unattached: "Fio de controle",
        youCanSeeThemInTheDrawing: "Você pode visualizar cada elemento no desenho, pressionando o 'olho' à esquerda da linha do elemento",
        sprinkler_nozzleMT: "Aspersor (Bico com rosca fêmea)",
        sprinkler_nozzleFT: "Aspersor (Bico com rosca macho)",
        "sprinkler_rotor1/2F": "Aspersor (Rotor) 1/2\" fêmea",
        "sprinkler_rotor3/4F": "Aspersor (Rotor) 3/4\"",
        "sprinkler_rotor1F": "Aspersor (Rotor) 1\"",
        "sprinkler_rotor11/4F": "Nó do aspersor (Rotor) 1 1/4\"",
        "sprinkler_rotor11/2F": "Nó do aspersor (Rotor) 1 1/2\"",
        "sprinkler_rotor2F": "Nó do aspersor (Rotor) 2\"",
        "sprinkler_rotor1/2M": "Aspersor (Rotor) 1/2\" macho",
        "sprinkler_rotor3/4M": "Sprinkler node (Rotor) 3/4\" male",
        "sprinkler_bubbler1/2F": "Aspersor (Bubbler)",
        sprinkler_bubblerNozzleMT: "Aspersor (Bico de Bubbler com rosca fêmea)",
        sprinkler_bubblerNozzleFT: "Aspersor (Bico de Bubbler com rosca macho)",
        dripIrrigation16: "Irrigação por gotejamento (16/13mm)",
        dripIrrigation17: "Irrigação por gotejamento (17mm)",
        rootZoneWatering: "Sistema de rega da zona radicular",
        manifold: "Nó do coletor de válvulas",
        automation: "Nó de automação",
        mainPipes_hdpePE80SDR11: "Tubos principais HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Tubos principais HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Tubos principais HDPE SDR 17.6",
        lateralPipes_hdpePE80SDR11: "Tubos laterais HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Tubos laterais HDPE SDR 13.6",
        lateralPipes_hdpePE80SDR176: "Tubos laterais HDPE SDR 17.6",
        mainPipes_hdpeSDR9: "Tubos principais HDPE SDR 9",
        mainPipes_hdpeSDR11: "Tubos principais HDPE SDR 11",
        mainPipes_hdpeSDR136: "Tubos principais HDPE SDR 13,6",
        mainPipes_hdpeSDR17: "Tubos principais HDPE SDR 17",
        mainPipes_hdpeSDR176: "Tubos principais HDPE SDR 17,6",
        lateralPipes_hdpeSDR9: "Tubos laterais HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Tubos laterais HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Tubos laterais HDPE SDR 13,6",
        lateralPipes_hdpeSDR17: "Tubos laterais HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Tubos laterais HDPE SDR 17,6",
        mainPipes_pvcSCH40: "Tubos principais PVC SCH40",
        mainPipes_pvcSCH80: "Tubos principais PVC SCH80",
        mainPipes_pvcCL315: "Tubos principais PVC CLASS 315",
        mainPipes_pvcCL200: "Tubos principais PVC CLASS 200",
        mainPipes_pvcCL160: "Tubos principais PVC CLASS 160",
        mainPipes_pvcCL125: "Tubos principais PVC CLASS 125",
        mainPipes_pvcUSCJPN18: "Main pipes PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Main pipes PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Main pipes PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Main pipes PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Main pipes PVC-U SCJ (PN4.5)",
        mainPipes_ldpeCLASS3: "Tubos principais LDPE CLASS 3",
        lateralPipes_pvcSCH40: "Tubos laterais PVC SCH40",
        lateralPipes_pvcSCH80: "Tubos laterais PVC SCH80",
        lateralPipes_pvcCL315: "Tubos laterais PVC CLASS 315",
        lateralPipes_pvcCL200: "Tubos laterais PVC CLASS 200",
        lateralPipes_pvcCL160: "Tubos laterais PVC CLASS 160",
        lateralPipes_pvcCL125: "Tubos laterais PVC CLASS 125",
        lateralPipes_pvcUSCJPN18: "Lateral pipes PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Lateral pipes PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Lateral pipes PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Lateral pipes PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Lateral pipes PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Tubos laterais LDPE CLASS 3",
        wiring: "Fiação",
        qcv: "Válvulas de engate rápido",
        fixedCntr: "fixo",
        stand_aloneCntr: "autônomo",
        modularCntr: "modular",
        decoderCntr: "decodificador",
        inset: "Mangueira protetora",
        insets: "Mangueiras protetoras",
        //-----------------------------------------
        novar: "sem variantes",
        choosevar: "escolha a variante",
//element.types----------------------------
        nozzle: "Bico",
        rotor: "Rotor",
        rotorNozzle: "Bico para rotor",
        bubbler: "Bubbler",
        bubblerNozzle: "Bico-bubbler",
        rzw: "Sistema de irrigação de zona radicular",
        sprayBody: "Corpo do aspersor",
        sprinklerStandAssembly: "Sprinkler stand (Riser)",
        outBarb: "Barb para bico",
        flexPipe: "Tubo flexível",
        sj: "Junção oscilante",
        inBarb: "Barb para tubo",
        midSprinkPipeFitting: "Conexão intermediária",
        endSprinkPipeFitting: "Conexão final",
        midRZWPipeFitting: "Conexão intermediária",
        endRZWPipeFitting: "Conexão final",
        dripPipe: "Tubo gotejador",
        blindPipe: "Tubo cego",
        dripTeeFitting: "Tê para tubo gotejador",
        dripCapFitting: "Tampa para tubo gotejador",
        dripCouplingFitting: "Acoplamento para tubo gotejador",
        dripElbowFitting: "Cotovelo para tubo gotejador",
        dripSpike: "Estaca para tubo gotejador",
        sprinklerZoneValve: "Válvula de zona de aspersão",
        emptyZoneValve: "Válvula sem consumidores",
        valveOutFitting: "Conexão da válvula para zona",
        dripZoneValve: "Válvula de zona de gotejamento",
        rzwZoneValve: "Válvula de rega na zona radicular",
        pressureReg: "Regulador de pressão",
        filter_pressureReg: "Filtro com regulador de pressão",
        controller: "Controlador",
        flowMeter: "Medidor de fluxo",
        rainSensor: "Sensor de chuva",
        soilSensor: "Sensor de umidade do solo",
        freezeSensor: "Sensor de congelamento",
        wrFreezeSensor: "Sensor de chuva e congelamento sem fio",
        windSensor: "Sensor de vento",
        solarSensor: "Sensor solar",
        flowSensor: "Sensor de fluxo",
        weatherStation: "Estação meteorológica",
        solarPanel: "Painel solar",
        mainPipe: "Tubo principal",
        teeFitting: "Tê",
        elbowFitting: "Cotovelo",
        reducerFitting: "Redutor",
        lateralPipe: "Tubo lateral",
        capFitting: "Tampão",
        basicCable: "Cabo básico",
        basicWire: "Fio básico",
        sensorCable: "Cabo para sensor meteorológico",
        qcPlastic: "Válvula de acoplamento rápido em plástico",
        qcMetal: "Válvula de acoplamento rápido em metal",
        gateway: "Gateway",
        antExt: "Antenna extension",
        loramod: "LoRa modules",
        //typesOfAcessories
        hdpeCOR: "Tubo corrugado",
        expModule: "Módulo de expansão",
        rzwSleeve: "Manga de tecido",
        rwCap: "Tampão de água reciclada",
        gutterMount: "Suporte de calha",
        delayRelay: "Relé de atraso",
        fctFlow: "Tê para receptáculo FCT",
        fctBspAdap: "Adaptador para conexão FCT",
        drainCheckValve: "Válvula de retenção",
        rwId: "ID de água recuperada",
        vpc: "Tampa à prova de vandalismo",
        inletFilter: "Filtro de entrada",
        wifiModule: "Módulo Wi-Fi",
        wallMount: "Suporte de parede",
        rwsSock: "Manga de tecido",
        rwsGrate: "Grade para RWS",
        npCover: "Tampa não potável",
        sprExt: "Extensão do spray",
        popUpToThread: "Adaptador de spray",
        valveBox: "Caixa de válvula",
        valveBoxExt: "Extensão da caixa de válvula",
        qcPlasticKey: "Chave para válvula Q/C",
        qcPlasticElbFit: "Encaixe de cotovelo",
        qcMetalKey: "Chave para válvula Q/C",
        qcMetalElbFit: "Encaixe de cotovelo",
        qcMetalCapKey: "Chave da tampa",
        insTape: "Fita isolante",
        wrConn: "Conector",
        shrinkTube: "Tubo termorretrátil",
        hcFrontPanel: "Painel frontal",
        ball_valve: "Válvula esférica",
        check_valve: "Válvula de retenção",
        thread_manifold: "Coletor",
        plastic_filter: "Filtro (plástico)",
        waterMeter: "Medidor de água",
        rfModule: "Módulo de rádio",
        largeAntenna: "Antena grande",
        wifiHub: "Hub Wi-Fi",
        handRemoteKit: "Kit remoto",
        handRemote: "Remoto",
        wifiBundleKit: "Kit de pacote Wi-Fi",
        //typesOfFittings
        //drip
        barb_cap_8: "Fecho final para irrigação por gotejamento",
        barb_elbow_PP: "Cotovelo barb",
        barb_elbow_PT: "Cotovelo barb com rosca",
        barb_tee_PPP: "Tê barb",
        barb_coupling_PP: "Acoplamento barb",
        barb_cross_PPPP: "Cruzeta barb",
        barb_cap_P: "Tampa final barb",
        barb_coupling_PT: "Acoplamento barb com rosca",
        barb_tee_PTP: "Tê barb com rosca",
        barb_valve_PT: "Válvula barb com rosca",
        barb_valve_PP: "Válvula barb",
        twlc_elbow_PP: "Cotovelo twist-lock",
        twlc_tee_PPP: "Tê twist-lock",
        twlc_coupling_PP: "Acoplamento twist-lock",
        twlc_cross_PPPP: "Cruzeta twist-lock",
        twlc_cap_P: "Tampa final twist-lock",
        twlc_coupling_PT: "Acoplamento twist-lock com rosca",
        twlc_tee_PTP: "Tê twist-lock com rosca",
        twlc_valve_PT: "Válvula twist-lock com rosca",
        twlc_valve_PP: "Válvula twist-lock",
        dl_valves: "Válvulas especiais",
//tubos
        hdpeSDR9: "Tubo HDPE SDR 9",
        hdpeSDR11: "Tubo HDPE SDR 11",
        hdpeSDR136: "Tubo HDPE SDR 13.6",
        hdpeSDR17: "Tubo HDPE SDR 17",
        hdpeSDR176: "Tubo HDPE SDR 17.6",
        ldpeSDR9: "Tubo LDPE SDR 9",
        ldpeSDR11: "Tubo LDPE SDR 11",
        ldpeSDR136: "Tubo LDPE SDR 13.6",
        ldpeSDR17: "Tubo LDPE SDR 17",
        pvcSCH40: "Tubo PVC SCH40",
        pvcSCH80: "Tubo PVC SCH80",
        pvcCL315: "Tubo PVC CLASS 315",
        pvcCL200: "Tubo PVC CLASS 200",
        pvcCL160: "Tubo PVC CLASS 160",
        pvcCL125: "Tubo PVC CLASS 125",
        pvcUSCJPN18: "Pipe PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Pipe PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Pipe PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Pipe PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Pipe PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "Tubo LDPE CLASS 3",
        compress_elbow_PT: "Cotovelo de compressão/roscado",
        compress_coupling_PT: "Acoplamento de compressão/roscado",
        compress_tee_PTP: "Tê de compressão/roscado",
        compress_cap_P: "Tampa final de compressão",
        compress_elbow_PP: "Cotovelo de compressão",
        compress_coupling_PP: "Acoplamento de compressão",
        compress_tee_PPP: "Tê de compressão",
        compress_cross_PPPP: "Cruzeta de compressão",
        compress_single_clamp_saddle: "Sela de compressão com uma abraçadeira",
        compress_ballvalve_PP: "Válvula de esfera de compressão",
        compress_ballvalve_PT: "Válvula de esfera de compressão/roscada",
        customfit_elbow_PT: "Cotovelo personalizado/roscado",
        customfit_coupling_PT: "Acoplamento personalizado/roscado",
        customfit_tee_PTP: "Tê personalizado/roscado",
        customfit_cap_P: "Tampa final personalizada",
        customfit_elbow_PP: "Cotovelo personalizado",
        customfit_coupling_PP: "Acoplamento personalizado",
        customfit_tee_PPP: "Tê personalizado",
        customfit_cross_PPPP: "Cruzeta personalizada",
        customfit_single_clamp_saddle: "Sela personalizada com uma abraçadeira",
        customfit_ballvalve_PP: "Válvula de esfera personalizada",
        customfit_ballvalve_PT: "Válvula de esfera personalizada/roscada",
        thread_nipple: "Niple",
        thread_coupling: "Acoplamento",
        thread_mf_reducer: "Redutor macho/fêmea",
        thread_mf_adapter: "Adaptador macho/fêmea",
        thread_mf_bush: "Bucha macho/fêmea",
        thread_tee: "Tê fêmea",
        thread_elbow: "Cotovelo fêmea",
        thread_mf_elbow: "Cotovelo macho/fêmea",
        thread_cap: "Tampa fêmea",
        thread_plug: "Plug macho",
        thread_union_nut: "Porca de união",
        thread_cross: "Cruzeta",
        cable: "Cabo",
        wire: "Fio",
// Slip
        slip_single_clamp_saddle: "Sela de uma abraçadeira (em tubo PVC)",
        slip_elbow_PT: "Cotovelo slip/roscado",
        slip_coupling_PT: "Acoplamento slip/roscado",
        slip_tee_PTP: "Tê slip/roscado",
        slip_cap_P: "Tampa final slip",
        slip_elbow_PP: "Cotovelo slip",
        slip_coupling_PP: "Acoplamento slip",
        slip_tee_PPP: "Tê slip",
        slip_cross_PPPP: "Cruzeta slip",
        slip_ballvalve_PP: "Válvula de esfera slip",
        slip_ballvalve_PT: "Válvula de esfera slip/roscada",
// Acessórios
        arbitraryFittings: "Acessórios arbitrários",
        dripStartAssembly: "Montagem do início de irrigação por gotejamento",
        intakeAssembly: "Montagem de entrada",
        offtakeAssembly: "Acessórios de tomada",
        numofvalves: "Número de válvulas: ",
        numofvalvesshort: "Válvulas: ",
        numofmanifs: "Número de coletores: ",
        intakePipeSize: "Tamanho do tubo de entrada: ",
        valveBoxes: "Caixas de válvula",
        valveAccessories: "Acessórios de válvula",
        oneValveAccessories: "Acessórios de válvula",
        controllerAccessories: "Acessórios de controlador",
        sensorAccessories: "Acessórios de sensor",
        sprBodyAccessories: "Acessórios de corpo de pulverização",
        rzwAccessories: "Acessórios de irrigação da zona radicular",
        pipeStartFittings: "Acessórios arbitrários de tubulação principal",
        qcAccessories: "Acessórios para válvulas Q/C",
        wiringAccessories: "Acessórios de cabeamento",
        pipeSize: "Tamanho do tubo: ",
        endOfPipe: "(Posição final)",
        midOfPipe: "(Corte)",
        emptyRender: [
            "Desculpe... nenhum conteúdo foi analisado",
            "Você não concluiu completamente nenhum dos nós de irrigação para renderizar"
        ],
        serviceFail: [
            "Desculpe... o serviço de renderização de especificações não está disponível no momento",
            "Tente novamente mais tarde, quando a conexão for estabelecida",
            "Observe que a configuração que você fez anteriormente será salva"
        ],
        serviceTrialExpired: [
            "Desculpe... o serviço de renderização de especificações não está disponível para a sua conta",
            "Isso significa que seu período de avaliação expirou e, se você quiser usar este serviço",
            "<a href='/account/subscription'>Você pode atualizar para uma conta PRO</a>"
        ],
        serviceLimitReached: [
            "Você atingiu o limite diário de geração de folhas de especificações",
            "Para remover o limite no número de renders de especificações por dia",
            "<a href='/account/subscription'>Você pode atualizar para uma conta PRO</a>"
        ],
        findInDrawing: "Mostrar no canvas",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Tubulações",
        labours_group_fittings: "Conexões",
        labours_group_valveBoxes: "Caixas de válvula",
        labours_group_wires: "Cabeamento",
        labours_group_sprinklers: "Aspersores",
        labours_group_rws: "Irrigação da zona radicular",
        labours_group_sprinklerConnections: "Conexões dos aspersores",
        labours_group_drip: "Tubos e conexões de gotejamento",
        labours_group_manifolds: "Coletores",
        labours_group_quickCoupling: "Acoplamentos rápidos",
        labours_group_controllers: "Controladores",
        labours_group_sensors: "Sensores",
        labours_group_trenches: "Valas",
        labours_group_insets: "Revestimentos de tubulação",
        labours_group_lawns: "Gramado",
        labours_group_irrigatedArea: "Área irrigada",
        labours_group_arbitrary_sp: "💦 Elementos de irrigação personalizados",
        labours_group_arbitrary_ld: "🌳 Elementos de paisagem personalizados",
        ldArbitrary_equip: "Equipamento",
        ldArbitrary_labour: "Mão de obra",
        spArbitrary_equip: "Equipamento",
        spArbitrary_labour: "Mão de obra",
        arbitrary_sp: '💦 Elementos de irrigação personalizados',
        arbitrary_ld: '🌳 Custom Landscape elements',
        ldLine_labour: "Linha",
        ldLine_equip: "Linha",
        spLine_labour: "Linha",
        spLine_equip: "Linha",
        ldLineWithArea_labour: "Linha (m2)",
        ldLineWithArea_equip: "Linha (m2)",
        spLineWithArea_labour: "Linha (m2)",
        spLineWithArea_equip: "Linha (m2)",
        ldVolumetricLine_labour: "Linha (m3)",
        ldVolumetricLine_equip: "Linha (m3)",
        spVolumetricLine_labour: "Linha (m3)",
        spVolumetricLine_equip: "Linha (m3)",
        polyLdSurface_labour: "Superfície",
        brushLdSurface_labour: "Superfície",
        polyLdSurface_equip: "Superfície",
        brushLdSurface_equip: "Superfície",
        polySpSurface_labour: "Superfície",
        brushSpSurface_labour: "Superfície",
        polySpSurface_equip: "Superfície",
        brushSpSurface_equip: "Superfície",
        polyLdVolumetricSurface_labour: "Superfície (m3)",
        brushLdVolumetricSurface_labour: "Superfície (m3)",
        polyLdVolumetricSurface_equip: "Superfície (m3)",
        brushLdVolumetricSurface_equip: "Superfície (m3)",
        polySpVolumetricSurface_labour: "Superfície (m3)",
        brushSpVolumetricSurface_labour: "Superfície (m3)",
        polySpVolumetricSurface_equip: "Superfície (m3)",
        brushSpVolumetricSurface_equip: "Superfície (m3)",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"],
        MMM: ["\x01", "Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"],
        dddd: ["\x02", "Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"],
        ddd: ["\x03", "Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
//buttonsCaps
        ok: "Ok",
        save: "Salvar",
        apply: "Aplicar",
        defaults: "Padrões",
        retry: "Tentar novamente",
        finish: "Concluir",
        safeRestart: "Reinicialização segura",
        saveAndExit: "Salvar e sair",
        exit: "Sair",
        cancel: "Cancelar",
        rename: "Renomear",
        idk: "Não sei",
        getFile: "Obter arquivo",
        reset: "Redefinir",
        random: "Aleatório",
        //misc
        zoneNum: "Zona #",
        valveNum: "Caixa de válvula #",
        zonesColoring: "Representação das zonas",
        coversColoured: "Pintar capas dos aspersores",
        dripsColoring: "Coloração de tubos de gotejamento",
        dripsSameAsZonesColored: "Tubos de gotejamento coloridos com a cor da zona correspondente",
//saveOflline
        saveOffline: [
            "Desculpe... conexão perdida",
            "Mas não se preocupe, você pode continuar seu projeto no modo offline.",
            "Enquanto você estiver offline, todas as suas alterações serão salvas como um arquivo de texto na pasta de downloads do seu navegador.",
            "E mais tarde, você poderá carregar a versão mais recente do seu desenho no servidor."
        ],
        restartOffline: [
            "Desculpe... conexão perdida",
            "Mas não se preocupe, o seu projeto foi salvo localmente em seu computador.",
            "Você pode encontrá-lo na pasta de downloads do navegador.",
            "Se desejar trabalhar offline, você pode baixar uma Instância Offline do aplicativo em sua conta em http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Desculpe... ocorreu um erro ao carregar seu projeto",
            "Parece que o seu arquivo de salvamento anterior foi corrompido de alguma forma.",
            "Mas não se preocupe, podemos repará-lo.",
            "Seu projeto será marcado como 'Quebrado' em seu workshop agora.",
            "E nossa equipe técnica lidará com essa situação o mais rápido possível."
        ],
        corruptedSavingFile: [
            "Desculpe... o arquivo que você está tentando carregar não pode ser lido",
            "Mas não se preocupe, podemos repará-lo.",
            "Tudo o que você precisa fazer é enviar este arquivo corrompido através do formulário de carregamento de arquivos em sua oficina.",
            "E então, vamos tentar fazê-lo funcionar novamente."
        ],
        ajaxReqFail: [
            "Desculpe... perdemos a conexão com o servidor",
            "Não é possível enviar/receber nenhum dado no momento",
            "Por favor, tente novamente mais tarde"
        ],
        critical: [
            "Desculpe... algo deu errado",
            "Mas não se preocupe, seu desenho está seguro, basta clicar no botão de reinício seguro para continuar..."
        ],
        fatal: [
            "Desculpe... algo deu errado",
            "Ajude-nos a melhorar nosso serviço. Descreva depois de quais ações do usuário esse erro ocorreu",
            "Fornecer informações aqui"
        ],
        areYouSure: [
            "Você está prestes a fechar este projeto",
            "Observe que todas as alterações não salvas serão perdidas."
        ],
        pickAnotherCSVFile: "Escolha outro arquivo",
        csvFileTooBig: [
            "Tamanho máximo do arquivo CSV excedido",
            "Para fins de otimização, o tamanho máximo do arquivo CSV permitido é limitado a 4 Mb"
        ],
        notAnCSV: [
            "Desculpe, este tipo de arquivo não é suportado",
            "Formatos suportados: .csv"
        ],
        invalidCSV: [
            "Conteúdo do arquivo CSV inválido",
            "Erro de análise do arquivo de exportação do aplicativo Moasure, verifique se o arquivo foi exportado corretamente"
        ],
        pickAnotherImage: "Escolha outra imagem",
        imageTooBig: [
            "Tamanho máximo da imagem excedido",
            "Para fins de otimização, o tamanho máximo da imagem suportado é limitado a 10Mb"
        ],
        notAnImage: [
            "Desculpe, esse tipo de arquivo não é suportado",
            "Formatos de imagem suportados: .pdf, .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "Ação RESTRITA",
            "Essa ação não é permitida para a assinatura GRÁTIS"
        ],
        goPro: 'FAÇA O UPGRADE',
        renameLayout: "Digite o novo nome",
        areYouSureDeleteLayout: [
            "Atenção! Esta ação não pode ser desfeita",
            "Tem certeza de que deseja excluir: ",
            "Excluir"
        ],
        setUnderlaySize: [
            "Defina o comprimento da linha que você acabou de desenhar",
            "Você digitou um valor incorreto. Por favor, tente novamente"
        ],
        setMonitorDiagonal: [
            "Por favor, informe o tamanho diagonal do seu monitor",
            "Você digitou um valor incorreto. Por favor, tente novamente"
        ],
        getSpecsTable: [
            "Defina as preferências de saída de especificações",
            "Agrupar equipamento por",
            "Nó", "Marca",
            "Defina o tipo de arquivo como",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Digite um título",
            "Leiaute #",
            "Salvar",
            "Salvando especificações",
            "Concluído. Clique aqui para abrir",
            "Falha ao salvar",
            "Atualizar leiautes existentes",
            "Atualizar",
            "Atualizando leiautes"
        ],
        exportLayoutsAsPdf: [
            "Escolha os leiautes a serem exportados",
            "arquivos separados (em desenvolvimento)",
            "um único arquivo",
            "Exportar",
            "Exportar leiautes em"
        ],
        differentSprGroups: [
            "Falha ao anexar diferentes tipos de irrigadores nesta tubulação",
            "De acordo com os padrões de projeto de irrigação, é inaceitável misturar diferentes tipos de irrigadores com diferentes taxas de precipitação na mesma zona"
        ],
        tooFarAwaySpr: [
            "Falha ao conectar consumidores",
            "Alguns dos consumidores estão muito distantes do tubo lateral para serem conectados. A distância máxima de conexão pode ser configurada no menu de preferências."
        ],
        outlayerConfig: [
            "Configuração da planilha de especificações"
        ],
        presetsMenu: {
            title: "Predefinições",
            titleTextboxLabel: "Título da predefinição",
            descriptionTextboxLabel: "Descrição",
            applyButton: "<i class='far fa-check-circle'></i> Aplicar",
            defaultButton: "<i class='far fa-undo'></i> Definir padrão",
            removeButton: "<i class='far fa-trash'></i> Remover",
            updateButton: "<i class='far fa-sync'></i> Atualizar",
            createButton: "<i class='far fa-plus'></i> Criar novo",
            closeButton: "<i class='far fa-times'></i> Fechar",
            favorites_drawing: "Ferramentas favoritas (Paisagismo)",
            favorites_sprinkling: "Ferramentas favoritas (Irrigação)",
            favorites_layouting: "Ferramentas favoritas (Layouts)",
            configs_drawing: "Configuração do Projeto",
            configs_outlayer: "Configuração da Planilha de Especificações",
        },
        newPresetItem: "Novo preset",
        cL_alreadyConnected: [
            "Falha na conexão de linhas",
            "Essas linhas já estão conectadas a"
        ],
        cL_segOnElem: [
            "Falha na conexão de linhas",
            "Você não pode se conectar a um segmento que está em"
        ],
        cL_strangeError: [
            "Falha na conexão de linhas",
            "Desculpe... A conexão falhou"
        ],
        cL_misgrouping: [
            "Falha na conexão de linhas",
            "Essas linhas têm consumidores que não são recomendados para serem colocados na mesma zona. Se você deseja conectá-los de qualquer maneira, ative o 'Modo inseguro' para Agrupamento de aspersores na configuração do projeto"
        ],
        cL_valve: "Manifold de válvulas",
        cL_waterSource: "Fonte de água",
        cL_dripStart: "Início de gotejamento",
        cL_controller: "Controlador",
        cL_sensors: "Sensor",
        cL_valves: "Manifold de válvulas",
        cL_notSameVariant: [
            "Falha na conexão de linhas",
            "Essas linhas têm tipos diferentes",
            "Tipo de linha que está sendo desenhada no momento",
            "Tipo de linha com o qual você deseja se conectar"
        ],
        hasRestorableProject: [
            "Você tem dados não salvos para este projeto",
            "Você pode restaurar o estado não salvo a partir da captura de tela tirada em"
        ],
        restoreProject: "Restaurar",
        imageLost: [
            "Desculpe, não conseguimos encontrar algumas das imagens de plano de fundo no servidor",
            "Esta imagem não foi encontrada:"
        ],
        precipCalcError_mixedError: [
            'Erro nos mapas de precipitação',
            'Falha ao construir mapas de precipitação para a combinação de aspersores:',
        ],
        precipCalcError_mprNonMprRot: 'Não é possível misturar rotores normais e rotores com bicos MPR',
        precipCalcError_mprNozNonMprRot: 'Não é possível misturar bicos MPR e rotores normais',
        precipCalcError_staticNozRot: 'Não é possível misturar bicos estáticos com rotores',
        precipCalcError_staticMprNoz: 'Não é possível misturar bicos estáticos com bicos MPR',
        precipCalcError_missingError: [
            'Erro nos mapas de precipitação',
            'Perfis de precipitação ausentes para aspersores:',
        ],
        precipCalcError_zoningError: [
            'Erro de zoneamento nos mapas de precipitação',
            'Falha ao construir mapas de precipitação para a combinação de aspersores:',
        ],
        precipCalcError_noZoneAndZone: 'Não é possível calcular a precipitação para rotores conectados e não conectados simultaneamente. O tempo de execução é desconhecido, portanto, a quantidade de revoluções dos rotores é incerta',
        algoNozzler_noSolutions: [
            'Nenhuma solução possível de posicionamento de aspersores encontrada',
            'Tente o seguinte:',
            '1. Altere as restrições de sobreposição e outras opções no menu de configuração da ferramenta de colocação automática',
            '2. Selecione outro tipo de aspersores, pois eles podem oferecer a flexibilidade necessária para o posicionamento',
            '3. Use o botão abaixo para reiniciar a solução com restrições mais "flexíveis" para sobreposição e cobertura'
        ],
        retryWithLooseOptions: "Tentar novamente com opções 'flexíveis'",
        cannotSaveBecauseOffline: [
            "Falha ao enviar solicitação para o servidor",
            "Sem conexão com o servidor",
            "Verifique se você tem uma conexão com a internet",
            "Para não perder dados, não feche esta janela e tente salvar os dados novamente mais tarde, quando a conexão com o servidor for estabelecida",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Falha ao salvar solicitação",
            "Muitas tentativas de código inválido",
            "Verifique se você inseriu o endereço de e-mail corretamente e tente novamente após 30 segundos.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Falha ao salvar solicitação",
            "Endereço de e-mail inserido incorretamente",
            "Verifique se você inseriu o endereço de e-mail corretamente e tente novamente",
            "",
            "",
        ],
        designRequestCompleted: [
            "Sua solicitação foi criada/atualizada com sucesso",
            "Link de edição", "copiar",
            "Link de visualização", "copiar",
        ],
        designRequestContacts: [
            "Contact information",
            "Organization",
            "Name",
            "Email",
            "Phone",
            "Address",
            "Website",
        ],
        "designRequestInfo": [
            "Bem-vindo ao Estúdio de Design!",
            "Aqui você pode criar um pedido para planejar seu sistema de irrigação de forma fácil e rápida.",
            "Você pode encontrar um <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>vídeo de instruções aqui</a>",
            "Para mais informações ou se tiver alguma dúvida, não hesite em nos contatar."
        ],
        approveActionByCode: [
            "Confirmar ação",
            "Um e-mail com um código de confirmação foi enviado para o endereço de e-mail fornecido.",
            "Por favor, insira este código no campo abaixo",
            "Você inseriu um número inválido, tente novamente"
        ],
        "revisionCheckFailedSoft": [
            "Conflito de revisão!",
            "Este projeto está atualmente aberto em outro navegador ou dispositivo.",
            "Você pode sobrescrever os dados no servidor (já que estamos armazenando apenas uma versão do seu projeto) clicando em `sobrescrever`, mas cuidado - todo o progresso feito em outras sessões será perdido!",
            "Uma estratégia melhor é entender onde e quem abriu este projeto e decidir qual versão está atualizada.",
            "Se você quiser assumir o controle sobre a versão mais recente deste projeto aberto simultaneamente, você pode abrir este projeto novamente duplicando esta aba no seu navegador.",
        ],
        "revisionBlocked": [
            "O salvamento está bloqueado pelo Admin!",
            "Atualmente, seu projeto está sendo revisado por nossa equipe técnica devido a erros que estão ocorrendo nele.",
            "Por favor, aguarde até que a revisão seja concluída, depois você será notificado por e-mail com instruções adicionais.",
        ],
        missingVariants: [
            'Erro de elementos ausentes',
            'Abaixo está a lista de elementos personalizados que estão ausentes na biblioteca do projeto e, portanto, não podem ser renderizados:',
            'Por favor, ative os conjuntos que contêm esses elementos no menu de configuração do projeto (na Oficina)'
        ],
        "openInOtherTab": "Abrir o mais recente",
        "overwrite": "Sobrescrever",
        "saveToFile": "Salvar em arquivo",
        filterSelection_exclude: "Excluir da seleção",
        filterSelection_include: "Incluir na seleção",
        filterSelectionNames: {
            sprinklers: "Consumidores",
            sprinklers_nozzle: "Consumidores - Bocais",
            sprinklers_rotaryNozzle: "Consumidores - Bocais rotativos",
            sprinklers_rotor: "Consumidores - Rotores",
            sprinklers_bubbler: "Consumidores - Bubblers",
            sprinklers_bubblerNozzle: "Consumidores - Bubbler-nozzles",
            sprinklers_pinpoint: "Consumidores - Aspersores de precisão",
            dripStarts: "Inícios de gotejamento",
            rzwLayer: "Rega na zona radicular",
            dripLines: "Linhas de gotejamento",
            valvesLayer: "Coletores de válvulas",
            waterSources: "Fontes de água",
            controllers: "Controladores",
            sensorsLayer: "Sensores",
            mainPipes: "Tubos principais",
            lateralPipes: "Tubos laterais",
            trenchesLayer: "Trincheiras",
            insetsLayer: "Mangas",
            wiresLayer: "Fiação",
            wirelessLayer: "Conexão sem fio",
            senswiresLayer: "Conexão sem fio de sensores",
            senswiresLayer: "Fiação de sensores",
            quickCoupLayer: "Acoplamentos rápidos",
            surfaces: "Polígonos e linhas",
            ldItemsLayer: "Itens de paisagismo",
            ldArbitraryLayer: "Elementos de paisagismo personalizados",
            spArbitraryLayer: "Elementos de irrigação personalizados"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Nó de aspersor",
        fcType: "Tipo de conexão",
        sj: "Junta oscilante",
        sprinklerStand: "Sprinkler stand (Riser)",
        flexPipeBarbs: "Tubo flexível + barbas",
        minFlexPipeLength: "Comprimento mínimo do tubo flexível por conexão",
        midSprinkPipeFitting: "Conector intermediário",
        endSprinkPipeFitting: "Conector final do tubo",
        single_clamp_saddle: "Braçadeira de suporte",
        tee_PTP: "Tê com rosca fêmea BSP",
        elbow_PT: "Cotovelo com rosca fêmea BSP",
        coupling_PT: "Adaptador com rosca fêmea BSP",
//MANIFOLD NODE CONFIGS
        manifoldNode: "Nós de coletores",
        valvesOutlay: "Coletores de válvulas",
        fold: "Dobrado",
        unfold: "Desdobrado",
        threadsNode: "Conexões roscadas",
        threadTypes: "Tipos de roscas",
//AUTOMATION NODE CONFIGS
        automationNode: "Nó de automação",
        controllerModules: "Módulos de expansão de controladores modulares selecionados:",
        controllerVoltage: "Tensão de entrada do controlador:",
        controllerVoltageV2: "Tensão de entrada do controlador:",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automático (melhor ajuste)",
        userModules: "Manual (como acessórios)",
//RZW NODE
        rzwNode: "Irrigação da zona radicular",
        midRZWPipeFitting: "Conexão para tubo principal",
        endRZWPipeFitting: "Conexão final para tubo principal",
//DRIP node
        dripNode: "Irrigação por gotejamento",
        dripConnectionType: "Tipo de conexão para gotejador",
        dripLengthPrecision: "Casas decimais no comprimento do tubo",
        dripTubingAddon: "Aditivo para tubulação de gotejamento",
        barb: "Conexões barb",
        twistLock: "Conexões twist-lock",
        dripSpikesStep: "Distância entre suportes para tubulação de gotejamento",
        dripCrossFittingAble: "Compatível com conexões cruzadas",
        pipesNode: "Seção de tubos",
        hdpeConnectionType: "Tipo de conexão para tubos HDPE",
        ldpeConnectionType: "Tipo de conexão para tubos LDPE",
        pvcConnectionType: "Tipo de conexão para tubos PVC",
        pipeAddon: "Aditivo para cada diâmetro de tubo",
        pipeLengthPrecision: "Casas decimais no comprimento dos tubos",
        crossFittingAble: "Compatível com conexões cruzadas",
        compress: "Conexões de compressão",
        customfit: "Conexões personalizadas",
        slip: "Slip fittings",
        wiringNode: "Seção de fiação",
        exportNode: "Opções de exportação",
        exportNumbersPrecision: "Dígitos após o ponto decimal nos números",
        basicWiringMethod: "Método de fiação de controle",
        cableCoresArray: "Faixa de número de núcleos do cabo",
        noAutoWiring: "Adicionar fiação manualmente",
        separateCableToManifold: "Separar cabo de vários núcleos para coletor",
        separateWireToValve: "Fio separado para a válvula + fio comum para o coletor",
        maxCableCores: "Núcleos máximos do cabo",
        verticalWiringAddon: "Aditivo vertical para fio do controlador",
        verticalSensWiringAddon: "Aditivo vertical para fio do sensor",
        wireAddon: "Aditivo de fio para cada tipo",
        wireLengthPrecision: "Dígitos após o ponto decimal no comprimento da fiação",
//DRAWER CONFIG
        drawerConfig: [
            "Configuração do projeto"
        ],
        //SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Consumidores",
        pressureDefinedBy: "Pressão esperada nos consumidores é",
        allowReduceRotors: "Permitir redução do raio dos rotores",
        autoconnector: "Conexão interativa de aspersores à tubulação lateral",
        radio_option_yes: "Sim",
        radio_option_no: "Não",
        extreme_rotor_reduction: "Extremo (Até 50%) (Pode causar precipitação irregular)",
        radio_option_yes2: "Sim",
        takeReductionInAccountWhenAutoPlacing: "Oferecer distâncias de lançamento reduzidas ao colocar aspersores automaticamente",
        takeReductionInAccountWhenAutoPlacingForRotors: "Oferecer distâncias de lançamento reduzidas ao colocar aspersores automaticamente (Rotors)",
        recommendedPressure: "Recomendado pelo fabricante",
        userPressure: "Definido pelo usuário",
        expPressure: "Pressão esperada no consumidor",
        sprinklerGroupMode: "Agrupando consumidores",
        safeSprGroupMode: "Modo restrito (agrupar somente compatíveis)",
        unsafeSprGroupMode: "Modo inseguro (ATENÇÃO! Sem restrições de agrupamento)",
        "sprinklerAttachBulkMode": "Modo de Conexão em Massa de Consumidores",
        "safeSprAttachMode": "Não reconectar consumidores já conectados",
        "unsafeSprAttachMode": "Modo inseguro (ATENÇÃO! Possível reconexão de consumidores já conectados. Use por sua conta e risco)",
//UNITS CONFIG
        unitsConfig: "Unidades de medida",
        precisionStd: "Casas decimais",
        unitsSystemGridAndRuler: "Sistema de unidades de medida para grade e régua",
        distanceUnits: "Distância",
        distancePrecision: "Casas decimais",
        trenchSizeUnits: "Unidades de dimensões",
        trenchSizePrecision: "Dígitos após o ponto decimal",
        sprinklerDistUnits: "Raio do aspersor",
        sprinklerDistPrecision: "Casas decimais",
        areaUnits: "Área",
        areaPrecision: "Casas decimais",
        volumeUnits: "Volume",
        volumePrecision: "Casas decimais",
        waterFlowUnits: "Vazão",
        waterFlowPrecision: "Casas decimais",
        pressureUnits: "Pressão",
        pressurePrecision: "Casas decimais",
        velocityUnits: "Velocidade",
        velocityPrecision: "Casas decimais",
        precipRateUnits: "Taxa de precipitação",
        precipRatePrecision: "Casas decimais",
        // ZONE PROPS CONFIG
        climateConfig: "Cálculo do tempo de irrigação",
        lawnCultureType: "Tipo de gramado",
        coolLoving: "Amante do clima frio",
        warmLoving: "Amante do clima quente",
        climateTemp: "Temperatura média de verão",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "Umidade média de verão",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Microclima da zona <i class='far fa-question-circle'></i>",
        microClimateTooltip: "Leve\n" +
            "Áreas de irrigação que estão na sombra, protegidas do vento e longe de objetos secos e aquecidos\n" +
            "\n" +
            "Normal\n" +
            "Lugares na paisagem onde as condições microclimáticas são representadas: a presença de\n" +
            "edifícios, calçadas e caminhos, sombra, etc. não afetam significativamente os valores de\n" +
            "evapotranspiração\n" +
            "\n" +
            "Severo\n" +
            "Reflete condições que impedem o crescimento das plantas e facilmente levam a um estado de estresse se a planta não for irrigada adequadamente. Pode ser um lugar aberto, sob sol forte, em proximidade a caminhos, edifícios ou outras estruturas da paisagem, refletindo a luz de vidros ou elementos da paisagem que absorvem calor, ou pode ser um lugar ventoso.",
        gentleMicroClimate: "Leve",
        normalMicroClimate: "Normal",
        toughMicroClimate: "Severo",
        soilType: "Composição do solo nas zonas",
        sand: "Areia",
        sandyLoam: "Solo arenoso",
        lightLoam: "Solo leve",
        mediumLoam: "Solo médio",
        heavyLoam: "Solo pesado",
        clay: "Argila",
        heavyClay: "Argila pesada",
        zoneSlope: "Inclinação geral nas zonas",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Orçamento de água",
        lowWB: "Baixo",
        normalWB: "Normal",
        highWB: "Alto",
        ft: "pés",
        in: "polegadas",
        ftin: "pés/polegadas",
        metric: "métrico",
        imperialUS: "imperial (EUA)",
//CONFIGURAÇÕES DE UNIDADES
        hydraConfig: "Hidráulica",
        waterTemp: "Temperatura da água",
        maxFlowVelocity: "Velocidade máxima de fluxo na tubulação",
        "commonConfig": "Configurações comuns",
        "lateralNozzlerSwitch": "Como mudar para o modo de fixação de bicos",
        "NStabonly": "Tab",
        "NStabshift": "Tab+Shift",
        "showActionSubtitles": "Mostrar legendas de ação",
        "Yeah": "Sim",
        "Nope": "Não",
        start: "Iniciar",
        recalibrate: "Recalibrar",
        calibrationSuccess: [
            "Calibração bem-sucedida",
            "Agora você pode usar o touchscreen em dois modos - 'mover cursor' (movimento leve ao tocar) e 'modo de arrastar' (movimento forte ao tocar)"
        ],
        calibrationFailEqual: [
            "Calibração falhou",
            "Não detectamos nenhuma diferença significativa na forma como você toca a tela em ambos os modos",
            "Você pode tentar novamente. E certifique-se de estar usando o dedo, não um estilete"
        ],
        calibrationFailImproper: [
            "Calibração falhou",
            "Detectamos maior pressão na pena do que no bigorna",
            "Você pode tentar novamente. E certifique-se de mover a pena com uma pressão mais leve do que a bigorna"
        ],
        calibrationImpossible: [
            "Calibração impossível",
            "Parece que seu dispositivo não suporta a medição da área de toque. Portanto, não podemos definir dois modos de interação por toque",
            "Neste caso, você pode usar um mouse virtual para arrastar qualquer coisa. Ele aparecerá no lado esquerdo da tela."
        ],
        calibrationNeeded: [
            "Calibração necessária!",
            "Precisamos calibrar seu touchscreen para poder definir dois modos de interação por toque:",
            "Modo de mover o cursor - quando você quer apenas mover o cursor ou deslocar o segmento do polígono ao desenhar",
            "E modo de arrastar - é quando você quer mover elementos ou redimensioná-los. Você também deve usar arrastar-mover quando quiser selecionar vários itens",
            "Por favor, clique no botão Iniciar e siga as instruções na tela"
        ],
        insertImage: 'Inserir',
        mapImagePicker: [
            "Carregador de imagem de satélite",
            "Latitude/Longitude",
            "Digite a Latitude",
            "Digite a Longitude",
            "Localização atual",
            "Ir",
            "Endereço",
            "Digite parte do endereço e clique em 'Pesquisar'",
            "Pesquisar",
            "Zoom",
            "Panorâmica"
        ],
        "imageCrop": [
            "Crop tool"
        ],
        cropImage: "Crop",
        invalid_dataset_1: 'Invalid dataset. Project contains prohibited types of surfaces. Only irrigated (LAWN), non-irrigated and obstacles are allowed.',
        invalid_dataset_2: 'Invalid dataset. Not more or less than ONE irrigated surface is allowed.',
        invalid_dataset_3: 'Invalid dataset. Irrigated surface is self-intersected.',
        invalid_dataset_4: 'Invalid dataset. Obstacle marker should not be compound (Made of more than one polygon)',
        invalid_dataset_5: 'Invalid dataset. Obstacle surface should be fully contained within irrigated surface.',
        invalid_dataset_6: 'Invalid dataset. Project contains prohibited types of sprinklers. Allowed:',
        invalid_dataset_7: 'Invalid dataset. Precipitation rate of sprinklers is out of range',
        invalid_dataset_8: 'Invalid dataset. Sprinklers must not have individual pressure settings',
        invalid_dataset_9: 'Invalid dataset. The project should not set a custom expected pressure at the sprinklers',
        invalid_dataset_10: 'Invalid dataset. Uniformity is too low.',
        invalid_dataset_11: 'Invalid dataset. Overwatered area is too big.',
        layoutPresetsMenu: [
            "Predefinições de layout",
            "Predefinição de layout atual",
            "Predefinição de conjunto de layouts",
            "Predefinição padrão para novo layout:",
            "- Escolher predefinição -",
            "- Sem predefinições disponíveis -"
        ]
    }
};
