this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "m",
        cm: "cm",
        mm: "mm",
        ft: "'",
        in: '"',
        ftin: "ft/in",
        sqm: "m2",
        acre: "ac",
        hectare: "ha",
        sqft: "sqr.ft",
        bar: "bar",
        kpa: "k Pa",
        atm: "atm",
        mH2O: "mH2O",
        psi: "psi",
        l: "l",
        m3: "m3",
        USg: "gal",
        cubft: "ft³",
        lpm: "on",
        lph: "lph",
        m3h: "m3/h",
        USgpm: "gpm",
        USgph: "gph",
        deg: "°",
        pcs: "ks",
        pcsDot: "ks.",
        pcsShort: "ks.",
        percent: "%",
        in_Alt: "dnu.",
        mps: "m/s",
        kph: "km/h",
        ftps: "ft/s",
        degreesCentigrade: "°C",
        mmph: "mm/h",
        mmp24h: "mm/deň",
        inph: "v/h",
        // unconvertable
        min: "min."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "Automatický šuflík",
        chooseSprinkler: "Vyberte dýzu:",
        auto: "Automatické nastavenie",
        waterSource2row: ["Voda", "Príjem"],
        setLineLength: "Nastaviť veľkosť čiary (mm):",
        setPressure: "Nastaviť očakávaný dynamický tlak v dýzach (bar):",
        setMaxFlow: "Nastavte maximálny prietok vody (l/min):",
        controllerShort: "C",
        sensorShort: "S",
        action_activateEraser: "Aktivovať gumu",
        action_deactivateEraser: "Deaktivovať gumu",
        action_boolUnite: "Zjednotiť",
        action_boolIntersect: "Prienik",
        action_boolSubtract: "Odčítať",
        action_boolExclude: "Vylúčiť",
        action_changeSprayBody: "Nastaviť sprej",
        action_changeVariant: "Nastaviť variant",
        action_changeImgVariant: "Nastaviť variant",
        action_changeType: "Nastaviť typ",
        action_addConsumers: "Pridať spotrebiteľov",
        action_drawBranches: "Pridať vetvy",
        action_editLine: "Upraviť segmenty",
        action_drawCircles: "Kresliť kruhy",
        action_detachAll: "Odpojiť všetko",
        action_drawBrush: "Kresliť štetec",
        action_editBrush: "Upraviť kefu",
        action_changeBrushSize: "Veľkosť kefky",
        action_booleans: "Boolean Ops.",
        action_intoPoly: "Premeniť na polygón",
        action_intoBrush: "Premeniť na štetec",
        action_activateRotation: "Otočiť",
        action_deactivateRotation: "Stále",
        action_markZones: "Zastúpenie zón",
        action_unmarkZones: "Odstrániť označenie",
        action_sprNames: "Názov kropiča",
        action_noSprNames: "Odstrániť mená",
        action_lockItem: "Zámok",
        action_unlockItem: "Odomknúť",
        Circle: "Kruh",
        Triangle: "trojuholník",
        BushForm: "Pramene",
        BushForm1: "Kríky 1",
        BushForm2: "Kríky 2",
        BushForm3: "Kríky 3",
        Square: "Štvorec",
        noShadow: "Žiadne",
        standardShadow: "Štandard",
        noArrows: "Žiadne",
        startArrow: "Na začiatku",
        endArrow: "Na konci",
        bothArrows: "Obidve strany",
        normalSizeSide: "Normálna",
        invertedSizeSide: "Vrátené",
        strMiter: "Miter",
        strRound: "Okrúhle",
        strBevel: "Bevel",
        strSquare: "Štvorec",
        strButt: "Butt",
        FWnormal: "Normálna",
        FWbold: "Tučné",
        FWitalic: "Kurzíva",
        FWbolditalic: "Kurzíva Bold",
        FJleft: "Vľavo",
        FJright: "Správne",
        FJcenter: "Stred",
        rzwHeight: "Výška"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Výber",
        //----Drawing
        selectPoly: "Žiadne označené položky",
        //----Sprinkling
        selectSprink: "Žiadne označené položky",
        lpNozzler: "Pripojenie spotrebiteľov vody",
        dl16CircDrawer: "Krúžky krúžkov položené 16/13mm",
        dl16sDrawer: "Drip cover draft 16/13mm",
        dl17CircDrawer: "Drip kruhy kladenie 17 mm",
        dl17sDrawer: "Kresba pre kvapky 17 mm",
        "ldTextDrawer": "Nastavenie textu",
        "staticTextDrawer": "Nastavenie textu",
        "dynamicTextDrawer": "Nastavenie textu",
        "ldStaticTextDrawer": "Nastavenie textu",
        "ldtextEditor": "Úprava textu",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Celková vzdialenosť",
        type: "Druh",
        variant: "Variant",
        area: "Oblasť",
        perimeter: "Perimeter",
        curveLength: "Dĺžka",
        treeDiameter: "Priemer",
        bushDiameter: "Priemer",
        nozTypes: "Dostupné typy",
        nozType: "Druh",
        sprBod: "Rozprašovacie teleso",
        rad: 'Polomer',
        angle: 'Uhol',
        reducedBy: 'Znížená',
        consump: 'Spotreba',
        pressure: 'Tlak',
        coverSize: 'Pokrytie',
        maxFlow: 'Maximálny prietok vody',
        pipesNum: "Pripojené potrubia",
        pipeType: "Druh",
        pipeLength: "Dĺžka",
        wireLength: "Dĺžka",
        valvesManifNum: "Ventily",
        valvesNum: "Ventily",
        propDiam: "Správny priemer",
        curDiam: "Priemer výkresu",
        outsNum: "Spotrebitelia vody",
        flow: "Prietok vody",
        precipRate: "Miera zrážok",
        totalPrecipArea: "Celkové pokrytie",
        uniformity: "CU",
        uniformity2: "DU",
        overwatered: "Prevodené",
        precipRateShort: "Precip.",
        runtimeInd: "Čas",
        coveredArea: "Oblasť",
        microClimateInd: "M/klimatické",
        soilTypeInd: "Pôda",
        zoneSlopeInd: "Sklon",
        maxInfiltrationRate: "Miera infiltrácie",
        waterDemand: "Dopyt po vode",
        numOfRuns: "Beží denne",
        timePerRun: "Čas na spustenie",
        dailyConsumption: "Denná spotreba",
        dripsNum: "Pripojenie kvapiek",
        dripType: "Typ kvapkania",
        dripRowsStep: "Krok povrchových riadkov",
        dripRowsAngle: "Uhol riadkov povrchu",
        cntrType: "Typ kontrolóra",
        sensType: "Typ snímača",
        zonesNum: "Kontrolované zóny",
        trenchWidth: "Šírka",
        trenchDepth: "Hĺbka",
        trenchVolume: "Objem",
        insetDiam: "Priemer",
        insetLength: "Dĺžka",
        insetVar: "Materiál",
        itemsCount: "Počet",
        insetDepth: "Hĺbka",
        zoneName: "Názov zóny",
        valveName: "Box ventilu",
        itemAlias: "Meno",
        lineWidth: "Šírka",
        lineDepth: "Hĺbka",
        lineArea: "Plocha",
        lineVolume: "Objem",
        surfaceDepth: "Hĺbka/Výška",
        surfaceVolume: "Objem",
        //MULTISELECTOR
        itemsSelected: "Vybrané",
        totalArea: "Celková plocha",
        totalPerimeter: "Celkový obvod",
        totalLength: "Celková dĺžka",
        totalVolume: "Celkový objem",
        totalConsumption: "Celková spotreba",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Neplatný polygón",
        isSelfCrossing_false: "Platný polygón",
        isConnected_true: "Pripojený",
        isConnected_false: "Nepripojený",
        isWired_true: "Drôty",
        isWired_false: "Bez drôtov",
        isDripZone_true: "Zóna kvapkania",
        isDripZone_false: "",
        isSprinklerZone_true: "Zóna kropiča",
        isSprinklerZone_false: "",
        isOverloaded_true: "Prekliaty!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Nízky tlak",
        isUnderpressured_false: "",
        isOverpressured_true: "Vysoký tlak",
        isOverpressured_false: "",
        isLocked_true: "Zamknuté",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Nehrdzavejúca oceľ",
        "High speed": "Vysoká rýchlosť",
        "Opposing nozzle": "Vzostupná dýza",
        "Plastic": "Plasty",
        "MPR Nozzles": "Trysky MPR",
        "Rotary Nozzles": "Rotačné trysky",
        Nozzles: "Trysky",
        "Bubbler nozzles": "Sondážne trysky",
        "Multi-stream": "Viacúčelové",
        "Dual-stream": "Dvojprúdové",
        "Stream Nozzles": "Streamové trysky",
        "Short Radius Nozzles": "Krátke lúčové trysky",
        "Pressure compensating": "Kompenzácia tlaku",
        "Adjustable flood": "Nastaviteľná záplava",
        Adjustable: "Nastaviteľné",
        Fixed: "Pevné",
        "Fixed Arc": "Pevný oblúk",
        "Strip Pattern": "Pruhovaný vzor",
        "Drip line": "Línia kvapkania",
        "Drip cover": "Pokrytie kvapkami",
        "16mm": "16/13 mm",
        "17mm": "17 mm",
        "emitter": "S emitormi",
        "noemitter": "Emitteri",
        "Root zone watering": "Zalievanie koreňovej zóny",
        Lateral: "Bočné",
        Main: "Hlavné",
        Trench: "Trench",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC [metric]",
        ldpe: "LDPE",
        Controller: "Kontrolór",
        Sensor: "Senzor",
        Wiring: "Spojenie",
        IrrigateMarks: "Zóna",
        Surface: "Plocha",
        Lawn: "trávnik",
        Bed: "Posteľ",
        Shrubs: "Krevety",
        Path: "Cesta",
        Concrete: "Betón",
        Sand: "Piesok",
        Water: "Voda",
        Bedding: "Posteľná bielizeň",
        Flower: "kvet",
        Herbal: "bylinné",
        geographic: "Geografické",
        loSurface: "Povrch",
        loStdSurf: "Štandardné (Polygón)",
        loStdSurf_BRUSH: "Štandardné (Štetec)",
        sizeMark: "Rozmery",
        scalingBar: "Scaling bar",
        loCurves: "Čiary",
        texts: "Texty",
        staticText: "Statický text",
        dynamicText: "Dynamický text",
        stampText: "Text pečiatky",
        stampTextDefault: "Text",
        stampTextgr1: "Definícia dokumentu",
        stampTextgr2: "Adresár",
        stampTextgr3: "Názov lokality",
        stampTextgr4: "Názov výkresu",
        stampTextgr9: "Informácie o organizácii",
        stampTextgr6t: "Štádium",
        stampTextgr7t: "Strana",
        stampTextgr8t: "Stránky",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "Ch.",
        stampTextgr15t: "Prtcp.",
        stampTextgr16t: "Strana",
        stampTextgr17t: "# Doc.",
        stampTextgr18t: "Podpíš.",
        stampTextgr19t: "Dátum",
        stampTextgr20t: "Orig. Inv.#",
        stampTextgr21t: "Podpis'n'Dátum",
        stampTextgr22t: "Repl. Inv.#",
        inserts: "Rúrky",
        poly: "Polygón",
        brush: "Štetec",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "Zobraziť správcu vrstiev",
        hideLM: "Skryť správcu vrstiev",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Bez mena",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "Rozloženie exportu",
        successExporting: "Úspešne vyvezený",
        failExporting: "Export zlyhal",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>Dosiahnutý denný limit</a>",
        exportingLimit: "Limit:",
        exportingLeft: "Vľavo dnes:",
        pdfExportingPopUpBlocked: "Váš prehliadač zablokoval pop-up okno. Prosím, pop-up pre túto stránku získať. Súbor PDF",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "Vyskakovacie vlákno",
        tt_group_MT: "Muži",
        tt_group_FT: "Ženy",
        tt_riserHeight: "Výška závitu",
        tt_pressureReg: "Regulátor tlaku",
        tt_checkValve: "(s kontrolným ventilom)",
        tt_home: "Domov",
        tt_prev: "Predchádzajúca",
        tt_next: "Nasledujúci",
        tt_end: "Koniec",
        tt_add: "Pridať",
        tt_clone: "Klon",
        tt_remove: "Odstrániť",
        tt_rename: "Premenovať",
        tt_addToFav: "Pridať do obľúbených",
        tt_remFromFav: "Odstrániť z obľúbených",
        tt_presets: "Prednastavenia",
        tt_MagicAutoPlacer: "",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "N",
        S: "S",
        E: "E",
        W: "Z",
        //conventions
        sprinklers: "Zavlažovače",
        dripStarts: "Štart kvapkania",
        rzwLayer: "Zalievanie koreňovej zóny",
        dripLines: "Línia kvapkania",
        valvesLayer: "Ventilačné potrubie",
        waterSources: "Zdroj vody",
        quickCoupLayer: "Rýchle spojenie",
        controllers: "Kontrolór",
        sensorsLayer: "Senzor",
        mainPipes: "Hlavné potrubie",
        lateralPipes: "Bočné potrubie",
        lateralPipes_sprinklerZone: "Zóna",
        lateralPipes_dripZone: "Zóna (čiarky)",
        lateralPipes_rzwZone: "Zóna (zavlažovacia zóna)",
        lateralPipes_emptyZone: "Zóna (W/O spotrebitelia)",
        trenchesLayer: "Zákopy",
        insetsLayer: "Dlaždice",
        wiresLayer: "Elektroinštalácia",
        wirelessLayer: "Bezdrôtové pripojenie",
        senswirelessLayer: "Bezdrôtové pripojenie snímača",
        senswiresLayer: "Kabeláž senzorov",
        surfaces: "Plocha",
        ldItemsLayer: "Rastliny",
        covers: "Oblasť pokrytia",
        nameplates: "Informácie pre spotrebiteľov",
        oreolas: "Značky spotrebiteľov",
        pipeInfo: "Informácie o potrubiach",
        lines: "riadky",
        overlays: "Prekrytia",
        stampLayer: "Rámček",
        stampTexts: "Texty pečiatky",
        //zonesTable
        zoneType: "Typ zóny",
        color: "Farba",
        consumers: "Spotrebitelia",
        waterFlow: "Prietok",
        sprinklerZone: "Kropič",
        dripZone: "Drip",
        rzwZone: "Koreňové zavlažovanie",
        emptyZone: "Žiadni spotrebitelia",
        specifyDiagonal: "Prosím, zadajte svoj monitor uhlopriečku v palcoch",
        //sprinklersTable
        consType: "Druh",
        consName: "Názov",
        zoneNum: "Zóna",
        sector: "Sektor",
        radius: "Polomer",
        reducedBy: "Znížená",
        nozzle: "Trysky",
        rotor: "Rotor",
        bubbler: "Bublina",
        bubblerNozzle: "Bubble-Nozzle",
        //dripsTable
        catId: "Cat. ID",
        brand: "Značka",
        emitterStep: "Krok",
        emitterFlow: "Prietok",
        //layersManangerSpecific
        consumersGrp: "Spotrebitelia",
        nodesGrp: "Uzly",
        wiresGrp: "Drôty",
        pipesGrp: "Rúrky",
        landscapeGrp: "Krajina",
        allTogether: "Všetky"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "Druh",
        brand: "Brand",
        catid: "Cat. ID",
        title: "Názov",
        units: "Jednotky",
        amount: "Suma",
        //predetermined
        dripLine: "Línia kvapkania",
        dl16: "Drip linka 16/13mm",
        dl17: "Línia kvapkania 17 mm",
        dripStart: "Štart kvapkania",
        ds16: "Začiatok kvapkania 16/13mm",
        ds17: "Štart kvapkania 17 mm",
        manifold_no_lps_issue: "Žiadne prepojené zóny",
        manifold_no_mp_issue: "Nie je pripojený k hlavnej linke",
        manifold_no_wr_issue: "Žiadny pripojený ovládací drôt",
        //nodes-----------------------------------
        sprinkler_unattached: "UPOZORNENIE!!! Máte nezaradené Sprinklers (nebudú prezentované v konečnom prehľade)",
        drip_unattached: "UPOZORNENIE!!! Máte nezaradené drip zavlažovacie prvky (nebudú prezentované vo finálnom prehľade)",
        mains_unattached: "UPOZORNENIE!!! Máte samostatné MAINLINES (nebudú prezentované v konečnom prehľade)",
        mains_empty: "UPOZORNENIE!!! Máte MAINLINES bez spotrebiteľov (nebudú prezentované vo finálnom prehľade)",
        laterals_unattached: "UPOZORNENIE!!! Máte nezaradené LATERAL PIPES (nebudú prezentované v záverečnom prehľade)",
        laterals_empty: "UPOZORNENIE!!! Máte LATERAL PIPES bez spotrebiteľov (nebudú prezentované v záverečnom prehľade)",
        rzw_unattached: "UPOZORNENIE!!! Máte nezaradené ROOT ZONE VODNÉ prvky (nebudú prezentované vo finálnom prehľade)",
        sensors_unattached: "UPOZORNENIE!!! Máte nezávislých SENSORS (nebudú prezentované v záverečnom prehľade)",
        manifolds_unfinished: "UPOZORNENIE!!! Máte nedokončené manifolds (nemôžete súťažiť konfiguráciu ventilov)",
        control_wires_unattached: "UPOZORNENIE!!! Máte neprepojené ovládacie drôty",
        control_wires_empty: "UPOZORNENIE!!! Máte ovládacie drôty bez pripojených ventilov",
        cntr_wr_unattached: "Ovládací drôt",
        youCanSeeThemInTheDrawing: "Môžete vidieť každý prvok na výkrese, stlačením 'oka' na ľavej strane riadku prvku",
        sprinkler_nozzleMT: "Kropiaci uzol (trojka s ženským závitom)",
        sprinkler_nozzleFT: "Kropiaci uzol (trojka s mužskou niťou)",
        "sprinkler_rotor1/2F": "Kropiaci uzol (Rotor) 1/2\"female",
        "sprinkler_rotor3/4F": "Kropiaci uzol (Rotor) 3/4\"",
        "sprinkler_rotor1F": "Kropiaci uzol (Rotor) 1\"",
        "sprinkler_rotor11/4F": "Kropiaci uzol (Rotor) 1 1/4\"",
        "sprinkler_rotor11/2F": "Kropiaci uzol (Rotor) 1 1/2\"",
        "sprinkler_rotor2F": "Kropiaci uzol (Rotor) 2\"",
        "sprinkler_rotor1/2M": "Kropiaci uzol (Rotor) 1/2\"male",
        "sprinkler_rotor3/4M": "Sprinkler node (Rotor) 3/4\" male",
        "sprinkler_bubbler1/2F": "Kropiaci uzol (Bubbler)",
        sprinkler_bubblerNozzleMT: "Kropiaci uzol (bublínová tryska s ženským závitom)",
        sprinkler_bubblerNozzleFT: "Kropiaci uzol (bublínová tryska s mužskou niťou)",
        dripIrrigation16: "Zavlažovanie kvapkaním (16/13mm)",
        dripIrrigation17: "Zavlažovanie kvapkaním (17 mm)",
        rootZoneWatering: "Zavlažovací systém koreňovej zóny",
        manifold: "Uzol potrubia ventilov",
        automation: "Automatický uzol",
        mainPipes_hdpePE80SDR11: "Hlavné rúry HDPE SDR 11",
        mainPipes_hdpePE80SDR136: "Hlavné rúry HDPE SDR 13.6",
        mainPipes_hdpePE80SDR176: "Hlavné rúry HDPE SDR 17,6",
        lateralPipes_hdpePE80SDR11: "Bočné potrubie HDPE SDR 11",
        lateralPipes_hdpePE80SDR136: "Bočné potrubie HDPE SDR 13,6",
        lateralPipes_hdpePE80SDR176: "Bočné potrubie HDPE SDR 17,6",
        mainPipes_hdpeSDR9: "Hlavné rúry HDPE SDR 9",
        mainPipes_hdpeSDR11: "Hlavné rúry HDPE SDR 11",
        mainPipes_hdpeSDR136: "Hlavné rúry HDPE SDR 13.6",
        mainPipes_hdpeSDR17: "Hlavné rúry HDPE SDR 17",
        mainPipes_hdpeSDR176: "Hlavné rúry HDPE SDR 17,6",
        lateralPipes_hdpeSDR9: "Bočné potrubie HDPE SDR 9",
        lateralPipes_hdpeSDR11: "Bočné potrubie HDPE SDR 11",
        lateralPipes_hdpeSDR136: "Bočné potrubie HDPE SDR 13,6",
        lateralPipes_hdpeSDR17: "Bočné potrubie HDPE SDR 17",
        lateralPipes_hdpeSDR176: "Bočné potrubie HDPE SDR 17,6",
        mainPipes_pvcSCH40: "Hlavné rúry PVC SCH40",
        mainPipes_pvcSCH80: "Hlavné rúry PVC SCH80",
        mainPipes_pvcCL315: "Hlavné rúry PVC TRIEDA 315",
        mainPipes_pvcCL200: "Hlavné rúry PVC TRIEDA 200",
        mainPipes_pvcCL160: "Hlavné rúry PVC TRIEDA 160",
        mainPipes_pvcCL125: "Hlavné rúry PVC TRIEDA 125",
        mainPipes_pvcUSCJPN18: "Hlavné rúry PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Hlavné rúry PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Hlavné rúry PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Hlavné rúry PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Hlavné rúry PVC-U SCJ (PN4.5)",
        mainPipes_ldpeCLASS3: "Hlavné rúry LDPE TRIEDA 3",
        lateralPipes_pvcSCH40: "Bočné potrubie PVC SCH40",
        lateralPipes_pvcSCH80: "Bočné potrubie PVC SCH80",
        lateralPipes_pvcCL315: "Bočné potrubie PVC TRIEDA 315",
        lateralPipes_pvcCL200: "Bočné potrubie PVC TRIEDA 200",
        lateralPipes_pvcCL160: "Bočné potrubie TRIEDA 160 PVC",
        lateralPipes_pvcCL125: "Bočné potrubie TRIEDA 125 PVC",
        lateralPipes_pvcUSCJPN18: "Bočné rúry PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Bočné rúry PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Bočné rúry PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Bočné rúry PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Bočné potrubia PVC-U SCJ (PN4.5)",
        lateralPipes_ldpeCLASS3: "Bočné potrubie LDPE TRIEDA 3",
        wiring: "Elektroinštalácia",
        qcv: "Rýchlospájacie ventily",
        fixedCntr: "pevné",
        stand_aloneCntr: "Stojte sami",
        modularCntr: "modulárny",
        decoderCntr: "dekodér",
        inset: "Potrubie",
        insets: "Dlaždice",
        //-----------------------------------------
        novar: "žiadne varianty",
        choosevar: "Vybrať variant",
        //element.types----------------------------
        nozzle: "Nozzle",
        rotor: "Rotor",
        rotorNozzle: "Rotorová dýza",
        bubbler: "Bubbler",
        bubblerNozzle: "Bublinka",
        rzw: "Zavlažovací systém koreňovej zóny",
        sprayBody: "Rozprašovacie teleso",
        sprinklerStandAssembly: "Stojan na kropenie (Riser)",
        outBarb: "Barb-to-nozzle",
        flexPipe: "Zábavné potrubie",
        sj: "Swing kĺb",
        inBarb: "Barb-to-pipe",
        midSprinkPipeFitting: "Montáž viazania",
        endSprinkPipeFitting: "Montáž koncoviek",
        midRZWPipeFitting: "Montáž viazania",
        endRZWPipeFitting: "Montáž koncoviek",
        dripPipe: "Kvapkové potrubie",
        blindPipe: "Slepé hadice",
        dripTeeFitting: "Drip tee",
        dripCapFitting: "Čiapka na kvapkanie",
        dripCouplingFitting: "Spriahadlo na kvapkanie",
        dripElbowFitting: "Drip lakeť",
        dripSpike: "hrot kvapkadla",
        sprinklerZoneValve: "Kropiace pásmo ventil",
        emptyZoneValve: "Ventil w/o spotrebitelia",
        valveOutFitting: "Ventil-to-zóna",
        dripZoneValve: "Ventil odkvapkávacej zóny",
        rzwZoneValve: "Root zavlažovací ventil",
        pressureReg: "Regulátor tlaku",
        filter_pressureReg: "Filter s regulátorom tlaku",
        controller: "Kontrolór",
        flowMeter: "Prietokomer",
        rainSensor: "Dážďový senzor",
        soilSensor: "Snímač pôdy",
        freezeSensor: "Snímač mrazu",
        wrFreezeSensor: "Bezdrôtový senzor pre dážď/mrazenie",
        windSensor: "Snímač vetra",
        solarSensor: "Solárny snímač",
        flowSensor: "Snímač prietoku",
        weatherStation: "Meteorologická stanica",
        solarPanel: "Solárny panel",
        mainPipe: "Hlavné potrubie",
        teeFitting: "Tee",
        elbowFitting: "Kolená",
        reducerFitting: "Redukátor",
        lateralPipe: "Bočné potrubie",
        capFitting: "Viečko",
        basicCable: "Základný kábel",
        basicWire: "Základné drôty",
        sensorCable: "Drôty zo snímačov počasia",
        qcPlastic: "Q/C Plastové ventily",
        qcMetal: "Q/C Kovové ventily",
        gateway: "Brána",
        antExt: "Rozšírenie antény",
        loramod: "Moduly LoRa",
        //typesOfAcessories
        hdpeCOR: "Vlnité rúry",
        expModule: "Modul rozšírenia",
        rzwSleeve: "Textílie",
        rwCap: "Rekultivovaný uzáver vody",
        gutterMount: "Uchytenie odlučovača",
        delayRelay: "Oneskorené relé",
        fctFlow: "FCT Name",
        fctBspAdap: "Adaptér pre montáž FCT",
        drainCheckValve: "Kontrolný ventil",
        rwId: "ID obnovenej vody",
        vpc: "Vandalový uzáver",
        inletFilter: "Vstupný filter",
        wifiModule: "Wi-Fi modul",
        wallMount: "Montáž na stenu",
        rwsSock: "Textílie",
        rwsGrate: "Graf pre RWS",
        npCover: "Krytina nepožierateľná",
        sprExt: "Rozprašovanie",
        popUpToThread: "Rozprašovací adaptér",
        valveBox: "Skriňa ventilu",
        valveBoxExt: "Rozšírenie ventilového boxu",
        qcPlasticKey: "Kľúč pre Q/C Ventil",
        qcPlasticElbFit: "Montáž lakťa",
        qcMetalKey: "Kľúč pre Q/C Ventil",
        qcMetalElbFit: "Montáž lakťa",
        qcMetalCapKey: "Kryt kľúča",
        insTape: "Izolačná páska",
        wrConn: "Konektor",
        shrinkTube: "Teplo zrážacia rúrka",
        hcFrontPanel: "Predný panel",
        ball_valve: "Guľový ventil",
        check_valve: "Kontrolný ventil",
        thread_manifold: "Manifold",
        plastic_filter: "Filter (plast)",
        waterMeter: "Merač vody",
        rfModule: "Rádiový modul",
        largeAntenna: "Anténa",
        wifiHub: "Name",
        handRemoteKit: "Vzdialená súprava",
        handRemote: "Vzdialený",
        wifiBundleKit: "Comment Kit",
        //typesOfFittings
        //drip
        barb_cap_8: "Koniec kvapkania",
        barb_elbow_PP: "Barb lakeť",
        barb_elbow_PT: "Barb lakť na vlákno",
        barb_tee_PPP: "Barb tee",
        barb_coupling_PP: "Barbové spojovacie zariadenie",
        barb_cross_PPPP: "Barb cross",
        barb_cap_P: "Barb end cap",
        barb_coupling_PT: "Barbové spojenie s niťou",
        barb_tee_PTP: "Barb tee na vlákno",
        barb_valve_PT: "Barbový ventil na závit",
        barb_valve_PP: "Barbový ventil",
        twlc_elbow_PP: "Twist-lock lakeť",
        twlc_tee_PPP: "Twist-lock tee",
        twlc_coupling_PP: "Twist-lock spojenie",
        twlc_cross_PPPP: "Twist-lock cross",
        twlc_cap_P: "Twist-lock koncový kryt",
        twlc_coupling_PT: "Pripojenie k závitom",
        twlc_tee_PTP: "Twist-lock tee na vlákno",
        twlc_valve_PT: "Twist-lock ventil na niť",
        twlc_valve_PP: "Twist-lock ventil",
        dl_valves: "Špeciálne ventily",
        //pipe
        hdpeSDR9: "HDPE rúrka SDR 9",
        hdpeSDR11: "Potrubie HDPE SDR 11",
        hdpeSDR136: "HDPE rúrka SDR 13,6",
        hdpeSDR17: "Potrubie HDPE SDR 17",
        hdpeSDR176: "HDPE rúrka SDR 17,6",
        ldpeSDR9: "Potrubie LDPE SDR 9",
        ldpeSDR11: "Potrubie LDPE SDR 11",
        ldpeSDR136: "Rúrka LDPE SDR 13,6",
        ldpeSDR17: "Potrubie LDPE SDR 17",
        pvcSCH40: "Pipe PVC SCH40",
        pvcSCH80: "Pipe PVC SCH80",
        pvcCL315: "Rúrka PVC TRIEDA 315",
        pvcCL200: "Rúrka PVC TRIEDA 200",
        pvcCL160: "Rúrka PVC TRIEDA 160",
        pvcCL125: "Rúrka PVC TRIEDA 125",
        pvcUSCJPN18: "Pipeta PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Potrubie PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Potrubie PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Potrubie PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Pipeta PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "Rúrka LDPE TRIEDA 3",
        compress_elbow_PT: "Kompresia/kolesový lakeť",
        compress_coupling_PT: "Kompresné/prečítané spojenie",
        compress_tee_PTP: "Kompresia/Thread Tee",
        compress_cap_P: "Zástrčka na koniec kompresie",
        compress_elbow_PP: "Kompresný lakeť",
        compress_coupling_PP: "Kompresné spojenie",
        compress_tee_PPP: "Kompresné kamienky",
        compress_cross_PPPP: "Krížová kompresia",
        compress_single_clamp_saddle: "Jednodielne sedlo",
        compress_ballvalve_PP: "Kompresný guľový ventil",
        compress_ballvalve_PT: "Kompresný/Threadový guľový ventil",
        customfit_elbow_PT: "Vlastný/Thread lakeť",
        customfit_coupling_PT: "Vlastné/Threadové spojenie",
        customfit_tee_PTP: "Vlastné/Thread tee",
        customfit_cap_P: "Vlastná koncová zásuvka",
        customfit_elbow_PP: "Vlastný lakeť",
        customfit_coupling_PP: "Vlastné spojenie",
        customfit_tee_PPP: "Vlastné odtie",
        customfit_cross_PPPP: "Vlastný kríž",
        customfit_single_clamp_saddle: "Jednodielne sedlo",
        customfit_ballvalve_PP: "Custom Ball ventil",
        customfit_ballvalve_PT: "Vlastný/Thread Guľový ventil",
        thread_nipple: "bradavka",
        thread_coupling: "Spojka",
        thread_mf_reducer: "Znižovač mužských/ženských žien",
        thread_mf_adapter: "Adaptér pre mužov/ženy",
        thread_mf_bush: "ker samčí/ženský",
        thread_tee: "Dievčatá",
        thread_elbow: "Ženské lakte",
        thread_mf_elbow: "Muž/žena lakeť",
        thread_cap: "Ženská čiapka",
        thread_plug: "Zástrčka pre mužov",
        thread_union_nut: "Marhule",
        thread_cross: "Kríž",
        cable: "Kábel",
        wire: "Drôty",
        // slip
        slip_single_clamp_saddle: "Jednosvorné sedlo (na PVC potrubí)",
        slip_elbow_PT: "Klzký lakeť",
        slip_coupling_PT: "Spriahadlo so slipom/závitom",
        slip_tee_PTP: "Sklz/závit",
        slip_cap_P: "Sklzu koncovej zásuvky",
        slip_elbow_PP: "Slip lakeť",
        slip_coupling_PP: "Spriahadlo",
        slip_tee_PPP: "Slip tee",
        slip_cross_PPPP: "Preklzu",
        slip_ballvalve_PP: "Slip Guľový ventil",
        slip_ballvalve_PT: "Slip/Thread Guľový ventil",
        //extendables
        arbitraryFittings: "Arbitrážne príslušenstvo",
        dripStartAssembly: "Štartovacia zostava kvapkania",
        intakeAssembly: "Sacie súpravy",
        offtakeAssembly: "Zber ľubovoľného príslušenstva",
        numofvalves: "Počet ventilov:",
        numofvalvesshort: "Ventily:",
        numofmanifs: "Počet potrubí:",
        intakePipeSize: "Veľkosť sacieho potrubia:",
        valveBoxes: "Skrine ventilov",
        valveAccessories: "Príslušenstvo ventilov",
        oneValveAccessories: "Príslušenstvo ventilov",
        controllerAccessories: "Príslušenstvo regulátora",
        sensorAccessories: "Príslušenstvo senzorov",
        sprBodyAccessories: "Príslušenstvo k rozprašovaciemu telu",
        rzwAccessories: "Root zóna zalievanie príslušenstvo",
        pipeStartFittings: "Prípojné príslušenstvo hlavného potrubia",
        qcAccessories: "Príslušenstvo k ventilom Q/C",
        wiringAccessories: "Príslušenstvo k inštalácii",
        pipeSize: "Veľkosť potrubia:",
        endOfPipe: "(Koniec polohy)",
        midOfPipe: "(Prierez)",
        emptyRender: [
            "Prepáč... žiadny obsah",
            "Máte úplne dokončený niektorý zo zavlažovacích uzlov, ktoré majú byť vykreslené"
        ],
        serviceFail: [
            "Prepáčte... špecifikácia služby je momentálne nedostupná",
            "Prosím, skúste to neskôr, kedy bude nadviazané pripojenie",
            "Všimnite si, že konfigurácia, ktorú ste urobili predtým bude uložená hoci"
        ],
        serviceTrialExpired: [
            "Prepáčte... špecifikácia renderovanie služba nie je k dispozícii pre váš účet",
            "To znamená, že vaša skúšobná doba skončila, a ak chcete používať túto službu",
            "<a href='/account/subscription'>Môžete aktualizovať na PRO účet</a>"
        ],
        serviceLimitReached: [
            "Dosiahli ste denný limit vykresľovania špeciálnych listov",
            "Odstrániť limit počtu špecifikácií za deň",
            "<a href='/account/subscription'>Môžete aktualizovať na PRO účet</a>"
        ],
        findInDrawing: "Zobraziť na plátne",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "Pipping",
        labours_group_fittings: "Príslušenstvo",
        labours_group_valveBoxes: "Skrine ventilov",
        labours_group_wires: "Elektroinštalácia",
        labours_group_sprinklers: "Zavlažovače",
        labours_group_rws: "Zalievanie koreňovej zóny",
        labours_group_sprinklerConnections: "Kropiace spojenia",
        labours_group_drip: "Linky a príslušenstvo",
        labours_group_manifolds: "Manifoldy",
        labours_group_quickCoupling: "Rýchle spojenie",
        labours_group_controllers: "Kontrolóri",
        labours_group_sensors: "Snímače",
        labours_group_trenches: "Zákopy",
        labours_group_insets: "Nádoby na rúrky",
        labours_group_lawns: "trávnik",
        labours_group_irrigatedArea: "Zavlažovaná plocha",
        labours_group_arbitrary_sp: "💦 Vlastné prvky zavlažovania",
        labours_group_arbitrary_ld: "🌳 Vlastné prvky krajiny",
        ldArbitrary_equip: "Zariadenie",
        ldArbitrary_labour: "Práca",
        spArbitrary_equip: "Zariadenie",
        spArbitrary_labour: "Práca",
        arbitrary_sp: '💦 Vlastné prvky zavlažovania',
        arbitrary_ld: '🌳 Custom Landscape elements',
        ldLine_labour: "Čiara",
        ldLine_equip: "Čiara",
        spLine_labour: "Čiara",
        spLine_equip: "Čiara",
        ldLineWithArea_labour: "Čiara (m2)",
        ldLineWithArea_equip: "Čiara (m2)",
        spLineWithArea_labour: "Čiara (m2)",
        spLineWithArea_equip: "Čiara (m2)",
        ldVolumetricLine_labour: "Čiara (m3)",
        ldVolumetricLine_equip: "Čiara (m3)",
        spVolumetricLine_labour: "Čiara (m3)",
        spVolumetricLine_equip: "Čiara (m3)",
        polyLdSurface_labour: "Plocha",
        brushLdSurface_labour: "Plocha",
        polyLdSurface_equip: "Plocha",
        brushLdSurface_equip: "Plocha",
        polySpSurface_labour: "Plocha",
        brushSpSurface_labour: "Plocha",
        polySpSurface_equip: "Plocha",
        brushSpSurface_equip: "Plocha",
        polyLdVolumetricSurface_labour: "Plocha (m3)",
        brushLdVolumetricSurface_labour: "Plocha (m3)",
        polyLdVolumetricSurface_equip: "Plocha (m3)",
        brushLdVolumetricSurface_equip: "Plocha (m3)",
        polySpVolumetricSurface_labour: "Plocha (m3)",
        brushSpVolumetricSurface_labour: "Plocha (m3)",
        polySpVolumetricSurface_equip: "Plocha (m3)",
        brushSpVolumetricSurface_equip: "Plocha (m3)",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\ x 00", "Január", "Február", "Marec", "Apríl", "Máj", "Jún", "Júl", "August", "september", "Október", "November", "December"],
        MMM: ["\ x 01", "Jan.", "Feb", "Mar", "Apríl", "Máj", "Jun", "Júl", "Aug", "Sep.", "Okt", "Nov", "Dec"],
        dddd: ["\ x 02", "Nedeľa", "pondelok", "Utorok", "Streda", "Štvrtok", "Piatok", "Sobota"],
        ddd: ["\ x03", "Slnko", "Po", "Ut", "St", "Št", "Pi", "So"],
        //buttonsCaps
        ok: "Dobre.",
        save: "Uložiť",
        apply: "Použiť",
        defaults: "Štandardy",
        retry: "Obnovenie",
        finish: "Dokončiť",
        safeRestart: "Bezpečný reštart",
        saveAndExit: "Uložiť a ukončiť",
        exit: "Výstup",
        cancel: "Zrušiť",
        rename: "Premenovať",
        idk: "Neviem.",
        getFile: "Získať súbor",
        reset: "Resetovať",
        random: "Náhodne",
        //misc
        zoneNum: "Zóna #",
        valveNum: "Valve Box #",
        zonesColoring: "Zastúpenie zón",
        coversColoured: "Kryty rozprašovačov na farby",
        dripsColoring: "Drip linky sfarbenie",
        dripsSameAsZonesColored: "Drip linka farebné v jeho zóne farby",
        //saveOflline
        saveOffline: [
            "Prepáčte... spojenie je stratené.",
            "Ale nebojte sa, môžete pokračovať so svojím projektom v režime offline.",
            "Kým ste offline - všetky vaše úspory budú uložené ako textový súbor vo vašom prehliadači sťahuje priečinok.",
            "A neskôr môžete nahrať najnovšiu verziu výkresu na server."
        ],
        restartOffline: [
            "Prepáčte... spojenie je stratené.",
            "Ale nebojte sa, váš projekt bol uložený lokálne na vašom počítači.",
            "Môžete ho nájsť v priečinku sťahovania prehliadača.",
            "Ak chcete pracovať offline, môžete si stiahnuť offline inventár aplikácie zo svojej skrine na http://www.irrisketch.com"
        ],
        brokenSaving: [
            "Prepáč... niečo sa pokazilo pri nakladaní tvojho projektu.",
            "Zdá sa, že vaša predchádzajúca záchrana bola nejako skazená.",
            "Ale neboj sa, môžeme to opraviť.",
            "Váš projekt bude vo vašej dielni označený ako 'Broken.'",
            "A naše technické veci vyriešia túto situáciu čo najskôr."
        ],
        corruptedSavingFile: [
            "Prepáčte... súbor, ktorý sa snažíte načítať, nie je čitateľný.",
            "Ale neboj sa, môžeme to opraviť.",
            "Všetko, čo potrebujete, je predložiť tento rozbitý súbor vo Vašom načítacom formulári.",
            "A potom sa pokúsime dostať ho späť do práce."
        ],
        ajaxReqFail: [
            "Prepáč... Stratili sme spojenie so serverom",
            "Momentálne nie je možné posielať/prijímať žiadne údaje",
            "Prosím, skúste to neskôr."
        ],
        critical: [
            "Prepáč... niečo sa pokazilo.",
            "Ale nebojte sa, vaša kresba je na bezpečnom mieste teraz, stačí kliknúť safe-restart tlačidlo pokračovať..."
        ],
        fatal: [
            "Prepáč... niečo sa pokazilo.",
            "Prosím, pomôžte nám zlepšiť naše služby. Opíšte, po akých krokoch došlo k tejto chybe",
            "Uveďte informácie tu"
        ],
        areYouSure: [
            "Chystáte sa ukončiť tento projekt",
            "Všimnite si, že všetky neuložené zmeny budú stratené."
        ],
        pickAnotherCSVFile: "Vyber si inú.",
        csvFileTooBig: [
            "Prekročená maximálna veľkosť súboru csv",
            "Pre optimalizáciu je maximálne spracovanie csv súboru limitované 4Mb"
        ],
        notAnCSV: [
            "Prepáčte, tento typ súboru nie je podporovaný",
            "Podporované formáty: .csv"
        ],
        invalidCSV: [
            "Neplatný obsah súboru CSV",
            "Chyba analýzy exportného súboru aplikácie Moasure, skontrolujte, či bol súbor správne exportovaný"
        ],
        pickAnotherImage: "Vyber si inú.",
        imageTooBig: [
            "Prekročená maximálna veľkosť obrázku",
            "Pre optimalizáciu je maximálna manipulácia s obrázkom obmedzená 10Mb"
        ],
        notAnImage: [
            "Prepáčte, tento typ súboru nie je podporovaný",
            "Podporované formáty obrázkov: .pdf .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "OBMEDZENÉ opatrenie",
            "Táto akcia nie je povolená na bezplatné predplatné"
        ],
        goPro: 'GO PRO',
        renameLayout: "Zadajte nové meno",
        areYouSureDeleteLayout: [
            "Pozor! Toto opatrenie nemožno zrušiť",
            "Naozaj chcete odstrániť:",
            "Odstrániť"
        ],
        setUnderlaySize: [
            "Nastaviť dĺžku čiary, ktorú ste práve nakreslili",
            "Zadali ste nesprávnu hodnotu. Prosím, skúste to znova."
        ],
        setMonitorDiagonal: [
            "Prosím, dajte nám informácie o uhlopriečke monitorov",
            "Zadali ste nesprávnu hodnotu. Prosím, skúste to znova."
        ],
        getSpecsTable: [
            "Nastaviť nastavenia výstupov špecifikácie",
            "Skupinové vybavenie",
            "Uzol", "Značka",
            "Nastaviť typ súboru ako",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "Zadajte názov",
            "Outlay #",
            "Uložiť",
            "Ukladanie špecifikácií",
            "Hotovo. Kliknite tu pre otvorenie",
            "Ukladanie zlyhalo",
            "Aktualizovať existujúce výdavky",
            "Aktualizácia",
            "Aktualizácia výdavkov"
        ],
        exportLayoutsAsPdf: [
            "Vyberte rozloženie na export",
            "samostatné súbory (vo vývoji)",
            "jeden album",
            "Vývoz",
            "Exportovať rozloženie v"
        ],
        differentSprGroups: [
            "Nepodarilo sa pripojiť na túto rúru rôzne typy odberateľov vody",
            "Podľa noriem návrhu zavlažovania je neprijateľné miešať rôzne typy odberateľov vody alebo rozprašovačov s rôznymi mierami zrážok v tej istej zóne."
        ],
        tooFarAwaySpr: [
            "Nepodarilo sa spojiť spotrebiteľov",
            "Niektorí spotrebitelia sú príliš ďaleko od bočnej rúry na pripojenie. Maximálna vzdialenosť pripojenia, ktorú môžete nastaviť v menu preferencií"
        ],
        outlayerConfig: [
            "Konfigurácia špecifikačného hárku"
        ],
        presetsMenu: {
            title: "Prednastavenia",
            titleTextboxLabel: "Prednastavené titulky",
            descriptionTextboxLabel: "Opis tovaru",
            applyButton: "<i class='far fa-check-circle'></i>&nbsp;Použiť",
            defaultButton: "<i class='far fa-undo'></i>&nbsp;Nastaviť štandardne",
            removeButton: "<i class='far fa-trash'></i>&nbsp;Odstrániť",
            updateButton: "<i class='far fa-sync'></i>&nbsp;Aktualizácia",
            createButton: "<i class='far fa-plus'></i>&nbsp;Vytvoriť nové",
            closeButton: "<i class='far fa-times'></i>&nbsp;Zavrieť",
            favorites_drawing: "Obľúbené nástroje (Landscape)",
            favorites_sprinkling: "Obľúbené nástroje (zavlažovanie)",
            favorites_layouting: "Obľúbené nástroje",
            configs_drawing: "Nastavenie projektu",
            configs_outlayer: "Nastavenie hárku špecifikácie",
        },
        newPresetItem: "Nová prednastavená",
        cL_alreadyConnected: [
            "Zlyhalo spojenie riadkov",
            "Tieto línie sú spojené s"
        ],
        cL_segOnElem: [
            "Zlyhalo spojenie riadkov",
            "Nemôžete sa pripojiť k segmentu, ktorý je na"
        ],
        cL_strangeError: [
            "Zlyhalo spojenie riadkov",
            "Prepáčte...Konnekcia zlyhala"
        ],
        cL_misgrouping: [
            "Zlyhalo spojenie riadkov",
            "Tieto linky majú spotrebiteľov, ktorým sa neodporúča umiestniť do tej istej zóny. Ak ich chcete pripojiť aj tak, zapnite 'Nebezpečný režim' pre zoskupovanie posypov v konfigurácii projektu"
        ],
        cL_valve: "Ventily",
        cL_waterSource: "Zdroj vody",
        cL_dripStart: "Štart kvapkania",
        cL_controller: "Kontrolór",
        cL_sensors: "Senzor",
        cL_valves: "Ventily",
        cL_notSameVariant: [
            "Zlyhalo spojenie riadkov",
            "Tieto riadky majú rôzne typy",
            "Typ aktuálneho kresliaceho riadku",
            "Typ riadku, s ktorým sa chcete spojiť"
        ],
        hasRestorableProject: [
            "Máte neuložené dáta pre tento projekt",
            "Môžete obnoviť nespasený stav zo snímky z"
        ],
        restoreProject: "Obnoviť",
        imageLost: [
            "Prepáč, že na serveri nenájdeme nejaké podložné obrázky.",
            "Tento obrázok nebol nájdený:"
        ],
        precipCalcError_mixedError: [
            'Chyba máp zrážok',
            'Nepodarilo sa vytvoriť zrážkové mapy pre kombináciu hasiacich zariadení:',
        ],
        precipCalcError_mprNonMprRot: 'Nie je možné miešať normálne rotory a rotory s tryskami MPR',
        precipCalcError_mprNozNonMprRot: 'Nie je možné miešať dýzy MPR a normálne rotory',
        precipCalcError_staticNozRot: 'Nie je možné zmiešať statické trysky s rotormi',
        precipCalcError_staticMprNoz: 'Nie je možné miešať statické trysky s tryskami MPR',
        precipCalcError_missingError: [
            'Chyba máp zrážok',
            'Chýbajúce zrážky pre hasiace zariadenia:',
        ],
        precipCalcError_zoningError: [
            'Zrážková mapa',
            'Nepodarilo sa vytvoriť zrážkové mapy pre kombináciu hasiacich zariadení:',
        ],
        precipCalcError_noZoneAndZone: 'Nie je možné vypočítať zrážky pre pripojené a nepripojené rotory súčasne. Čas chodu nie je známy, preto je množstvo otáčok rotorov neisté.',
        algoNozzler_noSolutions: [
            'Nenájdené žiadne možné riešenia posunu zavlažovacieho zariadenia',
            'Snažte sa robiť nasledovné:',
            '1. Zmeniť prekrývajúce sa obmedzenia a iné možnosti v menu konfigurácie nástroja Auto-Placemt',
            '2. Vyberte iný typ samočinných hasiacich zariadení, ako môžu poskytnúť potrebnú flexibilitu pri umiestnení',
            '3. Použite tlačidlo nižšie na reštart riešenia s viac "voľnými" obmedzeniami pre prekrývanie a odkrytie'
        ],
        retryWithLooseOptions: "Poézia s 'voľnými' možnosťami",
        cannotSaveBecauseOffline: [
            "Nepodarilo sa poslať žiadosť na server",
            "Žiadne pripojenie k serveru",
            "Skontrolujte, či máte pripojenie na internet",
            "Aby ste nestratili dáta, nezatvárajte toto okno a snažte sa uložiť dáta neskôr, keď je vytvorené pripojenie k serveru",
            "",
        ],
        cannotSaveBecauseTooManyFails: [
            "Nepodarilo sa uložiť požiadavku",
            "Príliš veľa neúspešných pokusov o kód",
            "Skontrolujte, či ste zadali e-mailovú adresu správne a skúste to znova po 30 sekundách.",
            "",
            "",
        ],
        cannotSaveBecauseNoMailProvided: [
            "Nepodarilo sa uložiť požiadavku",
            "Nesprávne zadaná e-mailová adresa",
            "Skontrolujte, či ste zadali e-mailovú adresu správne a skúste to znova",
            "",
            "",
        ],
        designRequestCompleted: [
            "Vaša žiadosť bola úspešne vytvorená/aktualizovaná",
            "Upraviť odkaz", "Rozumiem.",
            "Odkaz na zobrazenie", "Rozumiem.",
        ],
        designRequestContacts: [
            "Kontaktné informácie",
            "Organizácia",
            "Názov",
            "E-mail",
            "Telefón",
            "Adresa",
            "Webová stránka",
        ],
        designRequestInfo: [
            "Vitajte v Design Studio!",
            "Tu môžete vytvoriť požiadavku na plánovanie zavlažovacieho systému ľahko a rýchlo.",
            "Môžete nájsť<a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>inštruktáž video tu</a>",
            "Pre ďalšie informácie alebo ak máte akékoľvek otázky, neváhajte nás kontaktovať."
        ],
        approveActionByCode: [
            "Potvrdiť činnosť",
            "E-mail s potvrdzovacím kódom bol zaslaný na vašu e-mailovú adresu.",
            "Zadajte tento kód do poľa nižšie",
            "Zadali ste neplatné číslo, skúste to znova"
        ],
        revisionCheckFailedSoft: [
            'Revízny konflikt!',
            'Tento projekt je v súčasnosti otvorený na inom prehliadači alebo zariadení.',
            'Môžete prepísať dáta na serveri (pretože ukladáme iba jednu verziu vášho projektu) kliknutím na prepísanie, ale buďte opatrní - všetok pokrok dosiahnutý v iných sedeniach bude stratený!',
            'Lepšou stratégiou je pochopiť, kde a kto otvoril tento projekt a rozhodnúť, koho verzia je aktuálna.',
            'Ak chcete prevziať kontrolu nad najnovšou verziou tohto súčasne otvoreného projektu, môžete opäť otvoriť tento projekt duplikovaním tejto karty vo vašom prehliadači.',
        ],
        revisionBlocked: [
            'Úspora je zablokovaná administrátorom!',
            'V súčasnosti váš projekt revidujú naši technickí pracovníci z dôvodu chýb, ktoré sa v ňom dejú.',
            'Počkajte, prosím, kým sa preskúmanie dokončí, potom budete informovaní e-mailom s ďalšími pokynmi.',
        ],
        missingVariants: [
            'Chyba chýbajúcich prvkov',
            'Nižšie je zoznam vlastných prvkov, ktoré chýbajú vo vašej knižnici projektu, a preto ich nie je možné vykresliť:',
            'Prosím, zapnite sady obsahujúce tieto prvky v ponuke nastavení projektu (v Dielni)'
        ],
        openInOtherTab: "Otvoriť najnovšie",
        overwrite: "Prepísať",
        saveToFile: "Uložiť do súboru",
        filterSelection_exclude: "Vylúčenie z výberu",
        filterSelection_include: "Zahrnúť do výberu",
        filterSelectionNames: {
            sprinklers: "Spotrebitelia",
            sprinklers_nozzle: "Spotrebitelia - trysky",
            sprinklers_rotaryNozzle: "Spotrebitelia - rotačné trysky",
            sprinklers_rotor: "Spotrebitelia - rotory",
            sprinklers_bubbler: "Spotrebitelia - bubliny",
            sprinklers_bubblerNozzle: "Spotrebitelia - bubliny",
            sprinklers_pinpoint: "Spotrebitelia - Presné postrekovače",
            dripStarts: "Drip začína",
            rzwLayer: "Root zone watering",
            dripLines: "Linky na kvapkanie",
            valvesLayer: "Ventily",
            waterSources: "Zdroje vody",
            controllers: "Kontrolóri",
            sensorsLayer: "Snímače",
            mainPipes: "Hlavné rúry",
            lateralPipes: "Lateral pipes",
            trenchesLayer: "Trenches",
            insetsLayer: "Sleeves",
            wiresLayer: "Wiring",
            wirelessLayer: "Wireless connection",
            senswirelessLayer: "Wireless sensor connection",
            senswiresLayer: "Sensor wiring",
            quickCoupLayer: "Rýchle spojky",
            surfaces: "Polygóny a čiary",
            ldItemsLayer: "Položka krajiny",
            ldArbitraryLayer: "Vlastné prvky krajiny",
            spArbitraryLayer: "Vlastné prvky zavlažovania",
            overlays: "Prvky rozloženia",
            stampTexts: "Texty pečiatky"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "Kropiaci uzol",
        fcType: "Typ prípojky samočinného hasiaceho zariadenia",
        sj: "Swing joint",
        sprinklerStand: "Stojan na kropenie (Riser)",
        flexPipeBarbs: "Flexibilné potrubie + omietky",
        minFlexPipeLength: "Minimálna dĺžka flexu potrubia na pripojenie",
        midSprinkPipeFitting: "Tie-in fitting",
        endSprinkPipeFitting: "End-pipe fitting",
        single_clamp_saddle: "Sedadlo remeňa",
        tee_PTP: "Tee so ženskou BSP niťou",
        elbow_PT: "Kolená so ženskou BSP niťou",
        coupling_PT: "Adaptér so ženskou BSP niťou",
        //MANIFOLD NODE CONFIGS
        manifoldNode: "Manifoldové uzliny",
        valvesOutlay: "Náklady na ventily",
        fold: "Skladacie",
        unfold: "Rozviazané",
        threadsNode: "Prípojky so závitom",
        threadTypes: "Typy vlákien",
        //AUTOMATION NODE CONFIGS
        automationNode: "Automatický uzol",
        controllerModules: "Modulárne radiče rozšírenie moduly sú vybrané:",
        controllerVoltage: "Vstupné napätie riadiaceho pracovníka:",
        controllerVoltageV2: "Vstupné napätie riadiaceho pracovníka:",
        230: "230 VAC",
        "230A": "230 VAC (AUS)",
        120: "120 VAC",
        24: "24 VAC",
        autoModules: "Automaticky (najlepšie vybavenie)",
        userModules: "Ručne (ako príslušenstvo)",
        //RZW NODE
        rzwNode: "Koreňová zóna zavlažovacieho uzla",
        midRZWPipeFitting: "Tie-in fitting",
        endRZWPipeFitting: "End-pipe fitting",
        //DRIP node
        dripNode: "Zavlažovanie kvapkaním",
        dripConnectionType: "Typ príslušenstva na kvapkanie",
        dripLengthPrecision: "Digity po desatinnom bode dĺžky rúrky",
        dripTubingAddon: "Doplnková látka:",
        barb: "Ostnaté príslušenstvo",
        twistLock: "Príslušenstvo k závitovému uzáveru",
        dripSpikesStep: "Drip držiak hrot krok",
        dripCrossFittingAble: "Krížová montážna schopnosť",
        pipesNode: "Sekcia pingovanie",
        hdpeConnectionType: "Typ HDPE príslušenstva",
        ldpeConnectionType: "Typ LDPE príslušenstva",
        pvcConnectionType: "Typ PVC príslušenstva",
        pipeAddon: "Prídavné potrubie pre každý priemer",
        pipeLengthPrecision: "Digity za desatinným bodom dĺžky potrubia",
        crossFittingAble: "Krížová montážna schopnosť",
        compress: "Kompresné príslušenstvo",
        customfit: "Príslušenstvo na colné účely",
        slip: "Príslušenstvo k prešmykom",
        wiringNode: "Sekcia elektroinštalácie",
        exportNode: "Možnosti exportu",
        exportNumbersPrecision: "Počet desatinných miest za číslami",
        basicWiringMethod: "Metóda ovládacieho vedenia",
        cableCoresArray: "Rozsah počtu jadier káblov",
        noAutoWiring: "Ručne pridajte vedenie",
        separateCableToManifold: "Samostatný viacjadrový kábel do potrubia",
        separateWireToValve: "Oddelený drôt na ventil + spoločný drôt na potrubie",
        maxCableCores: "Max. jadrá káblov",
        verticalWiringAddon: "Vertikálna doplnková látka k ovládaciemu drôtu",
        verticalSensWiringAddon: "Vertikálna doplnková látka pre senzorový drôt",
        wireAddon: "Drôtová doplnková látka pre každý typ",
        wireLengthPrecision: "Digity za desatinným bodom dĺžky vedenia",
        //DRAWER CONFIG
        drawerConfig: [
            "Konfigurácia projektu"
        ],
        //SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "Spotrebitelia",
        pressureDefinedBy: "Očakávaný tlak na spotrebiteľov je",
        allowReduceRotors: "Povoliť zníženie polomeru rotorov",
        autoconnector: "Interaktívne pripojenie samočinných hasiacich zariadení k bočným rúrkam",
        radio_option_yes: "Áno (podľa odporúčania dodávateľa)",
        radio_option_no: "Nie.",
        extreme_rotor_reduction: "Extrémne (až 50%) (Môže spôsobiť nerovnomerné zrážky)",
        radio_option_yes2: "Áno",
        takeReductionInAccountWhenAutoPlacing: "Ponuka znížených vrhacích vzdialeností pri umiestnení hasiacich zariadení",
        takeReductionInAccountWhenAutoPlacingForRotors: "Ponuka znížených vrhacích vzdialeností pri umiestňovaní hasiacich zariadení (Rotors)",
        recommendedPressure: "Odporúčané predajcom",
        userPressure: "Nastaviť užívateľom",
        expPressure: "Očakávaný tlak na spotrebiteľa",
        sprinklerGroupMode: "Zoskupovanie spotrebiteľov",
        safeSprGroupMode: "Prísny režim (iba kompatibilná skupina)",
        unsafeSprGroupMode: "Nebezpečný režim (VARENIE! Žiadne obmedzenia zoskupenia)",
        "sprinklerAttachBulkMode": "Režim hromadného pripojenia spotrebiteľov",
        "safeSprAttachMode": "Neopätovať pripojenie už pripojených spotrebiteľov",
        "unsafeSprAttachMode": "Nebezpečný režim (VARENIE! Možné opätovné pripojenie už pripojených spotrebiteľov. Použitie na vlastné nebezpečentsvo)",
        //UNITS CONFIG
        unitsConfig: "Jednotky merania",
        precisionStd: "Počet desatinných miest",
        unitsSystemGridAndRuler: "Jednotky meracieho systému pre mriežku a pravítko",
        distanceUnits: "Vzdialenosť",
        distancePrecision: "Počet desatinných miest",
        trenchSizeUnits: "Jednotky rozmerov",
        trenchSizePrecision: "Číslice za desatinnou čiarkou",
        sprinklerDistUnits: "Polomer kropiča",
        sprinklerDistPrecision: "Počet desatinných miest",
        areaUnits: "Oblasť",
        areaPrecision: "Počet desatinných miest",
        volumeUnits: "Objem",
        volumePrecision: "Počet desatinných miest",
        waterFlowUnits: "Prietok vody",
        waterFlowPrecision: "Počet desatinných miest",
        pressureUnits: "Tlak",
        pressurePrecision: "Počet desatinných miest",
        velocityUnits: "Rýchlosť",
        velocityPrecision: "Počet desatinných miest",
        precipRateUnits: "Miera zrážok",
        precipRatePrecision: "Počet desatinných miest",
        // ZONE PROPS CONFIG
        climateConfig: "Výpočet času zavlažovania",
        lawnCultureType: "Typ trávnika",
        coolLoving: "Milovanie za studena",
        warmLoving: "Teplá láska",
        climateTemp: "Priemerná letná teplota",
        coolClimate: "< 21 °C",
        warmClimate: "21 - 32°C",
        hotClimate: "> 32°C",
        climateHumid: "Priemerná letná vlhkosť",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "Zóna mikroklíma&nbsp;<i class='far fa-question-circle'></i>",
        microClimateTooltip: "Mierna\n"+
            "Irrigation areas that are in the shade, sheltered from the wind and are away from dry and heated objects\n" +
            "\n" +
            "Normal\n" +
            "Places in the landscape where microclimate conditions are represented: the presence of\n" +
            "buildings, sidewalks and paths, shade, etc. do not significantly affect the values of\n" +
            "evapotranspiration\n" +
            "\n" +
            "Harsh\n" +
            "Reflects conditions that impede plant growth and easily translates to a stressed state if the plant is not properly watered. This can be an open place, under blazing sun, in close proximity to pathways, buildings or other landscape structures, reflecting light from glass or landscape elements that absorb heat, or it can be a windy place.",
        gentleMicroClimate: "Mierna",
        normalMicroClimate: "Normálna",
        toughMicroClimate: "Kruté",
        soilType: "Zloženie pôdy v zónach",
        sand: "Sandy",
        sandyLoam: "Pieskovec",
        lightLoam: "Slabá hlina",
        mediumLoam: "Stredná hlina",
        heavyLoam: "Silná hlina",
        clay: "Clay",
        heavyClay: "Ťažký íl",
        zoneSlope: "Všeobecný sklon na zónach",
        noneIncline: "0 - 5% (0 - 3°)",
        lightIncline: "5 - 8% (3- 5°)",
        mediumIncline: "8 - 12% (5 - 7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "Rozpočet na vodu",
        lowWB: "nízka",
        normalWB: "Normálna",
        highWB: "Vysoká",
        ft: "nohy",
        in: "palec",
        ftin: "nohy/palce",
        metric: "metrická",
        imperialUS: "cisársky (USA)",
        //UNITS CONFIG
        hydraConfig: "Hydraulické",
        waterTemp: "Teplota vody",
        maxFlowVelocity: "Maximálna rýchlosť prietoku v potrubí",
        commonConfig: "Spoločné nastavenia",
        lateralNozzlerSwitch: "Ako prepnúť do režimu pripojenia dýz",
        NStabonly: "Karta",
        NStabshift: "Tab+Shift",
        showActionSubtitles: "Zobraziť titulky akcie",
        Yeah: "Áno",
        Nope: "Nie.",
        start: "Začiatok",
        recalibrate: "Rekalibrácia",
        calibrationSuccess: [
            "Úspešne kalibrovaný",
            "Teraz môžete použiť dotykový displej v dvoch režimoch - 'pohyb kurzor' (ľahký dotykový pohyb) a 'drag mode' (tvrdý dotykový pohyb)"
        ],
        calibrationFailEqual: [
            "Kalibrácia zlyhala",
            "Nenašli sme žiadny veľký rozdiel v spôsobe dotyku obrazovky v oboch režimoch",
            "Môžeš to skúsiť znova. A uistite sa, že používate svoj prst, nie stylus"
        ],
        calibrationFailImproper: [
            "Kalibrácia zlyhala",
            "Zistili sme väčší tlak na pierko ako na nákovu.",
            "Môžeš to skúsiť znova. A uistite sa, že pohyb pierka s ľahším tlakom ako nákova"
        ],
        calibrationImpossible: [
            "Kalibrácia nie je možná",
            "Zdá sa, že vaše zariadenie nepodporuje meranie dotykovej plochy. Takže nemôžeme definovať dva režimy dotykovej interakcie",
            "V tomto prípade môžete použiť virtuálnu myš, aby ste mohli ťahať čokoľvek. Objaví sa na ľavej strane obrazovky.",
        ],
        calibrationNeeded: [
            "Potrebná kalibrácia!",
            "Musíme kalibrovať váš dotykový displej, aby sme mohli definovať dva režimy dotykovej interakcie:",
            "Pohybujúci sa kurzorový mód - keď chcete len presunúť kurzor alebo presunúť polygón segment pri kreslení",
            "A ťahanie režim - to je, keď chcete pohybovať prvky okolo alebo zmeniť ich veľkosť. Tiež by ste mali ťahať-pohyb, keď chcete vybrať veľa položiek",
            "Prosím kliknite na tlačidlo Štart a postupujte podľa pokynov na obrazovke"
        ],
        insertImage: 'Vložiť',
        mapImagePicker: [
            "Satelitné načítanie obrázkov",
            "Zemepisná šírka/dĺžka",
            "Zadajte zemepisnú šírku",
            "Zadajte zemepisnú dĺžku",
            "Aktuálna poloha",
            "Choď.",
            "Adresa",
            "Zadajte časť adresy a kliknite na 'Hľadanie'",
            "Hľadať",
            "Zoom",
            "Pan"
        ],
        "imageCrop": [
            "Nástroj na pestovanie plodín"
        ],
        cropImage: "Plodina",
        invalid_dataset_1: 'Neplatný súbor údajov. Projekt obsahuje zakázané typy povrchov. Iba zavlažované (LAWN), nezavlažované a prekážky sú povolené.',
        invalid_dataset_2: 'Neplatný súbor údajov. Nie viac alebo menej ako jedna zavlažovaná plocha je povolená.',
        invalid_dataset_3: 'Neplatný súbor údajov. Zavlažovaný povrch sa sám pretína.',
        invalid_dataset_4: 'Neplatný súbor údajov. Prekážkové označenie by nemalo byť zložené (vyrobené z viac ako jedného polygónu)',
        invalid_dataset_5: 'Neplatný súbor údajov. Prekážková plocha by mala byť úplne zavlažovaná.',
        invalid_dataset_6: 'Neplatný súbor údajov. Projekt obsahuje zakázané typy hasiacich zariadení. Povolené:',
        invalid_dataset_7: 'Neplatný súbor údajov. Zrážková rýchlosť samočinných hasiacich zariadení je mimo dosahu',
        invalid_dataset_8: 'Neplatný súbor údajov. Kropiace stroje nesmú mať individuálne nastavenie tlaku',
        invalid_dataset_9: 'Neplatný súbor údajov. Projekt by nemal nastaviť vlastný očakávaný tlak na rozprašovače',
        invalid_dataset_10: 'Neplatný súbor údajov. Jednotnosť je príliš nízka.',
        invalid_dataset_11: 'Neplatný súbor údajov. Nadmorská oblasť je príliš veľká.',
        layoutPresetsMenu: [
            "Predvoľby rozloženia",
            "Aktuálna predvoľba rozloženia",
            "Predvoľba sady rozložení",
            "Predvolená predvoľba pre nové rozloženie:",
            "- Vyberte predvoľbu -",
            "- Žiadne dostupné predvoľby -"
        ],
        edit: "Upraviť",
        nozzleCharacteristicsConfig: "Konfigurácie charakteristík trysky",
        nozzleCharacteristicsConfig_lang: {
           // Main editor
           title: "Konfigurácia charakteristík trysky",
           save: "Uložiť",
           cancel: "Zrušiť",
           reset: "Obnoviť",
           typeArc: "Oblúk",
           typeStrip: "Pás",
           typeVariableArc: "Premenný oblúk",
           unknown: "Neznámy",
           object: "Objekt",
           selectVariant: "Vybrať variant",
           editVariant: "Upraviť variant",

           // Variant editor fields
           editData: "Upraviť údaje o výkone",
           editPrecipMap: "Upraviť mapu zrážok",
           pressuresLabel: "Tlaky",
           anglesLabel: "Uhly",
           valuePairsLabel: "Dvojice hodnôt",
           valuesLabel: "Hodnoty",
           pointsLabel: "bodov",
           valuesSuffix: "hodnôt",
           pairsSuffix: "dvojíc",
           none: "žiadne",

           // Field name labels
           pressMap: "Tlak",
           angleMap: "Uhol",
           valuesMap: "Hodnoty",
           precipMap: "Zrážky",
           reducableBy: "Násobiteľ zníženia (0.0 - 1.0)",

           // Error messages
           invalidInputFormat: "Neplatný formát vstupu.",
           fieldInvalidFormat: "Neplatný formát.",
           reducableByOutOfRange: "Hodnota musí byť medzi 0.01 a 0.99.",

           // NozzleDataEditor translations (passed to that editor)
           dataEditor: {
               modeSingle: "Jednotlivé uhly",
               modeRange: "Rozsahy uhlov",
               pressureAngleLabel: "Tlak/Uhol",
               pressure: "Tlak",
               angle: "Uhol",
               distance: "Vzdialenosť",
               flow: "Prietok",
               addRow: "Pridať riadok",
               addCol: "Pridať stĺpec",
               delete: "Vymazať",
               save: "Uložiť",
               cancel: "Zrušiť",
               reset: "Obnoviť",
               distanceUnit: "Jednotka vzdialenosti",
               pressureUnit: "Jednotka tlaku",
               flowUnit: "Jednotka prietoku",
               angleMode: "Režim uhla:",
               cannotDeleteLastRow: "Nie je možné vymazať posledný riadok!",
               cannotDeleteLastColumn: "Nie je možné vymazať posledný stĺpec!",
               angleRangesCannotIntersect: "Rozsahy uhlov sa nemôžu pretínať!",
               pleaseFillAllCells: "Prosím vyplňte všetky bunky! Prázdne bunky:",
               row: "Riadok",
               col: "Stĺpec"
           },

           // PrecipMapEditor translations (passed to that editor)
           precipEditor: {
               precipitation: "Zrážky",
               distance: "Vzdialenosť",
               addCol: "Pridať stĺpec",
               delete: "Vymazať",
               save: "Uložiť",
               cancel: "Zrušiť",
               reset: "Obnoviť",
               precipitationUnit: "Jednotka zrážok",
               cannotDeleteLastColumn: "Nie je možné vymazať posledný stĺpec!"
           }
        },
        stylesConfig: "Štýly",
        linesStyles: "Štýly potrubí a kabeláže",
        linesStyles_lang: {
            title: "Konfigurácia štýlov čiar",
            save: "Uložiť",
            cancel: "Zrušiť",
            reset: "Obnoviť predvolené",
            // Group headers
            mainPipeGroup: "Farby hlavného potrubia",
            lateralPipeGroup: "Farby bočného potrubia",
            dripLinesGroup: "Farby kvapkacích liniek",
            wiresGroup: "Farby káblov",
            // Color labels
            mpColor: "Hlavné potrubie",
            mpOverColor: "Hlavné potrubie (Prejdenie)",
            mpPVCColor: "Hlavné potrubie PVC",
            mpPVCOverColor: "Hlavné potrubie PVC (Prejdenie)",
            mpPVCMSColor: "Hlavné potrubie PVC Viacžilové",
            mpPVCMSOverColor: "Hlavné potrubie PVC Viacžilové (Prejdenie)",
            lpColor: "Bočné potrubie",
            lpOverColor: "Bočné potrubie (Prejdenie)",
            lpPVCColor: "Bočné potrubie PVC",
            lpPVCOverColor: "Bočné potrubie PVC (Prejdenie)",
            lpPVCMSColor: "Bočné potrubie PVC Viacžilové",
            lpPVCMSOverColor: "Bočné potrubie PVC Viacžilové (Prejdenie)",
            lpLDPESColor: "Bočné potrubie LDPE-S",
            lpLDPESOverColor: "Bočné potrubie LDPE-S (Prejdenie)",
            dl16Color: "Kvapkacia linka 16mm",
            dl16OverColor: "Kvapkacia linka 16mm (Prejdenie)",
            dl17Color: "Kvapkacia linka 17mm",
            dl17OverColor: "Kvapkacia linka 17mm (Prejdenie)",
            wrColor: "Kábel",
            wrOverColor: "Kábel (Prejdenie)",
            wrlsColor: "Bezdrôtový",
            wrlsOverColor: "Bezdrôtový (Prejdenie)",
            swrColor: "Kábel snímača",
            swrOverColor: "Kábel snímača (Prejdenie)",
            swrlsColor: "Bezdrôtový snímač",
            swrlsOverColor: "Bezdrôtový snímač (Prejdenie)",
            dwrColor: "Dátový kábel",
            dwrOverColor: "Dátový kábel (Prejdenie)"
        }
    }
};
