this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        "m": "m",
        "cm": "cm",
        "mm": "mm",
        "ft": "'",
        "in": "\"",
        "ftin": "ft/in",
        "sqm": "m²",
        "acre": "akre",
        "hectare": "hektaar",
        "sqft": "kareft",
        "bar": "bar",
        "kpa": "kPa",
        "atm": "atm",
        "mH2O": "mH₂O",
        "psi": "psi",
        "l": "l",
        "m3": "m³",
        "USg": "gal",
        "lpm": "l/dk",
        "lph": "l/sa",
        "m3h": "m³/sa",
        "USgpm": "gal/dk",
        "USgph": "gal/sa",
        "deg": "°",
        "pcs": "adet",
        "pcsDot": "adet.",
        "pcsShort": "adet.",
        "percent": "%",
        "in_Alt": "inç.",
        "mps": "m/s",
        "kph": "km/sa",
        "ftps": "fit/sa",
        "degreesCentigrade": "°C",
        "mmph": "mm/sa",
        "mmp24h": "mm/gün",
        "inph": "inç/sa",
        // unconvertable
        "min": "dk."
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        "autoDrawer": "Otomatik çizici",
        "chooseSprinkler": "Püskürtücü seçin:",
        "auto": "Otomatik ayar",
        "waterSource2row": ["Su", "Giriş"],
        "setLineLength": "Hat boyutunu ayarla (mm):",
        "setPressure": "Püskürtücülerde beklenen dinamik basıncı ayarla (bar):",
        "setMaxFlow": "Maksimum su akışını ayarla (l/dk):",
        "controllerShort": "K",
        "sensorShort": "S",
        "action_activateEraser": "Silgiyi etkinleştir",
        "action_deactivateEraser": "Silgiyi devre dışı bırak",
        "action_boolUnite": "Birleştir",
        "action_boolIntersect": "Kesiştir",
        "action_boolSubtract": "Çıkart",
        "action_boolExclude": "Hariç tut",
        "action_changeSprayBody": "Sprey tipini ayarla",
        "action_changeVariant": "Varyantı ayarla",
        "action_changeImgVariant": "Varyantı ayarla",
        "action_changeType": "Türü ayarla",
        "action_addConsumers": "Tüketici ekleyin",
        "action_drawBranches": "Şubeleri ekleyin",
        "action_editLine": "Segmentleri düzenle",
        "action_drawCircles": "Daireler çizin",
        "action_detachAll": "Tümünü ayır",
        "action_drawBrush": "Fırça çizin",
        "action_editBrush": "Fırçayı düzenle",
        "action_changeBrushSize": "Fırça boyutu",
        "action_booleans": "Boolean işlemleri",
        "action_intoPoly": "Poligona dönüştür",
        "action_intoBrush": "Fırçaya dönüştür",
        "action_activateRotation": "Döndür",
        "action_deactivateRotation": "Sabitle",
        "action_markZones": "Bölge temsili",
        "action_unmarkZones": "İşareti kaldır",
        "action_sprNames": "Püskürtücü isimleri",
        "action_noSprNames": "İsimleri kaldır",
        "action_lockItem": "Kilitle",
        "action_unlockItem": "Kilidi aç",
        "Circle": "Daire",
        "Triangle": "Üçgen",
        "BushForm": "Çalılar",
        "BushForm1": "Çalılar 1",
        "BushForm2": "Çalılar 2",
        "BushForm3": "Çalılar 3",
        "Square": "Kare",
        "noShadow": "Yok",
        "standardShadow": "Standart",
        "noArrows": "Yok",
        "startArrow": "Başlangıçta",
        "endArrow": "Sonda",
        "bothArrows": "Her İki Tarafta",
        "normalSizeSide": "Normal",
        "invertedSizeSide": "Ters",
        "strMiter": "Mitre",
        "strRound": "Yuvarlak",
        "strBevel": "Eğik",
        "strSquare": "Kare",
        "strButt": "Butt",
        "FWnormal": "Normal",
        "FWbold": "Kalın",
        "FWitalic": "İtalik",
        "FWbolditalic": "İtalik Kalın",
        "FJleft": "Sol",
        "FJright": "Sağ",
        "FJcenter": "Orta",
        "rzwHeight": "Yükseklik"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "Seçici",
        //----Drawing
        selectPoly: "Seçili öğe yok",
        //----Sprinkling
        selectSprink: "Seçili öğe yok",
        lpNozzler: "Su tüketenleri bağlama",
        dl16CircDrawer: "16/13mm damla çemberi döşeme",
        dl16sDrawer: "16/13mm damla kapak çizimi",
        dl17CircDrawer: "17mm damla çemberi döşeme",
        dl17sDrawer: "17mm damla kapak çizimi",
        "ldTextDrawer": "Metin Kurulumu",
        "staticTextDrawer": "Metin Kurulumu",
        "dynamicTextDrawer": "Metin Kurulumu",
        "ldStaticTextDrawer": "Metin Kurulumu",
        "ldtextEditor": "Metin Düzenleme",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "Toplam mesafe",
        type: "Tür",
        variant: "Varyant",
        area: "Alan",
        perimeter: "Çevre",
        curveLength: "Uzunluk",
        treeDiameter: "Çap",
        bushDiameter: "Çap",
        nozTypes: "Mevcut tipler",
        nozType: "Tür",
        sprBod: "Sprey gövdesi",
        rad: 'Yarıçap',
        angle: 'Açı',
        reducedBy: 'Azaltılmış',
        consump: 'Tüketim',
        pressure: 'Basınç',
        coverSize: 'Kapsama',
        maxFlow: 'Maksimum su akışı',
        pipesNum: "Bağlı borular",
        pipeType: "Tür",
        pipeLength: "Uzunluk",
        wireLength: "Uzunluk",
        valvesManifNum: "Vanalar manifoldları",
        valvesNum: "Vanalar",
        propDiam: "Uygun çap",
        curDiam: "Çizim çapı",
        outsNum: "Su tüketenler",
        flow: "Su akışı",
        precipRate: "Yağış hızı",
        totalPrecipArea: "Toplam kapsama",
        uniformity: "Uniformity (CU)",
        overwatered: "Overwatered",
        precipRateShort: "Yağış",
        runtimeInd: "Çalışma süresi",
        coveredArea: "Alan",
        microClimateInd: "M/İklim",
        soilTypeInd: "Toprak",
        zoneSlopeInd: "Eğim",
        maxInfiltrationRate: "İnfiltrasyon hızı",
        waterDemand: "Su talebi",
        numOfRuns: "Günlük çalışma sayısı",
        timePerRun: "Çalışma süresi",
        dailyConsumption: "Günlük tüketim",
        dripsNum: "Bağlı damla hatları",
        dripType: "Damlama Türü",
        dripRowsStep: "Yüzey sıra adımı",
        dripRowsAngle: "Yüzey sıra açısı",
        cntrType: "Kontrolör türü",
        sensType: "Sensör türü",
        zonesNum: "Kontrol edilen bölgeler",
        trenchWidth: "Genişlik",
        trenchDepth: "Derinlik",
        trenchVolume: "Hacim",
        insetDiam: "Çap",
        insetLength: "Uzunluk",
        insetVar: "Malzeme",
        itemsCount: "Sayı",
        insetDepth: "Derinlik",
        zoneName: "Bölge adı",
        valveName: "Vana Kutusu",
        itemAlias: "Takma Ad",
        //MULTISELECTOR
        itemsSelected: "Seçilenler",
        totalArea: "Toplam alan",
        totalPerimeter: "Toplam çevre",
        totalLength: "Toplam uzunluk",
        totalVolume: "Toplam hacim",
        totalConsumption: "Toplam tüketim",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "Geçersiz çokgen",
        isSelfCrossing_false: "Geçerli çokgen",
        isConnected_true: "Bağlı",
        isConnected_false: "Bağlı değil",
        isWired_true: "Bağlantılı",
        isWired_false: "Bağlantılı değil",
        isDripZone_true: "Damlama bölgesi",
        isDripZone_false: "",
        isSprinklerZone_true: "Sprey bölgesi",
        isSprinklerZone_false: "",
        isOverloaded_true: "AŞIRI YÜK!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "Düşük basınç",
        isUnderpressured_false: "",
        isOverpressured_true: "Yüksek basınç",
        isOverpressured_false: "",
        isLocked_true: "Kilitli",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "Paslanmaz çelik",
        "High speed": "Yüksek hız",
        "Opposing nozzle": "Karşıt püskürtme ucu",
        "Plastic": "Plastik",
        "MPR Nozzles": "MPR Püskürtme Uçları",
        "Rotary Nozzles": "Döner Püskürtme Uçları",
        "Nozzles": "Püskürtme Uçları",
        "Bubbler nozzles": "Kabarcık püskürtme uçları",
        "Multi-stream": "Çoklu akış",
        "Dual-stream": "Çift akış",
        "Stream Nozzles": "Akış püskürtme uçları",
        "Short Radius Nozzles": "Kısa yarıçap püskürtme uçları",
        "Pressure compensating": "Basınç dengeleyici",
        "Adjustable flood": "Ayarlanabilir selden geçiş",
        "Adjustable": "Ayarlanabilir",
        "Fixed": "Sabir",
        "Fixed Arc": "Sabir açı",
        "Strip Pattern": "Şerit deseni",
        "Drip line": "Damla hattı",
        "Drip cover": "Damla kapak",
        "16mm": "16/13mm",
        "17mm": "17mm",
        "emitter": "Püskürtücü ile",
        "noemitter": "Püskürtücüsüz",
        "Root zone watering": "Kök bölgesi sulama",
        "Lateral": "Yan hat",
        "Main": "Ana hat",
        "Trench": "Çukur",
        "hdpe": "HDPE",
        "pvc": "PVC",
        pvcm: "PVC(Metric)",
        ldpe: "LDPE",
        "Controller": "Kontrol cihazı",
        "Sensor": "Sensör",
        Wiring: "Bağlantı",
        "IrrigateMarks": "Sulama bölgeleri",
        "Surface": "Yüzey",
        "Lawn": "Çim",
        "Bed": "Yatak",
        "Shrubs": "Çalılar",
        "Path": "Yol",
        "Concrete": "Beton",
        "Sand": "Kum",
        "Water": "Su",
        "Bedding": "Yatak döşemesi",
        "Flower": "Çiçek",
        "Herbal": "Bitkisel",
        "geographic": "Coğrafi",
        "sizeMark": "Boyutlar",
        "scalingBar": "Ölçek çubuğu",
        "loCurves": "Çizgiler",
        "texts": "Metinler",
        "staticText": "Sabit metin",
        "dynamicText": "Dinamik metin",
        "stampText": "Mühür metni",
        "stampTextDefault": "Metin",
        "stampTextgr1": "Belge tanımı",
        "stampTextgr2": "Adres hücresi",
        "stampTextgr3": "Site adı",
        "stampTextgr4": "Çizim adı",
        "stampTextgr9": "Organizasyon bilgisi",
        "stampTextgr6t": "Aşama",
        "stampTextgr7t": "Sayfa",
        "stampTextgr8t": "Sayfalar",
        "stampTextgr6": "P",
        "stampTextgr7": "1",
        "stampTextgr8": "10",
        "stampTextgr14t": "Ch.",
        "stampTextgr15t": "Prtcp.",
        "stampTextgr16t": "Sayfa",
        "stampTextgr17t": "Dok. #",
        "stampTextgr18t": "İmza",
        "stampTextgr19t": "Tarih",
        "stampTextgr20t": "Orij. Fatura #",
        "stampTextgr21t": "İmza ve Tarih",
        "stampTextgr22t": "Yedek Fatura #",
        "inserts": "Boru Kollukları",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        "showLM": "Katmanlar Yöneticisini Göster",
        "hideLM": "Katmanlar Yöneticisini Gizle",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "Unnamed",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        "beganExporting": "Düzeni dışa aktarıyor",
        "successExporting": "Başarıyla dışa aktarıldı",
        "failExporting": "Dışa aktarma başarısız oldu",
        "failExportingLimitReached": "<a target='_blank' href='/account/subscription'>Günlük sınır aşıldı</a>",
        "exportingLimit": "Sınır: ",
        "exportingLeft": "Bugün kalan: ",
        "pdfExportingPopUpBlocked": "Tarayıcınız popup pencereyi engelledi. Lütfen bu site için popup'ları izin vererek .PDF dosyasını alın.",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        "tt_group": "Açılır pencere ipliği",
        "tt_group_MT": "Erkek",
        "tt_group_FT": "Dişi",
        "tt_riserHeight": "Yükselme yüksekliği",
        "tt_pressureReg": "Basınç düzenleyici",
        "tt_checkValve": "(Kontrol Valfi ile)",
        "tt_home": "Ana Sayfa",
        "tt_prev": "Önceki",
        "tt_next": "Sonraki",
        "tt_end": "Son",
        "tt_add": "Ekle",
        "tt_clone": "Kopyala",
        "tt_remove": "Kaldır",
        "tt_rename": "Yeniden Adlandır",
        "tt_addToFav": "Favorilere Ekle",
        "tt_remFromFav": "Favorilerden Kaldır",
        "tt_presets": "Ön Ayarlar",
        tt_MagicAutoPlacer: "`Çizgi boyunca otomatik yerleştirme`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        "N": "K",
        "S": "G",
        "E": "D",
        "W": "B",
        //conventions
        "sprinklers": "Sulama Püskürtücüleri",
        "dripStarts": "Damlama Başlangıcı",
        "rzwLayer": "Kök Bölgesi Sulama",
        "dripLines": "Damlama Hattı",
        "valvesLayer": "Vanalar",
        "waterSources": "Su Kaynağı",
        "quickCoupLayer": "Hızlı Bağlantı",
        "controllers": "Kontrol Cihazları",
        "sensorsLayer": "Sensörler",
        "mainPipes": "Ana Boru",
        "lateralPipes": "Yan Borular",
        "lateralPipes_sprinklerZone": "Bölge (Sulama Püskürtücüleri)",
        "lateralPipes_dripZone": "Bölge (Damlama Hatları)",
        "lateralPipes_rzwZone": "Bölge (Kök Bölgesi Sulama)",
        "lateralPipes_emptyZone": "Bölge (Tüketici Yok)",
        "trenchesLayer": "Çukurlar",
        "insetsLayer": "Eklemeler",
        "wiresLayer": "Kablolar",
        wirelessLayer: "Kablosuz bağlantı",
        senswiresLayer: "Kablosuz sensör bağlantısı",
        "senswiresLayer": "Sensör Kabloları",
        "surfaces": "Yüzeyler",
        "ldItemsLayer": "Bitkiler",
        "covers": "Kaplama Alanı",
        "nameplates": "Tüketici Bilgileri",
        "oreolas": "Tüketici İşaretleri",
        "pipeInfo": "Boru Bilgileri",
        "lines": "Çizgiler",
        "overlays": "Üzerlikler",
        "stampLayer": "Çerçeve",
        "stampTexts": "Mühür Metinleri",
        //zonesTable
        "zoneType": "Bölge Türü",
        "color": "Renk",
        "consumers": "Tüketiciler",
        "waterFlow": "Akış",
        "sprinklerZone": "Sulama",
        "dripZone": "Damlama",
        "rzwZone": "Kök Sulama",
        "emptyZone": "Tüketici Yok",
        "specifyDiagonal": "Lütfen, ekran çapınızı inç cinsinden belirtin",
        //sprinklersTable
        "consType": "Tür",
        "consName": "Ad",
        "zoneNum": "Bölge",
        "sector": "Sektor",
        "radius": "Yarıçap",
        "reducedBy": "Azaltılmış",
        "nozzle": "Püskürtme Başlığı",
        "rotor": "Rotor",
        "bubbler": "Kabarcık Püskürtücü",
        "bubblerNozzle": "Kabarcık-Püskürtme Başlığı",
        //dripsTable
        "catId": "Kategori ID",
        "brand": "Marka",
        "emitterStep": "Adım",
        "emitterFlow": "Akış",
        //layersManangerSpecific
        "consumersGrp": "Tüketiciler",
        "nodesGrp": "Nodlar",
        "wiresGrp": "Kablolar",
        "pipesGrp": "Borular",
        "landscapeGrp": "Peyzaj",
        "allTogether": "Hepsi"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        "numsign": "#",
        "typeCol": "Tür",
        "brand": "Marka",
        "catid": "Kategori ID",
        "title": "Başlık",
        "units": "Birimler",
        "amount": "Miktar",
        //predetermined
        "dripLine": "Damlama Hattı",
        "dl16": "Damlama Hattı 16/13mm",
        "dl17": "Damlama Hattı 17mm",
        "dripStart": "Damlama Başlangıcı",
        "ds16": "Damlama Başlangıcı 16/13mm",
        "ds17": "Damlama Başlangıcı 17mm",
        "manifold_no_lps_issue": "Bağlı bölgeler yok",
        "manifold_no_mp_issue": "Ana hatta bağlı değil",
        "manifold_no_wr_issue": "Kontrol kablosu bağlı değil",
        //nodes-----------------------------------
        "sprinkler_unattached": "UYARI!!! Bağlı olmayan SULAMA PÜSKÜRTÜCÜLERİNİZ var (son ürün özellikleri tablosunda gösterilmeyecekler)",
        "drip_unattached": "UYARI!!! Bağlı olmayan DAMLAMA sulama elemanlarınız var (son ürün özellikleri tablosunda gösterilmeyecekler)",
        "mains_unattached": "UYARI!!! Bağlı olmayan ANA BORULARINIZ var (son ürün özellikleri tablosunda gösterilmeyecekler)",
        "mains_empty": "UYARI!!! Tüketici olmayan ANA BORULARINIZ var (son ürün özellikleri tablosunda gösterilmeyecekler)",
        "laterals_unattached": "UYARI!!! Bağlı olmayan YAN BORULARINIZ var (son ürün özellikleri tablosunda gösterilmeyecekler)",
        "laterals_empty": "UYARI!!! Tüketici olmayan YAN BORULARINIZ var (son ürün özellikleri tablosunda gösterilmeyecekler)",
        "rzw_unattached": "UYARI!!! Bağlı olmayan KÖK BÖLGESİ SULAMA elemanlarınız var (son ürün özellikleri tablosunda gösterilmeyecekler)",
        "sensors_unattached": "UYARI!!! Bağlı olmayan SENSÖRLERİNİZ var (son ürün özellikleri tablosunda gösterilmeyecekler)",
        "manifolds_unfinished": "UYARI!!! Tamamlanmamış VALF MANİFOLDLARINIZ var (valf konfigürasyonu yapılamaz)",
        "control_wires_unattached": "UYARI!!! Bağlı olmayan KONTROL KABLOLARINIZ var",
        "control_wires_empty": "UYARI!!! Bağlı olmayan KONTROL KABLOLARINIZ var (valf bağlı değil)",
        "cntr_wr_unattached": "Kontrol Kablosu",
        "youCanSeeThemInTheDrawing": "Her bir öğeyi, öğe sırasının solundaki 'göz' simgesine tıklayarak çizimde görebilirsiniz.",
        "sprinkler_nozzleMT": "Sulama düğmesi (Dişi başlıklı Nozul)",
        "sprinkler_nozzleFT": "Sulama düğmesi (Erkek başlıklı Nozul)",
        "sprinkler_rotor1/2F": "Sulama düğmesi (Rotor) 1/2\" dişi",
        "sprinkler_rotor3/4F": "Sulama düğmesi (Rotor) 3/4\"",
        "sprinkler_rotor1F": "Sulama düğmesi (Rotor) 1\"",
        "sprinkler_rotor1/2M": "Sulama düğmesi (Rotor) 1/2\" erkek",
        "sprinkler_rotor11/4F": "Püskürtücü düğümü (Rotor) 1 1/4\"",
        "sprinkler_rotor11/2F": "Püskürtücü düğümü (Rotor) 1 1/2\"",
        "sprinkler_rotor2F": "Püskürtücü düğümü (Rotor) 2\"",
        "sprinkler_bubbler1/2F": "Sulama düğmesi (Kabarcık Püskürtücü)",
        "sprinkler_bubblerNozzleMT": "Sulama düğmesi (Dişi başlıklı Kabarcık Nozulu)",
        "sprinkler_bubblerNozzleFT": "Sulama düğmesi (Erkek başlıklı Kabarcık Nozulu)",
        "dripIrrigation16": "Damlama Sulama (16/13mm)",
        "dripIrrigation17": "Damlama Sulama (17mm)",
        "rootZoneWatering": "Kök Bölgesi Sulama Sistemi",
        "manifold": "Valf Manifold Düğmesi",
        "automation": "Otomasyon Düğmesi",
        "mainPipes_hdpePE80SDR11": "Ana borular HDPE SDR 11",
        "mainPipes_hdpePE80SDR136": "Ana borular HDPE SDR 13.6",
        "mainPipes_hdpePE80SDR176": "Ana borular HDPE SDR 17.6",
        "lateralPipes_hdpePE80SDR11": "Yan borular HDPE SDR 11",
        "lateralPipes_hdpePE80SDR136": "Yan borular HDPE SDR 13.6",
        "lateralPipes_hdpePE80SDR176": "Yan borular HDPE SDR 17.6",
        "mainPipes_hdpeSDR9": "Ana borular HDPE SDR 9",
        "mainPipes_hdpeSDR11": "Ana borular HDPE SDR 11",
        "mainPipes_hdpeSDR136": "Ana borular HDPE SDR 13.6",
        "mainPipes_hdpeSDR17": "Ana borular HDPE SDR 17",
        "mainPipes_hdpeSDR176": "Ana borular HDPE SDR 17.6",
        "lateralPipes_hdpeSDR9": "Yan borular HDPE SDR 9",
        "lateralPipes_hdpeSDR11": "Yan borular HDPE SDR 11",
        "lateralPipes_hdpeSDR136": "Yan borular HDPE SDR 13.6",
        "lateralPipes_hdpeSDR17": "Yan borular HDPE SDR 17",
        "lateralPipes_hdpeSDR176": "Yan borular HDPE SDR 17.6",
        "mainPipes_pvcSCH40": "Ana borular PVC SCH40",
        "mainPipes_pvcSCH80": "Ana borular PVC SCH80",
        "mainPipes_pvcCL315": "Ana borular PVC CLASS 315",
        "mainPipes_pvcCL200": "Ana borular PVC CLASS 200",
        "mainPipes_pvcCL160": "Ana borular PVC CLASS 160",
        "mainPipes_pvcCL125": "Ana borular PVC CLASS 125",
        mainPipes_pvcUSCJPN18: "Main pipes PVC-U SCJ (PN18)",
        mainPipes_pvcUSCJPN12: "Main pipes PVC-U SCJ (PN12)",
        mainPipes_pvcUSCJPN9: "Main pipes PVC-U SCJ (PN9)",
        mainPipes_pvcUSCJPN6: "Main pipes PVC-U SCJ (PN6)",
        mainPipes_pvcUSCJPN45: "Main pipes PVC-U SCJ (PN4.5)",
        "mainPipes_ldpeCLASS3": "Ana borular LDPE CLASS 3",
        "lateralPipes_pvcSCH40": "Yan borular PVC SCH40",
        "lateralPipes_pvcSCH80": "Yan borular PVC SCH80",
        "lateralPipes_pvcCL315": "Yan borular PVC CLASS 315",
        "lateralPipes_pvcCL200": "Yan borular PVC CLASS 200",
        "lateralPipes_pvcCL160": "Yan borular PVC CLASS 160",
        "lateralPipes_pvcCL125": "Yan borular PVC CLASS 125",
        lateralPipes_pvcUSCJPN18: "Lateral pipes PVC-U SCJ (PN18)",
        lateralPipes_pvcUSCJPN12: "Lateral pipes PVC-U SCJ (PN12)",
        lateralPipes_pvcUSCJPN9: "Lateral pipes PVC-U SCJ (PN9)",
        lateralPipes_pvcUSCJPN6: "Lateral pipes PVC-U SCJ (PN6)",
        lateralPipes_pvcUSCJPN45: "Lateral pipes PVC-U SCJ (PN4.5)",
        "lateralPipes_ldpeCLASS3": "Yan borular LDPE CLASS 3",
        "wiring": "Kablolar",
        "qcv": "Hızlı Bağlantı Vanaları",
        "fixedCntr": "sabit",
        "stand_aloneCntr": "bağımsız",
        "modularCntr": "modüler",
        "decoderCntr": "dekoder",
        "inset": "Boru Kol",
        "insets": "Kolluklar",
        //-----------------------------------------
        "novar": "seçenek yok",
        "choosevar": "seçenek seç",
        //element.types----------------------------
        "nozzle": "Nozul",
        "rotor": "Rotor",
        "rotorNozzle": "Rotor nozulu",
        "bubbler": "Bubbler",
        "bubblerNozzle": "Bubbler-nozulu",
        "rzw": "Kök bölgesi sulama sistemi",
        "sprayBody": "Sprey gövdesi",
        "sprinklerStandAssembly": "Sulama püskürtücü standı (Riser)",
        "outBarb": "Nozul bağlantısı",
        "flexPipe": "Esnek boru",
        "sj": "Salınımlı bağlantı",
        "inBarb": "Boru bağlantısı",
        "midSprinkPipeFitting": "Bağlantı montajı",
        "endSprinkPipeFitting": "Son bağlantı montajı",
        "midRZWPipeFitting": "Bağlantı montajı",
        "endRZWPipeFitting": "Son bağlantı montajı",
        "dripPipe": "Damlama borusu",
        "blindPipe": "Kör boru",
        "dripTeeFitting": "Damlama t montajı",
        "dripCapFitting": "Damlama kapak montajı",
        "dripCouplingFitting": "Damlama bağlantı montajı",
        "dripElbowFitting": "Damlama dirsek montajı",
        "dripSpike": "Damlama mızrak",
        "sprinklerZoneValve": "Sulama bölge valfi",
        "emptyZoneValve": "Tüketici olmayan valf",
        "valveOutFitting": "Valf bağlantısı",
        "dripZoneValve": "Damlama bölge valfi",
        "rzwZoneValve": "Kök sulama valfi",
        "pressureReg": "Basınç düzenleyici",
        "filter_pressureReg": "Filtre ile basınç düzenleyici",
        "controller": "Kontrol cihazı",
        "flowMeter": "Akış ölçer",
        "rainSensor": "Yağmur sensörü",
        "soilSensor": "Toprak nem sensörü",
        "freezeSensor": "Donma sensörü",
        "wrFreezeSensor": "Kablosuz Yağmur/Donma sensörü",
        "windSensor": "Rüzgar sensörü",
        "solarSensor": "Güneş sensörü",
        "flowSensor": "Akış sensörü",
        "weatherStation": "Hava durumu istasyonu",
        "solarPanel": "Güneş paneli",
        "mainPipe": "Ana boru",
        "teeFitting": "T montajı",
        "elbowFitting": "Dirsek montajı",
        "reducerFitting": "Redüktör montajı",
        "lateralPipe": "Yan boru",
        "capFitting": "Kapak montajı",
        "basicCable": "Temel kablo",
        "basicWire": "Temel tel",
        "sensorCable": "Hava sensörü kablosu",
        "qcPlastic": "Q/C Vanası plastik",
        "qcMetal": "Q/C Vanası metal",
        "gateway": "Ağ geçidi",
        "antExt": "Anten uzatma",
        "loramod": "LoRa modülleri",
        //typesOfAcessories
        "hdpeCOR": "Dalgalı boru",
        "expModule": "Genişletme modülü",
        "rzwSleeve": "Kumaş kolluk",
        "rwCap": "Geri kazanılmış su kapak",
        "gutterMount": "Oluk montajı",
        "delayRelay": "Gecikme rölesi",
        "fctFlow": "FCT Konnektör T",
        "fctBspAdap": "FCT montajı için adaptör",
        "drainCheckValve": "Kontrol valfi",
        "rwId": "Geri kazanılmış su kimliği",
        "vpc": "Vandalizm önleyici kapak",
        "inletFilter": "Giriş filtresi",
        "wifiModule": "Wi-Fi modülü",
        "wallMount": "Duvar montajı",
        "rwsSock": "Kumaş kolluk",
        "rwsGrate": "RWS için ızgara",
        "npCover": "İçme suyu dışı kapak",
        "sprExt": "Sprey uzantısı",
        "popUpToThread": "Sprey adaptörü",
        "valveBox": "Vana kutusu",
        "valveBoxExt": "Vana kutusu uzantısı",
        "qcPlasticKey": "Q/C Valfi anahtarı",
        "qcPlasticElbFit": "Dirsek montajı",
        "qcMetalKey": "Q/C Valfi anahtarı",
        "qcMetalElbFit": "Dirsek montajı",
        "qcMetalCapKey": "Kapak anahtarı",
        "insTape": "İzolasyon bandı",
        "wrConn": "Bağlayıcı",
        "shrinkTube": "Isı büzüşen tüp",
        "hcFrontPanel": "Ön panel",
        "ball_valve": "Top vanası",
        "check_valve": "Kontrol valfi",
        "thread_manifold": "Manifold",
        "plastic_filter": "Filtre (plastik)",
        "waterMeter": "Su sayacı",
        "rfModule": "Radyo modülü",
        "largeAntenna": "Anten",
        "wifiHub": "Wi-Fi Hub",
        "handRemoteKit": "Uzaktan kumanda kit",
        "handRemote": "Uzaktan kumanda",
        "wifiBundleKit": "Wi-Fi Paket Kiti",
        //typesOfFittings
        //drip
        "barb_cap_8": "Damlama son kapatma",
        "barb_elbow_PP": "Barb dirsek",
        "barb_elbow_PT": "Konu ile barb dirsek",
        "barb_tee_PPP": "Barb tee",
        "barb_coupling_PP": "Barb bağlantı",
        "barb_cross_PPPP": "Barb çapraz bağlantı",
        "barb_cap_P": "Barb son kapatma",
        "barb_coupling_PT": "Konu ile barb bağlantı",
        "barb_tee_PTP": "Konu ile barb tee",
        "barb_valve_PT": "Konu ile barb valf",
        "barb_valve_PP": "Barb valf",
        "twlc_elbow_PP": "Döner kilit dirsek",
        "twlc_tee_PPP": "Döner kilit tee",
        "twlc_coupling_PP": "Döner kilit bağlantı",
        "twlc_cross_PPPP": "Döner kilit çapraz bağlantı",
        "twlc_cap_P": "Döner kilit son kapatma",
        "twlc_coupling_PT": "Konu ile döner kilit bağlantı",
        "twlc_tee_PTP": "Konu ile döner kilit tee",
        "twlc_valve_PT": "Konu ile döner kilit valf",
        "twlc_valve_PP": "Döner kilit valf",
        "dl_valves": "Özel valfler",
        //pipe
        "hdpeSDR9": "Boru HDPE SDR 9",
        "hdpeSDR11": "Boru HDPE SDR 11",
        "hdpeSDR136": "Boru HDPE SDR 13.6",
        "hdpeSDR17": "Boru HDPE SDR 17",
        "hdpeSDR176": "Boru HDPE SDR 17.6",
        "ldpeSDR9": "Boru LDPE SDR 9",
        "ldpeSDR11": "Boru LDPE SDR 11",
        "ldpeSDR136": "Boru LDPE SDR 13.6",
        "ldpeSDR17": "Boru LDPE SDR 17",
        "pvcSCH40": "Boru PVC SCH40",
        "pvcSCH80": "Boru PVC SCH80",
        "pvcCL315": "Boru PVC CLASS 315",
        "pvcCL200": "Boru PVC CLASS 200",
        "pvcCL160": "Boru PVC CLASS 160",
        "pvcCL125": "Boru PVC CLASS 125",
        pvcUSCJPN18: "Pipe PVC-U SCJ (PN18)",
        pvcUSCJPN12: "Pipe PVC-U SCJ (PN12)",
        pvcUSCJPN9: "Pipe PVC-U SCJ (PN9)",
        pvcUSCJPN6: "Pipe PVC-U SCJ (PN6)",
        pvcUSCJPN45: "Pipe PVC-U SCJ (PN4.5)",
        "ldpeCLASS3": "Boru LDPE CLASS 3",
        "compress_elbow_PT": "Sıkıştırma/Konu dirsek",
        "compress_coupling_PT": "Sıkıştırma/Konu bağlantı",
        "compress_tee_PTP": "Sıkıştırma/Konu t montajı",
        "compress_cap_P": "Sıkıştırma son tapa",
        "compress_elbow_PP": "Sıkıştırma dirsek",
        "compress_coupling_PP": "Sıkıştırma bağlantı",
        "compress_tee_PPP": "Sıkıştırma t montajı",
        "compress_cross_PPPP": "Sıkıştırma çapraz bağlantı",
        "compress_single_clamp_saddle": "Tek kelepçe montajı",
        "compress_ballvalve_PP": "Sıkıştırma top valfi",
        "compress_ballvalve_PT": "Sıkıştırma/Konu top valfi",
        "customfit_elbow_PT": "Özel/Konu dirsek",
        "customfit_coupling_PT": "Özel/Konu bağlantı",
        "customfit_tee_PTP": "Özel/Konu t montajı",
        "customfit_cap_P": "Özel son tapa",
        "customfit_elbow_PP": "Özel dirsek",
        "customfit_coupling_PP": "Özel bağlantı",
        "customfit_tee_PPP": "Özel t montajı",
        "customfit_cross_PPPP": "Özel çapraz bağlantı",
        "customfit_single_clamp_saddle": "Tek kelepçe montajı",
        "customfit_ballvalve_PP": "Özel top valfi",
        "customfit_ballvalve_PT": "Özel/Konu top valfi",
        "thread_nipple": "Borucuk",
        "thread_coupling": "Bağlantı",
        "thread_mf_reducer": "Erkek/Dişi redüktör",
        "thread_mf_adapter": "Erkek/Dişi adaptör",
        "thread_mf_bush": "Erkek/Dişi çalı",
        "thread_tee": "Dişi t montajı",
        "thread_elbow": "Dişi dirsek",
        "thread_mf_elbow": "Erkek/Dişi dirsek",
        "thread_cap": "Dişi kapak",
        "thread_plug": "Erkek tapa",
        "thread_union_nut": "Birleştirme somunu",
        "thread_cross": "Çapraz bağlantı",
        "cable": "Kablo",
        "wire": "Tel",
        // slip
        "slip_single_clamp_saddle": "Tek kelepçeli montaj (PVC boru üzerinde)",
        "slip_elbow_PT": "Kayar/Konu dirsek",
        "slip_coupling_PT": "Kayar/Konu bağlantı",
        "slip_tee_PTP": "Kayar/Konu t montajı",
        "slip_cap_P": "Kayar son tapa",
        "slip_elbow_PP": "Kayar dirsek",
        "slip_coupling_PP": "Kayar bağlantı",
        "slip_tee_PPP": "Kayar t montajı",
        "slip_cross_PPPP": "Kayar çapraz bağlantı",
        "slip_ballvalve_PP": "Kayar Top Valf",
        "slip_ballvalve_PT": "Kayar/Konu Top Valf",
        //extendables
        "arbitraryFittings": "Keyfi montaj parçaları",
        "dripStartAssembly": "Damlalık başlangıç montajı",
        "intakeAssembly": "Emiş montajı",
        "offtakeAssembly": "Alım montajı keyfi parçalar",
        "numofvalves": "Vana sayısı: ",
        "numofvalvesshort": "Vanalar: ",
        "numofmanifs": "Manifold sayısı: ",
        "intakePipeSize": "Emiş boru boyutu: ",
        "valveBoxes": "Vana kutuları",
        "valveAccessories": "Vana aksesuarları",
        "oneValveAccessories": "Vana aksesuarları",
        "controllerAccessories": "Kontrol cihazı aksesuarları",
        "sensorAccessories": "Sensör aksesuarları",
        "sprBodyAccessories": "Püskürtme gövde aksesuarları",
        "rzwAccessories": "Kök bölgesi sulama aksesuarları",
        "pipeStartFittings": "Ana boru keyfi montaj parçaları",
        "qcAccessories": "Q/C Vana aksesuarları",
        "wiringAccessories": "Kablo aksesuarları",
        "pipeSize": "Boru boyutu: ",
        "endOfPipe": "(Son pozisyon)",
        "midOfPipe": "(Kesim içi)",
        "emptyRender": [
            "Üzgünüz... hiçbir içerik ayrıştırılamadı",
            "Henüz işlenmemiş sulama düğümlerinden hiçbirini tamamlamadınız"
        ],
        "serviceFail": [
            "Üzgünüz... özellik düzenleme hizmetine şu anda ulaşılamıyor",
            "Bağlantı kurulduğunda lütfen tekrar deneyin",
            "Daha önce yaptığınız yapılandırma kaydedilecek"
        ],
        "serviceTrialExpired": [
            "Üzgünüz... özellik düzenleme hizmeti hesabınız için kullanılabilir değil",
            "Bu, deneme sürenizin sona erdiği ve bu hizmeti kullanmak istiyorsanız",
            "<a href='/account/subscription'>PRO Hesaba yükseltebilirsiniz</a>"
        ],
        "serviceLimitReached": [
            "Günlük özellik sayfası işleme sınırlamanıza ulaştınız",
            "Günlük özellik işleme sınırını kaldırmak için",
            "<a href='/account/subscription'>PRO Hesaba yükseltebilirsiniz</a>"
        ],
        "findInDrawing": "Tuvalde göster",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        "labours_group_pipes": "Boru Döşeme İşleri",
        "labours_group_fittings": "Bağlantı Parçaları İşleri",
        "labours_group_valveBoxes": "Vana Kutuları İşleri",
        "labours_group_wires": "Kablo Döşeme İşleri",
        "labours_group_sprinklers": "Sulama Başlıkları İşleri",
        "labours_group_rws": "Kök Bölgesi Sulama İşleri",
        "labours_group_sprinklerConnections": "Sulama Başlığı Bağlantı İşleri",
        "labours_group_drip": "Damlalık ve Bağlantı İşleri",
        "labours_group_manifolds": "Kollektörler İşleri",
        "labours_group_quickCoupling": "Hızlı Bağlantı İşleri",
        "labours_group_controllers": "Kontrol Cihazları İşleri",
        "labours_group_sensors": "Sensörler İşleri",
        "labours_group_trenches": "Trenches İşleri",
        "labours_group_insets": "Boru Manşonları İşleri",
        "labours_group_lawns": "Çim Alan İşleri",
        "labours_group_irrigatedArea": "Sulanan Alan İşleri"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        "MMMM": ["\x00", "Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
        "MMM": ["\x01", "Oca", "Şub", "Mar", "Nis", "May", "Haz", "Tem", "Ağu", "Eyl", "Eki", "Kas", "Ara"],
        "dddd": ["\x02", "Pazar", "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi"],
        "ddd": ["\x03", "Paz", "Pts", "Sal", "Çar", "Per", "Cum", "Cts"],
        //buttonsCaps
        "ok": "Tamam",
        "save": "Kaydet",
        "apply": "Uygula",
        "defaults": "Varsayılanlar",
        "retry": "Yeniden Dene",
        "finish": "Tamamla",
        "safeRestart": "Güvenli Yeniden Başlat",
        "saveAndExit": "Kaydet ve Çık",
        "exit": "Çık",
        "cancel": "İptal",
        "rename": "Yeniden Adlandır",
        "idk": "Bilmiyorum",
        "getFile": "Dosya Al",
        "reset": "Sıfırla",
        "random": "Rastgele",
        //misc
        "zoneNum": "Bölge #",
        "valveNum": "Vana Kutusu #",
        "zonesColoring": "Bölgelerin Temsili",
        "coversColoured": "Sulama Başlığı Kapaklarını Boya",
        "dripsColoring": "Damlalık Hatlarının Renklendirilmesi",
        "dripsSameAsZonesColored": "Damlalık Hat, Bölge Renginde",
        //saveOflline
        "saveOffline": [
            "Üzgünüz... bağlantı kaybedildi",
            "Ancak endişelenmeyin, projenize çevrimdışı modda devam edebilirsiniz.",
            "Çevrimdışıyken tüm kayıtlarınız tarayıcınızın indirilenler klasöründe metin dosyası olarak saklanır.",
            "Daha sonra projenizin en son sürümünü sunucuya yükleyebilirsiniz."
        ],
        "restartOffline": [
            "Üzgünüz... bağlantı kaybedildi",
            "Ancak endişelenmeyin, projeniz yerel olarak bilgisayarınıza kaydedildi.",
            "Bu dosyayı tarayıcınızın indirilenler klasöründe bulabilirsiniz.",
            "Çevrimdışı çalışmak isterseniz, http://www.irrisketch.com adresinden uygulamanın Çevrimdışı Sürümünü indirebilirsiniz."
        ],
        "brokenSaving": [
            "Üzgünüz... projenizi yüklerken bir sorun oluştu",
            "Görünüşe göre önceki kaydınız bir şekilde bozulmuş.",
            "Ancak endişelenmeyin, projeniz şu anda 'Bozuk' olarak işaretlenmiştir.",
            "Teknik ekibimiz bu durumu en kısa sürede ele alacaktır.",
            ""
        ],
        "corruptedSavingFile": [
            "Üzgünüz... yüklemeye çalıştığınız dosya okunabilir değil",
            "Ancak endişelenmeyin, bu dosyayı onarabiliriz.",
            "Yapmanız gereken tek şey, bu bozuk dosyayı atölye dosya yükleme formunda göndermek.",
            "Sonra onu tekrar çalışır hale getirmeye çalışacağız."
        ],
        "ajaxReqFail": [
            "Üzgünüz... Sunucu ile bağlantı kaybedildi",
            "Şu anda veri göndermek/alınmasını imkansız hale getirdi",
            "Lütfen daha sonra tekrar deneyin"
        ],
        "critical": [
            "Üzgünüz... bir şeyler ters gitti",
            "Ancak endişelenmeyin, çiziminiz şu anda güvende, devam etmek için güvenli yeniden başlat düğmesine tıklayın..."
        ],
        "fatal": [
            "Üzgünüz... bir şeyler ters gitti",
            "Hizmetimizi daha iyi hale getirmemize yardımcı olun. Bu hatanın hangi kullanıcı işlemlerinden sonra meydana geldiğini açıklayın",
            "Buraya bilgi sağlayın"
        ],
        "areYouSure": [
            "Bu projeyi kapatmaya hazırlanıyorsunuz",
            "Kaydedilmemiş tüm değişiklikler kaybolacaktır."
        ],
        "pickAnotherCSVFile": "Başka bir tane seç",
        "csvFileTooBig": [
            "Maksimum CSV dosya boyutu aşıldı",
            "Optimizasyon amaçlarıyla, maksimum CSV dosya boyutu 4 MB ile sınırlıdır"
        ],
        "notAnCSV": [
            "Üzgünüz, bu dosya türü desteklenmiyor",
            "Desteklenen formatlar: .csv"
        ],
        "pickAnotherImage": "Başka bir tane seç",
        "imageTooBig": [
            "Maksimum resim boyutu aşıldı",
            "Optimizasyon amaçlarıyla, işlenen maksimum resim boyutu 10 MB ile sınırlıdır"
        ],
        "notAnImage": [
            "Üzgünüz, bu dosya türü desteklenmiyor",
            "Desteklenen resim formatları: .pdf, .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        "goProTexts": [
            "EYLEM SINIRLI",
            "Bu eylem ÜCRETSİZ abonelik için izin verilmez"
        ],
        "goPro": "PRO'YA GEÇ",
        "renameLayout": "Yeni adı girin",
        "areYouSureDeleteLayout": [
            "Dikkat! Bu işlem geri alınamaz",
            "Silmek istediğinizden emin misiniz: ",
            "Sil"
        ],
        "setUnderlaySize": [
            "Şimdi çizdiğiniz çizginin uzunluğunu ayarlayın",
            "Yanlış değer girdiniz. Lütfen tekrar deneyin"
        ],
        "setMonitorDiagonal": [
            "Lütfen monitörünüzün çapraz boyutu hakkında bilgi verin",
            "Yanlış değer girdiniz. Lütfen tekrar deneyin"
        ],
        "getSpecsTable": [
            "Belirti çıktı tercihlerini ayarlayın",
            "Ekipmanı gruplayın: ",
            "Düğme", "Marka",
            "Dosya türünü ayarlayın: ",
            "XLSX", "ODS"
        ],
        "saveSpecsVariant": [
            "Başlık girin",
            "Dışa aktar #",
            "Kaydet",
            "Belirtiler kaydediliyor",
            "Tamamlandı. Açmak için buraya tıklayın",
            "Kaydetme başarısız oldu",
            "Mevcut dışa aktarmaları güncelle",
            "Güncelle",
            "Dışa aktarmalar güncelleniyor"
        ],
        "exportLayoutsAsPdf": [
            "Dışa aktarılacak düzenlemeleri seçin",
            "ayrı dosyalar (geliştirme aşamasında)",
            "bir albüm",
            "Dışa Aktar",
            "Düzenlemeleri dışa aktar"
        ],
        "differentSprGroups": [
            "Bu boruya farklı türde su tüketici eklemek başarısız oldu",
            "Irrigasyon tasarım standartlarına göre, aynı bölgede farklı türde su tüketicilerini veya farklı yağış oranlarına sahip sprinklerleri karıştırmak kabul edilemez."
        ],
        "tooFarAwaySpr": [
            "Tüketicileri bağlamak başarısız oldu",
            "Bazı tüketiciler, yan boruya bağlanmak için çok uzakta. Bağlantı mesafesini tercihler menüsünde yapılandırabileceğiniz maksimum mesafe"
        ],
        "outlayerConfig": [
            "Belirti sayfası yapılandırması"
        ],
        "presetsMenu": {
            "title": "Ön Ayarlar",
            "titleTextboxLabel": "Ön Ayar Başlığı",
            "descriptionTextboxLabel": "Açıklama",
            "applyButton": "<i class='far fa-check-circle'></i>&nbsp;Uygula",
            "defaultButton": "<i class='far fa-undo'></i>&nbsp;Varsayılanı Ayarla",
            "removeButton": "<i class='far fa-trash'></i>&nbsp;Kaldır",
            "updateButton": "<i class='far fa-sync'></i>&nbsp;Güncelle",
            "createButton": "<i class='far fa-plus'></i>&nbsp;Yeni Oluştur",
            "closeButton": "<i class='far fa-times'></i>&nbsp;Kapat",
            "favorites_drawing": "Favori Araçlar (Manzara)",
            "favorites_sprinkling": "Favori Araçlar (Irrigasyon)",
            "favorites_layouting": "Favori Araçlar (Düzenlemeler)",
            "configs_drawing": "Proje Yapılandırma",
            "configs_outlayer": "Belirti Sayfası Yapılandırma"
        },
        "newPresetItem": "Yeni Ön Ayar",
        "cL_alreadyConnected": [
            "Satırları birleştirmek başarısız oldu",
            "Bu hatlar her ikisi de şuna bağlı"
        ],
        "cL_segOnElem": [
            "Satırları birleştirmek başarısız oldu",
            "Bağlanamazsınız segment olan bir şeye"
        ],
        "cL_strangeError": [
            "Satırları birleştirmek başarısız oldu",
            "Üzgünüm...Bağlantı başarısız oldu"
        ],
        "cL_misgrouping": [
            "Satırları birleştirmek başarısız oldu",
            "Bu hatlar, aynı bölgeye yerleştirmeniz önerilmeyen tüketiciye sahiptir. Bunları yine de bağlamak isterseniz, projenin yapılandırmasında 'Güvensiz Modu' açın."
        ],
        "cL_valve": "Valflar Manifoldu",
        "cL_waterSource": "Su Kaynağı",
        "cL_dripStart": "Damlama Başlangıcı",
        "cL_controller": "Kontrol Cihazı",
        "cL_sensors": "Sensör",
        "cL_valves": "Valflar Manifoldu",
        "cL_notSameVariant": [
            "Satırları birleştirmek başarısız oldu",
            "Bu hatlar farklı tiplere sahiptir",
            "Şu anda çizim yapılan hattın tipi",
            "Bağlanmak istediğiniz hatın tipi"
        ],
        "hasRestorableProject": [
            "Bu projeniz için kaydedilmemiş verilere sahipsiniz",
            "Kaydedilmemiş durumu geri yükleyebilirsiniz. Anlık görüntülenen zamandan itibaren alınmıştır"
        ],
        "restoreProject": "Geri Yükle",
        "imageLost": [
            "Üzgünüz, sunucuda bazı arka plan resimlerini bulamıyoruz",
            "Bu resim bulunamadı:"
        ],
        precipCalcError_mixedError: [
            'Yağış haritaları hatası',
            'Püskürtücülerin kombinasyonu için yağış haritaları oluşturulamadı:',
        ],
        precipCalcError_mprNonMprRot: 'Normal rotorlar ve MPR memeleri olan rotorlar karıştırılamaz',
        precipCalcError_mprNozNonMprRot: 'MPR memeleri ve normal rotorlar karıştırılamaz',
        precipCalcError_staticNozRot: 'Statik memeler rotorlarla karıştırılamaz',
        precipCalcError_staticMprNoz: 'Statik memeler MPR memeleri ile karıştırılamaz',
        precipCalcError_missingError: [
            'Yağış haritaları hatası',
            'Püskürtücüler için eksik yağış profilleri:',
        ],
        precipCalcError_zoningError: [
            'Yağış haritaları bölgeleme hatası',
            'Püskürtücülerin kombinasyonu için yağış haritaları oluşturulamadı:',
        ],
        precipCalcError_noZoneAndZone: 'Bağlı ve bağlantısız rotorlar için aynı anda yağış hesaplanamaz. Çalışma süresi bilinmiyor, bu nedenle rotorların dönüş sayısı belirsiz',
        algoNozzler_noSolutions: [
            'Olası sulama başlığı yerleştirme çözümleri bulunamadı',
            'Şunları deneyin:',
            '1. Otomatik Yerleştirme aracı yapılandırma menüsündeki örtüşme kısıtlamalarını ve diğer seçenekleri değiştirin',
            '2. Yerleştirme esnekliği sağlayabilecek başka bir tür sulama başlığı seçin',
            '3. Aşağıdaki düğmeyi kullanarak, örtüşme ve kapsama alanı için daha "gevşek" kısıtlamalarla çözmeyi yeniden başlatın'
        ],
        retryWithLooseOptions: "'Gevşek' seçeneklerle yeniden dene",
        "cannotSaveBecauseOffline": [
            "Sunucuya istek gönderilemedi",
            "Sunucuya bağlantı yok",
            "İnternet bağlantınızın olduğundan emin olun",
            "Verilerinizi kaybetmemek için bu pencereyi kapatmayın ve sunucu bağlantısı sağlandığında verileri daha sonra tekrar kaydetmeyi deneyin",
            "",
        ],
        "cannotSaveBecauseTooManyFails": [
            "Kaydetme isteği başarısız oldu",
            "Çok sayıda geçersiz kod denemesi",
            "E-posta adresinizi doğru girdiğinizden emin olun ve 30 saniye sonra tekrar deneyin.",
            "",
            "",
        ],
        "cannotSaveBecauseNoMailProvided": [
            "Kaydetme isteği başarısız oldu",
            "E-posta adresi yanlış girildi",
            "E-posta adresinizi doğru girdiğinizden emin olun ve tekrar deneyin",
            "",
            "",
        ],
        "designRequestCompleted": [
            "İsteğiniz başarıyla oluşturuldu/güncellendi",
            "Düzenleme bağlantısı", "kopyala",
            "Görüntüleme bağlantısı", "kopyala",
        ],
        "designRequestContacts": [
            "İletişim Bilgileri",
            "Organizasyon",
            "Ad",
            "E-posta",
            "Telefon",
            "Adres",
            "Web Sitesi",
        ],
        "designRequestInfo": [
            "Tasarım Stüdyosu'na hoş geldiniz!",
            "Burada sulama sisteminizi planlamak için kolay ve hızlı bir şekilde bir istek oluşturabilirsiniz.",
            "Bir <a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>talimat videosu burada</a> bulabilirsiniz.",
            "Daha fazla bilgi veya sorularınız varsa, lütfen bizimle iletişime geçmekten çekinmeyin."
        ],
        "approveActionByCode": [
            "Eylemi Onayla",
            "Verdiğiniz e-posta adresine bir onay kodu içeren bir e-posta gönderildi.",
            "Lütfen bu kodu aşağıdaki alana girin",
            "Geçersiz bir numara girdiniz, tekrar deneyin"
        ],
        "revisionCheckFailedSoft": [
            'Revizyon Çatışması!',
            'Bu proje şu anda başka bir tarayıcıda veya cihazda açılmış durumda.',
            'Sunucudaki verileri üzerine yazabilirsiniz (çünkü projenizin yalnızca bir sürümünü saklıyoruz), ancak dikkatli olun - diğer oturumlarda yapılan ilerleme kaybolacaktır!',
            'Daha iyi bir strateji, bu projenin nerede ve kim tarafından açıldığını anlamak ve hangi sürümün güncel olduğuna karar vermek olacaktır.',
            'Bu aynı anda açılan projenin en son sürümünü denetim altına almak istiyorsanız, bu projeyi tarayıcınızdaki bu sekli çoğaltarak tekrar açabilirsiniz.',
        ],
        "revisionBlocked": [
            'Kaydetme, Admin tarafından engellendi!',
            'Şu anda projenizde meydana gelen hatalar nedeniyle teknik ekibimiz tarafından inceleniyor.',
            'İncelemenin tamamlanmasını bekleyin, ardından size e-posta ile daha fazla talimat gönderilecektir.',
        ],
        missingVariants: [
            'Eksik öğeler hatası',
            'Aşağıda, proje kitaplığınızda bulunmayan ve bu nedenle görüntülenemeyen özel öğelerin listesi bulunmaktadır:',
            'Lütfen bu öğeleri içeren Setleri proje yapılandırma menüsünden (Atölyede) etkinleştirin'
        ],
        "openInOtherTab": "En Sonunu Aç",
        "overwrite": "Üzerine Yaz",
        "saveToFile": "Dosyaya Kaydet",
        "filterSelection_exclude": "Seçimden Hariç Tut",
        "filterSelection_include": "Seçime Dahil Et",
        "filterSelectionNames": {
            "sprinklers": "Tüketici",
            "sprinklers_nozzle": "Tüketici - Memeler",
            "sprinklers_rotaryNozzle": "Tüketici - Döner Memeler",
            "sprinklers_rotor": "Tüketici - Rotorlar",
            "sprinklers_bubbler": "Tüketici - Bubblers",
            "sprinklers_bubblerNozzle": "Tüketici - Bubbler-Memeler",
            "dripStarts": "Damlama Başlangıçları",
            "rzwLayer": "Kök Bölgesi Sulama",
            "dripLines": "Damlama Hatları",
            "valvesLayer": "Valf Manifoldları",
            "waterSources": "Su Kaynakları",
            "controllers": "Kontrol Cihazları",
            "sensorsLayer": "Sensörler",
            "mainPipes": "Ana Borular",
            "lateralPipes": "Yan Borular",
            "trenchesLayer": "Siperler",
            "insetsLayer": "Kutular",
            "wiresLayer": "Kablolar",
            wirelessLayer: "Kablosuz bağlantı",
            senswiresLayer: "Kablosuz sensör bağlantısı",
            "senswiresLayer": "Sensör Kabloları",
            "quickCoupLayer": "Hızlı Bağlantılar",
            "surfaces": "Poligonlar ve Çizgiler",
            "ldItemsLayer": "Manzara Öğeleri",
        },
        //SPRINKLER NODE CONFIGS
        "sprinklerNode": "Sprey Başlığı Düğümü",
        "fcType": "Sprey Bağlantı Türü",
        "sj": "Salınım Eklemi",
        "sprinklerStand": "Sprey Başlığı Ayaklığı (Yükseltici)",
        "flexPipeBarbs": "Esnek Boru + Taraflar",
        "minFlexPipeLength": "Bağlantı başına minimum esnek boru uzunluğu",
        "midSprinkPipeFitting": "Bağlantı Fittingsi",
        "endSprinkPipeFitting": "Bitiş Boru Fittingsi",
        "single_clamp_saddle": "Kelepçe Sadakası",
        "tee_PTP": "Dişi BSP Konik Dişi ile Tee",
        "elbow_PT": "Dişi BSP Konik Dişi ile Dirsek",
        "coupling_PT": "Dişi BSP Konik Dişi ile Adaptör",
        //MANIFOLD NODE CONFIGS
        "manifoldNode": "Manifold Düğümleri",
        "valvesOutlay": "Vana Dizilimi",
        "fold": "Katlanmış",
        "unfold": "Açılmış",
        "threadsNode": "Dişli Bağlantılar",
        "threadTypes": "Diş Türleri",
        //AUTOMATION NODE CONFIGS
        "automationNode": "Otomasyon düğümü",
        "controllerModules": "Modüler denetleyici genişleme modülleri seçildi:",
        "controllerVoltage": "Denetleyici giriş voltajı:",
        controllerVoltageV2: "Denetleyici giriş voltajı:",
        "230": "230 VAC",
        "230A": "230 VAC (AUS)",
        "120": "120 VAC",
        "24": "24 VAC",
        "autoModules": "Otomatik (en iyi uyum)",
        "userModules": "Manuel (aksesuar olarak)",
        //RZW NODE
        "rzwNode": "Kök bölge sulama düğümü",
        "midRZWPipeFitting": "Bağlantı düzeneği",
        "endRZWPipeFitting": "Son-boru düzeneği",
        //DRIP node
        "dripNode": "Damlama sulama",
        "dripConnectionType": "Damlama bağlantı türü",
        "dripLengthPrecision": "Boru uzunluğundan sonra ondalık basamak sayısı",
        "dripTubingAddon": "Damlama boru katkısı",
        "barb": "Damlama bağlantı parçaları",
        "twistLock": "Twist-lock bağlantı parçaları",
        "dripSpikesStep": "Damlama hortum tutucu çivisi adımı",
        "dripCrossFittingAble": "Çapraz bağlantı parçası kullanabilir",
        "pipesNode": "Boru bölümü",
        "hdpeConnectionType": "HDPE bağlantı türü",
        "ldpeConnectionType": "LDPE bağlantı türü",
        "pvcConnectionType": "PVC bağlantı türü",
        "pipeAddon": "Her çap için boru katkısı",
        "pipeLengthPrecision": "Boru uzunluğundan sonra ondalık basamak sayısı",
        "crossFittingAble": "Çapraz bağlantı parçası kullanabilir",
        "compress": "Sıkıştırma bağlantı parçaları",
        "customfit": "Özel bağlantı parçaları",
        "slip": "Kayma bağlantı parçaları",
        "wiringNode": "Kablo bölümü",
        "exportNode": "Dışa aktarma seçenekleri",
        "exportNumbersPrecision": "Sayıların ondalık basamaklarından sonra sayısı",
        "basicWiringMethod": "Kontrol kablolama yöntemi",
        "cableCoresArray": "Kablo çekirdek sayısı aralığı",
        "noAutoWiring": "Kabloyu manuel olarak ekleyin",
        "separateCableToManifold": "Çoklu çekirdeği manifolda ayır",
        "separateWireToValve": "Vana için teli ayır + manifold için ortak tel",
        "maxCableCores": "Maksimum kablo çekirdek sayısı",
        "verticalWiringAddon": "Denetleyici kablosuna dikey katkı",
        "verticalSensWiringAddon": "Sensör kablosuna dikey katkı",
        "wireAddon": "Her tür için tel katkısı",
        "wireLengthPrecision": "Kablo uzunluğundan sonra ondalık basamak sayısı",
        //DRAWER CONFIG
        drawerConfig: [
            "Proje yapılandırması"
        ],
        //SPRINKLER PRESSURE CONFIGS
        "sprinklerConfig": "Sulama Noktaları",
        "pressureDefinedBy": "Sulama noktalarındaki beklenen basınç",
        "allowReduceRotors": "Rotorların yarıçapını azaltmaya izin ver",
        autoconnector: "Sprinklerlerin yan boru hattına etkileşimli bağlantısı",
        "radio_option_yes": "Evet",
        "radio_option_no": "Hayır",
        extreme_rotor_reduction: "Aşırı (Yüzde 50'ye kadar) (Eşitsiz yağışa neden olabilir)",
        radio_option_yes2: "Evet",
        takeReductionInAccountWhenAutoPlacing: "Sulama başlıklarını otomatik yerleştirirken azaltılmış atış mesafeleri sun",
        takeReductionInAccountWhenAutoPlacingForRotors: "Sulama başlıklarını otomatik yerleştirirken azaltılmış atış mesafeleri sun (Rotors)",
        "recommendedPressure": "Üretici tarafından önerilen basınç",
        "userPressure": "Kullanıcı tarafından ayarlanan basınç",
        "expPressure": "Tüketici tarafından beklenen basınç",
        "sprinklerGroupMode": "Sulama noktalarını gruplama",
        "safeSprGroupMode": "Katı mod (yalnızca uyumlu olanları grupla)",
        "unsafeSprGroupMode": "Güvensiz mod (UYARI! Gruplama kısıtlamaları yok. Kendi riskinizde kullanın)",
        "sprinklerAttachBulkMode": "Toplu Tüketici Bağlantı Modu",
        "safeSprAttachMode": "Zaten bağlı tüketicileri yeniden bağlama",
        "unsafeSprAttachMode": "Güvensiz mod (UYARI! Zaten bağlı tüketicilerin yeniden bağlanma olasılığı vardır. Kendi riskinizde kullanın)",
        //UNITS CONFIG
        "unitsConfig": "Ölçü Birimleri",
        "precisionStd": "Ondalık basamak sayısı",
        "unitsSystemGridAndRuler": "Izgara ve cetvel için ölçü birimleri",
        "distanceUnits": "Mesafe",
        "distancePrecision": "Ondalık basamak sayısı",
        "sprinklerDistUnits": "Sulama noktası yarıçapı",
        "sprinklerDistPrecision": "Ondalık basamak sayısı",
        "areaUnits": "Alan",
        "areaPrecision": "Ondalık basamak sayısı",
        "volumeUnits": "Hacim",
        "volumePrecision": "Ondalık basamak sayısı",
        "waterFlowUnits": "Su akışı",
        "waterFlowPrecision": "Ondalık basamak sayısı",
        "pressureUnits": "Basınç",
        "pressurePrecision": "Ondalık basamak sayısı",
        "velocityUnits": "Hız",
        "velocityPrecision": "Ondalık basamak sayısı",
        "precipRateUnits": "Yağış hızı",
        "precipRatePrecision": "Ondalık basamak sayısı",
        // ZONE PROPS CONFIG
        "climateConfig": "Sulama Süresi Hesaplama",
        "lawnCultureType": "Çim Türü",
        "coolLoving": "Serin sevici",
        "warmLoving": "Sıcak sevici",
        "climateTemp": "Ortalama yaz sıcaklığı",
        "coolClimate": "< 21°C",
        "warmClimate": "21-32°C",
        "hotClimate": "> 32°C",
        "climateHumid": "Ortalama yaz nem oranı",
        "wetClimate": "> 50%",
        "dryClimate": "< 50%",
        "microClimate": "Bölge mikroiklimi&nbsp;<i class='far fa-question-circle'></i>",
        microClimateTooltip: "Mild\n" +
            "Irrigation areas that are in the shade, sheltered from the wind and are away from dry and heated objects\n" +
            "\n" +
            "Normal\n" +
            "Places in the landscape where microclimate conditions are represented: the presence of\n" +
            "buildings, sidewalks and paths, shade, etc. do not significantly affect the values of\n" +
            "evapotranspiration\n" +
            "\n" +
            "Harsh\n" +
            "Reflects conditions that impede plant growth and easily translates to a stressed state if the plant is not properly watered. This can be an open place, under blazing sun, in close proximity to pathways, buildings or other landscape structures, reflecting light from glass or landscape elements that absorb heat, or it can be a windy place.",
        "gentleMicroClimate": "Hafif",
        "normalMicroClimate": "Normal",
        "toughMicroClimate": "Zor",
        "soilType": "Alanlardaki Toprak Kompozisyonu",
        "sand": "Kumlu",
        "sandyLoam": "Kumlu tınlı",
        "lightLoam": "Hafif tınlı",
        "mediumLoam": "Orta tınlı",
        "heavyLoam": "Ağır tınlı",
        "clay": "Kil",
        "heavyClay": "Ağır kil",
        "zoneSlope": "Alanlardaki Genel Eğim",
        "noneIncline": "0-5% (0-3°)",
        "lightIncline": "5-8% (3-5°)",
        "mediumIncline": "8-12% (5-7°)",
        "hugeIncline": "12%+ (7°+)",
        "waterBudget": "Su Bütçesi",
        "lowWB": "Düşük",
        "normalWB": "Normal",
        "highWB": "Yüksek",
        "ft": "fit",
        "in": "inç",
        "ftin": "fit/inç",
        "metric": "metrik",
        "imperialUS": "İngiliz (ABD)",
        //UNITS CONFIG
        "hydraConfig": "Hidrolik",
        "waterTemp": "Su sıcaklığı",
        "maxFlowVelocity": "Borudaki maksimum akış hızı",
        "commonConfig": "Ortak Ayarlar",
        "lateralNozzlerSwitch": "Nozullara geçiş modu",
        "NStabonly": "Sadece Sekme",
        "NStabshift": "Sekme + Shift",
        "showActionSubtitles": "Eylem altyazılarını göster",
        "Yeah": "Evet",
        "Nope": "Hayır",
        "start": "Başla",
        "recalibrate": "Yeniden kalibre et",
        "calibrationSuccess": [
            "Başarıyla kalibre edildi",
            "Şimdi dokunmatik ekranda iki mod için kullanabilirsiniz - 'imleci taşı' (hafif dokunuş hareketi) ve 'sürükleme modu' (sert dokunuş hareketi)"
        ],
        "calibrationFailEqual": [
            "Kalibrasyon başarısız oldu",
            "Her iki modda ekranı nasıl dokunduğunuzda büyük bir fark algılamadık",
            "Tekrar deneyebilirsiniz. Ve parmak yerine stilus kullanmadığınızdan emin olun"
        ],
        "calibrationFailImproper": [
            "Kalibrasyon başarısız oldu",
            "Tüy üzerinde daha büyük bir basınç algıladık",
            "Tekrar deneyebilirsiniz. Ve tüyü anavatana göre daha hafif bir basınçla sürdüğünüzden emin olun"
        ],
        "calibrationImpossible": [
            "Kalibrasyon mümkün değil",
            "Cihazınızın dokunma alanı ölçümünü desteklemediği görünüyor. Bu nedenle dokunma etkileşimi için iki mod tanımlayamayız",
            "Bu durumda, nesneleri sürüklemek için kullanılabilen sanal bir fare kullanabilirsiniz. Bu, ekranın sol tarafında görünecektir."
        ],
        "calibrationNeeded": [
            "Kalibrasyon gereklidir!",
            "Dokunmatik ekranınızı iki modu tanımlayabilmek için kalibre etmemiz gerekiyor:",
            "İmleci taşıma modu - yalnızca imleci etrafta taşımak veya çizim yaparken çok hafif dokunuşla bir segmenti taşımak istediğinizde",
            "Ve sürükleme modu - öğeleri sürüklemek veya yeniden boyutlandırmak istediğinizde kullanılan moddur. Ayrıca birçok öğeyi seçmek istediğinizde de sürükleme hareketi yapmalısınız",
            "Lütfen Başla düğmesine tıklayın ve ekrandaki talimatları takip edin"
        ],
        insertImage: 'Ekle',
        mapImagePicker: [
            "Uydu görüntü yükleyici",
            "Enlem/Boylam",
            "Enlem gir",
            "Boylam gir",
            "Mevcut konum",
            "Git",
            "Adres",
            "Adresin bir kısmını girin ve 'Ara'ya tıklayın",
            "Ara",
            "Yakınlaştır",
            "Kaydır"
        ],
        "imageCrop": [
            "Crop tool"
        ],
        cropImage: "Crop",
        invalid_dataset_1: 'Invalid dataset. Project contains prohibited types of surfaces. Only irrigated (LAWN), non-irrigated and obstacles are allowed.',
        invalid_dataset_2: 'Invalid dataset. Not more or less than ONE irrigated surface is allowed.',
        invalid_dataset_3: 'Invalid dataset. Irrigated surface is self-intersected.',
        invalid_dataset_4: 'Invalid dataset. Obstacle marker should not be compound (Made of more than one polygon)',
        invalid_dataset_5: 'Invalid dataset. Obstacle surface should be fully contained within irrigated surface.',
        invalid_dataset_6: 'Invalid dataset. Project contains prohibited types of sprinklers. Allowed:',
        invalid_dataset_7: 'Invalid dataset. Precipitation rate of sprinklers is out of range',
        invalid_dataset_8: 'Invalid dataset. Sprinklers must not have individual pressure settings',
        invalid_dataset_9: 'Invalid dataset. The project should not set a custom expected pressure at the sprinklers',
        invalid_dataset_10: 'Invalid dataset. Uniformity is too low.',
        invalid_dataset_11: 'Invalid dataset. Overwatered area is too big.',
    }
};
