this.LNG = {
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //UNITS---------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    units: {
        m: "米",
        cm: "厘米",
        mm: "毫米",
        ft: "英尺",
        in: "英寸",
        ftin: "英尺/英寸",
        sqm: "平方米",
        acre: "英亩",
        hectare: "公顷",
        sqft: "平方英尺",
        bar: "巴",
        kpa: "千帕",
        atm: "大气压",
        mH2O: "米水柱",
        psi: "磅每平方英寸",
        l: "升",
        m3: "立方米",
        USg: "加仑",
        lpm: "升/分钟",
        lph: "升/小时",
        m3h: "立方米/小时",
        USgpm: "加仑/分钟",
        USgph: "加仑/小时",
        deg: "度",
        pcs: "件",
        pcsDot: "件。",
        pcsShort: "件。",
        percent: "%",
        in_Alt: "英寸。",
        mps: "米/秒",
        kph: "千米/小时",
        ftps: "英尺/秒",
        degreesCentigrade: "摄氏度",
        mmph: "毫米/小时",
        mmp24h: "毫米/天",
        inph: "英寸/小时",
        // unconvertable
        min: "分钟"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWING TOOLS-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    drawing: {
        autoDrawer: "自动绘制器",
        chooseSprinkler: "选择喷嘴：",
        auto: "自动设置",
        waterSource2row: ["水源", "进水"],
        setLineLength: "设置管道长度（毫米）：",
        setPressure: "设置喷嘴的预期动态压力（巴）：",
        setMaxFlow: "设置最大水流量（升/分钟）：",
        controllerShort: "控制器",
        sensorShort: "传感器",
        action_activateEraser: "激活橡皮擦",
        action_deactivateEraser: "停用橡皮擦",
        action_boolUnite: "联合",
        action_boolIntersect: "交集",
        action_boolSubtract: "减去",
        action_boolExclude: "排除",
        action_changeSprayBody: "设置喷雾",
        action_changeVariant: "设置变体",
        action_changeImgVariant: "设置图像变体",
        action_changeType: "设置类型",
        action_addConsumers: "添加消费者",
        action_drawBranches: "添加分支",
        action_editLine: "编辑线段",
        action_drawCircles: "画圆",
        action_detachAll: "分离所有",
        action_drawBrush: "绘制画笔",
        action_editBrush: "编辑画笔",
        action_changeBrushSize: "画笔大小",
        action_booleans: "布尔运算",
        action_intoPoly: "转换为多边形",
        action_intoBrush: "转换为画笔",
        action_activateRotation: "旋转",
        action_deactivateRotation: "静止",
        action_markZones: "区域表示",
        action_unmarkZones: "移除标记",
        action_sprNames: "喷头名称",
        action_noSprNames: "移除名称",
        action_lockItem: "锁定",
        action_unlockItem: "解锁",
        Circle: "圆形",
        Triangle: "三角形",
        BushForm: "灌木",
        BushForm1: "灌木 1",
        BushForm2: "灌木 2",
        BushForm3: "灌木 3",
        Square: "方形",
        noShadow: "无",
        standardShadow: "标准",
        noArrows: "无",
        startArrow: "起点箭头",
        endArrow: "终点箭头",
        bothArrows: "双向箭头",
        normalSizeSide: "正常",
        invertedSizeSide: "反向",
        strMiter: "斜接",
        strRound: "圆角",
        strBevel: "斜角",
        strSquare: "方形",
        strButt: "平端",
        FWnormal: "正常",
        FWbold: "加粗",
        FWitalic: "斜体",
        FWbolditalic: "斜体加粗",
        FJleft: "左对齐",
        FJright: "右对齐",
        FJcenter: "居中",
        rzwHeight: "高度"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DRAWER HELPER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    interface: {
        //------------------------------------------------------------
        //-------------------TOOL NAMES-------------------------------
        //------------------------------------------------------------
        multiSelector: "选择器",
        //----Drawing
        selectPoly: "没有选择的项目",
        //----Sprinkling
        selectSprink: "没有选择的项目",
        lpNozzler: "连接用水设备",
        dl16CircDrawer: "滴灌圆圈铺设 16/13毫米",
        dl16sDrawer: "滴灌覆盖图 16/13毫米",
        dl17CircDrawer: "滴灌圆圈铺设 17毫米",
        dl17sDrawer: "滴灌覆盖图 17毫米",
        "ldTextDrawer": "文本设置",
        "staticTextDrawer": "文本设置",
        "dynamicTextDrawer": "文本设置",
        "ldStaticTextDrawer": "文本设置",
        "ldtextEditor": "文本编辑",
        //------------------------------------------------------------
        //-------------------VALUES-----------------------------------
        //------------------------------------------------------------
        //Values
        rulerLength: "总距离",
        type: "类型",
        variant: "变体",
        area: "面积",
        perimeter: "周长",
        curveLength: "长度",
        treeDiameter: "直径",
        bushDiameter: "直径",
        nozTypes: "可用类型",
        nozType: "类型",
        sprBod: "喷雾体",
        rad: '半径',
        angle: '角度',
        reducedBy: '减少了',
        consump: '消耗',
        pressure: '压力',
        coverSize: '覆盖范围',
        maxFlow: '最大水流量',
        pipesNum: "连接的管道数量",
        pipeType: "类型",
        pipeLength: "长度",
        wireLength: "长度",
        valvesManifNum: "阀门集管",
        valvesNum: "阀门",
        propDiam: "适当直径",
        curDiam: "绘图直径",
        outsNum: "用水设备",
        flow: "水流量",
        precipRate: "降水率",
        totalPrecipArea: "总覆盖范围",
        uniformity: "均匀度 (CU)",
        overwatered: "过度灌溉",
        precipRateShort: "降水",
        runtimeInd: "运行时间",
        coveredArea: "覆盖面积",
        microClimateInd: "微气候",
        soilTypeInd: "土壤类型",
        zoneSlopeInd: "坡度",
        maxInfiltrationRate: "渗透率",
        waterDemand: "需水量",
        numOfRuns: "每日运行次数",
        timePerRun: "每次运行时间",
        dailyConsumption: "每日消耗",
        dripsNum: "连接的滴灌线",
        dripType: "滴灌类型",
        dripRowsStep: "表面行距",
        dripRowsAngle: "表面行角",
        cntrType: "控制器类型",
        sensType: "传感器类型",
        zonesNum: "控制的区域数",
        trenchWidth: "宽度",
        trenchDepth: "深度",
        trenchVolume: "体积",
        insetDiam: "直径",
        insetLength: "长度",
        insetVar: "材料",
        itemsCount: "数量",
        insetDepth: "深度",
        zoneName: "区域名称",
        valveName: "阀箱",
        itemAlias: "别名",
        //MULTISELECTOR
        itemsSelected: "已选",
        totalArea: "总面积",
        totalPerimeter: "总周长",
        totalLength: "总长度",
        totalVolume: "总体积",
        totalConsumption: "总消耗量",
        //------------------------------------------------------------
        //-------------------STATUSES---------------------------------
        //------------------------------------------------------------
        //Stauses
        isSelfCrossing_true: "无效的多边形",
        isSelfCrossing_false: "有效的多边形",
        isConnected_true: "已连接",
        isConnected_false: "未连接",
        isWired_true: "有线",
        isWired_false: "无线",
        isDripZone_true: "滴灌区",
        isDripZone_false: "",
        isSprinklerZone_true: "喷灌区",
        isSprinklerZone_false: "",
        isOverloaded_true: "超载!!!",
        isOverloaded_false: "",
        isUnderpressured_true: "低压",
        isUnderpressured_false: "",
        isOverpressured_true: "高压",
        isOverpressured_false: "",
        isLocked_true: "已锁定",
        isLocked_false: "",
        //------------------------------------------------------------
        //-------------------CLASSES,SERIES,SUBSERIES etc.------------
        //------------------------------------------------------------
        "Stainless steel": "不锈钢",
        "High speed": "高速",
        "Opposing nozzle": "对立喷嘴",
        "Plastic": "塑料",
        "MPR Nozzles": "MPR 喷嘴",
        "Rotary Nozzles": "旋转喷嘴",
        Nozzles: "喷嘴",
        "Bubbler nozzles": "涌泉喷嘴",
        "Multi-stream": "多流",
        "Dual-stream": "双流",
        "Stream Nozzles": "流式喷嘴",
        "Short Radius Nozzles": "短半径喷嘴",
        "Pressure compensating": "压力补偿",
        "Adjustable flood": "可调洪水",
        Adjustable: "可调",
        Fixed: "固定",
        "Fixed Arc": "固定弧形",
        "Strip Pattern": "条纹模式",
        "Drip line": "滴灌线",
        "Drip cover": "滴灌覆盖",
        "16mm": "16/13毫米",
        "17mm": "17毫米",
        "emitter": "带有滴头",
        "noemitter": "无滴头",
        "Root zone watering": "根区灌溉",
        Lateral: "侧线",
        Main: "主线",
        Trench: "沟槽",
        hdpe: "HDPE",
        pvc: "PVC",
        pvcm: "PVC(公制)",
        ldpe: "LDPE",
        Controller: "控制器",
        Sensor: "传感器",
        Wiring: "连接",
        IrrigateMarks: "区域",
        Surface: "表面",
        Lawn: "草坪",
        Bed: "花坛",
        Shrubs: "灌木",
        Path: "路径",
        Concrete: "混凝土",
        Sand: "沙地",
        Water: "水",
        Bedding: "垫层",
        Flower: "花卉",
        Herbal: "草本",
        geographic: "地理",
        sizeMark: "尺寸",
        scalingBar: "比例尺",
        loCurves: "线条",
        texts: "文本",
        staticText: "静态文本",
        dynamicText: "动态文本",
        stampText: "图章文本",
        stampTextDefault: "文本",
        stampTextgr1: "文件定义",
        stampTextgr2: "地址单元",
        stampTextgr3: "站点名称",
        stampTextgr4: "图纸名称",
        stampTextgr9: "组织信息",
        stampTextgr6t: "阶段",
        stampTextgr7t: "页",
        stampTextgr8t: "页数",
        stampTextgr6: "P",
        stampTextgr7: "1",
        stampTextgr8: "10",
        stampTextgr14t: "章.",
        stampTextgr15t: "参与者",
        stampTextgr16t: "页",
        stampTextgr17t: "文档编号",
        stampTextgr18t: "签名",
        stampTextgr19t: "日期",
        stampTextgr20t: "原始库存号",
        stampTextgr21t: "签名和日期",
        stampTextgr22t: "替换库存号",
        inserts: "管套",
        //------------------------------------------------------------
        //-------------------LAYERS MANIPULATOR-----------------------
        //------------------------------------------------------------
        showLM: "显示图层管理器",
        hideLM: "隐藏图层管理器",
        //------------------------------------------------------------
        //-------------------SOME OTHER DETAILS-----------------------
        //------------------------------------------------------------
        noName: "未命名",
        //------------------------------------------------------------
        //-------------------AJAX LOADING STATUSES--------------------
        //------------------------------------------------------------
        beganExporting: "正在导出布局",
        successExporting: "导出成功",
        failExporting: "导出失败",
        failExportingLimitReached: "<a target='_blank' href='/account/subscription'>已达每日限额</a>",
        exportingLimit: "限制：",
        exportingLeft: "今天剩余：",
        pdfExportingPopUpBlocked: "您的浏览器阻止了弹出窗口。请允许此站点的弹出窗口以获取 .PDF 文件",
        //------------------------------------------------------------
        //-------------------TOOLTIPS---------------------------------
        //------------------------------------------------------------
        tt_group: "弹出线程",
        tt_group_MT: "男性",
        tt_group_FT: "女性",
        tt_riserHeight: "升降器高度",
        tt_pressureReg: "压力调节器",
        tt_checkValve: "（带止回阀）",
        tt_home: "首页",
        tt_prev: "上一个",
        tt_next: "下一个",
        tt_end: "结束",
        tt_add: "添加",
        tt_clone: "克隆",
        tt_remove: "移除",
        tt_rename: "重命名",
        tt_addToFav: "添加到收藏夹",
        tt_remFromFav: "从收藏夹移除",
        tt_presets: "预设",
        tt_MagicAutoPlacer: "`沿线自动布置`",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //LAYOUTER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    layouter: {
        //compass
        N: "北",
        S: "南",
        E: "东",
        W: "西",
        //conventions
        sprinklers: "喷头",
        dripStarts: "滴灌起点",
        rzwLayer: "根区灌溉",
        dripLines: "滴灌管线",
        valvesLayer: "阀门集管",
        waterSources: "水源",
        quickCoupLayer: "快速接头",
        controllers: "控制器",
        sensorsLayer: "传感器",
        mainPipes: "主管道",
        lateralPipes: "支管",
        lateralPipes_sprinklerZone: "区域（喷头）",
        lateralPipes_dripZone: "区域（滴灌管线）",
        lateralPipes_rzwZone: "区域（根区灌溉）",
        lateralPipes_emptyZone: "区域（无消费者）",
        trenchesLayer: "沟槽",
        insetsLayer: "嵌入物",
        wiresLayer: "布线",
        wirelessLayer: "无线连接",
        senswiresLayer: "无线传感器连接",
        senswiresLayer: "传感器布线",
        surfaces: "表面",
        ldItemsLayer: "植物",
        covers: "覆盖面积",
        nameplates: "消费者信息",
        oreolas: "消费者标记",
        pipeInfo: "管道信息",
        lines: "线条",
        overlays: "覆盖层",
        stampLayer: "框架",
        stampTexts: "印章文字",
        //zonesTable
        zoneType: "区域类型",
        color: "颜色",
        consumers: "消费者",
        waterFlow: "水流量",
        sprinklerZone: "喷头",
        dripZone: "滴灌",
        rzwZone: "根区灌溉",
        emptyZone: "无消费者",
        specifyDiagonal: "请指定您的显示器对角线尺寸（英寸）",
        //sprinklersTable
        consType: "类型",
        consName: "名称",
        zoneNum: "区域",
        sector: "区块",
        radius: "半径",
        reducedBy: "减少",
        nozzle: "喷嘴",
        rotor: "转子",
        bubbler: "涌泉",
        bubblerNozzle: "涌泉喷嘴",
        //dripsTable
        catId: "类别ID",
        brand: "品牌",
        emitterStep: "间距",
        emitterFlow: "流量",
        //layersManagerSpecific
        consumersGrp: "消费者",
        nodesGrp: "节点",
        wiresGrp: "布线",
        pipesGrp: "管道",
        landscapeGrp: "景观",
        allTogether: "全部"
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //OUTLAYER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    outlayer: {
        //tableHeaders
        numsign: "#",
        typeCol: "类型",
        brand: "品牌",
        catid: "类别ID",
        title: "标题",
        units: "单位",
        amount: "数量",
        //predetermined
        dripLine: "滴灌管线",
        dl16: "滴灌管线 16/13毫米",
        dl17: "滴灌管线 17毫米",
        dripStart: "滴灌起点",
        ds16: "滴灌起点 16/13毫米",
        ds17: "滴灌起点 17毫米",
        manifold_no_lps_issue: "无连接区域",
        manifold_no_mp_issue: "未连接到主管道",
        manifold_no_wr_issue: "未连接控制线",
        //nodes-----------------------------------
        sprinkler_unattached: "警告!!! 你有未连接的喷头（它们不会在最终规格表中显示）",
        drip_unattached: "警告!!! 你有未连接的滴灌元件（它们不会在最终规格表中显示）",
        mains_unattached: "警告!!! 你有未连接的主管道（它们不会在最终规格表中显示）",
        mains_empty: "警告!!! 你有无消费者的主管道（它们不会在最终规格表中显示）",
        laterals_unattached: "警告!!! 你有未连接的支管（它们不会在最终规格表中显示）",
        laterals_empty: "警告!!! 你有无消费者的支管（它们不会在最终规格表中显示）",
        rzw_unattached: "警告!!! 你有未连接的根区灌溉元件（它们不会在最终规格表中显示）",
        sensors_unattached: "警告!!! 你有未连接的传感器（它们不会在最终规格表中显示）",
        manifolds_unfinished: "警告!!! 你有未完成的集管（你不能完成阀门配置）",
        control_wires_unattached: "警告!!! 你有未连接的控制线",
        control_wires_empty: "警告!!! 你有无连接阀门的控制线",
        cntr_wr_unattached: "控制线",
        youCanSeeThemInTheDrawing: "你可以在绘图中看到每个元素，通过按下元素行左侧的'眼睛'图标",
        sprinkler_nozzleMT: "喷头节点（带内螺纹的喷嘴）",
        sprinkler_nozzleFT: "喷头节点（带外螺纹的喷嘴）",
        "sprinkler_rotor1/2F": "喷头节点（转子）1/2\" 内螺纹",
        "sprinkler_rotor3/4F": "喷头节点（转子）3/4\"",
        "sprinkler_rotor1F": "喷头节点（转子）1\"",
        "sprinkler_rotor1/2M": "喷头节点（转子）1/2\" 外螺纹",
        "sprinkler_rotor11/4F": "喷头节点（旋转）1 1/4\"",
        "sprinkler_rotor11/2F": "喷头节点（旋转）1 1/2\"",
        "sprinkler_rotor2F": "喷头节点（旋转）2\"",
        "sprinkler_bubbler1/2F": "喷头节点（涌泉）",
        sprinkler_bubblerNozzleMT: "喷头节点（带内螺纹的涌泉喷嘴）",
        sprinkler_bubblerNozzleFT: "喷头节点（带外螺纹的涌泉喷嘴）",
        dripIrrigation16: "滴灌系统（16/13毫米）",
        dripIrrigation17: "滴灌系统（17毫米）",
        rootZoneWatering: "根区灌溉系统",
        manifold: "阀门集管节点",
        automation: "自动化节点",
        mainPipes_hdpePE80SDR11: "HDPE SDR 11 主管道",
        mainPipes_hdpePE80SDR136: "HDPE SDR 13.6 主管道",
        mainPipes_hdpePE80SDR176: "HDPE SDR 17.6 主管道",
        lateralPipes_hdpePE80SDR11: "HDPE SDR 11 支管",
        lateralPipes_hdpePE80SDR136: "HDPE SDR 13.6 支管",
        lateralPipes_hdpePE80SDR176: "HDPE SDR 17.6 支管",
        mainPipes_hdpeSDR9: "HDPE SDR 9 主管道",
        mainPipes_hdpeSDR11: "HDPE SDR 11 主管道",
        mainPipes_hdpeSDR136: "HDPE SDR 13.6 主管道",
        mainPipes_hdpeSDR17: "HDPE SDR 17 主管道",
        mainPipes_hdpeSDR176: "HDPE SDR 17.6 主管道",
        lateralPipes_hdpeSDR9: "HDPE SDR 9 支管",
        lateralPipes_hdpeSDR11: "HDPE SDR 11 支管",
        lateralPipes_hdpeSDR136: "HDPE SDR 13.6 支管",
        lateralPipes_hdpeSDR17: "HDPE SDR 17 支管",
        lateralPipes_hdpeSDR176: "HDPE SDR 17.6 支管",
        mainPipes_pvcSCH40: "PVC SCH40 主管道",
        mainPipes_pvcSCH80: "PVC SCH80 主管道",
        mainPipes_pvcCL315: "PVC CLASS 315 主管道",
        mainPipes_pvcCL200: "PVC CLASS 200 主管道",
        mainPipes_pvcCL160: "PVC CLASS 160 主管道",
        mainPipes_pvcCL125: "PVC CLASS 125 主管道",
        mainPipes_pvcUSCJPN18: "PVC-U SCJ (PN18) 主管道",
        mainPipes_pvcUSCJPN12: "PVC-U SCJ (PN12) 主管道",
        mainPipes_pvcUSCJPN9: "PVC-U SCJ (PN9) 主管道",
        mainPipes_pvcUSCJPN6: "PVC-U SCJ (PN6) 主管道",
        mainPipes_pvcUSCJPN45: "PVC-U SCJ (PN4.5) 主管道",
        mainPipes_ldpeCLASS3: "LDPE CLASS 3 主管道",
        lateralPipes_pvcSCH40: "PVC SCH40 支管",
        lateralPipes_pvcSCH80: "PVC SCH80 支管",
        lateralPipes_pvcCL315: "PVC CLASS 315 支管",
        lateralPipes_pvcCL200: "PVC CLASS 200 支管",
        lateralPipes_pvcCL160: "PVC CLASS 160 支管",
        lateralPipes_pvcCL125: "PVC CLASS 125 支管",
        lateralPipes_pvcUSCJPN18: "PVC-U SCJ (PN18) 支管",
        lateralPipes_pvcUSCJPN12: "PVC-U SCJ (PN12) 支管",
        lateralPipes_pvcUSCJPN9: "PVC-U SCJ (PN9) 支管",
        lateralPipes_pvcUSCJPN6: "PVC-U SCJ (PN6) 支管",
        lateralPipes_pvcUSCJPN45: "PVC-U SCJ (PN4.5) 支管",
        lateralPipes_ldpeCLASS3: "LDPE CLASS 3 支管",
        wiring: "布线",
        qcv: "快速接头阀门",
        fixedCntr: "固定",
        stand_aloneCntr: "独立",
        modularCntr: "模块化",
        decoderCntr: "解码器",
        inset: "管套",
        insets: "套管",
        //-----------------------------------------
        novar: "无变体",
        choosevar: "选择变体",
        //element.types----------------------------
        nozzle: "喷嘴",
        rotor: "转子",
        rotorNozzle: "转子喷嘴",
        bubbler: "涌泉",
        bubblerNozzle: "涌泉喷嘴",
        rzw: "根区灌溉系统",
        sprayBody: "喷雾体",
        sprinklerStandAssembly: "喷头支架（升降器）",
        outBarb: "喷嘴接头",
        flexPipe: "柔性管",
        sj: "摆动接头",
        inBarb: "管接头",
        midSprinkPipeFitting: "中间连接件",
        endSprinkPipeFitting: "端管连接件",
        midRZWPipeFitting: "中间连接件",
        endRZWPipeFitting: "端管连接件",
        dripPipe: "滴灌管",
        blindPipe: "盲管",
        dripTeeFitting: "滴灌三通",
        dripCapFitting: "滴灌端帽",
        dripCouplingFitting: "滴灌接头",
        dripElbowFitting: "滴灌弯头",
        dripSpike: "滴灌插针",
        sprinklerZoneValve: "喷头区阀门",
        emptyZoneValve: "无消费者阀门",
        valveOutFitting: "阀门连接",
        dripZoneValve: "滴灌区阀门",
        rzwZoneValve: "根区灌溉阀门",
        pressureReg: "压力调节器",
        filter_pressureReg: "带压力调节器的过滤器",
        controller: "控制器",
        flowMeter: "流量计",
        rainSensor: "雨量传感器",
        soilSensor: "土壤传感器",
        freezeSensor: "冷冻传感器",
        wrFreezeSensor: "无线雨/冷冻传感器",
        windSensor: "风速传感器",
        solarSensor: "太阳能传感器",
        flowSensor: "流量传感器",
        weatherStation: "气象站",
        solarPanel: "太阳能板",
        mainPipe: "主管道",
        teeFitting: "三通",
        elbowFitting: "弯头",
        reducerFitting: "减径接头",
        lateralPipe: "支管",
        capFitting: "端帽",
        basicCable: "基本电缆",
        basicWire: "基本电线",
        sensorCable: "气象传感器线",
        qcPlastic: "塑料快速接头阀门",
        qcMetal: "金属快速接头阀门",
        gateway: "网关",
        antExt: "天线扩展",
        loramod: "LoRa 模块",
        //typesOfAcessories
        hdpeCOR: "波纹管",
        expModule: "扩展模块",
        rzwSleeve: "织物套",
        rwCap: "再生水盖",
        gutterMount: "水槽支架",
        delayRelay: "延迟继电器",
        fctFlow: "FCT 插座三通",
        fctBspAdap: "FCT 接头适配器",
        drainCheckValve: "止回阀",
        rwId: "再生水标识",
        vpc: "防破坏盖",
        inletFilter: "入口过滤器",
        wifiModule: "Wi-Fi 模块",
        wallMount: "墙面支架",
        rwsSock: "织物套",
        rwsGrate: "RWS 格栅",
        npCover: "非饮用水盖",
        sprExt: "喷雾扩展",
        popUpToThread: "喷雾适配器",
        valveBox: "阀门箱",
        valveBoxExt: "阀门箱扩展",
        qcPlasticKey: "快速接头阀门钥匙",
        qcPlasticElbFit: "弯头接头",
        qcMetalKey: "快速接头阀门钥匙",
        qcMetalElbFit: "弯头接头",
        qcMetalCapKey: "盖子钥匙",
        insTape: "绝缘胶带",
        wrConn: "连接器",
        shrinkTube: "热缩管",
        hcFrontPanel: "前面板",
        ball_valve: "球阀",
        check_valve: "止回阀",
        thread_manifold: "集管",
        plastic_filter: "过滤器（塑料）",
        waterMeter: "水表",
        rfModule: "无线模块",
        largeAntenna: "天线",
        wifiHub: "WiFi 集线器",
        handRemoteKit: "远程遥控套件",
        handRemote: "遥控器",
        wifiBundleKit: "WiFi 捆绑套件",
        //typesOfFittings
        //drip
        barb_cap_8: "滴灌端封",
        barb_elbow_PP: "管接头弯头",
        barb_elbow_PT: "管接头弯头至螺纹",
        barb_tee_PPP: "管接头三通",
        barb_coupling_PP: "管接头接头",
        barb_cross_PPPP: "管接头十字",
        barb_cap_P: "管接头端帽",
        barb_coupling_PT: "管接头接头至螺纹",
        barb_tee_PTP: "管接头三通至螺纹",
        barb_valve_PT: "管接头阀门至螺纹",
        barb_valve_PP: "管接头阀门",
        twlc_elbow_PP: "扭锁弯头",
        twlc_tee_PPP: "扭锁三通",
        twlc_coupling_PP: "扭锁接头",
        twlc_cross_PPPP: "扭锁十字",
        twlc_cap_P: "扭锁端帽",
        twlc_coupling_PT: "扭锁接头至螺纹",
        twlc_tee_PTP: "扭锁三通至螺纹",
        twlc_valve_PT: "扭锁阀门至螺纹",
        twlc_valve_PP: "扭锁阀门",
        dl_valves: "专用阀门",
        //pipe
        hdpeSDR9: "管 HDPE SDR 9",
        hdpeSDR11: "管 HDPE SDR 11",
        hdpeSDR136: "管 HDPE SDR 13.6",
        hdpeSDR17: "管 HDPE SDR 17",
        hdpeSDR176: "管 HDPE SDR 17.6",
        ldpeSDR9: "管 LDPE SDR 9",
        ldpeSDR11: "管 LDPE SDR 11",
        ldpeSDR136: "管 LDPE SDR 13.6",
        ldpeSDR17: "管 LDPE SDR 17",
        pvcSCH40: "管 PVC SCH40",
        pvcSCH80: "管 PVC SCH80",
        pvcCL315: "管 PVC CLASS 315",
        pvcCL200: "管 PVC CLASS 200",
        pvcCL160: "管 PVC CLASS 160",
        pvcCL125: "管 PVC CLASS 125",
        pvcUSCJPN18: "管 PVC-U SCJ (PN18)",
        pvcUSCJPN12: "管 PVC-U SCJ (PN12)",
        pvcUSCJPN9: "管 PVC-U SCJ (PN9)",
        pvcUSCJPN6: "管 PVC-U SCJ (PN6)",
        pvcUSCJPN45: "管 PVC-U SCJ (PN4.5)",
        ldpeCLASS3: "管 LDPE CLASS 3",
        compress_elbow_PT: "压缩/螺纹弯头",
        compress_coupling_PT: "压缩/螺纹接头",
        compress_tee_PTP: "压缩/螺纹三通",
        compress_cap_P: "压缩端塞",
        compress_elbow_PP: "压缩弯头",
        compress_coupling_PP: "压缩接头",
        compress_tee_PPP: "压缩三通",
        compress_cross_PPPP: "压缩十字",
        compress_single_clamp_saddle: "单夹鞍座",
        compress_ballvalve_PP: "压缩球阀",
        compress_ballvalve_PT: "压缩/螺纹球阀",
        customfit_elbow_PT: "定制/螺纹弯头",
        customfit_coupling_PT: "定制/螺纹接头",
        customfit_tee_PTP: "定制/螺纹三通",
        customfit_cap_P: "定制端塞",
        customfit_elbow_PP: "定制弯头",
        customfit_coupling_PP: "定制接头",
        customfit_tee_PPP: "定制三通",
        customfit_cross_PPPP: "定制十字",
        customfit_single_clamp_saddle: "单夹鞍座",
        customfit_ballvalve_PP: "定制球阀",
        customfit_ballvalve_PT: "定制/螺纹球阀",
        thread_nipple: "短接",
        thread_coupling: "接头",
        thread_mf_reducer: "公/母缩径",
        thread_mf_adapter: "公/母适配器",
        thread_mf_bush: "公/母衬套",
        thread_tee: "母三通",
        thread_elbow: "母弯头",
        thread_mf_elbow: "公/母弯头",
        thread_cap: "母端帽",
        thread_plug: "公端塞",
        thread_union_nut: "连接螺母",
        thread_cross: "十字接头",
        cable: "电缆",
        wire: "电线",
        // slip
        slip_single_clamp_saddle: "单夹鞍座（在PVC管上）",
        slip_elbow_PT: "滑动/螺纹弯头",
        slip_coupling_PT: "滑动/螺纹接头",
        slip_tee_PTP: "滑动/螺纹三通",
        slip_cap_P: "滑动端塞",
        slip_elbow_PP: "滑动弯头",
        slip_coupling_PP: "滑动接头",
        slip_tee_PPP: "滑动三通",
        slip_cross_PPPP: "滑动十字",
        slip_ballvalve_PP: "滑动球阀",
        slip_ballvalve_PT: "滑动/螺纹球阀",
        //extendables
        arbitraryFittings: "任意配件",
        dripStartAssembly: "滴灌起点组件",
        intakeAssembly: "进水组件",
        offtakeAssembly: "任意接取组件",
        numofvalves: "阀门数量: ",
        numofvalvesshort: "阀门: ",
        numofmanifs: "集管数量: ",
        intakePipeSize: "进水管尺寸: ",
        valveBoxes: "阀门箱",
        valveAccessories: "阀门配件",
        oneValveAccessories: "单个阀门配件",
        controllerAccessories: "控制器配件",
        sensorAccessories: "传感器配件",
        sprBodyAccessories: "喷雾体配件",
        rzwAccessories: "根区灌溉配件",
        pipeStartFittings: "主管道任意配件",
        qcAccessories: "快速接头阀门配件",
        wiringAccessories: "布线配件",
        pipeSize: "管道尺寸: ",
        endOfPipe: "（终点位置）",
        midOfPipe: "（中间切口）",
        emptyRender: [
            "对不起...没有解析内容",
            "你尚未完全完成任何灌溉节点的渲染"
        ],
        serviceFail: [
            "对不起... 规格渲染服务暂时不可用",
            "请稍后再试，当连接恢复时",
            "请注意，您之前的配置将被保存"
        ],
        serviceTrialExpired: [
            "对不起... 您的账户无法使用规格渲染服务",
            "这意味着您的试用期已结束，如果您想继续使用此服务",
            "<a href='/account/subscription'>您可以升级到PRO账户</a>"
        ],
        serviceLimitReached: [
            "您已达到每日规格表渲染限制",
            "要删除每日渲染规格表数量的限制",
            "<a href='/account/subscription'>您可以升级到PRO账户</a>"
        ],
        findInDrawing: "在画布上显示",
        // GROUP AND ELEMENTS IDS FOR LABOURS
        labours_group_pipes: "管道",
        labours_group_fittings: "配件",
        labours_group_valveBoxes: "阀门箱",
        labours_group_wires: "布线",
        labours_group_sprinklers: "喷头",
        labours_group_rws: "根区灌溉",
        labours_group_sprinklerConnections: "喷头连接",
        labours_group_drip: "滴灌管线和配件",
        labours_group_manifolds: "集管",
        labours_group_quickCoupling: "快速接头",
        labours_group_controllers: "控制器",
        labours_group_sensors: "传感器",
        labours_group_trenches: "沟槽",
        labours_group_insets: "管套",
        labours_group_lawns: "草坪",
        labours_group_irrigatedArea: "灌溉区域",
    },
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    //DIALOGER-------------------------------------------------------------
    //--------------------------------------------------------------------------
    //--------------------------------------------------------------------------
    dialoger: {
        MMMM: ["\x00", "一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
        MMM: ["\x01", "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
        dddd: ["\x02", "星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
        ddd: ["\x03", "周日", "周一", "周二", "周三", "周四", "周五", "周六"],
        //buttonsCaps
        ok: "确定",
        save: "保存",
        apply: "应用",
        defaults: "默认",
        retry: "重试",
        finish: "完成",
        safeRestart: "安全重启",
        saveAndExit: "保存并退出",
        exit: "退出",
        cancel: "取消",
        rename: "重命名",
        idk: "我不知道",
        getFile: "获取文件",
        reset: "重置",
        random: "随机",
        //misc
        zoneNum: "区域 #",
        valveNum: "阀箱 #",
        zonesColoring: "区域表示",
        coversColoured: "喷头覆盖区上色",
        dripsColoring: "滴灌管线着色",
        dripsSameAsZonesColored: "滴灌管线与区域颜色相同",
        //saveOffline
        saveOffline: [
            "对不起...连接丢失",
            "但别担心，你可以在离线模式下继续进行项目。",
            "当你离线时 - 所有保存的内容将以文本文件的形式存储在浏览器的下载文件夹中。",
            "稍后你可以将最新版本的图纸上传到服务器。"
        ],
        restartOffline: [
            "对不起...连接丢失",
            "但别担心，你的项目已保存在本地计算机。",
            "你可以在浏览器的下载文件夹中找到它。",
            "如果你想离线工作，可以从你的控制台下载离线版应用程序，网址为 http://www.irrisketch.com"
        ],
        brokenSaving: [
            "对不起...加载项目时出错",
            "看起来你之前的保存文件被损坏了。",
            "但别担心，我们可以修复它。",
            "你的项目现在将标记为 '损坏'，显示在你的工作区中。",
            "我们的技术团队将尽快处理这种情况。"
        ],
        corruptedSavingFile: [
            "对不起...你尝试加载的文件不可读",
            "但别担心，我们可以修复它。",
            "你只需要将这个损坏的文件提交到你的工作区文件加载表单中。",
            "然后我们会尝试恢复工作。"
        ],
        ajaxReqFail: [
            "对不起...我们失去了与服务器的连接",
            "目前无法发送/接收任何数据",
            "请稍后再试"
        ],
        critical: [
            "对不起...发生了一些错误",
            "但别担心，你的图纸现在安全了，只需点击安全重启按钮继续..."
        ],
        fatal: [
            "对不起...发生了一些错误",
            "请帮助我们改进我们的服务。请描述在发生错误时的用户操作",
            "在此处提供信息"
        ],
        areYouSure: [
            "你将关闭此项目",
            "请注意，所有未保存的更改将会丢失。"
        ],
        pickAnotherCSVFile: "选择另一个文件",
        csvFileTooBig: [
            "超过了最大的CSV文件大小",
            "为优化目的，最大CSV文件处理限制为4Mb"
        ],
        notAnCSV: [
            "对不起，不支持此文件类型",
            "支持的格式：.csv"
        ],
        pickAnotherImage: "选择另一个图片",
        imageTooBig: [
            "超过了最大的图片大小",
            "为优化目的，最大图片处理限制为10Mb"
        ],
        notAnImage: [
            "对不起，不支持此文件类型",
            "支持的图片格式：.pdf, .png, .jpg, .jpeg, .tiff, .gif, .bmp"
        ],
        goProTexts: [
            "操作已受限",
            "此操作不允许用于免费订阅"
        ],
        goPro: '升级到专业版',
        renameLayout: "输入新名称",
        areYouSureDeleteLayout: [
            "注意！此操作无法撤销",
            "你确定要删除：",
            "删除"
        ],
        setUnderlaySize: [
            "设置你刚刚绘制的线条长度",
            "你输入了错误的值，请重试"
        ],
        setMonitorDiagonal: [
            "请提供有关你的显示器对角线尺寸的信息",
            "你输入了错误的值，请重试"
        ],
        getSpecsTable: [
            "设置规格输出首选项",
            "按以下内容分组设备",
            "节点", "品牌",
            "设置文件类型为",
            "XLSX", "ODS"
        ],
        saveSpecsVariant: [
            "输入标题",
            "布局 #",
            "保存",
            "保存规格",
            "已完成。点击此处打开",
            "保存失败",
            "更新现有布局",
            "更新",
            "正在更新布局"
        ],
        exportLayoutsAsPdf: [
            "选择要导出的布局",
            "单独文件（正在开发）",
            "一个相册",
            "导出",
            "导出布局为"
        ],
        differentSprGroups: [
            "无法在此管道上连接不同类型的用水设备",
            "根据灌溉设计标准，在同一区域内混合不同类型的用水设备或喷头具有不同降水率是不允许的"
        ],
        tooFarAwaySpr: [
            "无法连接消费者",
            "某些消费者离支管太远无法连接。你可以在首选项菜单中配置最大连接距离"
        ],
        outlayerConfig: [
            "规格表配置"
        ],
        presetsMenu: {
            title: "预设",
            titleTextboxLabel: "预设标题",
            descriptionTextboxLabel: "描述",
            applyButton: "<i class='far fa-check-circle'></i>&nbsp;应用",
            defaultButton: "<i class='far fa-undo'></i>&nbsp;设为默认",
            removeButton: "<i class='far fa-trash'></i>&nbsp;移除",
            updateButton: "<i class='far fa-sync'></i>&nbsp;更新",
            createButton: "<i class='far fa-plus'></i>&nbsp;创建新的",
            closeButton: "<i class='far fa-times'></i>&nbsp;关闭",
            favorites_drawing: "最喜欢的工具（景观）",
            favorites_sprinkling: "最喜欢的工具（灌溉）",
            favorites_layouting: "最喜欢的工具（布局）",
            configs_drawing: "项目配置",
            configs_outlayer: "规格表配置"
        },
        newPresetItem: "新预设",
        cL_alreadyConnected: [
            "无法连接线条",
            "这些线条都已连接到"
        ],
        cL_segOnElem: [
            "无法连接线条",
            "你不能连接到在"
        ],
        cL_strangeError: [
            "无法连接线条",
            "抱歉...连接失败"
        ],
        cL_misgrouping: [
            "无法连接线条",
            "这些线条有一些消费者不建议放在同一区域。如果你仍然想连接它们，请在项目配置中启用“非安全模式”以分组喷头"
        ],
        cL_valve: "阀门集管",
        cL_waterSource: "水源",
        cL_dripStart: "滴灌起点",
        cL_controller: "控制器",
        cL_sensors: "传感器",
        cL_valves: "阀门集管",
        cL_notSameVariant: [
            "无法连接线条",
            "这些线条有不同类型",
            "当前绘制线条的类型",
            "你想要连接的线条类型"
        ],
        hasRestorableProject: [
            "此项目有未保存的数据",
            "你可以从拍摄于以下时间的快照中恢复未保存的状态"
        ],
        restoreProject: "恢复",
        imageLost: [
            "对不起，我们无法在服务器上找到一些底图",
            "找不到的图片："
        ],
        precipCalcError_mixedError: [
            "降水量地图错误",
            "无法为以下组合的喷头构建降水量地图："
        ],
        precipCalcError_mprNonMprRot: "不能混合普通转子和带有MPR喷嘴的转子",
        precipCalcError_mprNozNonMprRot: "不能混合MPR喷嘴和普通转子",
        precipCalcError_staticNozRot: "不能混合静态喷嘴和转子",
        precipCalcError_staticMprNoz: "不能混合静态喷嘴和MPR喷嘴",
        precipCalcError_missingError: [
            "降水量地图错误",
            "缺少喷头的降水量配置："
        ],
        precipCalcError_zoningError: [
            "降水量地图分区错误",
            "无法为以下组合的喷头构建降水量地图："
        ],
        precipCalcError_noZoneAndZone: "无法同时计算连接和未连接转子的降水量。运行时间未知，因此转子旋转的次数不确定",
        algoNozzler_noSolutions: [
            "未找到可能的喷头布置解决方案",
            "请尝试以下操作：",
            "1. 更改自动布置工具配置菜单中的重叠限制和其他选项",
            "2. 选择其他类型的喷头，它们可能在布置上提供更大的灵活性",
            "3. 使用下方按钮重新启动，并使用更“松散”的重叠和覆盖限制"
        ],
        retryWithLooseOptions: "使用“松散”选项重试",
        cannotSaveBecauseOffline: [
            "请求发送到服务器失败",
            "与服务器没有连接",
            "检查你的互联网连接",
            "为了不丢失数据，不要关闭此窗口，稍后在与服务器建立连接时再尝试保存数据",
            ""
        ],
        cannotSaveBecauseTooManyFails: [
            "请求保存失败",
            "无效代码尝试次数过多",
            "检查你是否正确输入了电子邮件地址，30秒后再试。",
            "",
            ""
        ],
        cannotSaveBecauseNoMailProvided: [
            "请求保存失败",
            "电子邮件地址输入错误",
            "检查你是否正确输入了电子邮件地址并重试",
            "",
            ""
        ],
        designRequestCompleted: [
            "你的请求已成功创建/更新",
            "编辑链接", "复制我",
            "查看链接", "复制我"
        ],
        designRequestContacts: [
            "联系信息",
            "组织",
            "名称",
            "电子邮件",
            "电话",
            "地址",
            "网站"
        ],
        designRequestInfo: [
            "欢迎来到设计工作室！",
            "在这里，你可以轻松快速地创建灌溉系统的规划请求。",
            "你可以在<a target='_blank' href='https://youtu.be/OHmm0Jb6EaY'>这里找到说明视频</a>",
            "如需进一步信息或有任何问题，请随时联系我们。"
        ],
        approveActionByCode: [
            "确认操作",
            "确认码的电子邮件已发送到你提供的电子邮件地址。",
            "请在下面的字段中输入此代码",
            "你输入了无效的数字，请重试"
        ],
        revisionCheckFailedSoft: [
            "修订冲突！",
            "该项目当前在另一个浏览器或设备上打开。",
            "你可以通过点击`覆盖`来覆盖服务器上的数据（因为我们只存储一个版本的项目），但要小心——在其他会话中所做的所有进展将会丢失！",
            "更好的策略是了解项目在何处和由谁打开，并决定哪个版本是最新的。",
            "如果你想控制这个同时打开的项目的最新版本，可以通过在浏览器中复制此标签再次打开项目。"
        ],
        revisionBlocked: [
            "保存被管理员阻止！",
            "目前你的项目由于发生错误，正在由我们的技术人员审核。",
            "请等待审核完成，随后你将收到电子邮件通知进一步的操作说明。"
        ],
        missingVariants: [
            '缺少元素错误',
            '以下是自定义元素列表，这些元素在您的项目库中缺失，因此无法渲染：',
            '请在项目配置菜单（在工作坊）中启用包含这些元素的集合'
        ],
        openInOtherTab: "打开最新",
        overwrite: "覆盖",
        saveToFile: "保存到文件",
        filterSelection_exclude: "从选择中排除",
        filterSelection_include: "包含到选择中",
        filterSelectionNames: {
            sprinklers: "消费者",
            sprinklers_nozzle: "消费者 - 喷嘴",
            sprinklers_rotaryNozzle: "消费者 - 旋转喷嘴",
            sprinklers_rotor: "消费者 - 转子",
            sprinklers_bubbler: "消费者 - 涌泉",
            sprinklers_bubblerNozzle: "消费者 - 涌泉喷嘴",
            dripStarts: "滴灌起点",
            rzwLayer: "根区灌溉",
            dripLines: "滴灌管线",
            valvesLayer: "阀门集管",
            waterSources: "水源",
            controllers: "控制器",
            sensorsLayer: "传感器",
            mainPipes: "主管道",
            lateralPipes: "支管",
            trenchesLayer: "沟槽",
            insetsLayer: "嵌入物",
            wiresLayer: "布线",
            wirelessLayer: "无线连接",
            senswiresLayer: "无线传感器连接",
            senswiresLayer: "传感器布线",
            quickCoupLayer: "快速接头",
            surfaces: "多边形和线条",
            ldItemsLayer: "景观物品"
        },
        //SPRINKLER NODE CONFIGS
        sprinklerNode: "喷头节点",
        fcType: "喷头连接类型",
        sj: "摆动接头",
        sprinklerStand: "喷头支架（升降器）",
        flexPipeBarbs: "柔性管 + 倒钩接头",
        minFlexPipeLength: "每个连接的柔性管最小长度",
        midSprinkPipeFitting: "中间连接件",
        endSprinkPipeFitting: "端管连接件",
        single_clamp_saddle: "夹式鞍座",
        tee_PTP: "带有BSP内螺纹的三通",
        elbow_PT: "带有BSP内螺纹的弯头",
        coupling_PT: "带有BSP内螺纹的适配器",
        //MANIFOLD NODE CONFIGS
        manifoldNode: "集管节点",
        valvesOutlay: "阀门布置",
        fold: "折叠",
        unfold: "展开",
        threadsNode: "螺纹连接",
        threadTypes: "螺纹类型",
        //AUTOMATION NODE CONFIGS
        automationNode: "自动化节点",
        controllerModules: "选择的模块化控制器扩展模块：",
        controllerVoltage: "控制器的输入电压：",
        controllerVoltageV2: "控制器的输入电压：",
        230: "230 伏交流电",
        "230A": "230 伏交流电（澳大利亚）",
        120: "120 伏交流电",
        24: "24 伏交流电",
        autoModules: "自动（最佳适配）",
        userModules: "手动（作为配件）",
        //RZW NODE
        rzwNode: "根区灌溉节点",
        midRZWPipeFitting: "中间连接件",
        endRZWPipeFitting: "端管连接件",
        //DRIP node
        dripNode: "滴灌",
        dripConnectionType: "滴灌连接类型",
        dripLengthPrecision: "管长度的小数位数",
        dripTubingAddon: "滴灌管添加物",
        barb: "倒钩接头",
        twistLock: "扭锁接头",
        dripSpikesStep: "滴灌管支架钉间距",
        dripCrossFittingAble: "允许十字接头",
        pipesNode: "管道部分",
        hdpeConnectionType: "HDPE接头类型",
        ldpeConnectionType: "LDPE接头类型",
        pvcConnectionType: "PVC接头类型",
        pipeAddon: "每种直径的管道添加物",
        pipeLengthPrecision: "管道长度的小数位数",
        crossFittingAble: "允许十字接头",
        compress: "压缩接头",
        customfit: "定制接头",
        slip: "滑动接头",
        wiringNode: "布线部分",
        exportNode: "导出选项",
        exportNumbersPrecision: "数字的小数位数",
        basicWiringMethod: "控制布线方法",
        cableCoresArray: "电缆芯数范围",
        noAutoWiring: "手动添加布线",
        separateCableToManifold: "多芯电缆独立到集管",
        separateWireToValve: "独立的电线到阀门 + 公共线到集管",
        maxCableCores: "最大电缆芯数",
        verticalWiringAddon: "控制器线的垂直添加物",
        verticalSensWiringAddon: "传感器线的垂直添加物",
        wireAddon: "每种类型的电线添加物",
        wireLengthPrecision: "布线长度的小数位数",
        //DRAWER CONFIG
        drawerConfig: [
            "项目配置"
        ],
        //SPRINKLER PRESSURE CONFIGS
        sprinklerConfig: "消费者",
        pressureDefinedBy: "消费者预期的压力是",
        allowReduceRotors: "允许减少转子半径",
        autoconnector: "喷头与侧管道的互动连接",
        radio_option_yes: "是（由供应商推荐）",
        radio_option_no: "否",
        extreme_rotor_reduction: "极端（最多减少50%）（可能导致降水不均匀）",
        radio_option_yes2: "是",
        takeReductionInAccountWhenAutoPlacing: "在放置喷头时考虑减少的抛射距离",
        takeReductionInAccountWhenAutoPlacingForRotors: "在放置喷头时考虑减少的抛射距离 (Rotors)",
        recommendedPressure: "供应商推荐",
        userPressure: "用户设定",
        expPressure: "消费者预期的压力",
        sprinklerGroupMode: "消费者分组",
        safeSprGroupMode: "严格模式（仅分组兼容）",
        unsafeSprGroupMode: "不安全模式（警告！没有分组限制）",
        "sprinklerAttachBulkMode": "批量消费者连接模式",
        "safeSprAttachMode": "不重新连接已连接的消费者",
        "unsafeSprAttachMode": "不安全模式（警告！可能重新连接已连接的消费者。使用时请自行承担风险）",
        //UNITS CONFIG
        unitsConfig: "计量单位",
        precisionStd: "小数点后的位数",
        unitsSystemGridAndRuler: "网格和尺子的测量系统单位",
        distanceUnits: "距离",
        distancePrecision: "小数点后的位数",
        sprinklerDistUnits: "喷头半径",
        sprinklerDistPrecision: "小数点后的位数",
        areaUnits: "面积",
        areaPrecision: "小数点后的位数",
        volumeUnits: "体积",
        volumePrecision: "小数点后的位数",
        waterFlowUnits: "水流量",
        waterFlowPrecision: "小数点后的位数",
        pressureUnits: "压力",
        pressurePrecision: "小数点后的位数",
        velocityUnits: "速度",
        velocityPrecision: "小数点后的位数",
        precipRateUnits: "降水率",
        precipRatePrecision: "小数点后的位数",
        // ZONE PROPS CONFIG
        climateConfig: "灌溉时间计算",
        lawnCultureType: "草坪类型",
        coolLoving: "冷爱",
        warmLoving: "温暖爱",
        climateTemp: "夏季平均温度",
        coolClimate: "< 21°C",
        warmClimate: "21-32°C",
        hotClimate: "> 32°C",
        climateHumid: "夏季平均湿度",
        wetClimate: "> 50%",
        dryClimate: "< 50%",
        microClimate: "区域微气候&nbsp;<i class='far fa-question-circle'></i>",
        microClimateTooltip: "温和\n" +
            "灌溉区域处于阴影处，避风，远离干燥和加热的物体\n" +
            "\n" +
            "正常\n" +
            "在景观中，微气候条件的存在：建筑物、人行道和小路、阴影等对蒸散量的影响不显著\n" +
            "\n" +
            "恶劣\n" +
            "反映了妨碍植物生长的条件，如果没有适当的灌溉，植物很容易进入压力状态。这可能是一个开放的地方，阳光直射，靠近路径、建筑物或其他吸热的景观结构，或者它可能是一个风大的地方。",
        //
        //
        gentleMicroClimate: "温和",
        normalMicroClimate: "正常",
        toughMicroClimate: "恶劣",
        soilType: "区域内的土壤组成",
        sand: "沙质土",
        sandyLoam: "沙壤土",
        lightLoam: "轻壤土",
        mediumLoam: "中壤土",
        heavyLoam: "重壤土",
        clay: "粘土",
        heavyClay: "重粘土",
        zoneSlope: "区域的总体坡度",
        noneIncline: "0-5% (0-3°)",
        lightIncline: "5-8% (3-5°)",
        mediumIncline: "8-12% (5-7°)",
        hugeIncline: "12%+ (7°+)",
        waterBudget: "水预算",
        lowWB: "低",
        normalWB: "正常",
        highWB: "高",
        ft: "英尺",
        in: "英寸",
        ftin: "英尺/英寸",
        metric: "公制",
        imperialUS: "英制（美国）",
        //UNITS CONFIG
        hydraConfig: "水力学",
        waterTemp: "水温",
        maxFlowVelocity: "管道中的最大流速",
        commonConfig: "常用设置",
        lateralNozzlerSwitch: "如何切换到喷嘴连接模式",
        NStabonly: "Tab键",
        NStabshift: "Tab+Shift键",
        showActionSubtitles: "显示操作字幕",
        Yeah: "是",
        Nope: "否",
        start: "开始",
        recalibrate: "重新校准",
        calibrationSuccess: [
            "校准成功",
            "现在你可以在两种模式下使用触摸屏 - '移动光标'（轻触移动）和 '拖动模式'（用力触摸移动）"
        ],
        calibrationFailEqual: [
            "校准失败",
            "我们没有检测到你在两种模式下触摸屏幕的方式有很大差异",
            "你可以再试一次。并确保你在使用手指而不是触控笔"
        ],
        calibrationFailImproper: [
            "校准失败",
            "我们检测到羽毛上的压力大于铁砧上的压力",
            "你可以再试一次。并确保你移动羽毛时施加的压力比铁砧小"
        ],
        calibrationImpossible: [
            "校准不可能",
            "似乎你的设备不支持触摸面积测量。因此我们无法定义两种触摸交互模式",
            "在这种情况下，你可以使用虚拟鼠标来拖动任何东西。它将出现在屏幕的左侧。"
        ],
        calibrationNeeded: [
            "需要校准！",
            "我们必须校准你的触摸屏，以便定义两种触摸交互模式：",
            "移动光标模式 - 当你只想在绘图时移动光标或多边形段时",
            "拖动模式 - 当你想要移动或调整大小时使用。你还应该在选择多个项目时拖动移动",
            "请点击开始按钮并按照屏幕上的说明进行操作"
        ],
        insertImage: '插入',
        mapImagePicker: [
            "卫星图像加载器",
            "纬度/经度",
            "输入纬度",
            "输入经度",
            "当前位置",
            "前往",
            "地址",
            "输入部分地址并点击'搜索'",
            "搜索",
            "缩放",
            "平移"
        ],
        "imageCrop": [
            "裁剪工具"
        ],
        cropImage: "裁剪",
        invalid_dataset_1: '无效的数据集。项目包含禁止的表面类型。仅允许灌溉（草坪）、非灌溉和障碍物。',
        invalid_dataset_2: '无效的数据集。不允许有一个以上或一个以下的灌溉表面。',
        invalid_dataset_3: '无效的数据集。灌溉表面自相交。',
        invalid_dataset_4: '无效的数据集。障碍标记不应是复合的（由多个多边形组成）',
        invalid_dataset_5: '无效的数据集。障碍表面应完全包含在灌溉表面内。',
        invalid_dataset_6: '无效的数据集。项目包含禁止的喷头类型。允许：',
        invalid_dataset_7: '无效的数据集。喷头的降水率超出范围',
        invalid_dataset_8: '无效的数据集。喷头不应有单独的压力设置',
        invalid_dataset_9: '无效的数据集。项目不应设置喷头的自定义预期压力',
        invalid_dataset_10: '无效的数据集。均匀度太低。',
        invalid_dataset_11: '无效的数据集。过度灌溉区域太大。'
    }
};
